### ISSUE TITLE
温控器调节风速时会自动打开送风

### ISSUE THREAD

**Issue by ProjectA31** [al-one/hass-xiaomi-miot#1011]
在温控器关闭情况下，调节风速会自动开启送风模式。看代码是有意这么做的，但是风速和模式是两个不相关的设置，不需要联动。多数温控器是可以在关闭模式下调整风速的吧？

目前这么做的话在某些情况下会带来问题，比如我想设置自动化，每天定时 21 点风速调为低速，早上 8 点设为高速。但是我不需要自动开启送风。我会在需要的时候手动开启制冷或者制热。

**Comment by al-one** [comment]
https://github.com/al-one/hass-xiaomi-miot/blob/cc6704b951830feaccd5e693799dbcc6ab90ddc3/custom_components/xiaomi_miot/climate.py#L575-L581

HA的homekit集成不支持在iOS家庭中开启送风模式，这样可以在iOS家庭中通过温控器的风速控件开启送风模式。
如果你想单独控制风速，可以使用[`xiaomi_miot.set_property`](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.set_property)服务。

**Comment by ProjectA31** [comment]
谢谢，用属性 thermostat.fan_level 设置成功
