### ISSUE TITLE
LED indicator switch is missing for Air Purifier 4 (zhimi.airp.mb5a)

### ISSUE THREAD

**Issue by dawiinci** [al-one/hass-xiaomi-miot#1012]
Unfortunately I can't switch off the LED, which I like to do at night. The switch is missing in Home Assistant.

It is a new [Air Purifier 4 (zhimi.airp.mb5a)](https://home.miot-spec.com/s/zhimi.airp.mb5a). Everything else works though.

Switches for LED indicators are available with zhimi.airpurifier.vb2 and zhimi.airpurifier.mb3 but **not** with zhimi.airp.mb5a.

**Comment by al-one** [comment]
Try master branch.

**Comment by dawiinci** [comment]
It works. Thanks for the quick fix.
