### ISSUE TITLE
能否添加烟感卫士的支持

### ISSUE THREAD

**Issue by tankpro** [al-one/hass-xiaomi-miot#103]
lumi.sensor_smoke.mcn02

**Comment by al-one** [comment]
未找到该型号对应的urn

https://miot-spec.org/miot-spec-v2/instances?status=all

**Comment by tankpro** [comment]
{
        "did": "blt.3.16t361a44lg00",
        "token": "XXX",
        "longitude": "0.00000000",
        "latitude": "0.00000000",
        "name": "小米烟感卫士",
        "pid": "6",
        "localip": "",
        "mac": "XX",
        "ssid": "",
        "bssid": "",
        "parent_id": "",
        "parent_model": "",
        "show_mode": 1,
        "model": "lumi.sensor_smoke.mcn02",
        "adminFlag": 1,
        "shareFlag": 0,
        "permitLevel": 16,
        "isOnline": true,
        "desc": "设备在线 ",
        "extra": {
          "isSetPincode": 0,
          "pincodeType": 0,
          "fw_version": "1.1.1_0010",
          "needVerifyCode": 0,
          "isPasswordEncrypt": 0
        },
        "uid": XX,
        "pd_id": 2455,
        "password": "",
        "p2p_id": "",
        "rssi": 0,
        "family_id": 0,
        "reset_flag": 0
      },

**Comment by al-one** [comment]
https://miot-spec.org/miot-spec-v2/instances?status=all

上面的网址打开后找不到型号`lumi.sensor_smoke.mcn02`，因此无法支持。

**Comment by tankpro** [comment]
需要等待官方把产品加到miot-spec支持列表吗

**Comment by al-one** [comment]
是的
