### ISSUE TITLE
是否可以增加雷士智能吸顶灯（智臻款）适配本地接入leishi.light.wy0c02

### ISSUE THREAD

**Issue by WalterDSU** [al-one/hass-xiaomi-miot#1030]
### Device model / 设备型号

[leishi.light.wy0c02](https://home.miot-spec.com/s/leishi.light.wy0c02)

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

群主是都可以搞成本地接入.

### Entity attributes / 实体属性

Attributes
Model
leishi.light.wy0c02
Lan IP
192.168.8.17
MAC address
B4:60:ED:1F:7B:4C
Entity class
MiotLightEntity
Home room
W@lter的家 主人房
Miot type
urn:miot-spec-v2:device:light:0000A001:leishi-wy0c02:2:0000C802
Light.on
false
Light.brightness
100
Light.color temperature
4,700
Light.mode
0
Light.flex switch
false
Default
0
Default.user save.error
-704030013 Property is not readable
Scens.on off.error
-704030013 Property is not readable
Scens.brightness add.error
-704030013 Property is not readable
Scens.brightness dec.error
-704030013 Property is not readable
Scens.brightness switch.error
-704030013 Property is not readable
Scens.on brightness switch.error
-704030013 Property is not readable
Scens.color temperatureadd.error
-704030013 Property is not readable
Scens.color temperaturedec.error
-704030013 Property is not readable
Scens.color temp switch.error
-704030013 Property is not readable
Scens.on or colortemp.error
-704030013 Property is not readable
State updater
cloud

**Comment by WalterDSU** [comment]
我是直接选择自动模式接入的, 然后发现是云端的. 我查过不在你的本地设备清单里面. 以为还没有适配. 按你所说的, 是不是,你后面更新到本地名单里面, 自动模式就会更新为本地接入???

**Comment by al-one** [comment]
你用token接入确认没问题后我再加入本地设备列表。

**Comment by al-one** [comment]
配置-系统-日志

**Comment by WalterDSU** [comment]
This error originated from a custom integration.

Logger: custom_components.xiaomi_miot.light
Source: custom_components/xiaomi_miot/__init__.py:1374
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 12:54:43 (67 occurrences)
Last logged: 13:28:01

衣帽(leishi.light.wy0c02): Got MiioException while fetching the state: Unable to discover the device 192.168.8.17, mapping: {'light.on': {'siid': 2, 'piid': 1}, 'light.brightness': {'siid': 2, 'piid': 2}, 'light.color_temperature': {'siid': 2, 'piid': 3}, 'light.mode': {'siid': 2, 'piid': 5}, 'light.flex_switch': {'siid': 2, 'piid': 6}, 'default': {'siid': 4, 'piid': 1}, 'default.user_save': {'siid': 4, 'piid': 2}, 'scens.on_off': {'siid': 3, 'piid': 1}, 'scens.brightness_add': {'siid': 3, 'piid': 2}, 'scens.brightness_dec': {'siid': 3, 'piid': 3}, 'scens.brightness_switch': {'siid': 3, 'piid': 4}, 'scens.on_brightness_switch': {'siid': 3, 'piid': 5}, 'scens.color_temperatureadd': {'siid': 3, 'piid': 6}, 'scens.color_temperaturedec': {'siid': 3, 'piid': 7}, 'scens.color_temp_switch': {'siid': 3, 'piid': 8}, 'scens.on_or_colortemp': {'siid': 3, 'piid': 9}}, max_properties: 8/16

**Comment by al-one** [comment]
`192.168.8.17`是当前该设备的正确IP吗？且HA的IP是否也是`192.168.8.xxx`相同网段？

**Comment by WalterDSU** [comment]
在米家能正常操作啊. 另外, token之后, 灯一直自己不停地关了又开. 直到直接在HA删除设备.

**Comment by al-one** [comment]
添加以下配置后再次尝试token接入。
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    leishi.light.wy0c02:
      exclude_miot_services: default,scens
```

**Comment by WalterDSU** [comment]
可以了. 一切正常. 看来是不支持默认的scens,对吗?

**Comment by al-one** [comment]
![leishi.light.wy0c02 spec](https://user-images.githubusercontent.com/4549099/220284393-249d15bc-b92c-417e-8168-af576a94132d.png)

`scens`服务下的属性均没有读取权限，因此可能是在读取这些属性的时候造成设备固件重启。

**Comment by WalterDSU** [comment]
明白, 群主可以close了.

**Comment by al-one** [comment]
再次尝试下这个配置：
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    leishi.light.wy0c02:
      exclude_miot_services: scens
      exclude_miot_properties: user_save
      select_properties: default
```

**Comment by WalterDSU** [comment]
能正常使用. 而且, 还多了一个默认设置选择.
![image](https://user-images.githubusercontent.com/91654066/220820467-98667b54-a25f-4f3a-8071-6333f1ef4802.png)
![image](https://user-images.githubusercontent.com/91654066/220820492-3dcabbd8-404b-4ec9-b550-68e6699e5d2e.png)
