### ISSUE TITLE
zimi.mosq.v1 Mosquito dispeller state problem 

### ISSUE THREAD

**Issue by kodbuzz** [al-one/hass-xiaomi-miot#1033]
Hello, 

I got few zimi.mosq.v1 mosquito dispellers, although the product appears to be uncontrollable through the integration, but it was good to be able to check on its status anyway, but unfortunately the state detection has been acting abnormal since earlier this year. Despite the device is powered off, it shows up as 'on' in this integration, causing a great deal of frustration. 

I personally suspect that this issue may be related to https://github.com/al-one/hass-xiaomi-miot/issues/942

I really appreciate all the hard work you've put into this project and the time you're taking to address the issue. Thank you in advance for your efforts!

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/984#issuecomment-1415061483
