### ISSUE TITLE
Yeelight Led  Ceiling light 320 PRO

### ISSUE THREAD

**Issue by zigajamnik** [al-one/hass-xiaomi-miot#1039]
### Device model / 设备型号

[yeelink.light.ceila](https://home.miot-spec.com/s/yeelink.light.ceila)

### Component version / 插件版本

0.7.5

### HA core version / HA版本

 2023.2.5

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

After i've (unfortunately) updated this light via yeelight app to v2.1.7_0011, the light went unavaliable in home assistant. I've tried re-adding, renaming and re-adding and everything. but it's always disconnected in HA :( 
It also seems when HA is trying to connect to the light, light quickly turn off and back on. 
The light is avaliable in yeelight app and also in xiaomi home app. It worked flawlessly in Home Assistant before the update.

### Entity attributes / 实体属性

/

### Home Assistant Logs / 系统日志

kuhinjaX2(yeelink.light.ceila): Got MiioException while fetching the state: Unable to discover the device 192.168.1.144, mapping: {'light.on': {'siid': 2, 'piid': 1}, 'light.mode': {'siid': 2, 'piid': 2}, 'light.brightness': {'siid': 2, 'piid': 3}, 'light.color_temperature': {'siid': 2, 'piid': 5}, 'yeelight.init_power_opt': {'siid': 4, 'piid': 1}, 'yeelight.save_state': {'siid': 4, 'piid': 2}, 'yeelight.cron_add': {'siid': 4, 'piid': 3}, 'yeelight.cron_del': {'siid': 4, 'piid': 4}, 'yeelight.cron_get': {'siid': 4, 'piid': 5}, 'yeelight.night_time': {'siid': 4, 'piid': 6}, 'yeelight.set_scene': {'siid': 4, 'piid': 7}, 'yeelight.set_adjust': {'siid': 4, 'piid': 8}, 'yeelight.set_ps': {'siid': 4, 'piid': 9}, 'yeelight.flow_param': {'siid': 4, 'piid': 10}, 'yeelight.brightness_delta': {'siid': 4, 'piid': 11}, 'yeelight.ct_delta': {'siid': 4, 'piid': 12}, 'yeelight.ct_adjust_alexa': {'siid': 4, 'piid': 13}, 'yeelight.brightness_with_zero': {'siid': 4, 'piid': 14}}, max_properties: 9/18

**Comment by al-one** [comment]
Please try unplugging the device, if it still doesn't work, add this custom option: `exclude_miot_services: yeelight`

![xiaomi miot customize](https://user-images.githubusercontent.com/4549099/222052428-86bcd4d6-bb10-40dc-bb95-9548723f78f1.png)

https://user-images.githubusercontent.com/4549099/211185592-79daa90d-c5cb-4c9e-829c-12a52fa3eaf0.mp4

**Comment by zigajamnik** [comment]
Unplugging doesn't work. I've reset the light several times ( 5x unplug and plug back ). Will this exclude_miot_services: yeelight also apply on other yeelights? Because I have several in my appartment. Also several of the same type.

**Comment by al-one** [comment]
`exclude_miot_services: yeelight` only works on `yeelink.light.ceila`, and does it work after you custom ?

**Comment by zigajamnik** [comment]
I haven't tried it yet. I wanted to ask you if it will also affect other lights of this type in my appartment? Because I have several lights (which work without problem) and are also yeelink.light.ceila.
![image](https://user-images.githubusercontent.com/27785913/222066440-76abff8a-54de-4a2b-add4-48c241d231d6.png)

**Comment by al-one** [comment]
![xiaomi miot config flow](https://user-images.githubusercontent.com/4549099/222076371-b23c5208-c2e3-4163-8d5e-10721aa88408.png)

- `Customizing entity (自定义实体)` valid for a single device
- `Customizing device (自定义设备)` valid for all devices of the same model

**Comment by zigajamnik** [comment]
thanks! Will try that out and will report.

**Comment by zigajamnik** [comment]
First of all - I have many duplicated entities? How can I delete these? it's probably because i've added them multiple times?

![image](https://user-images.githubusercontent.com/27785913/222085572-1792a868-7ce5-4335-baef-e7923c5fe94e.png)

**Comment by al-one** [comment]
Integrate it by token or account ?

**Comment by zigajamnik** [comment]
By account

**Comment by zigajamnik** [comment]
I deleted it and tried to add it again (this time by token) and i get this: 
![image](https://user-images.githubusercontent.com/27785913/222131856-dcae4c85-d068-4182-8493-04b4f5628824.png)

**Comment by al-one** [comment]
[Logs](https://my.home-assistant.io/redirect/logs)

**Comment by zigajamnik** [comment]
Logger: custom_components.xiaomi_miot.light
Source: custom_components/xiaomi_miot/__init__.py:1374
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 16:09:37 (13 occurrences)
Last logged: 16:10:07

kuhinjaX2(yeelink.light.ceila): Got MiioException while fetching the state: Unable to discover the device 192.168.1.144, mapping: {'light.on': {'siid': 2, 'piid': 1}, 'light.mode': {'siid': 2, 'piid': 2}, 'light.brightness': {'siid': 2, 'piid': 3}, 'light.color_temperature': {'siid': 2, 'piid': 5}, 'yeelight.init_power_opt': {'siid': 4, 'piid': 1}, 'yeelight.save_state': {'siid': 4, 'piid': 2}, 'yeelight.cron_add': {'siid': 4, 'piid': 3}, 'yeelight.cron_del': {'siid': 4, 'piid': 4}, 'yeelight.cron_get': {'siid': 4, 'piid': 5}, 'yeelight.night_time': {'siid': 4, 'piid': 6}, 'yeelight.set_scene': {'siid': 4, 'piid': 7}, 'yeelight.set_adjust': {'siid': 4, 'piid': 8}, 'yeelight.set_ps': {'siid': 4, 'piid': 9}, 'yeelight.flow_param': {'siid': 4, 'piid': 10}, 'yeelight.brightness_delta': {'siid': 4, 'piid': 11}, 'yeelight.ct_delta': {'siid': 4, 'piid': 12}, 'yeelight.ct_adjust_alexa': {'siid': 4, 'piid': 13}, 'yeelight.brightness_with_zero': {'siid': 4, 'piid': 14}}, max_properties: 9/18

**Comment by zigajamnik** [comment]
I have now successfully added it via token, but it is unavaliable. Same error in logs.

**Comment by zigajamnik** [comment]
I have figured out that i have somehow integrated all devices several times. Will first clear then up and will revert then.

**Comment by zigajamnik** [comment]
Ok, I have now deleted all the integrations and added all devices but this light by account. Then I added this light by token and added customization for it:
![image](https://user-images.githubusercontent.com/27785913/222239528-be764564-908e-4545-9326-dec7aa5d4bbb.png)
![image](https://user-images.githubusercontent.com/27785913/222239596-f02a4263-4a95-4a3a-86cb-89f0f2c79697.png)
![image](https://user-images.githubusercontent.com/27785913/222239657-c4906d86-0d92-4770-a441-7f33d043100b.png)

Unfortunately the light is still unavaliable. nothing really changed. This error still appears:

2023-03-01 20:08:15.479 ERROR (MainThread) [custom_components.xiaomi_miot.light] LightKuhinja(yeelink.light.ceila): Got MiioException while fetching the state: Unable to discover the device 192.168.1.144, mapping: {'light.on': {'siid': 2, 'piid': 1}, 'light.mode': {'siid': 2, 'piid': 2}, 'light.brightness': {'siid': 2, 'piid': 3}, 'light.color_temperature': {'siid': 2, 'piid': 5}, 'yeelight.init_power_opt': {'siid': 4, 'piid': 1}, 'yeelight.save_state': {'siid': 4, 'piid': 2}, 'yeelight.cron_add': {'siid': 4, 'piid': 3}, 'yeelight.cron_del': {'siid': 4, 'piid': 4}, 'yeelight.cron_get': {'siid': 4, 'piid': 5}, 'yeelight.night_time': {'siid': 4, 'piid': 6}, 'yeelight.set_scene': {'siid': 4, 'piid': 7}, 'yeelight.set_adjust': {'siid': 4, 'piid': 8}, 'yeelight.set_ps': {'siid': 4, 'piid': 9}, 'yeelight.flow_param': {'siid': 4, 'piid': 10}, 'yeelight.brightness_delta': {'siid': 4, 'piid': 11}, 'yeelight.ct_delta': {'siid': 4, 'piid': 12}, 'yeelight.ct_adjust_alexa': {'siid': 4, 'piid': 13}, 'yeelight.brightness_with_zero': {'siid': 4, 'piid': 14}}, max_properties: 9/18

May I ask how can I switch to master branch? I am kind of a newb regarding this.

**Comment by zigajamnik** [comment]
Somehow I've managed to get it work, but just for a second. I've added entity customization and it appeared avaliable. I turned it off and back on and it went unavaliable again...

![image](https://user-images.githubusercontent.com/27785913/222249288-0c00c2db-0505-42e3-9079-4570950e515f.png)

**Comment by al-one** [comment]
![hacs download master](https://user-images.githubusercontent.com/4549099/222336536-50a957f4-cc9e-47d1-9dec-143d073b862c.png)

**Comment by zigajamnik** [comment]
I have switched to master. Same, light is unavaliable, with or without customization of the entity

**Comment by al-one** [comment]
Show logs.

**Comment by zigajamnik** [comment]
![image](https://user-images.githubusercontent.com/27785913/222375054-e16d958d-0c8e-4d22-89eb-a104f50725e1.png)

**Comment by al-one** [comment]
It looks like you did not upgrade successfully, please upgrade to v0.7.6.

**Comment by zigajamnik** [comment]
The light is now back online and avaliable :) 

Thank you very much!

![Screenshot_20230302_103311_Home Assistant](https://user-images.githubusercontent.com/27785913/222389162-10e4db5c-a013-443c-b2fc-0818acfc3567.jpg)
