### ISSUE TITLE
Xiaomi Miot Auto小米账户登录失败

### ISSUE THREAD

**Issue by heliujie11** [al-one/hass-xiaomi-miot#1045]
配置Xiaomi Miot Auto集成，账号密码无错，总是提示“次登陆小米账号需要安全验证，[点击这里]继续！你需要在与HA宿主机同局域网的设备下完成安全验证，如果你使用的是云服务器，将无法验证通过。” 账号验证无误，也是登录失败。

**Comment by 376980787** [comment]
怎么解决呢？我是阿里云

**Comment by al-one** [comment]
> 怎么解决呢？我是阿里云

@376980787  想办法在阿里云服务器登录米家账号并完成完整。这通常需要云服务支持GUI界面。

**Comment by zijie-415112984** [comment]
> 怎么解决呢？我是阿里云

给你的阿里云服务器装个远程桌面，远程上去后在服务器上，打开浏览器登录一下小米账号就妥了，然后再在HA里面就能正常等登录了

**Comment by zhulingbiezhi** [comment]
https://www.ququ123.top/2023/09/homeassistant_xiaomi_login  已经解决

**Comment by Swear1207** [comment]
刚安装home assistant第一次下载Xiaomi Miot Auto是可以正常登入的，隔了两天后登入Xiaomi Miot Auto显示Unknown error occurred并重启了Home assistant
