### ISSUE TITLE
升级后无法获取加湿器的湿度值和控制加湿器的灯状态

### ISSUE THREAD

**Issue by nmweizi** [al-one/hass-xiaomi-miot#105]
- 0.3.2的时候是可以获取到加湿器湿度值的，升级到0.3.5后无法获取湿度值了。
- 0.3.2的时候是可以控制加湿器的灯状态，升级到0.3.5后无法控制了。
- 温度值获取是正确的，控制开关也是可以的。
- 使用的是局域网模式
- 设备信息
deerma.humidifier.jsq3
by deerma
固件：2.0.4

```
custom.water_shortage_fault.error: -4004
custom.the_tank_filed.error: -4004
indicator_light.on.error: -4004
alarm.error: -4004
environment.relative_humidity.error: -4004
```

**Comment by al-one** [comment]
-4004报错应该是与插件版本无关的，请在设备电源打开的情况下观察状态属性。
如果仍无法获取和控制，请通过下面的shell命令降级至v0.3.2后再试：
```shell
wget -q -O - https://cdn.jsdelivr.net/gh/al-one/hass-xiaomi-miot/install.sh | ARCHIVE_TAG=v0.3.2 bash -
```
如果v0.3.2也是无法获取和控制，那就只能开启云端模式了。

**Comment by nmweizi** [comment]
@al-one 感谢。
用上面的方法退回到0.3.2，可以正常获取到湿度和控制指示灯状态。
看样子是0.3.5有什么改动了。

**Comment by al-one** [comment]
请提供0.3.2版本下的实体[状态属性](https://my.home-assistant.io/redirect/developer_states)。

**Comment by nmweizi** [comment]
- light.xiaomi_miot_jia_shi_qi_humidifier_indicator_light # 控制指示灯状态
```
supported_color_modes:
  - onoff
color_mode: onoff
indicator_light.on: true
entity_class: MiotLightSubEntity
friendly_name: Xiaomi Miot 加湿器 Humidifier Indicator Light
supported_features: 0
```
- sensor.xiaomi_miot_jia_shi_qi_humidifier_relative_humidity。# 湿度
```
environment.relative_humidity: 45
unit_of_measurement: '%'
friendly_name: 湿度
supported_features: 0
device_class: humidity
```

**Comment by al-one** [comment]
麻烦加下QQ群：[198841186](https://jq.qq.com/?_wv=1027&k=lZAMn5Uo) 联系我。

**Comment by nmweizi** [comment]
@al-one qq密码是实在是找不到了，可以其他方式吗？

**Comment by al-one** [comment]
那请加我微信，微信号同GitHub用户名

**Comment by al-one** [comment]
升级到master最新的提交：https://github.com/al-one/hass-xiaomi-miot/commit/b8bb356d8fd8281ec9e628196ed4e61d515fea73 即可解决。
或者现有版本通过添加自定义属性：
```yaml
# customize.yaml
humidity.your_entity_id:
  chunk_properties: 6
```
