### ISSUE TITLE
Xiaomi MI Air Purifier 3C [zhimi.airp.mb4a] - brightness of display

### ISSUE THREAD

**Issue by blugoshi** [al-one/hass-xiaomi-miot#1056]
Unfortunately I can't change brightness of the LED display, which I like to do at night. The entity is missing in Home Assistant.

It is a [zhimi.airp.mb4a] thru local integration (https://home.miot-spec.com/s/zhimi.airp.mb4a). Everything else works superb.

Thank you for your help

**Comment by al-one** [comment]
Please use [issue templaye](https://github.com/al-one/hass-xiaomi-miot/issues/new?template=device-issue.yml).
