### ISSUE TITLE
Please, add support to "Midian No Blue Light Music Lamp"

### ISSUE THREAD

**Issue by panferovaleksey** [al-one/hass-xiaomi-miot#106]
Device information (use miiocli device --ip --token)
```
Model: noc196.light.mdyctd
Hardware version: esp8266
Firmware version: 2.1.3
```
Additional context
http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:light:0000A001:noc196-mdyctd:1

**Comment by al-one** [comment]
This device should already be supported. If the entity is not available, please check whether there is an entity-related logs.
