### ISSUE TITLE
关于小爱音箱 conversation 轮询的建议

### ISSUE THREAD

**Issue by Sleaf** [al-one/hass-xiaomi-miot#1063]
可以实现在轮询前检测设备唤醒状态码？目前在路由看到是 15s 进行一次访问，而且并没有判断任何条件。
使用人数多了之后这对于小米服务器可能会带来压力，以至于后期可能会导致该服务不稳定或被ban ip？

**Comment by al-one** [comment]
插件无法得知小爱音箱的唤醒状态。目前已知小米服务器是根据账号对api限流的，因此随着使用人数的增加不会增加限流得风险，除非你的账号下面云端请求过于频繁，才会对你的账号进行限流。
