### ISSUE TITLE
小爱音箱 conversation 在多次询问同一个问题时不响应 state_changed

### ISSUE THREAD

**Issue by Sleaf** [al-one/hass-xiaomi-miot#1064]
是否可以将响应的 **msg** 与**问话时间**作为 payload？或者通过什么其他方式进行区分？

设备为小爱音箱pro  lx06

**Comment by Sleaf** [comment]
目前需求是自定义小爱的连续对话，但并没有找到合适的触发源，固定词触发就会遇上状态不变更的问题

**Comment by al-one** [comment]
可以通过检测对话实体`timestamp`属性来触发自动化。

```yam
trigger:
  - platform: state
    entity_id: sensor.xiaomi_x08c_xxxx_conversation
    attribute: timestamp
```

**Comment by Sleaf** [comment]
我使用的是node-red 的触发节点，去除  Current state equals previous state 就可以了，感谢！

![image](https://user-images.githubusercontent.com/23637144/226165846-6c8c2b2e-8592-4e1a-864e-19b7a2fc778f.png)
