### ISSUE TITLE
请问有办法把这个云米设备添加进入 Xiaomi Miot Auto 吗？

### ISSUE THREAD

**Issue by terenceng81** [al-one/hass-xiaomi-miot#1065]
设备名称：云米互联网洗碗机 Pro （8套嵌入式）
设备编号：viomi.dishwasher.v02

备注：此设备不在小米设备列表中，但是能在云米自己的app里找到。

希望有办法。。先谢了。

**Comment by al-one** [comment]
如果该设备无法添加到米家APP，那么这个插件也无能为力。

**Comment by terenceng81** [comment]
> 如果该设备无法添加到米家APP，那么这个插件也无能为力。

嗯，了解，谢谢您。
