### ISSUE TITLE
杜亚M1 接入后 米家里的窗帘自动反向 并且造成米家和HA都无法控制窗帘

### ISSUE THREAD

**Issue by ibule** [al-one/hass-xiaomi-miot#1066]
接入homeassistant后，开合一次后就无法再次开合，开合键点击都无反应，并且造成米家电机自动勾选了反转，然后米家也无法点击开合。

**Comment by marssl** [comment]
同样的问题，但可能不是插件的问题，因为我断开插件后，在米家APP里也还是会出现这个问题。

**Comment by limxc** [comment]
确实如此, 现在不知道怎么搞才好了

**Comment by ibule** [comment]
断开插件，断开窗帘电源，然后再去米家关闭反向就好了。
一单接入插件都得这样重置，插件和米家不兼容。
ywy ***@***.***>于2023年5月3日 周三上午12:59写道：

**Comment by al-one** [comment]
尝试master分支。

**Comment by tohkinzhu** [comment]
@ibule 断开电源后 显示离线 好像没办法进米家APP设置了额 请教下 如何处理哈？

**Comment by ibule** [comment]
断开后离线，等3分钟后，会上线的。 如果还是离线，说明你没有把窗帘固定IP而已，此时只需要长安WiFi键重置，然后在米家配对就好，建议固定IP，以防家里偶尔断电引起IP变动。

**Comment by tohkinzhu** [comment]
尝试了master分支后，问题已修复。

**Comment by TomatoFryEggs** [comment]
> 尝试了master分支后，问题已修复。

我原来是用的HACS里的，重新下载后还是一样？

用手动拉的`wget -q -O - https://raw.githubusercontent.com/al-one/hass-xiaomi-miot/master/install.sh | ARCHIVE_TAG=latest bash -`这个吗？

**Comment by 416631663** [comment]
> 手动复制文件夹后 这个困扰一年的 bug 终于被修好了，太感谢了。

HA和米家可以交叉控制了么？ 我目前还是HA控制了一次，米家APP里的电机反转就变过来了。看了配置文件：
