### ISSUE TITLE
可否支持平头熊X6智能中控屏开关 (WIFI)的本地化

### ISSUE THREAD

**Issue by lovedreamland** [al-one/hass-xiaomi-miot#1068]
https://home.miot-spec.com/spec/090615.switch.x6wtft
目前该设备是通过云端来同步状态的，他自带的子设备控制在米家里面没有选项，但是接入到HA里面好像是可以被HA接管的，可以用来联动其他设备，但是目前状态是通过云端来执行的， 所以经常会没有反应，要是可以直接本地化的话就好了。

**Comment by al-one** [comment]
请使用[issue模板](https://github.com/al-one/hass-xiaomi-miot/issues/new?assignees=&labels=&template=device-issue.yml)重新提交。
