### ISSUE TITLE
No video capture for chuangmi.camera.ipc019 

### ISSUE THREAD

**Issue by romanad** [al-one/hass-xiaomi-miot#1076]
### Device model / 设备型号

[chuangmi.camera.ipc019](https://home.miot-spec.com/s/chuangmi.camera.ipc019)

### Component version / 插件版本

0.7.7

### HA core version / HA版本

2023.3.6

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Dear friends, I have chuangmi.camera.ipc019e (Firmware: 4.1.6_0211).
I'm using Xiaomi Miot Auto Integration, it is able to find my camera but video capture doesn't work.
Every settings are default.
Could you suggest how any fix if possible.
![2023-04-02 00_29_25-Settings – Home Assistant](https://user-images.githubusercontent.com/26842711/229315272-8de15d3b-8a95-4e5d-beb8-0ec5fd5e6f5c.jpg)

### Entity attributes / 实体属性

![2023-04-02 00_49_46-Developer Tools – Home Assistant](https://user-images.githubusercontent.com/26842711/229315632-6c690813-59fa-4ff3-a155-9917d6e41954.jpg)
![2023-04-02 00_48_41-Developer Tools – Home Assistant](https://user-images.githubusercontent.com/26842711/229315636-0b54e36b-1e9c-4d8c-8e71-f6e3540c5695.jpg)

### Home Assistant Logs / 系统日志

This error originated from a custom integration.

Logger: custom_components.xiaomi_miot.camera
Source: custom_components/xiaomi_miot/camera.py:306
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: April 1, 2023 at 23:30:33 (73 occurrences)
Last logged: 00:49:33

Video camera(chuangmi.camera.ipc019e): camera events is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'thirdPartPlayUnits': [], 'nextTime': 1679780612000, 'isContinue': True}, 'description': '成功', 'ts': 1680385413313}
Video camera(chuangmi.camera.ipc019e): camera events is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'thirdPartPlayUnits': [], 'nextTime': 1679780792000, 'isContinue': True}, 'description': '成功', 'ts': 1680385593383}
Video camera(chuangmi.camera.ipc019e): camera events is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'thirdPartPlayUnits': [], 'nextTime': 1679780852000, 'isContinue': True}, 'description': '成功', 'ts': 1680385653385}
Video camera(chuangmi.camera.ipc019e): camera events is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'thirdPartPlayUnits': [], 'nextTime': 1679780912000, 'isContinue': True}, 'description': '成功', 'ts': 1680385713493}
Video camera(chuangmi.camera.ipc019e): camera events is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'thirdPartPlayUnits': [], 'nextTime': 1679780972000, 'isContinue': True}, 'description': '成功', 'ts': 1680385773528}

![2023-04-02 00_51_22-Settings – Home Assistant](https://user-images.githubusercontent.com/26842711/229315678-9486f4da-7a34-4c78-b675-aea2df127132.jpg)

**Comment by ductu3590** [comment]
i same error :( i can contrl turn on/off camera but not watch stream video camera

**Comment by al-one** [comment]
Unsupported device.
