### ISSUE TITLE
Missing unit in pm2_5_density sensor

### ISSUE THREAD

**Issue by fleaz** [al-one/hass-xiaomi-miot#108]
Hey,

I just integrated my AIrPurifier 3C into Homeassistant and the sensor for the PM2.5 concentration is shown as discrete values instead of a graph. According to the [documentation](https://www.home-assistant.io/integrations/template#unit_of_measurement) this is due the fact that the sensor is missing a unit.

This is how it's currently shown:
![Screenshot_2021-06-16_11:00:19](https://user-images.githubusercontent.com/2489598/122214972-01365700-ceab-11eb-8bf8-330d14c1d1f4.png)

**Comment by al-one** [comment]
You can add a customize attribute for `unit_of_measurement`.
> [⚙️ Configuration](https://my.home-assistant.io/redirect/config) > [🖌 Customize](https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui) > 🔍 Select Entity > Add unit_of_measurement

**Comment by fleaz** [comment]
Can confirm that this works as intended as a workaround. Thx :)

**Comment by fleaz** [comment]
Hey,

I intentionally left this issue open, because imho this was just a workaround and not a proper fix. Don't you think that fixing this directly in the integration code would be a better way to deal with this?

**Comment by al-one** [comment]
Now it has a unit.
