### ISSUE TITLE
Missing device class: Sphygmomanometer

### ISSUE THREAD

**Issue by alryaz** [al-one/hass-xiaomi-miot#1080]
### Device model / 设备型号

[ihealth.bp.bpm1](https://home.miot-spec.com/s/ihealth.bp.bpm1)

### Component version / 插件版本

0.7.7

### HA core version / HA版本

2023.3.5

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Device is recognized only at setup stage.
There are no sensors present.
The component downloads specification to .storage, however does not add the device.

### Entity attributes / 实体属性

_None_
_[Available here](https://home.miot-spec.com/spec/ihealth.bp.bpm1)_

### Home Assistant Logs / 系统日志

`Request Xiaomi api: v2/message/v2/typelist {} failed, response: None`

**Comment by al-one** [comment]
![image](https://user-images.githubusercontent.com/4549099/230532682-3829ff08-4c88-44f8-aa5d-1c46b0d21ebe.png)

None of the properties have read permissions and therefore cannot be supported.

**Comment by alryaz** [comment]
Having battery support would be nice 🙂
(To remind about recharging)
