### ISSUE TITLE
deerma.humidifier.jsq2g always unavailable

### ISSUE THREAD

**Issue by sasukebinbin** [al-one/hass-xiaomi-miot#1089]
### Device model / 设备型号

[deerma.humidifier.jsq2g](https://home.miot-spec.com/s/deerma.humidifier.jsq2g)

### Component version / 插件版本

0.7.7

### HA core version / HA版本

2023.3.6

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

最近2天不知道什么时候开始,一直不可用状态.
小米App里显示已连接,但也控制不了.

但是miiocli device --ip 192.168.0.109 --token 2c26df38fcf925cb28dcc8xxxxc63 info
Model: deerma.humidifier.jsq2g
Hardware version: RTL8720C
Firmware version: 2.2.2
没有问题

### Entity attributes / 实体属性
```yaml
min_humidity: 40
max_humidity: 80
available_modes: Off, Level1, Level2, Level3, Humidity
device_class: humidifier
friendly_name: 小米加湿器 Humidifier
supported_features: 1
```

### Home Assistant Logs / 系统日志

此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.humidifier
Source: custom_components/xiaomi_miot/__init__.py:1384
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 01:11:46 (103 occurrences)
Last logged: 02:05:48

小米加湿器(deerma.humidifier.jsq2g): Got MiioException while fetching the state: Unable to recover failed command, mapping: {'humidifier.on': {'siid': 2, 'piid': 1}, 'humidifier.fault': {'siid': 2, 'piid': 2}, 'humidifier.fan_level': {'siid': 2, 'piid': 5}, 'humidifier.target_humidity': {'siid': 2, 'piid': 6}, 'custom.water_shortage_fault': {'siid': 7, 'piid': 1}, 'custom.the_tank_filed': {'siid': 7, 'piid': 2}, 'indicator_light.on': {'siid': 6, 'piid': 1}, 'alarm': {'siid': 5, 'piid': 1}, 'environment.relative_humidity': {'siid': 3, 'piid': 1}, 'environment.temperature': {'siid': 3, 'piid': 7}}, max_properties: 6/10
小米加湿器(deerma.humidifier.jsq2g): Got MiioException while fetching the state: Unable to discover the device 192.168.0.109, mapping: {'humidifier.on': {'siid': 2, 'piid': 1}, 'humidifier.fault': {'siid': 2, 'piid': 2}, 'humidifier.fan_level': {'siid': 2, 'piid': 5}, 'humidifier.target_humidity': {'siid': 2, 'piid': 6}, 'custom.water_shortage_fault': {'siid': 7, 'piid': 1}, 'custom.the_tank_filed': {'siid': 7, 'piid': 2}, 'indicator_light.on': {'siid': 6, 'piid': 1}, 'alarm': {'siid': 5, 'piid': 1}, 'environment.relative_humidity': {'siid': 3, 'piid': 1}, 'environment.temperature': {'siid': 3, 'piid': 7}}, max_properties: 6/10
小米加湿器(deerma.humidifier.jsq2g): Got MiioException while fetching the state: No response from the device, mapping: {'humidifier.on': {'siid': 2, 'piid': 1}, 'humidifier.fault': {'siid': 2, 'piid': 2}, 'humidifier.fan_level': {'siid': 2, 'piid': 5}, 'humidifier.target_humidity': {'siid': 2, 'piid': 6}, 'custom.water_shortage_fault': {'siid': 7, 'piid': 1}, 'custom.the_tank_filed': {'siid': 7, 'piid': 2}, 'indicator_light.on': {'siid': 6, 'piid': 1}, 'alarm': {'siid': 5, 'piid': 1}, 'environment.relative_humidity': {'siid': 3, 'piid': 1}, 'environment.temperature': {'siid': 3, 'piid': 7}}, max_properties: 6/10

**Comment by al-one** [comment]
建议尝试给设备断电。

**Comment by sasukebinbin** [comment]
尝试断电后可以用了, 感谢
