### ISSUE TITLE
门窗传感器数据不能正常同步

### ISSUE THREAD

**Issue by HeHang0** [al-one/hass-xiaomi-miot#109]
小米门窗传感器。如果开关门在5秒钟之内是无法捕获到的。不会触发事件。大佬可不可以优化一下

**Comment by al-one** [comment]
由于本插件是通过轮询的方式获取设备状态，因此不适合门窗传感器等实时性要求比较高的设备。
建议使用XiaomiGateway3+多模网关接入。

https://github.com/al-one/hass-xiaomi-miot/issues/37#issuecomment-803870650
https://github.com/al-one/hass-xiaomi-miot/issues/89#issuecomment-845789992

**Comment by HeHang0** [comment]
> 由于本插件是通过轮询的方式获取设备状态，因此不适合门窗传感器等实时性要求比较高的设备。
> 建议使用XiaomiGateway3+多模网关接入。
> 
> https://github.com/al-one/hass-xiaomi-miot/issues/37#issuecomment-803870650
> https://github.com/al-one/hass-xiaomi-miot/issues/89#issuecomment-845789992

+ 代码里直接给这个实体轮训设为1s可以了，感谢大佬

**Comment by al-one** [comment]
通过添加自定义属性`interval_seconds: 1`确实可以实现每1秒查询一次状态，但其实不太推荐这么做，毕竟是云端查询，5s或者10s轮询一次也许更适合。

**Comment by HeHang0** [comment]
> 通过添加自定义属性`interval_seconds: 1`确实可以实现每1秒查询一次状态，但其实不太推荐这么做，毕竟是云端查询，5s或者10s轮询一次也许更适合。

就只给这一个设备1s，其他的还是默认。反正只要小米不封号就可以了吧，哈哈哈

**Comment by al-one** [comment]
1s也可能会导致HA产生一些更新状态过快的日志。

**Comment by HeHang0** [comment]
> 1s也可能会导致HA产生一些更新状态过快的日志。

观察几天看看，不行我就自己写个服务轮巡，然后有变化了调ha接口更新状态。

**Comment by weiyideai520** [comment]
如果不加 interval_seconds: 1，默认是多少秒更新一次。
还有怎么添加自定义属性 interval_seconds: 1

**Comment by al-one** [comment]
> 如果不加 interval_seconds: 1，默认是多少秒更新一次。

binary_sensor实体的默认刷新时间为30秒。
https://github.com/home-assistant/core/blob/0eae0cca2bf841f2c2cb87fc602bc8afa3557174/homeassistant/components/binary_sensor/__init__.py#L24

**Comment by jifengmm** [comment]
门窗传感器历史数据也无法同步，我看米家APP提示4点有开关门，但是HA里面没有。我只需要看历史就行了。 

> 由于本插件是通过轮询的方式获取设备状态，因此不适合门窗传感器等实时性要求比较高的设备。
> 建议使用XiaomiGateway3+多模网关接入。
> 
> [#37 (comment)](https://github.com/al-one/hass-xiaomi-miot/issues/37#issuecomment-803870650)
> [#89 (comment)](https://github.com/al-one/hass-xiaomi-miot/issues/89#issuecomment-845789992)

请问历史数据也和米家不一致也是这样原因吗？

**Comment by al-one** [comment]
> 请问历史数据也和米家不一致也是这样原因吗？

插件不会去同步历史数据，HA中的历史数据是每次轮询后HA自己记录的。
