### ISSUE TITLE
Feature request: Option to disable "devices offline" notification

### ISSUE THREAD

**Issue by banditoth** [al-one/hass-xiaomi-miot#1095]
Should be great, if we could configure whether we want the "Devices offline" notif, or not.

I used to plug some of my smart sockets out, or switch off the bulbs with the wall switch. 

![image](https://user-images.githubusercontent.com/24568882/232619694-1ca99724-442d-417d-8b7c-e26cf7ab8e0d.png)

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/705#issuecomment-1186726699
- https://github.com/al-one/hass-xiaomi-miot/issues/574#issuecomment-1121955107

**Comment by banditoth** [comment]
Thanks @al-one
