### ISSUE TITLE
空调风速映射不正确

### ISSUE THREAD

**Issue by HateBaozi** [al-one/hass-xiaomi-miot#1099]
### Device model / 设备型号

[qdhkl.aircondition.b23](https://home.miot-spec.com/s/qdhkl.aircondition.b23)

### Component version / 插件版本

0.7.7

### HA core version / HA版本

2023.4.6

### Integrated mode / 集成方式

Automatic (自动模式)

### Entity attributes / 实体属性

空调的风速映射，和米家APP还有控制器实际风速都不一样
低速 = 高速
中速 = 中速
高速 = 低速

### Home Assistant Logs / 系统日志

无

**Comment by HateBaozi** [comment]
![IMG_9307](https://user-images.githubusercontent.com/5424856/234447196-52af113f-6043-4941-81ca-8da27e48d14e.png)
![IMG_9308](https://user-images.githubusercontent.com/5424856/234447219-2c3caefd-2248-4245-b483-5f7ee724f8dd.png)
![IMG_9308]
fan_level 4对应的应该是low，miot-spec网页上的是对的。但是插件映射出来不对，fan_mode变成high了

**Comment by al-one** [comment]
![qdhkl.aircondition.b23](https://user-images.githubusercontent.com/4549099/235098984-d7fc763a-371e-4bd4-856d-c699c537240c.png)

该设备有两个版本的规格，插件会优先使用`released`状态的最新版本。已在最新的提交中为该设备强制使用`debug`状态的规格，请升级至master分支后重试。

**Comment by HateBaozi** [comment]
> ![qdhkl.aircondition.b23](https://user-images.githubusercontent.com/4549099/235098984-d7fc763a-371e-4bd4-856d-c699c537240c.png)
> 
> 该设备有两个版本的规格，插件会优先使用`released`状态的最新版本。已在最新的提交中为该设备强制使用`debug`状态的规格，请升级至master分支后重试。

能否增加一个local_delay_update的参数，这款设备和其他设备不一样，它需要等待空调回应状态，自身的状态才会更新。现在本地模式连接这个设备，打开空调以后，会马上用lan模式获取状态，但是这个时候空调的状态还是关闭的，估计要过2秒左右才会更新状态
