### ISSUE TITLE
rockrobo.vacuum.v1 不支持定位

### ISSUE THREAD

**Issue by bsx1990** [al-one/hass-xiaomi-miot#110]
您好，我发现rockrobo.vacuum.v1没有办法支持定位扫地机器人。在米家App上，可以通过“定位扫地机器人”让扫地机器人语音播报自己的位置。这对于扫地机器人不知道在哪里卡住的时候特别的有用。

尝试看了下代码，发现是否支持定位是由以下逻辑决定的：如果miot_service.get_action('position')为false，则使用self._srv_battery.get_property('position', 'find_device')

我想尝试下看看应该如何debug并且修复这个问题，您可以告诉我一下要怎么调试，查看每个方法的返回值吗？我看到代码里面引入了logger，但是并没有看到有日志输出。

**Comment by al-one** [comment]
该型号扫地机对应的miot-urn为`urn:miot-spec-v2:device:vacuum:0000A006:rockrobo-v1:1`，在其[miot-spec](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:vacuum:0000A006:rockrobo-v1:1)协议定义中未找到**定位**相关的服务或action，应该无法通过miot协议为该设备提供定位功能。

**Comment by bsx1990** [comment]
我看home assistant官方文档里面说可以支持定位的，几年前最早接触home assistant的时候，忘记了是用的什么插件了，但确实实现过

**Comment by al-one** [comment]
本插件是通过[miot-spec](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:vacuum:0000A006:rockrobo-v1:1)协议接入小米设备的，在旧版的miio协议中确实支持该型号扫地机的定位，而在[miot-spec](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:vacuum:0000A006:rockrobo-v1:1)协议中需要厂商定义对应的服务才可以支持。

**Comment by bsx1990** [comment]
这样啊。好久没有关注HA的情况了。不过还是想问一下，如果想要调试研究代码实现的话，有什么文档推荐吗？或者我应该怎么着手呢？

另外想问下，通过抓包米家app的定位的网络通讯数据，然后来尝试自己实现定位的需求，是否可行呢？如果有的话，可有相关的文档推荐吗？

现在从事的场景跟HA关系不大，想试着看下应该怎么调试HA

**Comment by al-one** [comment]
该问题的主要原因是米家协议的更新换代，与HA无关。
抓包米家是可行的，本插件云端模式就是依赖米家APP的部分接口。
调试HA最简单的方法就是日志级别的修改，以及增加日志的收集。

**Comment by bsx1990** [comment]
谢谢回复，我晚上去看一下。
感谢跟进，那我先把这个问题关了吧

**Comment by al-one** [comment]
在最新提交：https://github.com/al-one/hass-xiaomi-miot/commit/6b0b9bc07c54f88dbcbf76f1841072e5b0660148 中，我通过miio协议的命令支持了对扫地机的定位。
