### ISSUE TITLE
无法集成设备“小米手环7NFC版”

### ISSUE THREAD

**Issue by murazi** [al-one/hass-xiaomi-miot#1100]
### Device model / 设备型号

Xiaomi Smart Band 7 NFC ([hmpace.watch.v7nfc](https://home.miot-spec.com/s/hmpace.watch.v7nfc))

### Component version / 插件版本

0.7.8

### HA core version / HA版本

2023.4.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

更新设备列表，在列表里倒是有设备名，但插件无法集成设备出来（小米手环7NFC版）

0.7.7和0.7.8都不行

### Entity attributes / 实体属性

hmpace.watch.v7nfc

**Comment by al-one** [comment]
![hmpace.watch.v7nfc spec](https://user-images.githubusercontent.com/4549099/235102349-11a98b72-4635-4384-825d-d78fee93fd78.png)

设备厂商没有为该设备定义任何属性，因此无法支持。
