### ISSUE TITLE
小米门铃不可用

### ISSUE THREAD

**Issue by weiyideai520** [al-one/hass-xiaomi-miot#111]
小米门铃

设备信息
linp.doorbell.g03
by linp
固件：2.2.0
实体
小米门铃 Doorbell
不可用

已勾选，开启云端模式

**Comment by al-one** [comment]
https://github.com/al-one/hass-xiaomi-miot/issues/38#issuecomment-806505118

该设备的miot-spec协议中仅有一个音量属性是(`volume`)可以被支持的，按门铃的事件(`event`)目前无法支持。
如果你确定想只接入音量实体，请提供该实体相关日志。

**Comment by weiyideai520** [comment]
好的吧，其实不能支持事件的画，控制音量也没有什么意思了
