### ISSUE TITLE
Inter VLAN Local Connection

### ISSUE THREAD

**Issue by DEADSEC-SECURITY** [al-one/hass-xiaomi-miot#1112]
Hi guys, I currently have 2 Networks setup in my house, one for HomeAssistant and another one for IOT devices and all my devices (Esphome, Aqara, etc) work fine in this setup but for some reason I can't connect locally via this library. Is there a port that I should allow between the VLANs/device? 
I currently don't have any restriction between IOT and HomeAssistant so not sure why it wouldnt work.

Also my Route logs don't show any firewall rules enforced so I guess its not a Networking issue.

**Comment by al-one** [comment]
- https://python-miio.readthedocs.io/en/latest/troubleshooting.html#discover-devices-across-subnets
- https://github.com/rytilahti/python-miio/issues/422#issuecomment-455824152
- https://github.com/al-one/hass-xiaomi-miot/issues/349#issuecomment-1004179460
