### ISSUE TITLE
中央空调VRF 接入ha后实体中没有温度传感器，米家app中有当前温度数据且正常

### ISSUE THREAD

**Issue by shutiao88** [al-one/hass-xiaomi-miot#1119]
设备信息：[090615.aircondition.ktf](https://home.miot-spec.com/s/090615.aircondition.ktf)
第三方米家vrf设备连接日立中央空调（空调带温度传感器，不像空调伴侣），接入 mi iot auto 转homekit
homekit 中所有当前温度显示都为21 度，查询现有资料说这个是缺省值
查看米家app中，有当前温度数据，且是正常的。
但是在导入后的实体中，只有风量和模式控制，没有当前温度数据。

如下图所示，米家app可现实当前室温29， 设定温度20。 ha内只有设定值20， homekit为缺省值21度
![IMG_8935](https://github.com/al-one/hass-xiaomi-miot/assets/133900707/d2d6c48a-ec62-48d4-a537-5de6be18e811)
![IMG_A5F58CD1A439-1](https://github.com/al-one/hass-xiaomi-miot/assets/133900707/55e392ef-6ede-4e5e-b68f-7cfd307340e0)

**Comment by wolnlow** [comment]
在属性里面有的setmode.roomtemp，不过这个值一般不是很准的

**Comment by al-one** [comment]
提供完整的实体属性。

**Comment by tgogod** [comment]
我的也是这样：
![image](https://github.com/al-one/hass-xiaomi-miot/assets/3376916/aeb7041a-5498-49f7-9736-6f0b4a50754f)
看了下产品库，090615.aircondition.ktf 这个设备有两个版本的数据服务，新版本的还在debug状态，但已经有了环境温度的属性：
https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:air-conditioner:0000A004:090615-ktf:2
![image](https://github.com/al-one/hass-xiaomi-miot/assets/3376916/c7f63fb7-841c-4f44-8ea2-a39578d56c5e)
能否帮忙更新，以支持这个属性？谢谢  @al-one

**Comment by al-one** [comment]
请更新至master分支后尝试。

**Comment by tgogod** [comment]
> 请更新至master分支后尝试。

你好，已经切换到master分支并重新下载、加载。温度出来了，但是都显示为0。
![image](https://github.com/al-one/hass-xiaomi-miot/assets/3376916/5b024e07-b1a5-4106-a06e-4f5b309c7fcf)
请问这个是设备传数据的问题吗
