### ISSUE TITLE
No more support for lumi.camera.aq1  - can u bring back the on/off switch ? 

### ISSUE THREAD

**Issue by faxbio** [al-one/hass-xiaomi-miot#112]
Many releases ago the lumi.camera.aq1 was configured but not working with the streaming.
It is correct to not have it fully supported.
Now it is marked as unsopported and no more configured.

"Xiaomi Miot Warning
Your camera lumi.camera.aq1 doesn't support streaming services.
你的摄像机不支持流服务。
https://github.com/al-one/hass-xiaomi-miot/issues/60#issuecomment-819435571"

Considering that the Switch camera on off was working correctly (i was able to use it to put the camera in the sleep mode), is it possible to have the camera "partially supported" ?

I need that on off camera switch .....

**Comment by al-one** [comment]
Try last commit: https://github.com/al-one/hass-xiaomi-miot/commit/732514323af833c229df7102b0485b89d34e7bbe
