### ISSUE TITLE
可否增加个功能

### ISSUE THREAD

**Issue by linus4532** [al-one/hass-xiaomi-miot#1124]
你好，能不能给温控器增加一个自定义温度计实体的功能，现在的vrf和小超人自己的温度都不准。

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/686#issuecomment-1173297983
- https://github.com/al-one/hass-xiaomi-miot/issues/143#issuecomment-885658452

**Comment by tianyanli** [comment]
> * [无法获取空调伴侣设定的当前空调的工作温度 #686 (comment)](https://github.com/al-one/hass-xiaomi-miot/issues/686#issuecomment-1173297983)
> * [空调伴侣如何设定卡片上的温度 #143 (comment)](https://github.com/al-one/hass-xiaomi-miot/issues/143#issuecomment-885658452)

添加自定义实体后似乎没有效果，是我搞的不对吗？配置如下
customizing_entity:
  climate.lumi_mcn02_a7e0_air_conditioner:
    bind_sensor: climate.lumi_mcn02_a7e0_air_conditioner
    chunk_properties: '7'
    sensor_attributes: electric_power,power_cost_today,power_cost_month

**Comment by al-one** [comment]
`bind_sensor`应该配置温度传感器
