### ISSUE TITLE
可以指定添加单个蓝牙设备吗？

### ISSUE THREAD

**Issue by weiyideai520** [al-one/hass-xiaomi-miot#113]
现在登录账户后，添加就是同类型的都添加的，但是我只想添加其中的一个，不知道是否可以可以这样操作

**Comment by al-one** [comment]
最新的提交：https://github.com/al-one/hass-xiaomi-miot/commit/1c67a71459e3a7fa80989d48716b0d5bdc75499c 已支持。

**Comment by weiyideai520** [comment]
可以了，感谢~~~
