### ISSUE TITLE
DNS 对了，但是还是连接不上

### ISSUE THREAD

**Issue by leo95123** [al-one/hass-xiaomi-miot#1167]
![image](https://github.com/al-one/hass-xiaomi-miot/assets/28439527/66bf09ec-0c54-4fe6-b303-e3a350577fd5)

**Comment by SodaWithoutSparkles** [comment]
处理网络连线问题有泛用方法

1. `ping 127.0.0.1` 以确认网卡正常
2. `ifconfig` 以获取网关 (gateway) ip, 通常是你的router
3. `ping <gateway_ip>` 以确认可以连接网关
4. `ping 1.1.1.1` 或者其他外网ip以确定外网连接正常
5. `ping example.com` 以确认DNS服务正常

如果只是处理DNS问题，可尝试

`dig example.com @1.1.1.1` 
  > **Note**: 1.1.1.1是指定的DNS server

**Comment by leo95123** [comment]
> 

后来确认了一下，是主机网络的问题，而且问题很严重。
网线插上会对局域网内其他主机有影响，上不了网，暂时拔掉网线了，后面再重装

**Comment by SodaWithoutSparkles** [comment]
主机网络问题就不是这里的事了。issue应该可以关掉了
