### ISSUE TITLE
loock.cateye.v01 ?

### ISSUE THREAD

**Issue by djmalin** [al-one/hass-xiaomi-miot#117]
hello, is it possible to add this iteration? I see that the v2 version is possible, maybe it will also work with this version?

**Comment by al-one** [comment]
Model: loock.cateye.v01
urn: [urn:miot-spec-v2:device:video-doorbell:0000A03A:loock-v01:1](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:video-doorbell:0000A03A:loock-v01:1)

According to the definition of the miot-spec, this component only supports the battery level sensor and motion detection switch for this device.

**Comment by djmalin** [comment]
It will be possible in the near future to have an image from the camera?

**Comment by al-one** [comment]
Temporarily unachievable.
