### ISSUE TITLE
Switches become unavailable every 1-2 minutes, api.io.mi.com timeout

### ISSUE THREAD

**Issue by msaario** [al-one/hass-xiaomi-miot#1170]
### Device model / 设备型号

lumi.switch.b1nc01, lumi.switch.b1lc04

### Component version / 插件版本

0.7.10

### HA core version / HA版本

2023.6.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Multiple devices go unavailable every 1-2 minutes and return available in 1-2 minutes. This seems to affect Zigbee and BLE devices connected by cloud, such as lumi.switch.b1nc01 and lumi.switch.b1lc04.

Status for devices is "became unavailable" constantly, so I cannot reliably control.

Logs show most often following error: timeout, exception: HTTPSConnectionPool(host='api.io.mi.com', port=443): Read timed out. (read timeout=10)

Ping api.io.mi.com works although there is some packet loss. I cannot identify any network issues and it seems to only affect this integration.

I have tried master branch with same issue.

Thanks.

### Entity attributes / 实体属性

device_class: switch
friendly_name: Aqara Smart Wall Switch E1 (With Neutral, Single Rocker) Switch
supported_features: 0
model: lumi.switch.b1nc01
lan_ip: ''
mac_address: '498149803'
entity_class: MiotSwitchEntity
home_room: House Bathroom
miot_type: urn:miot-spec-v2:device:switch:0000A003:lumi-b1nc01:1
switch.on: false
button.disable_btn.error: '-704083036 Device operation timeout'
alarm.temperature_alarm.error: '-704083036 Device operation timeout'
electric_cfg.poweroff_memory.error: '-704083036 Device operation timeout'
night_close_enable-4-1.error: '-704083036 Device operation timeout'
indicator_light.overturn_light.error: '-704083036 Device operation timeout'
config_time_period-4-3.error: '-704083036 Device operation timeout'
state_updater: cloud

device_class: switch
friendly_name: Kitchen Lights Switch E1 (No Neutral) Switch
supported_features: 0
model: lumi.switch.b1lc04
lan_ip: ''
mac_address: '420937346'
entity_class: MiotSwitchEntity
home_room: House Kitchen
miot_type: urn:miot-spec-v2:device:switch:0000A003:lumi-b1lc04:1
switch.on: false
mode_change: 4
button.disable_bsn: 1
alarm.temperature_alarm: 0
electric_cfg.poweroff_memory: 1
night_close_enble-3-1: 0
config_time_period-3-3: 589845
state_updater: cloud

### Home Assistant Logs / 系统日志

This error originated from a custom integration.

Logger: custom_components.xiaomi_miot.core.xiaomi_cloud
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:68
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 20:56:49 (112 occurrences)
Last logged: 21:13:33

Request xiaomi api: miotspec/prop/get {'params': [{'did': '498149803', 'siid': 2, 'piid': 1}, {'did': '498149803', 'siid': 7, 'piid': 1}, {'did': '498149803', 'siid': 6, 'piid': 1}, {'did': '498149803', 'siid': 5, 'piid': 1}, {'did': '498149803', 'siid': 4, 'piid': 1}, {'did': '498149803', 'siid': 4, 'piid': 2}, {'did': '498149803', 'siid': 4, 'piid': 3}]} failed, response: None
Request xiaomi api: miotspec/prop/get {'params': [{'did': '463939760', 'siid': 2, 'piid': 1}, {'did': '463939760', 'siid': 2, 'piid': 3}, {'did': '463939760', 'siid': 2, 'piid': 4}, {'did': '463939760', 'siid': 9, 'piid': 1}, {'did': '463939760', 'siid': 9, 'piid': 3}, {'did': '463939760', 'siid': 9, 'piid': 5}, {'did': '463939760', 'siid': 9, 'piid': 6}, {'did': '463939760', 'siid': 7, 'piid': 1}, {'did': '463939760', 'siid': 6, 'piid': 1}, {'did': '463939760', 'siid': 6, 'piid': 2}, {'did': '463939760', 'siid': 3, 'piid': 1}, {'did': '463939760', 'siid': 3, 'piid': 3}, {'did': '463939760', 'siid': 3, 'piid': 4}, {'did': '463939760', 'siid': 3, 'piid': 5}, {'did': '463939760', 'siid': 3, 'piid': 6}, {'did': '463939760', 'siid': 3, 'piid': 7}, {'did': '463939760', 'siid': 3, 'piid': 8}, {'did': '463939760', 'siid': 3, 'piid': 9}, {'did': '463939760', 'siid': 3, 'piid': 10}, {'did': '463939760', 'siid': 3, 'piid': 11}, {'did': '463939760', 'siid': 3, 'piid': 12}, {'did': '463939760', 'siid': 3, 'piid': 13}, {'did': '463939760', 'siid': 3, 'piid': 14}, {'did': '463939760', 'siid': 3, 'piid': 15}, {'did': '463939760', 'siid': 3, 'piid': 16}, {'did': '463939760', 'siid': 3, 'piid': 17}, {'did': '463939760', 'siid': 3, 'piid': 18}, {'did': '463939760', 'siid': 3, 'piid': 19}, {'did': '463939760', 'siid': 3, 'piid': 20}, {'did': '463939760', 'siid': 3, 'piid': 21}, {'did': '463939760', 'siid': 3, 'piid': 22}, {'did': '463939760', 'siid': 3, 'piid': 24}, {'did': '463939760', 'siid': 3, 'piid': 25}, {'did': '463939760', 'siid': 3, 'piid': 26}, {'did': '463939760', 'siid': 3, 'piid': 27}, {'did': '463939760', 'siid': 8, 'piid': 1}, {'did': '463939760', 'siid': 5, 'piid': 1}, {'did': '463939760', 'siid': 5, 'piid': 2}]} failed, response: None
Request xiaomi api: miotspec/prop/get {'params': [{'did': '1048259497', 'siid': 2, 'piid': 2}, {'did': '1048259497', 'siid': 2, 'piid': 3}, {'did': '1048259497', 'siid': 2, 'piid': 4}, {'did': '1048259497', 'siid': 2, 'piid': 5}, {'did': '1048259497', 'siid': 2, 'piid': 6}, {'did': '1048259497', 'siid': 2, 'piid': 7}, {'did': '1048259497', 'siid': 3, 'piid': 3}, {'did': '1048259497', 'siid': 3, 'piid': 4}, {'did': '1048259497', 'siid': 3, 'piid': 5}, {'did': '1048259497', 'siid': 3, 'piid': 8}, {'did': '1048259497', 'siid': 3, 'piid': 10}, {'did': '1048259497', 'siid': 3, 'piid': 11}, {'did': '1048259497', 'siid': 3, 'piid': 16}, {'did': '1048259497', 'siid': 3, 'piid': 17}, {'did': '1048259497', 'siid': 3, 'piid': 19}, {'did': '1048259497', 'siid': 3, 'piid': 21}, {'did': '1048259497', 'siid': 3, 'piid': 22}, {'did': '1048259497', 'siid': 3, 'piid': 23}, {'did': '1048259497', 'siid': 3, 'piid': 24}, {'did': '1048259497', 'siid': 5, 'piid': 1}, {'did': '1048259497', 'siid': 5, 'piid': 2}]} failed, response: None
Request xiaomi api: miotspec/prop/get {'params': [{'did': '420949301', 'siid': 2, 'piid': 1}, {'did': '420949301', 'siid': 10, 'piid': 1}, {'did': '420949301', 'siid': 6, 'piid': 1}, {'did': '420949301', 'siid': 5, 'piid': 1}, {'did': '420949301', 'siid': 4, 'piid': 1}, {'did': '420949301', 'siid': 3, 'piid': 1}, {'did': '420949301', 'siid': 3, 'piid': 3}]} failed, response: None
Request xiaomi api: miotspec/prop/get {'params': [{'did': '463939760', 'siid': 3, 'piid': 1}, {'did': '463939760', 'siid': 3, 'piid': 3}, {'did': '463939760', 'siid': 3, 'piid': 4}, {'did': '463939760', 'siid': 3, 'piid': 5}, {'did': '463939760', 'siid': 3, 'piid': 6}, {'did': '463939760', 'siid': 3, 'piid': 7}, {'did': '463939760', 'siid': 3, 'piid': 8}, {'did': '463939760', 'siid': 3, 'piid': 9}, {'did': '463939760', 'siid': 3, 'piid': 10}, {'did': '463939760', 'siid': 3, 'piid': 11}, {'did': '463939760', 'siid': 3, 'piid': 12}, {'did': '463939760', 'siid': 3, 'piid': 13}, {'did': '463939760', 'siid': 3, 'piid': 14}, {'did': '463939760', 'siid': 3, 'piid': 15}, {'did': '463939760', 'siid': 3, 'piid': 16}, {'did': '463939760', 'siid': 3, 'piid': 17}, {'did': '463939760', 'siid': 3, 'piid': 18}, {'did': '463939760', 'siid': 3, 'piid': 19}, {'did': '463939760', 'siid': 3, 'piid': 20}, {'did': '463939760', 'siid': 3, 'piid': 21}, {'did': '463939760', 'siid': 3, 'piid': 22}, {'did': '463939760', 'siid': 3, 'piid': 24}, {'did': '463939760', 'siid': 3, 'piid': 25}, {'did': '463939760', 'siid': 3, 'piid': 26}, {'did': '463939760', 'siid': 3, 'piid': 27}, {'did': '463939760', 'siid': 9, 'piid': 1}, {'did': '463939760', 'siid': 9, 'piid': 3}, {'did': '463939760', 'siid': 9, 'piid': 5}, {'did': '463939760', 'siid': 9, 'piid': 6}, {'did': '463939760', 'siid': 7, 'piid': 1}, {'did': '463939760', 'siid': 6, 'piid': 1}, {'did': '463939760', 'siid': 6, 'piid': 2}, {'did': '463939760', 'siid': 8, 'piid': 1}, {'did': '463939760', 'siid': 5, 'piid': 1}, {'did': '463939760', 'siid': 5, 'piid': 2}, {'did': '463939760', 'siid': 2, 'piid': 1}, {'did': '463939760', 'siid': 2, 'piid': 3}, {'did': '463939760', 'siid': 2, 'piid': 4}]} failed, response: None

This error originated from a custom integration.

Logger: custom_components.xiaomi_miot.switch
Source: custom_components/xiaomi_miot/__init__.py:2204
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 21:10:31 (1 occurrences)
Last logged: 21:10:31

Kitchen Lights Switch E1 (No Neutral)(lumi.switch.b1lc04): Set miot property {'did': '420937346', 'siid': 2, 'piid': 1, 'value': True} failed, result: {'did': '420937346', 'iid': '0.2.1', 'siid': 2, 'piid': 1, 'code': -704083036, 'exe_time': 0}

**Comment by arklev** [comment]
I have encountered the same problem with my three devices (Camera, Heater, Vacuum). I was looking for solutions here but didn't find any. 
Was able to fix it (for now) by going to the configuration tab in the integration itself and selecting the "Cloud" option instead of the "Automatic." I also disabled the notifications, but I'm not sure if it's related. Hope this helps someone.

**Comment by steuerzentrale** [comment]
thats a good hint, I will try that too and report if it solves the issue.

**Comment by arklev** [comment]
Yes, So fat its been two days and i didnt had any disconnections.
