### ISSUE TITLE
Mi Smart Power Plug 2 (chuangmi.plug.212a01) power consumption sensor wrong

### ISSUE THREAD

**Issue by blakadder** [al-one/hass-xiaomi-miot#118]
power consumption value should have two decimal points. in this case actual power consumption is 78.25W while its being reported as 7825:

`[{'did': 'electric_power', 'piid': 6, 'siid': 5, 'value': 7825 'code': 0}]`

verified with the app and independent power meter

![image](https://user-images.githubusercontent.com/5904370/124293338-d6a8f700-db56-11eb-851f-dd30476827e2.png)

`[{'did': 'electric_current', 'piid': 2, 'siid': 5, 'value': 5, 'code': 0}]` and `[{'did': 'power_consumption', 'piid': 1, 'siid': 5, 'value': 100, 'code': 0}]` are stuck at these values even the plug is switched off

**Comment by al-one** [comment]
Duplicate https://github.com/al-one/hass-xiaomi-miot/issues/101#issuecomment-856406591

**Comment by blakadder** [comment]
Wouldn't it make more sense for the device to work out of the box by customising the W sensor automatically instead of requiring manual .yaml editing?

**Comment by al-one** [comment]
This value and unit are from miot-spec. Under normal circumstances, the component will not be changed for a specific model of device, unless the entity is unavailable or affects the use.
