### ISSUE TITLE
小米无线开关未显示

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [al-one/hass-xiaomi-miot#1183]
### Device model / 设备型号

N/A

### Component version / 插件版本

0.7.10

### HA core version / HA版本

2023.06.02

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

这个装置虽然在米家已经绑定，但无法在HA使用

型号：WXKG01LM
协议：zigbee
网关：lumi.gateway.mgl03，固件1.5.5_0006

米家可供使用的触发条件：
- 单击
- 双击
- 长按

预计沟通方式：开关通过zigbee协议广播状态
预计HA存取方式：poll网关获取按钮状态

```
   NAME:     无线开关
   ID:       lumi.158d00087e859a
   MODEL:    lumi.sensor_switch.v2
   ---------
```

### Entity attributes / 实体属性

N/A

### Home Assistant Logs / 系统日志

N/A

**Comment by SodaWithoutSparkles** [comment]
暂时或许可行的替代方法：使用米家按钮触发小爱同学对话状态，HA在该状态改变时触发

**Comment by qq273681448** [comment]
> 暂时或许可行的替代方法：使用米家按钮触发小爱同学对话状态，HA在该状态改变时触发

请问小米多模网关2可否实时读取按钮状态？

**Comment by al-one** [comment]
> 请问小米多模网关2可否实时读取按钮状态？

可以，配合`XiaomiGateway3`插件。本插件不支持无线开关。

**Comment by qq273681448** [comment]
HI!我是邵磊，您的邮件我已经收到啦，我会在第一时间给您回复哦。

**Comment by qq273681448** [comment]
HI!您的邮件我已经收到啦，我会在第一时间给您回复哦。
