### ISSUE TITLE
最近Xiaomi智能摄像机2 AI增强版 实体不可用了

### ISSUE THREAD

**Issue by nesror** [al-one/hass-xiaomi-miot#1187]
### Device model / 设备型号

chuangmi.camera.051a01

### Component version / 插件版本

0.7.10

### HA core version / HA版本

2023.6.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

 * 不秦楚是不是更新了HA导致的还是更新设备固件导致的。。
 * 米家里正常
 * 另外希望增加one-key-call->key-call-switch开关。这个相当于按下摄像头通话按钮

### Entity attributes / 实体属性

unavailable

### Home Assistant Logs / 系统日志

Logger: custom_components.xiaomi_miot.camera
Source: custom_components/xiaomi_miot/__init__.py:1384
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 16:31:59 (205 occurrences)
Last logged: 19:57:25

客厅相机(chuangmi.camera.051a01): Got MiioException while fetching the state: Unable to discover the device 192.168.31.111, mapping: {'camera_control.on': {'siid': 2, 'piid': 1}, 'camera_control.image_rollover': {'siid': 2, 'piid': 2}, 'camera_control.night_shot': {'siid': 2, 'piid': 3}, 'camera_control.wdr_mode': {'siid': 2, 'piid': 5}, 'glimmer_full_color-2-6': {'siid': 2, 'piid': 6}, 'camera_control.recording_mode': {'siid': 2, 'piid': 7}, 'camera_control.motion_tracking': {'siid': 2, 'piid': 8}, 'camera_control.time_watermark': {'siid': 2, 'piid': 9}, 'one_key_call.key_call_switch': {'siid': 12, 'piid': 1}, 'one_key_call.key_call_status': {'siid': 12, 'piid': 2}, 'smart_care.smart_care_switch': {'siid': 11, 'piid': 1}, 'smart_care.smart_care_area': {'siid': 11, 'piid': 2}, 'smart_care.smart_care_config': {'siid': 11, 'piid': 3}, 'smart_care.smart_care_clock_key': {'siid': 11, 'piid': 4}, 'cruise.cruise_switch': {'siid': 10, 'piid': 1}, 'cruise.cruise_config': {'siid': 10, 'piid': 2}, 'fav_area': {'siid': 9, 'piid': 1}, 'fav_area.active_fav_area': {'siid': 9, 'piid': 2}, 'ai_scene.figureid': {'siid': 8, 'piid': 1}, 'ai_scene.gesture_name': {'siid': 8, 'piid': 2}, 'chuangmi_ai.face_switch': {'siid': 7, 'piid': 1}, 'chuangmi_ai.babycry_switch': {'siid': 7, 'piid': 2}, 'chuangmi_ai.pet_switch': {'siid': 7, 'piid': 3}, 'chuangmi_ai.gesture_switch': {'siid': 7, 'piid': 4}, 'speaker.volume': {'siid': 13, 'piid': 1}, 'speaker.mute': {'siid': 13, 'piid': 2}, 'motion_detection': {'siid': 5, 'piid': 1}, 'motion_detection.alarm_interval': {'siid': 5, 'piid': 2}, 'detection_sensitivity-5-3': {'siid': 5, 'piid': 3}, 'motion_detection_start_time-5-4': {'siid': 5, 'piid': 4}, 'motion_detection_end_time-5-5': {'siid': 5, 'piid': 5}, 'memory_card_management.status': {'siid': 4, 'piid': 1}, 'storage_total_space-4-2': {'siid': 4, 'piid': 2}, 'storage_free_space-4-3': {'siid': 4, 'piid': 3}, 'storage_used_space-4-4': {'siid': 4, 'piid': 4}, 'indicator_light.on': {'siid': 3, 'piid': 1}}, max_properties: 9/36

**Comment by nesror** [comment]
突然可以了

**Comment by JonathanKang** [comment]
我也遇到这个问题了，一样的错误日志。

**Comment by nesror** [comment]
chuangmi.camera.051a01机型的bug，断网重连后只有米家app里会正常显示，iot插件和中枢极客版里都显示离线。重启摄像机后正常

**Comment by JonathanKang** [comment]
@nesror 请问你的这个摄像头能看到实时监控画面吗？我逛了一圈issue，发现这个设备只支持`P2P Stream`，应该是没戏。
