### ISSUE TITLE
小米多功能网关二代彩灯和警戒实体属性获取失败

### ISSUE THREAD

**Issue by HateBaozi** [al-one/hass-xiaomi-miot#1188]
### Device model / 设备型号

lumi.gateway.v3

### Component version / 插件版本

0.7.10

### HA core version / HA版本

2023.6.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

彩灯和报警器属性提示错误 “-704220043 Property value error”

### Entity attributes / 实体属性

supported_color_modes:
  - onoff
model: lumi.gateway.v3
lan_ip: 192.168.3.63
mac_address: 7C:49:EB:88:DD:7A
entity_class: MiotLightEntity
home_room: 我的家 一楼
miot_type: urn:miot-spec-v2:device:gateway:0000A019:lumi-v3:2
light.on.error: '-704040003 Property does not exist'
motion_sensor.illumination.error: '-704220043 Property value error'
alarm: false
alarm.volume: 0
gateway.guard_mode.error: '-704040003 Property does not exist'
state_updater: cloud
friendly_name: 网关一楼 Light
supported_features: 0

### Home Assistant Logs / 系统日志

无这个设备相关日志

**Comment by EvilCult** [comment]
发现一样的问题

一样的报错信息
