### ISSUE TITLE
Qingping Motion & Ambient Light Sensor

### ISSUE THREAD

**Issue by fenkail-ui** [al-one/hass-xiaomi-miot#119]
Qingping Motion & Ambient Light Sensor，There is no light sensor in the entity.
Hope to fix it
thx

**Comment by al-one** [comment]
What is the model of this device ?

**Comment by al-one** [comment]
[`cgllc.motion.cgpr1`](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:motion-sensor:0000A014:cgllc-cgpr1:1) is the model of this device ?
