### ISSUE TITLE
通过本地DLNA控制小爱音箱

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [al-one/hass-xiaomi-miot#1192]
小爱音箱的DLNA服务是部分阉割的，无法直接使用，导致home assistant无法通过小爱作为media renderer。

不过我成功測試了一个方法可以使用，不过限制是只能通过URI获取，换言之需要有类似于HTTP server的东西。

![Screenshot_2023-07-04-19-07-08-148_com.realvnc.viewer.android-edit.jpg](https://github.com/al-one/hass-xiaomi-miot/assets/64138578/3f0e3b7e-9632-4175-b6de-6bf5ebfb7fb1)

如图所示，通过invoke `SetAVTransport` 并提供URI，即可播放。已经测试了本地URI是没问题的，所以可以配合jellyfin使用。不过它不会停止，会一直循环，所以需要在适当时候invoke `Stop` 来停止播放。

下一步是看看怎么样可以结合到HA里面了。

**Comment by SodaWithoutSparkles** [comment]
@WinkeyLin 确实如此。关于jellyfin的问题已经在jellyfin/jellyfin repo 里开了issue，编号9963。为避免github自己连到一起就不放链接了。

**Comment by yzlnew** [comment]
用 Music Assistant 是可以播放支持 DLNA 的小爱音箱，基本是完美的。

**Comment by 810517583** [comment]
相同问题 ，HA里的musicASS可以，jellyfin不行

**Comment by 810517583** [comment]
现在jellyfin可以找到，就是不能播放，我还一直以为是我自己的问题

**Comment by yzlnew** [comment]
这个问题我研究过，只要想办法把音乐的地址变成网络地址，可以通过 play_media 直接播放。

**Comment by 810517583** [comment]
> 这个问题我研究过，只要想办法把音乐的地址变成网络地址，可以通过 play_media 直接播放。 这个和原楼是一致的。

对了，用HA里的musicassistant推送 的时候，HA的卡片暂停键的卡片是失效的

**Comment by 810517583** [comment]
> 这个问题我研究过，只要想办法把音乐的地址变成网络地址，可以通过 play_media 直接播放。 这个和原楼是一致的。

还有一点，jellyfin的DLNA有很多的配置文件，不知道能不能用，我记得1-2年前我是有用JELLY成功推送过的

**Comment by 810517583** [comment]
> 这个问题我研究过，只要想办法把音乐的地址变成网络地址，可以通过 play_media 直接播放。 这个和原楼是一致的。

你最近还在研究么?要不要加个好友，有什么进展可以交流下，我今天查到说如果环境里有docker什么的也会影响，哪怕jellyfin不在docker里，我打算用windows的jelly测试下

**Comment by SodaWithoutSparkles** [comment]
> > 这个问题我研究过，只要想办法把音乐的地址变成网络地址，可以通过 play_media 直接播放。 这个和原楼是一致的。
> 
> 还有一点，jellyfin的DLNA有很多的配置文件，不知道能不能用，我记得1-2年前我是有用JELLY成功推送过的

这个的问题是jellyfin没有办法获取播放讯息，所以播放失败了。详情看 jellyfin/jellyfin#9963，和我上面说的一样

The issue is that jellyfin cannot obtain player control information, so the playback failed as said above.

**Comment by 810517583** [comment]
> > > 这个问题我研究过，只要想办法把音乐的地址变成网络地址，可以通过 play_media 直接播放。 这个和原楼是一致的。
> > 
> > 
> > 还有一点，jellyfin的DLNA有很多的配置文件，不知道能不能用，我记得1-2年前我是有用JELLY成功推送过的
> 
> 这个的问题是jellyfin没有办法获取播放讯息，所以播放失败了。详情看 [jellyfin/jellyfin-plugin-dlna#39](https://github.com/jellyfin/jellyfin-plugin-dlna/issues/39) ，和我上面说的一样
> 
> The issue is that jellyfin cannot obtain player control information, so the playback failed as said above.



> > > 这个问题我研究过，只要想办法把音乐的地址变成网络地址，可以通过 play_media 直接播放。 这个和原楼是一致的。
> > 
> > 
> > 还有一点，jellyfin的DLNA有很多的配置文件，不知道能不能用，我记得1-2年前我是有用JELLY成功推送过的
> 
> 这个的问题是jellyfin没有办法获取播放讯息，所以播放失败了。详情看 [jellyfin/jellyfin-plugin-dlna#39](https://github.com/jellyfin/jellyfin-plugin-dlna/issues/39) ，和我上面说的一样
> 
> The issue is that jellyfin cannot obtain player control information, so the playback failed as said above.

这个问题是最近的版本才会吗？是jellyfin本身的问题还是DLNA被阉割了部分

**Comment by SodaWithoutSparkles** [comment]
> 这个问题是最近的版本才会吗？是jellyfin本身的问题还是DLNA被阉割了部分

正如上述：
> 小爱音箱的DLNA服务是部分阉割的，无法直接使用

**Comment by 810517583** [comment]
HA里的musicassistant可以查到到小爱音箱的DLNA xml文件，但是复制到jellyfin说是格式不支持，也不知道怎么使用
[soundxml.zip](https://github.com/al-one/hass-xiaomi-miot/files/14355934/soundxml.zip)

**Comment by yzlnew** [comment]
@810517583 没有用过 jellyfin 来播放，我试过直接用 webdav 的地址播放音频文件。

**Comment by 810517583** [comment]
> @810517583 没有用过 jellyfin 来播放，我试过直接用 webdav 的地址播放音频文件。

EMBY有这种问题吗？或者类似的软件

**Comment by SodaWithoutSparkles** [comment]
> HA里的musicassistant可以查到到小爱音箱的DLNA xml文件，但是复制到jellyfin说是格式不支持，也不知道怎么使用
> [soundxml.zip](https://github.com/al-one/hass-xiaomi-miot/files/14355934/soundxml.zip)
> 

我一会看看这个行不行 https://github.com/jellyfin/jellyfin/issues/6118

**Comment by 810517583** [comment]
> > HA里的musicassistant可以查到到小爱音箱的DLNA xml文件，但是复制到jellyfin说是格式不支持，也不知道怎么使用
> > [soundxml.zip](https://github.com/al-one/hass-xiaomi-miot/files/14355934/soundxml.zip)
> 
> 我一会看看这个行不行 [jellyfin/jellyfin#6118](https://github.com/jellyfin/jellyfin/issues/6118)
有结果吗
