### ISSUE TITLE
Please add more functions for Mijia DD Combination Washer Dryer 10kg

### ISSUE THREAD

**Issue by diemon24** [al-one/hass-xiaomi-miot#1194]
### Device model / 设备型号

[Mijia DD Combination Washer Dryer 10kg](https://home.miot-spec.com/s/mibx5.washer.v10)

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

please add more sensors and switches from this attributes for management from HA

I have only this:
![IMG_2198](https://github.com/al-one/hass-xiaomi-miot/assets/91910101/472acda6-dd94-4be2-989a-784564e43a62)

And I see more attributes:
![IMG_2197](https://github.com/al-one/hass-xiaomi-miot/assets/91910101/b0b823b7-545b-4333-aa70-09d7780a6fc7)

### Entity attributes / 实体属性

![IMG_2197](https://github.com/al-one/hass-xiaomi-miot/assets/91910101/c1a89ec1-6b58-4473-9563-3cd16917d14d)

**Comment by diemon24** [comment]
example management options in mi home app:
![IMG_2200](https://github.com/al-one/hass-xiaomi-miot/assets/91910101/8d35df1f-97da-4aac-8980-5f6f5c483d9f)

**Comment by diemon24** [comment]
And please add sensor state automation detergent supply. mi home app have empty state

![IMG_2207](https://github.com/al-one/hass-xiaomi-miot/assets/91910101/5a82133e-68df-4f5d-903d-8dd37a27adad)

**Comment by al-one** [comment]
Try master branch.

**Comment by diemon24** [comment]
> Try master branch.

What do you have in mind?

**Comment by diemon24** [comment]
> Try master branch.

This is works! thx you very much! 

<img width="249" alt="image" src="https://github.com/al-one/hass-xiaomi-miot/assets/91910101/6927d28c-8272-4b60-b397-1c114c38a3d5">

<img width="256" alt="image" src="https://github.com/al-one/hass-xiaomi-miot/assets/91910101/fef50886-ea28-4d86-b923-71b5cc79924f">
