### ISSUE TITLE
[Supported Devices]已支持设备收集

### ISSUE THREAD

**Issue by al-one** [al-one/hass-xiaomi-miot#12]
如果您使用本插件成功接入设备，请留下您的设备型号，或者为已有的回复点赞👍🏻

回复格式如下：
```markdown
xiaomi.aircondition.mt1
```

如果您的设备需要开启[miot_cloud](https://github.com/al-one/hass-xiaomi-miot#configuration-xiaomi-cloud)或通过账号接入才可以使用的话，请回复：
```markdown
xiaomi.wifispeaker.x08c(cloud)
```

---

从[v0.4.2](https://github.com/al-one/hass-xiaomi-miot/releases/latest)版本开始，本插件新增了收集支持本地miot协议的设备型号( https://github.com/al-one/hass-xiaomi-miot/commit/d9a2579bb003813feb22fc990b7e4b30d3dd58ad )，如果想根据型号查询更多的设备信息，可通过[小米/米家产品库](https://home.miot-spec.com/)查询

**Comment by al-one** [comment]
xiaomi.aircondition.mt1

**Comment by al-one** [comment]
xiaomi.aircondition.mt5

**Comment by al-one** [comment]
xiaomi.aircondition.mc5

**Comment by al-one** [comment]
xiaomi.wifispeaker.x08c

**Comment by al-one** [comment]
isa.camera.hlc6(cloud)

**Comment by al-one** [comment]
yeelink.light.fancl1

**Comment by womeimingzi11** [comment]
dmaker.fan.p9

**Comment by womeimingzi11** [comment]
dmaker.fan.p10

**Comment by womeimingzi11** [comment]
cuco.plug.cp1

**Comment by womeimingzi11** [comment]
chuangmi.plug.212a01

**Comment by forlover** [comment]
lumi.airer.acn01(cloud)

**Comment by anschein** [comment]
zhimi.airpurifier.va1
yeelink.bhf_light.v5(cloud)
cgllc.airmonitor.s1(cloud)
yunmi.waterpuri.lx11
lumi.curtain.hagl05
xiaomi.aircondition.mc5
xiaomi.wifispeaker.lx06(cloud)
zhimi.toilet.va1(cloud)功能不全
zhimi.heater.ma3
xiaomi.wifispeaker.lx05(cloud)

**Comment by mikeinblue** [comment]
lumi.acpartner.mcn02(cloud)

**Comment by womeimingzi11** [comment]
xiaomi.wifispeaker.l7a

**Comment by mikeinblue** [comment]
chuangmi.camera.ipc021(cloud)
mijia.camera.v1(cloud)

**Comment by miklosandras** [comment]
mijia.camera.v3(cloud)

**Comment by womeimingzi11** [comment]
chuangmi.camera.029a02(cloud)

**Note: Please set  `video_attribute: 1 or 2 (recommanded) or 3` to the `camera.entity_id` in the customize.yaml**

**Comment by karolzamosc** [comment]
chuangmi.camera.ipc009(cloud)

**Comment by rege245** [comment]
mijia.camera.v3 work via cloud, but no audio. it is possible to get one way audio from camera?

**Comment by adnn-hassio** [comment]
chuangmi.camera.ipc019 is it supported.  Everything seems good in config.yaml, i always get this warning..
Login attempt failed
Login attempt or request with invalid authentication from x.x.x. See the log for details.

**Comment by xuefer** [comment]
chunmi.ihcooker.v1(cloud)

**Comment by xuefer** [comment]
https://github.com/rytilahti/python-miio/issues/627

**Comment by xuefer** [comment]
> zhimi.airpurifier.va1
> yeelink.bhf_light.v5(cloud)
> cgllc.airmonitor.s1(cloud)
> yunmi.waterpuri.lx11
> lumi.curtain.hagl05
> xiaomi.aircondition.mc5
> xiaomi.wifispeaker.lx06(cloud)
> zhimi.toilet.va1(cloud)功能不全
> zhimi.heater.ma3
> xiaomi.wifispeaker.lx05(cloud)

xiaomi.wifispeaker.lx05 cannot connect

**Comment by cwt0490** [comment]
lumi.switch.l3acn3(cloud)

**Comment by al-one** [comment]
xiaomi.wifispeaker.lx04(cloud)

**Comment by al-one** [comment]
midr.rv_mirror.v1(cloud)

**Comment by al-one** [comment]
viomi.hood.v1(cloud)

**Comment by al-one** [comment]
minij.washer.v14(cloud)

**Comment by al-one** [comment]
miaomiaoce.sensor_ht.t2(cloud)

**Comment by al-one** [comment]
chuangmi.plug.v3(cloud)
chuangmi.plug.m3(cloud)

**Comment by sonicmingit** [comment]
心想胶囊机
`scishare.coffee.s1102(cloud)`
控制开关和查看开关状态

**Comment by Benny2102** [comment]
chuangmi.camera.021a04

**Comment by wang2879644** [comment]
zhimi
zhimi.fan.za4
客厅
Xiaomi Miot Auto
-
小米AX3600
xiaomi
xiaomi.router.r3600
Xiaomi Miot Auto
-
床头灯（右） light
yeelink
yeelink.light.ml2
卧室
Xiaomi Miot Auto
-
床头灯（左） light
yeelink
yeelink.light.ml2
卧室
Xiaomi Miot Auto
-
晾衣架
mrbond
mrbond.airer.m1s
Xiaomi Miot Auto
-
次卧空调
lumi
lumi.acpartner.v1
次卧
Xiaomi Miot Auto
-
次卧窗帘
leshi
leshi.curtain.v0001
次卧
Xiaomi Miot Auto
-
氛围灯
chuangmi
chuangmi.plug.m1
Xiaomi Miot Auto
-
浴霸
viomi
viomi.bhf_light.v1
浴室
Xiaomi Miot Auto
-
电饭煲 Cooker
imibar
imibar.cooker.mbihr3
Xiaomi Miot Auto
-
门锁
lumi
lumi.lock.mcn01
玄关
Xiaomi Miot Auto

**Comment by PWSteal** [comment]
SWDK ZDG300 mop robot kxf321.mop.mo001(cloud)

**Comment by blakadder** [comment]
zhimi.heater.na1 works in local and cloud mode

**Comment by loanon** [comment]
opple.light.tablgt

**Comment by blakadder** [comment]
zhimi.fan.za4(cloud)

**Comment by GuryYu** [comment]
xiaomi.aircondition.c16

**Comment by Sihan001** [comment]
cloud:
viomi.oven.so1 云米蒸烤机
chunmi.cooker.k1pro1 小米压力电饭煲
cuco.plug.cp2 goshung 16A 插座
viomi.bhf_light.v1 云米浴霸
viomi.hood.c1 云米抽烟机
chuangmi.camera.ipc009 小米云台360摄像头
local:
mrbond.airer.m1s 绑先生晾衣机

<img width="349" alt="截屏2021-06-10 15 52 07" src="https://user-images.githubusercontent.com/9584451/121488123-5b47a000-ca05-11eb-8a41-b4396a19e067.png">

<img width="355" alt="截屏2021-06-10 15 52 00" src="https://user-images.githubusercontent.com/9584451/121488153-64387180-ca05-11eb-86b6-be7525a370c7.png">

<img width="353" alt="截屏2021-06-10 15 51 50" src="https://user-images.githubusercontent.com/9584451/121488185-6bf81600-ca05-11eb-981a-5b63ae5c25e7.png">

<img width="353" alt="截屏2021-06-10 15 51 42" src="https://user-images.githubusercontent.com/9584451/121488221-74e8e780-ca05-11eb-80e7-ea3abb3334b0.png">

<img width="366" alt="截屏2021-06-10 15 51 34" src="https://user-images.githubusercontent.com/9584451/121488234-79ad9b80-ca05-11eb-9aec-d7515a416327.png">

<img width="347" alt="截屏2021-06-10 15 51 13" src="https://user-images.githubusercontent.com/9584451/121488276-83370380-ca05-11eb-8d68-00a477616999.png">

<img width="351" alt="截屏2021-06-10 15 52 21" src="https://user-images.githubusercontent.com/9584451/121488321-8df19880-ca05-11eb-953d-71d255152e5b.png">

**Comment by HeHang0** [comment]
#### chuangmi.plug.212a01(cloud) （米家智能插座2 蓝牙网管版）
#### zimi.switch.dhkg01(cloud) （米家智能开关 单开单控）
#### lemesh.switch.sw0a01(cloud) （mesh通断器）
#### lumi.acpartner.mcn02(cloud) （米家空调伴侣2）
#### xiaomi.wifispeaker.lx05(cloud) (播放后按钮状态未更新) （小爱音响Play）
#### miaomiaoce.sensor_ht.t2(cloud) （米家蓝牙温湿度计2）
#### isa.magnet.dw2hl(cloud) (状态更新有延迟，5秒内开关门hass无法检测到) （小米门窗传感器2）

**Comment by shtljs** [comment]
MODEL:    chuangmi.camera.ipc021
小米云台摄像机2kpro 有设备，但是视频卡顿，几乎不能看

**Comment by shtljs** [comment]
MODEL:    lumi.sensor_motion.v2
小米人体感应 一直有人状态

**Comment by blakadder** [comment]
viomi.vacuum.v18 - Viomi S9 UV (EU Version)

**Comment by League2EB** [comment]
@al-one can support isa.camera.hlc7?
thx all

**Comment by L1cardo** [comment]
> #### chuangmi.plug.212a01 （米家智能插座2 蓝牙网管版）
> #### zimi.switch.dhkg01(cloud) （米家智能开关 单开单控）
> #### lemesh.switch.sw0a01(cloud) （mesh通断器）
> #### lumi.acpartner.mcn02 （米家空调伴侣2）
> #### xiaomi.wifispeaker.lx05(cloud) (播放后按钮状态未更新) （小爱音响Play）
> #### miaomiaoce.sensor_ht.t2(cloud) （米家蓝牙温湿度计2）
> #### isa.magnet.dw2hl(cloud) (状态更新有延迟，5秒内开关门hass无法检测到) （小米门窗传感器2）

兄弟，温湿度传感器2 怎么连接呀？ 我是在docker中运行了ha，然后蓝牙也可以在docker中使用，但是一直不能获取温度信息

**Comment by wang2879644** [comment]
用云端模式接入ha就能显示




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月9日(星期一) 凌晨0:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [al-one/hass-xiaomi-miot] [Supported Devices]已支持设备收集 (#12)





  
chuangmi.plug.212a01 （米家智能插座2 蓝牙网管版）
 
zimi.switch.dhkg01(cloud) （米家智能开关 单开单控）
 
lemesh.switch.sw0a01(cloud) （mesh通断器）
 
lumi.acpartner.mcn02 （米家空调伴侣2）
 
xiaomi.wifispeaker.lx05(cloud) (播放后按钮状态未更新) （小爱音响Play）
 
miaomiaoce.sensor_ht.t2(cloud) （米家蓝牙温湿度计2）
 
isa.magnet.dw2hl(cloud) (状态更新有延迟，5秒内开关门hass无法检测到) （小米门窗传感器2）
  
兄弟，温湿度传感器2 怎么连接呀？ 我是在docker中运行了ha，然后蓝牙也可以在docker中使用，但是一直不能获取温度信息
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Reykoil** [comment]
> #### chuangmi.plug.212a01 （米家智能插座2 蓝牙网管版）
> #### zimi.switch.dhkg01(cloud) （米家智能开关 单开单控）
> #### lemesh.switch.sw0a01(cloud) （mesh通断器）
> #### lumi.acpartner.mcn02 （米家空调伴侣2）
> #### xiaomi.wifispeaker.lx05(cloud) (播放后按钮状态未更新) （小爱音响Play）
> #### miaomiaoce.sensor_ht.t2(cloud) （米家蓝牙温湿度计2）
> #### isa.magnet.dw2hl(cloud) (状态更新有延迟，5秒内开关门hass无法检测到) （小米门窗传感器2）

为什么我的 米家空调伴侣2 只有连接了cloud才能使用？

**Comment by MageDelfador** [comment]
xiaomi.tv.rmh1

**Comment by FaintGhost** [comment]
yeelink.light.lamp22(automatic)

**Comment by sctale** [comment]
我一共接入了8个设备，以下5款上面没人提到：
dooya.curtain.m5（杜亚新款电动窗帘）
deerma.humidifier.jsq1（米家智能加湿器）
yeelink.light.nl1（米家蓝牙夜灯，通过小爱音箱蓝牙mesh接入）
lumi.sensor_gas.mcn02（小米天然气报警器，新版的，WIFI接入，带蓝牙网关）
lumi.sensor_smoke.mcn02（小米烟雾报警器，通过蓝牙mesh接入，接入的实体信息很少，只有一个工作中的实体和电量实体）

**Comment by HandisableL** [comment]
xiaomi.wifispeaker.l15a(小爱音响AI升级版)
yeelink.light.ceiling17(yeelight韶华吸顶灯)
philips.light.downlight(飞利浦筒灯)
yeelink.light.color2(yeelight彩光灯泡V2)
cgllc.magnet.hodor(青萍门窗开合传感器)
zimi.switch.dhkg02(米家智能开关 双开单控)
chunmi.cooker.eh1(米家小饭煲,只支持显示温度,工作状态,)
isa.switch.kg01hl(米家屏显开关 单开单控)

**Comment by uleatest** [comment]
lumi.switch.n3acn3(cloud) Aqara智能墙壁开关 D1（零火线三键版）
lumi.switch.b2nacn02(cloud) Aqara智能墙壁开关 D1（零火线双键版）
lumi.switch.b1nacn02(cloud) Aqara智能墙壁开关 D1（零火线单键版）
lumi.weather.v1 Aqara(cloud) 温湿度气压传感器
yuemee.airmonitor.mhfd1(cloud)  霍尼韦尔甲醛传感器(JQJCY01YM 小米商城卖的那款)
lumi.flood.bmcn01(cloud) 小米水浸卫士
lumi.airrtc.tcpecn01(cloud) 绿米空调温控器(牌子印的是EigenStone) 
lumi.gateway.v3(cloud) 

cloud状态是从开发者工具选择实体后看state_updater: cloud确认到的, 是这样操作的吗?

关于霍尼韦尔甲醛传感器, Miot Auto识别了电池, 温度, 环境(默认值是湿度), 但是没有为甲醛值单独生成一个实体,但是在环境实体的属性中, 可以看到甲醛值(environment.hcho_density), 目前临时用template sensor来读取这个属性, 已反馈大佬.
`template: 
  - sensor:
      - name: "甲醛"
        unit_of_measurement: "ug/m³"
        state: 
          "{{ state_attr('sensor.yuemee_mhfd1_5148_environment', 'environment.hcho_density') }}"

**Comment by Jo-Jo1987** [comment]
https://home.miot-spec.com/spec/chuangmi.gateway.ipc011

**Comment by cyh801** [comment]
mijia.vacuum.v2 有些功能不全对比米家App

**Comment by fi6** [comment]
zhimi.heater.ma5
在设置preset为ll heating设置时会报错（但能成功设置）

**Comment by mywp** [comment]
yeelink.light.ceil38
本地模式无法连接和控制

**Comment by emilianogetino** [comment]
Mi Water Purifier H600G
[https://home.miot-spec.com/s/chunmi.waterpuri.600f2](url)

no info:
  -  Water_Purifier Total Dissolved Solids Sensor for Output Water
  - water consuption detail

**Comment by Thnowing** [comment]
qjiang.acpartner.wb20
ICX智能空调遥控器

**Comment by AJEvans3** [comment]
dmaker.humidifier.p2
