### ISSUE TITLE
lumi.sensor_magnet.v2 status is not refreshing

### ISSUE THREAD

**Issue by trancestor** [al-one/hass-xiaomi-miot#121]
Hello im new in the Home Assistant Community. I just downloaded Hacs and installed the Intigration. I tryed hass-xiaomi-miot and the auto version but bough got the same issue. My Sensors are showing always only one status "closed" Window or Door.. The lumi.weather.v1 Sensor for indoor is working perfectly. Is there any bug currenty for the Door/Window Sensors?

![sensor status](https://user-images.githubusercontent.com/16270742/124488394-1585b980-ddb0-11eb-816d-fd400a4b1ac4.png)

Note: Geschlossen means closed

Edit: I use a Xiaomi Mijia Aqara Gateway (lumi.gateway.mieu01) and in my Xiaomi Home App the Sensors are showing the Status correctly.

**Comment by al-one** [comment]
The default update frequency of the binary_sensor entity is 30 seconds, so if the door is opened and closed within 30 seconds, the state will not be accurately obtained.
You can modify the update frequency by adding custom entity attributes:
```yaml
binary_sensor.magnet_entity_id:
  interval_seconds: 3
```

**Recommended** [Customization Using The UI](https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui):

> [⚙️ Configuration](https://my.home-assistant.io/redirect/config) > 🖌 Customize > 🔍 Select Entity > Add Other Attribute

**Comment by trancestor** [comment]
> The default update frequency of the binary_sensor entity is 30 seconds, so if the door is opened and closed within 30 seconds, the state will not be accurately obtained.
> You can modify the update frequency by adding custom entity attributes:
> 
> ```yaml
> binary_sensor.magnet_entity_id:
>   interval_seconds: 3
> ```
> 
> **Recommended** [Customization Using The UI](https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui):
> 
> > [⚙️ Configuration](https://my.home-assistant.io/redirect/config) > 🖌 Customize > 🔍 Select Entity > Add Other Attribute

First, thx for your answer, u are the first who helped me with this issu. But I already changed the Interval Time and the Status is still the Same. I can open the Window for 1 Hour and no change at all :( BTW the Battery Status is also not showing of. From the Temperatur Sensor i see the Battery health.

**Comment by al-one** [comment]
Use the HA service and get results in notifications.
```yaml
service: xiaomi_miot.get_device_data
data:
  entity_id: binary_sensor.magnet_entity_id # change it
  type: prop
  key: device_log
  limit: 1
```

**Comment by trancestor** [comment]
Can u explain me that a bit more pls? Im new in this and my english is not that good. :(

**Comment by trancestor** [comment]
Do u mean this interface?
![dienst_ha](https://user-images.githubusercontent.com/16270742/124613224-4bd83d00-de73-11eb-893b-2b2a28807a1b.png)

**Comment by al-one** [comment]
Yes. You will get a new notification in left sidebar.

**Comment by al-one** [comment]
OK. I'll fix it tomorrow.

**Comment by trancestor** [comment]
Thank you so much

**Comment by al-one** [comment]
Fixed in commit: https://github.com/al-one/hass-xiaomi-miot/commit/c5df88da8bc0325bec50ae2fce58b2aa3f9b5e5c

**Comment by trancestor** [comment]
Important as Node. Deinstall the old Intigration. Reboot, install the Intigration and Reboot. For me this was the only way to get it working after fix. 

@al-one thx for your help u made my day <3

**Comment by al-one** [comment]
Integration without uninstallation, just restart HA after overwriting the component files.
