### ISSUE TITLE
可以增加支持Aqara VRF设备么？

### ISSUE THREAD

**Issue by firesunCN** [al-one/hass-xiaomi-miot#122]
型号：lumi.airrtc.vrfegl01
控制中央空调的设备，还就是中宏代工的
https://post.smzdm.com/p/715965/

THX

**Comment by al-one** [comment]
未找到与型号`lumi.airrtc.vrfegl01`对应的miot-spec urn
https://miot-spec.org/miot-spec-v2/instances?status=released

**Comment by luyishisan** [comment]
顶上来，i need vrf

**Comment by al-one** [comment]
@luyishisan 有其他的VRF可以替代，并支持通过本插件接入HA
https://home.miot-spec.com/s/vrf%20gateway

**Comment by luyishisan** [comment]
- [ ] @al-one 我已经部署了绿米zigbee的VRF了。现在是通过M1S接入的米家。主要的困难，就是如何将现在这个Zigbee的VRF 通过 auto导入到HA。vrf在米家里面是以一个温控器设备展示的，使用起来非常不方便。但是在homekit里面，就能独立显示。我又想双套接入，不想放弃米家。（大概这个需求，已经持续了2年了，一直没有特别好的解决方案。）
- [ ] 我目前看到的，前几天在.hassbian上的解决方案，是用homekit 控制器反向接入到米家。

**Comment by al-one** [comment]
本插件仅能通过云端模式支持ZigBee子设备，而云端模式下需要厂商定义[miot-spec](https://home.miot-spec.com/spec/lumi.airrtc.vrfegl01)，很不幸的是，该设备的miot规格未被定义。
