### ISSUE TITLE
dreame.vacuum.mc1808 Translation missing on speed parameters

### ISSUE THREAD

**Issue by dinde** [al-one/hass-xiaomi-miot#1223]
### Device model / 设备型号

dreame.vacuum.mc1808

### Component version / 插件版本

0.7.10

### HA core version / HA版本

2023.7.3

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

Firmware: 4.3.3_1122@Linux

Settings are in Chinese
![image](https://github.com/al-one/hass-xiaomi-miot/assets/5851544/735be1e1-cd4c-4af1-89b7-f68270ee7d8b)

### Entity attributes / 实体属性

Not required

### Home Assistant Logs / 系统日志

None needed

**Comment by pomianowski** [comment]
Same for `ijai.vacuum.v3`

Device: **ijai.vacuum.v3**
Device firmware: **4.3.3_0048**
MIOT manually installed from: https://github.com/al-one/hass-xiaomi-miot/commit/08e51e701124a97a9b6ed087e74354158d1c8a42

List of words to translate for `fan_speed`:
 - 关
 - 节能
 - 标准
 - 强劲

List of words to translate for `water_state`:
 - 低
 - 中
 - 高

I'd love to help with the translation myself, but I don't quite understand the structure of the project

![image](https://github.com/al-one/hass-xiaomi-miot/assets/13592821/eacbf9f6-4797-459a-abf1-0313fb38fee7)
![image](https://github.com/al-one/hass-xiaomi-miot/assets/13592821/f8c789cd-cf5d-4ba4-8fec-9ac72dd3b84e)

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/842#issuecomment-1275964389

**Comment by dinde** [comment]
@al-one : Thanks for that. It indeed fixed it !
