### ISSUE TITLE
yeelink.light.ceiling1 missing features

### ISSUE THREAD

**Issue by Styx85** [al-one/hass-xiaomi-miot#1225]
When I add this lamp via the yeelight integration into home assistant I got shown a nightmode sensor (wonder if it is really integrated into this type of lamp) and there are several programs available. In the Xiomi Miot integration they are not shown. See Screenshots attached.
Is there any possibility to integrate these?
![yeelight 1 yeelight a](https://github.com/al-one/hass-xiaomi-miot/assets/32103696/ce735a2d-25dd-444b-a497-8f8aeaee9a90)
![yeelight 1 yeelight b](https://github.com/al-one/hass-xiaomi-miot/assets/32103696/fb1eb669-c44b-4f9c-a1a9-279ad61d112a)

![yeelight 1 miot a](https://github.com/al-one/hass-xiaomi-miot/assets/32103696/7f68d487-0c4c-4042-bb4d-5c4310ff4dae)
![yeelight 1 miot b](https://github.com/al-one/hass-xiaomi-miot/assets/32103696/2199b481-b7a1-4720-a1c4-b6c92cdad609)

**Comment by al-one** [comment]
Does not have any related properties in it‘s [miot-spec](https://home.miot-spec.com/spec/yeelink.light.ceiling1).
