### ISSUE TITLE
EraClean Max 冰箱除味杀菌器（EraClean Intelligent deodorizer）

### ISSUE THREAD

**Issue by mywp** [al-one/hass-xiaomi-miot#1226]
### Device model / 设备型号

era.airp.cwb03

### HA core version / HA版本

 20230705.1 - latest

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

怎么适配这个蓝牙设备？EraClean Max 冰箱除味杀菌器（EraClean Intelligent deodorizer）

### Entity attributes / 实体属性

无

**Comment by keniji** [comment]
我也刚买了一个，这玩意貌似是需要手机直连才能控制不能通过网关，感觉上当了…

**Comment by keniji** [comment]
https://github.com/dentra/esphome-components/tree/master/components/miot_cwbs01
找到这个不过暂时没看懂是怎么用的，因为这个integration似乎只配了binary sensor…

**Comment by al-one** [comment]
无法支持

**Comment by zz66** [comment]
> https://github.com/dentra/esphome-components/tree/master/components/miot_cwbs01 找到这个不过暂时没看懂是怎么用的，因为这个integration似乎只配了binary sensor…

这个是esphome的集成，我基本照抄配置，HA成功识别。多谢你的提示。
![Screenshot_2024-12-19-14-50-38-620_io homeassistant companion android-edit](https://github.com/user-attachments/assets/56d4baa9-9292-41de-92a7-9309b31730e7)
![Screenshot_2024-12-19-14-50-54-787_io homeassistant companion android-edit](https://github.com/user-attachments/assets/c65346d2-6350-438e-8763-d28c934ead4b)
