### ISSUE TITLE
暂不支持lumi.sensor_switch.aq3

### ISSUE THREAD

**Issue by firesunCN** [al-one/hass-xiaomi-miot#123]
目前还不支持添加aqara迷你开关
型号：lumi.sensor_switch.aq3

https://community.home-assistant.io/t/zha-aqara-wireless-mini-switch-model-lumi-sensor-swit/269157

**Comment by al-one** [comment]
无线开关无法支持，也暂时不会考虑适配。因为无线开关是基于miot事件的，而本插件仅可以轮询方式查询设备状态，无法接收事件。

**Comment by firesunCN** [comment]
已用Xiaomi Gateway 3+小米网关2解决
