### ISSUE TITLE
共享家庭后登录账号提示“该小米账号下没有设备”

### ISSUE THREAD

**Issue by uleatest** [al-one/hass-xiaomi-miot#1235]
米家账户A是管理员，将整个家庭共享给米家账户B（无论是将账户B设为管理员或成员），账户B通过共享后，在miot auto中登录B账号（选择账号集成方式登录）， 跳出提示“该小米账号下没有设备”。

如果米家账户A把某几个设备共享给账户B，此时在miot auto中登录B账号，可以成功更新到所有已接受共享的设备。

miot auto版本：0.7.10
HA版本:2023.8.0

**Comment by al-one** [comment]
暂不支持集成直接通过米家共享家庭的设备，请通过共享单个设备集成。

> https://github.com/al-one/hass-xiaomi-miot/issues/1123#issuecomment-1569963041

**Comment by uleatest** [comment]
大佬，不得已只能选共享整个家庭，因为发现米家APP内，只能共享WIFI类或蓝牙类的设备，如果是ZIGBEE类的设备，都跳不出共享的选项，大佬也遇到过这种情况吗？

> 暂不支持集成直接通过米家共享家庭的设备，请通过共享单个设备集成。
> 
> > [#1123 (comment)](https://github.com/al-one/hass-xiaomi-miot/issues/1123#issuecomment-1569963041)

**Comment by uleatest** [comment]
等大佬之后开发共享家庭接入啦，先关了这个提问。

**Comment by al-one** [comment]
现已支持读取共享家庭中的设备。
