### ISSUE TITLE
设备各个子实体集成到一个实体

### ISSUE THREAD

**Issue by AgaigetS** [al-one/hass-xiaomi-miot#1240]
我通过账号集成了一个落地风扇，设备包含的所有实体如图：
![image](https://github.com/al-one/hass-xiaomi-miot/assets/24350317/965dc18c-02b7-43f1-a28d-d1711f0d7d2b)

这个是根实体里面包含的属性，可以看到只包含了水平摇头、风速等，并没有包含所有控制开关
![image](https://github.com/al-one/hass-xiaomi-miot/assets/24350317/d8403771-606f-48fe-b143-23fe2c1c7342)

这样导致我加入homekit的时候，一个实体里面包含了水平摇头、风速等一些设置，另外一些实体包含其他开关，比如水平摇头角度等，这样控制起来就不够方便，我希望所有开关都集成在一个实体里面，这样要怎么实现呢？请教大神，刚接触没多久

**Comment by a74074011** [comment]
需要手动编辑`configuration.yaml`生成一个虚拟设备，
参考： https://www.home-assistant.io/integrations/fan.template/
