### ISSUE TITLE
建议优化一些attributes的数据减少数据库大小

### ISSUE THREAD

**Issue by a74074011** [al-one/hass-xiaomi-miot#1242]
例如净化器的主设备的attributes有 Environment.pm2_5_density  Air_purifier.fan_level 这些数据，
但是这些参数在设备的传感器实体中同样也有，导致会记录一些重复数据。

实体的attributes数据只要其中任意一部分变化都会存储完整的attributes，
尤其是传感器实体会有个Updated_time，每分钟会更新2次，
这就导致每个设备的大量传感器都会保存下Updated_time导致的重复数据。

而主设备实体的attributes几乎存在所有的传感器数据，
这些数据变动很频繁，导致几乎每次轮询都会再存储完整的attributes。

我观察数据库中几乎有2/3的内容都是这种attributes数据，对于数据库的空间很不友好，
尝试使用recorder: exclude过滤又会导致主要的数据也不会存储了 :(

另外在开发官网中 
https://developers.home-assistant.io/docs/core/entity#advanced-properties 
的上方 DANGER 也建议 removing non-critical attributes 来减少数据库大小

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/blob/master/README_zh.md#filter-entity-attributes

**Comment by a74074011** [comment]
> * https://github.com/al-one/hass-xiaomi-miot/blob/master/README_zh.md#filter-entity-attributes

感谢回复，这个设置能解决大部分的问题

**Comment by latel** [comment]
> > * https://github.com/al-one/hass-xiaomi-miot/blob/master/README_zh.md#filter-entity-attributes
> 
> 感谢回复，这个设置能解决大部分的问题

能分享下你的过滤配置吗，设备类别太多了，每个实体都有好多不重名的属性，一个个的加感觉会累死
