### ISSUE TITLE
Since update of HA to 2023.8.1 version "send_command" for vacuum stopped working (roborock.vacuum.a15)

### ISSUE THREAD

**Issue by Szeryff** [al-one/hass-xiaomi-miot#1247]
**Device model / 设备型号**
roborock.vacuum.m1s

**Component version / 插件版本**
0.7.10

**HA core version / HA版本**
2023.8.1

**The problem / 问题详情**
After update of HA to 2023.8.1 version "send_command" for vacuum device (Roborock S7 - roborock.vacuum.a15) stopped working.
Whenever I try to invoke it I get "Call-service error. Entity _vacuum.robot_miot_cleaner_ does not support this service."

Can you please advise? Unless there is another way to invoke zone cleaning?

**Comment by al-one** [comment]
HA 2023.8.2 and miot v0.7.11 is working.
![xiaomi miot vacuum](https://github.com/al-one/hass-xiaomi-miot/assets/4549099/aa1dc309-b116-419a-8b53-610e6a2048f3)

**Comment by kodbuzz** [comment]
Vacuum Viomi V7, HA 2023.8.2 / Miot v0.7.11

I've been utilizing a script with the Vacuum Map Card to enable the cleaning of specific rooms, but it seems to have stopped functioning properly after the recent update.

_"Failed to call service vacuum.send_command. Entity vacuum.viomi_v7_xxxx_robot_cleaner does not support this service."_

**Comment by Szeryff** [comment]
Same here. Not working. I'm using my script from node red.

sob., 12 sie 2023, 14:52 użytkownik kodbuzz ***@***.***>
napisał:

**Comment by kodbuzz** [comment]
> 

Just as a temporary solution, I made the switch from using "`vacuum.send_command`" to "`xiaomi_miot.send_command`," and it looks like everything is back to working as it should. So far, this can be considered a viable workaround.

**Comment by al-one** [comment]
Try master branch.

**Comment by kodbuzz** [comment]
> Try master branch.

Thank you for addressing this! I see that the issue has been resolved in the Master branch. Great work!

**Comment by al-one** [comment]
> not working for viomi.vacuum.v7 Failed to call service vacuum.send_command. Entity vacuum.viomi_v7_xxxx_robot_cleaner does not support this service if change "vacuum.send_command" to "xiaomi_miot.send_command" i get "extra keys not allowed @ data['command']"

`app_zoned_clean` was originally a built-in command of the roborock vacuum, and the viomi vacuum can only use this command through the `vacuum.send_command` service, and `xiaomi_miot.send_command` can only execute the built-in command of the device.
After successfully upgrading the master branch, the viomi vacuum will be able to use the `app_zoned_clean` and `app_goto_target` commands in the `vacuum.send_command` service, because the component has adapted for them.

**Comment by lameritos** [comment]
Thanks i redownload integration from latest version to master version and all working in vacuum.send_command

**Comment by Szeryff** [comment]
I also confirm working with master version
