### ISSUE TITLE
登录失败，显示“本次登录小米账号需要安全验证，点击这里继续！”。但是mi.com可以登录。

### ISSUE THREAD

**Issue by trueif** [al-one/hass-xiaomi-miot#1248]
![图片](https://github.com/al-one/hass-xiaomi-miot/assets/85400483/12f1e7cc-eb64-4a02-b05e-f1d3148fa5bc)

The login of Xiaomi account needs security verification. Click here to continue!
本次登录小米账号需要安全验证，点击这里继续！你需要在与HA宿主机同局域网的设备下完成安全验证，如果你使用的是云服务器，将无法验证通过。

小米账户登录失败，请检查账号密码。如多次尝试仍登陆失败，请在与当前网络相同的环境下登陆小米官网(mi.com)后重试

**Comment by trueif** [comment]
日志：

Xiaomi serviceLoginAuth2: ['https://account.xiaomi.com/pass/serviceLoginAuth2', {'_json': 'true'}, {'user': XXXX'hash': XXXX'callback': 'https://sts.api.io.mi.com/sts', 'sid': 'xiaomiio', 'qs': '%3Fsid%3Dxiaomiio%26_json%3Dtrue', '_sign': '0psXfr43eNI0IX6q9Suk3qWbRqU='}, {'User-Agent': 'Android-7.1.1-1.0.0-ONEPLUS A3010-136-XXXXAPP/xiaomi.smarthome APPV/62830'}, {'sdkVersion': '3.8.6', 'deviceId': 'XXXX'}]

**Comment by trueif** [comment]
Logger: custom_components.xiaomi_miot.config_flow
Source: custom_components/xiaomi_miot/config_flow.py:301
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 22:08:42 (4 occurrences)
Last logged: 22:10:34

    Setup xiaomi cloud for user: xxxx failed: Login to xiaomi error: &&&START&&&{"notificationUrl":"https://account.xiaomi.com/identity/authStart?sid=xiaomiio&context=obCPJXQDc0a3p7wF6xxxXEVfOkvsV0Fkipqf-JUFzg-Pn5-1HCyTyOt-3qAQYChjDzCrT8e9KHA2hFYQX8SDzKwomfHl3E50s_kcDBoKLxY0TJO1TmNtviN8EU0UWHSB0biKKMmgBjgugBeWRq1ePJFyN5vK_qxHhpw0hXD4-GOsTM4BLQnMHIOE6AQeZrHPlsq1PrG9vwWSxDlrMNPxA-9W7coeqeIeTG2ZWViYebA_6cy43jFshReWMbfJK3HcGqH_6UBNtrXBIXN0PX_-OqIlVnwrBVe96Y3snQOFTzCslCRG9VSOrCEBXqxxxn5gaER3ETQP16KVKEum7xgs4tvTqiokTIzRIA4mihE-EPUyZIyuAXbV_PcPn15Js87gU-_HJZDeUJORp0kuoiD3m6UJi9x_w6OgT_7yDCVYq9vhYEJUpXQb-yFkh1vDu_cTusCFcrmMQ-z0AJIk88u2S9crX0g-Ng2K2mulOoB-b0p_0wvWR5M81cKYNUQVgH1z1o5xirNa1V_vy7HKMV9PHSO9SG49RBbYNguIjPey-c_u31Pq3u1RaM1zGqa5aYH_5ljylQ96-FroKHEoSiBZdL532c5qrSSkqTkiA9xxxjyKjCdo3uVvSj5OFLTjfrYVRGdPOyNl_VRovu6hpkV57hMp79qCVQTolPUDTRe3kmyQqZ2nY3_cN81YBKv&_locale=en_US","result":"ok","code":0,"captchaUrl":null,"description":"成功","location":"","securityStatus":16,"pwd":0,"child":0,"desc":"成功"}

**Comment by trueif** [comment]
请问这种打开一个新页面然后验证的原理是啥？新页面已经验证成功了，显示"ok"，但是旧页面啥反应都没有啊。

**Comment by anqi-sky** [comment]
同样的问题，怎么都无法登录，打开的验证页显示“ok“也没有用。请问有办法解决吗？

**Comment by zhangseammm** [comment]
我也遇到了，头大

**Comment by lotherli** [comment]
有人解决了吗？

**Comment by zhulingbiezhi** [comment]
https://www.ququ123.top/2023/09/homeassistant_xiaomi_login  已经解决

**Comment by zhixuchen** [comment]
同问，找了一圈说是云服务器上无法鉴权，必须在同网段下验证，那如果是部署在云服务器上的就放弃吧，这条路不通了

**Comment by gzh9619** [comment]
> https://www.ququ123.top/2023/09/homeassistant_xiaomi_login 已经解决

无法载入网址

**Comment by ddducn** [comment]
还是不行啊无语死了，没其他登陆方法了吗，跳到验证页面后ok了没反应啊，是在同一网段下。密码也改过了，新账号也注册过，就是死活都不行

**Comment by trueif** [comment]
放弃了xiaomi-miot，改用gateway3+HA里面自己的自动化，硬写自动化逻辑来实现了各种效果。

**Comment by zhulingbiezhi** [comment]
> > https://www.ququ123.top/2023/09/homeassistant_xiaomi_login 已经解决
> 
> 无法载入网址

已经修复了

**Comment by zhouc7037zc** [comment]
> 同问，找了一圈说是云服务器上无法鉴权，必须在同网段下验证，那如果是部署在云服务器上的就放弃吧，这条路不通了

特意买了一台云服务器竟然不行 我干

**Comment by ZhengHaoF** [comment]
解决了，如果是在云服务器上部署的，可以用服务器搭建代理，本地电脑使用代理进行小米账号安全验证

**Comment by dll0922a** [comment]
> 解决了，如果是在云服务器上部署的，可以用服务器搭建代理，本地电脑使用代理进行小米账号安全验证

大神，具体怎么操作的，能不能出个教程？我用的是阿里云服务器

**Comment by avinrock** [comment]
咋关闭了呢，我也是这个问题

**Comment by EdChee012** [comment]
> 解决了，如果是在云服务器上部署的，可以用服务器搭建代理，本地电脑使用代理进行小米账号安全验证

大神，能给个教程吗，找了好久不知道怎么操作

**Comment by al-one** [comment]
@EdChee012 在服务器安装chrome登录小米官网
- https://hub.docker.com/r/alone/chrome-novnc

**Comment by Zhanglk-stack** [comment]
> [@EdChee012](https://github.com/EdChee012) 在服务器安装chrome登录小米官网
> 
> * https://hub.docker.com/r/alone/chrome-novnc

使用这个镜像不管是在容器内的浏览器还是电脑浏览器，登录了小米云后依然不可以

**Comment by Pony888** [comment]
这个问题直到现在版本1.0.16依然存在，有人解决了喊一声啊

**Comment by a3d21** [comment]
今天我也遇到了，试了3个号码，都是这个错误
