### ISSUE TITLE
米家塔扇2（23年3月新款）缺少一些功能

### ISSUE THREAD

**Issue by yyxida** [al-one/hass-xiaomi-miot#1251]
### Device model / 设备型号

[dmaker.fan.p45](https://home.miot-spec.com/s/dmaker.fan.p45)

### Component version / 插件版本

0.7.10

### HA core version / HA版本

2023.8.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

塔扇的控制缺少一些功能，没有切换自然风的类型的选项，缺少手动控制左右微调的功能，另外选择风模式没有汉化不知道是不是我的问题。
![image](https://github.com/al-one/hass-xiaomi-miot/assets/22792135/22af77db-6d8c-4fd6-97c4-02bb9b2e6a14)

### Entity attributes / 实体属性

无实体（貌似）

**Comment by al-one** [comment]
尝试master分支。

**Comment by yyxida** [comment]
> 升级到`v0.7.12`。

![image](https://github.com/al-one/hass-xiaomi-miot/assets/22792135/6c9d3266-97e3-4129-80ee-8ac723e4d684)
![image](https://github.com/al-one/hass-xiaomi-miot/assets/22792135/c558621a-6bd3-4a88-a220-3c0d3717858a)
选风模式仍然是英文，然后自然风选择还是没有，不过手动左右微调已经有了就足够了。
