### ISSUE TITLE
如何才能在homeassistant中查看xiaomi miot的版本号

### ISSUE THREAD

**Issue by otherbanana** [al-one/hass-xiaomi-miot#1254]
请问一下，要如何才能在homeassistant中查看xiaomi miot的版本号啊?怎么找都找不到

**Comment by al-one** [comment]
配置 > 系统 > 修复 > ⋮ > [系统信息](https://my.home-assistant.io/redirect/system_health)

**Comment by otherbanana** [comment]
> 配置 > 系统 > 修复 > `⋮` > [系统信息](https://my.home-assistant.io/redirect/system_health)

找到了，非常感谢大佬
