### ISSUE TITLE
Qingping Air Monitor (cgllc.airmonitor.s1): add TVOC as separate entity

### ISSUE THREAD

**Issue by andrey-yantsen** [al-one/hass-xiaomi-miot#126]
At the moment `tvoc-density` is available only as an attribute and requires some template-sensors magic to draw nice graphs and trigger alerts based on the value.

Please let the value be a separate entity from the start :) [spec/device:air-monitor:0000A008](https://miot-spec.org/miot-spec-v2/spec/device?type=urn:miot-spec-v2:device:air-monitor:0000A008), [spec/service:environment:0000780A](https://miot-spec.org/miot-spec-v2/spec/service?type=urn:miot-spec-v2:service:environment:0000780A)

<img width="345" alt="image" src="https://user-images.githubusercontent.com/629281/124958752-685eab80-e012-11eb-970a-4411db08c20e.png">

**Comment by al-one** [comment]
Try the latest commit of the master branch.

**Comment by andrey-yantsen** [comment]
Working like a charm, thank you!
