### ISSUE TITLE
Aqara 空调伴侣(升级版)自动模式只能识别局域网内的，非局域网的显示不可用，云端模式都正常

### ISSUE THREAD

**Issue by sweetstzw** [al-one/hass-xiaomi-miot#1262]
### Device model / 设备型号

lumi.acpartner.v3

### Component version / 插件版本

0.7.11

### HA core version / HA版本

2023.8.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Aqara 空调伴侣(升级版)自动模式只能识别局域网内的，非局域网的显示不可用，云端模式都正常

### Entity attributes / 实体属性

自动模式下实体不可用
非局域网内的米家台灯 1S也是一样，云端模式都没问题

**Comment by al-one** [comment]
`lumi.acpartner.v3`已经适配了本地读取设备状态，因此在自动模式下会默认本地接入。如果你的设备和HA不在同一局域网，请通过云端模式接入该设备。
