### ISSUE TITLE
WD1-LB Linptech smart electric window opener automatically

### ISSUE THREAD

**Issue by nunokaneco** [al-one/hass-xiaomi-miot#1263]
### Device model / 设备型号

[WD1-LB Linptech](https://home.miot-spec.com/s/linp.wopener.wd1lb)

### Component version / 插件版本

0.7.10

### HA core version / HA版本

Home Assistant 2023.8.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

New device not available in the list of the devices using this integration, can you please added this device? 

Please let me know if you need further information 

Thank you  

### Entity attributes / 实体属性

n/a

### Home Assistant Logs / 系统日志

n/a

**Comment by al-one** [comment]
![linp.wopener.wd1lb](https://github.com/al-one/hass-xiaomi-miot/assets/4549099/a923bd69-eb49-4287-84ef-5b66cb02d016)

**Comment by seeya** [comment]
@nunokaneco do you need a bluetooth mesh device to connect the WD1-LB Linptech? What's the setup like? I'm trying to setup mine with the Xiaomi app but the device keeps saying it's offline.

**Comment by k7franklin** [comment]
> @nunokaneco do you need a bluetooth mesh device to connect the WD1-LB Linptech? What's the setup like? I'm trying to setup mine with the Xiaomi app but the device keeps saying it's offline.

Yes. I'm using an xiaomi mi gateway 3 and it works fine.

I really wish it does local conection, but the delay (about 3s) means the connection depends xiaomi cloud.

If i can use my bluetooth dongle, will be fine!!
