### ISSUE TITLE
调用服务 Xiaomi Miot Auto: Get bindkey 如何正确传参

### ISSUE THREAD

**Issue by yuangezhizao** [al-one/hass-xiaomi-miot#1264]
`米家蓝牙温湿度计 2`想获取`bindkey`以进行登录
<img width="816" alt="image" src="https://github.com/al-one/hass-xiaomi-miot/assets/16861681/4443d978-781f-44ef-b2f1-278ac63604be">
<hr>

1. 先调用`xiaomi_miot: Get token`，得到`did`和`token`
<img width="1223" alt="image" src="https://github.com/al-one/hass-xiaomi-miot/assets/16861681/b6653fb1-3ff4-4984-a5fd-504c4cb0a353">

2. 再调用`Xiaomi Miot Auto: Get bindkey`，实体选择“温度/湿度/电量”结果都返回`null`
<img width="1231" alt="image" src="https://github.com/al-one/hass-xiaomi-miot/assets/16861681/479e1c61-fa55-4832-9ad6-476a184747be">

3. 尝试追加可选参数`did`，结果仍然返回`null`
<img width="1224" alt="image" src="https://github.com/al-one/hass-xiaomi-miot/assets/16861681/d4bacc52-4f9d-49fe-aa17-a0bd16ac2fae">

以上，请问应该如何传入参数？

**Comment by al-one** [comment]
已在master分支中修复，同时`get_token`服务支持获取返回列表中第一个蓝牙设备的`beaconkey`。
> 因此未来的版本可能会移除`get_bindkey`服务。

**Comment by yuangezhizao** [comment]
我这里在`HACS`中更新`master`分支有点儿问题，于是一直在等新版本。现在已升级至`v0.7.12`，确认`get_bindkey`调用成功
<img width="1219" alt="image" src="https://github.com/al-one/hass-xiaomi-miot/assets/16861681/c5e4dd92-cbd4-42ec-a8cf-e8becf284b59">

`get_token`返回结果也有`beaconkey`了
<img width="1231" alt="image" src="https://github.com/al-one/hass-xiaomi-miot/assets/16861681/91a5e536-f384-43a2-a671-508ff8253d34">

感谢大佬的迅速修复~

**Comment by zelong77** [comment]
> 已在master分支中修复，同时`get_token`服务支持获取返回列表中第一个蓝牙设备的`beaconkey`。
> 
> > 因此未来的版本可能会移除`get_bindkey`服务。

beaconkey就是 bindkey 吗?现在 get_token 里又没有 token 了😂

**Comment by js4jiang5** [comment]
剛剛試了一下，Get Token 只有顯示 bindkey，沒有 token
