### ISSUE TITLE
不能控制 YEELIGHT䊹玉吸頂燈

### ISSUE THREAD

**Issue by s04115love** [al-one/hass-xiaomi-miot#1266]
### Device model / 设备型号

yeelink.light.ceiling12

### Component version / 插件版本

0.7.11

### HA core version / HA版本

2023.8.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

可以设备进HA 但点击灯具时 直接提示不可用

### Entity attributes / 实体属性

min_color_temp_kelvin: 2702
max_color_temp_kelvin: 6493
min_mireds: 154
max_mireds: 370
effect_list:
  - Day
  - Night
supported_color_modes:
  - brightness
  - color_temp
  - onoff
friendly_name: 客廳吸頂燈
supported_features: 36

### Home Assistant Logs / 系统日志

Logger: custom_components.xiaomi_miot.light
Source: custom_components/xiaomi_miot/__init__.py:1401
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 下午3:34:05 (937 occurrences)
Last logged: 下午11:38:41

客廳吸頂燈(yeelink.light.ceiling12): Got MiioException while fetching the state: Unable to discover the device 192.168.31.209, mapping: {'light.on': {'siid': 2, 'piid': 1}, 'light.brightness': {'siid': 2, 'piid': 2}, 'light.color_temperature': {'siid': 2, 'piid': 3}, 'light.mode': {'siid': 2, 'piid': 4}, 'light.off_delay_time': {'siid': 2, 'piid': 102}}, max_properties: 10/5
次臥吸頂燈(yeelink.light.ceila): Got MiioException while fetching the state: Unable to discover the device 192.168.31.178, mapping: {'light.on': {'siid': 2, 'piid': 1}, 'light.mode': {'siid': 2, 'piid': 2}, 'light.brightness': {'siid': 2, 'piid': 3}, 'light.color_temperature': {'siid': 2, 'piid': 5}, 'yeelight.init_power_opt': {'siid': 4, 'piid': 1}, 'yeelight.save_state': {'siid': 4, 'piid': 2}, 'yeelight.cron_get': {'siid': 4, 'piid': 5}, 'yeelight.night_time': {'siid': 4, 'piid': 6}, 'yeelight.brightness_with_zero': {'siid': 4, 'piid': 14}}, max_properties: 10/9

**Comment by al-one** [comment]
- 检查设备IP`192.168.31.209` `192.168.31.178`
- 如果IP正确，尝试给灯具断电几分钟
