### ISSUE TITLE
设置了路由表也无法跨网络连接设备

### ISSUE THREAD

**Issue by YiZhong-NAT** [al-one/hass-xiaomi-miot#1267]
### Device model / 设备型号

米家空调插座2代（[lumi.acpartner.mcn02](https://home.miot-spec.com/s/lumi.acpartner.mcn02)）

### Component version / 插件版本

0.7.11

### HA core version / HA版本

Home Assistant 2023.7.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

设置了路由表也无法跨网络连接设备

比如：
192.168.1.1为主路由器（主路由的网段为192.168.1.0/24）
HA所在的ip为192.168.1.2，在192.168.1.2这台机器上配置了路由表，将192.168.2.0 255.255.255.0转发到192.168.1.3
192.168.1.3为子路由器（子路由的网段为192.168.2.0/24）
设备所在ip为192.168.2.2
在192.168.1.2使用miiocli -d device --ip 192.168.2.2 --token **** info，获得返回
```
miio.exceptions.DeviceException: Unable to discover the device 192.168.2.2                                                                                                                           
Error: Unable to discover the device 192.168.77.108
```

确认在添加路由表后，可以ping通192.168.2.2，也可以TCP/UDP连接到子路由里的对应服务，防火墙应该是通了的。

同时确认，在添加路由表后，Xiaomi Gateway 3可以控制下面的电灯。

### Entity attributes / 实体属性

空调插座 Air Conditioner

### Home Assistant Logs / 系统日志

Logger: custom_components.xiaomi_miot.climate
Source: custom_components/xiaomi_miot/__init__.py:1401
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 18:55:50 (115 occurrences)
Last logged: 20:49:55

空调插座(lumi.acpartner.mcn02): Got MiioException while fetching the state: Unable to discover the device 192.168.2.2, mapping: {'air_conditioner.on': {'siid': 2, 'piid': 1}, 'air_conditioner.mode': {'siid': 2, 'piid': 2}, 'target_temperature-2-3': {'siid': 2, 'piid': 3}, 'electric_power-5-1': {'siid': 5, 'piid': 1}, 'match_state-4-1': {'siid': 4, 'piid': 1}, 'ac_work_mode-4-2': {'siid': 4, 'piid': 2}, 'ac_state-4-3': {'siid': 4, 'piid': 3}, 'fan_control.fan_level': {'siid': 3, 'piid': 1}, 'fan_control.vertical_swing': {'siid': 3, 'piid': 2}}, max_properties: 10/9

**Comment by delphicchen** [comment]
我也是類似的狀況，HA server與設備屬於不同子網路，但在路由器上有配置路由，HA server可以ping到設備，不知有沒有辦法指定特定設備走雲端連線解決?

**Comment by YiZhong-NAT** [comment]
> 我也是類似的狀況，HA server與設備屬於不同子網路，但在路由器上有配置路由，HA server可以ping到設備。 但是我重新新增一次帳號集成，但是限制"雲端模式"，再指定另一個子網的設備，然就可以正常運作了。

是的，只使用云端模式可以运作。

**Comment by hyf635269547** [comment]
> 比如： 192.168.1.1为主路由器（主路由的网段为192.168.1.0/24） HA所在的ip为192.168.1.2，在192.168.1.2这台机器上配置了路由表，将192.168.2.0 255.255.255.0转发到192.168.1.3 192.168.1.3为子路由器（子路由的网段为192.168.2.0/24）

这个是小米的问题，禁止非同网段的使用本地模式，如果你的路由器支持源地址nat,可将hass的源地址nat为和小米同一网段,就可以使用本地模式
