### ISSUE TITLE
航天长兴DT-210探测器无实体和属性

### ISSUE THREAD

**Issue by 2Maliao** [al-one/hass-xiaomi-miot#1268]
### Device model / 设备型号

htcx.alarm.dt210

### Component version / 插件版本

0.7.11

### HA core version / HA版本

2023.8.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

这个设备不管是自动模式还是局域网模式，都是可以连接设备，但是没有实体，看不到任何数据
设备信息:https://home.miot-spec.com/s/htcx.alarm.dt210

### Entity attributes / 实体属性

无法显示实体，设备是https://home.miot-spec.com/spec/htcx.alarm.dt210

**Comment by al-one** [comment]
尝试master分支。

**Comment by 2Maliao** [comment]
测试了几天，数据显示都没问题，就是有的数据单位要自己手动添加。支持断网后本地读取。
非常感谢能适配这个设备
