### ISSUE TITLE
Qingping Air Monitor (cgllc.airmonitor.s1): pm2.5 sensor doesn't have unit

### ISSUE THREAD

**Issue by andrey-yantsen** [al-one/hass-xiaomi-miot#127]
So, as the title says — for some reason the unit of measurement is not set for my PM2.5 sensor of Qingping Air Monitor, while for Qingping Air Monitor Lite it shows µg/m³ as it should.

<img width="310" alt="image" src="https://user-images.githubusercontent.com/629281/124960261-099a3180-e014-11eb-8ffd-2c2ec6bd54d8.png">

**Comment by al-one** [comment]
Try the latest commit of the master branch.

**Comment by andrey-yantsen** [comment]
Yup, it has the unit now, thanks!
