### ISSUE TITLE
construct版本写死导致Docker中部署的HA无法加载本插件

### ISSUE THREAD

**Issue by Christ9038** [al-one/hass-xiaomi-miot#1274]
目前插件manifest.json的requirements中写死了construct==2.10.56。但HomeAssistant官方的Docker镜像已经更新construct的版本到2.10.68。容器setup时，pip会尝试更新construct，但没有root权限会失败，导致插件无法加载。我目前临时修改manifest.json中construct的版本到2.10.68，插件可以运行。

**Comment by al-one** [comment]
感谢提醒，为了兼容更多的HA版本，已改为`construct>=2.10.56`

**Comment by Christ9038** [comment]
大佬辛苦
