### ISSUE TITLE
dmaker.fan.p28希望增加手动转头按钮

### ISSUE THREAD

**Issue by 1105169500** [al-one/hass-xiaomi-miot#1277]
### Device model / 设备型号

[dmaker.fan.p28](https://home.miot-spec.com/s/dmaker.fan.p28)

### Component version / 插件版本

最新

### HA core version / HA版本

最新

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

![1](https://github.com/al-one/hass-xiaomi-miot/assets/33370025/2bb9ee14-3369-4754-82c8-da809362644d)
![2](https://github.com/al-one/hass-xiaomi-miot/assets/33370025/22174e16-8199-4116-8978-2f2dec0fa036)
希望能增加手动转头的实体

### Entity attributes / 实体属性

dmaker.fan.p28

### Home Assistant Logs / 系统日志

无

**Comment by al-one** [comment]
尝试master分支。

**Comment by 1105169500** [comment]
已更新 使用正常 感谢

**Comment by 1105169500** [comment]
dmaker.fan.p28
风速无法调节 
调风速变成了Mijia Smart Standing Air Circulation Fan off-delay-time

**Comment by 1105169500** [comment]
另外希望增加 一键回正 back-to-center

**Comment by musk-1024** [comment]
p28的percentage变成了off delay time，目前风速无法调节

**Comment by al-one** [comment]
更新master分支。

**Comment by hgaogao** [comment]
dmaker.fan.p5c也希望可以添加左右摇头控制的按钮

**Comment by wagaman** [comment]
zhimi.fan.za4希望可以添加左右摇头控制的按钮,谢谢🙏
