### ISSUE TITLE
升级0.7.12版本后，空调显示不可用

### ISSUE THREAD

**Issue by jinjinjijiao** [al-one/hass-xiaomi-miot#1282]
### Device model / 设备型号

[xiaomi.aircondition.mc9](https://home.miot-spec.com/s/xiaomi.aircondition.mc9)

### Component version / 插件版本

0.7.12

### HA core version / HA版本

2023.8.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

从0.7.11升级到0.7.12版本后，此空调不可用（原先可用）
并且每隔几十秒，空调会发出“叮铃”声4次，整个屏幕被点亮

### Entity attributes / 实体属性

hvac_modes: cool, heat, dry, fan_only, auto, off
min_temp: 16
max_temp: 31
target_temp_step: 0.5
fan_modes: auto, level1, level2, level3, level4, level5, level6, level7
swing_modes: off, vertical, horizontal, both
friendly_name: Mi Smart Ultra Electricity Saving Vertical Air Conditioner(2HP/Inverter/New China Energy Label Level 3) Air Conditioner
supported_features: 105

### Home Assistant Logs / 系统日志

1. Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}

2. Mi Smart Ultra Electricity Saving Vertical Air Conditioner(2HP/Inverter/New China Energy Label Level 3)(xiaomi.aircondition.mc9): Got MiioException while fetching the state: Unable to recover failed command, mapping: {'air_conditioner.on': {'siid': 2, 'piid': 1}, 'air_conditioner.mode': {'siid': 2, 'piid': 2}, 'target_temperature-2-4': {'siid': 2, 'piid': 4}, 'air_conditioner.eco': {'siid': 2, 'piid': 7}, 'air_conditioner.heater': {'siid': 2, 'piid': 9}, 'air_conditioner.dryer': {'siid': 2, 'piid': 10}, 'air_conditioner.sleep_mode': {'siid': 2, 'piid': 11}, 'flag_bit.frequency_limit': {'siid': 13, 'piid': 1}, 'flag_bit.frequency_under': {'siid': 13, 'piid': 2}, 'flag_bit.rh': {'siid': 13, 'piid': 3}, 'machine_state.indoor_pipe_temp': {'siid': 12, 'piid': 1}, 'machine_state.indoor_fan_speed': {'siid': 12, 'piid': 3}, 'real_heater_switch-12-4': {'siid': 12, 'piid': 4}, 'realindoor_fan_lever-12-5': {'siid': 12, 'piid': 5}, 'machine_state.outdoor_temp': {'siid': 12, 'piid': 7}, 'machine_state.outdoor_pipe_temp': {'siid': 12, 'piid': 8}, 'outdoor_exhaust_temp-12-9': {'siid': 12, 'piid': 9}, 'machine_state.outdoor_fan_lever': {'siid': 12, 'piid': 10}, 'compressor_frequency-12-11': {'siid': 12, 'piid': 11}, 'fourway_valve_switch-12-12': {'siid': 12, 'piid': 12}, 'machine_state.outdoor_current': {'siid': 12, 'piid': 13}, 'machine_state.outdoor_m_voltage': {'siid': 12, 'piid': 14}, 'machine_state.expansion_valve': {'siid': 12, 'piid': 15}, 'longitude_latitude-12-16': {'siid': 12, 'piid': 16}, 'enhance.fan_percent': {'siid': 10, 'piid': 1}, 'enhance.timer': {'siid': 10, 'piid': 3}, 'maintenance.clean': {'siid': 9, 'piid': 1}, 'maintenance.examine': {'siid': 9, 'piid': 2}, 'indicator_light.on': {'siid': 6, 'piid': 1}, 'alarm': {'siid': 5, 'piid': 1}, 'environment.temperature': {'siid': 4, 'piid': 7}, 'fan_control.fan_level': {'siid': 3, 'piid': 2}, 'fan_control.horizontal_swing': {'siid': 3, 'piid': 3}, 'fan_control.vertical_swing': {'siid': 3, 'piid': 4}}, max_properties: 7/34

3. Update of climate.xiaomi_mc9_38a7_air_conditioner is taking over 10 seconds

**Comment by al-one** [comment]
Try master branch.

**Comment by al-one** [comment]
尝试master分支。

**Comment by jinjinjijiao** [comment]
可以正常使用了。
