### ISSUE TITLE
security verification、在本局域网登入官网之后依然无法登入

### ISSUE THREAD

**Issue by zhangseammm** [al-one/hass-xiaomi-miot#1283]
配置小米账户
⚠️ The login of Xiaomi account needs security verification. [Click here](https://account.xiaomi.com/identity/authStart?sid=xiaomiio&context=PHxVUDEgEMzEUpRgFT0Rqq4slkqj4houPatCpffeh0hfp_oh_4roYgkeLYuqwYccmuxjh2sSWbtrzNSQ4jsJ6mAXbpkXm3uqgnTKY8gp1rROQSZ29ye3g4RkQ8_FnbR8BxVr4CE5ZJQuhZPoL63r3Hil8YYA60AHLi9NDcvLG3wBsg-Xv_GB0-xVRoLEWF3sCWulcbCFTEalODN8vOXlBq46YufH5dzGHVGqxbBf9cBwLUJ2NU_4CVAcwgS_X4vqUzNhxBiPhgLz2nJ37E_hQoyusxIqdM7PSRBozrPPgbewWUL14qFt8eUnZLEQ3QUw6y-qmD9zNGZtFgvwzeY-90JRc0PY1fFLfTSIch8zCPXqQv5-f8_XoyPc4YDcaHSzkuL8dRlx_3VeFAjSNI7GIk4Eoi-fMOkvgGk6bBlqUmUioXofoFpaYzvc6i6GczkavG-vc-npLPtepBrVmr3al1hebki8UjM0NzFPn1EJTzw_BD7Gi1gTFl5nVgHcdROGTwEczcLA33SYcLgUXMblSzcwplEfTkP_gqvu6p6d1eF4xlfRwDXsfLny6KrRqW9QXNxYPUpaj9I1ESURL0xhPx1deUq7NCNMeGafRApHIzhQIc_LZUqy3kBDR5F4eytTjPfc5AeZiTrUlFwc9N83Dq3CKDVPHXJonYggTWdQc-_wOQxtsK1yQKKOW5PUtaRe&_locale=en_US) to continue!
本次登录小米账号需要安全验证，[点击这里](https://account.xiaomi.com/identity/authStart?sid=xiaomiio&context=PHxVUDEgEMzEUpRgFT0Rqq4slkqj4houPatCpffeh0hfp_oh_4roYgkeLYuqwYccmuxjh2sSWbtrzNSQ4jsJ6mAXbpkXm3uqgnTKY8gp1rROQSZ29ye3g4RkQ8_FnbR8BxVr4CE5ZJQuhZPoL63r3Hil8YYA60AHLi9NDcvLG3wBsg-Xv_GB0-xVRoLEWF3sCWulcbCFTEalODN8vOXlBq46YufH5dzGHVGqxbBf9cBwLUJ2NU_4CVAcwgS_X4vqUzNhxBiPhgLz2nJ37E_hQoyusxIqdM7PSRBozrPPgbewWUL14qFt8eUnZLEQ3QUw6y-qmD9zNGZtFgvwzeY-90JRc0PY1fFLfTSIch8zCPXqQv5-f8_XoyPc4YDcaHSzkuL8dRlx_3VeFAjSNI7GIk4Eoi-fMOkvgGk6bBlqUmUioXofoFpaYzvc6i6GczkavG-vc-npLPtepBrVmr3al1hebki8UjM0NzFPn1EJTzw_BD7Gi1gTFl5nVgHcdROGTwEczcLA33SYcLgUXMblSzcwplEfTkP_gqvu6p6d1eF4xlfRwDXsfLny6KrRqW9QXNxYPUpaj9I1ESURL0xhPx1deUq7NCNMeGafRApHIzhQIc_LZUqy3kBDR5F4eytTjPfc5AeZiTrUlFwc9N83Dq3CKDVPHXJonYggTWdQc-_wOQxtsK1yQKKOW5PUtaRe&_locale=en_US)继续！你需要在与HA宿主机同局域网的设备下完成安全验证，如果你使用的是云服务器，将无法验证通过。

**Comment by lotherli** [comment]
你的解决了吗？

**Comment by zhulingbiezhi** [comment]
https://www.ququ123.top/2023/09/homeassistant_xiaomi_login  已经解决

**Comment by fckngnthng** [comment]
> https://www.ququ123.top/2023/09/homeassistant_xiaomi_login 已经解决

Url not loading dude

**Comment by zhulingbiezhi** [comment]
> > https://www.ququ123.top/2023/09/homeassistant_xiaomi_login 已经解决
> 
> Url not loading dude

now is ok

**Comment by gzh9619** [comment]
> > > https://www.ququ123.top/2023/09/homeassistant_xiaomi_login 已经解决
> > 
> > 
> > Url not loading dude
> 
> now is ok

still not loading

**Comment by zhulingbiezhi** [comment]
> > > > https://www.ququ123.top/2023/09/homeassistant_xiaomi_login 已经解决
> > > 
> > > 
> > > Url not loading dude
> > 
> > 
> > now is ok
> 
> still not loading

The service has been a bit unstable, but it's working fine now.　Realy

**Comment by maciejpawlak** [comment]
If anyone has similiar problem - I logged in in the same browser to https://account.xiaomi.com/ and it stopped asking for two-factor in hassio :|
