### ISSUE TITLE
Yeelink.light.lamp4 not working 0.7.12

### ISSUE THREAD

**Issue by zzaal** [al-one/hass-xiaomi-miot#1288]
### Device model / 设备型号

yeelink.light.lamp4

### Component version / 插件版本

0.7.12

### HA core version / HA版本

core-2023.8.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Hello!
After upgrading to version 0.7.12, the lamp (yeelink.light.lamp4) is always in inactive mode.
When rolling back to version 0.7.11, the lamp works fine.
Please pay attention to this malfunction and fix it if possible.
Thank you.

### Entity attributes / 实体属性

.

### Home Assistant Logs / 系统日志

.

**Comment by IronButterfly** [comment]
The same story. Reverted back to 0.7.11

**Comment by al-one** [comment]
- #1259

**Comment by zzaal** [comment]
471bd1d
now it works!!!
THX.
