### ISSUE TITLE
Xiaomi Mi Smart Doorbell 2 Support

### ISSUE THREAD

**Issue by rendas** [al-one/hass-xiaomi-miot#129]
Is Xiaomi Mi Smart Doorbell 2 supported?
I checked there is a Doorbell in the supported list, but not sure if this one is supported:
 - https://www.powerplanetonline.com/pt/video-porteiro-xiaomi-mi-smart-doorbell-2
Do you have such information?

Also, which entities are available for the supported Doorbell?
- Is there a sensor for the button and a camera feed as well?
Thanks in advance.

**Comment by al-one** [comment]
At present, most models of video doorbells only support battery sensor, and a small number of them support volume adjustment. Button and video streaming are not supported.
