### ISSUE TITLE
米家窗帘伴侣合体之后不显示实时状态

### ISSUE THREAD

**Issue by MiaoJiawei** [al-one/hass-xiaomi-miot#1293]
两个米家窗帘伴侣，型号为 lumi.curtain.hmcn02，合体后型号为 [lumi.curtain.hmcn04](https://home.miot-spec.com/s/lumi.curtain.hmcn04)，不显示实时状态，只有开关停三个选项

**Comment by al-one** [comment]
没有状态、当前位置等属性。
![lumi.curtain.hmcn04](https://github.com/user-attachments/assets/cc1b9dbb-4124-4c05-bc9b-9760add19a06)
