### ISSUE TITLE
小米电视开机问题

### ISSUE THREAD

**Issue by snadn** [al-one/hass-xiaomi-miot#1294]
### Device model / 设备型号

xiaomi.tv.fsprov1

### Component version / 插件版本

0.7.12

### HA core version / HA版本

2023.6.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

在家庭有网关（多模网关2）接入的情况下，在米家 app 可以操作打开电视，但在 ha 中无法打开电视。
期望能够实现电视的开机功能。

ps：看文档目前似乎只是绑定音箱一种方式能够实现电视开机，不知道是否有通过网关进行开机的方式？

### Entity attributes / 实体属性

source_list:
  - TV
  - DTMB
  - AV
  - HDMI 1
  - HDMI 2
  - HDMI 3
device_class: tv
friendly_name: 主卧的小米电视 Play Control
supported_features: 20365
volume_level: 0.08
is_volume_muted: false
model: xiaomi.tv.fsprov1
lan_ip: 192.168.1.125
mac_address: 'xxx'
entity_class: MitvMediaPlayerEntity
miot_type: urn:miot-spec-v2:device:television:0000A010:xiaomi-fsprov1:1
6095_state: false
speaker.volume: 8
speaker.mute: false
television.input_control.error: '-704042011 Device offline'
state_updater: cloud
miot_action_error: '-704042011 Device offline'
miot_action_result:
  did: mitv.6f7b5c6ff91992db73560aef3fe8ed12:e5d77ddf6f804db78100e08a86070cce
  miid: 0
  siid: 2
  aiid: 1
  code: -704042011
  exe_time: 0
  withLatency: 0
sub_entities:
  - keycodes

**Comment by ABUAIJUTIE** [comment]
目前没有，网关没支持发送这一类蓝牙广播

**Comment by lukedumboy** [comment]
目前可以通过米家App直接开机，并不需要小米网关，因为小米电视是直接通过蓝牙信号开机，和它的蓝牙遥控器一样

**Comment by al-one** [comment]
目前仅能通过小爱音箱开机。
