### ISSUE TITLE
chuangmi.plug.v1 -10000 Method not found

### ISSUE THREAD

**Issue by xuefer** [al-one/hass-xiaomi-miot#13]
```
Device info
chuangmi.plug.v1
by chuangmi
Firmware: 1.2.4_7
```

was good with xiaomi_miio, but error after switching to xiaomi_miot

```
2021-02-02 19:08:16 ERROR (MainThread) [custom_components.xiaomi_miot] Got exception while fetching the state for WorkRoom Desktop Light USB Switch Status: {'code': -10000, 'message': 'Method not found.'}
2021-02-02 19:08:16 ERROR (MainThread) [custom_components.xiaomi_miot] Got exception while fetching the state for WorkRoom Desktop Light Power Switch Status: {'code': -10000, 'message': 'Method not found.'}
```

beside this issue, temperature sensor is missing

**Comment by al-one** [comment]
This device needs enable [miot_cloud](https://github.com/al-one/hass-xiaomi-miot#configuration-xiaomi-cloud).

**Comment by xuefer** [comment]
customize.yaml
···
switch.workroom_desktop_light_power_switch_status:
  miot_cloud: 'true'
sensor.ih_cooker_induction_cooker:
  miot_cloud: 'true'
sensor.ih_cooker_2:
  miot_cloud: 'true'
···
Is there anything wrong with this configuration?

This is generated by "Configuration > Customize > Select Entity > Add Other Attribute"


I wonder why xiaomi_miio don't need micloud username/password

**Comment by al-one** [comment]
> customize.yaml
> ···
> switch.workroom_desktop_light_power_switch_status:
> miot_cloud: 'true'
> sensor.ih_cooker_induction_cooker:
> miot_cloud: 'true'
> sensor.ih_cooker_2:
> miot_cloud: 'true'
> ···
> Is there anything wrong with this configuration?
> 
> This is generated by "Configuration > Customize > Select Entity > Add Other Attribute"
> 
> I wonder why xiaomi_miio don't need micloud username/password

Because this device does not support miot-spec in LAN.

**Comment by xuefer** [comment]
hrm.. so is this devices support old miio spec but not miot spec?

**Comment by al-one** [comment]
Yes. You can try this shell:
```shell
pip3 install python-miio
miiocli -d device --ip 192.168.lan.ip --token xxxxxx raw_command get_properties "[{'did': 'result', 'siid': 2, 'piid': 1}]"
miiocli -d device --ip 192.168.lan.ip --token xxxxxx raw_command get_properties "[{'did': 'result', 'siid': 3, 'piid': 1}]"
```

This device support miot-spec only in cloud.
https://debugger.iot.mi.com/iot/devices

**Comment by xuefer** [comment]
反馈给小米了，等他们升级吧，也可能不升级了
