### ISSUE TITLE
智米全直流变频空调室内温度显示不正确

### ISSUE THREAD

**Issue by joseph2947** [al-one/hass-xiaomi-miot#130]
您好，如题，室内外显示"温度""湿度"都是室外的，以至于LOVELACE卡片，会显示不正确数据，的再麻烦您调整，感谢~~
[debug.txt](https://github.com/al-one/hass-xiaomi-miot/files/6793419/debug.txt)
![擷取](https://user-images.githubusercontent.com/71556774/125124463-b1098800-e12a-11eb-8790-5abeb29ce695.JPG)

**Comment by al-one** [comment]
请下载最新提交：https://github.com/al-one/hass-xiaomi-miot/commit/06eb90243b4321457f39aa2e814d5ac42dadf2d8 后尝试

**Comment by joseph2947** [comment]
刚尝试，目前测试OK~~感谢您!!
