### ISSUE TITLE
TVOC Entity not available for Long-term statistics

### ISSUE THREAD

**Issue by home110120** [al-one/hass-xiaomi-miot#1300]
Device: [cgllc.airmonitor.s1](https://home.miot-spec.com/s/cgllc.airmonitor.s1)
Entity: sensor.cgllc_s1_576d_tvoc_density

The entity is not supported for long-term statistics, it seems there is no 'State_Class' available for this entity. Please help to correct.

青萍空气检测仪，TVOC不支持长期统计数据，根据‘Statistics Graph Card’的官方文档，缺少State_Class的信息，请帮忙修复。谢谢大佬！下面是官方提供的文档链接。

https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics.

**Comment by al-one** [comment]
- #1284
