### ISSUE TITLE
本地模式添加的设备（空调、除湿器）过一段时间后变为不可用了

### ISSUE THREAD

**Issue by XiaTracy** [al-one/hass-xiaomi-miot#1309]
### Device model / 设备型号

xiaomi.aircondition.m9，dmaker.derh.22l，xiaomi.aircondition.c32

### Component version / 插件版本

0.7.12

### HA core version / HA版本

2023.8.4

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

miot auto 使用的是main分支，一共6个小米设备，使用局域网/本地模式（ip+token）添加上了（空调和除湿器），当时测试控制设备都可用，第二天打开ha发现6个设备都变为不可用了，在路由器上给设备绑定了固定ip，所以ip地址没有问题。麻烦请教一下大神，这个问题如何解决啊，多谢！
系统通知如下：
Devices offline
Some devices cannot be connected in the LAN, please check their IP and make sure they are in the same subnet as the HA.

一些设备无法通过局域网连接，请检查它们的IP，并确保它们和HA在同一子网。

实验室2-小米巨省电立式空调(xiaomi.aircondition.c32): 192.168.8.113
实验室1-小米巨省电立式空调(xiaomi.aircondition.c32): 192.168.8.114
实验室2-小米空调巨省电 1.5匹(xiaomi.aircondition.m9): 192.168.8.103
实验室2-米家智能除湿机 22L(dmaker.derh.22l): 192.168.8.105
实验室1-米家智能除湿机 22L 2(dmaker.derh.22l): 192.168.8.108
实验室1-小米空调巨省电(xiaomi.aircondition.m9): 192.168.8.107

### Entity attributes / 实体属性

![image](https://github.com/al-one/hass-xiaomi-miot/assets/13192714/ff47208d-e8a1-4755-8844-3b418db790a7)

### Home Assistant Logs / 系统日志

![image](https://github.com/al-one/hass-xiaomi-miot/assets/13192714/8ed47747-1ac7-4a7d-b828-b8657d1b12a5)
![image](https://github.com/al-one/hass-xiaomi-miot/assets/13192714/5f3caeb5-85f8-4b71-bd24-4f284b6f5477)
![image](https://github.com/al-one/hass-xiaomi-miot/assets/13192714/ba2fe13b-25e3-4be7-80bb-8aedce3aa70d)

**Comment by al-one** [comment]
- 空调可能是因为读取了过多的属性，请更新master分支后再试(减少一些不重要的属性的读取)
- 除湿器尝试添加自定义属性`chunk_properties: 1`，参考: https://github.com/al-one/hass-xiaomi-miot/issues/1257#issuecomment-1685053180

**Comment by XiaTracy** [comment]
多谢大佬，我使用云端模式添加设备了，目前运行稳定，不考虑离线模式了
