### ISSUE TITLE
In Xiaomi Purifier 3C  Entity environment missing

### ISSUE THREAD

**Issue by fudu** [al-one/hass-xiaomi-miot#131]
In Xiaomi Purifier 3C (zhimi.airpurifier.mb4) Entity Environment is missing from some release updates

**Comment by al-one** [comment]
Are there any environmental sensors in the [latest version](https://github.com/al-one/hass-xiaomi-miot/releases/latest) ?

**Comment by fudu** [comment]
No, I wrote just after latest update

**Comment by al-one** [comment]
Please provide entity state attrs:
> [🔨 Developer tools](https://my.home-assistant.io/redirect/developer_states) > [ℹ️ State](https://my.home-assistant.io/redirect/developer_states) > 🔍 Filter Entity

**Comment by fudu** [comment]
Before was
 air_quality.purifier_name_environment
Now
sensor.purifier_name_air_purifier_pm2_5_density

Same value, so it's fine...
Anyway state attrs below
It is recognized as Climate entity

hvac_modes:
  - auto
  - 'off'
min_temp: 16
max_temp: 31
target_temp_step: 1
preset_modes:
  - Sleep
  - Favorite
  - 'off'
current_temperature: null
preset_mode: null
model: zhimi.airpurifier.mb4
lan_ip: 10.200.0.111
mac_address: 54:48:E6:C3:53:F3
firmware_version: 2.0.8
hardware_version: esp32
entity_class: MiotClimateEntity
miot_type: urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-mb4:2
air_purifier.on: true
air_purifier.fault: 'null'
air_purifier.mode: 0
custom_service.moto_speed_rpm: 388
custom_service.miio_lib_version: 'Jerry Yang . Ver: 1.7.0. Date: Jun 18 2020. Time: 20:26:19.'
custom_service.favorite_speed: 2000
custom_service.aqi_updata_heartbeat: 0
physical_controls_locked: false
screen.brightness: 3
alarm: false
filter.filter_life_level: 79
filter.filter_used_time: 731
environment.pm2_5_density: 3
state_updater: lan
sub_entities:
  - environment-3.pm2_5_density-4
  - filter-4.filter_life_level-1
  - filter-4.filter_used_time-3
  - physical_controls_locked-8.physical_controls_locked-1
friendly_name: Purificatore Aria Francy Air Purifier
supported_features: 16

**Comment by al-one** [comment]
The AirQuality platform has been marked as deprecated. The `air_quality` entity is removed and replaced with sensor entities.
