### ISSUE TITLE
dmaker.fan.p28  调节风速无效

### ISSUE THREAD

**Issue by kylinfedora** [al-one/hass-xiaomi-miot#1313]
### Device model / 设备型号

dmaker.fan.p28

### Component version / 插件版本

v0.7.12

### HA core version / HA版本

2023.9.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

dmaker.fan.p28  调节风速无效

### Entity attributes / 实体属性

在HA上调整风速档位时不能生效，米家APP上调整没问题
dm_service.speed_level: 35

**Comment by al-one** [comment]
v0.7.13 已修复
