### ISSUE TITLE
米家智能直流变频循环扇 落地式 无法调节风速

### ISSUE THREAD

**Issue by Wanguy** [al-one/hass-xiaomi-miot#1319]
### Device model / 设备型号

dmaker.fan.p28

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

米家智能直流变频循环扇 dmaker.fan.p28 无法调节风速，在HomeKit中也没法调节，请问是否需要绑定什么实体

<img width="500" alt="image" src="https://github.com/al-one/hass-xiaomi-miot/assets/21999088/53fcded8-eabf-4f7c-b7d9-1d9215900d18">
<img width="500" alt="image" src="https://github.com/al-one/hass-xiaomi-miot/assets/21999088/9d8af3e3-1729-4477-bbb5-496a855770c9">

### Entity attributes / 实体属性

dmaker.fan.p28

**Comment by SodaWithoutSparkles** [comment]
试试在ha里面点击fan实体

**Comment by Wanguy** [comment]
经过测试发现，在ha里直接调整风量大小，在米家app中显示实际调整的是delay off的时间，猜想是不是实体绑定错误了？

<img width="223" alt="SCR-20230914-tzwe" src="https://github.com/al-one/hass-xiaomi-miot/assets/21999088/e26cfd96-0ccc-40ec-973f-845a02feaefb">
<img width="233" alt="image" src="https://github.com/al-one/hass-xiaomi-miot/assets/21999088/8b87eb69-63a1-40c6-9a62-156290b213c4">

**Comment by al-one** [comment]
v0.7.13 已修复
