### ISSUE TITLE
灯光色温问题

### ISSUE THREAD

**Issue by Wang1998** [al-one/hass-xiaomi-miot#1324]
homeassistant 显示色温调节有问题 具体如下  
<img width="613" alt="image" src="https://github.com/al-one/hass-xiaomi-miot/assets/23552159/ed65a1f6-5ee9-4f9f-8565-386e7667d262">
<img width="719" alt="image" src="https://github.com/al-one/hass-xiaomi-miot/assets/23552159/1f0649a0-6fba-4612-b31b-61b0deb5c37f">
![IMG_4008](https://github.com/al-one/hass-xiaomi-miot/assets/23552159/97e17714-621d-4d72-a290-413f3ceb2bab)

**Comment by al-one** [comment]
![aimore.light.cw3201 color temp](https://github.com/al-one/hass-xiaomi-miot/assets/4549099/aecbf08d-58aa-42f4-9671-520e24b58478)

该设备被定义了错误的色温单位，已在插件中纠正，更新master尝试。

**Comment by redhatme** [comment]
这个灯，我用了最新的插件，还是色温有问题， 全都是红色的
