### ISSUE TITLE
Xiaomi Air Purifier Pro

### ISSUE THREAD

**Issue by nikomaxos** [al-one/hass-xiaomi-miot#133]
Hello,

While having the latest version installed  - v0.3.8 - 2021-07-12, my purifier appears as unavailable. After enabling the debug logging i receive the following error: 

This error originated from a custom integration.

Logger: custom_components.xiaomi_miot
Source: custom_components/xiaomi_miot/__init__.py:843
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 7:07:33 PM (2 occurrences)
Last logged: 7:08:03 PM

Got MiioException while fetching the state for Xiaomi Air Purifier Air Purifier: {'code': -32601, 'message': 'Method not found.'}, mapping: {'air_purifier.on': {'siid': 2, 'piid': 1}, 'air_purifier.mode': {'siid': 2, 'piid': 2}, 'indicator_light.on': {'siid': 7, 'piid': 1}, 'alarm': {'siid': 6, 'piid': 1}, 'physical_controls_locked': {'siid': 5, 'piid': 1}, 'filter.filter_life_level': {'siid': 4, 'piid': 1}, 'filter.filter_used_time': {'siid': 4, 'piid': 2}, 'environment.relative_humidity': {'siid': 3, 'piid': 1}, 'environment.pm2_5_density': {'siid': 3, 'piid': 2}, 'environment.temperature': {'siid': 3, 'piid': 3}}

Core
Version
core-2021.7.2
-------------
Supervisor
Version
supervisor-2021.06.8

Any ideas on how to resolve?

**Comment by al-one** [comment]
The device may not support miot-spec in  LAN, you can integrate the device through Xiaomi account, or enable cloud mode.
