### ISSUE TITLE
 chuangmi.camera.ipc019e support camera?

### ISSUE THREAD

**Issue by saramlove** [al-one/hass-xiaomi-miot#134]
hello,
 chuangmi.camera.ipc019e support camera?
Thank you.

brand: chuangmi
model: chuangmi.camera.ipc019e

firmware_version: 3.5.8_0166
hardware_version: ''
entity_class: MiotCameraEntity
miot_type: urn:miot-spec-v2:device:camera:0000A01C:chuangmi-ipc019e:1
camera_control.on: true
camera_control.image_rollover: 0
camera_control.night_shot: 0
camera_control.time_watermark: true
camera_control.wdr_mode: false
camera_control.glimmer_full_color: true
camera_control.recording_mode: 2
camera_control.motion_tracking: false
state_updater: cloud
miot_error: Nonsupport start hls/rstp stream
sub_entities:
   - camera_control.on
friendly_name: ab Camera Control
entity_picture: >-
   /api/camera_proxy/camera.ab_camera_control?token=
supported_features: 1
miot_cloud: true

**Comment by al-one** [comment]
This model of camera is not supported.

**Comment by saramlove** [comment]
Thank you for quick response.
I wish it was supported.
