### ISSUE TITLE
米家智能插座2 蓝牙网关版 功率显示不正确

### ISSUE THREAD

**Issue by catchfishday** [al-one/hass-xiaomi-miot#1342]
### Device model / 设备型号

chuangmi.plug.212a01 制造商：chuangmi 固件：2.1.8_0044

### Component version / 插件版本

Xiaomi Miot Auto 自定义组件版本	0.7.13 可访问米家服务器	ok 可获取MIoT规格	ok 已登录的账户数量	1 米家设备总数量	13

### HA core version / HA版本

Home Assistant 2023.10.1 Supervisor 2023.10.0 前端版本： 20231005.0 - latest

### Integrated mode / 集成方式

Automatic (自动模式)

### Entity attributes / 实体属性

实际功率494，ha上面显示4.94 ，正确值应该X100

**Comment by zhaqianyuan** [comment]
云端模式也是这样

**Comment by Latezly** [comment]
![image](https://github.com/al-one/hass-xiaomi-miot/assets/17759624/fcb77932-5f4a-4d93-905e-5dcb9303e871)

**Comment by sleepinging** [comment]
解决方法
https://github.com/al-one/hass-xiaomi-miot/issues/534
