### ISSUE TITLE
多种设备不可用

### ISSUE THREAD

**Issue by MrSleeplessC** [al-one/hass-xiaomi-miot#1346]
### Device model / 设备型号

chuangmi.plug.m3 / cuco.plug.v3 / cuco.plug.sp5 / cuco.plug.cp5d / yeelink.light.ceiling1 /  

### Component version / 插件版本

0.7.13

### HA core version / HA版本

Supervisor 2023.10.0   Operating System 10.5   前端版本： 20231005.0 - latest

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

通过账号集成-自动 添加设备后，排插、智能开关 均显示不可用。 风扇、杜亚窗帘 这两种设备认不到区域且提示“未找到设备或服务”。

### Entity attributes / 实体属性

device_class: outlet
friendly_name: 智能排插-右 Switch
supported_features: 0

### Home Assistant Logs / 系统日志

[home-assistant_2023-10-09T16-58-05.350Z.log](https://github.com/al-one/hass-xiaomi-miot/files/12848598/home-assistant_2023-10-09T16-58-05.350Z.log)

**Comment by MrSleeplessC** [comment]
系统日志提示超出字符数，所以上传了log文档

**Comment by f0re1gnKey** [comment]
同样遇到这种问题，排查网络排查了很久，最终发现是插件自己的问题，米家连接完全正常

**Comment by tianzehao** [comment]
是否在添加miot插件时勾选了按照家庭添加的选项？取消勾选试试

**Comment by al-one** [comment]
检查设备IP。
```
插座(chuangmi.plug.m3): Got MiioException while fetching the state: Unable to discover the device 10.0.30.29
打印机(cuco.plug.v3): Got MiioException while fetching the state: Unable to discover the device 10.0.30.25
智能排插-右(cuco.plug.sp5): Got MiioException while fetching the state: Unable to discover the device 10.0.30.17
洞洞板排插(cuco.plug.cp5d): Got MiioException while fetching the state: Unable to discover the device 10.0.30.32
Yeelight Ceiling Light(yeelink.light.ceiling1): Got MiioException while fetching the state: Unable to discover the device 10.0.30.34
```
