### ISSUE TITLE
No percentage value - water level

### ISSUE THREAD

**Issue by home409ca** [al-one/hass-xiaomi-miot#1348]
The water level entity is not numeric (percentage), but varchar.

I can't create a chart with this data....

![image](https://github.com/al-one/hass-xiaomi-miot/assets/114701129/649b99bc-afdd-4d73-9b6c-54c38857e18c)

[zhimi.humidifier.cb1](https://home.miot-spec.com/s/zhimi.humidifier.cb1)
producent: zhimi
oprogramowanie: 2.0.2@MTK7697

**Comment by al-one** [comment]
Try master.

**Comment by home409ca** [comment]
thanks!
