### ISSUE TITLE
add support for Mi IH Pressure Rice Cooker

### ISSUE THREAD

**Issue by Comee** [al-one/hass-xiaomi-miot#135]
Mode ：chunmi.cooker.press1

**Comment by Golab** [comment]
Yes please add support for chunmi.cooker.press1

**Comment by al-one** [comment]
`cooker` is a supported device type. If the device is not available after being integrated, please check the error [logs](https://my.home-assistant.io/redirect/logs).

**Comment by Comee** [comment]
How to config the following cook modes，I can't see these after add `Mi IH Pressure Rice Cooker` by cloud mode

![微信图片_20210720093245](https://user-images.githubusercontent.com/5416227/126248766-513ef036-2c7e-47b0-b826-f2589eb38276.jpg)

**Comment by al-one** [comment]
```json
{
    "property":"cook-mode",
    "desc":"Cook Mode",
    "access":"",
    "format":"uint8",
    "value-list":[
        {
            "value":1,
            "description":"Fine Cook"
        },
        {
            "value":2,
            "description":"Quick Cook"
        },
        {
            "value":3,
            "description":"Cook Congee"
        },
        {
            "value":4,
            "description":"Keep Warm"
        }
    ]
}
```
This is the `cook-mode` property defined in the miot-spec of this model [`chunmi.cooker.press1`](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:cooker:0000A00B:chunmi-press1:1), so only these cook-modes can be selected through miot.
In the previous version, there should be a fan entity to integrate the device, and cook-mode can be selected through the preset mode of the fan entity.
After the commit: https://github.com/al-one/hass-xiaomi-miot/commit/fe049e2c94ce3507fb6fc4cd21fe1df205abb3b9, if your HA version is higher than v2021.7, the fan entity is deprecated and changed to the select entity.

**Comment by Comee** [comment]
According to [xiaomi_miio_cooker/services.yaml](https://github.com/syssi/xiaomi_cooker/blob/develop/custom_components/xiaomi_miio_cooker/services.yaml), maybe we can add `custom`  `cook-mode` feature

**Comment by Comee** [comment]
可以提供支持增加更多的食谱吗？

**Comment by al-one** [comment]
> 可以提供支持增加更多的食谱吗？

可以通过服务[`xiaomi_miot.send_command`](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.send_command)开始烹饪并指定食谱profile：
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: sensor.dian_fan_bao_cooker
  method: set_start
  params:
    - abcdef0123456789 # 食谱profile
```

**Comment by Comee** [comment]
thanks
