### ISSUE TITLE
请问hasscc / tianqi的服务器域要填什么

### ISSUE THREAD

**Issue by lipwah** [al-one/hass-xiaomi-miot#1352]
请问天气预告那里配置服务器域要怎么填，谢谢

**Comment by al-one** [comment]
- https://mp.weixin.qq.com/s/_4aFbsb40qPgII-kYB3phA

这篇文章里有。

**Comment by lipwah** [comment]
> * https://mp.weixin.qq.com/s/_4aFbsb40qPgII-kYB3phA
> 
> 这篇文章里有。

 感谢

**Comment by elainec728** [comment]
感谢！
