### ISSUE TITLE
领普人体存在传感器无法获取到光照

### ISSUE THREAD

**Issue by kinglonh** [al-one/hass-xiaomi-miot#1356]
<img width="520" alt="image" src="https://github.com/al-one/hass-xiaomi-miot/assets/39109449/1f71ffa1-f388-44b1-b46f-1c16d131dde5">

如图，领普人体存在传感器只能获取到是否有人存在，无法获取到光照值
<img width="395" alt="image" src="https://github.com/al-one/hass-xiaomi-miot/assets/39109449/6be27eec-0aec-4b19-8f68-98fe4722300c">

实际上应该是可以读到的，但插件不能自动获取到，插件版本v7.0.13，Home Assistant 2023.10.1 docker

**Comment by ABUAIJUTIE** [comment]
<img width="393" alt="截屏2023-10-18 12 11 37" src="https://github.com/al-one/hass-xiaomi-miot/assets/29325925/176f2ba0-84e1-4e5b-9544-d52070b36bdf">
是这个地方的读数不准确吗？

**Comment by kinglonh** [comment]
> <img alt="截屏2023-10-18 12 11 37" width="393" src="https://user-images.githubusercontent.com/29325925/276082193-176f2ba0-84e1-4e5b-9544-d52070b36bdf.png">
> 是这个地方的读数不准确吗？

读数准确，但不能加入到面板

**Comment by ABUAIJUTIE** [comment]
试了下确实是没有单独的一个实体，如果可以通过 xiaomi gatway 3 插件接入的话就用那个，如果不行就新建一个模板实体吧～
[![Open your Home Assistant instance and show your helper entities.](https://my.home-assistant.io/badges/helpers.svg)](https://my.home-assistant.io/redirect/helpers/)
添加一个模板辅助元素
`{{ state_attr('sensor.linp_occupancy_sensor', 'occupancy_sensor.illumination') }}`
大概长这样
<img width="601" alt="模板辅助元素" src="https://github.com/al-one/hass-xiaomi-miot/assets/29325925/10ade43c-655c-48da-89d5-c35251f8f9c3">

**Comment by SodaWithoutSparkles** [comment]
@ABUAIJUTIE 你写code的时候用引用格式好像有点怪，建议用回code block格式。

````
```
code
```
````



@kinglonh 解决了吗？解决的就可以关掉issue了
