### ISSUE TITLE
Xiaomi Gateway Alarm always triggered

### ISSUE THREAD

**Issue by xzebra** [al-one/hass-xiaomi-miot#1362]
### Device model / 设备型号

lumi.gateway.mgl03

### Component version / 插件版本

0.7.13

### HA core version / HA版本

2023.10.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

I've the lumi.gateway.mgl03 added to Homeassistant through Miot Auto integration. An arming entity (alarm_control_panel.lumi_mgl03_ad8f_arming) is created with it.

The arming appears always as triggered. If I try to reset the state to "disarmed" via Developer Tools, it instantly comes up again as triggered:

![image](https://github.com/al-one/hass-xiaomi-miot/assets/20362769/841ba572-111e-4e74-87c5-f85b2841cb5f)

### Entity attributes / 实体属性

Alarm arming entity:

```
friendly_name: Centralita arming
supported_features: 15
code_arm_required: false
model: lumi.gateway.mgl03
lan_ip: 192.168.18.9
mac_address: 54:EF:44:23:AD:8F
entity_class: MiotAlarmEntity
home_room: **REDACTED**
miot_type: urn:miot-spec-v2:device:gateway:0000A019:lumi-mgl03:2
arming.arming_mode: 0
arming.customize_mode_1.error: -704083036 Device operation timeout
arming.customize_mode_2.error: -704083036 Device operation timeout
arming.customize_mode_3.error: -704083036 Device operation timeout
arming.customize_mode_4.error: -704083036 Device operation timeout
arming.customize_mode_5.error: -704083036 Device operation timeout
arming.customize_mode_6.error: -704083036 Device operation timeout
arming.delay_time_basic.error: -704083036 Device operation timeout
arming.alarm_duration_basic.error: -704083036 Device operation timeout
arming.alarm_volume_basic.error: -704083036 Device operation timeout
arming.delay_time_home: 5
arming.alarm_duration_home.error: -704083036 Device operation timeout
arming.alarm_volume_home.error: -704083036 Device operation timeout
arming.delay_time_away: 15
arming.alarm_duration_away.error: -704083036 Device operation timeout
arming.alarm_volume_away.error: -704083036 Device operation timeout
arming.delay_time_sleep: 5
arming.alarm_duration_sleep.error: -704083036 Device operation timeout
arming.alarm_volume_sleep.error: -704083036 Device operation timeout
arming.target_arming_mode: 0
arming.alarm: 1
accidental_deletion.on_off: 1
indicator_light.on.error: -704083036 Device operation timeout
state_updater: cloud
```

### Home Assistant Logs / 系统日志

Alarm arming logs:

```
2023-10-19 20:44:41.657 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.lumi_mgl03_ad8f_arming is taking over 10 seconds
```

No relevant miot logs to this entity or device.

**Comment by SodaWithoutSparkles** [comment]
changing the state in devtools does not change the state of the actual device. 

go to the services tab in devtools, type in "alarm" in the dropdown, then you can see the actions to interact w/ the alarm.

to un-trigger it, try to disarm the the alarm

if that doesnt work, arm it to whatever state then disarm again.
