### ISSUE TITLE
Support for Mi Smart Standing Fan 2 dmaker.fan.p42

### ISSUE THREAD

**Issue by lukyjay** [al-one/hass-xiaomi-miot#1368]
### Device model / 设备型号

Xiaomi Smart Standing Fan 2

### Component version / 插件版本

0.7.13

### HA core version / HA版本

core-2023.10.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

The Smart Fan 2 does not appear: https://www.mi.com/global/product/mi-smart-standing-fan-2/

I think the device is: https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:fan:0000A005:dmaker-p42:1

In Xiaomi Home app I must set server to Singapore to use this fan. I have set the Miot Auto configuration to Singapore but it still does not appear.

### Entity attributes / 实体属性

Not listed

### Home Assistant Logs / 系统日志

Two logs appear but I think they are relevant to my other devices....

Request xiaomi api: v2/message/v2/typelist {} failed, response: None
7:36:35 PM – (WARNING) Xiaomi Miot Auto (custom integration) - message first occurred at 7:30:38 PM and shows up 3 times
Get xiaomi message for 36808571 failed: {'code': 0, 'message': 'ok', 'result': {'messages': None}}
7:30:38 PM – (WARNING) Xiaomi Miot Auto (custom integration) - message first occurred at 7:27:47 PM and shows up 2 times

**Comment by SodaWithoutSparkles** [comment]
does the official integration in home assistant support it?

**Comment by SodaWithoutSparkles** [comment]
https://www.home-assistant.io/integrations/xiaomi_miio/#tower-fanstanding-fan-2standing-fan-pro-dmakerfanp9dmakerfanp10dmakerfanp11

Try using the official integration (xiaomi_miio) in home assistant, just enter the account ID/email & pw, select server to be singapore.

Then select the device. It would warn you about not being able to find config flow or sth, just manually select the entry for `dmaker.fan.p10`

**Comment by lukyjay** [comment]
> https://www.home-assistant.io/integrations/xiaomi_miio/#tower-fanstanding-fan-2standing-fan-pro-dmakerfanp9dmakerfanp10dmakerfanp11
> 
> Try using the official integration (xiaomi_miio) in home assistant, just enter the account ID/email & pw, select server to be singapore.
> 
> Then select the device. It would warn you about not being able to find config flow or sth, just manually select the entry for `dmaker.fan.p10`

Thanks so much for reminding me! I love this add-on so much that I forgot to try that one. Yes it works, says it's unrecognised but using the device you mentioned fixes it. 

Should it still be added to this add-on or is there no appetite to add devices that work via the official add-on?

**Comment by SodaWithoutSparkles** [comment]
it is generally not recommended to duplicate the device. just wasting resources. unless there's a function missing.

**Comment by lukyjay** [comment]
> it is generally not recommended to duplicate the device. just wasting resources. unless there's a function missing.

Ok no worries. Thanks again, have a good weekend 🙂
