### ISSUE TITLE
你的摄像机不支持流服务

### ISSUE THREAD

**Issue by JachinY** [al-one/hass-xiaomi-miot#137]
Your camera mxiang.camera.mwc11 doesn't support streaming services.
你的摄像机不支持流服务。
https://github.com/al-one/hass-xiaomi-miot/issues/60#issuecomment-819435571

**Comment by JachinY** [comment]
@al-one 大佬 室外摄像头有可能接入miot_cloud吗

**Comment by al-one** [comment]
出现该提示表示该设备目前无法通过本插件集成camera实体，且暂时没有解决方案。

**Comment by JachinY** [comment]
@al-one 大佬，有什么推荐的摄像头吗 完美接入的

**Comment by al-one** [comment]
很抱歉，目前没有完美接入的摄像头。
本插件的接入摄像头所用的服务[`camera-stream-for-google-home`](https://miot-spec.org/miot-spec-v2/spec/service?type=urn:miot-spec-v2:service:camera-stream-for-google-home:00007831)仅在部分型号上有，且不能稳定使用(#56)，具体原因未知。

**Comment by JachinY** [comment]
![image](https://user-images.githubusercontent.com/42339509/126363592-963170d2-7f3d-4468-96c2-22f594d84237.png)

camera.xiao_mi_zhi_neng_she_xiang_ji

**Comment by JachinY** [comment]
好像也没啥反应

**Comment by al-one** [comment]
See https://github.com/al-one/hass-xiaomi-miot/issues/166
