### ISSUE TITLE
support 米家智能晾衣架 hyd.airer.znlyj2

### ISSUE THREAD

**Issue by Comee** [al-one/hass-xiaomi-miot#138]
Current problems
<img width="1439" alt="截屏2021-07-21 下午10 43 39" src="https://user-images.githubusercontent.com/5416227/126522456-ce5829cc-4373-4949-af38-42a830f4667a.png">
<img width="727" alt="截屏2021-07-22 上午12 14 41" src="https://user-images.githubusercontent.com/5416227/126523100-29545599-1d76-4ec3-aee4-4b971e6d8932.png">

**此外，添加到Homekit后，升降控制均无效**

other maybe useful information
<img width="384" alt="截屏2021-07-22 上午12 08 35" src="https://user-images.githubusercontent.com/5416227/126522365-f7347baa-850f-4b14-849e-85a806d0cc6b.png">

**Comment by al-one** [comment]
该型号的[miot协议](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:airer:0000A00D:hyd-znlyj2:2)定义有点乱，有两个`airer`服务，且其中一个有两个`target-position`属性，另一个下面所有属性错误码`-704040002`表示**服务不存在**，因此siid为4的服务应该是无效的，可以将其关联的cover实体和fan实体禁用。

另外，请提供下面不同状态下的实体状态以及`airer.status`、`airer.current_position`：
- 最顶部
- 30%左右非暂停
- 65%左右暂停
- 最低部

**Comment by Comee** [comment]
```
升到最顶端：airer.current_position = 1  airer.status = 0
上升过程中：airer.current_position = 0  airer.status = 1
降到最低端：airer.current_position = 2  airer.status = 0
下降过程中：airer.current_position = 0  airer.status = 2
中途暂停（不管上升还是下降代码一样）airer.current_position = 0  airer.status = 3
```

原来的图标含义也有问题，上升图标表示下降，下降图标表示上升

**Comment by al-one** [comment]
请更新master后再试下。

**Comment by Comee** [comment]
error log
.homeassistant/custom_components/xiaomi_miot/cover.py", line 181, in is_closed
if pos < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'

**Comment by al-one** [comment]
再试下

**Comment by Comee** [comment]
home assistant 上测试已经没问题，但是集成到homekit上后，苹果手机家庭里面无法控制升降（可以控制照明），看日志是调用了`HomeKit send command set_cover_position for 晾衣架 Airer`

**Comment by al-one** [comment]
在HA上点开实体弹出框通过滑竿控制升降试试。并且观察下HomeKit操作后有无相关[日志](https://my.home-assistant.io/redirect/logs)，如没有请开启debug日志后再试：
```yaml
service: logger.set_level
data:
  custom_components.xiaomi_miot: debug
```
日志以`Set miot property to 晾衣架 Airer ...`开头。

**Comment by Comee** [comment]
HA上通过滑竿控制也不可以，debug日志如下：
```
2021-07-22 19:37:42 DEBUG (SyncWorker_8) [custom_components.xiaomi_miot] Set miot property to 晾衣架 Airer ({'did': '358897291', 'siid': 2, 'piid': 5, 'value': 45}), result: {'did': '358897291', 'siid': 2, 'piid': 5, 'code': -704002000}
```

**Comment by al-one** [comment]
当cover实体支持设置行程时，HomeKit会通过设置行程控制实体。请再次更新，已将该型号的`target-position`默认禁用。

**Comment by Comee** [comment]
可以控制了，homekit里面显示有问题，显示反了：
实际晾衣架已升到最上面（关上状态），HomeKit里显示已打开
实际晾衣架降到最下面（打开状态），HomeKit里显示已关闭

**Comment by al-one** [comment]
状态没有问题，晾衣架类是没有打开关闭的说法的，请把晾衣架想象成卷帘。

**Comment by Comee** [comment]
这个能改吗，语音控制起来，有点反常识，别扭😂

**Comment by al-one** [comment]
```yaml
# customize.yaml
cover.your_entity_id:
  motor_reverse: true
```
你可以添加此自定义属性尝试，但是可能会导致操作也是反的

**Comment by Comee** [comment]
HomeKit 测试没问题了，要是能把暂停功能也加入HomeKit 那就更完美了，现在在HomeKit里面只能升到最顶端，或降到最低端。HA里则可以让其停在任意位置😊。

**Comment by al-one** [comment]
可以添加一个[脚本](https://my.home-assistant.io/redirect/scripts)调用`cover.stop_cover`服务并同步script实体到HomeKit。

**Comment by Comee** [comment]
非常感谢🙏

**Comment by Comee** [comment]
homekit 语音 关闭全屋窗帘，会导致关闭 该晾衣架，有什么办法可以不让其受影响吗

**Comment by Comee** [comment]
homekit 语音 关闭全屋窗帘，会导致关闭 该晾衣架，有什么办法可以不让其受影响吗

**Comment by al-one** [comment]
只能晾衣机不接入HomeKit，用[template switch](https://www.home-assistant.io/integrations/switch.template)或者[script](https://my.home-assistant.io/redirect/scripts)调用服务控制衣机。

**Comment by Comee** [comment]
👌谢谢
