### ISSUE TITLE
小米空调伴侣2接入

### ISSUE THREAD

**Issue by Peterzhangnoise** [al-one/hass-xiaomi-miot#1391]
小米空调伴侣2接入后，在HK上显示两个，一个风扇，一个空调，有没有什么办法可以两个合并到一起

**Comment by al-one** [comment]
已经是合在一起的。
> 空调实体接入到HomeKit是HA的实现的，插件无法控制。

![xiaomi miot climate homekit](https://github.com/al-one/hass-xiaomi-miot/assets/4549099/236c28eb-c83e-43b0-9baf-13ca26d2d090)

**Comment by eunrui** [comment]
> 已经是合在一起的。
> 
> > 空调实体接入到HomeKit是HA的实现的，插件无法控制。
> 
> ![xiaomi miot climate homekit](https://private-user-images.githubusercontent.com/4549099/283082269-236c28eb-c83e-43b0-9baf-13ca26d2d090.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTE1MTEsIm5iZiI6MTcwMjI5MTIxMSwicGF0aCI6Ii80NTQ5MDk5LzI4MzA4MjI2OS0yMzZjMjhlYi1jODNlLTQzYjAtOWJhZi0xM2NhMjZkMmQwOTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTFUMTA0MDExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGI1YjRkYTEzNzgxYTMzZDA0NzNjNDVjMTUxOTUzOTUzNDg2YjlhYzlkMDhlZmE1M2FlNTMyYmNkZTkzZjQwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1U79y2-ArIfN5qtrX92RUqP5cpphERdgwFlmjKHEqbs)

原来大家都一样，我说怎么升级ios17之后，就没有控制风向的选项了
