### ISSUE TITLE
Control over notification

### ISSUE THREAD

**Issue by linceaerian** [al-one/hass-xiaomi-miot#1392]
Hello Maintainer(s),

Thanks a lot for the integration.

Do you have an ignore option for the "devices offline" notification ?  (I saw some that's call "throw" in the translation but I cannot find it in the current HAss UI, I only find options for "Delete", "Disable", "Deactivate").

![image](https://github.com/al-one/hass-xiaomi-miot/assets/1318470/f375e3ea-3cb2-4f34-a44c-6ccfe0f0ae36)

I got some device "offline" which is "normal" (due to moving or them having some trouble, like the fan of purifier being noisy at random interval) and is the correct behavior. I want to be able to "keep" them inside HAss configuration without getting a reminder everyday they are offline :)

If you do not have one, can you add either a "ignore" offline status option by device or just a global option "do not notify for offline devices" at the service level like the renew option... https://github.com/al-one/hass-xiaomi-miot/blob/3e77571b4038d51df336326d40db49e4d1a69713/custom_components/xiaomi_miot/services.yaml#L276 (or even just a configuration about "how often the notification should be issue") ?

The code that seems to manage this part is the "tip" here:
https://github.com/al-one/hass-xiaomi-miot/blob/3e77571b4038d51df336326d40db49e4d1a69713/custom_components/xiaomi_miot/__init__.py#L1463

Thanks in advance,
Have a good day

Mathieu

**Comment by al-one** [comment]
- #705 
- #606
- #574 

![image](https://github.com/al-one/hass-xiaomi-miot/assets/4549099/729d409f-f8d8-460b-ba6c-047ad5707597)

**Comment by linceaerian** [comment]
Thanks for the help @al-one ,
It helped me figure out the process.

Let me add more details for non-Chinese speaker, cause I had to get help from my wife :)

As specified in this doc:
https://github.com/al-one/hass-xiaomi-miot/issues/600

1. Click on the link [https://my.home-assistant.io/redirect/config_flow_start/?domain=xiaomi_miot]
2. Click on "Are you sure", it will open a popup menu with "Customizing Entities/devices" option choice,
3. Click on the customizing options
4. Specify your target device (wildcard or not) ex:
![image](https://github.com/al-one/hass-xiaomi-miot/assets/1318470/809f6905-9fd7-45a1-833e-f30bc8270324)
5. Add the custom option to "ignore_offline"
![image](https://github.com/al-one/hass-xiaomi-miot/assets/1318470/55cf0d67-b9fe-4be9-be98-c13637f50fec)
6. Should show a summary in "Xiaomi: Customizes", ex:
![image](https://github.com/al-one/hass-xiaomi-miot/assets/1318470/b0dd0e8f-52ce-4b3f-b4d3-ba5eba868274)
7. Reload the configuration of integration (Dev -> Yaml -> Xiaomi)


And that should do it, I'll check the detail tmr and close if functional.
A bit strange to have a custom config separated but, hey, as long as it works :D

PS: Sorry for the duplicated issue >.< Should have search before... bad brain.

**Comment by linceaerian** [comment]
I confirm it fixed the problem for me, closing this.
