### ISSUE TITLE
Xiaomi Whale Spout (xjx.toilet.pro)

### ISSUE THREAD

**Issue by karolzamosc** [al-one/hass-xiaomi-miot#14]
@al-one Can you add the Xiaomi Whale Spout (xjx.toilet.pro) integration?

**Comment by karolzamosc** [comment]
@al-one thanks, can you help me to add this sensor to the HA? I have added the whale spout in configuration/integrations but I don't know what next...

**Comment by al-one** [comment]
Please upgrade to [v0.2.5](https://github.com/al-one/hass-xiaomi-miot/releases/latest).
There will be a binary sensor after integration.
