### ISSUE TITLE
小米空气净化器4 无法加入 / 不停重启

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [al-one/hass-xiaomi-miot#1405]
### Device model / 设备型号

[xiaomi.airp.mp4](https://home.miot-spec.com/s/xiaomi.airp.mp4)

### Component version / 插件版本

0.7.13

### HA core version / HA版本

2023.11.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

无法新增小米空气净化器4。设备新增之后，点进去没有任何控制项，点开hidden的项目有一个灰色的风扇类。
同时小米空气净化器4在新增之后不停重启，大约2-3分钟一次。
上述情况在使用官方的xiaomi_miio也一样

### Entity attributes / 实体属性

N/A

### Home Assistant Logs / 系统日志

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:927
First occurred: 6:32:52 AM (2 occurrences)
Last logged: 6:33:04 AM

Update of fan.xiaomi_mp4_ea38_air_purifier is taking over 10 seconds
```

```
This error originated from a custom integration.

Logger: custom_components.xiaomi_miot.fan
Source: custom_components/xiaomi_miot/__init__.py:1897
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 6:32:54 AM (1 occurrences)
Last logged: 6:32:54 AM

Xiaomi Smart Air Purifier 4(xiaomi.airp.mp4): Set miot property {'did': '694985133', 'siid': 2, 'piid': 5, 'value': 2} failed, result: {'did': '694985133', 'iid': '0.2.5', 'siid': 2, 'piid': 5, 'code': -704083036, 'exe_time': 0}
```

**Comment by SodaWithoutSparkles** [comment]
日志我一会再填，现在没空
可能和 #1401 有关

**Comment by SodaWithoutSparkles** [comment]
@al-one 已更新日志记录

现在好像能够在HA看到实体记录了，不过仍然是在不停重启。

**Comment by chazikai24** [comment]
Xiaomi Smart Air Purifier 4 PRO(xiaomi.airp.va2b) 也有同样的问题，一直在不停的重启

**Comment by SodaWithoutSparkles** [comment]
估计是升级净化器固件之后有部分的api不一样了？

**Comment by SodaWithoutSparkles** [comment]
找到了关于4 pro的另外一个issue，估计也有关联： #1334

**Comment by al-one** [comment]
通过自定义属性`exclude_miot_services`和`exclude_miot_properties`排除一些不重要的属性和服务试试。

```yaml
exclude_miot_services: custom_service,rfid
```

**Comment by chazikai24** [comment]
> ```yaml
> custom_service
> ```

经过测试，排除custom_service即可

**Comment by chazikai24** [comment]
> 确认已解决，要不把上述修正变为预设？

我的一台旧款4pro，型号zhimi.airp.va2就没问题，可能还是固件的问题

**Comment by SodaWithoutSparkles** [comment]
会不会只是 `xiaomi.airp` class 才有问题？

**Comment by LiuxingLX** [comment]
新人请教一下，如何设置自定义属性呀？

> 确认已解决，要不把上述修正变为预设？

**Comment by SodaWithoutSparkles** [comment]
> 新人请教一下，如何设置自定义属性呀？

1. @LiuxingLX 这个修正已经变为预设设定了，应该不需要手动调节
2. 你看看安装了最新更新没有
3. 通常用评论挖起旧issue是不太礼貌的事情，尤其是完全和核心问题无关的时候。在这个情况下，如果你更新之后还有同一个问题，才会值得挖起一个旧issue。而且最好是提供背景资料，例如你也有一个XX设备有同一个问题，但是找不到YY设置在哪之类的。
4. 你去miot auto 下方新增一个integration就可以自定义了
