### ISSUE TITLE
zhimi.heater.nb1

### ISSUE THREAD

**Issue by reesion** [al-one/hass-xiaomi-miot#141]
Hi, I have a zhimi.heater.nb1 and I have successfully added the device via Integration.

All the components/functions are showing up correctly.

However, when I try to use it, it is giving me error.

I tried to turn it on and getting the following error.

Failed to call service climate/set_hvac_mode. int() argument must be a string, a bytes-like object or a number, not 'list'

Any idea why?

Thank you in advance

**Comment by al-one** [comment]
Show me the yaml you call this service, and the error logs.

**Comment by reesion** [comment]
Hi,

I managed to figure out the issue. It was my wireless connection being weak and thus the error.

Thank you for your time. I will close the ticket.
