### ISSUE TITLE
可以增加儿童手表的定位功能吗 xiaoxun.watch.sw762

### ISSUE THREAD

**Issue by Jar01** [al-one/hass-xiaomi-miot#142]
能看到硬件清单xiaoxun.watch.sw762，选择后无任何设备被添加

**Comment by al-one** [comment]
手表类型`watch`已经在刚刚的提交：https://github.com/al-one/hass-xiaomi-miot/commit/0c02953e79324012ac1a16c713039e0c4b5cf405 中支持了，但是我从[miot-spec](https://miot-spec.org/miot-spec-v2/instances?status=all)中未找到你的儿童手表型号`xiaoxun.watch.sw762`对应的`urn`，仅找到类似的型号：
```
xiaoxun.watch.sw306   urn:miot-spec-v2:device:watch:0000A07C:xiaoxun-sw306:1
xiaoxun.watch.sw560   urn:miot-spec-v2:device:watch:0000A07C:xiaoxun-sw560:1
xiaoxun.watch.sw660   urn:miot-spec-v2:device:watch:0000A07C:xiaoxun-sw660:1
xiaoxun.watch.sw705   urn:miot-spec-v2:device:watch:0000A07C:xiaoxun-sw705:1
xiaoxun.watch.sw710a2 urn:miot-spec-v2:device:watch:0000A07C:xiaoxun-sw710a2:1
xiaoxun.watch.sw760   urn:miot-spec-v2:device:watch:0000A07C:xiaoxun-sw760:1
xiaoxun.watch.sw766   urn:miot-spec-v2:device:watch:0000A07C:xiaoxun-sw766:1
xiaoxun.watch.sw767   urn:miot-spec-v2:device:watch:0000A07C:xiaoxun-sw767:1
xiaoxun.watch.sw768   urn:miot-spec-v2:device:watch:0000A07C:xiaoxun-sw768:1
xiaoxun.watch.sw900   urn:miot-spec-v2:device:watch:0000A07C:xiaoxun-sw900:1
xiaoxun.watch.sw960   urn:miot-spec-v2:device:watch:0000A07C:xiaoxun-sw960:1
```

**Comment by Jar01** [comment]
谢谢！  
在硬件列表中显示的是 xiaoxun.watch.sw762 (米兔儿童电话手表4C)
Produkt nummer: MTSB11XUN

**Comment by al-one** [comment]
由于没有`urn`，因此该型号无法支持。

**Comment by Jar01** [comment]
urn这几款表看上去都很相似，可以直接把数字改变下加上吗
比如： urn:miot-spec-v2:device:watch:0000A07C:xiaoxun-sw762:1

**Comment by al-one** [comment]
urn与设备型号一一对应，是不同设备miot协议的唯一标识，由设备厂商定义。

**Comment by Jar01** [comment]
这几个智能表的`urn`都是手表型号直接一一对应，`urn`上唯一不同的只有手表型号
比如xiaoxun.watch.sw306  对应 `urn:miot-spec-v2:device:watch:0000A07C:xiaoxun-sw306:1`
       xiaoxun.watch.sw710a2 对应 `urn:miot-spec-v2:device:watch:0000A07C:xiaoxun-sw710a2:1`
未知`urn`在已知型号的情况下难道不可以类推出新的`urn`
比如xiaoxun.watch.sw762 对应的`urn`很可能是`urn:miot-spec-v2:device:watch:0000A07C:xiaoxun-sw762:1`

**Comment by al-one** [comment]
该urn不存在：[`https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:watch:0000A07C:xiaoxun-sw762:1`](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:watch:0000A07C:xiaoxun-sw762:1)

**Comment by Jar01** [comment]
好吧 谢谢

**Comment by al-one** [comment]
请更新到master分支后观察此手表是否可用。

**Comment by Jar01** [comment]
2020-06-29米兔儿童电话手表4C
[xiaoxun.watch.sw762](https://home.miot-spec.com/spec/xiaoxun.watch.sw762)

依旧不可用，设备列表可以看到，但无法成功添加，添加后设备和实体都没有

**Comment by al-one** [comment]
@Jar01 升级到最新的v0.5.4版本了吗？

**Comment by Jar01** [comment]
是的，之前手动升级新版device_tracker.py从新启动HA，无任何变化。今天整个升级到了新版从新启动HA，Xiaomi Miot Auto选项里更新设备列表，设备连接是automatic自动模式，从新点选xiaoxun.watch.sw762 (米兔儿童电话手表4C)，设备和实体里没变化

**Comment by al-one** [comment]
检查有无error/warning日志。

**Comment by Jar01** [comment]
home-assistant.log里没找到和xiaomi_miot里watch或者device_tracker相关的错误日志。  Xiaomi Miot Auto集成从新删除，从起HA，添加新的Xiaomi Miot Auto集成，选择Add devices using Mi Account (账号集成)，所有设备添加，除了个别实体offline显示不可用，设备和实体还是没有watch

**Comment by al-one** [comment]
请通过米家APP共享此设备至`143050915`。

**Comment by guoqiang881245** [comment]
大佬您好，这个米兔4C 现在还是添加不了 请问有解决办法吗？xiaoxun.watch.sw762
