### ISSUE TITLE
deerma.humidifier.jsq2w available modes

### ISSUE THREAD

**Issue by kajarit** [al-one/hass-xiaomi-miot#1421]
### Device model / 设备型号

[deerma.humidifier.jsq2w](https://home.miot-spec.com/s/deerma.humidifier.jsq2w)

### Component version / 插件版本

latest/v0.7.13

### HA core version / HA版本

2023.12.1

### Integrated mode / 集成方式

Automatic (自动模式)

### Xiaomi Smart Humidifier 2
EU version
Model: MJJSQ05DY, 28W, 350 ml/h, <= 38 db(A), 4.5 L

The properties used for this device (miot_type: **jsq2w**) and their values seems to be too complicated compared to other similar device (miot_type: **jsq5**).

Especially the Mode and fan settings are more simple, straightforward and simpler to use for the latter.
I tried both settings for my model and the jsq5 is more useful, the only difference why I don't use it is because the max humidity property is 80 for jsq5 which is 70 for jsq2w.
Please see below what it looks like, maybe it's more obvious when seeing the results.

**JSQ2W** (only the _Constant Humidity_ is a better match for the device compared to the other):
<img width="534" alt="jsq2w" src="https://github.com/al-one/hass-xiaomi-miot/assets/31929264/fa5b0fd5-f1ad-4c12-9025-d2841803215a">

**JSQ5** (here _Level1_, _Level2_, _Level3_ are a better match for the device compared to the other):
<img width="537" alt="Screenshot 2023-12-10 at 13 21 07" src="https://github.com/al-one/hass-xiaomi-miot/assets/31929264/b6a4604d-07f0-4f95-a00d-553b3b1caf01">

As both miot_type works with the device, if possible, please use the jsq5 available_modes for the jsq2w also, this way the separate fan properties will not be needed. Thanks!

### JSQ2W
**miot_type:** urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq2w:1
```
	humidifier properties (relevant only):
		model: deerma.humidifier.jsq2w
		available_modes: Off, None, Constant Humidity
		humidifier.fan_level: 2
		humidifier.status: 2
		humidifier.mode: 0
	fan properties (relevant only):
		preset_modes: Level1, Level2, Level3, Level4
		preset_mode: Level2
		humidifier.fan_level: 2
		humidifier.fan_level_desc: Level2
```

### JSQ5
**miot_type:** urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq5:1
```
	humidifier prop (relevant only):
		model: deerma.humidifier.jsq2w
		available_modes: Off, Level1, Level2, Level3, Humidity
		mode: Level2
		humidifier.fan_level: 2
	fan entity not available
```

**Comment by al-one** [comment]
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    deerma.humidifier.jsq2w:
      mode_property: humidifier.fan_level
```

**Comment by kajarit** [comment]
As I can see there is a fresh release v0.7.14, which includes this.
Works great, thanks!

**Comment by kajarit** [comment]
Oh is there a way to rename Level4 to Humidity?

**Comment by al-one** [comment]
> Oh is there a way to rename Level4 to Humidity?

- https://github.com/al-one/hass-xiaomi-miot/issues/1427#issuecomment-1857630294
