### ISSUE TITLE
空调伴侣如何设定卡片上的温度

### ISSUE THREAD

**Issue by JachinY** [al-one/hass-xiaomi-miot#143]
您好，室内已放置温湿度传感器，如何将值赋给空调伴侣呢

**Comment by al-one** [comment]
可以通过给climate实体添加[自定义属性](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)绑定温度传感器：
```yaml
​climate.your_entity_id​:
  ​bind_sensor​: ​sensor.temperature_entity_id
```

参考：https://github.com/al-one/hass-xiaomi-miot/issues/74#issuecomment-837771416
