### ISSUE TITLE
Cannot send mc1808 to clean specific room

### ISSUE THREAD

**Issue by PGayol** [al-one/hass-xiaomi-miot#1437]
### Device model / 设备型号

dreame.vacuum.mc1808

### Component version / 插件版本

0.7.14

### HA core version / HA版本

2023.12.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Hi!

At some point in the past I was able to send my mc1808 to clean a specific room, but I'm not able anymore. Vacuum doesn't start cleaning. I'm able to clean the whole house with the integration, as well as other functions (locate, back to dock, etc), but no room/zone cleaning.

This is the service call I'm using:

```
service: xiaomi_miot.call_action
data:
  throw: true
  entity_id: vacuum.dreame_mc1808_0750
  siid: 18
  aiid: 1
  params: 
    - piid: 1,
      value: 18
    - piid: 21,
      value: "{\"selects\":[[2,1,1,3,1]]}"
```

And the result is:

`{'did': '382827525', 'miid': 0, 'siid': 18, 'aiid': 1, 'code': -704220025, 'exe_time': 0, 'withLatency': 0}`

### Entity attributes / 实体属性

fan_speed_list: Silent, Standard, Medium, Turbo
battery_level: 99
battery_icon: mdi:battery-charging-100
fan_speed: Standard
model: dreame.vacuum.mc1808
lan_ip: 192.168.0.233
mac_address: D4:D2:D6:F5:07:50
entity_class: MiotVacuumEntity
exclude_miot_services: consumable, annoy, remote, time
exclude_miot_properties: delete_timer, clean_info, map_view, frame_info
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:dreame-mc1808:1
vacuum.fault: 0
vacuum.status: 6
audio.volume: 43
audio.voice_packets: EN
clean.work_mode: 6
clean.area: 
clean.timer: 
clean.mode: 1
clean.water_box.error: -704030013 Property is not readable
clean.total_clean_time: 23003
clean.total_clean_times: 1744
clean.total_clean_area: 15732
clean.clean_log_start_time: 1612799326
clean.button_led: 0
clean.task_done: 1
brush_left_time-28-1: 21
brush_life_level-28-2: 10
filter.filter_life_level: 49
filter.filter_left_time: 74
brush_cleaner.brush_left_time: 151
brush_cleaner.brush_life_level: 50
battery.charging_state: 1
state_updater: cloud
vacuum.status_desc: Charging
sub_entities: vacuum-3.status-2, filter-27.filter_life_level-1, filter-27.filter_left_time-2, battery-2.battery_level-1, battery-2.charging_state-2, brush_cleaner-26.brush_left_time-1, brush_cleaner-26.brush_life_level-2, brush_cleaner-28.brush_left_time-1, brush_cleaner-28.brush_life_level-2
miot_action_result: 
did: '382827525'
miid: 0
siid: 18
aiid: 1
code: -704220025
exe_time: 0
withLatency: 0

miot_action_error: -704220025 The number of action parameters does not match
friendly_name: Aspiradora Robot Cleaner
supported_features: 13048

**Comment by araik1998** [comment]
Hi, is there a solution?

**Comment by PGayol** [comment]
> Hi, is there a solution?

Hi! I've found that the issue seems to be related to the vacuum being connected to my 2.4GHz wifi network. Since the xiaomi mobile app does not provide an easy way to change the network, I just disable my 2.4 from the router settings for a few minutes, so the vacuum automatically connects to the 5.8GHz network.

The "remote" option from the Mi Home app works super laggy when connected to 2.4. So this also fixes that issue.

**Comment by KapriQ** [comment]
Is there anyone with working room cleaning on Miija 1C ?

**Comment by PGayol** [comment]
> Is there anyone with working room cleaning on Miija 1C ?

Currently working here on my side

**Comment by KapriQ** [comment]
> > Is there anyone with working room cleaning on Miija 1C ?
> 
> Currently working here on my side

That's nice. And Can you please share your config / detailed info how it is working for you? because i have spent almost 6 hours with the same result. The room cleaning is not working. I have Xiaomi MIOT Auto integration

**Comment by PGayol** [comment]
> KapriQ

Sure! This is in my configuration.yaml:
`xiaomi_miot:
  language: en
  device_customizes:
    dreame.vacuum.mc1808:
        auto_cloud: true
        # miot_local: true`
 
 And this is the Lovelace Vacuum Map card configuration from where I send my room cleaning command:
 
 `- type: custom:xiaomi-vacuum-map-card
    map_source:
      camera: camera.xiaomi_cloud_map_extractor
    calibration_source:
      camera: true
    entity: vacuum.dreame_mc1808_0750
    vacuum_platform: al-one/hass-xiaomi-miot
    map_modes:
      - template: vacuum_clean_zone
        max_selections: 1
        repeats_type: EXTERNAL
        max_repeats: 3
        service_call_schema:
          evaluate_data_as_template: true
          service: xiaomi_miot.call_action
          service_data:
            entity_id: '[[entity_id]]'
            siid: 18
            aiid: 1
            params:
              - piid: 1
                value: 19
              - piid: 21
                value: '{"areas":[[[[selection_unwrapped]],[[repeats]],1,1]]}'
            force_params: true
      - template: vacuum_clean_segment
        max_selections: 8
        repeats_type: EXTERNAL
        max_repeats: 3
        service_call_schema:
          evaluate_data_as_template: true
          service: xiaomi_miot.call_action
          service_data:
            entity_id: '[[entity_id]]'
            siid: 18
            aiid: 1
            params:
              - piid: 1
                value: 18
              - piid: 21
                value: '{"selects":[[[[selection_unwrapped]],[[repeats]],1,3,1]]}'
            force_params: true
        predefined_selections:
          - id: '1'
            icon:
              name: mdi:broom
              x: -3450
              'y': 3350
            label:
              text: Cuarto
              x: -3450
              'y': 3350
              offset_y: 35
            outline:
              - - -4750
                - 1600
              - - -2150
                - 1600
              - - -2150
                - 5100
              - - -4750
                - 5100
          - id: '2'
            icon:
              name: mdi:broom
              x: -4275
              'y': 425
            label:
              text: Baño
              x: -4275
              'y': 425
              offset_y: 35
            outline:
              - - -5050
                - -700
              - - -3500
                - -700
              - - -3500
                - 1550
              - - -5050
                - 1550
          - id: '3'
            icon:
              name: mdi:broom
              x: -2775
              'y': 1125
            label:
              text: Pasillo
              x: -2775
              'y': 1125
              offset_y: 35
            outline:
              - - -3450
                - 700
              - - -2100
                - 700
              - - -2100
                - 1550
              - - -3450
                - 1550
          - id: '4'
            icon:
              name: mdi:broom
              x: -1375
              'y': 225
            label:
              text: Barra
              x: -1375
              'y': 225
              offset_y: 35
            outline:
              - - -1950
                - 0
              - - -800
                - 0
              - - -800
                - 450
              - - -1950
                - 450
          - id: '5'
            icon:
              name: mdi:broom
              x: -2125
              'y': -500
            label:
              text: Cocina
              x: -2125
              'y': -500
              offset_y: 35
            outline:
              - - -3450
                - -950
              - - -800
                - -950
              - - -800
                - -50
              - - -3450
                - -50
          - id: '6'
            icon:
              name: mdi:broom
              x: -600
              'y': 1525
            label:
              text: Living
              x: -600
              'y': 1525
              offset_y: 35
            outline:
              - - -2050
                - -1450
              - - 850
                - -1450
              - - 850
                - 4500
              - - -2050
                - 4500
    map_locked: true`
