### ISSUE TITLE
温湿度计的 湿度 状态无法在 Homekit 中显示！

### ISSUE THREAD

**Issue by weiyideai520** [al-one/hass-xiaomi-miot#144]
温湿度计的 湿度 状态无法在 Homekit 中显示！

在Hass 查看 温湿度的 湿度显示成了 温度的图标，应该类型device_class 出现了错误，应该是 humidity

temperature_humidity_sensor.relative_humidity: 72
unit_of_measurement: '%'
friendly_name: 客厅温湿度 Temperature Humidity Sensor Relative Humidity
supported_features: 0
device_class: temperature

**Comment by al-one** [comment]
设备型号多少？

**Comment by al-one** [comment]
请更新至master后尝试。

**Comment by weiyideai520** [comment]
我感觉你这么判断应该不行

> if 'temperature' in name:
             ret = DEVICE_CLASS_TEMPERATURE
         elif 'humidity' in name:
             ret = DEVICE_CLASS_HUMIDITY

------
因名字里面 既有 temperature 又有 humidity
如我的设备名称就是 ：sensor.ke_ting_wen_shi_du_temperature_humidity_sensor_relative_humidity
-----
我修改如下
props = {
            'temperature': DEVICE_CLASS_TEMPERATURE,
            'relative_humidity': DEVICE_CLASS_HUMIDITY,
            'battery': DEVICE_CLASS_BATTERY,
            
---------------

测试了如下型号可以正常显示了
lumi.weather.v1
lumi.sensor_ht.v1（这个缺少了大气压）
cgllc.sensor_ht.dk2
miaomiaoce.sensor_ht.t2

**Comment by weiyideai520** [comment]
可以了，幸苦了
