### ISSUE TITLE
iot.switch.padw2p，用电量为0，缺少日、月、年用电量，米家app有，能否增加

### ISSUE THREAD

**Issue by qq610368720** [al-one/hass-xiaomi-miot#1451]
### Device model / 设备型号

iot.switch.padw2p

### Component version / 插件版本

0.7.14

### HA core version / HA版本

2023.12.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

![QQ截图20231225204748](https://github.com/al-one/hass-xiaomi-miot/assets/51961126/b520ed2e-c39a-46d4-82d9-8388d8236d1c)
![QQ图片20231225205157](https://github.com/al-one/hass-xiaomi-miot/assets/51961126/5c29a4a5-a723-4700-810f-5e40839d5163)

### Entity attributes / 实体属性

device_class: switch
friendly_name: 智能总空开 Switch
supported_features: 0
model: iot.switch.padw2p
lan_ip: 192.168.11.50
mac_address: B8:50:D8:C8:45:AF
entity_class: MiotSwitchEntity
miot_type: urn:miot-spec-v2:device:switch:0000A003:iot-padw2p:1:0000D00D
switch.on: true
switch.fault: 0
switch.default_power_on_state: 2
switch.temperature: 28
custom.self_check: false
custom.leak_set: AA0500001F173B
custom.leak_switch: true
custom.voice_switch: false
custom.over_electric_set: 63
custom.lack_voltage_set: 170
custom.delay_set: 15
custom.timer_set: AA1F0000000000000000000000000000000000000000000000000000000000001F
custom.close_temp_set: 70
custom.over_voltage_set: 275
custom.alert_temp_set: 60
custom.setting_tips: AA1001013F5AD200E601400A643C64325A3E
screen.on: false
power_consumption: 0
electric_current-3-2: 4.39
electric_power-3-3: 898
power_consumption.voltage: 229
state_updater: lan
sub_entities: switch-2.fault-5, switch-2.temperature-9, power_consumption-3.power_consumption-1, power_consumption-3.electric_current-2, power_consumption-3.electric_power-3, power_consumption-3.voltage-4

### Home Assistant Logs / 系统日志

智能总空开(iot.switch.padw2p): Got MiioException while fetching the state: Unable to discover the device 192.168.11.50, mapping: {'switch.on': {'siid': 2, 'piid': 1}, 'switch.fault': {'siid': 2, 'piid': 5}, 'switch.default_power_on_state': {'siid': 2, 'piid': 8}, 'switch.temperature': {'siid': 2, 'piid': 9}, 'custom.self_check': {'siid': 5, 'piid': 19}, 'custom.leak_set': {'siid': 5, 'piid': 20}, 'custom.leak_switch': {'siid': 5, 'piid': 21}, 'custom.voice_switch': {'siid': 5, 'piid': 22}, 'custom.over_electric_set': {'siid': 5, 'piid': 23}, 'custom.lack_voltage_set': {'siid': 5, 'piid': 24}, 'custom.delay_set': {'siid': 5, 'piid': 28}, 'custom.timer_set': {'siid': 5, 'piid': 29}, 'custom.close_temp_set': {'siid': 5, 'piid': 30}, 'custom.over_voltage_set': {'siid': 5, 'piid': 31}, 'custom.alert_temp_set': {'siid': 5, 'piid': 32}, 'custom.setting_tips': {'siid': 5, 'piid': 33}, 'screen.on': {'siid': 4, 'piid': 1}, 'power_consumption': {'siid': 3, 'piid': 1}, 'electric_current-3-2': {'siid': 3, 'piid': 2}, 'electric_power-3-3': {'siid': 3, 'piid': 3}, 'power_consumption.voltage': {'siid': 3, 'piid': 4}}, max_properties: 7/21

**Comment by HanTirong** [comment]
米家智能插座3 每日用电量为0，当月用电量正常
![image](https://github.com/al-one/hass-xiaomi-miot/assets/114554456/b1101739-62fe-42bb-ab90-dd0e4367c027)

**Comment by roycho93** [comment]
请问这个问题有没有得到解决，我也用的这款断路器

**Comment by al-one** [comment]
在此讨论：https://github.com/al-one/hass-xiaomi-miot/issues/1530
