### ISSUE TITLE
customize.yaml causing MiotSensorEntity's temperature readings to not work

### ISSUE THREAD

**Issue by melandmeland** [al-one/hass-xiaomi-miot#1458]
i have customize.yaml to increase the detect inverval for my thermometer, it worked fine until i decided to udpate HASS core to latest, now it can't fetch temperature and humidity data
the bluetooth power plug still works as i can turn on and off the power

here's the error in log

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:133
First occurred: 2023年12月27日 16:36:25 (1 occurrences)
Last logged: 2023年12月27日 16:36:25

Detected that custom integration 'miot' restore_state.RestoreStateData.async_get_instance is deprecated, and not intended to be called by custom components; Pleaserefactor your code to use RestoreEntity instead; restore_state.async_get(hass) can be used in the meantime at custom_components/miot/sensor.py, line 613: restored = await RestoreStateData.async_get_instance(self.hass), please report it to the author of the 'miot' custom integration

and this is what i put in customize.yaml

sensor.miaomiaoce_t2_xxxx_temperature_humidity_sensor:
  interval_seconds: 1800

i have to remove lines in configuratuion.yaml to not use customize.yaml in order for HASS to read temperature/humidity data again.

**Comment by codyc1515** [comment]
Possible regression from, or missed in, #1144
