### ISSUE TITLE
绿米的水浸传感器 lumi.sensor_wleak.aq1 

### ISSUE THREAD

**Issue by weiyideai520** [al-one/hass-xiaomi-miot#146]
这款老版的水浸传感器无法识别到

**Comment by al-one** [comment]
已修复。

**Comment by weiyideai520** [comment]
关于大气压，class 还是写错了
需要在 miot_spec.py 文件中添加如下代码
-------
 'atmospheric_pressure': DEVICE_CLASS_PRESSURE,
----------
props = {
            'temperature': DEVICE_CLASS_TEMPERATURE,
            'relative_humidity': DEVICE_CLASS_HUMIDITY,
            'humidity': DEVICE_CLASS_HUMIDITY,
            'battery_level': DEVICE_CLASS_BATTERY,
            'battery': DEVICE_CLASS_BATTERY,
            'illumination': DEVICE_CLASS_ILLUMINANCE,
            'voltage': DEVICE_CLASS_VOLTAGE,
            'electric_current': DEVICE_CLASS_CURRENT,
            'electric_power': DEVICE_CLASS_POWER,
            'co2': DEVICE_CLASS_CO2,
            'atmospheric_pressure': DEVICE_CLASS_PRESSURE,
        }
