### ISSUE TITLE
除湿机，无法调整湿度

### ISSUE THREAD

**Issue by weiyideai520** [al-one/hass-xiaomi-miot#147]
型号：nwt.derh.330ef
型号：nwt.derh.312en
----------
这两款型号都不行，可以控制开关，但是不是调整湿度

**Comment by weiyideai520** [comment]
非常感谢，可以使用了

**Comment by weiyideai520** [comment]
我找到个这个：不知道是否继承进去
https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:dehumidifier:0000A02D:nwt-312en:1

{"iid":3,"type":"urn:nwt-spec:property:water-tank-status:00000003:nwt-312en:1","description":"水箱满或移除","format":"bool","access":["read","notify"]}

**Comment by al-one** [comment]
@League2EB 

https://home.mi.com/baike/index.html#/detail?model=nwt.derh.330ef

https://home.mi.com/baike/index.html#/detail?model=nwt.derh.312en

**Comment by League2EB** [comment]
> @League2EB
> 
> https://home.mi.com/baike/index.html#/detail?model=nwt.derh.330ef
> 
> https://home.mi.com/baike/index.html#/detail?model=nwt.derh.312en

@al-one 謝謝作者的支援
因為剛踏入這個環境，目前最痛苦的就是尋找有支援的設備型號是那些
想詢問 loock.cateye.v02 這個有支援嗎?
再次感謝

**Comment by al-one** [comment]
@League2EB 可视门铃类目前仅支持电量等传感器，暂不支持视频流。其他问题请创建新的issue，并且请勿再回复此issue。
