### ISSUE TITLE
每隔1-2天米家内的智能会失效

### ISSUE THREAD

**Issue by zxerqw** [al-one/hass-xiaomi-miot#1470]
Hello,

我的HASS单独就装了这个插件，在nodered设置了一些简单的获取状态，小爱播报的流程。
但是不知道为什么每1-2天左右米家的智能化都会失效，比如一些感应器，能看到灯闪了一下，米家内也是可以看到有触发了，但就是不会执行设置好的智能化，只能断电重启设备才恢复，大概去年到今天，尝试过好几次都是这个情况

**Comment by al-one** [comment]
> 只能断电重启设备才恢复

断电重启的具体什么设备。

**Comment by zxerqw** [comment]
不好意思，忘记说了，是米家多模网关2

**Comment by zxerqw** [comment]
这两天测试了一下，只登录账号，不添加任何设备看起来没有问题，之后我加了2台小爱音箱，没有在nodered用到这两个设备，差不多两天后就出现问题了 @al-one  想问问这个我有什么办法调试吗？

**Comment by al-one** [comment]
@zxerqw  请问关闭这个issue的原因是什么

**Comment by zxerqw** [comment]
不知道为什么这次重启后没有发生失效的情况了，同样还是只有2个小爱，可能是升级了新版修复了？我也不知道如何调试就关闭了，如果有需要的话我把所有设备按照平时使用的添加进来看看

**Comment by zxerqw** [comment]
我把设备都添加进来了，用几天更新情况

**Comment by zxerqw** [comment]
现在没问题了，没出现智能不触发的情况
