### ISSUE TITLE
No sensors available in humidifier.deerma_jsq2w_a42e_humidifier

### ISSUE THREAD

**Issue by Gmarapet** [al-one/hass-xiaomi-miot#1474]
### Device model / 设备型号

humidifier.deerma_jsq2w_a42e_humidifier

### Component version / 插件版本

0.7.14

### HA core version / HA版本

2024.1.0

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

After update HA core no more sensors available.

### Entity attributes / 实体属性

![Screenshot_20240104-001149](https://github.com/al-one/hass-xiaomi-miot/assets/17617764/77eb18c5-eb08-4f25-bd79-faf1be91b225)

**Comment by Alfy1080** [comment]
Same happened to me with a bunch of devices using this integration. Camera, Fan, Humidifier entities became unavailable a few hours ago.

**Comment by ArellanoF** [comment]
The same problem in HA 2024.01, any solutions?

**Comment by al-one** [comment]
- #1641

Fixed in v0.7.15.

**Comment by ArellanoF** [comment]
This sensor works on 2023.12.4 but not on 2024.01, is it possible?

sensor.miaomiaoce_t2_8fb6_temperature_humidity_sensor
