### ISSUE TITLE
Problem with devices in HA 2024.01

### ISSUE THREAD

**Issue by ArellanoF** [al-one/hass-xiaomi-miot#1478]
### Device model / 设备型号

miaomiaoce.sensor_ht.t2

### Component version / 插件版本

0.7.15

### HA core version / HA版本

2024.01

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

This device and other like cgllc.clock.dov, cleargrass.sensor_ht.dk1, not working in HA 2024.01, but in HA 2023.X is work.

Thanks

### Entity attributes / 实体属性

state_class: measurement
model: miaomiaoce.sensor_ht.t2
lan_ip: 
mac_address: A4:C1:38:9F:8F:B6
entity_class: MiotSensorEntity
home_room: Mi Casa Habitación Lola
miot_type: urn:miot-spec-v2:device:temperature-humidity-sensor:0000A00A:miaomiaoce-t2:1
state_property: temperature-2-1
temperature-2-1: 17.5
relative_humidity-2-2: 66.6
battery_level: 100
state_updater: cloud
sub_entities: battery-3.battery_level-1, temperature_humidity_sensor-2.relative_humidity-2
unit_of_measurement: °C
device_class: temperature
friendly_name: Hab. Lola Temperature Humidity Sensor
supported_features: 0

**Comment by al-one** [comment]
- #1475

**Comment by ArellanoF** [comment]
Thanks
