### ISSUE TITLE
Device support ! 

### ISSUE THREAD

**Issue by League2EB** [al-one/hass-xiaomi-miot#148]
any one can support device model : isa.camera.hlc7 ? 

thx all

**Comment by al-one** [comment]
This model of camera has two miot-spec urn:
```
urn:miot-spec-v2:device:camera:0000A01C:isa-hlc7:1 # version 1
urn:miot-spec-v2:device:camera:0000A01C:isa-hlc7:2 # version 2
```

`start-hls-stream` is supported in version 2. If you get a notification saying `Your camera doesn't support streaming services` when integrating the device, you need to delete `.storage/xiaomi_miot/instances.json` in the HA directory and reload the integration.

**Comment by League2EB** [comment]
@al-one 我刪除了該文件，但我的控制台目前呈現該情況

![image.png](https://i.loli.net/2021/07/27/OtcfMIewzgSsr6d.png)

目前可以控制鏡頭開關，但無法看見攝影機畫面 

我該怎麼正確地把攝影機加入 ?

我使用本地Token集成

非常感謝指導

**Comment by al-one** [comment]
`miot_action_error`中的错误码表示服务不存在，无法通过action获取流地址，可能厂商定义的miot-spec有问题。

**Comment by al-one** [comment]
暂无解决方案。

**Comment by League2EB** [comment]
> 暂无解决方案。

https://github.com/al-one/hass-xiaomi-miot/issues/11#issuecomment-771462773

這是我不能理解了，貌似isa.camera.hlc6 可以獲得解決，但是isa.camera.hlc7卻無法解決

是否我用相同方式可能可以運行?

**Comment by al-one** [comment]
hlc7无法通过miot云端接口获取流地址，问题出在云端，插件无能为力。

**Comment by League2EB** [comment]
> hlc7无法通过miot云端接口获取流地址，问题出在云端，插件无能为力。

這個問題需要等官方那邊開通接口才能讓問題解決的意思嗎 ? 

無論如何感謝您的貢獻!

**Comment by al-one** [comment]
> 這個問題需要等官方那邊開通接口才能讓問題解決的意思嗎 ?

可以这么理解，这款摄像头刚发布的时候是没有`start-hls-stream` miot action的，后来更新了一版协议后才加上，因此也许厂家会在后续版本的设备固件中支持。

**Comment by al-one** [comment]
See https://github.com/al-one/hass-xiaomi-miot/issues/166
