### ISSUE TITLE
小米烟雾报警器无法识别

### ISSUE THREAD

**Issue by weiyideai520** [al-one/hass-xiaomi-miot#149]
Name: Mi Smoke Detector
Model: lumi.sensor_smoke.mcn02

**Comment by al-one** [comment]
[miot-spec](https://miot-spec.org/miot-spec-v2/instances?status=all)中未找到型号`lumi.sensor_smoke.mcn02`对应的`urn`。

**Comment by befantasy** [comment]
这个设备现在可以接入了，HA中看起来也正常，但是在homekit中总是无响应，每次重启HA之后都要手动重载homekit bridge才能恢复正常。也没有什么报错。
