### ISSUE TITLE
水侵传感器 lumi.sensor_wleak.aq1 状态显示未知

### ISSUE THREAD

**Issue by weiyideai520** [al-one/hass-xiaomi-miot#150]
此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.binary_sensor
Source: custom_components/xiaomi_miot/binary_sensor.py:236
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 11:15:27 (261 occurrences)
Last logged: 12:20:28

Get miio data for 水浸传感器 Submersion Sensor failed: None

**Comment by weiyideai520** [comment]
我觉得可以给个默认值，（干燥）。这个传感器是 ZB协议的，
应该是没有检查到水就没有上报信息

**Comment by al-one** [comment]
设备型号多少？

**Comment by weiyideai520** [comment]
lumi.sensor_wleak.aq1

**Comment by al-one** [comment]
请加QQ群：[198841186](https://jq.qq.com/?_wv=1027&k=lZAMn5Uo)联系我

**Comment by al-one** [comment]
已修复，请更新到master分支后尝试。

**Comment by catzym** [comment]
已经使用最新的0.6.4版本，水侵传感器 lumi.sensor_wleak.aq1 状态还是显示未知
