### ISSUE TITLE
zhimi.airpurifier.sa2 fan level

### ISSUE THREAD

**Issue by naix07** [al-one/hass-xiaomi-miot#1500]
### Device model / 设备型号

zhimi.airpurifier.sa2

### Component version / 插件版本

0.7.14

### HA core version / HA版本

2024.1.1

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

Problem setting fan level to 3 when calling service `xiaomi_miot.set_miot_property` using values `'siid': 2, 'piid': 2, 'value': 5` as per [spec](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-sa2:2)

### Entity attributes / 实体属性

preset_modes: Auto, Sleep, Favorite, None
friendly_name: Xiaomi Air Purifier MAX Pro Air Purifier
supported_features: 9
percentage_step: 17
preset_mode: Favorite
model: zhimi.airpurifier.sa2
lan_ip: 192.168.x.x
mac_address: 50:EC:50:x:x:x
entity_class: MiotFanEntity
exclude_miot_services: button, filter_time, rfid, others
exclude_miot_properties: average_aqi_cnt, aqi_zone, sensor_state, aqi_goodh, aqi_runstate, aqi_state, motor_strong, motor_high, motor_med, motor_med_l, motor_low, motor_silent, motor_favorite, motor_set_speed
miot_type: urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-sa2:2
aqi: 1
motor1_speed: 0
purify_volume: 5130340
air_purifier.on: false
air_purifier.fan_level: 2
air_purifier.mode: 2
favorite_fan_level-9-1: 9
physical_controls_locked: false
alarm: false
indicator_light.on: true
indicator_light.brightness: 0
filter-5.filter_life_level: 28
filter-5.filter_used_time: 5726
filter.filter_life_level: 28
filter.filter_used_time: 5726
environment.relative_humidity: 62
environment.pm2_5_density: 1
environment.temperature: 29.4
state_updater: lan
sub_entities: air_purifier-2.on-1, alarm-7.alarm-1, air_purifier_favorite-9.favorite_fan_level-1, environment-3.relative_humidity-1, environment-3.pm2_5_density-2, environment-3.temperature-3, filter-4.filter_life_level-1, filter-4.filter_used_time-2, filter-5.filter_life_level-1, filter-5.filter_used_time-2, physical_controls_locked-8.physical_controls_locked-1, indicator_light-6
percentage: null

### Home Assistant Logs / 系统日志

Xiaomi Air Purifier MAX Pro(zhimi.airpurifier.sa2): Set miot property {'did': 'prop.2.2', 'siid': 2, 'piid': 2, 'value': 5} failed: {'code': -5001, 'message': 'invaild_arg'}

**Comment by al-one** [comment]
Try master branch.

**Comment by naix07** [comment]
> Try master branch.
Confirming that it now works on 0.7.17.
