### ISSUE TITLE
如何指定自定义实体中switch_properties的对应值呢？

### ISSUE THREAD

**Issue by micturkey** [al-one/hass-xiaomi-miot#1503]
[yeelink.bhf_light.v10](https://home.miot-spec.com/s/yeelink.bhf_light.v10) 浴霸中有一个干燥功能，只有在`ptc_bath_heater.mode=1`时才可以启动
为了方便在ha中开关这一功能，我把`ptc_bath_heater.mode`放到了自定义实体中`switch_properties`里。
但是始终无法通过这一个开关打开干燥功能，我检查了一下，发现在`ptc_bath_heater`实体中开启干燥功能，是将`ptc_bath_heater.mode`设为`1`，而`switch_properties`则是设置为`true`，因此导致了问题的发生，后面我也用`Xiaomi Miot Auto: Set miot property`服务试了一下，确实如此。
所以，请问有没有办法指定自定义实体中开关实体的可选值呢？

**Comment by al-one** [comment]
更新到master分支，并且添加自定义：
```yaml
descriptions_for_on: Dry
descriptions_for_off: Idle
```

- #600

**Comment by micturkey** [comment]
> 更新到master分支，并且添加自定义：
> 
> ```yaml
> 
> descriptions_for_on: Dry
> 
> descriptions_for_off: Idle
> 
> ```
> 
> 
> 
> - #600

感谢！
