### ISSUE TITLE
Xiaomi Vacuum S12

### ISSUE THREAD

**Issue by MotoWiZ** [al-one/hass-xiaomi-miot#1509]
### Device model / 设备型号

xiaomi.vacuum.b106eu

### Component version / 插件版本

0.7.15

### HA core version / HA版本

2024.1.4

### Integrated mode / 集成方式

Automatic (自动模式) or Token

### The problem / 问题详情

Unable to discover the device 192.168.1.77. It's unusable in HA Core 2024.1.4

### Entity attributes / 实体属性

fan_speed_list: Slient, Standard, Medium, Turbo
friendly_name: Xiaomi Robot Vacuum S12 Robot Cleaner
supported_features: 12536

### Home Assistant Logs / 系统日志

list:
  - did: "1055473378"
    name: Xiaomi Robot Vacuum S12
    host: 192.168.1.77
    model: xiaomi.vacuum.b106eu
    token: 6a4977335665486f64516d54586e7862
    miio_cmd: >-
      miiocli device --ip 192.168.1.77 --token 6a4977335665486f64516d54586e7862
      info
    miio_info:
      error: Unable to discover the device 192.168.1.77

**Comment by MotoWiZ** [comment]
Problem solved. Instead of automatic connection in configuration, just force cloud connection.

**Comment by xvolte** [comment]
I got it working too, using the force cloud solution.
However, I noticed I can define the aspiration force, but I can not select if I want it to mop only, or to do both dust & mop ...
Anyway to do that ?
I also noticed there is no setting available to select the amount of water to use (like in the app itself)

if someone figured this out, could you help please ? 👍 
Thank you very much in advance

**Comment by PapaFuchs84** [comment]
> I got it working too, using the force cloud solution. However, I noticed I can define the aspiration force, but I can not select if I want it to mop only, or to do both dust & mop ... Anyway to do that ? I also noticed there is no setting available to select the amount of water to use (like in the app itself)
> 
> if someone figured this out, could you help please ? 👍 Thank you very much in advance

I have the Same Problems Here. Would be awesome If the Xiaomi s12 would be supported completely.

**Comment by diegogarciaarriaza** [comment]
I can`t connect my vacuum S12, how do you did? Any help would be very appreciated!

With Integration "Xiaomi Miio" I get a message saying something like "unknown device.. cannot be configured following the config flow..."

With hacks maybe?

Thanks!

**Comment by lrlunin** [comment]
> I can`t connect my vacuum S12, how do you did? Any help would be very appreciated!
> 
> With Integration "Xiaomi Miio" I get a message saying something like "unknown device.. cannot be configured following the config flow..."
> 
> With hacks maybe?
> 
> Thanks!

Just have the same issue now while before the last week it worked perfectly.
