### ISSUE TITLE
Unable to get the stream from the IP cameras 

### ISSUE THREAD

**Issue by MiAutomations** [al-one/hass-xiaomi-miot#152]
Hello I have the following error for all this camera models 

![image](https://user-images.githubusercontent.com/47602733/127474597-51390378-57f5-4c72-bea9-36d0c386beaa.png)

lumi.camera.gwagl01 
lumi.camera.aq1 
isa.camera.df3 
xiaovv.camera.ptz 
xiaovv.camera.lamp
xiaovv.camera.xvb4
xiaovv.camera.xva3
chuangmi.camera.v2
chuangmi.camera.v5
chuangmi.camera.v3
chuangmi.camera.ip026c
chuangmi.camera.ip029a
chuangmi.camera.ipc016
chuangmi.camera.ipc019e 
chuangmi.camera.ipc020 
chuangmi.camera.ipc013d
chuangmi.camera.v6

Can you please help me in order to solve this issue ?

Thank you in advance for your support and best regards

**Comment by MiAutomations** [comment]
But I still receiving the message in my mobile phone that is watching the stream as you can view in this image 
![Screenshot_2021-07-29-09-55-56-808_com miui home](https://user-images.githubusercontent.com/47602733/127510304-7ddc8df0-ad8c-4e5d-ace1-e4b12c7756ce.jpg)

**Comment by MiAutomations** [comment]
@al-one Can you please help me in order to solve this issue ? 
Thank you

**Comment by Zeunas** [comment]
Try to downgrade to version 0.3.8 newer versions of the add-on have affected the camera streams l, even the new one that was just released has not fixed the stream yet.
