### ISSUE TITLE
Home Assistant is annoying with these error messages

### ISSUE THREAD

**Issue by Toolmaster30** [al-one/hass-xiaomi-miot#1528]
Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 12:41:41 (3128 occurrences)
Last logged: 12:41:53

DATA_RATE_KIBIBYTES_PER_SECOND was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfDataRate.KIBIBYTES_PER_SECOND instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
DATA_RATE_MEBIBYTES_PER_SECOND was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfDataRate.MEBIBYTES_PER_SECOND instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
DATA_RATE_GIBIBYTES_PER_SECOND was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfDataRate.GIBIBYTES_PER_SECOND instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
ENTITY_CATEGORY_CONFIG was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use EntityCategory.CONFIG instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
ENTITY_CATEGORY_DIAGNOSTIC was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use EntityCategory.DIAGNOSTIC instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

**Comment by dincojazz** [comment]
Same to me too.
I've updated to Home Assistant Core 2024.2.0 and the things goes mad. Even the integration won't load for this errors. Reverted back to last version with restore from backup and integration is working but filling log with this errors:

Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 22:38:25 (3542 occurrences)
Last logged: 22:42:13

DATA_RATE_KIBIBYTES_PER_SECOND was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfDataRate.KIBIBYTES_PER_SECOND instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
DATA_RATE_MEBIBYTES_PER_SECOND was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfDataRate.MEBIBYTES_PER_SECOND instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
DATA_RATE_GIBIBYTES_PER_SECOND was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfDataRate.GIBIBYTES_PER_SECOND instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
ENTITY_CATEGORY_CONFIG was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use EntityCategory.CONFIG instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
ENTITY_CATEGORY_DIAGNOSTIC was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use EntityCategory.DIAGNOSTIC instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

Logger: homeassistant.components.alarm_control_panel.const
Source: helpers/deprecation.py:205
Integration: Alarm control panel (documentation, issues)
First occurred: 22:41:29 (8 occurrences)
Last logged: 22:41:29

SUPPORT_ALARM_ARM_AWAY was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_AWAY instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
SUPPORT_ALARM_ARM_NIGHT was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_NIGHT instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
SUPPORT_ALARM_TRIGGER was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.TRIGGER instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
SUPPORT_ALARM_ARM_CUSTOM_BYPASS was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_CUSTOM_BYPASS instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
SUPPORT_ALARM_ARM_VACATION was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_VACATION instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

Logger: homeassistant.components.humidifier.const
Source: helpers/deprecation.py:205
Integration: Humidifier (documentation, issues)
First occurred: 22:41:06 (3 occurrences)
Last logged: 22:41:06

DEVICE_CLASS_HUMIDIFIER was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use HumidifierDeviceClass.HUMIDIFIER instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
DEVICE_CLASS_DEHUMIDIFIER was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use HumidifierDeviceClass.DEHUMIDIFIER instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
SUPPORT_MODES was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use HumidifierEntityFeature.MODES instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

Logger: homeassistant.components.climate.const
Source: helpers/deprecation.py:205
Integration: Climate (documentation, issues)
First occurred: 22:38:25 (42 occurrences)
Last logged: 22:41:00

SUPPORT_TARGET_HUMIDITY was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_HUMIDITY instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
SUPPORT_FAN_MODE was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
SUPPORT_PRESET_MODE was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
SUPPORT_SWING_MODE was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.SWING_MODE instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
SUPPORT_AUX_HEAT was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.AUX_HEAT instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

and much more

**Comment by Shinji-IkariG** [comment]
I have same issue

**Comment by kuailezhiyuan** [comment]
+1

**Comment by macxl69** [comment]
+1
