### ISSUE TITLE
Select Auto/Lan/Cloud individually for devices 

### ISSUE THREAD

**Issue by Cook23** [al-one/hass-xiaomi-miot#1537]
Hello,

Cannot found a way to force some devices to use "cloud" (because connected on another lan sub-network) while other devices use "lan"

Thanks

**Comment by SodaWithoutSparkles** [comment]
Just setup 3 entries

![Screenshot_2024-02-21-19-31-49-559_io.homeassistant.companion.android-edit.jpg](https://github.com/al-one/hass-xiaomi-miot/assets/64138578/4ffc34cb-aa8a-4689-8c6e-a1df064f0498)
