### ISSUE TITLE
cuco.plug.cp1m设备异常问题

### ISSUE THREAD

**Issue by JachinY** [al-one/hass-xiaomi-miot#154]
大佬，有几个小问题想请教您 @al-one 
1.
![image](https://user-images.githubusercontent.com/42339509/127777562-d92e9fff-9175-42ad-ab77-8ece7c6c4937.png)
cuco.plug.cp1m设备 gosund智能插座一直不可用 不管是局域网还是云端 昨天曾经成功添加过一次 能在实体信息里看到电流等信息，但是没有对应的sensor
2.
![image](https://user-images.githubusercontent.com/42339509/127777588-cf70a63e-172d-49d7-b991-60d0848adcdd.png)
![image](https://user-images.githubusercontent.com/42339509/127777625-143bbb8d-6879-47de-abb6-e9f29978badf.png)

cuco.plug.sp5设备 出现巨多的重复的lock 可能几乎是每一次重启ha服务或者是断电的情况下就会重复生成一个新的实体
辛苦大佬了，请帮看看怎么解决

**Comment by JachinY** [comment]
BUG LOG也许是这些：
Logger: custom_components.xiaomi_miot
Source: custom_components/xiaomi_miot/__init__.py:881
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 24:28:45 (7 occurrences)
Last logged: 24:29:20

Got MiioException while fetching the state for Power Strip(Dinning Room) USB Switch Status: Unable to discover the device 192.168.0.126, mapping: {'switch-7.on': {'siid': 7, 'piid': 1}, 'custome.off_memory': {'siid': 9, 'piid': 1}, 'switch-6.on': {'siid': 6, 'piid': 1}, 'switch-5.on': {'siid': 5, 'piid': 1}, 'switch-4.on': {'siid': 4, 'piid': 1}, 'switch-3.on': {'siid': 3, 'piid': 1}, 'physical_controls_locked': {'siid': 8, 'piid': 1}, 'switch.on': {'siid': 2, 'piid': 1}}
Got MiioException while fetching the state for Power Strip(Dinning Room) switch: Unable to discover the device 192.168.0.126, mapping: {'switch-5.on': {'siid': 5, 'piid': 1}, 'custome.off_memory': {'siid': 9, 'piid': 1}, 'switch-6.on': {'siid': 6, 'piid': 1}, 'switch-4.on': {'siid': 4, 'piid': 1}, 'switch-3.on': {'siid': 3, 'piid': 1}, 'physical_controls_locked': {'siid': 8, 'piid': 1}, 'switch-7.on': {'siid': 7, 'piid': 1}, 'switch.on': {'siid': 2, 'piid': 1}}
Got MiioException while fetching the state for Power Strip(Dinning Room) switch: Unable to discover the device 192.168.0.126, mapping: {'switch-4.on': {'siid': 4, 'piid': 1}, 'custome.off_memory': {'siid': 9, 'piid': 1}, 'switch-6.on': {'siid': 6, 'piid': 1}, 'switch-5.on': {'siid': 5, 'piid': 1}, 'switch-3.on': {'siid': 3, 'piid': 1}, 'physical_controls_locked': {'siid': 8, 'piid': 1}, 'switch-7.on': {'siid': 7, 'piid': 1}, 'switch.on': {'siid': 2, 'piid': 1}}
Got MiioException while fetching the state for Power Strip(Dinning Room) switch: Unable to discover the device 192.168.0.126, mapping: {'switch-3.on': {'siid': 3, 'piid': 1}, 'custome.off_memory': {'siid': 9, 'piid': 1}, 'switch-6.on': {'siid': 6, 'piid': 1}, 'switch-5.on': {'siid': 5, 'piid': 1}, 'switch-4.on': {'siid': 4, 'piid': 1}, 'physical_controls_locked': {'siid': 8, 'piid': 1}, 'switch-7.on': {'siid': 7, 'piid': 1}, 'switch.on': {'siid': 2, 'piid': 1}}
Got MiioException while fetching the state for Power Strip(Dinning Room) switch: Unable to discover the device 192.168.0.126, mapping: {'switch-6.on': {'siid': 6, 'piid': 1}, 'custome.off_memory': {'siid': 9, 'piid': 1}, 'switch-5.on': {'siid': 5, 'piid': 1}, 'switch-4.on': {'siid': 4, 'piid': 1}, 'switch-3.on': {'siid': 3, 'piid': 1}, 'physical_controls_locked': {'siid': 8, 'piid': 1}, 'switch-7.on': {'siid': 7, 'piid': 1}, 'switch.on': {'siid': 2, 'piid': 1}}

**Comment by L1cardo** [comment]
我也是这个设备 `cuco.plug.cp1m`， 希望可以加入电量统计和当前功率显示

**Comment by al-one** [comment]
> [cuco.plug.cp1m](https://home.mi.com/baike/index.html#/detail?model=cuco.plug.cp1m) 希望可以加入电量统计和当前功率显示

已支持电量、功能等传感器实体 (https://github.com/al-one/hass-xiaomi-miot/commit/4adeb63f910f7ba3fc4e0effd2daf34028b281e5)

> [cuco.plug.sp5](https://home.mi.com/baike/index.html#/detail?model=cuco.plug.sp5) 设备 出现巨多的重复的lock

已修复，请更新至master后重试 (https://github.com/al-one/hass-xiaomi-miot/commit/506001f74cd5ce13c6f1e10cb5d5e2ab1a2b00f2)

> Unable to discover the device 192.168.0.xxx

请检查设备与HA之间的网络

**Comment by L1cardo** [comment]
请问开发者，类似这种的
```python
'cuco.plug.cp1m': {
	'sensor_properties': 'power_consumption,voltage,electric_current',
},
```
是在哪里查看的？

**Comment by al-one** [comment]
- 在 https://miot-spec.org/miot-spec-v2/instances?status=all 找到设备型号（如：`cuco.plug.cp1m`）对应的`urn`
- 打开[https://miot-spec.org/miot-spec-v2/instance?type=`urn`](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:outlet:0000A002:cuco-cp1m:1)
- 找到形如`urn:miot-spec-v2:property:属性名称:0000002F:cuco-cp1m:1`的值，从中获取属性名称
- 本插件需要把属性名称中的减号`-`替换成下划线`_`

**Comment by L1cardo** [comment]
https://github.com/al-one/hass-xiaomi-miot/commit/4adeb63f910f7ba3fc4e0effd2daf34028b281e5 这里面好像少了几个属性，而且单位和数据的位数也不是很正确，我想的能不能自己改一改😂

**Comment by al-one** [comment]
自己改的话，可以通过[自定义属性](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)添加。
