### ISSUE TITLE
Error: pm10 is using 'None' unit of measurement - expected 'µg/m³'

### ISSUE THREAD

**Issue by TheNightmanX** [al-one/hass-xiaomi-miot#1542]
Got the following error:

Entity sensor.zhimi_vb4_561d_pm10_density (<class 'custom_components.xiaomi_miot.sensor.MiotSensorSubEntity'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('pm10') it is using; expected one of ['µg/m³']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

**Comment by TheNightmanX** [comment]
Still getting this error.

**Comment by al-one** [comment]
Try master branch.

**Comment by TheNightmanX** [comment]
Fix is working. Thank you for your work.
