### ISSUE TITLE
Usage of deprecated constants

### ISSUE THREAD

**Issue by TheNightmanX** [al-one/hass-xiaomi-miot#1543]
Got the following error:

DATA_RATE_KIBIBYTES_PER_SECOND was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfDataRate.KIBIBYTES_PER_SECOND instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

DATA_RATE_MEBIBYTES_PER_SECOND was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfDataRate.MEBIBYTES_PER_SECOND instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

DATA_RATE_GIBIBYTES_PER_SECOND was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfDataRate.GIBIBYTES_PER_SECOND instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

ENTITY_CATEGORY_CONFIG was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use EntityCategory.CONFIG instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

ENTITY_CATEGORY_DIAGNOSTIC was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use EntityCategory.DIAGNOSTIC instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

**Comment by redstar2k1** [comment]
Same here

Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 20:04:36 (3128 occurrences)
Last logged: 20:04:59

DATA_RATE_KIBIBYTES_PER_SECOND was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfDataRate.KIBIBYTES_PER_SECOND instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
DATA_RATE_MEBIBYTES_PER_SECOND was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfDataRate.MEBIBYTES_PER_SECOND instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
DATA_RATE_GIBIBYTES_PER_SECOND was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfDataRate.GIBIBYTES_PER_SECOND instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
ENTITY_CATEGORY_CONFIG was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use EntityCategory.CONFIG instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
ENTITY_CATEGORY_DIAGNOSTIC was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use EntityCategory.DIAGNOSTIC instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

**Comment by redstar2k1** [comment]
Logger: homeassistant.components.device_tracker.const
Source: helpers/deprecation.py:205
Integration: Device tracker ([documentation](https://www.home-assistant.io/integrations/device_tracker), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+device_tracker%22))
First occurred: 20:04:55 (1 occurrences)
Last logged: 20:04:55

SOURCE_TYPE_GPS was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.GPS instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

**Comment by radek-kafka** [comment]
I have the same. Is there some way to solve it w/o need to import all constants and fill logs by these messages?

**Comment by radek-kafka** [comment]
Many thanks.. Now ok ..
