### ISSUE TITLE
Use of more deprecated constants

### ISSUE THREAD

**Issue by TheNightmanX** [al-one/hass-xiaomi-miot#1544]
Got the following error:

SUPPORT_ALARM_ARM_AWAY was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_AWAY instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

SUPPORT_ALARM_ARM_NIGHT was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_NIGHT instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

SUPPORT_ALARM_TRIGGER was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.TRIGGER instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

SUPPORT_ALARM_ARM_CUSTOM_BYPASS was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_CUSTOM_BYPASS instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

SUPPORT_ALARM_ARM_VACATION was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_VACATION instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

**Comment by redstar2k1** [comment]
Logger: homeassistant.components.alarm_control_panel.const
Source: helpers/deprecation.py:205
Integration: Alarm control panel ([documentation](https://www.home-assistant.io/integrations/alarm_control_panel), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+alarm_control_panel%22))
First occurred: 20:04:57 (8 occurrences)
Last logged: 20:04:57

SUPPORT_ALARM_ARM_AWAY was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_AWAY instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
SUPPORT_ALARM_ARM_NIGHT was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_NIGHT instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
SUPPORT_ALARM_TRIGGER was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.TRIGGER instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
SUPPORT_ALARM_ARM_CUSTOM_BYPASS was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_CUSTOM_BYPASS instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
SUPPORT_ALARM_ARM_VACATION was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_VACATION instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
