### ISSUE TITLE
Use of Deprecated Constants part 3

### ISSUE THREAD

**Issue by TheNightmanX** [al-one/hass-xiaomi-miot#1545]
DEVICE_CLASS_HUMIDIFIER was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use HumidifierDeviceClass.HUMIDIFIER instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

DEVICE_CLASS_DEHUMIDIFIER was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use HumidifierDeviceClass.DEHUMIDIFIER instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

SUPPORT_MODES was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use HumidifierEntityFeature.MODES instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

**Comment by redstar2k1** [comment]
Logger: homeassistant.components.humidifier.const
Source: helpers/deprecation.py:205
Integration: Humidifier ([documentation](https://www.home-assistant.io/integrations/humidifier), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+humidifier%22))
First occurred: 20:04:53 (3 occurrences)
Last logged: 20:04:53

DEVICE_CLASS_HUMIDIFIER was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use HumidifierDeviceClass.HUMIDIFIER instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
DEVICE_CLASS_DEHUMIDIFIER was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use HumidifierDeviceClass.DEHUMIDIFIER instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
SUPPORT_MODES was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use HumidifierEntityFeature.MODES instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
