### ISSUE TITLE
米家智能水暖毯长时间离线不可用

### ISSUE THREAD

**Issue by Young1223** [al-one/hass-xiaomi-miot#1547]
### Device model / 设备型号

xiaomi.blanket.mj2

### Component version / 插件版本

0.7.15

### HA core version / HA版本

2024.2.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

米家智能水暖毯长时间离线不可用，网络是正常的，米家app里可以正常控制，其他所有接入的设备也是正常的，就单单是这个离线，之前也有短暂的离线，但是能够自动恢复，现在基本是不可用的状态，已经尝试重新绑定过设备，没有解决

### Entity attributes / 实体属性

无具体实体，设备整个不可用

### Home Assistant Logs / 系统日志

此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.switch
Source: custom_components/xiaomi_miot/__init__.py:1418
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 15:08:21 (54 occurrences)
Last logged: 15:34:41

水暖毯(xiaomi.blanket.mj2): Got MiioException while fetching the state: No response from the device, mapping: {'electric_blanket.on': {'siid': 2, 'piid': 1}, 'electric_blanket.fault': {'siid': 2, 'piid': 2}, 'electric_blanket.mode': {'siid': 2, 'piid': 3}, 'target_temperature-2-4': {'siid': 2, 'piid': 4}, 'electric_blanket.temperature': {'siid': 2, 'piid': 5}, 'electric_blanket.water_level': {'siid': 2, 'piid': 6}, 'custom.antifreezing_switch': {'siid': 7, 'piid': 1}, 'custom.anti_scald_switch': {'siid': 7, 'piid': 2}, 'custom.sleep_setting': {'siid': 7, 'piid': 3}, 'countdown.countdown_time': {'siid': 6, 'piid': 1}, 'indicator_light.on': {'siid': 5, 'piid': 1}, 'indicator_light-5.switch_status': {'siid': 5, 'piid': 2}, 'alarm': {'siid': 4, 'piid': 1}, 'physical_controls_locked': {'siid': 3, 'piid': 1}}, max_properties: 7/14

**Comment by al-one** [comment]
尝试master分支
