### ISSUE TITLE
升级HA后，插件显示未加载，重新添加集成显示message:"Invalid handler specified"

### ISSUE THREAD

**Issue by hbsgithub** [al-one/hass-xiaomi-miot#1550]
Device model / 设备型号
树莓派4

Component version / 插件版本
0.7.15

HA core version / HA版本
2024.2.4

Integrated mode / 集成方式
Automatic (自动模式)

The problem / 问题详情
一开始开机显示“未加载”
重启、升级均无用
尝试删除集成重新配置
添加集成时显示“message":"Invalid handler specified” 无法添加了

Entity attributes / 实体属性
无实体

Home Assistant Logs / 系统日志

**Comment by kiwilam2023** [comment]
same question

**Comment by Stardust3939** [comment]
Docker版，同样问题，卸载home assistant重新安装后好了。

**Comment by hbsgithub** [comment]
> Docker版，同样问题，卸载home assistant重新安装后好了。

请问你重装后的ha版本是多少呢？

**Comment by idiot110** [comment]
我也是升级2.4之后就这样了，不知道你的问题解决没，看来只能回退版本了

**Comment by hbsgithub** [comment]
> 我也是升级2.4之后就这样了，不知道你的问题解决没，看来只能回退版本了

没有解决，目前是回退了旧版本，可能2.4版跟该插件有兼容性问题

**Comment by Stardust3939** [comment]
> > Docker版，同样问题，卸载home assistant重新安装后好了。
> 
> 
> 
> 请问你重装后的ha版本是多少呢？

和你一样，是2024.2.4，似乎卸载后要手动删除它的配置文件。但是重装真的是没办法的办法了，我重新配置花了将近一天时间才搞定。

**Comment by kiwilam2023** [comment]
暂时未解决，没有卸载重装home assistant觉得好麻烦，配置了很多东西，不知道重装小米的集成能不能解决

**Comment by DavidAlcatraz** [comment]
**同求修复升级HA到2月版本后，无法连接米家集成，报错message":"Invalid handler specified的问题~**

**Comment by cctv180** [comment]
> **同求修复升级HA到2月版本后，无法连接米家集成，报错消息":"指定的处理程序无效的问题~**

我的也出现这个问题，今天更新Docker的HA到最新版正常了。

**Comment by cclucky1** [comment]
same question

**Comment by DavidAlcatraz** [comment]
> **同求修复升级HA到2月版本后，无法连接米家集成，报错message":"Invalid handler specified的问题~**

升级到了3月新版本的HA后，上述问题已解决。

**Comment by viviwon** [comment]
我也是修改成latest后就好了，指定的版本刚好也不行
