### ISSUE TITLE
Xiaomi Miot Auto: Set miot property服务调用报错

### ISSUE THREAD

**Issue by xbdian** [al-one/hass-xiaomi-miot#1551]
### Device model / 设备型号

zimi.waterheater.h01

### Component version / 插件版本

0.7.15

### HA core version / HA版本

2024.2.4

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

Xiaomi Miot Auto: Set miot property服务调用报错。

### Entity attributes / 实体属性

无实体

### Home Assistant Logs / 系统日志

日志详细信息( ERROR )
Logger: homeassistant.components.websocket_api.messages
Source: components/websocket_api/messages.py:248
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 16:12:20 (7 occurrences)
Last logged: 21:15:01

Unable to serialize to JSON. Bad data found at $.result.response.result={'did': '572558832', 'siid': 2, 'piid': 8, 'code': 0}(<class 'custom_components.xiaomi_miot.core.miot_spec.MiotResult'>
Unable to serialize to JSON. Bad data found at $.result.response.result={'did': '572558832', 'siid': 2, 'piid': 2, 'code': 0}(<class 'custom_components.xiaomi_miot.core.miot_spec.MiotResult'>

**Comment by idiot110** [comment]
请问你的问题解决了吗

**Comment by xbdian** [comment]
> 请问您的问题解决了吗

没有，node-red配置的很多流暂时无法使用，你也碰到这个问题了吗？

**Comment by idiot110** [comment]
是的更新2.4之后这个集成就用不了了，目前推送了2.5我先更新看能不能好，不能好只能回退了，

**Comment by xbdian** [comment]
> 是的更新2.4之后这个集成就用不了了，目前推送了2.5我先更新看能不能好，不能好只能回退了，

**Comment by xbdian** [comment]
> > 是的更新2.4之后这个集成就用不了了，目前推送了2.5我先更新看能不能好，不能好只能回退了，

我已经更新了，今天仔细看了下，目前我主要使用了xiaomi_miot.call_action、xiaomi_miot.set_miot_property这2个服务，其中xiaomi_miot.call_action是正常的，就是xiaomi_miot.set_miot_property报错。

**Comment by al-one** [comment]
Fixed in master branch.

**Comment by xbdian** [comment]
> Fixed in master branch.

非常感谢，刚刚测试了，可以使用了。👍

**Comment by xbdian** [comment]
> 请问你的问题解决了吗

作者已经进行修复了，目前我这边用最新版测试没有报错了。
