### ISSUE TITLE
Frequent DNS polling API server

### ISSUE THREAD

**Issue by leroyloren** [al-one/hass-xiaomi-miot#1560]
Hello,

I use this integration in Local mode, is it ok that the integration polls the Xiaomi API server every minute?

![obrazek](https://github.com/al-one/hass-xiaomi-miot/assets/57643470/1678a10e-b42b-4663-a8fb-f8c8d2af23e7)
![obrazek](https://github.com/al-one/hass-xiaomi-miot/assets/57643470/5e79c638-afe0-4a13-aaa2-d188cce95e05)

**Comment by al-one** [comment]
![image](https://github.com/al-one/hass-xiaomi-miot/assets/4549099/c5b6e9ea-1f34-48f6-b698-42be47b6f15d)
