### ISSUE TITLE
Invalid config

### ISSUE THREAD

**Issue by junkcook** [al-one/hass-xiaomi-miot#157]
日志提示 Invalid config。 集成中通过账号密码方式，但是无法获取到实体，也找不到
![微信截图_20210805163154](https://user-images.githubusercontent.com/29994530/128318983-6e3ef543-464c-42a4-8947-29001a717af9.png)

有集成，无实体。 就是添加后，界面上看不到找不到实体

![微信截图_20210805163303](https://user-images.githubusercontent.com/29994530/128319060-f15ef9a3-9014-4bdd-9c93-fb52c5fe7a9c.png)

**Comment by al-one** [comment]
请升级HA至v2021.4版本以上，或更新本插件至master分支版本。

**Comment by junkcook** [comment]
感谢，升级后已正常。

想请问下 Xiaomi MIoT  和 Xiaomi Miot Auto 区别？

**Comment by al-one** [comment]
> 想请问下 Xiaomi MIoT  和 Xiaomi Miot Auto 区别？

- 两者集成设备的方式及流程不同
- 两者对设备支持的方式和程度不同
- https://github.com/rytilahti/python-miio/pull/1095#issuecomment-891436077
