### ISSUE TITLE
更新后小米净水器yunmi.waterpuri.lx11缺少tds-out 仅有tds-in

### ISSUE THREAD

**Issue by ptbsare** [al-one/hass-xiaomi-miot#1574]
### Device model / 设备型号

yunmi.waterpuri.lx11

### Component version / 插件版本

0.7.16

### HA core version / HA版本

2024.3.0

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

更新后小米净水器yunmi.waterpuri.lx11缺少tds-out 仅有tds-in
旧版正常。
新版净水后tds传感器消失，仅有进水tds传感器。少了一个传感器。

### Entity attributes / 实体属性

state_class: measurement
entity_class: MiotSensorSubEntity
parent_entity_id: sensor.yunmi_lx11_bb89_water_purifier
service_description: Total Dissolved Solids Sensor
property_description: Total Dissolved Solids for Input Water
updated_time: "2024-03-12T20:38:05.426732+08:00"
tds_sensor.tds_in: 80
unit_of_measurement: ppm
icon: mdi:water
friendly_name: 厨房净水器 Total Dissolved Solids Sensor for Input Water
supported_features: 0

**Comment by al-one** [comment]
https://github.com/al-one/hass-xiaomi-miot/blob/b6a13c75675e9b8458a244f82c2a3a41cf57921a/custom_components/xiaomi_miot/core/device_customizes.py#L1815-L1817

It has been fixed through custom option.

**Comment by ptbsare** [comment]
Seems still not fixed.
