### ISSUE TITLE
更新后扫地机器人viomi.vacuum.v7缺失两个entity sensor.viomi_v7_4c26_miio_s_area sensor.viomi_v7_4c26_miio_s_time

### ISSUE THREAD

**Issue by ptbsare** [al-one/hass-xiaomi-miot#1579]
### Device model / 设备型号

viomi.vacuum.v7

### Component version / 插件版本

master

### HA core version / HA版本

2024.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

更新后扫地机器人viomi.vacuum.v7缺失两个entity sensor.viomi_v7_4c26_miio_s_area sensor.viomi_v7_4c26_miio_s_time

回退至2024.2.5 正常。

### Entity attributes / 实体属性

无

**Comment by al-one** [comment]
- #1562
