### ISSUE TITLE
MJSXJ02HL (isa.camera.hlc6) cannot view

### ISSUE THREAD

**Issue by deneraraujo** [al-one/hass-xiaomi-miot#158]
I'm trying to integrate my MJSXJ02HL camera, but I cannot get the stream.
My Mi Home app says the livestream is being watched. But nothing is shown on HA.
There is no errors on log, and the camera status is "on".
I already updated to the last version on branch master (14 hours ago).

![](https://drive.google.com/uc?export=view&id=1soerExBTdYhS8G5pI0V16nFjCPYkMfhu)
![](https://drive.google.com/uc?export=view&id=1dqKxaKVls9zzXIwlLLkE1k-JRZTpKLfU)
![](https://drive.google.com/uc?export=view&id=1wCq7V9Xz3W5lq9VrCN6xMviA6I11LdFB)

**Comment by KlyukinND** [comment]
Same issue. Cannot get this camera to work. Tried from Home Assistant Core and OS.

**Comment by al-one** [comment]
Show me the [state attributes ](https://my.home-assistant.io/redirect/developer_states) of camera entity.

**Comment by deneraraujo** [comment]
> 
> 
> Show me the [state attributes ](https://my.home-assistant.io/redirect/developer_states) of camera entity.

```
access_token: bd84de64534f85f60c6e4ab6d297255e7c89d9facf65852e23f59066db55ef8e
brand: isa
friendly_name: Câmera de Segurança Residencial 1080p Mi (Suporte Magnético) Camera Control
entity_picture: /api/camera_proxy/camera.camera_de_seguranca_residencial_1080p_mi_suporte_magnetico_camera_control?token=bd84de64534f85f60c6e4ab6d297255e7c89d9facf65852e23f59066db55ef8e
supported_features: 3
miot_cloud: false
```
![](https://drive.google.com/uc?export=view&id=1hnv_Lzpl2qN4doQ1WyLxspKRMwt7iT00)

**Comment by al-one** [comment]
Get state attributes after open camera dialog.

**Comment by deneraraujo** [comment]
> 
> 
> Show me the [state attributes ](https://my.home-assistant.io/redirect/developer_states) of camera entity.



```
access_token: bd84de64534f85f60c6e4ab6d297255e7c89d9facf65852e23f59066db55ef8e
brand: isa
friendly_name: Câmera de Segurança Residencial 1080p Mi (Suporte Magnético) Camera Control
entity_picture: /api/camera_proxy/camera.camera_de_seguranca_residencial_1080p_mi_suporte_magnetico_camera_control?token=bd84de64534f85f60c6e4ab6d297255e7c89d9facf65852e23f59066db55ef8e
supported_features: 3
miot_cloud: false
```

> 
> 
> Get state attributes after open camera dialog.

This dialog?
The attributes still the same
![](https://drive.google.com/uc?export=view&id=1lHYzoUqNGiVrOs8JfFoIpGC20lwWGDwS)

**Comment by al-one** [comment]
```yaml
miot_cloud: true
```

**Comment by deneraraujo** [comment]
> 
> 
> ```yaml
> miot_cloud: true
> ```

Now I set the miot_cloud to true.
The attributes:
```
access_token: 347e0debdafa3f49418cd87e615faa91847015cc5d5be5160ce4fe697f2c15d0
brand: isa
friendly_name: Câmera de Segurança Residencial 1080p Mi (Suporte Magnético) Camera Control
entity_picture: /api/camera_proxy/camera.camera_de_seguranca_residencial_1080p_mi_suporte_magnetico_camera_control?token=347e0debdafa3f49418cd87e615faa91847015cc5d5be5160ce4fe697f2c15d0
supported_features: 3
miot_cloud: true
```
Unfortunately still cannot view:
![](https://drive.google.com/uc?export=view&id=1Uqj9WwglUGSTUiGiWRZHirsGEaU-IMmS)

**Comment by deneraraujo** [comment]
After set miot_cloud to true, I'm no longer receiving the "user is watching the livestream" notifications on my phone.

**Comment by deneraraujo** [comment]
When I put the preview URL on a new tab in my browser, I get a error 500 (Internal server error).

**Comment by rojong** [comment]
I have same symptoms for this cam.  I have also an error in the logfile, maybe this helps the diagnosis:


Logboekdetails (FOUT)
 Deze fout is ontstaan door een aangepaste integratie.
Logger: aiohttp.server
Source: custom_components/xiaomi_miot/camera.py:188
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 20:35:11 (13 occurrences)
Last logged: 20:37:33

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 206, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 517, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 534, in handle
    image = await camera.async_camera_image()
  File "/config/custom_components/xiaomi_miot/camera.py", line 245, in async_camera_image
    url = await self.stream_source()
  File "/config/custom_components/xiaomi_miot/camera.py", line 188, in stream_source
    odt = self._act_start_stream.out_results(result.get('out')) or {
AttributeError: 'bool' object has no attribute 'get'

Parts of the states:
brand: isa
model: isa.camera.hlc6
lan_ip: 192.168.178.98
mac_address: E4:AA:EC:2A:7A:BE
firmware_version: 4.0.9_0112
hardware_version: ''
entity_class: MiotCameraEntity
miot_type: urn:miot-spec-v2:device:camera:0000A01C:isa-hlc6:1
camera_control.on: true

**Comment by deneraraujo** [comment]
> 
> 
> Which version of the Xiaomi Miot Auto integration do you have? For me (and for other's) any version after v0.3.8 don't let you see the stream. Even the newest version v0.3.12 has not fixed this issue.

I'm using version 0.3.11 (Aug 6, 2021).

**Comment by al-one** [comment]
See https://github.com/al-one/hass-xiaomi-miot/issues/166

**Comment by masakotsubuku1** [comment]
HA blocks stream access from MIOT after certain time like 6 mins. Seems like Miot updates stream_address and for a security reason, HA blocks it with 403 error. No work around found so far.
