### ISSUE TITLE
米家智能浴霸Pro缺少灯光实体

### ISSUE THREAD

**Issue by qiuyuxuan1999** [al-one/hass-xiaomi-miot#1587]
### Device model / 设备型号

yeelink.bhf_light.v13

### Component version / 插件版本

0.7.17

### HA core version / HA版本

2024.2.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

https://home.miot-spec.com/s/yeelink.bhf_light.v13，这个浴霸的灯实体原来可以用的，没注意从哪个版本开始显示集成“xiaomi_miot”不再提供此实体。
另外针对这个版本的浴霸，miot协议中几个模式的处理可能也有问题，目前是浴霸climate实体里，模式下有“除湿”和“关闭”，预设模式下有“除雾”、“快速除雾”、“急速加热”、“other”和“off”。

### Entity attributes / 实体属性

light.yeelink_v13_e3f6_light

**Comment by Flyu-777** [comment]
我也遇到了，不知道怎么解决

**Comment by al-one** [comment]
提供实体属性

**Comment by Jared-Tang** [comment]
我也提了这个问题，然后就发现这里已经有人提过了，之前我手动把instances.json文件中的"type": "urn:miot-spec-v2:device:vacuum:0000A006:viomi-v13:2"这一句里面的的v13:2改成 v13:1，并删除urn:miot-spec-v2:device:bath-heater:0000A028:yeelink-v13:1.json文件，再重载插件，可以出现灯光实体，也可以控制。

**Comment by qiuyuxuan1999** [comment]
> 提供实体属性

您说的实体属性，是HA中的实体状态属性吗？如下：
restored: true
effect_list:
  - 日光
  - 夜光
supported_color_modes:
  - brightness
  - onoff
icon: hue:ceiling-aurelle
friendly_name: 厕所灯
supported_features: 36

**Comment by al-one** [comment]
所有实体的属性

**Comment by qiuyuxuan1999** [comment]
> 所有实体的属性
 是这个吗？
hvac_modes:
  - "off"
  - dry
min_temp: 25
max_temp: 45
target_temp_step: 1
fan_modes:
  - 低
  - 高
preset_modes:
  - 除雾
  - 快速除雾
  - 极速加热
  - Other
  - "off"
swing_modes:
  - "off"
  - vertical
current_temperature: null
temperature: 30
fan_mode: null
hvac_action: "off"
preset_mode: "off"
swing_mode: "off"
model: yeelink.bhf_light.v13
lan_ip: 192.168.123.206
mac_address: B4:60:ED:C9:E3:F6
entity_class: MiotClimateEntity
home_room: 石门苑 厕所
miot_type: urn:miot-spec-v2:device:bath-heater:0000A028:yeelink-v13:2
ptc_bath_heater.mode: 0
ptc_bath_heater.blow: false
ptc_bath_heater.heating: false
ptc_bath_heater.ventilation: false
ptc_bath_heater.heat_level: 2
ptc_bath_heater.off_delay: false
ptc_bath_heater.off_delay_time: 0
target_temperature-3-8: 30
remote_delay_off_time-3-9.error: "-4003 Property/Action/Event does not exist"
ptc_bath_heater.room_size.error: "-4003 Property/Action/Event does not exist"
alarm.error: "-4004 Other internal errors"
delay-7.delay.error: "-4004 Other internal errors"
delay-7.delay_time.error: "-4004 Other internal errors"
delay-7.delay_remain_time.error: "-4004 Other internal errors"
delay.error: "-4004 Other internal errors"
delay.delay_time.error: "-4004 Other internal errors"
delay.delay_remain_time.error: "-4004 Other internal errors"
fan_control.vertical_swing.error: "-4004 Other internal errors"
fan_control.vertical_angle.error: "-4003 Property/Action/Event does not exist"
fan_control.fan_level.error: "-4004 Other internal errors"
fan_control-5.fan_level.error: "-4004 Other internal errors"
light.on.error: "-4004 Other internal errors"
light.mode.error: "-4004 Other internal errors"
light.default_power_on_state.error: "-4003 Property/Action/Event does not exist"
light.night_light_switch.error: "-4004 Other internal errors"
light.enable_time_period.error: "-4004 Other internal errors"
state_updater: lan
sub_entities:
  - ptc_bath_heater-3.off_delay_time-7
  - 除雾
  - 快速除雾
  - 极速加热
  - Other
  - ptc_bath_heater-3.blow-2
  - ptc_bath_heater-3.heating-3
  - ptc_bath_heater-3.ventilation-4
  - ptc_bath_heater-3.off_delay-6
light.brightness: 100
light.brightness.error: "-4004 Other internal errors"
friendly_name: 浴霸 浴霸
supported_features: 441

**Comment by al-one** [comment]
尝试master分支。

- #1593

**Comment by qiuyuxuan1999** [comment]
> 尝试master分支。
> 
> * [米家智能浴霸V13版本的灯光实体不可用 #1593](https://github.com/al-one/hass-xiaomi-miot/issues/1593)

可以了，十分感谢。
