### ISSUE TITLE
新出的小爱play增强版好像无法正常接入

### ISSUE THREAD

**Issue by jifengmm** [al-one/hass-xiaomi-miot#159]
显示小爱音箱Play增强版 Play Control
状态为未知
![image](https://user-images.githubusercontent.com/35440294/128700359-e347f1eb-8984-4b77-890b-ba9ee3bf5c55.png)

**Comment by jifengmm** [comment]
> 请问该小爱音箱的型号(Model)是多少？
> 云端接入的设备状态由小米miot接口返回，如果接口没有返回正确的状态，插件也无能为力。你可以观察该实体的状态属性（开发者工具 > 状态）以确认是否是小米接口返回的问题。
> 另外接入小爱同学更实用的功能为TTS和语音命令，了解更多：[#100 (comment)](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-885989099)

**Comment by jifengmm** [comment]
@al-one

volume_level: 0.5
is_volume_muted: true
model: xiaomi.wifispeaker.l05c
lan_ip: XXXXXXXXX
mac_address: XXXXXXXXX
firmware_version: 1.0.0
hardware_version: ''
entity_class: MiotMediaPlayerEntity
miot_type: urn:miot-spec-v2:device:speaker:0000A015:xiaomi-l05c:1
attribution: Support TTS through service
play_control.playing_state.error: '-704220043 Property value error'
play_control.play_loop_mode.error: '-704220008 Invalid IID (PID, SID, AID, etc.)'
clock.on.error: '-704220008 Invalid IID (PID, SID, AID, etc.)'
clock.status.error: '-704220008 Invalid IID (PID, SID, AID, etc.)'
clock.fault.error: '-704220008 Invalid IID (PID, SID, AID, etc.)'
clock.ringtone.error: '-704220008 Invalid IID (PID, SID, AID, etc.)'
microphone.mute: false
speaker.volume: 50
speaker.mute: true
state_updater: cloud
friendly_name: 小爱音箱Play增强版 Play Control
supported_features: 20541
device_class: speaker

**Comment by al-one** [comment]
```yaml
play_control.playing_state.error: '-704220043 Property value error'
```
小米云端接口报错。

**Comment by jifengmm** [comment]
云端接口报错怎么解决？是我设置的问题还是小米官方服务的问题？

**Comment by al-one** [comment]
小米云端接口的问题。
