### ISSUE TITLE
Xiaomi Air Purifier 3C

### ISSUE THREAD

**Issue by asiersan** [al-one/hass-xiaomi-miot#16]
Can you add support for zhimi.airpurifier.mb4 ??? Si detected in lan mode, but not working neither sensores or switch and no al entities displayed

**Comment by al-one** [comment]
Need debug logs.

**Comment by al-one** [comment]
Please upgrade to [v0.2.5](https://github.com/al-one/hass-xiaomi-miot/releases/latest).  It supports the air purifier better.
