### ISSUE TITLE
生成了重复的实体

### ISSUE THREAD

**Issue by ptbsare** [al-one/hass-xiaomi-miot#1608]
### Device model / 设备型号

hyd.airer.lyjpro

### Component version / 插件版本

master

### HA core version / HA版本

2024.3.3

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

master 版本的集成在新添加设备会生成重复的实体，其中一个在miot auto集成下，另一个会在基本传感器/开关集成下。删除集成第一个实体会删除，第二个实体为无unique id状态无法删除。
不止一个设备出现这种情况。
![Screen Shot 2024-03-30 at 20 28 33](https://github.com/al-one/hass-xiaomi-miot/assets/3147576/2308faed-d6f6-4278-b5ab-c26bb5d59444)
![Screen Shot 2024-03-30 at 20 28 56](https://github.com/al-one/hass-xiaomi-miot/assets/3147576/fbedc90c-5f98-4119-bd27-4064d825adb0)

### Entity attributes / 实体属性

无。

**Comment by ptbsare** [comment]
![Screen Shot 2024-03-30 at 20 34 00](https://github.com/al-one/hass-xiaomi-miot/assets/3147576/6e631fee-654f-4b1c-a00d-299478840904)
![Screen Shot 2024-03-30 at 20 34 16](https://github.com/al-one/hass-xiaomi-miot/assets/3147576/87789163-4dc5-4bdc-bb96-a52e92fa8f5e)

**Comment by lelemka0** [comment]
遇到相同的问题
Component version: v0.7.17
master HA core version: 2024.4.1
![image](https://github.com/al-one/hass-xiaomi-miot/assets/20322043/3b7ac3df-2ef9-4737-b08b-72b0a91c80cd)

**Comment by ptbsare** [comment]
Confirm Fixed in 1.0.x HA 2025.1 beta
