### ISSUE TITLE
燈缺少brightness屬性

### ISSUE THREAD

**Issue by aaroncat007** [al-one/hass-xiaomi-miot#1612]
### Device model / 设备型号

yeelink.light.mono6

### Component version / 插件版本

v0.7.17

### HA core version / HA版本

2024.3.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

燈的屬性brightness: null 導致卡片無法正確顯示當前的亮度
![image](https://github.com/al-one/hass-xiaomi-miot/assets/4236169/3a1b90ba-34b8-4a41-9303-0521f548d6a7)
![image](https://github.com/al-one/hass-xiaomi-miot/assets/4236169/d057f06a-e8bf-4c1d-9f4a-ee37eba19a66)

### Entity attributes / 实体属性

<html>
<body>

supported_color_modes: brightness 
color_mode: unknown brightness: null model: yeelink.light.mono6 lan_ip: 192.168.0.212 mac_address: 64:90:C1:B2:05:0A entity_class: MiotLightEntity home_room: 默认家庭 客廳 miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-mono6:1 light.on: true state_updater: lan sub_entities: light-2.brightness-3 light.brightness: 65 friendly_name: 門口 supported_features: 32
--

</body>
</html>

**Comment by al-one** [comment]
Fixed in v0.7.18.
