### ISSUE TITLE
kejia.airer.mznpro is not added correctly via local integration

### ISSUE THREAD

**Issue by gnep88** [al-one/hass-xiaomi-miot#162]
Type: kejia.airer.mznpro (米智能 电动晾衣机PRO)

See urn:miot-spec-v2:device:airer:0000A00D:kejia-mznpro:1
[http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:airer:0000A00D:kejia-mznpro:1](http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:airer:0000A00D:kejia-mznpro:1)

It should have following functions:
Power (ON/OFF) <== missing currently (issue)
UV light 紫外线灯 (ON/OFF) <== missing currently (issue)
Light 照明 (ON/OFF)
Dryer 烘干 (ON/OFF)
Dryer 风干 (ON/OFF)
Up/Down/Pause

**Comment by al-one** [comment]
Please try latest commit: https://github.com/al-one/hass-xiaomi-miot/commit/fd31596211abf8ae4d2285b6094e49dcd4c39799 of branch [master](https://github.com/al-one/hass-xiaomi-miot/tree/master).

**Comment by gnep88** [comment]
Thank you. It is fixed.
