### ISSUE TITLE
MiotClimateEntity implements `is_aux_heat` which is deprecated and will be unsupported from 2024.10

### ISSUE THREAD

**Issue by slydiman** [al-one/hass-xiaomi-miot#1620]
Home Assistant 2024.4.2 warning message:

xiaomi_miot::MiotClimateEntity implements the `is_aux_heat` property or uses the auxiliary heater methods in a subclass of ClimateEntity which is deprecated and will be unsupported from Home Assistant 2024.10.

**Comment by al-one** [comment]
Fixed in v0.7.18.
