### ISSUE TITLE
此项在版本 2024.10.0 中无法工作。请在升级之前解决。

### ISSUE THREAD

**Issue by Lengran1992** [al-one/hass-xiaomi-miot#1623]
The custom integration xiaomi_miot implements the is_aux_heat property or uses the auxiliary heater methods in a subclass of ClimateEntity.

Please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues.

Once an updated version of xiaomi_miot is available, install it and restart Home Assistant to fix this issue.

**Comment by DUWENINK** [comment]
i meet the same question

**Comment by dukewang2002** [comment]
升级HA CORE 2024.4.3版本时也遇到了这个问题，麻烦大佬有空看看是否要升级一下。

**Comment by Leonlouwu** [comment]
我也遇到了

**Comment by al-one** [comment]
Fixed in v0.7.18.

- #1620
