### ISSUE TITLE
小米电视如何获取信号源状态

### ISSUE THREAD

**Issue by xiw321** [al-one/hass-xiaomi-miot#1627]
想根据当前信号源设置一些自动化，但是play control只能获取关闭和空闲两个状态

**Comment by al-one** [comment]
![xiaomi tv miot](https://github.com/al-one/hass-xiaomi-miot/assets/4549099/4c5a4a95-97eb-4490-bb06-7de260406ff4)

**Comment by xiw321** [comment]
已解决：template里面自定义一个sensors把source提取出来就可以了
