### ISSUE TITLE
TDS OUT entity is GONE for yunmi.waterpuri.lx7 

### ISSUE THREAD

**Issue by dinde** [al-one/hass-xiaomi-miot#1634]
### Device model / 设备型号

yunmi.waterpuri.lx7 

### Component version / 插件版本

0.7.17

### HA core version / HA版本

2024.4.3

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

Hello,

For some reasons since march 12th, no more entity for TDS OUT
Also Light mode never worked.
All others are working. You initialy fixed it on #890 

Thanks !

### Entity attributes / 实体属性

state_class: measurement
model: yunmi.waterpuri.lx7
lan_ip: 192.168.x.y
mac_address: [REMOVED]
entity_class: MiotSensorEntity
miot_type: urn:miot-spec-v2:device:water-purifier:0000A013:yunmi-lx7:1
state_property: water_purifier.temperature
run_status: 0
f1_totalflow: 7200
f1_totaltime: 8640
f2_totalflow: 7200
f2_totaltime: 17280
water_purifier.temperature: 19
water_purifier.rinse: 0
water_purifier.light_mode: false
water_purifier.tds_warn_thd: 60
water_purifier.filter_remaining: 25
filter_c2_remaining-2-112: 12.5
filter-5.filter_used_time: 15112
filter-5.filter_used_flow: 640
filter.filter_used_time: 6484
filter.filter_used_flow: 200
tds_sensor.tds_in: 130
tds_sensor.tds_out: 121
state_updater: lan
sub_entities: water_purifier-2.rinse-101, water_purifier-2.filter_remaining-111, water_purifier-2.filter_remaining-112, water_purifier-2.light_mode-102, water_purifier-2.tds_warn_thd-103, filter-4.filter_used_time-1, filter-4.filter_used_flow-2, filter-5.filter_used_time-1, filter-5.filter_used_flow-2, tds_sensor-3.tds_in-1
unit_of_measurement: °C
device_class: temperature
friendly_name: Water Bar Water Purifier Temperature
supported_features: 0

### Home Assistant Logs / 系统日志

EMPTY

**Comment by al-one** [comment]
Upgrade to master branch.

**Comment by dinde** [comment]
Tested master and it's fixed.
Thanks !
