### ISSUE TITLE
Qingping Air Monitor Lite does not work after updating

### ISSUE THREAD

**Issue by MrSnakeSPb** [al-one/hass-xiaomi-miot#164]
Good afternoon, please help!
It stopped working for me and my father with the same configuration Qingping Air Monitor Lite.
I linked again through MiHome, but it doesn't help, maybe the writing syntax has changed?
  sensor:
      - platform: xiaomi_miot_raw
        name: qingping_air_monitor
        host: 192.168.2.9
        token: *************************
        mapping:
          temperature:
            siid: 3
            piid: 7
          humidity:
            siid: 3
            piid: 1
          co2:
            siid: 3
            piid: 8
          pm_2_5:
            siid: 3
            piid: 4
          pm_10:
            siid: 3
            piid: 5
          battery:
            siid: 4
            piid: 1
          charging:
            siid: 4
            piid: 2
          voltage:
            siid: 4
            piid: 3
        params:
        sensor_property: co2
        sensor_unit: 'ppm'
        scan_interval: 60

The log writes an error:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/xiaomi_miot_raw/sensor.py", line 247, in async_setup_entry
    await async_setup_platform(hass, config, async_add_entities)
  File "/config/custom_components/xiaomi_miot_raw/sensor.py", line 120, in async_setup_platform
    if mapping.get(t):
AttributeError: 'str' object has no attribute 'get'

**Comment by al-one** [comment]
`xiaomi_miot_raw` is not this component, please download and install this component from [releases](https://github.com/al-one/hass-xiaomi-miot/releases) page and try again.

**Comment by MrSnakeSPb** [comment]
Configured for your integration, everything worked through the GUI.
Thank you very much.
