### ISSUE TITLE
xiaomi_miot 自定义集成使用了已弃用的气候辅助加热器

### ISSUE THREAD

**Issue by Leonlouwu** [al-one/hass-xiaomi-miot#1641]
### Device model / 设备型号

is_aux_heat

### Component version / 插件版本

0.7.17

### HA core version / HA版本

2024.4.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

此项在版本 2024.10.0 中无法工作。请在升级之前解决。
自定义集成 xiaomi_miot 实现 is_aux_heat 属性或在 ClimateEntity 的子类中使用辅助加热器方法。
请在 https://github.com/al-one/hass-xiaomi-miot/issues 创建缺陷报告。
一旦有 xiaomi_miot 的更新版本可用，请安装它并重新启动 Home Assistant 以解决此问题。

警告 - 2024/4/16

### Entity attributes / 实体属性

无实体

**Comment by al-one** [comment]
Fixed in v0.7.18.

- #1620
