### ISSUE TITLE
更新后，米家设备一直显示无法更新状态

### ISSUE THREAD

**Issue by yun59t** [al-one/hass-xiaomi-miot#1647]
### Device model / 设备型号

dooya.curtain.m1

### Component version / 插件版本

	0.7.17

### HA core version / HA版本

core-2024.5.0b1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

7个米家设备，均跳出以下信息，且设备状态与米家无共同步，之前版本无此问题。
调用服务 cover/stop_cover 失败。 Detected that custom integration 'xiaomi_miot' calls async_write_ha_state from a thread at custom_components/xiaomi_miot/__init__.py, line 1924: self.async_write_ha_state(). Please report it to the author of the 'xiaomi_miot' custom integration.

### Entity attributes / 实体属性

current_position: 0
model: dooya.curtain.m1
lan_ip: 192.168.8.165
mac_address: 7C:C2:94:79:1E:C4
entity_class: MiotCoverEntity
exclude_miot_properties: fault
miot_type: urn:miot-spec-v2:device:curtain:0000A00C:dooya-m1:1
curtain.status: 1
curtain.mode: 1
curtain.current_position: 0
curtain.target_position: 0
curtain.motor_reverse: false
state_updater: lan
device_class: curtain
friendly_name: 客厅窗帘 Curtain
supported_features: 15
sub_entities: curtain-2.status-4, curtain-2.mode-5, curtain-2.motor_reverse-8

**Comment by al-one** [comment]
- #1645

**Comment by yun59t** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
