### ISSUE TITLE
想问下 LONINK VRF中央空调控制器（qdhkl.gateway.lonink）设备支持嘛？

### ISSUE THREAD

**Issue by clarkyu2016** [al-one/hass-xiaomi-miot#1649]
### Device model / 设备型号

qdhkl.gateway.lonink

### Component version / 插件版本

2.2.7_0001

### HA core version / HA版本

2022.12.

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

选择本地模式，登陆小米app账号，可以选择控制器，但是无法找到空调vrf控制器，显示没有实体或者设备

### Entity attributes / 实体属性

无实体

**Comment by will-huang9531** [comment]
这个问题确实很奇怪，这个设备在miot-spec里显示miot-local，但是并不能通过直接添加vrf网关来实现本地执行，直接添加vrf网关会什么都不显示，必须要添加作为虚拟设备的具体空调内机才可以，但虚拟设备又并不支持本地执行，请阿龙来帮我们解解惑 @al-one

**Comment by al-one** [comment]
@will-huang9531 目前VRF类的设备下的空调子设备都需要在选择设备时单独勾选，而空调子设备在米家是以虚拟设备的形式存在，及无法与子设备直接通信，需要通过云端与米家服务器通信。
VRF网关支持本地表示其支持本地miot协议，但是目前还没找到通过网关与子设备本地通信的方法。
