### ISSUE TITLE
如果删除设备

### ISSUE THREAD

**Issue by weiyideai520** [al-one/hass-xiaomi-miot#165]
我用账户添加的设备，现在取消了一些设备，但是设备里面还是有，我可以删除实体，但是我想连设备也删除，请问应该怎么做？

**Comment by al-one** [comment]
[v0.3.11](https://github.com/al-one/hass-xiaomi-miot/releases/tag/v0.3.11)开始支持删除通过本插件生成HA设备，请将设备名称修改为”删除“或”delete“即可。

**Comment by weiyideai520** [comment]
学习了，原来这样的，感谢，搞定了

**Comment by gy6221** [comment]
谢谢，建议添加到FAQ
