### ISSUE TITLE
风扇导风轮无法控制

### ISSUE THREAD

**Issue by aihhkc** [al-one/hass-xiaomi-miot#1672]
### Device model / 设备型号

leshi.light.wyfan

### Component version / 插件版本

0.7.18

### HA core version / HA版本

2024.5.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

风扇的导风轮无法在HA中进行控制，摇头选项提示不支持该功能：
调用服务 fan/oscillate 失败。 Entity fan.leshi_wyfan_27ff_fan does not suppo

使用遥控或米家APP可进行导风轮控制，实体属性中fan.motor_reverse: false参数状态也会跟着变化为true

### Entity attributes / 实体属性

preset_modes: 
friendly_name: 主卧风扇灯 Fan
supported_features: 1
percentage_step: 33
model: leshi.light.wyfan
lan_ip: 192.168.2.231
mac_address: B4:60:ED:27:27:FF
entity_class: MiotFanEntity
home_room: 我们的家 主卧
miot_type: urn:miot-spec-v2:device:light:0000A001:leshi-wyfan:1
fan.on: false
fan.fan_level: 1
fan.motor_reverse: false
light.on: false
light.brightness: 100
light.color_temperature: 4700
state_updater: lan
percentage: null

### Home Assistant Logs / 系统日志

日志: homeassistant.components.light
来源: components/light/__init__.py:913
集成: 灯光 ([文档](https://www.home-assistant.io/integrations/light), [问题](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
首次发生: 12:43:39 (4 全部发生)
上次记录: 15:20:10

light.leshi_wyfan_27ff_light (<class 'custom_components.xiaomi_miot.light.MiotLightEntity'>) does not report a color mode, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
light.cuco_v3_a8f6_indicator_light (<class 'custom_components.xiaomi_miot.light.MiotLightSubEntity'>) does not report a color mode, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
light.leshi_wyfa01_e7af_light (<class 'custom_components.xiaomi_miot.light.MiotLightEntity'>) does not report a color mode, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

**Comment by al-one** [comment]
设备厂商未定义相关miot规格。

![image](https://github.com/al-one/hass-xiaomi-miot/assets/4549099/3b9652a8-e3cf-4276-8ccb-5dd66626d8a3)
