### ISSUE TITLE
小爱相关的所有功能都一边报错一边运行，所有小爱相关的自动化都失效

### ISSUE THREAD

**Issue by ElementZh** [al-one/hass-xiaomi-miot#1677]
![xiaoaiIssue](https://github.com/al-one/hass-xiaomi-miot/assets/26291674/51852392-7c0f-4ba2-8c49-ed5c14ac6ba7)

包括但不限于小爱Pro,触屏小爱的调用小爱功能和利用小爱的IR控制设备，手动调用是可行的但会弹出报错如图；

自动化日志：
执行时间：2024年5月19日 07:17:27
错误: Detected that custom integration 'xiaomi_miot' calls async_write_ha_state from a thread at custom_components/xiaomi_miot/__init__.py, line 1924: self.async_write_ha_state(). Please report it to the author of the 'xiaomi_miot' custom integration.
结果：
params:
  domain: script
  service: unknown_9
  service_data: {}
  target: {}
running_script: true
child_id:
  domain: script
  item_id: unknown_9
  run_id: eea93ec26ae49e9505120b99820a5122

**Comment by ElementZh** [comment]
自从haos更新 2024.5版本后就出现这个问题，可以通过回滚到2024.4.*版本解决但该版本不兼容新版本的其他插件（Node_Red等）
系统环境：
![image](https://github.com/al-one/hass-xiaomi-miot/assets/26291674/05bc3eab-ab42-40dd-bab2-7672907f19b6)
使用冬瓜haos

**Comment by 248968499** [comment]
我也是这样 ，有些设备可以开不能关，有些没有影响

**Comment by mildrabbit** [comment]
我也在2024.5.x的版本中遇到同样的问题了。请大佬尽快更新。

**Comment by al-one** [comment]
升级v0.7.18
