### ISSUE TITLE
Smooky智能跳绳接入

### ISSUE THREAD

**Issue by binghun9806** [al-one/hass-xiaomi-miot#1690]
### Device model / 设备型号

无

### HA core version / HA版本

2024.3.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

大佬，能否做一下Smooky跳绳的接入，现在米家中能接入，但是插件中没有显示

### Entity attributes / 实体属性

无实体

**Comment by al-one** [comment]
https://home.miot-spec.com/spec/smooky.jmprope.ts43

无任何有读取权限的属性。
