### ISSUE TITLE
ha core 更新2024.6.1版本后自定义轮询时间失效

### ISSUE THREAD

**Issue by hgaogao** [al-one/hass-xiaomi-miot#1704]
之前的版本自定义这个门窗传感器是生效的，更新后不失效了

**Comment by hgaogao** [comment]
![image](https://github.com/al-one/hass-xiaomi-miot/assets/47255125/540dd5be-9583-46c7-8c92-a8ff9b485c87)

**Comment by bet3ter** [comment]
一样的情况，所有加了这个自定义属性都不生效。
回退到2024.5.5版本就正常。

**Comment by hgaogao** [comment]
你是如何回退的？，是在虚拟机上面装的吗？还是里面ha里面那个辈分

**Comment by bet3ter** [comment]
就更新时候做的那个备份，用那个回退的。

**Comment by xy3777** [comment]
直接修改configuration.yaml可以生效

**Comment by al-one** [comment]
- #1763
