### ISSUE TITLE
绿米空调伴侣执行问题

### ISSUE THREAD

**Issue by Flying-Pika** [al-one/hass-xiaomi-miot#172]
用这款插件 使用云端模式，绿米的空调伴侣，每次打开空调，模式都是自动，跟米家app里面设置的模式完全不一样，请问我要怎么才能修改默认打开空调的模式，并且现在对siri说打开空调 必须要加房间作为定语，比如不能直接说 “siri打开空调”，必须要说“siri 打开xx房间的空调”，请问怎么设置呀

**Comment by al-one** [comment]
> 每次打开空调，模式都是自动

在HA及苹果`家庭`APP中应该都是可以指定模式打开设备开关的，不知道你具体是以什么方式打开开关的。
你还可以[添加自定义属性](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)来生成一个开关实体用于打开空调：
```yaml
climate.your_entity_id:
  switch_properties: on
```

> 必须要说“siri 打开xx房间的空调”

如果是对HomePod说，可以尝试将HomePod和空调伴侣在`家庭`APP设置在同一房间。如果是对iPhone说，可以尝试设置快捷指令。

**Comment by al-one** [comment]
你可以通过[快捷指令](https://support.apple.com/zh-cn/guide/shortcuts/apdf22b0444c/ios)实现。
