### ISSUE TITLE
小米智能猫眼1S 无法正常创建实体

### ISSUE THREAD

**Issue by xiaodong-lx** [al-one/hass-xiaomi-miot#1731]
### Device model / 设备型号

loock.cateye.v06

### Component version / 插件版本

0.7.18

### HA core version / HA版本

core-2024.3.3（docker）

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

可以正常添加设备，但是仅有一个Video Doorbell的Camera实体（并且不可用），没有其他实体（比如Battery等），日志有报错
固件版本：2.1.9_1058.1056

![](https://github.com/al-one/hass-xiaomi-miot/assets/172955787/f0bcf856-a086-4c8d-aeac-303f1b63b2fb)

### Entity attributes / 实体属性

entity_picture: /api/camera_proxy/camera.loock_xxxxxxxx_video_doorbell?token=20580170281xxxxxxxxxd12cbe42d
friendly_name: Mi Smart Video Doorbell with Monitor 1S Video Doorbell 
supported_features: 0

### Home Assistant Logs / 系统日志

日志: custom_components.xiaomi_miot.camera
来源: custom_components/xiaomi_miot/__init__.py:1412
集成: Xiaomi Miot Auto (文档, 问题)
首次发生: 22:36:59 (2 全部发生)
上次记录: 22:37:59

Mi Smart Video Doorbell with Monitor 1S(loock.cateye.v06): Got MiioException while fetching the state: Unable to discover the device 192.168.0.189, mapping: {'video_doorbell.status': {'siid': 2, 'piid': 2}, 'video_doorbell.night_shot': {'siid': 2, 'piid': 3}, 'video_doorbell.wdr_mode': {'siid': 2, 'piid': 5}, 'video_doorbell.eco': {'siid': 2, 'piid': 6}, 'video_doorbell.ringtone': {'siid': 2, 'piid': 7}, 'cateye.auto_ota': {'siid': 5, 'piid': 2}, 'cateye.distortion_correct': {'siid': 5, 'piid': 3}, 'cateye.auto_screen_on': {'siid': 5, 'piid': 4}, 'cateye.light_sensibility': {'siid': 5, 'piid': 5}, 'cateye.device_warn_time': {'siid': 5, 'piid': 7}, 'cateye.motion_latency_time': {'siid': 5, 'piid': 8}, 'cateye.screen_status': {'siid': 5, 'piid': 10}, 'cateye.yd_model': {'siid': 5, 'piid': 18}, 'cateye.sn': {'siid': 5, 'piid': 19}, 'cateye.record_sd': {'siid': 5, 'piid': 21}, 'cateye.stay_duration': {'siid': 5, 'piid': 22}, 'cateye.tamper_alarm_switch': {'siid': 5, 'piid': 23}, 'cateye.visitpush': {'siid': 5, 'piid': 25}, 'cateye.pushpattern': {'siid': 5, 'piid': 26}, 'cateye.visitpushtime': {'siid': 5, 'piid': 27}, 'cateye.motionpush': {'siid': 5, 'piid': 28}, 'cateye.pushtype': {'siid': 5, 'piid': 29}, 'cateye.record_video_length': {'siid': 5, 'piid': 30}, 'cateye.voice_autoreply': {'siid': 5, 'piid': 31}, 'cateye.voice_autoreply_time': {'siid': 5, 'piid': 33}, 'cateye.voice_autoreply_item': {'siid': 5, 'piid': 34}, 'cateye.voice_autoreply_week': {'siid': 5, 'piid': 35}, 'cateye.ver_camera_detail': {'siid': 5, 'piid': 36}, 'cateye.ver_fw_camera': {'siid': 5, 'piid': 37}, 'cateye.sdcard_info': {'siid': 5, 'piid': 38}, 'cateye.sdcard_status': {'siid': 5, 'piid': 39}, 'cateye.ver_internal': {'siid': 5, 'piid': 41}, 'cateye.motiondetection': {'siid': 5, 'piid': 42}, 'speaker.volume': {'siid': 8, 'piid': 1}, 'battery_level': {'siid': 6, 'piid': 1}, 'detection_sensitivity-4-3': {'siid': 4, 'piid': 3}, 'motion_detection_start_time-4-4': {'siid': 4, 'piid': 4}, 'motion_detection_end_time-4-5': {'siid': 4, 'piid': 5}, 'motion_detection.alarm_interval': {'siid': 4, 'piid': 6}, 'indicator_light.on': {'siid': 3, 'piid': 1}}, max_properties: 10/40

--------------------------------------------

日志: homeassistant.helpers.entity
来源: helpers/entity.py:1597
首次发生: 22:35:54 (1 全部发生)
上次记录: 22:35:54

Entity camera.loock_v06_77ba_video_doorbell (<class 'custom_components.xiaomi_miot.camera.MiotCameraEntity'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CameraEntityFeature: 0>, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by xiaodong-lx** [comment]
该设备可云端模式使用，本地模式不行

**Comment by MrSitnikov** [comment]
For some reason there is no video broadcast from the device, only occasional images can be seen.Is there any way to fix this? Thank you!
