### ISSUE TITLE
The camera entity camera.(...) does not support requesting width and height, please open an issue with the integration author

### ISSUE THREAD

**Issue by john5du** [al-one/hass-xiaomi-miot#174]
core 更新到2021.9.1 后日志出现类似的告警

设备型号：[madv.cateye.dlowle](https://home.miot-spec.com/s/madv.cateye.dlowle)

日志： 2021-09-03 10:45:26 WARNING (MainThread) [homeassistant.components.camera] The camera entity camera.(...) does not support requesting width and height, please open an issue with the integration author

**Comment by al-one** [comment]
最新提交：https://github.com/al-one/hass-xiaomi-miot/commit/cc9a6c7300486ba9fdb8b4ac55000fbece92c245 已修复。
