### ISSUE TITLE
小爱PRO的电视遥控器不好用

### ISSUE THREAD

**Issue by 2Maliao** [al-one/hass-xiaomi-miot#1741]
### Device model / 设备型号

miir.tv.ir01

### Component version / 插件版本

0.7.18

### HA core version / HA版本

2024.6.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

miir.tv.ir01的TV Remote Control IR TV Control之前有几个按钮可以调音量和控制开关，现在所有按钮都没了

### Entity attributes / 实体属性

miir_ir01_ir_tv_control

**Comment by al-one** [comment]
提供的信息(实体属性、日志)不全
