### ISSUE TITLE
问一下，局域网已经添加好的设备，ip和token是存放在哪里的，我该如何找到ip和token

### ISSUE THREAD

**Issue by HF1643** [al-one/hass-xiaomi-miot#177]
问一下，局域网已经添加好的设备，ip和token是存放在哪里的，我该如何找到ip和token

Ask me, where are the IP and token stored for the devices added to the LAN, and how can I find the IP and token

**Comment by al-one** [comment]
如果有添加账号集成或者在yaml配置账号密码，可以通过HA服务[`xiaomi_miot.get_token`](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.get_token)来获取设备IP和Token。
如果只有token集成，可以在HA目录下的文件`.storage/core.config_entries`中找到设备信息。

**Comment by HF1643** [comment]
好的，已经扎到了，非常感谢
