### ISSUE TITLE
小米音箱

### ISSUE THREAD

**Issue by sundyint** [al-one/hass-xiaomi-miot#1770]
### Device model / 设备型号

xiaomi.wifispeaker.l16a

### Component version / 插件版本

	0.7.19

### HA core version / HA版本

2024.7.2

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

本地连接，实体Xiaomi Sound Play Control不可用。

### Entity attributes / 实体属性

media_player.xiaomi_l16a_d26e_play_control

### Home Assistant Logs / 系统日志

日志记录器: miio.miioprotocol
来源: custom_components/xiaomi_miot/__init__.py:695
集成: Xiaomi Miot Auto (文档, 问题)
首次出现: 16:30:07 (112 次总计出现)
上次记录: 17:25:53

Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}

日志记录器: custom_components.xiaomi_miot.media_player
来源: custom_components/xiaomi_miot/__init__.py:1432
集成: Xiaomi Miot Auto (文档, 问题)
首次出现: 16:30:07 (112 次总计出现)
上次记录: 17:25:53

Xiaomi Sound(xiaomi.wifispeaker.l16a): Got MiioException while fetching the state: Unable to recover failed command, mapping: {'play_control.playing_state': {'siid': 3, 'piid': 1}, 'play_control.play_loop_mode': {'siid': 3, 'piid': 3}, 'sound_recognition.noise_decibel': {'siid': 10, 'piid': 2}, 'sound_detection-10-3': {'siid': 10, 'piid': 3}, 'noise_detection-10-4': {'siid': 10, 'piid': 4}, 'no_disturb': {'siid': 9, 'piid': 1}, 'no_disturb.enable_time_period': {'siid': 9, 'piid': 2}, 'intelligent_speaker.sleep_mode': {'siid': 7, 'piid': 3}, 'intelligent_speaker.audio_id': {'siid': 7, 'piid': 4}, 'clock.on': {'siid': 6, 'piid': 1}, 'clock.status': {'siid': 6, 'piid': 2}, 'clock.fault': {'siid': 6, 'piid': 3}, 'clock.ringtone': {'siid': 6, 'piid': 4}, 'microphone.mute': {'siid': 4, 'piid': 1}, 'speaker.volume': {'siid': 2, 'piid': 1}, 'speaker.mute': {'siid': 2, 'piid': 2}}, max_properties: 8/16

**Comment by al-one** [comment]
小米音箱不支持本地接入。
