### ISSUE TITLE
关于循环扇(xiaomi.fan.p51)的角度实体的属性，以及其他设备的属性应该如何参照miot来添加？

### ISSUE THREAD

**Issue by PerryLayne** [al-one/hass-xiaomi-miot#1779]
### Device model / 设备型号

xiaomi.fan.p51

### Component version / 插件版本

0.7.19

### HA core version / HA版本

2024.6.4

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

我想添加一些自己的属性，例如[循环扇](https://home.miot-spec.com/spec/xiaomi.fan.p51)的[horizontal-swing-included-angle](https://miot-spec.org/miot-spec-v2/spec/property?type=urn:miot-spec-v2:property:horizontal-swing-included-angle:0000011B),也就是下面实体属性中的**horizontal_swing_included_angle-2-5**项

我不懂代码，但通过阅读文档、反复尝试成功添加Gateway 3的自定义设备和实体属性
我想知道xiaomi-miot能不能也有类似办法来参照miot-spec自己添加设备及属性，因为我阅读了[添加实体文档](https://github.com/al-one/hass-xiaomi-miot/issues/100)我也阅读并且尝试了很久，依然没有成功添加实体，不知道是不是我的方法有问题。因为我没有代码相关基础很遗憾。
只能劳烦作者，如果您能给一个或者一些示例那更是万分感谢，授人以鱼不如授人以渔。

另外洗衣机有些翻译我补全了。我不太会用github，我不知道怎样提交顺便请教一下

### Entity attributes / 实体属性

preset_modes: 直吹风, 自然风
oscillating: true
percentage: 36
percentage_step: 1
preset_mode: 自然风
model: xiaomi.fan.p51
entity_class: MiotFanEntity
home_room: Perry Home 套房
miot_type: urn:miot-spec-v2:device:fan:0000A005:xiaomi-p51:1
fan.on: false
fan.fan_level: 2
fan.mode: 1
fan.horizontal_swing: true
horizontal_swing_included_angle-2-5: 30
fan-2.stepless_fan_level: 36
delay: false
delay.delay_time: 0
delay.delay_remain_time: 0
physical_controls_locked: false
alarm: true
indicator_light.on: true
state_updater: lan
sub_entities: physical_controls_locked-7.physical_controls_locked-1, indicator_light-5
friendly_name: 米家循环扇 Fan
supported_features: 11

**Comment by SodaWithoutSparkles** [comment]
你进[customization](http://ha.lan/_my_redirect/config_flow_start?domain=xiaomi_miot) 里面，选customizing device，选择对应型号。在`number_propertities`里面写`horizontal_swing_included_angle-2-5`。

再不行找一个template number 或者 template select 写一下就好。虽然说比较难，但是客制化更多。尤其适合没有规律的角度。例如我的风扇支持 [0, 30, 60, 90, 120, 140]，因为不是按照步长30，所以用number选不到140度。

**Comment by al-one** [comment]
尝试master分支
