### ISSUE TITLE
温度湿度设备（miaomiaoce.sensor_ht.t2）获取实时数据问题

### ISSUE THREAD

**Issue by ideatechfr** [al-one/hass-xiaomi-miot#178]
共有3个温度设备，但在HA里显示获取的温度经常是几个小时以前的，没有实时数据。已经启用了轮询查询

麻烦帮忙看看

**Comment by al-one** [comment]
请在温湿度不更新的时间段进入[开发者工具 > 状态](https://my.home-assistant.io/redirect/developer_states)，并筛选温度实体，把实体状态属性反馈给我。并截图实体的历史图表。

**Comment by ideatechfr** [comment]
model: miaomiaoce.sensor_ht.t2
lan_ip: 
mac_address: A4:C1:38:90:12:1A
firmware_version: 1.0.0_0130
hardware_version: 
entity_class: MiotSensorEntity
miot_type: urn:miot-spec-v2:device:temperature-humidity-sensor:0000A00A:miaomiaoce-t2:1
state_property: temperature-2-1
temperature-2-1: 28.1
relative_humidity-2-2: 53
battery.battery_level: 100
state_updater: cloud
sub_entities: battery-3.battery_level-1, temperature_humidity_sensor-2.relative_humidity-2
unit_of_measurement: °C
friendly_name: 路由 Temperature Humidity Sensor Temperature
supported_features: 0
device_class: temperature

设备一个小时没有更新数据
![截屏2021-09-08 16 22 21](https://user-images.githubusercontent.com/37808758/132527464-964d1503-c9b1-40ae-b903-8025043839a3.png)
米家显示的实时数据信息
![IMG_2BFD41F6AAEB-1](https://user-images.githubusercontent.com/37808758/132527652-f42485d0-e9b2-4d1c-9568-d09e9d5141f6.jpeg)

**Comment by ideatechfr** [comment]
收到的通知信息，会不会因为是云数据获取不到？
![截屏2021-09-08 16 50 42](https://user-images.githubusercontent.com/37808758/132534353-cf7047f8-8820-41ea-98d9-6e8f5bf5f2de.png)

**Comment by al-one** [comment]
> 收到的通知信息，会不会因为是云数据获取不到？
> ![截屏2021-09-08 16 50 42](https://user-images.githubusercontent.com/37808758/132534353-cf7047f8-8820-41ea-98d9-6e8f5bf5f2de.png)
> 

这个通知是通过HA服务[`xiaomi_miot.get_token`](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.get_token)查询设备信息产生的通知，与此问题无关。获取设备信息需要填入米家中的设备名称。

**Comment by al-one** [comment]
请问这个问题还存在吗？

**Comment by ideatechfr** [comment]
你好，这个问题还是存在。不过有点不同的是现在大约1-2天会出现不能获取实时数据，现在就重启HA就能恢复正常，是否可以加一个定时重启服务的任务呢？

**Comment by al-one** [comment]
也许你可以尝试用HA自动化定时执行下面的服务：
```yaml
# 更新单个实体/设备
service: homeassistant.update_entity
target:
  entity_id: sensor.your_entity_id
```

```yaml
# 重载某个实体所属的集成
service: homeassistant.reload_config_entry
target:
  entity_id: sensor.your_entity_id
```

**Comment by al-one** [comment]
@ideatechfr 关于温湿度计数据不更新的问题，请更新到master分支后尝试是否仍然存在。

**Comment by ideatechfr** [comment]
已经更新，今天会看一下是否能持续更新

**Comment by ideatechfr** [comment]
你好，昨天更新到master分支后，数据更新的确有改善大约有十几小时数据还是有更新，但早上看显示获取不到数据，更新到0.4.12也是同样问题。

![截屏2021-12-17 上午9 02 09](https://user-images.githubusercontent.com/37808758/146510971-49d7320e-1df5-4bf0-a32c-6abae623c383.png)
![截屏2021-12-17 上午9 03 08](https://user-images.githubusercontent.com/37808758/146510989-ff76a611-034f-4087-b6eb-4ebb5838b65f.png)

**Comment by al-one** [comment]
实体已经不可用，请检查下有没有报错日志。

**Comment by ideatechfr** [comment]
重启了几次设备已经正常了，目前数据看来时稳定跟新的。
