### ISSUE TITLE
Devices offline

### ISSUE THREAD

**Issue by teamolaguer** [al-one/hass-xiaomi-miot#1787]
### Device model / 设备型号

xiaomi.airp.cpa4

### Component version / 插件版本

0.7.19

### HA core version / HA版本

core-2024.7.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Cannot add Air purifier 4 compact. ip address in correct. previously working. see notification below.
already tried uninstalling and reinstalling via HACS

Notification:

Devices offline
Some devices cannot be connected in the LAN, please check their IP and make sure they are in the same subnet as the HA.

Some devices cannot be connected via LAN, please check their IP and make sure they are on the same subnet as HA.

Xiaomi Smart Air Purifier 4 Compact(xiaomi.airp.cpa4): 192.168.x.x

Logs:

### Entity attributes / 实体属性

fan.xiaomi_cpa4_94c4_air_purifier

### Home Assistant Logs / 系统日志

Logger: custom_components.xiaomi_miot.fan
Source: custom_components/xiaomi_miot/__init__.py:1432
integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 3:08:11 AM (16 occurrences)
Last logged: 3:15:46 AM

Xiaomi Smart Air Purifier 4 Compact(xiaomi.airp.cpa4): Got MiioException while fetching the state: Unable to discover the device 192.168.2.14, mapping: {'air_purifier.on': {'siid': 2, 'piid': 1}, 'air_purifier.fault': {'siid': 2, 'piid': 2}, 'air_purifier.mode': {'siid': 2, 'piid': 4}, 'aqi.aqi_updata_heartbeat': {'siid': 11, 'piid': 4}, 'screen.brightness': {'siid': 13, 'piid': 2}, 'physical_controls_locked': {'siid': 8, 'piid': 1}, 'alarm': {'siid': 6, 'piid': 1}, 'filter.filter_life_level': {'siid': 4, 'piid': 1}, 'filter.filter_used_time': {'siid': 4, 'piid': 3}, 'filter.filter_left_time': {'siid': 4, 'piid': 4}, 'environment.pm2_5_density': {'siid': 3, 'piid': 4}}, max_properties: 6/11

**Comment by st412m** [comment]
Регистратор: custom_components.xiaomi_miot.vacuum
Источник: custom_components/xiaomi_miot/__init__.py:1432
интеграция: Xiaomi Miot Auto ([документация](https://github.com/al-one/hass-xiaomi-miot), [проблемы](https://github.com/al-one/hass-xiaomi-miot/issues))
Первое сообщение: 14:24:43 (103 сообщений)
Последнее сообщение: 16:06:48
Толик(roidmi.vacuum.v60): Got MiioException while fetching the state: Unable to discover the device 192.168.1.36, mapping: {'vacuum.status': {'siid': 2, 'piid': 1}, 'vacuum.fault': {'siid': 2, 'piid': 2}, 'vacuum.mode': {'siid': 2, 'piid': 4}, 'vacuum.sweep_type': {'siid': 2, 'piid': 8}, 'vacuum.on': {'siid': 2, 'piid': 10}, 'sweep.sweep_mode': {'siid': 14, 'piid': 1}, 'brush_left_time-15-1': {'siid': 15, 'piid': 1}, 'brush_life_level-15-2': {'siid': 15, 'piid': 2}, 'brush_left_time-12-1': {'siid': 12, 'piid': 1}, 'brush_life_level-12-2': {'siid': 12, 'piid': 2}, 'brush_cleaner.brush_left_time': {'siid': 11, 'piid': 1}, 'brush_cleaner.brush_life_level': {'siid': 11, 'piid': 2}, 'filter.filter_life_level': {'siid': 10, 'piid': 1}, 'filter.filter_left_time': {'siid': 10, 'piid': 2}, 'speaker.volume': {'siid': 9, 'piid': 1}, 'speaker.mute': {'siid': 9, 'piid': 2}, 'battery_level': {'siid': 3, 'piid': 1}, 'battery.charging_state': {'siid': 3, 'piid': 2}}, max_properties: 9/18

**Comment by st412m** [comment]
It fixed itself

**Comment by al-one** [comment]
- #500

**Comment by teamolaguer** [comment]
This is all good now. Thanks team!
