### ISSUE TITLE
homeassistant更新到2024.7.4后，设备配置的interval_seconds修改不生效

### ISSUE THREAD

**Issue by 375088843** [al-one/hass-xiaomi-miot#1793]
### Device model / 设备型号

izq.sensor_occupy.solo

### HA core version / HA版本

2024.7.4

### Integrated mode / 集成方式

Token

### The problem / 问题详情

homeassistant更新到2024.7.4后，通过token集成或本地集成的设备配置interval_seconds后，interval_seconds都不生效。
![1722610456511](https://github.com/user-attachments/assets/080fa8de-1b67-4d09-af99-9404e492aa2a)

### Entity attributes / 实体属性

```yaml
sensor.izq_solo_80f1_occupancy_sensor
```

**Comment by al-one** [comment]
- #1559
