### ISSUE TITLE
新增设备是在哪里新增的

### ISSUE THREAD

**Issue by redhatme** [al-one/hass-xiaomi-miot#1798]
### Device model / 设备型号

[szhhkj.diffuser.jd01](https://home.miot-spec.com/s/szhhkj.diffuser.jd01)

### Component version / 插件版本

目前最新版

### HA core version / HA版本

2024.7.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

有个设备不支持。想手动新增，是在core/miio2miot_specs.py这里写吗，比如想简单的实验一下。    'szhhkj.diffuser.jd01': {
        'miio_specs': {
        'prop.2.1004': {'prop': 'power', 'setter': True, 'format': 'onoff'},
        }, 是这样添加上吗。  但是重启ha。ha里面还是没有这个设备。

### Entity attributes / 实体属性

```yaml
无实体
```

**Comment by al-one** [comment]
该设备无任何有读取权限的属性。
![szhhkj.diffuser.jd01 spec](https://github.com/user-attachments/assets/79548df8-334d-42a1-9d88-0d29a8f1dd46)

**Comment by redhatme** [comment]
多谢大佬回复。好的，了解了。

**Comment by gas04032006** [comment]
> 多謝大佬回覆。好，了解了。

有新增成功嗎?
