### ISSUE TITLE
请求支持 大金空调/新风（米家新支持可以连接大金了）

### ISSUE THREAD

**Issue by frishcat** [al-one/hass-xiaomi-miot#1799]
米家现在可以连接大金账号了，支持大金中央空调、新风接入
请求大神支持接入米家的大金空调、新风🙏

![IMG_B20592607681-1](https://github.com/user-attachments/assets/c39c4c3b-7ca3-4f80-a91c-3c535e256b39)

![IMG_9869](https://github.com/user-attachments/assets/db6a8f3c-04c6-4368-8798-968ada758782)

![IMG_E8CB7F4F9A8B-1](https://github.com/user-attachments/assets/e505c8f9-ec8b-4caf-a0ab-68beb0132371)

------------------------------------------------
备注：
之前通过 DS-AIR 也可以接入，但是存在几个问题
- 支持的 VRF 非常有限
- 只能支持中央空调，不支持新风
- 拿不到环境温度、空气质量信息

**Comment by al-one** [comment]
只能通过云端接入该设备。
如果可以，请将整个家庭共享给米家账号:`143050915`，也可以在米家新建一个家庭，只把大金设备移过去共享。

**Comment by frishcat** [comment]
> 只能通过云端接入该设备。 如果可以，请将整个家庭共享给米家账号:`143050915`，也可以在米家新建一个家庭，只把大金设备移过去共享。

已共享管理员权限。🙏

**Comment by al-one** [comment]
master分支已支持。

**Comment by frishcat** [comment]
> master分支已支持。

超赞！辛苦大神🙏

我在 HA 里已经能看到设备了。新风的话，米家中有一个空气质量信息，不知道这个信息是否可以得到呢？

- 目前新风设别下面只有一个 Air Fresh 实体
- 空气质量信息如下图：

![IMG_9907](https://github.com/user-attachments/assets/98bd80c7-742f-4723-b0d8-8d336af0503a)

**Comment by al-one** [comment]
感谢感谢！💝

不过该型号的新风设备规格中并未有空气指数属性。
![image](https://github.com/user-attachments/assets/c611fa3a-7b85-470d-b047-933cda664e53)

**Comment by frishcat** [comment]
> 感谢感谢！💝
> 
> 不过该型号的新风设备规格中并未有空气指数属性。
> ![image](https://github.com/user-attachments/assets/c611fa3a-7b85-470d-b047-933cda664e53)

okok，那可能是没有暴露这个接口。那这个 issue 应该可以 close 啦 😄🙏
