### ISSUE TITLE
添加空调内存泄漏

### ISSUE THREAD

**Issue by xztxy** [al-one/hass-xiaomi-miot#18]
云米空调添加使用后内存不断增加，导致homeassistant死掉。卸载插件后正常~

**Comment by al-one** [comment]
请问：
- HA死掉的频率大概多久一次？
- 是否只集成了一台空调设备？
- 是否开启了miot_cloud？

请尝试仅删除空调集成（不删插件）后运行看看。

**Comment by xztxy** [comment]
> 请问：
> 
> * HA死掉的频率大概多久一次？
> * 是否只集成了一台空调设备？
> * 是否开启了miot_cloud？
> 
> 请尝试仅删除空调集成（不删插件）后运行看看。

感谢大佬回复！HA插件是没有删除的，我的一个雷士的miot灯一直正常在用。空调总共有三台接入，控制都没问题。HA 1G内存大概5个小时就满内存了。 miot_cloud没用到呢

**Comment by al-one** [comment]
能否尝试下仅保留一台空调的集成，然后再运行一段时间看看。

**Comment by xztxy** [comment]
> 能否尝试下仅保留一台空调的集成，然后再运行一段时间看看。

好的。试下~

**Comment by xztxy** [comment]
> 能否尝试下仅保留一台空调的集成，然后再运行一段时间看看。

中午出门前添加了一台空调，刚回来发现又死了。。内存100%
