### ISSUE TITLE
Does not set FanEntityFeature.TURN_OFF / TURN_ON

### ISSUE THREAD

**Issue by gurglingtonic** [al-one/hass-xiaomi-miot#1806]
> Logger: homeassistant.components.fan
> Source: components/fan/__init__.py:295
> integration: Fan ([documentation](https://www.home-assistant.io/integrations/fan), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+fan%22))
> First occurred: 9:29:43 pm (2 occurrences)
> Last logged: 9:29:43 pm
> 
> Entity xiaomi_miot.zhimi_za4_9a58_fan (<class 'custom_components.xiaomi_miot.fan.MiotFanEntity'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> Entity xiaomi_miot.zhimi_za4_9a58_fan (<class 'custom_components.xiaomi_miot.fan.MiotFanEntity'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues

Home Assistant Version 2024.8.0

**Comment by rwjack** [comment]
Yep, same here
