### ISSUE TITLE
Consult about unit_of_measurement of atmospheric_pressure

### ISSUE THREAD

**Issue by facutopa** [al-one/hass-xiaomi-miot#181]
Hi,

I got this pressure value:
![preasure](https://user-images.githubusercontent.com/7283431/133082234-244bf595-830d-4a1f-89d7-932bfcc87800.png)
Can I do something to change the Unit Measurement?

Thanks and regards!

**Comment by al-one** [comment]
Yes, you can change the unit of measurement by [modifying custom attributes](https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui).
![image](https://user-images.githubusercontent.com/4549099/133083581-6413711d-df79-4b92-b6fb-e1fa27b73353.png)

But if you get the value through entity properties, you need to create an entity through a [template](https://www.home-assistant.io/integrations/template#change-the-unit-of-measurement).

**Comment by facutopa** [comment]
Ok I will check how update the template because I just setup HA the last friday and I'm a bit newbiee with all this.
Thanks
