### ISSUE TITLE
xiaomi.vacuum.c107 is unavailable in Automatic or Local mode（or with token）, but performs well in Cloud mode

### ISSUE THREAD

**Issue by jiandong94** [al-one/hass-xiaomi-miot#1823]
### Device model / 设备型号

xiaomi.vacuum.c107

### Component version / 插件版本

0.7.19

### HA core version / HA版本

2024.7.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

xiaomi.vacuum.c107 is unavailable in Automatic or Local mode（or with token）, but performs well in Cloud mode. The log is similar to #1586 , and it reports 'Please check its IP and make sure it is in the same subnet as the HA' in the sidebar notifications in Home Assistant. However, I have confirmed that it is indeed in the same subnet. Please check this bug, thank you!

### Entity attributes / 实体属性

```yaml
无实体
```

**Comment by hi94740** [comment]
I have the same problem. It worked in the first couple of days and then it stopped working.

**Comment by kostrum** [comment]
Same issue.
Will someone help to fix it?

**Comment by al-one** [comment]
Try master branch.
```bash
wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
```

**Comment by hi94740** [comment]
> Try master branch.
> 
> ```bash
> 
> wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
> 
> ```

Thanks! It appears to be working fine in local mode now.

**Comment by al-one** [comment]
A card for this robot.
- https://github.com/al-one/hass-xiaomi-miot/discussions/2225
