### ISSUE TITLE
https://home.miot-spec.com无法打开

### ISSUE THREAD

**Issue by zengyr49** [al-one/hass-xiaomi-miot#1827]
<img width="1218" alt="image" src="https://github.com/user-attachments/assets/7a159f9c-916b-47db-9ebd-c5f88ce4e9bf">
我打算去查看这个具体的设备参数，但是发现报500错误。不知道大家有遇到这个问题，知道怎么解决吗？
GET这个地址：https://home.miot-spec.com/s/switch

**Comment by ABUAIJUTIE** [comment]
+1 好几天了

**Comment by xmasrain** [comment]
是不是无法更新设备？

**Comment by al-one** [comment]
已恢复访问。
