### ISSUE TITLE
Unable to see a live stream

### ISSUE THREAD

**Issue by new-kirte** [al-one/hass-xiaomi-miot#183]
I am getting the following error in the log:
2021-09-14 12:32:48 ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream -decryption_key XXXXXXXXXXXXXXXXXXXXXXXXXXXX -decryption_iv 3716138E68EAD0C9BB1446C9DD90CE7F -i "crypto+https://sg.processor.smartcamera.api.io.mi.com/miot/camera/app/play/v1/video/file.mp4?stoId=XXXXXXXXXXXXXXXXXXXX&fileId=63453077639796096&segmentIv=0x3716138E68EAD0C9BB1446C9DD90CE7F&did=322523286&yetAnotherServiceToken=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX="

Camera device model: chuangmi.camera.ipc019
camera-stream-for-google-home is present https://home.miot-spec.com/spec?model=chuangmi.camera.ipc019
Masked stream_address: https://sg09.livestreaming.io.mi.com/hlstranscoder/<mask-63-characters>_H265transH264/playlist.m3u8
ffmpeg:
bash-5.1# ffmpeg -v warning -y -i 'https://sg09.livestreaming.io.mi.com/hlstranscoder/<mask-63-characters>_H265transH264/playlist.m3u8' an -c:v mjpeg -f mpjpeg xiaomi_camera_video
[https @ 0x7f26c5b8db40] HTTP error 403 Forbidden
https://sg09.livestreaming.io.mi.com/hlstranscoder/<mask-63-characters>_H265transH264/playlist.m3u8: Server returned 403 Forbidden (access denied)

**Comment by new-kirte** [comment]
access_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
brand: chuangmi
model: chuangmi.camera.ipc019
lan_ip: 192.168.100.128
mac_address: 5C:E5:0C:6A:53:D0
firmware_version: 4.0.9_0426
hardware_version: ''
entity_class: MiotCameraEntity
miot_type: urn:miot-spec-v2:device:camera:0000A01C:chuangmi-ipc019:1
miot_action_result:
  did: '311243068'
  miid: 0
  siid: 4
  aiid: 1
  code: 0
  out:
    - >-
      https://sg09.livestreaming.io.mi.com/hlstranscoder/<mask>_H265transH264/playlist.m3u8
stream_address: >-
  https://sg09.livestreaming.io.mi.com/hlstranscoder/<mask>_H265transH264/playlist.m3u8
expire_at: '2021-09-14 12:34:36.201869'
miot_error: null
camera_control.on: true
camera_control.image_rollover: 0
camera_control.night_shot: 0
camera_control.time_watermark: true
camera_control.wdr_mode: true
glimmer_full_color-2-6: true
camera_control.recording_mode: 3
camera_control.motion_tracking: true
stream_status-3-1: 1
state_updater: cloud
sub_entities:
  - camera_control.on
  - motion_event
friendly_name: Sonya camera Camera Control
entity_picture: >-
  /api/camera_proxy/camera.chuangmi_ipc019_53d0_camera_control?token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
supported_features: 3
video_attribute: '2'
keep_streaming: 'true'
use_motion_stream: 'true'
sub_motion_stream: 'true'
motion_stream_slice: '-1'

**Comment by john5du** [comment]
#166

**Comment by new-kirte** [comment]
@john5du, so I read #166 and it does not fix the issue. Anything more precise you would recommend me to try?

**Comment by al-one** [comment]
>  miot_action_error: '-704220025 The number of action parameters does not match'

See https://github.com/al-one/hass-xiaomi-miot/issues/179#issuecomment-917365887

**Comment by new-kirte** [comment]
@al-one, thanks. Why does video_attribute: 0 not work?

**Comment by al-one** [comment]
I don’t know, this error was returned by Xiaomi Cloud.

**Comment by new-kirte** [comment]
Closing as a valid workaround exist - adding the property video_attribute: 1

**Comment by Aljumaili85** [comment]
@al-one I was digging in your HACS code and I wanted to ask if you could provide me a clear way to get the live streaming of the camera ? I didnt get any success using python-miio . Appricate your help.
