### ISSUE TITLE
老款立式空调 模式切换出错

### ISSUE THREAD

**Issue by Madagascarooh** [al-one/hass-xiaomi-miot#1835]
### Device model / 设备型号

[xiaomi.aircondition.ma4](https://home.miot-spec.com/s/xiaomi.aircondition.ma4)

### Component version / 插件版本

2.2.8

### HA core version / HA版本

2024.8.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

HA和Homekit设置里模式出错：
设置制冷➞实际除湿
设置除湿➞实际加热

### Entity attributes / 实体属性

```yaml
climate.xiaomi_ma4_3268_air_conditioner
```

### Home Assistant Logs / 系统日志

自行安裝整合產生錯誤。

記錄器: custom_components.xiaomi_miot.climate
來源: custom_components/xiaomi_miot/__init__.py:1445
整合: Xiaomi Miot Auto (相關文件, 問題)
首次發生: 上午2:42:12 (7 事件)
最後紀錄: 上午2:48:17

客厅空调(xiaomi.aircondition.ma4): Got MiioException while fetching the state: Unable to discover the device 192.168.1.100, mapping: {'air_conditioner.on': {'siid': 2, 'piid': 1}, 'air_conditioner.mode': {'siid': 2, 'piid': 2}, 'target_temperature-2-3': {'siid': 2, 'piid': 3}, 'air_conditioner.eco': {'siid': 2, 'piid': 4}, 'air_conditioner.heater': {'siid': 2, 'piid': 5}, 'air_conditioner.sleep_mode': {'siid': 2, 'piid': 6}, 'air_conditioner.dryer': {'siid': 2, 'piid': 7}, 'maintenance.examine': {'siid': 9, 'piid': 2}, 'indicator_light.on': {'siid': 6, 'piid': 1}, 'alarm': {'siid': 5, 'piid': 1}, 'environment.temperature': {'siid': 4, 'piid': 1}, 'fan_control.fan_level': {'siid': 3, 'piid': 1}, 'fan_control.vertical_swing': {'siid': 3, 'piid': 2}, 'fan_control.horizontal_swing': {'siid': 3, 'piid': 3}}, max_properties: 10/14

**Comment by al-one** [comment]
尝试master分支

**Comment by anhnvme** [comment]
> 尝试master分支

thank you. i'm wait this fix so long. My ma1 not working few month ago. now it's work perfectly. when its official release ?

**Comment by al-one** [comment]
Fixed in v0.7.22
