### ISSUE TITLE
米家蓝牙Mesh筒灯断电后显示状态为On

### ISSUE THREAD

**Issue by andyliu50** [al-one/hass-xiaomi-miot#1843]
米家蓝牙Mesh筒灯接入HA后，可以正常开/关使用。但是如果用物理开关将筒灯断电后，HA中显示筒灯仍然是开启的状态，但是，如果打开米家App查看，却显示筒灯是关闭的状态。请问这个问题是否有解？

Xiaomi MIOT Auto: v0.7.20
HA Core: 2024.8.3
HA Frontend: 20240809.0

**Comment by al-one** [comment]
暂时无解
