### ISSUE TITLE
人体传感器一直显示触发，和米家app不一致

### ISSUE THREAD

**Issue by jifengmm** [al-one/hass-xiaomi-miot#185]
![image](https://user-images.githubusercontent.com/35440294/133394661-24a9aa01-3ee3-4724-910a-c33ea23e62aa.png)
Model
[lumi.motion.bmgl01](https://home.miot-spec.com/s/lumi.motion.bmgl01)
Lan IP
MAC address
54:EF:44:E5:A9:9D
Firmware version
1.1.1_0010
Hardware version
Entity class
LumiBinarySensorEntity
Miot type
urn:miot-spec-v2:device:motion-sensor:0000A014:lumi-bmgl01:1
State property
no_motion_duration-2-2
Motion sensor.illumination.error
-704220043 Property value error
No motion duration-2-2
false
Battery.battery level
100
State updater
cloud
Sub entities
battery-3.battery_level-1

![image](https://user-images.githubusercontent.com/35440294/133394695-a4986b78-db6e-4d23-ad41-625b7e24dafe.png)
![7c19dbbd215cee2f871b542adaad76b](https://user-images.githubusercontent.com/35440294/133394809-3abbded4-f316-4991-88a4-1627a8c2ebcb.jpg)

**Comment by al-one** [comment]
请尝试更新到master分支后尝试。

**Comment by jifengmm** [comment]
更新到最新分支后问题解决。
