### ISSUE TITLE
乐天派人体传感器POP显示不全

### ISSUE THREAD

**Issue by lili890527** [al-one/hass-xiaomi-miot#1851]
### Device model / 设备型号

[乐天派人体传感器POP](https://home.miot-spec.com/s/rhj.sensor_occupy.l730a)

### Component version / 插件版本

0.7.X

### HA core version / HA版本

2024.9.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

乐天派人体传感器POP有多个传感器，通过网关后，米家APP都有数值。但HA自动接入的时候，传感器少了照度传感器数值。

### Entity attributes / 实体属性

```yaml
无实体
```

**Comment by al-one** [comment]
提供同设备下其他实体的属性

**Comment by lili890527** [comment]
> 提供同设备下其他实体的属性
已经用template模板写好了，可以调用出来，如果可以自动生成就更好了。
sensor:
  - platform: template
    sensors:
      zhuwo_renzai_lux:
        friendly_name: "主卧人在照度"
        value_template:  "{{ state_attr('sensor.rhj_l730a_7b50_occupancy_sensor', 'occupancy_sensor.illumination') }}"
        unit_of_measurement: "lx"
        unique_id: sensor.zhuwo_renzai_lux
        device_class: illuminance

设备的属性图片如下：![b49958dc52b0fe3dc04717b7a9d46ba](https://github.com/user-attachments/assets/ebfe2126-2f83-43a4-be20-c80290457076)
