### ISSUE TITLE
vacuum.xiaomi_c107 Devices offline

### ISSUE THREAD

**Issue by kostrum** [al-one/hass-xiaomi-miot#1856]
### Device model / 设备型号

vacuum.xiaomi_c107

### Component version / 插件版本

0.7.20

### HA core version / HA版本

2024.9.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

The vacuum was connected for a short time, then an error appeared:
Devices offline:
Some devices cannot be connected in the LAN, please check their IP and make sure they are in the same subnet as the HA.

![image](https://github.com/user-attachments/assets/b6bcaddc-8e2b-4b57-a369-6102a72c5e0e)
![image](https://github.com/user-attachments/assets/eccf1499-60d8-4acd-bc1c-1bddd64d1f78)

Could someone help to fix it?

### Entity attributes / 实体属性

```yaml
fan_speed_list: Silent, Basic, Strong, Full Speed
friendly_name: Mijia Robot Vacuum M30 Pro Robot Cleaner
supported_features: 12540
```

### Home Assistant Logs / 系统日志

Logger: custom_components.xiaomi_miot.vacuum
Source: custom_components/xiaomi_miot/__init__.py:1445
integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 10:46:52 (55 occurrences)
Last logged: 11:41:12
Mijia Robot Vacuum M30 Pro(xiaomi.vacuum.c107): Got MiioException while fetching the state: No response from the device, mapping: {'vacuum.vacuum_frameware_version': {'siid': 2, 'piid': 1}, 'vacuum.status': {'siid': 2, 'piid': 2}, 'vacuum.fault': {'siid': 2, 'piid': 3}, 'vacuum.sweep_mop_type': {'siid': 2, 'piid': 4}, 'vacuum.sweep_type': {'siid': 2, 'piid': 5}, 'vacuum.cleaning_area': {'siid': 2, 'piid': 6}, 'vacuum.cleaning_time': {'siid': 2, 'piid': 7}, 'vacuum.clean_times': {'siid': 2, 'piid': 8}, 'vacuum.mode': {'siid': 2, 'piid': 9}, 'vacuum.mop_water_output_level': {'siid': 2, 'piid': 10}, 'vacuum.mop_status': {'siid': 2, 'piid': 11}, 'vacuum.zone_ids': {'siid': 2, 'piid': 12}, 'vacuum.restricted_sweep_areas': {'siid': 2, 'piid': 13}, 'vacuum.restricted_walls': {'siid': 2, 'piid': 14}, 'vacuum.room_information': {'siid': 2, 'piid': 16}, 'vacuum.last_clean_time': {'siid': 2, 'piid': 17}, 'base_station_working_status-2-18': {'siid': 2, 'piid': 18}, 'vacuum.order_clean': {'siid': 2, 'piid': 19}, 'vacuum.carpet_boost': {'siid': 2, 'piid': 20}, 'vacuum.carpet_avoidance': {'siid': 2, 'piid': 21}, 'vacuum.carpet_display': {'siid': 2, 'piid': 22}, 'vacuum.sweep_break_switch': {'siid': 2, 'piid': 23}, 'vacuum.sleep_status': {'siid': 2, 'piid': 25}, 'vacuum.location_status': {'siid': 2, 'piid': 26}, 'vacuum.map_complete_dialog': {'siid': 2, 'piid': 27}, 'vacuum.enable_mop_wash': {'siid': 2, 'piid': 28}, 'vacuum.frequency_mop_wash': {'siid': 2, 'piid': 29}, 'water_output_for_washing_mop-2-30': {'siid': 2, 'piid': 30}, 'vacuum.drying_time': {'siid': 2, 'piid': 31}, 'vacuum.auto_dust_arrest': {'siid': 2, 'piid': 32}, 'vacuum.dust_arrest_frequency': {'siid': 2, 'piid': 33}, 'vacuum.auto_mop_dry': {'siid': 2, 'piid': 34}, 'vacuum.auto_water_change': {'siid': 2, 'piid': 35}, 'vacuum.use_detergent': {'siid': 2, 'piid': 36}, 'vacuum.ai_cleaning': {'siid': 2, 'piid': 37}, 'vacuum.exit_remote_dialog': {'siid': 2, 'piid': 38}, 'vacuum.current_cleaning_config': {'siid': 2, 'piid': 40}, 'vacuum.hot_water_mop_wash': {'siid': 2, 'piid': 41}, 'vacuum.user_define_sweep_cfg': {'siid': 2, 'piid': 42}, 'vacuum.user_define_sweep_id': {'siid': 2, 'piid': 43}, 'vacuum.mop_auto_lift': {'siid': 2, 'piid': 44}, 'vacuum.sweep_ai_detection': {'siid': 2, 'piid': 45}, 'vacuum.dirt_detection': {'siid': 2, 'piid': 46}, 'vacuum.object_detection': {'siid': 2, 'piid': 47}, 'vacuum.room_detection': {'siid': 2, 'piid': 48}, 'vacuum.floor_material_detection': {'siid': 2, 'piid': 49}, 'vacuum.defecation_detection': {'siid': 2, 'piid': 50}, 'vacuum.liquid_dirt_detection': {'siid': 2, 'piid': 51}, 'vacuum.solid_dirt_detection': {'siid': 2, 'piid': 52}, 'vacuum.water_check_list': {'siid': 2, 'piid': 53}, 'vacuum.water_check_status': {'siid': 2, 'piid': 54}, 'vacuum.edge_swing_tail_sweep': {'siid': 2, 'piid': 55}, 'vacuum.sweep_ai_object': {'siid': 2, 'piid': 56}, 'vacuum.sweep_furniture': {'siid': 2, 'piid': 57}, 'vacuum.carpet_object': {'siid': 2, 'piid': 58}, 'vacuum.detergent_self_delivery': {'siid': 2, 'piid': 59}, 'mop_water_output_level_no_tank-2-60': {'siid': 2, 'piid': 60}, 'frequency_mop_wash_no_tank-2-61': {'siid': 2, 'piid': 61}, 'auto_water_change_installed-2-62': {'siid': 2, 'piid': 62}, 'vacuum.cut_hair_config': {'siid': 2, 'piid': 63}, 'frequency_cut_hair_config-2-64': {'siid': 2, 'piid': 64}, 'vacuum.fault_ids': {'siid': 2, 'piid': 66}, 'vacuum.action_result': {'siid': 2, 'piid': 67}, 'vacuum.edge_sweep_frequency': {'siid': 2, 'piid': 68}, 'vacuum.ai_managed_cleaning': {'siid': 2, 'piid': 69}, 'vacuum.plugin_info_remind': {'siid': 2, 'piid': 70}, 'detergent_depletion_reminder-2-71': {'siid': 2, 'piid': 71}, 'vacuum.notice': {'siid': 2, 'piid': 72}, 'vacuum.carpet_cleaning_method': {'siid': 2, 'piid': 73}, 'vacuum.sweep_route': {'siid': 2, 'piid': 74}, 'obstacle_avoidance_strategy-2-75': {'siid': 2, 'piid': 75}, 'vacuum.carpet_deep_cleaning': {'siid': 2, 'piid': 76}, 'vacuum.carpet_discriminate': {'siid': 2, 'piid': 77}, 'custom.updata_difference': {'siid': 20, 'piid': 3}, 'ai_picture_info-17-2': {'siid': 17, 'piid': 2}, 'dust_bag.dust_bag_life_level': {'siid': 19, 'piid': 1}, 'dust_bag.dust_bag_left_time': {'siid': 19, 'piid': 2}, 'detergent_left_level-18-1': {'siid': 18, 'piid': 1}, 'detergent_self_delivery-18-2': {'siid': 18, 'piid': 2}, 'detergent_self_delivery_level-18-3': {'siid': 18, 'piid': 3}, 'detergent_left_time-18-4': {'siid': 18, 'piid': 4}, 'voice_management.target_voice': {'siid': 15, 'piid': 1}, 'voice_management.cur_voice': {'siid': 15, 'piid': 2}, 'download_status-15-3': {'siid': 15, 'piid': 3}, 'download_progress-15-4': {'siid': 15, 'piid': 4}, 'filter.filter_life_level': {'siid': 14, 'piid': 1}, 'filter.filter_left_time': {'siid': 14, 'piid': 2}, 'brush_life_level-13-1': {'siid': 13, 'piid': 1}, 'brush_left_time-13-2': {'siid': 13, 'piid': 2}, 'brush_cleaner.brush_life_level': {'siid': 12, 'piid': 1}, 'brush_cleaner.brush_left_time': {'siid': 12, 'piid': 2}, 'no_disturb': {'siid': 11, 'piid': 1}, 'no_disturb.enable_time_period': {'siid': 11, 'piid': 2}, 'no_disturb.current_no_disturb': {'siid': 11, 'piid': 3}, 'vacuum_map.map_obj_name': {'siid': 10, 'piid': 1}, 'vacuum_map.trajectory_obj_name': {'siid': 10, 'piid': 2}, 'vacuum_map.clean_record': {'siid': 10, 'piid': 3}, 'vacuum_map.vacuum_position': {'siid': 10, 'piid': 4}, 'vacuum_map.map_management': {'siid': 10, 'piid': 5}, 'vacuum_map.current_map_id': {'siid': 10, 'piid': 6}, 'vacuum_map.carpet_obj_name': {'siid': 10, 'piid': 7}, 'vacuum_map.map_3d_info': {'siid': 10, 'piid': 9}, 'mop.mop_life_level': {'siid': 9, 'piid': 1}, 'mop.mop_left_time': {'siid': 9, 'piid': 2}, 'physical_controls_locked': {'siid': 5, 'piid': 1}, 'current_physical_control_lock-5-2': {'siid': 5, 'piid': 2}, 'alarm': {'siid': 4, 'piid': 1}, 'alarm.volume': {'siid': 4, 'piid': 2}, 'battery_level': {'siid': 3, 'piid': 1}, 'battery.charging_state': {'siid': 3, 'piid': 2}, 'battery.voltage': {'siid': 3, 'piid': 3}}, max_properties: 10/111

![image](https://github.com/user-attachments/assets/3a2af665-8a67-460b-9ef7-c6e356298d26)
![image](https://github.com/user-attachments/assets/425efb08-be2e-4742-8b60-ab4458002edb)

**Comment by leotantantan** [comment]
the same here

**Comment by al-one** [comment]
Try master branch.
```bash
wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
```

**Comment by leotantantan** [comment]
> Try master branch.
> 
> ```shell
> wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
> ```

Thanks, it works for me. Problem resolved!

**Comment by kostrum** [comment]
> Try master branch.
> 
> ```shell
> wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
> ```

work for me, Thanks a lot!

**Comment by al-one** [comment]
A card for this robot.
- https://github.com/al-one/hass-xiaomi-miot/discussions/2225
