### ISSUE TITLE
Error at log: xiaomi_miot validates schema outside the event loop, which will stop working in HA Core 2025.10

### ISSUE THREAD

**Issue by KitHubek** [al-one/hass-xiaomi-miot#1865]
rejestrator: homeassistant.helpers.frame
Source: helpers/frame.py:184

`Detected that custom integration 'xiaomi_miot' validates schema outside the event loop, which will stop working in HA Core 2025.10 at custom_components/xiaomi_miot/core/miio2miot.py, line 138: tpl = cv.template(tpl), please report it to the author of the 'xiaomi_miot' custom integration`

**Comment by z-master42** [comment]
See #1879.

**Comment by al-one** [comment]
Fixed in v0.7.21
