### ISSUE TITLE
米家无线智能宠物饮水机 缺少实体

### ISSUE THREAD

**Issue by LOVE2CMOL** [al-one/hass-xiaomi-miot#1875]
### Device model / 设备型号

xiaomi.pet_waterer.002

### Component version / 插件版本

0.7.20

### HA core version / HA版本

2024.8.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

米家无线智能宠物饮水机  缺少实体 添加时能看见 但是添加后不显示
[urn:miot-spec-v2:device:pet-drinking-fountain:0000A067:xiaomi-002:1](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:pet-drinking-fountain:0000A067:xiaomi-002:1)

https://home.miot-spec.com/s/xiaomi.pet_waterer.002
https://home.miot-spec.com/spec/xiaomi.pet_waterer.002

### Entity attributes / 实体属性

```yaml
无实体
```

**Comment by al-one** [comment]
[v1版本](https://github.com/al-one/hass-xiaomi-miot/discussions/1905)会解决此问题。

**Comment by LOVE2CMOL** [comment]
已经确认
