### ISSUE TITLE
Any way to have the magnet sensors show state? 

### ISSUE THREAD

**Issue by TheLordVader** [al-one/hass-xiaomi-miot#188]
Hi, I love your work; many thanks!

Are there any way to add a magnet sensor (door/window sensor) state, e.g. open/closed? I doesn't seem to update the status in HA when the door is open, it status is as the door is permanently closed.

**Comment by al-one** [comment]
Thank you for your love and support!
However, this component has incomplete support for ble devices with high real-time requirements. One reason is that this component uses a polling method to read the device status in the Xiaomi cloud, which makes it impossible to get a real-time status. Another reason is that Mi Cloud sometimes cannot return to the correct state. You can leave your device model (found from the [HA devices](https://my.home-assistant.io/redirect/devices) or [here](https://home.miot-spec.com)), and I will optimize it as much as possible.

**Comment by TheLordVader** [comment]
Thank you for a fast reply!  The device model is
**lumi.sensor_magnet.v2**
[https://home.mi.com/baike/index.html#/detail?model=lumi.sensor_magnet.v2](url)

I would be more than happy if you can look into the issue when you have the time. Thanks!

**Comment by al-one** [comment]
Please try to open the door/window for more than one minute to check if there is any change in the entity state.
And execute the HA service: [`xiaomi_miot.get_device_data`](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.get_device_data), get the result from the notification on the left:
```yaml
service: xiaomi_miot.get_device_data
data:
  entity_id: binary_sensor.lumi_magnet_entity_id
  type: prop
  key: device_log
  time_start: 1600000000
```

**Comment by TheLordVader** [comment]
Thanks for a fast update. Unfortunately I'm not at the place where I have my sensors installed. I will be back there in one month, so it will be a delay until I have the opportunity to test again. I'll get back to you!

**Comment by al-one** [comment]
If your HA can be accessed remotely, you can execute the service via HA developer tool.

**Comment by TheLordVader** [comment]
I tried, but it ended up with this:
[https://ibb.co/b64rpBQ](url)
I couldn't execute "xiaomi_miot.get_device_data" in developer tools/Services. Please advise!

**Comment by al-one** [comment]
Domain `xiaomi_miot_raw` is not this component.
Please download this component from [releases](https://github.com/al-one/hass-xiaomi-miot/releases), or search `Xiaomi Miot Auto` in hacs.

**Comment by TheLordVader** [comment]
Sorry, installed and running now. I have been switchning between the modules and trying out...
It looks like this now:
[https://ibb.co/GcX1PCY](url)

**Comment by al-one** [comment]
> ```yaml
> service: xiaomi_miot.get_device_data
> data:
>   entity_id: binary_sensor.lumi_magnet_entity_id
>   type: prop
>   key: device_log
>   time_start: 1600000000
> ```

Enter the data and call service, then find result from notifications on the left bar.

**Comment by al-one** [comment]
Please upgrade to [master branch](https://github.com/al-one/hass-xiaomi-miot/tree/master) and try again.

**Comment by TheLordVader** [comment]
Thanks! Just tried to call service and it responded like this:
`{'code': 0, 'message': 'ok', 'result': [{'uid': '6373405080', 'time': 1632058887, 'type': 'prop', 'value': '["[1632058884,[\"event.close\",[]]]"]', 'did': 'lumi.158d000482fbb3', 'key': 'device_log'}, {'uid': '6373405080', 'time': 1632058831, 'type': 'prop', 'value': '["[1632058828,[\"event.open\",[]]]"]', 'did': 'lumi.158d000482fbb3', 'key': 'device_log'}, {'uid': '6373405080', 'time': 1631985517, 'type': 'prop', 'value': '["[1631985514,[\"event.close\",[]]]"]', 'did': 'lumi.158d000482fbb3', 'key': 'device_log'}, {'uid': '6373405080', 'time': 1631985497, 'type': 'prop', 'value': '["[1631985494,[\"event.open\",[]]]"]', 'did': 'lumi.158d000482fbb3', 'key': 'device_log'}, {'uid': '6373405080', 'time': 1631980947, 'type': 'prop', 'value': '["[1631980944,[\"event.close\",[]]]"]', 'did': 'lumi.158d000482fbb3', 'key': 'device_log'}]}`

**Comment by TheLordVader** [comment]
I am not able to be at the house where the physical installation of the magnet sensors are, before later next month. Then I can open and close the doors and try.

**Comment by al-one** [comment]
Because this component uses polling to obtain the state of the device, it cannot obtain the state in real time. For the magnet device, the component obtains the state every 15 seconds. Therefore, if the door is opened and closed within a short period of time, the state of the entity will not change. If you want to shorten this duration, you can [add custom attributes](https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui):
```yaml
# customize.yaml
binary_sensor.lumi_magnet_entity_id:
  interval_seconds: 5 # seconds
```

**Comment by TheLordVader** [comment]
Great! I will try this when I am at the other house, 15 seconds seems totally fine for my needs. Thanks for taking your time and for your great integration!!

**Comment by al-one** [comment]
Hello, does it work well ?

**Comment by TheLordVader** [comment]
Hello! Thank you so much for getting back. I will be in the cottage from wednesday next week, and then I can try. I'll let you know!

**Comment by TheLordVader** [comment]
Hi! I can confirm that all is working very well with the magnet contacts. Thank you :-)

Another question regarding lumi.sensor_wleak.aq1;  I can't see the state it just shows "unknown" in HA. It's working in the Mi Home app. [https://home.miot-spec.com/s/lumi.sensor_wleak.aq1](url)

**Comment by al-one** [comment]
For [lumi.sensor_wleak.aq1](https://home.miot-spec.com/s/lumi.sensor_wleak.aq1), it has no properties defined in [miot-spec](https://home.miot-spec.com/spec/lumi.sensor_wleak.aq1).

**Comment by al-one** [comment]
But I have fixed [lumi.sensor_wleak.aq1](https://home.miot-spec.com/s/lumi.sensor_wleak.aq1) in #150 , please make sure that the device has recent logs in MiHome.

**Comment by TheLordVader** [comment]
Working! By giving the sensor a little water it created the log file and status in HA. Great!

How can I delete a no longer in use lumi.plug.mmeu01, not visible in MiHome app..?

**Comment by al-one** [comment]
> How can I delete a no longer in use lumi.plug.mmeu01, not visible in MiHome app..?

You can change the device name to "delete" in the [HA device page](https://my.home-assistant.io/redirect/devices).

**Comment by TheLordVader** [comment]
Wow, now I learned something new and helpful. Many thanks for your great support, I really appreciate it! :-)
