### ISSUE TITLE
Failed to connect the device

### ISSUE THREAD

**Issue by makkanftw** [al-one/hass-xiaomi-miot#19]
Hi!
I'm having problems trying to get this addon to work, no matter what I try it always ends up with "Failed to connect the device".
I'm using the European (German) servers and my camera shows up fine there and I've been able to get my token etc without issues.
This is what I've added to my configuration.yaml:
![image](https://user-images.githubusercontent.com/66296537/108623683-91eeb000-7440-11eb-8f0a-d9b0adefb094.png)
Addon downloaded from HACS and then when trying to add the integration I get this and nothing more:
![image](https://user-images.githubusercontent.com/66296537/108623711-b0ed4200-7440-11eb-8c79-f75aaf2bd6de.png)
Error in the log isn't saying much either:
2021-02-21 12:29:22 DEBUG (MainThread) [custom_components.xiaomi_miot.config_flow] Xiaomi Miot config flow: {'user_input': {'name': 'xiaomi_cam_01', 'host': 'xxx', 'token': 'xxx'}, 'miio_info': None, 'errors': {'base': 'cannot_connect'}}

Is there a step I've missed? Do I need to installa anything besides the addon itself?

**Comment by al-one** [comment]
Use this shell to test your device:
```shell
pip3 install python-miio
miiocli -d device --ip 192.168.lan.ip --token xxxxxx info
```

**Comment by makkanftw** [comment]
Right so with that I got nowhere until I connected to the IoT Wifi the device is on, seems the routing might be the culprit here. Seems to work fine if I move the hassio installation to the iot network but that's not ideal. I'll keep digging, thanks for pointing me in the right direction :)
