### ISSUE TITLE
cannot import name 'DATA_CUSTOMIZE' from 'homeassistant.config'

### ISSUE THREAD

**Issue by RoyLiu04** [al-one/hass-xiaomi-miot#1900]
### Device model / 设备型号

导入设备前出现问题

### Component version / 插件版本

0.7.21

### HA core version / HA版本

2024.11.0.dev202410260227

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

添加集成时提示 无法加载配置向导: {"message":"Invalid handler specified"}无法添加集成，我注释`xiaomi_miot/__init__.py` line 30`from homeassistant.config import DATA_CUSTOMIZE`后可以添加集成，但无法成功添加设备。
取消注释上文代码之后，hass的log报错
`ImportError: cannot import name 'DATA_CUSTOMIZE' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)`

### Entity attributes / 实体属性

```yaml
无实体
```

### Home Assistant Logs / 系统日志

`2024-10-27 01:11:52.316 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.xiaomi_miot',) in /usr/src/homeassistant/homeassistant/loader.py, line 1071:`
`ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue`
`2024-10-27 01:11:52.328 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'xiaomi_miot': Unable to import component: cannot import name 'DATA_CUSTOMIZE' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)`
`File "/config/custom_components/xiaomi_miot/__init__.py", line 30, in <module>`
`File "/config/custom_components/xiaomi_miot/__init__.py", line 30, in <module>`

**Comment by al-one** [comment]
Fixed in v0.7.22
