### ISSUE TITLE
mrbond.airer.m1t 同样情况，无法上升

### ISSUE THREAD

**Issue by 0uzu0** [al-one/hass-xiaomi-miot#1918]
mrbond.airer.m1t 同样情况，无法上升，看代码已经改动很多，方法已经不适用，请帮忙

_Originally posted by @0uzu0 in https://github.com/al-one/hass-xiaomi-miot/issues/3#issuecomment-2453321840_

**Comment by al-one** [comment]
按格式[重新提交issue](https://github.com/al-one/hass-xiaomi-miot/issues/new?template=device-issue.yml)
