### ISSUE TITLE
Xiaomi Miio Airconditioning Companion MCN02 -  Error doing job: Task exception was never retrieved 

### ISSUE THREAD

**Issue by johnjoemorgan** [al-one/hass-xiaomi-miot#194]
The device is configured using Cloud.  Device is working OK with no problems.
Seeing this error in logs.  

==========

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/xiaomi_miio_airconditioningcompanionmcn02/climate.py:247
Integration: xiaomi_miio_airconditioningcompanionmcn02 (documentation, issues)
First occurred: 13:15:16 (71 occurrences)
Last logged: 16:58:08

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_miio_airconditioningcompanionmcn02/climate.py", line 266, in _async_sensor_changed
    await self._async_update_temp(new_state)
  File "/config/custom_components/xiaomi_miio_airconditioningcompanionmcn02/climate.py", line 247, in _async_update_temp
    self._current_temperature = self.hass.config.units.temperature(
AttributeError: 'NoneType' object has no attribute 'config'

**Comment by al-one** [comment]
These logs are not generated by this component.

**Comment by al-one** [comment]
Find logs like this:
```
Logger: custom_components.xiaomi_miot.*
Source: custom_components/xiaomi_miot/*.py
Integration: Xiaomi Miot Auto (documentation, issues)
```
