### ISSUE TITLE
ijai.vacuum.v2 always offline

### ISSUE THREAD

**Issue by aamrzv** [al-one/hass-xiaomi-miot#1953]
### Device model / 设备型号

ijai.vacuum.v2

### Integrated mode / 集成方式

Token

### The problem / 问题详情

Available in the app mihome, but not via integration

### Entity attributes / 实体属性

```yaml
vacuum.ijai_v2_5894_robot_cleaner
```

**Comment by al-one** [comment]
提供debug日志

**Comment by aamrzv** [comment]
It looks like the problem is with the device itself. I'll close the issue for now.
