### ISSUE TITLE
Home assistant complains about async

### ISSUE THREAD

**Issue by Jaguar222833** [al-one/hass-xiaomi-miot#1954]
Home assistant complains about async but it performs requested actions like switching on and off

Не удалось вызвать службу light/turn_on. Detected that custom integration 'xiaomi_miot' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/xiaomi_miot/__init__.py, line 1906: self.async_write_ha_state(). Please report it to the author of the 'xiaomi_miot' custom integration.

**Comment by al-one** [comment]
HA version ?
Component version ?

**Comment by al-one** [comment]
Upgrade to latest
