### ISSUE TITLE
All device become unavailables

### ISSUE THREAD

**Issue by asvel78** [al-one/hass-xiaomi-miot#1967]
### Device model / 设备型号

ijai.vacuum.v19

### Component version / 插件版本

0.7.23

### Integrated mode / 集成方式

Cloud (云端模式)

### The problem / 问题详情

After 17/11/2024 all my devices on xiaomi miot auto become unavailable.
My devices are
ijai.vacuum.v19
dmaker.fan.1c
viomi.vacuum.v8
On xiaomi home app all working properly but in home assistant all the devices become unavailable 
I tried to reload the integration without success, tried to reconfigure with my user Id - password - server location=Europe - connection mode=cloud 
But the message I receive is "No devices found under this Xiaomi account" 

### Entity attributes / 实体属性

```yaml
unavailable
```

### Home Assistant Logs / 系统日志

Logger: custom_components.xiaomi_miot.sensor
Source: custom_components/xiaomi_miot/sensor.py:647
integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 6:50:43 PM (2 occurrences)
Last logged: 6:52:03 PM

Get xiaomi message for 8195647625 failed: {'code': 0, 'message': 'SERVICETOKEN_EXPIRED'}

**Comment by al-one** [comment]
- #1956
