### ISSUE TITLE
小米小爱音箱Play 增强版 不支持

### ISSUE THREAD

**Issue by goxofy** [al-one/hass-xiaomi-miot#197]
链接为： https://item.jd.com/100012854455.html

配置完成之后，状态一直是未知
![image](https://user-images.githubusercontent.com/1695416/135062826-82865840-cefe-4b16-9001-8e196018ec32.png)

属性如下：

![image](https://user-images.githubusercontent.com/1695416/135062984-93b623b4-e057-4433-a67c-aa69f49fc999.png)

**Comment by al-one** [comment]
从实体属性可以看到部分状态属性获取报错了，这些错误均由小米云端接口返回，原因未知。
小爱音箱`media_player`实体的可操作性有限，更多的用处如播放文本和执行语音命令请参考：
- https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-885989099
- https://bbs.hassbian.com/thread-14006-1-1.html

**Comment by goxofy** [comment]
好的谢谢
