### ISSUE TITLE
Temperature sensor randomly return unavailable or NaN

### ISSUE THREAD

**Issue by MBRjun** [al-one/hass-xiaomi-miot#1973]
### Device model / 设备型号

``miaomiaoce.sensor_ht.t2``, ``cgllc.sensor_ht.dk2``

### Component version / 插件版本

0.7.24

### HA core version / HA版本

2024.10.3

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

温湿度计时不时变成 NaN（不可用）
大概每分钟出现一次，10秒左右不可用，历史记录断断续续的
目前只发现上面提及的设备受到影响，其他型号正常

### Entity attributes / 实体属性

```yaml
state_class: measurement
unit_of_measurement: °C
device_class: temperature
friendly_name: 客厅-TR 温度
supported_features: 0
```

### Home Assistant Logs / 系统日志

此错误来自自定义集成。

日志记录器: custom_components.xiaomi_miot.core.xiaomi_cloud
来源: custom_components/xiaomi_miot/core/xiaomi_cloud.py:283
集成: Xiaomi Miot Auto (文档, 问题)
首次出现: 2024年11月25日 23:52:19 (1493 次总计出现)
上次记录: 03:13:35

Request xiaomi api: user/get_user_device_data {'did': '87471380', 'key': 'device_log', 'type': 'prop', 'time_start': 1732302790, 'time_end': 1732562050, 'limit': 1} failed, response: None
Request xiaomi api: user/get_user_device_data {'did': '94504803', 'key': 'powerCost', 'type': 'store', 'time_start': 1729797190, 'time_end': 1732562050, 'limit': 31, 'group': 'day'} failed, response: None
Request xiaomi api: user/get_user_device_data {'did': '71862939', 'key': 'power_cost', 'type': 'prop_cal_day', 'time_start': 1729797193, 'time_end': 1732562053, 'limit': 31} failed, response: None
Request xiaomi api: user/get_user_device_data {'did': 'lumi.158d00028914c6', 'key': 'device_log', 'type': 'prop', 'time_start': 1732302805, 'time_end': 1732562065, 'limit': 1} failed, response: None
Request xiaomi api: user/get_user_device_data {'did': '87471380', 'key': 'device_log', 'type': 'prop', 'time_start': 1732302805, 'time_end': 1732562065, 'limit': 1} failed, response: None
此错误来自自定义集成。

日志记录器: custom_components.xiaomi_miot.core.xiaomi_cloud
来源: custom_components/xiaomi_miot/core/xiaomi_cloud.py:246
集成: Xiaomi Miot Auto (文档, 问题)
首次出现: 2024年11月25日 23:52:19 (875 次总计出现)
上次记录: 03:13:20

Request xiaomi api: miotspec/prop/get {'params': [{'did': '285242428', 'siid': 2, 'piid': 1}]} failed, response: None
Request xiaomi api: miotspec/prop/get {'params': [{'did': 'blt.3.1g8189000ck00', 'siid': 2, 'piid': 1}, {'did': 'blt.3.1g8189000ck00', 'siid': 2, 'piid': 2}, {'did': 'blt.3.1g8189000ck00', 'siid': 3, 'piid': 1}]} failed, response: None
Request xiaomi api: miotspec/prop/get {'params': [{'did': 'blt.3.1g81805t4cg00', 'siid': 2, 'piid': 1}, {'did': 'blt.3.1g81805t4cg00', 'siid': 2, 'piid': 2}, {'did': 'blt.3.1g81805t4cg00', 'siid': 3, 'piid': 1}]} failed, response: None
Request xiaomi api: miotspec/prop/get {'params': [{'did': 'blt.3.1fqjjbj0ok800', 'siid': 2, 'piid': 1}, {'did': 'blt.3.1fqjjbj0ok800', 'siid': 2, 'piid': 2}, {'did': 'blt.3.1fqjjbj0ok800', 'siid': 2, 'piid': 3}]} failed, response: None
Request xiaomi api: miotspec/prop/get {'params': [{'did': 'blt.3.1fqjhr90gk800', 'siid': 2, 'piid': 1}, {'did': 'blt.3.1fqjhr90gk800', 'siid': 2, 'piid': 2}, {'did': 'blt.3.1fqjhr90gk800', 'siid': 2, 'piid': 3}]} failed, response: None

**Comment by MBRjun** [comment]
![IMG_7543](https://github.com/user-attachments/assets/fef38e6e-c576-4b5b-97c1-39c08aecfcda)

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/500#unreach

**Comment by MBRjun** [comment]
fixed by disabling IPv6 network.

不过有没有办法 只有这个插件不使用IPv6 系统內其他程序仍然可以用v6
