### ISSUE TITLE
输入小米的密码和账号后，提交，一直在转圈，转好几分钟也登陆不上。

### ISSUE THREAD

**Issue by redhatme** [al-one/hass-xiaomi-miot#1985]
1，HA和xiaomi auto都是最新，插件也重新安装过
2，dns也都改过
3，ping  account.xiaomi.com也能ping通
4，整个主机，ha服务，重启过多次。

一直转圈，一直转，也没有报错。
还有什么排查的方向吗？

**Comment by redhatme** [comment]
gateway3这个插件登录账号的时候，也是登录不上小米的账号。应该不是插件的问题。 估计还是网络问题，具体怎么排查？

**Comment by al-one** [comment]
在HA配置中关闭IPv6

**Comment by redhatme** [comment]
也是关闭了，静态的时候，顺手把Ipv6关闭了

**Comment by whiterober** [comment]
我也是这种情况，目前没发现解决方案，直接就是登不上

**Comment by xceszzy** [comment]
同问题。 偶尔能登录，但是过会儿 灯就离线了。

**Comment by xceszzy** [comment]
终于找到问题关键了。 楼主，就是网络问题哦。
我开始往ipv6 方向排查，想禁用，但是找不到禁用的入口（haos 设置中无效）。
后来，把 ipv4 改成自动获取，ipv6 禁用，即可。
开始一直转圈，是因为我把 ip 改成静态了。如果想要静态，建议到路由中去绑定 ip=mac。

**Comment by redhatme** [comment]
好的，多谢

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月08日 10:22 |
| 收件人 | al-one/hass-xiaomi-miot ***@***.***> |
| 抄送人 | redhatme ***@***.***>,
State ***@***.***> |
| 主题 | Re: [al-one/hass-xiaomi-miot] 输入小米的密码和账号后，提交，一直在转圈，转好几分钟也登陆不上。 (Issue #1985) |

终于找到问题关键了。 楼主，就是网络问题哦。
我开始往ipv6 方向排查，想禁用，但是找不到禁用的入口（haos 设置中无效）。
后来，把 ipv4 改成自动获取，ipv6 禁用，即可。
开始一直转圈，是因为我把 ip 改成静态了。如果想要静态，建议到路由中去绑定 ip=mac。
