### ISSUE TITLE
Xiaomi roborock m1s most entities disappear since few weeks 

### ISSUE THREAD

**Issue by Cook23** [al-one/hass-xiaomi-miot#1994]
### Device model / 设备型号

roborock vacuum m1s

### Component version / 插件版本

1.0.1 and previous

### HA core version / HA版本

2024.11.4 

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Integration don't provide entities anymore except battery percentage and battery charging status trough lan. Vacuum entity is not provided anymore. Trough cloud all is fine. Problems appeared 2 or 3 weeks before, I patiently wait for an update but the last update don't solve the issue. I have many m1s, all fails simultaneously.

### Entity attributes / 实体属性

```yaml
All entities except sensor.xxx_battery_level sensor.xxx_status sensor.xxx_info not provided anymore by integration. The entities provided works fine showing the real state.
```

**Comment by Biegnik** [comment]
The same situation

**Comment by dangerdanik** [comment]
+1 The same situation. Rolled back to version - 0.7.25.

**Comment by Cook23** [comment]
Problem solved with last version.
