### ISSUE TITLE
can't find cloud enable setting

### ISSUE THREAD

**Issue by omerbitas** [al-one/hass-xiaomi-miot#20]
Hi
Im trying to add a chuangmi.camera.ipc016 camera using the integration.
I'm trying to follow the instructions on the code page.
I've managed to add miot cloud for entity using the customization page.
It than says to "Enabled miot cloud for device: Configuration > Integrations > Xiaomi Miot Auto > Options > Enable miot cloud"
but I cannot see this option anywhere. is this crucial for camera operation? 
Currently I got it to look like this:
![image](https://user-images.githubusercontent.com/49685964/108633586-bae16600-747d-11eb-8fd2-3b6697442012.png)
But getting this when I'm trying to see an image:
![image](https://user-images.githubusercontent.com/49685964/108633618-da788e80-747d-11eb-9180-91403c599e44.png)

only miot error from log I can see is this:
`2021-02-21 19:48:35 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.miot_camera_control is taking over 10 seconds
`

what can be the cause?
where can I enable "miot cloud for device" if needed?
where can I find the did value? is it manetory?

thanks,

**Comment by al-one** [comment]
`Enabled miot cloud for device` need upgrade to last commit of [master](https://github.com/al-one/hass-xiaomi-miot/tree/master).

Or you can goto `Configuration > Customize > Select Entity > Add Other Attribute`

**Comment by omerbitas** [comment]
Thanks for the answer.
On the entity level is enough?
![Screenshot_20210222-071808__01](https://user-images.githubusercontent.com/49685964/108665811-789c4100-74de-11eb-8a45-8f14709f9c27.jpg)
And what about the other settings? Any idea why not working?

**Comment by al-one** [comment]
Make sure your `customize.yaml` include by `configuration.yaml`.

```yaml
# configuration.yaml
homeassistant:
  customize: !include customize.yaml
```

Check entity state attributes has `miot_cloud: "true"` in `Developer tools > State`.

**Comment by omerbitas** [comment]
Yes, got both:
![Screenshot_20210222-074352__01](https://user-images.githubusercontent.com/49685964/108667428-dda56600-74e1-11eb-99df-6436d6ff6bfe.jpg)
![Screenshot_20210222-074326](https://user-images.githubusercontent.com/49685964/108667436-e138ed00-74e1-11eb-9deb-0ddb30e40b8c.jpg)

**Comment by al-one** [comment]
`chuangmi.camera.ipc016` does not support.

See https://github.com/al-one/hass-xiaomi-miot/issues/11#issuecomment-770642627 https://github.com/al-one/hass-xiaomi-miot/issues/11#issuecomment-774625999 #15 .
