### ISSUE TITLE
宠物喂食器不能用了，mmgg.feeder.petfeeder

### ISSUE THREAD

**Issue by ocerot** [al-one/hass-xiaomi-miot#201]
之前还可以用，手动出量，升级后设备变未知了，重新添加也不行，另外云米洗衣机viomi.washer.v24切换模式，温度，转速等都不能设定了

**Comment by al-one** [comment]
请提供该设备实体的[状态属性](https://my.home-assistant.io/redirect/developer_states)。

**Comment by ocerot** [comment]
model: mmgg.feeder.petfeeder
lan_ip: 192.168.1.92
mac_address: 54:48:xx:xx:xx:xx 
firmware_version: 2.1.3
hardware_version: ''
entity_class: MiotSensorEntity
miot_type: urn:miot-spec-v2:device:pet-feeder:0000A06C:mmgg-petfeeder:1
state_property: feeding_measure
state_updater: none
friendly_name: 宠物喂食器 Pet Feeder Feeding Measure

**Comment by al-one** [comment]
该型号[mmgg.feeder.petfeeder](https://home.miot-spec.com/s/mmgg.feeder.petfeeder)喂食器的[miot-spec](https://home.miot-spec.com/spec/mmgg.feeder.petfeeder)中未定义任何可读取的属性，因此状态为未知。
请检查该设备下是否还有个开关实体，打开该实体可以实现投喂。

**Comment by ocerot** [comment]
restored: true
supported_features: 0
friendly_name: 宠物喂食器 Pet Feeder Feeding Measure pet_feeder.pet_food_out
icon: mdi:shaker

另一个实体也是灰色，状态unavailable

**Comment by al-one** [comment]
请尝试升级到master后再试，如果投喂switch实体仍然不可用，请检查有无报错[日志](https://my.home-assistant.io/redirect/logs)。

**Comment by ocerot** [comment]
请问如何升级到master版本，只看到0.45版

**Comment by al-one** [comment]
如果是HACS可依次点击：HACS > 集成 > 找到`Xiaomi Miot Auto` > 左边三个点 > 重新安装 > ☑️显示测试版 > 选择`master` > 安装
或者直接通过GitHub下载：https://github.com/al-one/hass-xiaomi-miot/archive/refs/heads/master.zip

**Comment by al-one** [comment]
@ChristianSwift  请确保你是最新的v0.6.4版本。

**Comment by ChristianSwift** [comment]
> @ChristianSwift 请确保你是最新的v0.6.4版本。

你好，我这个确认是0.6.4版本  
<img width="1909" alt="image" src="https://user-images.githubusercontent.com/20925565/168727308-d8a9b363-cf97-444c-adf3-64cc13e26ee9.png">  
<img width="1581" alt="image" src="https://user-images.githubusercontent.com/20925565/168727359-c86543a8-7391-497f-84dc-a315728f3d28.png">
