### ISSUE TITLE
HACS提示无法安装，HA版本 2024.11.3

### ISSUE THREAD

**Issue by zhaosk** [al-one/hass-xiaomi-miot#2011]
**Home Assistant** Core 2024.11.3版本，HACS下安装提示如下，无法安装

---------
**HACS**

Xiaomi Miot Auto

Commit will be downloaded

When downloaded, this will be located in '/config/custom_components/xiaomi_miot'
Remember that you need to restart Home Assistant before changes to integrations (custom_components) are applied.

The version for this integration can not be used with HACS.

**Comment by al-one** [comment]
网络问题，可以尝试[HACS极速版](https://hacs.vip)

**Comment by zhaosk** [comment]
实际测试，HA更新至24.12即可
