### ISSUE TITLE
Mi Crossover Range Hood S1 无法控制！

### ISSUE THREAD

**Issue by fanyan1026** [al-one/hass-xiaomi-miot#2015]
Mi Crossover Range Hood S1 添加后实体2个开关无法使用，不能控制，然后会自动掉线（实际没有掉线），苹果家庭里面加入后也是未响应状态！

**Comment by al-one** [comment]
按[格式](https://github.com/al-one/hass-xiaomi-miot/issues/new?template=device-issue.yml)重新提交。
