### ISSUE TITLE
Miwifi 2.5GHz connection for Mobile phone not available anymore

### ISSUE THREAD

**Issue by andrewlimkk** [al-one/hass-xiaomi-miot#2018]
### Device model / 设备型号

MiWiFi, Samsung S22+, Samsung S23 Ultra

### Component version / 插件版本

1.0.1

### HA core version / HA版本

2024.12.0

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

last time, if connected to Miwifi 2.4G or 5G, it could be detected as Home or away. Now, it only recognizes 5G, but 2.5G it said 
This entity is no longer being provided by the miwifi integration. If the entity is no longer in use, delete it in settings.

### Entity attributes / 实体属性

```yaml
device_tracker.miwifi_aa_bb_cc_dd_ee_ff
![image](https://github.com/user-attachments/assets/851b7633-de84-4959-b69f-98b937549b3a)
```

### Home Assistant Logs / 系统日志

Logger: homeassistant.components.device_tracker
Source: helpers/entity_platform.py:773
integration: Device Tracker (documentation, issues)
First occurred: 5 December 2024 at 11:53:44 (2 occurrences)
Last logged: 5 December 2024 at 13:20:37

Platform miwifi does not generate unique IDs. ID miwifi-AA:BB:DD:DD:DD:DDis already used by device_tracker.miwifi_AA_AA_BB_BB_CC_CC - ignoring device_tracker.miwifi_AA_BB_CC_DD_EE_FF # <== this is N/A now
Platform miwifi does not generate unique IDs. ID miwifi-D8:43:AE:8D:6A:82 is already used by device_tracker.miwifi_DD_DD_EE_EE_FF_FF - ignoring device_tracker.miwifi_FF_EE_DD_CC_BB_AA # <== this is N/A now

**Comment by al-one** [comment]
Not this component.
