### ISSUE TITLE
Xiaomi Fish Tank - feed unavailable

### ISSUE THREAD

**Issue by Aliskin-Papa** [al-one/hass-xiaomi-miot#2025]
After last update 1.0.2 in the Fish Tank Feed = unavailable

**Comment by al-one** [comment]
Migrate  to  another  entity.

**Comment by daichidan** [comment]
@al-one which entity?

**Comment by ronechang0417** [comment]
Same problem, also some entity can't be controlled.

**Comment by al-one** [comment]
Try 1.0.4

**Comment by ronechang0417** [comment]
I already tried 1.0.4, and I switch the feeding button to 1/2/3, but still not working. I attached my debug log file, please help it.
[home-assistant_xiaomi_miot_2024-12-12T15-23-59.656Z.log](https://github.com/user-attachments/files/18113838/home-assistant_xiaomi_miot_2024-12-12T15-23-59.656Z.log)

**Comment by three-m** [comment]
Same problem, when use select entity - have error 'Unable to recover failed command'. (miio.exceptions.RecoverableError: {'code': -9999, 'message': 'user ack timeout'})

**Comment by daichidan** [comment]
Looks like with 1.0.5 it works. Use new select entity select.hfjh_m100_7cde_pet_food_out . Thanks for fixing!
