### ISSUE TITLE
问题反馈：小沐马桶盖显示错误

### ISSUE THREAD

**Issue by zraxx** [al-one/hass-xiaomi-miot#2034]
滤芯已用时间，应为滤芯剩余天数，单位hours应改为“天”![Screenshot_2024-12-07-09-47-19-930_io.homeassistant.companion.android.png](https://github.com/user-attachments/assets/13ead7d5-958e-42f7-9b80-27b16863ecda)

![Screenshot_2024-12-07-10-40-07-502_io.homeassistant.companion.android.png](https://github.com/user-attachments/assets/1b87684f-b28a-4b57-945a-5c8d7ea76031)

**Comment by al-one** [comment]
v1.0.5 按厂商定义的规格显示为小时
