### ISSUE TITLE
绘睡水暖毯无法接入

### ISSUE THREAD

**Issue by Young1223** [al-one/hass-xiaomi-miot#2044]
### Device model / 设备型号

[isleep.blanket.hs2401](https://home.miot-spec.com/s/isleep.blanket.hs2401)

### Component version / 插件版本

1.0.2

### HA core version / HA版本

2024.12.0

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

通过自动模式在设备列表勾选了水暖毯，但是设备无法接入，通过局域网模式接入，所有实体都不可用

### Entity attributes / 实体属性

```yaml
所有实体不可用
```

### Home Assistant Logs / 系统日志

系统日志里面没有相关信息，水暖毯设备的信息如下：

Info
水暖垫
Model
isleep.blanket.hs2401
Did
App link
Miot type
urn:miot-spec-v2:device:electric-blanket:0000A069:isleep-hs2401:1
Available
true
Home room
Updater
none
Updated at
Converters
info, electric_blanket.on, ambient_light.on, ambient_light.brightness, electric_blanket.fault, electric_blanket.temperature, electric_blanket.water_level, custom.low_temperature, custom.screen_switch, custom.key_tone, custom.automatic_shutdown, custom.fast_heating, target_temperature-2-4, countdown.countdown_time, electric_blanket.mode, custom.sleep_level
Customizes
sensor_properties: fault,temperature,water_level
select_properties: mode,sleep_level
number_properties: target_temperature,countdown_time
switch_properties: low_temperature,screen_switch,key_tone,automatic_shutdown,fast_heating

**Comment by al-one** [comment]
尝试master分支。
```bash
wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
```

**Comment by Young1223** [comment]
> 尝试master分支。
> 
> ```shell
> wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
> ```

可以了，感谢
