### ISSUE TITLE
FOWAD 空调温控器2

### ISSUE THREAD

**Issue by ympchuan** [al-one/hass-xiaomi-miot#2046]
### Device model / 设备型号

[fawad.aircondition.3010](https://home.miot-spec.com/s/fawad.aircondition.3010)

### Component version / 插件版本

1.0.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Air Conditioner Switch Status 无效
<img width="663" alt="截屏2024-12-09 18 01 55" src="https://github.com/user-attachments/assets/82137462-48ec-46f3-b14d-a05a01488931">

### Entity attributes / 实体属性

```yaml
Air Conditioner Switch Status 无效
```

**Comment by ympchuan** [comment]
**button.fawad_3010_info** 

nfo: 内厅空调
model: fawad.aircondition.3010
did: 555892511
mac: 68:AB:BC:92:9C:31
lan_ip: 192.168.31.35
app_link: mihome://device?uid=6123458&did=551234511
miot_type: urn:miot-spec-v2:device:air-conditioner:0000A004:fawad-3010:1
available: true
home_room: 新风空调地暖
icon: mdi:information
updater: local
updated_at: 2024-12-11 16:59:29.910784+08:00
converters: info, environment.temperature, thermostat.screen_lock_enable, thermostat.beep_opration_enable, thermostat.dark_night_display, thermostat.show_tempreture_poff, thermostat.power_hold, thermostat.fannostop, thermostat.count_down, thermostat.antifreeze_set, thermostat.tempreture_delta, thermostat.heat_type
customizes: 
sensor_properties: electricity.electricity
switch_properties: >-
  screen_lock_enable,beep_opration_enable,dark_night_display,show_tempreture_poff,power_hold,fannostop
select_properties: antifreeze_set,tempreture_delta,heat_type
number_properties: count_down
fan_services: air_fresh
chunk_properties: 1
exclude_miot_properties: >-
  device_info,ontime_dark,offtime_dark,monday_timer,tuesday_timer,wednesday_timer,thursday_timer,friday_timer,saturday_timer,sunday_timer

thermostat.screen_lock_enable: false
thermostat.beep_opration_enable: true
thermostat.dark_night_display: false
thermostat.show_tempreture_poff: true
thermostat.power_hold: true
thermostat.antifreeze_set: 0
thermostat.tempreture_delta: 1
thermostat.fannostop: false
thermostat.heat_type: 2
thermostat.count_down: 0
environment.temperature: 21.1823
thermostat.schedule_enable: false
thermostat.factory_settings: false
fan_control.fan_level: 1
air_conditioner.on: false
air_conditioner.mode: 1
air_conditioner.fault: 0
target_temperature-2-4: 23
miot_error: Unable to discover the device 192.168.31.35
device_class: update
friendly_name:  内厅空调 信息

**climate.fawad_3010_air_conditioner**

hvac_modes: cool, heat, fan_only, auto, off
min_temp: 5
max_temp: 35
target_temp_step: 0.5
fan_modes: auto, low, medium, high
current_temperature: 21.2
temperature: 23
fan_mode: low
hvac_action: off
thermostat.screen_lock_enable: false
thermostat.beep_opration_enable: true
thermostat.dark_night_display: false
thermostat.schedule_enable: false
thermostat.show_tempreture_poff: true
thermostat.factory_settings: false
thermostat.power_hold: true
thermostat.antifreeze_set: 0
thermostat.tempreture_delta: 1
thermostat.fannostop: false
thermostat.heat_type: 2
thermostat.count_down: 0
environment.temperature: 21.2029
fan_control.fan_level: 1
air_conditioner.on: false
air_conditioner.mode: 1
air_conditioner.fault: 0
target_temperature-2-4: 23
state_updater: local
friendly_name: 内厅空调 空调
supported_features: 393

**switch.fawad_3010_switch_status**

restored: true
icon: mdi:power
friendly_name: 内厅空调 Air Conditioner Switch Status
supported_features: 0

**Comment by al-one** [comment]
v1.0.5已修复
