### ISSUE TITLE
Xioami FishTank feeding_measure become unavailable 

### ISSUE THREAD

**Issue by Dex077** [al-one/hass-xiaomi-miot#2059]
### Device model / 设备型号

[hfjh.fishbowl.m100](https://home.miot-spec.com/s/hfjh.fishbowl.m100)

### Component version / 插件版本

1.0.4

### HA core version / HA版本

2024.12.12

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Hi, after update entity switch.hfjh_m100_c280_feeding_measure become unavailable. I like your integration. My Fisht ank fully controlled through HA. Thanks

### Entity attributes / 实体属性

```yaml
switch.hfjh_m100_c280_feeding_measure unavailable
```

**Comment by Dex077** [comment]
Pet Food doesn't work either. Add my log file. Thanks. [error_log_miot.txt](https://github.com/user-attachments/files/18117701/error_log_miot.txt)

**Comment by al-one** [comment]
Try master branch.
```bash
wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
```

**Comment by Kubakh** [comment]
> Try master branch.
> 
> ```shell
> wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
> ```

not work ((

**Comment by Kubakh** [comment]
> ```shell
> wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
> ```

Not work ([
[home-assistant_xiaomi_miot_2024-12-13T14-51-32.896Z.log](https://github.com/user-attachments/files/18127820/home-assistant_xiaomi_miot_2024-12-13T14-51-32.896Z.log)
](url)

**Comment by al-one** [comment]
Try master again.

**Comment by Kubakh** [comment]
> Try master again.

THIS WORKED!!!!!!!!!!!!!!!!!!!

**Comment by Dex077** [comment]
Thanks, Downloaded again through HACS, I was lazy ro use CLI.

**Comment by Dex077** [comment]
Everything work now -))) Thanks 😊
