### ISSUE TITLE
functools.partial will be a method descriptor in future

### ISSUE THREAD

**Issue by OlegPitsenko** [al-one/hass-xiaomi-miot#2060]
/srv/homeassistant/lib/python3.13/site-packages/miio/miot_device.py:23: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior Bool = partial(_str2bool)

**Comment by al-one** [comment]
- https://github.com/home-assistant/core/issues/132902#issuecomment-2539442277
