### ISSUE TITLE
小米智能插座功率显示错误

### ISSUE THREAD

**Issue by invoker-karl** [al-one/hass-xiaomi-miot#2064]
设备号：chuangmi.plug.212a01
小米智能插座显示功率值为实际的0.01倍。 比如说，实际应是100W，但是显示是1W，且显示为（单位为0.01W）

改进方法：device_customizes.py文件中把213行
'chuangmi.plug.*:electric_power': {
        'value_ratio': 0.01,

改为
'chuangmi.plug.*:electric_power': {
        'value_ratio': 1,

这样重启HA后，功率显示正常了

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/534#issuecomment-1105475576
