### ISSUE TITLE
集成的红外设备不可用

### ISSUE THREAD

**Issue by sephrioth** [al-one/hass-xiaomi-miot#2066]
### Device model / 设备型号

 xiaomi.wifispeaker.l05c

### Component version / 插件版本

1.0.4

### HA core version / HA版本

2024.12.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

之前在小米小爱音箱增强版中集成的红外遥控设备在插件更新后不可用， 包括对应的 remote.xiaomi_ai_speaker entity也变为了不可用状态

### Entity attributes / 实体属性

```yaml
select.remote_yamaha_ysp_soundbar
select.remote_hdmi_switcher
remote.xiaomi_ai_speaker

都是 unavailable
```

### Home Assistant Logs / 系统日志

Yamaha Soundbar(miir.remote.ir01): Device has no spec
HDMI Switcher(miir.remote.ir01): Device has no spec

**Comment by ZDZX-T** [comment]
![image](https://github.com/user-attachments/assets/12af96ff-3a3d-4552-804e-9160f395ac70)
我有同样的问题。
回退为1.0.3后一切正常

**Comment by sephrioth** [comment]
@ZDZX-T 你的HA版本多少？ 我回退插件到1.0.3还是一样的问题..

**Comment by ZDZX-T** [comment]
> @ZDZX-T 你的HA版本多少？ 我回退插件到1.0.3还是一样的问题..

core是2024.12.3，目前我升级了1.0.5的集成，没有出现问题了

**Comment by sephrioth** [comment]
同升级到 1.0.5 后问题解决。
