### ISSUE TITLE
Error: 无法加载配置向导: 500 Internal Server Error Server got itself in trouble 

### ISSUE THREAD

**Issue by konglingboy** [al-one/hass-xiaomi-miot#2067]
Component version / 插件版本
1.0.4

HA core version / HA版本
2024.11.3

Integrated mode / 集成方式
Automatic(自动模式)

设置->设备与服务->Xiaomi Miot Auto->配置，Get Error message：
无法加载配置向导: 500 Internal Server Error Server got itself in trouble

**Comment by noxetlux** [comment]
+1
更新完就没法配置了……

**Comment by al-one** [comment]
Upgrade to master branch.
```
wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
```

**Comment by konglingboy** [comment]
@ManiaciaChao The Assist seems to not function properly after upgrading to the new version (HA 2024.12.x),  A rollback to version 2024.11.x is necessary.
