### ISSUE TITLE
home.miot-spec.com is down.

### ISSUE THREAD

**Issue by vevsvevs** [al-one/hass-xiaomi-miot#208]
Is it intentional, is there any hope to get it back soon? Btw, thank you very much for all your efforts!

**Comment by al-one** [comment]
This website is currently hosted on my Raspberry Pi. Recently, my home network suffered a failure. It should be restored today. Later, I will host the website on a cloud server.
Thank you for your support !

**Comment by vevsvevs** [comment]
@al-one 500 Server Error :(

**Comment by vevsvevs** [comment]
@al-one and once again - 500 Server Error.
