### ISSUE TITLE
实体状态更新频率异常/状态不自动更新 (Entity/state does not refresh automatically)

### ISSUE THREAD

**Issue by home110120** [al-one/hass-xiaomi-miot#2084]
12月7号白天开始（更新1.0或者1.01前后），状态刷新异常，状态数据只会在系统重启或者integration reload的时候才会刷新一次，否则一直也不会有state更新，涉及多个device和entity。
![image](https://github.com/user-attachments/assets/90c50a20-542a-4655-8969-2f48281ecc32)

**Comment by Kai-Cloud** [comment]
12月15日更新至1.0.5后，遇到相同问题！
![image](https://github.com/user-attachments/assets/bd43d2e3-52de-46aa-af9b-cc4a67906d16)

**Comment by al-one** [comment]
HA 版本多少

**Comment by Kai-Cloud** [comment]
> HA 版本多少

Core 2024.5.1
Frontend 20240501.0

**Comment by home110120** [comment]
Core
2024.12.3
Supervisor
2024.11.4
Operating System
14.0
Frontend
20241127.8

**Comment by al-one** [comment]
尝试master分支。
```bash
wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
```

**Comment by Kai-Cloud** [comment]
> HA 版本多少

更新到Core 2024.12.3后，exclude再include所有小米设备，多数实体恢复正常更新频率！感谢！

**Comment by home110120** [comment]
尝试exclude和include无变化

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by YonghuiKing** [comment]
同样的问题，大量设备仅在重启的时候更新数据，或者是在诊断里点击“按下”,才会更新，否则无论几天都不会更新一下数据

**Comment by home110120** [comment]
@al-one 召唤大佬，还有什么想法吗

**Comment by al-one** [comment]
master

**Comment by home110120** [comment]
1.0.6还是不work。。。
![image](https://github.com/user-attachments/assets/9f0e5e02-18e5-4b4f-8af5-b6549057739b)

**Comment by home110120** [comment]
看了一下来自其他integration的state也有类似的问题，recorder没有发现有意义的log。但是问题在我手动重启pgsql后莫名其妙就好了。我的HA和pgsql实体都是每天重启两次的，但是这个问题持续了11天，不确定具体发生了什么。。我这就把issue关掉了。

**Comment by home110120** [comment]
@YonghuiKing Hi，我在HA Core开了一个issue，不知道你的问题有没有解决，如果没有我们可以在那边接着沟通。
https://github.com/home-assistant/core/issues/133639
