### ISSUE TITLE
米家台灯1s 在插件更新1.0.x版本后没有brightness亮度属性

### ISSUE THREAD

**Issue by kimberxu** [al-one/hass-xiaomi-miot#2086]
### Device model / 设备型号

yeelink.light.lamp4 

### Component version / 插件版本

1.0.5

### HA core version / HA版本

2024.12.0

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

米家台灯1s 在插件更新v1.0.x版本后，没有brightness亮度属性，而在v0.7.x版本中是有的。希望能加回来。

v0.7.24
![image](https://github.com/user-attachments/assets/d377b6bb-9e3e-4142-a5be-d1db4a146ebb)

### Entity attributes / 实体属性

```yaml
light.yeelink_lamp4_2cb6_light
brightness
```

**Comment by al-one** [comment]
尝试master分支。
```bash
wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
```

**Comment by fixedid** [comment]
不知道是否有关
更新到1.0.x版本后 可调亮度的灯在HA手动调亮度 调完也会在HA显示亮度
但只要重启HA后 灯就只显示开/关 不会显示亮度 需要手动调亮度才显示  0.7.x版本是没这个问题的

**Comment by kimberxu** [comment]
> 尝试master分支。
> 
> ```shell
> wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
> ```

执行这行命令并重启后
台灯的属性里出现“brightness”，但是数值一直是null
![image](https://github.com/user-attachments/assets/a40e50fb-1155-47a7-8ef9-0dd5f56d111d)

**Comment by al-one** [comment]
master 分支已修复

**Comment by kimberxu** [comment]
更新最新master 分支后，亮度正常显示了
