### ISSUE TITLE
空调缺少实体

### ISSUE THREAD

**Issue by xtjun** [al-one/hass-xiaomi-miot#2087]
### Device model / 设备型号

[xiaomi.airc.r09h00](https://home.miot-spec.com/s/xiaomi.airc.r09h00)

### Component version / 插件版本

1.0.5

### HA core version / HA版本

2024.12.1

### Integrated mode / 集成方式

Local (本地模式)

### The problem / 问题详情

最近米家巨省电空调（xiaomi.airc.r09h00）设备不可用，今天更新了插件1.0.5版本，设备可用了，但是缺少了很多的控制实体，只剩下空调实体了，形如睡眠模式、节能模式开光灯控制实体都没有了，ha控制台未见报错
![image](https://github.com/user-attachments/assets/0e220ed3-682e-40c7-9f82-6d361402702d)
之前的实体参见另一台空调如下图
![image](https://github.com/user-attachments/assets/7d5afa86-6de4-4189-8904-41a486b0be49)

### Entity attributes / 实体属性

```yaml
无实体
```

### Home Assistant Logs / 系统日志

未见有相关日志

**Comment by al-one** [comment]
尝试master分支。
```bash
wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
```

**Comment by xtjun** [comment]
更新1.0.6完美解决
