### ISSUE TITLE
chuangmi.plug.hmi206 issues since upgrade to 1.0.4

### ISSUE THREAD

**Issue by BoxedIns** [al-one/hass-xiaomi-miot#2088]
Hi,

After yesterday's upgrade of Xiaomi Miot Auto to 1.0.5 the chuangmi.plug.hmi206  integration is broken. It takes much more time dor command to process, the switch status is not always cought by Home Assistant propely, automations fail, temperature readings are bogus (58 degrees centigrade displayed when ambient temperature is 23) and LED config is unavailable.

Best regards.

**Comment by MonsterVic** [comment]
I confirm, same issue, after upgrading to 1.0.5. actually I lost all chuangmi.plug.hmi206 devices all become unavailable, even reconfiguration said successful they stayed unavaillable.   Reverted back to 1.0.3, and all came back to life.

**Comment by al-one** [comment]
Try master branch.
```bash
wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
```

**Comment by al-one** [comment]
- Info entitty attributes
- Debug logs

**Comment by BoxedIns** [comment]
Hello @al-one,

I am not sure if this is what you wanted, but the entities are:
```
light.chuangmi_hmi206_c224_switch_status
button.chuangmi_hmi206_c224_info
switch.chuangmi_hmi206_c224_switch
sensor.chuangmi_hmi206_c224_temperature
```
And debug log is attached.
[home-assistant_xiaomi_miot_2024-12-18T12-45-47.516Z.log](https://github.com/user-attachments/files/18181474/home-assistant_xiaomi_miot_2024-12-18T12-45-47.516Z.log)
Thanks!

**Comment by BoxedIns** [comment]
Hello,

Just an update, the 1.0.6 makes it much better. The switch operation is back to normal. The temp reading is still a bit off (41 degrees with ambient temp of 24) but I cannot say it was any better previously.

Best regards.

**Comment by MonsterVic** [comment]
I confirm too 1.0.6 is working
