### ISSUE TITLE
Unable to parse message payload: Mi Smart AC with Ventilation (Elite Edition 1.5HP) Air Conditioner

### ISSUE THREAD

**Issue by iZonex** [al-one/hass-xiaomi-miot#209]
**System Info**
`System Health

Version | core-2021.10.4
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 5.11.0-37-generic
CPU Architecture | x86_64
Timezone | Europe/Kiev

Xiaomi Miot Auto

Component Version	0.4.5
Reach Xiaomi API Server	ok
Reach MIoT-Spec Server	ok
Logged Accounts	1
Total MiHome Devices	11
`

**Exception**

` This error originated from a custom integration.
Logger: custom_components.xiaomi_miot.climate
Source: custom_components/xiaomi_miot/__init__.py:1037
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 13:24:41 (18 occurrences)
Last logged: 13:32:35

Mi Smart AC with Ventilation (Elite Edition 1.5HP) Air Conditioner: Got MiioException while fetching the state: Unable to parse message payload, mapping: {'air_conditioner.on': {'siid': 2, 'piid': 1}, 'air_conditioner.mode': {'siid': 2, 'piid': 2}, 'air_conditioner.fault': {'siid': 2, 'piid': 3}, 'target_temperature-2-4': {'siid': 2, 'piid': 4}, 'air_conditioner.eco': {'siid': 2, 'piid': 7}, 'air_conditioner.heater': {'siid': 2, 'piid': 9}, 'air_conditioner.dryer': {'siid': 2, 'piid': 10}, 'air_conditioner.sleep_mode': {'siid': 2, 'piid': 11}, 'air_conditioner.soft_wind': {'siid': 2, 'piid': 12}, 'air_conditioner.uv': {'siid': 2, 'piid': 13}, 'air_conditioner.target_humidity': {'siid': 2, 'piid': 14}, 'screen_show.screen_version': {'siid': 17, 'piid': 1}, 'single_smart_scene.auto_cooling': {'siid': 16, 'piid': 1}, 'automatic_heating-16-2': {'siid': 16, 'piid': 2}, 'single_smart_scene.auto_dry': {'siid': 16, 'piid': 3}, 'auto_air_fresh-16-5': {'siid': 16, 'piid': 5}, 'freshair_dark_switch-16-8': {'siid': 16, 'piid': 8}, 'single_smart_scene.sleep_soft': {'siid': 16, 'piid': 9}, 'filter_life': {'siid': 15, 'piid': 1}, 'flag_bit.fault_value': {'siid': 13, 'piid': 1}, 'machine_state.indoor_pipe_temp': {'siid': 12, 'piid': 1}, 'machine_state.indoor_fan_speed': {'siid': 12, 'piid': 3}, 'real_heater_switch-12-4': {'siid': 12, 'piid': 4}, 'realindoor_fan_lever-12-5': {'siid': 12, 'piid': 5}, 'machine_state.outdoor_temp': {'siid': 12, 'piid': 7}, 'machine_state.outdoor_pipe_temp': {'siid': 12, 'piid': 8}, 'outdoor_exhaust_temp-12-9': {'siid': 12, 'piid': 9}, 'machine_state.outdoor_fan_lever': {'siid': 12, 'piid': 10}, 'compressor_frequency-12-11': {'siid': 12, 'piid': 11}, 'fourway_valve_switch-12-12': {'siid': 12, 'piid': 12}, 'machine_state.outdoor_m_current': {'siid': 12, 'piid': 13}, 'machine_state.outdoor_m_voltage': {'siid': 12, 'piid': 14}, 'machine_state.expansion_valve': {'siid': 12, 'piid': 15}, 'longitude_latitude-12-16': {'siid': 12, 'piid': 16}, 'air_fresh_fan_speed-12-17': {'siid': 12, 'piid': 17}, 'new_wind_fan_lever-12-18': {'siid': 12, 'piid': 18}, 'machine_state.ambient_light': {'siid': 12, 'piid': 19}, 'machine_state.new_fan_anti_cond': {'siid': 12, 'piid': 20}, 'machine_state.dew_point_tp': {'siid': 12, 'piid': 21}, 'iot_linkage.iot_temp': {'siid': 11, 'piid': 1}, 'iot_linkage.temp_ctrl': {'siid': 11, 'piid': 5}, 'iot_linkage.smart_sleep_ctrl': {'siid': 11, 'piid': 6}, 'iot_linkage.ai_formaldehyde': {'siid': 11, 'piid': 9}, 'iot_linkage.formaldehyde': {'siid': 11, 'piid': 10}, 'enhance.fan_percent': {'siid': 10, 'piid': 1}, 'enhance.timer': {'siid': 10, 'piid': 3}, 'enhance.humidity_range': {'siid': 10, 'piid': 6}, 'enhance.filter_core_rest': {'siid': 10, 'piid': 7}, 'enhance.sleep_diy_sign': {'siid': 10, 'piid': 8}, 'enhance.tp_and_humidity': {'siid': 10, 'piid': 9}, 'enhance.tp_carbon_dioxide': {'siid': 10, 'piid': 10}, 'enhance.huy_carbon_dioxide': {'siid': 10, 'piid': 11}, 'enhance.display_carbon': {'siid': 10, 'piid': 12}, 'enhance.display_co_two': {'siid': 10, 'piid': 13}, 'maintenance.clean': {'siid': 9, 'piid': 1}, 'maintenance.examine': {'siid': 9, 'piid': 2}, 'maintenance.running_duration': {'siid': 9, 'piid': 5}, 'electricity': {'siid': 8, 'piid': 1}, 'electricity.elec_count': {'siid': 8, 'piid': 3}, 'electricity.time_count': {'siid': 8, 'piid': 5}, 'air_fresh.on': {'siid': 14, 'piid': 1}, 'air_fresh.fault': {'siid': 14, 'piid': 2}, 'air_fresh.fan_level': {'siid': 14, 'piid': 5}, 'indicator_light.on': {'siid': 6, 'piid': 1}, 'indicator_light.brightness': {'siid': 6, 'piid': 2}, 'alarm': {'siid': 5, 'piid': 1}, 'environment.temperature': {'siid': 4, 'piid': 7}, 'environment.co2_density': {'siid': 4, 'piid': 8}, 'environment.relative_humidity': {'siid': 4, 'piid': 9}, 'fan_control.fan_level': {'siid': 3, 'piid': 2}, 'fan_control.horizontal_swing': {'siid': 3, 'piid': 3}, 'fan_control.vertical_swing': {'siid': 3, 'piid': 4}, 'fan_control.horizontal_angle': {'siid': 3, 'piid': 5}, 'fan_control.vertical_angle': {'siid': 3, 'piid': 6}}, max_properties: 10`

**Comment by shuaihuaiyi** [comment]
> Find the `model` (like: brand.aircondition.abc) in [devices](https://my.home-assistant.io/redirect/devices).
> 
> Try to [add a custom attribute](https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui):
> 
> ```yaml
> climate.your_entity_id:
>   chunk_properties: 7
> ```

@al-one This doesn't work:

> Mi Smart AC with Ventilation (Elite Edition 1.5HP)(xiaomi.aircondition.mt0): Got MiioException while fetching the state: Unable to parse message payload, mapping: {'air_conditioner.on': {'siid': 2, 'piid': 1}, 'air_conditioner.mode': {'siid': 2, 'piid': 2}, 'air_conditioner.fault': {'siid': 2, 'piid': 3}, 'target_temperature-2-4': {'siid': 2, 'piid': 4}, 'air_conditioner.eco': {'siid': 2, 'piid': 7}, 'air_conditioner.heater': {'siid': 2, 'piid': 9}, 'air_conditioner.dryer': {'siid': 2, 'piid': 10}, 'air_conditioner.sleep_mode': {'siid': 2, 'piid': 11}, 'air_conditioner.soft_wind': {'siid': 2, 'piid': 12}, 'air_conditioner.uv': {'siid': 2, 'piid': 13}, 'air_conditioner.target_humidity': {'siid': 2, 'piid': 14}, 'screen_show.screen_version': {'siid': 17, 'piid': 1}, 'single_smart_scene.auto_cooling': {'siid': 16, 'piid': 1}, 'automatic_heating-16-2': {'siid': 16, 'piid': 2}, 'single_smart_scene.auto_dry': {'siid': 16, 'piid': 3}, 'auto_air_fresh-16-5': {'siid': 16, 'piid': 5}, 'freshair_dark_switch-16-8': {'siid': 16, 'piid': 8}, 'single_smart_scene.sleep_soft': {'siid': 16, 'piid': 9}, 'air_fresh_more.filter_life': {'siid': 15, 'piid': 1}, 'flag_bit.fault_value': {'siid': 13, 'piid': 1}, 'machine_state.indoor_pipe_temp': {'siid': 12, 'piid': 1}, 'machine_state.indoor_fan_speed': {'siid': 12, 'piid': 3}, 'real_heater_switch-12-4': {'siid': 12, 'piid': 4}, 'realindoor_fan_lever-12-5': {'siid': 12, 'piid': 5}, 'machine_state.outdoor_temp': {'siid': 12, 'piid': 7}, 'machine_state.outdoor_pipe_temp': {'siid': 12, 'piid': 8}, 'outdoor_exhaust_temp-12-9': {'siid': 12, 'piid': 9}, 'machine_state.outdoor_fan_lever': {'siid': 12, 'piid': 10}, 'compressor_frequency-12-11': {'siid': 12, 'piid': 11}, 'fourway_valve_switch-12-12': {'siid': 12, 'piid': 12}, 'outdoor_mach_current-12-13': {'siid': 12, 'piid': 13}, 'outdoor_mach_voltage-12-14': {'siid': 12, 'piid': 14}, 'machine_state.expansion_valve': {'siid': 12, 'piid': 15}, 'air_fresh_fan_speed-12-17': {'siid': 12, 'piid': 17}, 'new_wind_fan_lever-12-18': {'siid': 12, 'piid': 18}, 'machine_state.ambient_light': {'siid': 12, 'piid': 19}, 'machine_state.new_fan_anti_cond': {'siid': 12, 'piid': 20}, 'machine_state.dew_point_tp': {'siid': 12, 'piid': 21}, 'iot_linkage.iot_temp': {'siid': 11, 'piid': 1}, 'iot_linkage.temp_ctrl': {'siid': 11, 'piid': 5}, 'iot_linkage.smart_sleep_ctrl': {'siid': 11, 'piid': 6}, 'iot_linkage.ai_formaldehyde': {'siid': 11, 'piid': 9}, 'iot_linkage.formaldehyde': {'siid': 11, 'piid': 10}, 'enhance.fan_percent': {'siid': 10, 'piid': 1}, 'enhance.timer': {'siid': 10, 'piid': 3}, 'enhance.humidity_range': {'siid': 10, 'piid': 6}, 'enhance.filter_core_rest': {'siid': 10, 'piid': 7}, 'enhance.off_flag': {'siid': 10, 'piid': 8}, 'enhance.tp_and_humidity': {'siid': 10, 'piid': 9}, 'enhance.tp_carbon_dioxide': {'siid': 10, 'piid': 10}, 'enhance.huy_carbon_dioxide': {'siid': 10, 'piid': 11}, 'enhance.display_carbon': {'siid': 10, 'piid': 12}, 'enhance.display_co_two': {'siid': 10, 'piid': 13}, 'maintenance.clean': {'siid': 9, 'piid': 1}, 'maintenance.examine': {'siid': 9, 'piid': 2}, 'maintenance.running_duration': {'siid': 9, 'piid': 5}, 'electricity': {'siid': 8, 'piid': 1}, 'electricity.elec_count': {'siid': 8, 'piid': 3}, 'electricity.time_count': {'siid': 8, 'piid': 5}, 'air_fresh.on': {'siid': 14, 'piid': 1}, 'air_fresh.fault': {'siid': 14, 'piid': 2}, 'air_fresh.fan_level': {'siid': 14, 'piid': 5}, 'indicator_light.on': {'siid': 6, 'piid': 1}, 'indicator_light.brightness': {'siid': 6, 'piid': 2}, 'alarm': {'siid': 5, 'piid': 1}, 'environment.temperature': {'siid': 4, 'piid': 7}, 'environment.co2_density': {'siid': 4, 'piid': 8}, 'environment.relative_humidity': {'siid': 4, 'piid': 9}, 'fan_control.fan_level': {'siid': 3, 'piid': 2}, 'fan_control.horizontal_swing': {'siid': 3, 'piid': 3}, 'fan_control.vertical_swing': {'siid': 3, 'piid': 4}, 'fan_control.horizontal_angle': {'siid': 3, 'piid': 5}, 'fan_control.vertical_angle': {'siid': 3, 'piid': 6}}, max_properties: 7/73
