### ISSUE TITLE
米家插座显示功率比实际小100倍

### ISSUE THREAD

**Issue by moetayuko** [al-one/hass-xiaomi-miot#2091]
此时实际功率是 2177 W，界面中显示的刚好小了 100 倍
![图片](https://github.com/user-attachments/assets/a8a5c60c-24e8-4ea7-973e-48283311b2a1)

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/1253#issuecomment-1676666715
