### ISSUE TITLE
Unable to Adjust Humidifier Screen Brightness

### ISSUE THREAD

**Issue by kkqq9320** [al-one/hass-xiaomi-miot#2097]
### Device model / 设备型号

[zhimi.humidifier.ca6](https://home.miot-spec.com/s/zhimi.humidifier.ca6)

### Component version / 插件版本

1.0.5

### HA core version / HA版本

2024.12.4

### Integrated mode / 集成方式

Token

### The problem / 问题详情

An error occurs when attempting to adjust brightness by manipulating the options of the select entity, and the adjustment fails. 

```Failed to perform the action select/select_option. invalid literal for int() with base 10: 'Glimmer'```

I tried both token and automatic methods, but neither worked

![image](https://github.com/user-attachments/assets/9097483c-65f2-4253-b803-29f26a645612)

Additionally, the current state of the select entity is empty.

![image](https://github.com/user-attachments/assets/30e2d6c1-aaa1-44e7-b464-db13199e1377)

![image](https://github.com/user-attachments/assets/c9253f2e-6221-49e0-9188-2038e13a3c6a)

![image](https://github.com/user-attachments/assets/76b1c65f-effe-477b-b016-0aaeb00b3cd0)

### Entity attributes / 实体属性

```yaml
select.zhimi_ca6_4cff_brightness
Hum Bedroom Brightness
unknown	options: Dark, Glimmer, Brightest
friendly_name: Hum Bedroom Brightness
screen.brightness: 0
```
humidifier.bedroom
Hum Bedroom Humidifier
off	min_humidity: 30
max_humidity: 60
available_modes: Off, Fav, Auto, Sleep
device_class: humidifier
friendly_name: Hum Bedroom Humidifier
supported_features: 1
current_humidity: 49
humidity: 60
mode: Off
state_updater: local
other.actual_speed: 548
other.country_code: 44
other.clean: false
other.self_clean_percent: 0
other.pump_state: false
other.pump_cnt: 279
physical_controls_locked: false
screen.brightness: 0
alarm: true
environment.temperature: 24
environment.relative_humidity: 49
humidifier.on: false
humidifier.fault: 0
humidifier.fan_level: 2
humidifier.target_humidity: 60
humidifier.water_level: 1
humidifier.automatic_air_drying: false
humidifier.status: 1
```


### Home Assistant Logs / 系统日志

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:245
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:54:01 AM (7 occurrences)
Last logged: 12:01:59 PM

[140014889850560] Unexpected exception
[140014114037264] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 188, in async_handle_select_option
    await self.async_select_option(option)
  File "/config/custom_components/xiaomi_miot/select.py", line 69, in async_select_option
    await self.device.async_write({self.attr: option})
  File "/config/custom_components/xiaomi_miot/core/device.py", line 614, in async_write
    data = self.encode(payload)
  File "/config/custom_components/xiaomi_miot/core/device.py", line 609, in encode
    conv.encode(self, payload, v)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/core/converters.py", line 116, in encode
    value = int(value) # bool to int
ValueError: invalid literal for int() with base 10: 'Dark'

**Comment by al-one** [comment]
Fixed in master branch.
```bash
wget -O - https://get.hacs.vip | DOMAIN=xiaomi_miot ARCHIVE_TAG=master bash -
```

**Comment by kkqq9320** [comment]
It's fixed! Thank you for the quick resolution.
