### ISSUE TITLE
config flow lose input value on failure

### ISSUE THREAD

**Issue by xuefer** [al-one/hass-xiaomi-miot#21]
type wrong ip or wrong token
"Failed to connect the device"
3 fields i just input is lost, reset to default value
expected: preserve values i inputted so i can correct them and try again

**Comment by al-one** [comment]
Will be supported in the next release.
Added it in [fd0f0b26](https://github.com/al-one/hass-xiaomi-miot/commit/fd0f0b26ccbf89482d357866450f34d046783487).
