### ISSUE TITLE
chuangmi.camera.038a02看不到實時影像

### ISSUE THREAD

**Issue by ckkherman** [al-one/hass-xiaomi-miot#210]
![image](https://user-images.githubusercontent.com/80907722/137377670-29a5c124-7a4b-481a-9441-bdbdf828ac95.png)
access_token: 202722d3000a0c1999c1fadb7c04a81fbac932ffa8332eed547c45592......
brand: chuangmi
model: chuangmi.camera.038a02
lan_ip: 192.168.31.29
mac_address: 60:7E:A4:8E:........
firmware_version: 4.1.4_0085
hardware_version: 
entity_class: MiotCameraEntity
miot_type: urn:miot-spec-v2:device:camera:0000A01C:chuangmi-038a02:1
camera_control.on: true
camera_control.image_rollover: 0
camera_control.night_shot: 2
camera_control.wdr_mode: false
glimmer_full_color-2-6: true
camera_control.recording_mode: 2
camera_control.motion_tracking: false
camera_control.time_watermark: true
motion_detection: true
motion_detection.alarm_interval: 5
detection_sensitivity-5-3: 1
motion_detection_start_time-5-4: 00:00:00
motion_detection_end_time-5-5: 23:59:00
memory_card_management.status: 5
storage_total_space-4-2: 30212096
storage_free_space-4-3: 30146560
storage_used_space-4-4: 65536
indicator_light.on: true
state_updater: cloud
motion_video_time: 2021-10-15 02:46:24
stream_address: https://business.smartcamera.api.io.mi.com/common/app/........?data=FtmAAxKUX3MP9f8z1kZxn1dWvGm6q8n8Gp1EuWpJG%2FI3mAC1jThlL6VNPXpCRAvq8ACoRHig8au3t4I1HggLDbUPBp8DfJWVpqR72z%2BQ%2FKtlJdw2m58gx5m5r5F4u6TdBwqmDKWeu3ac3JyFhFTbs7HGqVvz&rc4_hash__=QqGCDQHjBhRn7oldhQJx60kQ6nHTkcHPPJQnvg%3D%3D&signature=3yjJ7q2DW8%2FVoZMQFc5tYQY68cI%3D&ssecurity=acXI42Wg3qMYjLbWom3LbQ%3D%3D&_nonce=f2vqz%2BJj05kBn5uo&yetAnotherServiceToken=xxxx
image_address: https://processor.smartcamera.api.io.mi.com/miot/camera/..........?data=hHfBw2eAH3Wdh4nJqM4s%2BxnJkx1C2Z98%2B7O0Z%2FcvPbjRfrnqjAywflZy3XGLUelFFuF3hYVRpGDn9ojc0loA19TZbjowpqyzLFG1v10LrYQx0%2F7a0u0LAqoTv9BIclGYZmiLv0nrjIJjeczpGwR3QY%2Fe8PWtQreahGeWtQDKIGCcU4NlstLsO9OPSGBVIkhBWI1SN39HE9gAizVSPnxB2m3uJOiOZBAiulxv0dSzPZPjmzK3DJ4j1FAXnExg6bPS6v7JZSOvmyMvrMgX6w4FZKs6eSqMe1rgkx%2FR9L4NwpHit2MSF1%2BQXoncqvBYUe25boBjYlOs2BSwjWDvjC75RqT0z%2BGEXMfSyk3goFnjVIJ%2BJXayPZUXd959km0KgOSPkI4kurhMtnJ2RpoCPaypgoWHpa404pyFSLVtdQa60URpEz8kko7y1TlyoRzzGMvuv7Jv9YFwXgGOzAKRD0RVERDS9Gc%2BrToJL4L0%2B3gyUSuhx%2BiTwF5%2Fuq%2B2T2IOq6XPRW%2FKFvPXDlZoBYMZvvLK7TUmZYpTjccQecDOEJq%2FA%2FERxN9s3YSzkzfgGZ99zrtXH43IyioYOVGcilFXdTpZh0xjjPpBP1Op%2BTbGR8g3ZPlTJ47FPHowv77XJUasHIrknrnsankGqPfgpJ8lM9ph7YHauVia1oZizmO5zVfSdBTEOo2Y94sZHzdZc%2BIzJ%2FOs6Bx9Cs%2FVVE7iC1Cr%2FQZMo84wCbLA18ZgyBhjaPeOzPskeBkooX2K7ti1qGH4dVe62uJLunB4Eoye37KB6N8%3D&rc4_hash__=uRvg5VL0dBSaw8mV0Ixds0DA1mFSkKcn6o%2BneA%3D%3D&signature=ugM9KpYkS0pfLh%2BgT8hgqnzXwTc%3D&ssecurity=acXI42Wg3qMYjLbWom3LbQ%3D%3D&_nonce=sRnfZCOMga4Bn5uo&yetAnotherServiceToken=xxxx
sub_entities: camera_control.on, motion_detection-5.motion_detection-1, indicator_light-3
motion_video_latest: 
startDuration: 0
cut: false
offset: 0
isCloud: false
isRead: false
videoStoreId: >-
  GLACFC79h4RgPctuoTtgPcbEeCwVVr7zVx_72Oe5-ZHBXbFWE6N0RJI7rK2NrHHcb5Y_rfQjY-jlSc7s62n83S0uTSgNPh8Z6hRPcGxO4KFF55t8ymB0JAE4Y3zuloRC5Gh7SthzYcHT9-2I5RX7HNpLuRdhZx2Bn5MTL8L8SHLJRYEMEPuC8-DLRUWaXi7cr401J1RmAORIg8aOPAxyRoBII6LeSDB-CrH7GdX6obYUh_ACCXMjfljRKDDGSjLxw92lNG-KwBqsGmqcO9dhX2OK1X8ItLQ7GbNWxLwuUYVkSetM0i6IUSZ2FvTHRWFTzYF-uYtrAfF54MDOVeK_dWHU-GsZq7_9CBuKlBSe7XhbFtEeFNSEcuM6kckFU3bIgYHh8b-nBP4JZO4EWrxrQinBVxgSS7vf-LAXTGG7EVEi1QVgkMsBGBCt4acl7vyyeS8IYJXTn5-0GBTFIB-5h536sXw_LEPcxc05ZOlldwA
eventType: PeopleMotion
expireTime: 1634841990178
isAlarm: true
imgStoreId: >-
  GLAC_vKSm-Nqi2rWWcT9euOSreKoLJWSxOT86gVABgpQfoJCswbG_GBeiBkWTO82CwAqeL2KzpQolfaODemYoO98uvZPsRinWiRLByL9mqOsQZGygNVUsMWm8WOCdOkUozaEkM6HXxxVv0oHPC_owJu5y29jXiyhIzCfz0hddVdnGrLESgwdm4pCqcJaj3JFsY5yvg8T1rmnUoVua4wxe1ybvpSQHZVRmV0cwcJK8Zck4kZrc5aRmi3YgF1hcb8xd9hRUUV4OIRsZn9_uLMPCO9pnNX9Rz5XSG9JHT67grKdPE4LDVi--_WVTK0uL064G8VF15dKYQJZe6NinTsbI-Fts8TFMJ0uAJFMLLsNooAiTxFC9PHHUwBB-PjjVIZL5djrHa54f9V_2uLm9kdidm0UfBgSXmEZBkEzQKCSITOvyiQ0drUBGBBWHWp0bY1p9xpG96X_3ldqGBR_Exd_06Xmg_5noyWXw7x_9mS5GQA
fileId: '64841097680543616'
extraInfo: '{"ver":"1.0.0","alarmStart":true,"eventType":"PeopleMotion"}'

friendly_name: IMILAB C21 Camera Control
entity_picture: /api/camera_proxy/camera.chuangmi_038a02_477f_camera_control?token=202722d3000a0c1999c1fadb7c04a81fbac932ffa8332eed547c45592f.........
supported_features: 3
video_attribute: 3
keep_streaming: true

**Comment by ckkherman** [comment]
![未命名](https://user-images.githubusercontent.com/80907722/137379127-32ded097-7cff-43a2-99e8-f15c1f41491d.png)

**Comment by al-one** [comment]
我已经帮你问题中的网址打过码，不过为了安全起见，建议你修改小米账户的密码。
这款摄像机不支持实时直播流，但是可以通过实体的`entity_picture`属性看到回放截图。

**Comment by al-one** [comment]
#166
