### ISSUE TITLE
Does this integration support any recent Xiaomi Smart Watches or Smart Bands?

### ISSUE THREAD

**Issue by BlaXun** [al-one/hass-xiaomi-miot#2108]
I've recently been looking for a smart band or smart watch to track my daily step count without having to rely on my iPhone all the time. I'd like to ask if this integration supports any of the recent xiaomi smart bands (for example the smart band 9) or any of the more recent smart watches.

Thanks in advance

**Comment by al-one** [comment]
Currently not supported, no plan.
