### ISSUE TITLE
MYG100 fish tank feeding measure switch unavailable after update to 1.0

### ISSUE THREAD

**Issue by korneyev** [al-one/hass-xiaomi-miot#2110]
### Device model / 设备型号

[hfjh.fishbowl.m100](https://home.miot-spec.com/s/hfjh.fishbowl.m100)

### Component version / 插件版本

1.0.0

### HA core version / HA版本

2024.10.2

### Integrated mode / 集成方式

Token

### The problem / 问题详情

After update from version 0.7.25 to 1.0.0 entity switch.hfjh_m100_8b54_feeding_measure (switch for turning on fish feed device) became unavailable. Problem persists in all newer versions up (and including) to 1.0.6

### Entity attributes / 实体属性

```yaml
switch.hfjh_m100_8b54_feeding_measure
```

### Home Assistant Logs / 系统日志

There are no lines corresponding to this device in HA logs

**Comment by al-one** [comment]
Upgrade to latest version

**Comment by korneyev** [comment]
As I've mentioned - version 1.0.6 has same problem. Tried it just today.

**Comment by al-one** [comment]
Provide all attributes of the `info` entity.

**Comment by korneyev** [comment]
Below are attributes from info entity in 1.0.6 version.
Version 0.7.25 doesn't provides info entity, it is disabled.

<template TemplateState(<state
          button.hfjh_m100_8b54_info=2024-12-20T10:02:56.058083+00:00;
          info=Aquarium,
          model=hfjh.fishbowl.m100,
          did=,
          mac=8C:D0:B2:BA:8B:54,
          lan_ip=192.168.2.9,
          app_link=,
          miot_type=urn:miot-spec-v2:device:fish-tank:0000A0A2:hfjh-m100:2,
          available=True,
          home_room=,
          icon=mdi:information,
          updater=local,
          updated_at=2024-12-20
          13:06:19.489973+03:00,
          exception_card.trigger_status=128,
          no_reminder_status-12-3=0,
          temperature_warn_on-9-3=False,
          temperature_warn_min-9-4=10,
          temperature_warn_max-9-5=30,
          no_disturb_custom.repeat_cycle=127,
          light_status_on-8-4=True,
          light_status_mode-8-5=0,
          light_status_bright-8-6=1,
          light_status_flow-8-7=0,
          pump_status_on-8-8=True,
          pump_status_flux-8-9=0,
          no_disturb_working-8-10=False,
          feeder_custom.feeder_status=0,
          feeder_custom.today_feeded_num=1,
          feeder_custom.feed_protect_on=False,
          feeder_custom.protect_status=0,
          pump_custom.temperature_status=1,
          pump_custom.pump_current=value,
          pump_custom.running_duration.error=-4003
          Property
          Action
          Event
          does
          not
          exist,
          light_custom.light_mode_list=16724753-hfjh_nmg-4,14279679-hfjh_xlg-5,16777215-hfjh_white-3,7,0,1,2,
          light_custom.light_edit_on=False,
          light_water_use_time-4-4=66,
          light_custom.light_edit_color=255,
          light_custom.light_edit_bright=100,
          physical_controls_locked=False,
          light.on=True,
          light.mode=2,
          light.brightness=100,
          light.flow_speed_level=2,
          indicator_light.on=False,
          alarm=False,
          filter-11.filter_life_level=86,
          filter-11.filter_left_time=3723,
          filter.filter_life_level=0,
          filter.filter_left_time=0,
          no_disturb=False,
          no_disturb.enable_time_period=09:00:00-21:00:00,
          fish_tank.on=True,
          fish_tank.water_pump=True,
          fish_tank.pump_flux=1,
          fish_tank.temperature=26,
          fish_tank.water_pump_status=2,
          converters=['button.info'
          ,'switch.fish_tank.on'
          ,'light.light.on'
          ,'light.brightness'
          ,'light.mode'
          ,'light.indicator_light.on'
          ,'switch.physical_controls_locked'
          ,'sensor.filter.filter_life_level'
          ,'sensor.filter.filter_left_time'
          ,'sensor.filter-11.filter_life_level'
          ,'sensor.filter-11.filter_left_time'
          ,'sensor.fish_tank.temperature'
          ,'sensor.fish_tank.water_pump_status'
          ,'sensor.alarm'
          ,'switch.fish_tank.water_pump'
          ,'switch.no_disturb'
          ,'switch.feeder_custom.feed_protect_on'
          ,'switch.light_status_on-8-4'
          ,'switch.pump_status_on-8-8'
          ,'switch.temperature_warn_on-9-3'
          ,'number.no_disturb_custom.repeat_cycle'
          ,'number.light_status_bright-8-6'
          ,'number.temperature_warn_min-9-4'
          ,'number.temperature_warn_max-9-5'
          ,'select.fish_tank.pump_flux'
          ,'select.light.flow_speed_level'
          ,'select.light_status_mode-8-5'
          ,'select.light_status_flow-8-7'
          ,'select.pump_status_flux-8-9'
          ,'select.fish_tank.pet_food_out'
          ],
          customizes=select_actions=pet_food_out,
          sensor_properties=temperature,water_pump_status,filter_life_level,alarm.alarm,
          switch_properties=water_pump,feed_protect_on,no_disturb,light_status_on,pump_status_on,temperature_warn_on,
          number_properties=repeat_cycle,light_status_bright,temperature_warn_min,temperature_warn_max,
          light_services=light,
          select_properties=pump_flux,light_status_mode,light_status_flow,pump_status_flux,flow_speed_level,
          extend_miot_specs=[{'iid'
          :
          15,'properties'
          :
          [{'iid':
          2,'value-list'
          :
          [{'value':
          0,'description'
          :'Day'
          },
          {'value':
          1,'description'
          :'Flow'
          },
          {'value':
          2,'description'
          :'Water
          Grass'
          },
          {'value':
          3,'description'
          :'Color
          1'
          },
          {'value':
          4,'description'
          :'Color
          2'
          },
          {'value':
          5,'description'
          :'Color
          3'
          },
          {'value':
          6,'description'
          :'Color
          4'
          },
          {'value':
          7,'description'
          :'Night
          Light'
          },
          {'value':
          8,'description'
          :'Color
          5'
          }]}]}],
          device_class=update,
          friendly_name=Aquarium
          Info
          @
          2024-12-20T13:02:56.058173+03:00>)>

**Comment by al-one** [comment]
Migrate to `select.hfjh_m100_8b54_pet_food_out`

**Comment by korneyev** [comment]
Thank you very much.
I've missed that new entity.
Have tried it - works perfectly.
