### ISSUE TITLE
Xiaomi Heatcold Heating Thermostat  ЕР

### ISSUE THREAD

**Issue by BiznessDronss** [al-one/hass-xiaomi-miot#213]
hvac_modes: auto, off
min_temp: 0
max_temp: 90
target_temp_step: 1
preset_modes: Home, Away, Smart, Sleep, off
current_temperature: 0
temperature: 17
preset_mode: null
model: cubee.airrtc.th123w
lan_ip: 192.168.1.76
mac_address: 54:48:E6:53:96:02
firmware_version: 2.0.8
hardware_version: esp32
entity_class: MiotClimateEntity
miot_type: urn:miot-spec-v2:device:thermostat:0000A031:cubee-th123w:1
thermostat.on: true
thermostat.status.error: -4004 Other internal errors
thermostat.fault.error: -4004 Other internal errors
thermostat.mode.error: -4004 Other internal errors
thermostat.target_temperature.error: -4004 Other internal errors
thermostat.temperature.error: -4004 Other internal errors
heatold.childlock.error: -4004 Other internal errors
heatold.sensortype.error: -4004 Other internal errors
heatold.tempactivate.error: -4004 Other internal errors
heatold.tempcomp.error: -4004 Other internal errors
heatold.tempfloor: 0
heatold.maxsettemp.error: -4004 Other internal errors
heatold.minsettemp.error: -4004 Other internal errors
state_updater: lan
thermostat.mode: 0
thermostat.target_temperature: 17
friendly_name: Xiaomi Miot Thermostat
supported_features: 17

**Comment by al-one** [comment]
This error `-4004 Other internal errors` is returned by the device. The device of this model [`cubee.airrtc.th123w`](https://home.miot-spec.com/s/cubee.airrtc.th123w) uses the local connection method by default, but it seems to be a bit problematic. So this commit changes the connection mode of the device to the cloud by default.

**Comment by BiznessDronss** [comment]
> This error `-4004 Other internal errors` is returned by the device. The device of this model [`cubee.airrtc.th123w`](https://home.miot-spec.com/s/cubee.airrtc.th123w) uses the local connection method by default, but it seems to be a bit problematic. So this commit [47888ee](https://github.com/al-one/hass-xiaomi-miot/commit/47888ee611028742a7215f38f991ba1ea125c279) changes the connection mode of the device to the cloud by default.
tell me what needs to be done? I didn't understand!
