### ISSUE TITLE
小米人脸识别智能门锁X支持接入吗？

### ISSUE THREAD

**Issue by w87777w** [al-one/hass-xiaomi-miot#215]

**Comment by al-one** [comment]
已知该设备型号为[`lumi.lock.bmcn05`](https://home.mi.com/baike/index.html#/detail?model=lumi.lock.bmcn05)，但貌似厂商仍未定义任何[miot-spec规格](https://home.miot-spec.com/spec/lumi.lock.bmcn05)。

**Comment by al-one** [comment]
设备[`lumi.lock.bmcn05`](https://home.mi.com/baike/index.html#/detail?model=lumi.lock.bmcn05)的[miot-spec规格](https://home.miot-spec.com/spec/lumi.lock.bmcn05)已发布，规格中仅定义了`lock`、`door`、`battery`服务，因此只能像普通门锁一样支持部分传感器。
![图片](https://user-images.githubusercontent.com/4549099/141106677-0ff875b8-9574-4c3a-ac8b-740865785ba2.png)
