### ISSUE TITLE
ＨＥＲＥ’Ｓ！！＊ ＷＡＹ ＴＯ ＷＡＴＣＨ Ｏｌｅｋｓａｎｄｒ Ｕｓｙｋ ｖｓ Ｔｙｓｏｎ Ｆｕｒｙ ２ ＬＩＶＥ ＳＴＲＥＡＭＳ ＲＥＤＤＩＴ ＢＯＸＩＮＧ ＯＮ ＴＶ ＣＨＡＮＮＥＬ

### ISSUE THREAD

**Issue by yohalvisch33** [al-one/hass-xiaomi-miot#2153]
ＨＥＲＥ’Ｓ！！＊ ＷＡＹ ＴＯ ＷＡＴＣＨ Ｏｌｅｋｓａｎｄｒ Ｕｓｙｋ ｖｓ Ｔｙｓｏｎ Ｆｕｒｙ ２ ＬＩＶＥ ＳＴＲＥＡＭＳ ＲＥＤＤＩＴ ＢＯＸＩＮＧ ＯＮ ＴＶ ＣＨＡＮＮＥＬ 𝙒𝙖𝙩𝙘𝙝 Fury vs Usyk 𝙇𝙞𝙫𝙚 𝙁𝙧𝙚𝙚 𝙁𝙪𝙡𝙡 𝙂𝙖𝙢𝙚𝙨 𝙊𝙣𝙡𝙞𝙣𝙚 2024

10 second ago

[►🌍👉 Fury vs Usyk 𝙇𝙞𝙫𝙚](https://prostreamstv.blogspot.com/2024/12/boxing.html)

## [►🌍👉 Fury vs Usyk 𝙇𝙞𝙫𝙚](https://prostreamstv.blogspot.com/2024/12/boxing.html)

𝙏𝙮𝙨𝙤𝙣 𝙁𝙪𝙧𝙮 𝙬𝙞𝙡𝙡 𝙤𝙣𝙘𝙚 𝙖𝙜𝙖𝙞𝙣 𝙜𝙤 𝙩𝙤𝙚-𝙩𝙤-𝙩𝙤𝙚 𝙬𝙞𝙩𝙝 𝙊𝙡𝙚𝙠𝙨𝙖𝙣𝙙𝙧 𝙐𝙨𝙮𝙠 𝙞𝙣 𝙩𝙝𝙚𝙞𝙧 𝙝𝙤𝙩𝙡𝙮-𝙖𝙣𝙩𝙞𝙘𝙞𝙥𝙖𝙩𝙚𝙙 𝙧𝙚𝙢𝙖𝙩𝙘𝙝 – 𝙝𝙚𝙧𝙚'𝙨 𝙚𝙫𝙚𝙧𝙮𝙩𝙝𝙞𝙣𝙜 𝙮𝙤𝙪 𝙣𝙚𝙚𝙙 𝙩𝙤 𝙠𝙣𝙤𝙬 𝙖𝙗𝙤𝙪𝙩 𝙩𝙝𝙚 𝙛𝙞𝙜𝙝𝙩, 𝙞𝙣𝙘𝙡𝙪𝙙𝙞𝙣𝙜 𝙩𝙝𝙚 𝙨𝙩𝙖𝙧𝙩 𝙩𝙞𝙢𝙚, 𝙏𝙑 𝙘𝙝𝙖𝙣𝙣𝙚𝙡 𝙖𝙣𝙙 𝙪𝙣𝙙𝙚𝙧𝙘𝙖𝙧𝙙

𝙏𝙮𝙨𝙤𝙣 𝙁𝙪𝙧𝙮 𝙞𝙨 𝙜𝙚𝙖𝙧𝙞𝙣𝙜 𝙪𝙥 𝙛𝙤𝙧 𝙝𝙞𝙨 𝙝𝙤𝙩𝙡𝙮-𝙖𝙣𝙩𝙞𝙘𝙞𝙥𝙖𝙩𝙚𝙙 𝙧𝙚𝙢𝙖𝙩𝙘𝙝 𝙬𝙞𝙩𝙝 𝙐𝙠𝙧𝙖𝙞𝙣𝙞𝙖𝙣 𝙧𝙞𝙫𝙖𝙡 𝙊𝙡𝙚𝙠𝙨𝙖𝙣𝙙𝙧 𝙐𝙨𝙮𝙠. 𝙊𝙣 𝙎𝙖𝙩𝙪𝙧𝙙𝙖𝙮, 𝘿𝙚𝙘𝙚𝙢𝙗𝙚𝙧 21, 𝙩𝙝𝙚 𝙨𝙤-𝙘𝙖𝙡𝙡𝙚𝙙 𝙂𝙮𝙥𝙨𝙮 𝙆𝙞𝙣𝙜 𝙬𝙞𝙡𝙡 𝙗𝙚 𝙤𝙪𝙩 𝙛𝙤𝙧 𝙧𝙚𝙫𝙚𝙣𝙜𝙚 𝙬𝙝𝙞𝙡𝙚 𝙐𝙨𝙮𝙠 𝙖𝙞𝙢𝙨 𝙩𝙤 𝙙𝙚𝙛𝙚𝙣𝙙 𝙝𝙞𝙨 𝙒𝘽𝙊, 𝙒𝘽𝘾 𝙖𝙣𝙙 𝙒𝘽𝘼 𝙝𝙚𝙖𝙫𝙮𝙬𝙚𝙞𝙜𝙝𝙩 𝙩𝙞𝙩𝙡𝙚𝙨.

𝙏𝙝𝙚 𝙗𝙤𝙪𝙩 – 𝙩𝙞𝙩𝙡𝙚𝙙 𝙐𝙨𝙮𝙠 𝙫 𝙁𝙪𝙧𝙮 2: 𝙍𝙚𝙞𝙜𝙣𝙞𝙩𝙚𝙙 – 𝙞𝙨 𝙨𝙚𝙩 𝙩𝙤 𝙩𝙖𝙠𝙚 𝙥𝙡𝙖𝙘𝙚 𝙞𝙣 𝙍𝙞𝙮𝙖𝙙𝙝, 𝙎𝙖𝙪𝙙𝙞 𝘼𝙧𝙖𝙗𝙞𝙖, 𝙖𝙣𝙙 𝙛𝙖𝙣𝙨 𝙘𝙖𝙣 𝙤𝙧𝙙𝙚𝙧 𝙩𝙝𝙚 𝙛𝙞𝙜𝙝𝙩 𝙖𝙝𝙚𝙖𝙙 𝙤𝙛 𝙩𝙞𝙢𝙚. 𝙏𝙝𝙚 𝙞𝙣𝙞𝙩𝙞𝙖𝙡 𝙚𝙣𝙘𝙤𝙪𝙣𝙩𝙚𝙧 𝙗𝙚𝙩𝙬𝙚𝙚𝙣 𝙩𝙝𝙚 𝙩𝙬𝙤 𝙝𝙚𝙖𝙫𝙮𝙬𝙚𝙞𝙜𝙝𝙩𝙨, 𝙝𝙚𝙡𝙙 𝙞𝙣 𝙍𝙞𝙮𝙖𝙙𝙝 𝙞𝙣 𝙈𝙖𝙮, 𝙨𝙖𝙬 𝙐𝙨𝙮𝙠 𝙘𝙧𝙤𝙬𝙣𝙚𝙙 𝙩𝙝𝙚 𝙛𝙞𝙧𝙨𝙩 𝙪𝙣𝙙𝙞𝙨𝙥𝙪𝙩𝙚𝙙 𝙬𝙤𝙧𝙡𝙙 𝙝𝙚𝙖𝙫𝙮𝙬𝙚𝙞𝙜𝙝𝙩 𝙘𝙝𝙖𝙢𝙥𝙞𝙤𝙣 𝙨𝙞𝙣𝙘𝙚 1999.

𝙊𝙫𝙚𝙧 𝙩𝙝𝙚 𝙘𝙤𝙪𝙧𝙨𝙚 𝙤𝙛 12 𝙧𝙤𝙪𝙣𝙙𝙨, 𝙐𝙨𝙮𝙠 𝙚𝙢𝙚𝙧𝙜𝙚𝙙 𝙫𝙞𝙘𝙩𝙤𝙧𝙞𝙤𝙪𝙨 𝙫𝙞𝙖 𝙖 𝙨𝙥𝙡𝙞𝙩 𝙙𝙚𝙘𝙞𝙨𝙞𝙤𝙣 (115-112, 113-114, 114-113), 𝙙𝙚𝙡𝙞𝙫𝙚𝙧𝙞𝙣𝙜 𝙁𝙪𝙧𝙮 𝙩𝙝𝙚 𝙛𝙞𝙧𝙨𝙩 𝙙𝙚𝙛𝙚𝙖𝙩 𝙤𝙛 𝙝𝙞𝙨 𝙥𝙧𝙤𝙛𝙚𝙨𝙨𝙞𝙤𝙣𝙖𝙡 𝙘𝙖𝙧𝙚𝙚𝙧. 𝙁𝙤𝙡𝙡𝙤𝙬𝙞𝙣𝙜 𝙩𝙝𝙚𝙞𝙧 𝙛𝙞𝙧𝙨𝙩 𝙛𝙞𝙜𝙝𝙩, 𝙐𝙨𝙮𝙠 𝙝𝙖𝙨 𝙝𝙖𝙙 𝙩𝙤 𝙝𝙖𝙣𝙙 𝙤𝙫𝙚𝙧 𝙝𝙞𝙨 𝙄𝘽𝙁 𝙩𝙞𝙩𝙡𝙚 𝙩𝙤 𝘽𝙧𝙞𝙩𝙞𝙨𝙝 𝙗𝙤𝙭𝙚𝙧 𝘿𝙖𝙣𝙞𝙚𝙡 𝘿𝙪𝙗𝙤𝙞𝙨 𝙖𝙛𝙩𝙚𝙧 𝙝𝙚 𝙙𝙚𝙛𝙚𝙖𝙩𝙚𝙙 𝘼𝙣𝙩𝙝𝙤𝙣𝙮 𝙅𝙤𝙨𝙝𝙪𝙖 𝙞𝙣 𝙎𝙚𝙥𝙩𝙚𝙢𝙗𝙚𝙧, 𝙧𝙚𝙥𝙤𝙧𝙩𝙨 𝙈𝙮𝙇𝙤𝙣𝙙𝙤𝙣.

𝙎𝙥𝙚𝙖𝙠𝙞𝙣𝙜 𝙩𝙤 𝙏𝙉𝙏 𝙎𝙥𝙤𝙧𝙩𝙨 𝙚𝙖𝙧𝙡𝙞𝙚𝙧 𝙩𝙝𝙞𝙨 𝙢𝙤𝙣𝙩𝙝, 𝙁𝙪𝙧𝙮 𝙫𝙤𝙬𝙚𝙙 𝙩𝙤 𝙜𝙤 𝙞𝙣𝙩𝙤 𝙝𝙞𝙨 𝙧𝙚𝙢𝙖𝙩𝙘𝙝 𝙬𝙞𝙩𝙝 𝙐𝙨𝙮𝙠 𝙞𝙣 ‘𝙙𝙚𝙨𝙩𝙧𝙤𝙮 𝙢𝙤𝙙𝙚’, 𝙏𝙖𝙡𝙠𝙨𝙥𝙤𝙧𝙩 𝙧𝙚𝙥𝙤𝙧𝙩𝙚𝙙. "𝙄'𝙢 𝙜𝙤𝙞𝙣𝙜 𝙩𝙤 𝙜𝙤 𝙞𝙣 𝙩𝙝𝙚𝙧𝙚 [𝙞𝙣] 𝙙𝙚𝙨𝙩𝙧𝙤𝙮 𝙢𝙤𝙙𝙚. 𝙇𝙖𝙨𝙩 𝙩𝙞𝙢𝙚 𝙄 𝙬𝙚𝙣𝙩 𝙩𝙤 𝙗𝙤𝙭 𝙝𝙞𝙢 𝙖𝙣𝙙 𝙄 𝙬𝙖𝙨 𝙗𝙚𝙞𝙣𝙜 𝙘𝙖𝙪𝙩𝙞𝙤𝙪𝙨.

"𝙄 𝙬𝙖𝙨 𝙗𝙤𝙭𝙞𝙣𝙜 𝙩𝙝𝙚 𝙝𝙚𝙖𝙙 𝙧𝙞𝙜𝙝𝙩 𝙤𝙛𝙛 𝙝𝙞𝙢, 𝙡𝙚𝙩'𝙨 𝙩𝙖𝙡𝙠 𝙛𝙖𝙘𝙩𝙨. 𝘼𝙣𝙮𝙤𝙣𝙚 𝙘𝙖𝙣 𝙜𝙚𝙩 𝙘𝙖𝙪𝙜𝙝𝙩 𝙖𝙨 𝙬𝙚'𝙫𝙚 𝙨𝙚𝙚𝙣 𝙞𝙣 𝙖 𝙡𝙤𝙩 𝙤𝙛 𝙩𝙝𝙚𝙨𝙚 𝙝𝙚𝙖𝙫𝙮𝙬𝙚𝙞𝙜𝙝𝙩 𝙛𝙞𝙜𝙝𝙩𝙨. 𝘽𝙪𝙩 𝙩𝙝𝙞𝙨 𝙩𝙞𝙢𝙚 𝙄'𝙢 𝙣𝙤𝙩 𝙜𝙤𝙞𝙣𝙜 𝙛𝙤𝙧 𝙖 𝙥𝙤𝙞𝙣𝙩𝙨 𝙙𝙚𝙘𝙞𝙨𝙞𝙤𝙣. 𝙄'𝙢 𝙜𝙤𝙞𝙣𝙜 𝙩𝙤 𝙠𝙣𝙤𝙘𝙠 𝙖 𝙢𝙤𝙩𝙝𝙚𝙧*****𝙧 𝙤𝙪𝙩."

𝙒𝙞𝙩𝙝 𝙖𝙣𝙩𝙞𝙘𝙞𝙥𝙖𝙩𝙞𝙤𝙣 𝙗𝙪𝙞𝙡𝙙𝙞𝙣𝙜 𝙖𝙢𝙤𝙣𝙜𝙨𝙩 𝙗𝙤𝙭𝙞𝙣𝙜 𝙛𝙖𝙣𝙨 𝙛𝙤𝙧 𝙖𝙣𝙤𝙩𝙝𝙚𝙧 𝙧𝙚𝙢𝙖𝙧𝙠𝙖𝙗𝙡𝙚 𝙛𝙞𝙜𝙝𝙩, 𝙙𝙚𝙩𝙖𝙞𝙡𝙨 𝙧𝙚𝙜𝙖𝙧𝙙𝙞𝙣𝙜 𝙩𝙝𝙚 𝙨𝙩𝙖𝙧𝙩𝙞𝙣𝙜 𝙩𝙞𝙢𝙚 𝙤𝙛 𝙐𝙨𝙮𝙠 𝙫 𝙁𝙪𝙧𝙮 2 𝙖𝙣𝙙 𝙤𝙥𝙩𝙞𝙤𝙣𝙨 𝙛𝙤𝙧 𝙨𝙩𝙧𝙚𝙖𝙢𝙞𝙣𝙜 𝙩𝙝𝙚 𝙚𝙫𝙚𝙣𝙩 𝙡𝙞𝙫𝙚 𝙝𝙖𝙫𝙚 𝙗𝙚𝙚𝙣 𝙘𝙤𝙣𝙛𝙞𝙧𝙢𝙚𝙙.

𝙒𝙝𝙚𝙣 𝙞𝙨 𝙏𝙮𝙨𝙤𝙣 𝙁𝙪𝙧𝙮 𝙫𝙨 𝙊𝙡𝙚𝙠𝙨𝙖𝙣𝙙𝙧 𝙐𝙨𝙮𝙠 2? 𝙏𝙮𝙨𝙤𝙣 𝙁𝙪𝙧𝙮 𝙖𝙣𝙙 𝙊𝙡𝙚𝙠𝙨𝙖𝙣𝙙𝙧 𝙐𝙨𝙮𝙠 𝙬𝙞𝙡𝙡 𝙛𝙖𝙘𝙚 𝙤𝙛𝙛 𝙤𝙣 𝙎𝙖𝙩𝙪𝙧𝙙𝙖𝙮, 𝘿𝙚𝙘𝙚𝙢𝙗𝙚𝙧 21. 𝘼𝙘𝙘𝙤𝙧𝙙𝙞𝙣𝙜 𝙩𝙤 𝘿𝘼𝙕𝙉, 𝙩𝙝𝙚 𝙢𝙖𝙞𝙣 𝙛𝙞𝙜𝙝𝙩 𝙘𝙖𝙧𝙙 𝙞𝙨 𝙚𝙭𝙥𝙚𝙘𝙩𝙚𝙙 𝙩𝙤 𝙗𝙚𝙜𝙞𝙣 𝙖𝙧𝙤𝙪𝙣𝙙 4𝙥𝙢 𝙞𝙣 𝙩𝙝𝙚 𝙐𝙆.

𝙏𝙝𝙚 𝙁𝙪𝙧𝙮 𝙖𝙣𝙙 𝙐𝙨𝙮𝙠 𝙧𝙞𝙣𝙜𝙬𝙖𝙡𝙠𝙨 𝙖𝙧𝙚 𝙚𝙭𝙥𝙚𝙘𝙩𝙚𝙙 𝙩𝙤 𝙗𝙚𝙜𝙞𝙣 𝙖𝙧𝙤𝙪𝙣𝙙 10.25𝙥𝙢.

𝙒𝙝𝙖𝙩 𝙞𝙨 𝙩𝙝𝙚 𝙐𝙨𝙮𝙠 𝙫𝙨 𝙁𝙪𝙧𝙮 2 𝙪𝙣𝙙𝙚𝙧𝙘𝙖𝙧𝙙? 𝙎𝙚𝙧𝙝𝙞𝙞 𝘽𝙤𝙝𝙖𝙘𝙝𝙪𝙠 𝙫𝙨 𝙄𝙨𝙝𝙢𝙖𝙚𝙡 𝘿𝙖𝙫𝙞𝙨 – 𝙇𝙞𝙜𝙝𝙩 𝙢𝙞𝙙𝙙𝙡𝙚𝙬𝙚𝙞𝙜𝙝𝙩 𝙈𝙤𝙨𝙚𝙨 𝙄𝙩𝙖𝙪𝙢𝙖 𝙫𝙨 𝘿𝙚𝙢𝙨𝙚𝙮 𝙈𝙘𝙆𝙚𝙖𝙣 – 𝙃𝙚𝙖𝙫𝙮𝙬𝙚𝙞𝙜𝙝𝙩 𝙅𝙤𝙝𝙣𝙣𝙮 𝙁𝙞𝙨𝙝𝙚𝙧 𝙫𝙨 𝘿𝙖𝙫𝙚 𝘼𝙡𝙡𝙚𝙣 – 𝙃𝙚𝙖𝙫𝙮𝙬𝙚𝙞𝙜𝙝𝙩 𝙋𝙚𝙩𝙚𝙧 𝙈𝙘𝙂𝙧𝙖𝙞𝙡 𝙫𝙨 𝙍𝙝𝙮𝙨 𝙀𝙙𝙬𝙖𝙧𝙙𝙨 – 𝙎𝙪𝙥𝙚𝙧 𝙗𝙖𝙣𝙩𝙖𝙢𝙬𝙚𝙞𝙜𝙝𝙩 𝙄𝙨𝙖𝙖𝙘 𝙇𝙤𝙬𝙚 𝙫𝙨 𝙇𝙚𝙚 𝙈𝙘𝙂𝙧𝙚𝙜𝙤𝙧 – 𝙁𝙚𝙖𝙩𝙝𝙚𝙧𝙬𝙚𝙞𝙜𝙝𝙩 𝘿𝙖𝙣𝙞𝙚𝙡 𝙇𝙖𝙥𝙞𝙣 𝙫𝙨 𝘿𝙮𝙡𝙖𝙣 𝘾𝙤𝙡𝙞𝙣 – 𝙇𝙞𝙜𝙝𝙩-𝙝𝙚𝙖𝙫𝙮𝙬𝙚𝙞𝙜𝙝𝙩 𝘼𝙣𝙙𝙧𝙞𝙞 𝙉𝙤𝙫𝙮𝙩𝙨𝙠𝙮𝙞 𝙫𝙨 𝙀𝙙𝙜𝙖𝙧 𝙍𝙖𝙢𝙞𝙧𝙚𝙯 – 𝙃𝙚𝙖𝙫𝙮𝙬𝙚𝙞𝙜𝙝𝙩

**Comment by terriana42** [comment]
y
