### ISSUE TITLE
Vacuum - Valetudo (RE) Support?

### ISSUE THREAD

**Issue by jlohmeier** [al-one/hass-xiaomi-miot#216]
Will you support valetudo (RE) on custom firmware in the future?

Xiaomi Miot For HomeAssistant v0.4.7
HA 2021.10.5
Valetudo (RE) on custom firmware (miio-client 3.3.9; A.03.0005; using TOKEN) using Roborock S5

```
Logger: custom_components.xiaomi_miot.vacuum
Source: custom_components/xiaomi_miot/__init__.py:1074 
Integration: Xiaomi Miot Auto (documentation, issues) 
First occurred: 18:57:08 (4 occurrences) 
Last logged: 18:58:38

Valetudo Robot Cleaner: Got invalid miot result while fetching the state: ['u', 'n', 'k', 'n', 'o', 'w', 'n', '_', 'm', 'e', 't', 'h', 'o', 'd'], mapping: {'vacuum.status': {'siid': 2, 'piid': 1}, 'vacuum.mode': {'siid': 2, 'piid': 2}, 'battery.battery_level': {'siid': 3, 'piid': 1}, 'battery.charging_state': {'siid': 3, 'piid': 2}}
```

**Comment by al-one** [comment]
This firmware does not support miot in LAN. If it can be bound to the Mihome APP, you can try to integrate it through your Xiaomi account.

**Comment by al-one** [comment]
Valetudo will disconnect the vacuum from the Mi Cloud. Unless it can support the miot-sepc protocol in the LAN, this component will not be available.
Of course, you can also use MQTT to integrate valetudo into your HA: https://valetudo.cloud/pages/integrations/home-assistant-integration.html
