### ISSUE TITLE
Add support Mijia Wireless Smart Pet Fountain

### ISSUE THREAD

**Issue by diemon24** [al-one/hass-xiaomi-miot#2196]
### Device model / 设备型号

xiaomi.pet_waterer.002

### Component version / 插件版本

2.1.1_0029

### HA core version / HA版本

2024.11.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Not support device. Please add support. 
![IMG_8838](https://github.com/user-attachments/assets/833dbc2c-e35a-41dd-a441-8fc3e923f818)

### Entity attributes / 实体属性

```yaml
Not view sensor for off water level. 
Not available battery state.
Not available water switch. 
Not available sensor for filter.
```

**Comment by danieldabate** [comment]
I don't understand why this issue was closed. Is it already supported? If not, could it potentially be supported?

Or do we need to look for other way of connecting this device?

**Comment by diemon24** [comment]
This device work only with BLE gateway.

**Comment by danieldabate** [comment]
But is that a limitation of the device or how it is supported by this library? Maybe something can be done so a xiaomi gateway is not needed? I'm not an expert on xiaomi protocols, but I'm guessing this is just using Bluetooth.

**Comment by diemon24** [comment]
I don't know. This device not accessible without BLE gateway when my mobile device far.

**Comment by diemon24** [comment]
> But is that a limitation of the device or how it is supported by this component? Maybe something can be done so a xiaomi gateway is not needed? I'm not an expert on xiaomi protocols, but I'm guessing this is just using Bluetooth.

Maybe can use ESP32 BLE Proxy and ESP32 Xiaomi BLE for analysis BLE protocol. But i don't know how use this metod.
