### ISSUE TITLE
Unable to add integration

### ISSUE THREAD

**Issue by thomasreiser** [al-one/hass-xiaomi-miot#22]
I am using Home Assistant OS 5.12 (HASS Core 2021.2.3) and installed the integration (v0.2.4) via HACS:

![image](https://user-images.githubusercontent.com/170543/108817945-f03e9e80-75b8-11eb-9394-fae35a3ef41a.png)

But unfortunately, I am not able to select the integration in the HASS configuration -> Integrations:

![image](https://user-images.githubusercontent.com/170543/108818009-1106f400-75b9-11eb-99be-ce55bffbedf4.png)

Is there something wrong with my setup?

EDIT:
Log file says the integration is active
`2021-02-23 09:27:47 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.`
Is there no more GUI?

**Comment by al-one** [comment]
You need to restart HA and clear your browser cache.

**Comment by thomasreiser** [comment]
I did that but it somehow did not work. Reinstalled everything and works now.
Thank you!
