### ISSUE TITLE
hyd.airer.lyjpro 晾衣架 建议添加默认自定义chunk_properties: '1'，否则在local模式下环境湿度、灯光不可用

### ISSUE THREAD

**Issue by ptbsare** [al-one/hass-xiaomi-miot#2214]
### Device model / 设备型号

hyd.airer.lyjpro

### Component version / 插件版本

1.0.7

### HA core version / HA版本

2025.1 beta

### Integrated mode / 集成方式

Local (本地模式)

### Entity attributes / 实体属性

```yaml
略
```

**Comment by al-one** [comment]
建议PR
