### ISSUE TITLE
Latency on/off and change

### ISSUE THREAD

**Issue by Redram49RUS** [al-one/hass-xiaomi-miot#2253]
In version 1.07 humidifier 2 and heater 1s long change status or humidifity, temperature in the card on dashboard.

**Comment by MStankiewiczOfficial** [comment]
Same problem with `deerma.humidifier.jsq2w`

**Comment by al-one** [comment]
Describe in detail.

- https://github.com/al-one/hass-xiaomi-miot/issues/new?template=device-issue.yml
