### ISSUE TITLE
小爱音箱成为媒体设备

### ISSUE THREAD

**Issue by pyhofficial** [al-one/hass-xiaomi-miot#2254]
能不能像社区开发的集成的那样将小爱音箱的播放直接当媒体设备，不用自己搓卡片了

**Comment by al-one** [comment]
哥们你走错片场了。。

**Comment by pyhofficial** [comment]
![图片](https://github.com/user-attachments/assets/f53e9810-ff47-4bd9-a503-3f1894d74987)
类似于这种
![图片](https://github.com/user-attachments/assets/37fea5cf-e001-435b-aaa6-058376c15ccd)
它更加方便。

**Comment by al-one** [comment]
这里就是社区集成。。。
官方集成在这: https://github.com/XiaoMi/ha_xiaomi_home

**Comment by pyhofficial** [comment]
我是傻逼
