### ISSUE TITLE
Cammot login with mi cloud credentials

### ISSUE THREAD

**Issue by waudoglio** [al-one/hass-xiaomi-miot#231]
Hi, I'm driving crazy with this issue since a couple of weeks.

I had to reconfigure my home assistant and had to remove xiaomi miot auto integration which drove my dreame robot very well.

When I reconfigured all the stuff, I added back the integration but it now says my credentials are wrong!! Of course I checked them plenty of times and they work fine on mi account website and mi cloud website too!! 
The only guess I can do is that in both websites, after the insertion of login/password, system wants a confirmation code sent to my email or cellphone to finally let me in... maybe this step is the one that fails to complete in the integration. 
Am I the only one with this problem? 

Thanks in advance for the support

**Comment by kaosheng** [comment]
cant login , even if the email verify show ok, still cant log in
![xiaomi](https://user-images.githubusercontent.com/88337367/155842883-1c2a092e-39c0-46bb-8ef1-94a47c6a0a9c.jpg)
![xiaomi0](https://user-images.githubusercontent.com/88337367/155842914-fc6221ef-5452-4c28-b6e2-a3b1007eaf4c.jpg)

**Comment by kaosheng** [comment]
I copy wrong, first i try Xiaomi Miot Auto, can't login,so i change to Xiaomi Miot raw（this is ok, VM on local PC), Also cant login,the environment is VM On GCP , Debian with supervisor

**Comment by al-one** [comment]
@kaosheng Please re-create a new issue and provide an error message or logs.

**Comment by kaosheng** [comment]
Use vm on gcp to login is ok
