### ISSUE TITLE
请求支持ha11.0的Entity categorization功能

### ISSUE THREAD

**Issue by FaintGhost** [al-one/hass-xiaomi-miot#232]
感谢大大的custom_component非常好用！Ha 11月新出的功能，把设备的主要实体和部分不太常用的比如battery类的实体分组，看文档描述说custom_component也可以支持，希望下个版本可以支持！感谢！

**Comment by al-one** [comment]
最新提交 https://github.com/al-one/hass-xiaomi-miot/commit/99c55b946e75941f1048cffaf8078260058c2441 中已支持，预计[v0.4.10](https://github.com/al-one/hass-xiaomi-miot/releases)版本发布。

目前被标记为`config`的实体有：童锁、指示灯、氛围灯、灯/风扇的延时关闭及通电电状态配置
目前被标记为`diagnostic`的实体有：剩余电量

**Comment by FaintGhost** [comment]
速度好快！感恩大佬！
