### ISSUE TITLE
chuangmi.cateye.ipc018

### ISSUE THREAD

**Issue by balbulator** [al-one/hass-xiaomi-miot#235]
Hello.
Tell me, are you planning to support chuangmi.cateye.ipc018, which at the moment of integration only gives a battery charge and a screenshot of a random freeze frame?
Device: Xiaobai Smart Camera Doorbell Cat Eye
Model: CMMY18A
Object: camera.chuangmi_ipc018
Software version: 4.0.9_2313
thanks

**Comment by al-one** [comment]
The [miot-spec](https://home.miot-spec.com/spec/chuangmi.cateye.ipc018) of the device only provides a `battery-level` property, and currently this component can only view the screenshots of the video doorbell/camera.
