### ISSUE TITLE
小米电视xiaomi.tv.rmh1缩略图（屏幕截图）有时无法显示

### ISSUE THREAD

**Issue by MageDelfador** [al-one/hass-xiaomi-miot#236]
今天发现这个media_player.xiaomi_rmh1_eee1_play_control_2实体没有图标（内容是屏幕截图）显示了，并且日志报错。昨天还是正常显示的。日志报错的原因是实体media_player.xiaomi_rmh1_eee1_play_control_2的capture属性值为
http://null:6095/request?action=getResource&name=screenCapture&timestamp=*******
url里出现了一个null，导致无法访问并报错
之后抓了个包：

插件->电视	
GET /controller?action=capturescreen&compressrate=100&timestamp=1636300018646&opaque=65f4df14b38d161da938c586c359b397b307b10a HTTP/1.1 
电视->插件
{

"status":0,

"msg":"success",

"data":{"code":0,"url":"http:\/\/null:6095\/request?action=getResource&name=screenCapture","pkg":"com.xiaodianshi.tv.yst","label":"äºè§å¬å°çµè§","clz":"com.xiaodianshi.tv.yst.ui.main.MainActivity","token":"pm7rVsfcdgAAFHVj","extra":{}}

}

电视返回的url中确实带null。把null修改为电视的ip地址后访问，截图正常显示。据此猜测电视有时候不返回IP地址，建议处理下url中地址为null的情况

**Comment by al-one** [comment]
请在电视在线的时候通过集成选项更新设备列表并保存，以获取电视设备最新的IP。另外我将添加通过自定义属性的方式来指定电视IP。

**Comment by MageDelfador** [comment]
感谢深夜回复，尝试更新了列表，但是没有起作用。刚才看了下插件的代码，在media_player.py 中169行

```
    async def async_update(self):
        await super().async_update()
        if not self._available:
            return
        adt = {}

        pms = self.with_opaque({
            'action': 'capturescreen',
            'compressrate': 100,
        })
        rdt = await self.async_request_mitv_api('controller', params=pms)
        if 'url' in rdt:
            url = rdt.get('url', '')
            pms = urlparse(url).query
            url = f'{url}'.replace(pms, '')
            pms = dict(parse_qsl(pms))
            pms = self.with_opaque(pms, token=rdt.get('token'))
            self._attr_media_image_url = url + urlencode(pms)
            self._attr_app_id = rdt.get('pkg')
            self._attr_app_name = rdt.get('label')
            adt.update({
                'capture': self._attr_media_image_url,
                'capture_token': rdt.get('token'),
                'app_current': f'{self._attr_app_name} - {self._attr_app_id}',
                'app_page': rdt.get('clz'),
            })
```

可以看到插件没有处理电视返回url中的IP地址，是直接复制到capture属性中的。需要对电视返回null的情况单独处理一下。

**Comment by al-one** [comment]
原来是电视返回的IP为`null`，已修复，请更新到master分支后尝试。

**Comment by MageDelfador** [comment]
测试一切正常
