### ISSUE TITLE
device:vacuum:0000A006:roborock-a01 cant get status

### ISSUE THREAD

**Issue by komOrmand** [al-one/hass-xiaomi-miot#237]
```
entity_class: MiotRoborockVacuumEntity
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:roborock-a01:1
vacuum.status.error: '-704010000 Unknown'
vacuum.mode.error: '-704030013 Property is not readable'
state_updater: cloud
```

I can send the commands, but yhe status is empty.

**Comment by al-one** [comment]
Fixed for [roborock.vacuum.a01](https://home.miot-spec.com/s/roborock.vacuum.a01) in commit: https://github.com/al-one/hass-xiaomi-miot/commit/f38a659fee22a1b6811c3240d4a2deca7e5ab7c7

**Comment by komOrmand** [comment]
yeap fixed! thanks!
almost ok, just not showing the battery state

**Comment by al-one** [comment]
Try https://github.com/al-one/hass-xiaomi-miot/commit/e256ee7e7ee37f7e2586479888e76aa560b5753d

**Comment by komOrmand** [comment]
Ok, ill try, just found 
![Screenshot_2](https://user-images.githubusercontent.com/87458360/140871833-823e1a84-2bb8-4941-b42a-73e609c687f8.png)
