### ISSUE TITLE
米家地暖温控器控制缺失？（开，关，改变模式等）

### ISSUE THREAD

**Issue by supern001** [al-one/hass-xiaomi-miot#239]
您好，我添加了米家地暖温控器[suittc.airrtc.wk168](https://home.miot-spec.com/s/suittc.airrtc.wk168)，可以读取到环境温度和设定温度，但是没有找到开，关或者改变模式等功能的方法。求助，先谢过。
![138497555-e099f5b7-0924-4fdb-80a1-f2e1c1fe7368](https://user-images.githubusercontent.com/92826092/140972005-ef1685dc-d56b-471f-8d79-35e1805a78ff.jpeg)
![Screenshot 2021-11-10 010947](https://user-images.githubusercontent.com/92826092/140972031-7fbad4f5-ec1e-4999-924f-9af802e7dddb.png)
![Screenshot 2021-11-10 011011](https://user-images.githubusercontent.com/92826092/140972058-c430de3a-df16-4a5c-af56-860db2636c82.png)

**Comment by al-one** [comment]
请更新到master分支后尝试。

**Comment by al-one** [comment]
请问有更新master分支并尝试吗？

**Comment by supern001** [comment]
> 请问有更新master分支并尝试吗？

不好意思，不太懂怎么更新到master分支。HA新人

**Comment by al-one** [comment]
好的，请等过两天插件新版本发布了更新后再试。

**Comment by supern001** [comment]
> 好的，请等过两天插件新版本发布了更新后再试。

ok, 期待

**Comment by al-one** [comment]
[v0.4.10](https://github.com/al-one/hass-xiaomi-miot/releases/latest)新版已发布，你可以更新后再试下。

**Comment by supern001** [comment]
> [v0.4.10](https://github.com/al-one/hass-xiaomi-miot/releases/latest)新版已发布，你可以更新后再试下。

可以了，感谢。
虽然操作方式稍微有点瑕疵，但已经能完全达到我想要的操作了。thx again.

**Comment by jianguooo** [comment]
你这款面板的背景灯 会频闪吗

**Comment by supern001** [comment]
> 你这款面板的背景灯 会频闪吗

不会

**Comment by jianguooo** [comment]
有购买连接吗 发我一个

**Comment by jianguooo** [comment]
> > 你这款面板的背景灯 会频闪吗
> 
> 不会

有购买连接吗 发我一个

**Comment by supern001** [comment]
> > > 你这款面板的背景灯 会频闪吗
> > 
> > 
> > 不会
> 
> 有购买连接吗 发我一个

taobao直接搜索米家 温控，很多

**Comment by jianguooo** [comment]
> > > > 你这款面板的背景灯 会频闪吗
> > > 
> > > 
> > > 不会
> > 
> > 
> > 有购买连接吗 发我一个
> 
> taobao直接搜索米家 温控，很多

我买了一款但是背景灯会频闪 ，suittc这家的
