### ISSUE TITLE
Loock Cateye v01

### ISSUE THREAD

**Issue by djmalin** [al-one/hass-xiaomi-miot#24]
Hello is posible add this integration (Loock Cateve v01)?

**Comment by al-one** [comment]
The last commit: https://github.com/al-one/hass-xiaomi-miot/commit/7642404b30eeecadf548764abb0685c43e28cda7 of [master](https://github.com/al-one/hass-xiaomi-miot/tree/master) already supports the device, but only supports the `battery-level` sensor and `motion_detection` binary sensor.
