### ISSUE TITLE
已添加的设备如何删除？

### ISSUE THREAD

**Issue by gy6221** [al-one/hass-xiaomi-miot#241]
如题，通过账号集成添加了一个空调伴侣，但没法删掉了
在include列表里把勾去掉也无效，设备还是在

**Comment by al-one** [comment]
Duplicate https://github.com/al-one/hass-xiaomi-miot/issues/165#issuecomment-899988208

**Comment by gy6221** [comment]
谢谢，建议添加到FAQ
