### ISSUE TITLE
Missing feature on deerma.humidifier.jsq3

### ISSUE THREAD

**Issue by chiksum** [al-one/hass-xiaomi-miot#242]
Hello,

I own a Xiaomi humidifier and connected it to home assistant via xiaomi miot auto successfully.
However, the alarm setting (beep sound) is missing. I see there is an alarm attribute on home.miot-spec.com said it can be read/write, but how can I?

Thanks.

**Comment by al-one** [comment]
Show me the [entity state attributes](https://my.home-assistant.io/redirect/developer_states).

**Comment by chiksum** [comment]
min_humidity: 40
max_humidity: 80
available_modes:
  - 'Off'
  - Level1
  - Level2
  - Level3
  - Humidity
humidity: 50
mode: Level1
model: deerma.humidifier.jsq3
lan_ip: 192.168.1.180
mac_address: 58:B6:23:1C:E2:FE
firmware_version: 2.0.3
hardware_version: RTL8720C
entity_class: MiotHumidifierEntity
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq3:1
humidifier.on: true
humidifier.fault: 0
humidifier.fan_level: 1
humidifier.target_humidity: 50
humidifier.target_temperature.error: '7'
custom.water_shortage_fault.error: '-4004 Other internal errors'
custom.the_tank_filed: false
indicator_light.on: true
alarm: false
environment.relative_humidity: 61
environment.temperature: 26
state_updater: lan
sub_entities:
  - environment-3.relative_humidity-1
  - environment-3.temperature-7
  - indicator_light-6
friendly_name: Xiaomi Air Humidifier Humidifier
supported_features: 1
device_class: humidifier

**Comment by al-one** [comment]
You can [add custom attribute](https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui):
```yaml
# customize.yaml
humidifier.deerma_jsq3_entity_id:
  switch_properties: alarm
```

**Comment by chiksum** [comment]
It's is working now
Thanks!

**Comment by dmatora** [comment]
Mine is deerma.humidifier.jsq
The state is
```
min_humidity: null
max_humidity: null
model: deerma.humidifier.jsq
lan_ip: 192.168.1.206
mac_address: 44:23:7C:BD:A5:89
firmware_version: 2.0.7
hardware_version: ''
entity_class: MiotHumidifierEntity
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq:1
humidifier.on: true
alarm: false
indicator_light.on: true
environment.relative_humidity: 86
environment.temperature: 23
state_updater: cloud
sub_entities:
  - environment-3.relative_humidity-1
  - environment-3.temperature-2
  - indicator_light-4
friendly_name: Humidifier Мила Humidifier
supported_features: 0
device_class: humidifier
```
is there a way to add water presence indicator?
