### ISSUE TITLE
有支撑的浴霸开关吗

### ISSUE THREAD

**Issue by jianguooo** [al-one/hass-xiaomi-miot#244]
支持列表里面翻找下没有看到有可以支持的浴霸开关

**Comment by al-one** [comment]
请问设备型号多少？
可以在[这里](https://home.miot-spec.com)找到你的设备吗？

**Comment by al-one** [comment]
如果你是在寻找米家支持的浴霸开关，可以试试[开关](https://home.miot-spec.com/s/%E6%B5%B4%E9%9C%B8%20%E5%BC%80%E5%85%B3)、[面板](https://home.miot-spec.com/s/%E6%B5%B4%E9%9C%B8%20%E9%9D%A2%E6%9D%BF)，对应的购买渠道需要你自己搜索下。

**Comment by Davie521** [comment]
您好 请问在这里能找到的设备都可以支持么 谢谢

**Comment by al-one** [comment]
这个不一定，也要看设备对miot协议的支持程度。你可以通过设备列表中的`规格`去了解设备定义了哪些服务属性，通常属性越多表示可控制的功能越多。

**Comment by jianguooo** [comment]
列表里面找了一圈，没找到

**Comment by al-one** [comment]
请参考下面issue提到的浴霸开关：
- https://github.com/al-one/hass-xiaomi-miot/issues/487
- 购买链接：https://s.click.taobao.com/3EVKQZu
