### ISSUE TITLE
小米厨下式净水器无法获取滤芯寿命等信息 型号：yunmi.waterpuri.lx3

### ISSUE THREAD

**Issue by CrazyMouse** [al-one/hass-xiaomi-miot#247]
![image](https://user-images.githubusercontent.com/1176862/141891840-d27bf519-4d3d-43ff-be2f-dcd55e3dcc39.png)
一共拿到这么些传感器，没有滤芯使用寿命，代码中也查不到lx3这个型号😅

**Comment by al-one** [comment]
由于该设备的[miot-spec规格](https://home.miot-spec.com/spec/yunmi.waterpuri.lx3)中仅定义了滤芯已使用时长属性，没有定义剩余时长相关属性，因此无法通过miot协议获取剩余寿命。
不过你可以参开 https://github.com/al-one/hass-xiaomi-miot/issues/218#issuecomment-964712557 使用miio协议获取设备更多属性。

**Comment by CrazyMouse** [comment]
> 由于该设备的[miot-spec规格](https://home.miot-spec.com/spec/yunmi.waterpuri.lx3)中仅定义了滤芯已使用时长属性，没有定义剩余时长相关属性，因此无法通过miot协议获取剩余寿命。 不过你可以参开 [#218 (comment)](https://github.com/al-one/hass-xiaomi-miot/issues/218#issuecomment-964712557) 使用miio协议获取设备更多属性。

感谢回复

**Comment by CrazyMouse** [comment]
> 由于该设备的[miot-spec规格](https://home.miot-spec.com/spec/yunmi.waterpuri.lx3)中仅定义了滤芯已使用时长属性，没有定义剩余时长相关属性，因此无法通过miot协议获取剩余寿命。 不过你可以参开 [#218 (comment)](https://github.com/al-one/hass-xiaomi-miot/issues/218#issuecomment-964712557) 使用miio协议获取设备更多属性。

还想请教一个问题，既然是这样的话，那米家app上面展示的剩余时长和百分比是怎么得来的呢？是否有某种曲线救国的办法实现这个显示呢？

**Comment by al-one** [comment]
设备本身是有剩余寿命属性的，但是没有通过miot协议暴露出来。曲线救国的方式就是上面提到的 https://github.com/al-one/hass-xiaomi-miot/issues/218#issuecomment-964712557 ，不过需要你自己动手。

**Comment by CrazyMouse** [comment]
> 设备本身是有剩余寿命属性的，但是没有通过miot协议暴露出来。曲线救国的方法就是上面提到的 [#218 (comment)](https://github.com/al-one/hass-xiaomi-miot/issues/218#issuecomment-964712557) ，不过需要你自己动手。

我理解也就是说我去通过哪个apk开启debug模式，然后拿到属性的名称，然后自己自定义上这个属性就ok了对么？

**Comment by al-one** [comment]
是的。但是通过上面的方法获取的属性不是作为单独的实体，而是存在于实体状态的属性中。你可能还需要[template](https://www.home-assistant.io/integrations/template#state-based-template-sensors)将属性作为传感器实体，参考：https://github.com/al-one/hass-xiaomi-miot/issues/223#issuecomment-954640424

**Comment by CrazyMouse** [comment]
> 是的。但是通过上面的方法获取的属性不是作为单独的实体，而是存在于实体状态的属性中。你可能还需要[template](https://www.home-assistant.io/integrations/template#state-based-template-sensors)将属性作为传感器实体，参考：[#223 (comment)](https://github.com/al-one/hass-xiaomi-miot/issues/223#issuecomment-954640424)

这个我会处理，非常感谢

**Comment by CrazyMouse** [comment]
> 是的。但是通过上面的方法获取的属性不是作为单独的实体，而是存在于实体状态的属性中。你可能还需要[template](https://www.home-assistant.io/integrations/template#state-based-template-sensors)将属性作为传感器实体，参考：[#223 (comment)](https://github.com/al-one/hass-xiaomi-miot/issues/223#issuecomment-954640424)
由于没有andorod设备，只好去github找别人的代码，发现 [这里](https://github.com/biner88/homebridge-mi-waterpuri/blob/master/Devices/MiWaterPurifier.js) 有自定义的properties

![image](https://user-images.githubusercontent.com/1176862/141949159-b6ba4b5c-645e-492d-815f-9b111892bd6a.png)

然后配置
`sensor.yunmi_lx3_e256_water_purifier:
  miio_props: f1_totaltime,f2_totaltime,f3_totaltime,f4_totaltime,,f5_totaltime,f6_totaltime,f7_totaltime`
无法获取数据，后来发现需要修改成
`sensor.yunmi_lx3_e256_water_purifier:
  miio_cloud_props: f1_totaltime,f2_totaltime,f3_totaltime,f4_totaltime,,f5_totaltime,f6_totaltime,f7_totaltime` _即可，剩下的就好办了，在这里备忘一下，哈哈

**Comment by al-one** [comment]
自定义属性`miio_cloud_props`是从小米云端获取属性，推荐使用`miio_properties`通过局域网直接从设备获取（而不是`miio_props`）：
```yaml
sensor.yunmi_lx3_e256_water_purifier:
  miio_properties: f1_totaltime,f2_totaltime,f3_totaltime,f4_totaltime,,f5_totaltime,f6_totaltime,f7_totaltime
```

**Comment by CrazyMouse** [comment]
> [自定义属性](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)`miio_cloud_props`是从小米云端获取属性，推荐使用`miio_properties`通过局域网直接从设备获取（而不是`miio_props`）：
> 
> ```yaml
> sensor.yunmi_lx3_e256_water_purifier:
>   miio_properties: f1_totaltime,f2_totaltime,f3_totaltime,f4_totaltime,,f5_totaltime,f6_totaltime,f7_totaltime
> ```

收到，非常感谢

**Comment by CrazyMouse** [comment]
> [自定义属性](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)`miio_cloud_props`是从小米云端获取属性，推荐使用`miio_properties`通过局域网直接从设备获取（而不是`miio_props`）：
> 
> ```yaml
> sensor.yunmi_lx3_e256_water_purifier:
>   miio_properties: f1_totaltime,f2_totaltime,f3_totaltime,f4_totaltime,,f5_totaltime,f6_totaltime,f7_totaltime
> ```

![image](https://user-images.githubusercontent.com/1176862/141957359-1939dfee-47f4-4d70-9716-b224630e000a.png)
con从局域网貌似只能获取第一个数据，具体原因不清楚
