### ISSUE TITLE
looks like the MJSXJ09CM camera isn't supported

### ISSUE THREAD

**Issue by jaimyborgman** [al-one/hass-xiaomi-miot#25]
Hi, first of all, great to see this module!

Currently trying to set up my Mi 360 Home Security Camera 2K with it, while getting the token and successfully added it via the integrations page. I'm not getting much info from it, it also says "unavailable" in the entities overview.

Could anyone confirm if the camera type is supported?

**Comment by al-one** [comment]
Have you enabled [miot_cloud](https://github.com/al-one/hass-xiaomi-miot#configuration-xiaomi-cloud).

> Configuration > Integrations > Xiaomi Miot Auto > Options > Enable miot cloud

**Comment by jaimyborgman** [comment]
yes I've enabled could, but that didn't make any change, after that, I've decided to manually put the `xiaomi_miot` section into my configuration with the correct server specified which helped a step further and now I'm also seeing 2 entities from that integration which both are available

so it looks like the camera is available, but I'm not seeing any image when clicking on it so no screens it shows a browser broken image icon any idea what that could be? I'm running home assistant on a raspberry pi btw :)

**Comment by jaimyborgman** [comment]
btw after rebooting home assistant the camera was gone again so it looks a little bit glitchy

**Comment by al-one** [comment]
Get the `stream_address` from the entity state attributes (Developer tools > [State](https://my.home-assistant.io/redirect/developer_states)), and test whether it can play through VLC and other players.
