### ISSUE TITLE
cuco.plug.cp2 接入失败

### ISSUE THREAD

**Issue by tangxingjie1991** [al-one/hass-xiaomi-miot#252]
![227C4B1A-6458-4D82-92D3-65C3E652BD2B](https://user-images.githubusercontent.com/42593245/142625196-4ebd257a-3f2b-48f4-9d08-6a22851e1b88.png)

**Comment by al-one** [comment]
https://github.com/al-one/hass-xiaomi-miot/blob/c79e7b90f1948b91087508dc4415a8705e7a0a29/custom_components/xiaomi_miot/core/miot_local_devices.py#L30

由于误以为该设备能支持本地模式加入[本地设备型号列表](https://github.com/al-one/hass-xiaomi-miot/blob/master/custom_components/xiaomi_miot/core/miot_local_devices.py#L30)，导致该设备使用本地miot模式连接，你需要通过[添加自定义属性](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)使其通过云端模式连接：
```yaml
# customize.yaml
switch.cuco_cp2_entity_id:
  miot_cloud: true
```

我将在下个版本将该设备从列表中去除。

**Comment by al-one** [comment]
[v0.4.11](https://github.com/al-one/hass-xiaomi-miot/releases/latest)版本中修复了该问题并已发布，请更新后在观察该设备的实体是都可用。
