### ISSUE TITLE
添加用电量支持 cuco.plug.cp5pro

### ISSUE THREAD

**Issue by MapleEve** [al-one/hass-xiaomi-miot#253]
https://home.miot-spec.com/spec/cuco.plug.cp5pro

entity_class: MiotSensorSubEntity 
parent_entity_id: switch.cuco_cp5pro_dbc1_usb_switch_status 
service_description: Power Consumption 
property_description: Power Consumption 
power_consumption: 0 
unit_of_measurement: Wh 
friendly_name: 沙发插头用电 
supported_features: 0

**Comment by MapleEve** [comment]
上述传感器名称 sensor.cuco_cp5pro_1490_power_consumption

**Comment by al-one** [comment]
`power_consumption`属性由于没有描述其计量周期，因此这个属性无法作为电量统计。

请更新到master分支后尝试有无电量统计实体。

**Comment by MapleEve** [comment]
> `power_consumption`属性由于没有描述其计量周期，因此这个属性无法作为电量统计。
> 
> 请更新到master分支后尝试有无电量统计实体。

Entity class
BaseSensorSubEntity
Parent entity ID
switch.cuco_cp5pro_dbc1_switch_5
Power cost month
0.201

Entity class
BaseSensorSubEntity
Parent entity ID
switch.cuco_cp5pro_1490_switch_5
Power cost month
0.1

两个插线板都有了数值，直接用任意一个即可？

**Comment by al-one** [comment]
`Power cost month`为月度用电，`Power cost today`为今日用电。

**Comment by MapleEve** [comment]
插头的功率是 watt，可以统一成 W 么

**Comment by MapleEve** [comment]
过了12点了，插座50W 跑了俩小时，功率下面没有任何数值了


```
2021-11-20 21:58:37 WARNING (MainThread) [homeassistant.components.energy.sensor] Found unexpected state_class None for sensor.cuco_cp5pro_dbc1_power_cost_today
2021-11-20 21:58:37 WARNING (MainThread) [homeassistant.components.energy.sensor] Found unexpected state_class None for sensor.cuco_cp5pro_1490_power_cost_today
```

```
state_class: total_increasing
entity_class: BaseSensorSubEntity
parent_entity_id: switch.cuco_cp5pro_dbc1_switch_3
power_cost_today: 0
unit_of_measurement: kWh
friendly_name: 沙发插板日
supported_features: 0
device_class: energy

```


不知道这个是不是按照每个 switch 来单独统计的，因为另外一个同样的插板 `parent_entity_id` 是 USB 接口，接了 Homepod，所以今日有 0.0XX 的数据

**Comment by al-one** [comment]
统计数据来自米家云端，目前我所看到过的插座都是整个设备的电量统计，没有单个switch统计的。你可以查看米家上的电量统计数据是否与HA中一致。

**Comment by MapleEve** [comment]
> 统计数据来自米家云端，目前我所看到过的插座都是整个设备的电量统计，没有单个switch统计的。你可以查看米家上的电量统计数据是否与HA中一致。

![image](https://user-images.githubusercontent.com/1845053/142755508-183aee5c-0996-41c6-9c3c-ff4c2b90fcb8.png)

字段内是0.038，米家是 0.04，但是 HA 里面取值是 0.0

**Comment by al-one** [comment]
请再次更新后观察下。另外该设备的[miot-spec规格](https://home.miot-spec.com/spec/cuco.plug.cp5pro)中并无功率相关属性。

**Comment by al-one** [comment]
请问用电量正确了吗？

**Comment by MapleEve** [comment]
> 请问用电量正确了吗？

还是不正常，我把这个设备共享给Alone2了

![C1616F98-91D9-4970-AA9E-54CA145DD89F](https://user-images.githubusercontent.com/1845053/143073205-d5993505-f528-4525-b18c-ac6937e57e2c.png)

昨天烧了个火锅，但是统计仍然是0

**Comment by al-one** [comment]
已修复。
