### ISSUE TITLE
philips.light.bulb本地接入失败

### ISSUE THREAD

**Issue by fromthink** [al-one/hass-xiaomi-miot#254]
我看代码[MIOT_LOCAL_MODELS](https://github.com/al-one/hass-xiaomi-miot/blob/master/custom_components/xiaomi_miot/core/miot_local_devices.py) 里有[philips.light.bulb](https://home.miot-spec.com/s/philips.light.bulb)，但是无法本地接入，提示
错误信息: {'code': -10000, 'message': 'Method not found.'}

该设备不支持本地接入，已启用云端接入。请再次点击“提交”
这是什么原因呢

**Comment by al-one** [comment]
从插件收集的数据来看，该设备在固件版本`2.0.8_0003`及以上是支持本地接入的，但是我不确定是否所有人都可以升级到此固件。如果不能升级固件，我会考虑把该设备型号从`MIOT_LOCAL_MODELS`列表中移除。

------

> 该设备不支持本地接入，已启用云端接入。请再次点击“提交”

另外，该错误提示不是本插件提示的。

**Comment by fromthink** [comment]
确实，我的设备固件版本较低，而且无法在线更新。谢谢

**Comment by al-one** [comment]
我已经在刚才的提交 https://github.com/al-one/hass-xiaomi-miot/commit/4ae54532d59740a223ab9c02990987f7bbf67f58 中把该设备型号从`MIOT_LOCAL_MODELS`列表中移除，你可以升级到master分支或等待下个版本再次尝试。

**Comment by al-one** [comment]
[v0.4.11](https://github.com/al-one/hass-xiaomi-miot/releases/latest)版本中修复了该问题并已发布，请更新后在观察该设备的实体是都可用。

**Comment by al-one** [comment]
该设备已在[v0.5.0](https://github.com/al-one/hass-xiaomi-miot/releases/latest)版本中适配本地模式。
