### ISSUE TITLE
大神又来麻烦您了。能把米家电磁炉接入吗?

### ISSUE THREAD

**Issue by ilongjiang** [al-one/hass-xiaomi-miot#257]
型号是[chunmi.ihcooker.v1](https://home.miot-spec.com/s/chunmi.ihcooker.v1)，米家最早的电磁炉。接入后发现没有实体

**Comment by al-one** [comment]
请检查下有无该设备相关[日志](https://my.home-assistant.io/redirect/logs)。

**Comment by al-one** [comment]
根据该设备的[miot-spec规格](https://home.miot-spec.com/spec/chunmi.ihcooker.v1)显示，`status`属性没有读取权限，应该就是没有实体的原因。

**Comment by al-one** [comment]
已适配该设备本地接入，请更新至master分支后尝试。
