### ISSUE TITLE
能否允许云台版摄像头旋转？

### ISSUE THREAD

**Issue by Max-Sum** [al-one/hass-xiaomi-miot#259]
希望能实现云台摄像头在回家的时候自动旋转到面壁、出门时自动旋转回来。
可惜小米摄像头不支持ONVIF

**Comment by al-one** [comment]
你可以尝试使用小爱音箱控制转向试试，如果可以控制，可以通过本插件接入小爱音箱后使用`xiaomi_miot.intelligent_speaker`服务控制。
