### ISSUE TITLE
Option to switch between fan modes

### ISSUE THREAD

**Issue by jschonenberg** [al-one/hass-xiaomi-miot#26]
First of all, great work with this plugin! It works perfectly with my Yeelight ceiling fan. 

A minor thing I'm missing though is the ability to control fan mode. In the app it offers the options "direct" and "natural mode". There's also a third mode which changes the direction in which the fan turns. 

Could support for these features be added to the plugin?

**Comment by al-one** [comment]
As I know, yeelink has only one ceiling fan: `yeelink.ven_fan.vf1`. Is that yours ?

**Comment by jschonenberg** [comment]
I have the `yeelink.light.fancl2`, which is named Yeelight Ceiling Fan S2001 in the Mii Home app.

**Comment by al-one** [comment]
You can upgrade HA to 2021.3.0b0+ (Pre-release). It supports preset modes.
https://github.com/home-assistant/core/pull/45407

You also need to upgrade `hass-xiaomi-miot` to [v0.2.6](https://github.com/al-one/hass-xiaomi-miot/releases/latest).

**Comment by jschonenberg** [comment]
Great! Good to hear it's being worked on. I'll just wait until it's in the regular HA release though.
