### ISSUE TITLE
通过homeassistant接入到homekit只有温度显示，无法调节怎么处理

### ISSUE THREAD

**Issue by jianguooo** [al-one/hass-xiaomi-miot#262]
[suittc.airrtc.wk168](https://home.miot-spec.com/s/suittc.airrtc.wk168) 这个地暖温控器在homekit里面只能显示当前温度无法调温怎么办
![AB047AB9-A6DE-4575-B670-A6A58F4E4E51](https://user-images.githubusercontent.com/16218132/143729143-fd611b72-b4a7-4ba1-a676-54bfa789b0a0.jpeg)
![Uploading 40C40408-639E-403E-B6F1-7B77E5AF5D56.png…]()

**Comment by al-one** [comment]
在HA中能否调节温度？

**Comment by al-one** [comment]
另外你的第二张图片未上传完成。请重新上传下。
