### ISSUE TITLE
zimi.switch.dhkg02（米家智能双控开关）无法控制的问题

### ISSUE THREAD

**Issue by hikinsley** [al-one/hass-xiaomi-miot#263]
zimi.switch.dhkg02这个可以识别，但是无法控制。

**Comment by hikinsley** [comment]
https://home.miot-spec.com/s/zimi.switch.dhkg02

**Comment by hikinsley** [comment]
开关的固件是最新版本：1.4.4_0088

**Comment by hikinsley** [comment]
目前是接入到HomeAssistant，然后通过Xiaomi miot auto接入到home kit
zimi.switch.dhkg02这个开关无论是HomeAssistant还是home kit都无法控制，也看不到开关状态

**Comment by al-one** [comment]
请提供下实体[状态属性](https://my.home-assistant.io/redirect/developer_states)和[日志](https://my.home-assistant.io/redirect/logs)。

**Comment by al-one** [comment]
请检查下集成配置选项中有没有勾选该设备被拆分出来的按键设备，如有需要取消勾选。

**Comment by al-one** [comment]
我已经在最新的提交 https://github.com/al-one/hass-xiaomi-miot/commit/1dc16a2d9c7bc8a0bf0952c6fbd859c8073aaa17 中将拆分后的虚拟按键设备过滤（貌似升级到米家7.0后，即使未手动拆分按键，米家的设备列表接口也会拿到被拆分的按键），请升级到master分支后尝试。

如下图中的`左键` `右键`为`卫生间 灯`这个设备的两个虚拟按键设备，在米家APP中其实并未开启拆分，可是米家接口仍能获取到，插件将从下个版本开始过滤此类虚拟按键设备。
![.](https://user-images.githubusercontent.com/4549099/143802161-9034cc87-7bbb-42ed-99fd-690f7a878157.png)

**Comment by hikinsley** [comment]
好的，谢谢大佬解答。
我最近较忙，过几天我实践一下。😘

**Comment by al-one** [comment]
升级到最新的v0.4.11版本即可。

**Comment by hikinsley** [comment]
nice，完美解决。
感谢
