### ISSUE TITLE
Aqara门窗传感器数据和实际情况正相反

### ISSUE THREAD

**Issue by imoasislee** [al-one/hass-xiaomi-miot#265]
当门窗关闭时，米家客户端显示正常，但ha获取到门窗开启。

**Comment by al-one** [comment]
请问设备具体型号是什么？能否在[此页面](https://home.miot-spec.com/s/magnet)中找到？

**Comment by imoasislee** [comment]
型号为E1（lumi.magnet.acn001） 由小米智能多模网关（lumi.gateway.mgl03）连接

**Comment by al-one** [comment]
如果可以，希望你将此设备通过米家共享给我（ID: 143050915），蓝牙/ZigBee设备可能需要先共享网关才可以共享子设备。

**Comment by imoasislee** [comment]
已尝试共享网关 麻烦查看一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Alone ***@***.***&gt;
发送时间: 2021年11月30日 17:09
收件人: al-one/hass-xiaomi-miot ***@***.***&gt;
抄送: OasisLee ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [al-one/hass-xiaomi-miot] Aqara门窗传感器数据和实际情况正相反 (Issue #265)

**Comment by lkisme** [comment]
可以试一下：reverse_state: true  # 反转开关状态（仅作用于Binary Sensor）

**Comment by al-one** [comment]
我在最新的提交 https://github.com/al-one/hass-xiaomi-miot/commit/d073b31495688c5374352143f4ffd2ed4603c0cc 中修复了此问题（感谢@lkisme），你可以升级到master分支尝试。
