### ISSUE TITLE
lumi.acpartner.v3 set fan-level failed

### ISSUE THREAD

**Issue by foXaCe** [al-one/hass-xiaomi-miot#266]
hello
my  [lumi.acpartner.v3](https://home.miot-spec.com/s/lumi.acpartner.v3) do not work
why ?

Air Conditioner: Set miot property {'did': '134963433', 'siid': 3, 'piid': 1, 'value': 1} failed, result: {'did': '134963433', 'siid': 3, 'piid': 1, 'code': -706010002, 'exe_time': 0}

**Comment by al-one** [comment]
Error code `-706010002` means `Service does not exist`, it is returned by Xiaomi cloud. Maybe you can check whether the device firmware is up-to-date.

**Comment by foXaCe** [comment]
yes the firmware is up to date   

lastest version  1.4.1_162.0149

**Comment by foXaCe** [comment]
do you need more log?

**Comment by al-one** [comment]
Maybe you can try: https://github.com/syssi/xiaomi_airconditioningcompanion

**Comment by al-one** [comment]
Unfortunately, the miot-spec protocol used in this component can only support the device in the cloud mode, but Xiaomi cloud can not normally control the fan level, so there is nothing to do about it.
