### ISSUE TITLE
空气净化器无法使用

### ISSUE THREAD

**Issue by xztxy** [al-one/hass-xiaomi-miot#27]
![image](https://user-images.githubusercontent.com/31698398/109902910-085b9f80-7cd6-11eb-8b3f-21757e446484.png)
![image](https://user-images.githubusercontent.com/31698398/109902933-101b4400-7cd6-11eb-9eca-527ca6e1d410.png)
麻烦你看下~~谢谢！

**Comment by al-one** [comment]
- 请升级插件到最新的v0.2.6版本
- 请打开climate实体弹出层卡片，并测试运行模式及预设模式是否可以正常控制
- 请进入 `配置 > 状态` 筛选该设备的climate实体，并将状态反馈给我
- 请进入 `配置 > 日志` 检查有无本插件或该设备相关日志

**Comment by xztxy** [comment]
> * climate

![image](https://user-images.githubusercontent.com/31698398/109905004-1101a500-7cd9-11eb-9a1c-da822e74e1ed.png)
![image](https://user-images.githubusercontent.com/31698398/109905122-44443400-7cd9-11eb-8ba9-a01b907571a0.png)
麻烦了

**Comment by al-one** [comment]
请进入 `配置 > 日志` 检查有无本插件或该设备相关日志

**Comment by xztxy** [comment]
> 请进入 `配置 > 日志` 检查有无本插件或该设备相关日志

![image](https://user-images.githubusercontent.com/31698398/109906021-af423a80-7cda-11eb-8863-78451eaa28c5.png)
就看到这一条

**Comment by al-one** [comment]
> ![image](https://user-images.githubusercontent.com/31698398/109906021-af423a80-7cda-11eb-8863-78451eaa28c5.png)
> 就看到这一条

这条报错也像是云端模式未准备好导致的，请问现在实体还是不可用状态吗？

**Comment by xztxy** [comment]
> > ![image](https://user-images.githubusercontent.com/31698398/109906021-af423a80-7cda-11eb-8863-78451eaa28c5.png)
> > 就看到这一条
> 
> 这条报错也像是云端模式未准备好导致的，请问现在实体还是不可用状态吗？

好的，我检查下，我把整个环境重新做下。再试试，~先关了谢谢~~
