### ISSUE TITLE
小米门窗传感器2 在HA中出现了显示的开关状态与实际状态相反的状况

### ISSUE THREAD

**Issue by usefrancisco3210** [al-one/hass-xiaomi-miot#270]
小米门窗传感器2 在米家中显示状态显示正常，在HA中显示的开关状态与实际状态相反。
设备信息
[isa.magnet.dw2hl](https://home.miot-spec.com/s/isa.magnet.dw2hl)
制造商：isa
固件：1.1.1_0041

**Comment by wang-bing323** [comment]
我这也遇到同样的问题，门明明关着，米家APP里面也显示关的，但HA里显示开着的

**Comment by al-one** [comment]
请更新到master分支后再尝试。

**Comment by wang-bing323** [comment]
更新到master后还是同样的问题 @al-one

**Comment by al-one** [comment]
@wang-bing323 我自己测试已经没有问题了，如果你的设备状态还是反的，请提供实体属性。

![image](https://user-images.githubusercontent.com/4549099/144201690-e677ebcc-4f1e-4f4d-b8c2-7272986d30f7.png)

**Comment by wang-bing323** [comment]
你好，我这边门磁状态是反的








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "al-one/hass-xiaomi-miot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月1日(星期三) 下午4:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [al-one/hass-xiaomi-miot] 小米门窗传感器2 在HA中出现了显示的开关状态与实际状态相反的状况 (Issue #270)





 
@wang-bing323 我自己测试已经没有问题了，如果你的设备状态还是反的，请提供实体属性。
 

 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wang-bing323** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "al-one/hass-xiaomi-miot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月1日(星期三) 下午4:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [al-one/hass-xiaomi-miot] 小米门窗传感器2 在HA中出现了显示的开关状态与实际状态相反的状况 (Issue #270)





 
@wang-bing323 我自己测试已经没有问题了，如果你的设备状态还是反的，请提供实体属性。
 

 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by al-one** [comment]
@wang-bing323 请提供[实体属性](https://my.home-assistant.io/redirect/developer_states)和设备型号。

**Comment by wang-bing323** [comment]
![image](https://user-images.githubusercontent.com/90600723/144203627-81d08874-25b5-4bd3-9ba0-f48f5cfabeef.png)
![image](https://user-images.githubusercontent.com/90600723/144203626-b09e1f10-e58a-405c-bb04-aea125f07a51.png)
![image](https://user-images.githubusercontent.com/90600723/144203625-840f325f-1983-4f27-b1bb-98744320c951.png)

**Comment by wang-bing323** [comment]
wechat:32996758,能否加下详聊？

**Comment by leokklai** [comment]
I have the same issue that the on/off status is reversed on door sensor after Xiaomi MIoT upgraded.

**Comment by wang-bing323** [comment]
在@al-one 大佬指导下已解决，谢谢！
@leokklai hacs里更新可能不能解决问题，直接手动下载替换

**Comment by leokklai** [comment]
> 在@al-one 大佬指導下已解決，謝謝！ @leokklai hacs裏更新可能不能解決問題，直接手動下載替換

手動更新了, 但問題仍在.. 

Device: binary_sensor.dw2hl_cloud_g85o01_state
Status: **On**

model: isa.magnet.dw2hl
firmware_version: 1.1.1_0041
hardware_version: N/A for Cloud Mode
magnet_sen_illumination: Weak
magnet_sen_contact_state: **true**
battery_battery_level: 5
friendly_name: 客廳門窗感應器 Magnet sen contact state
device_class: door

**Comment by al-one** [comment]
@leokklai 

> binary_sensor.dw2hl_cloud_g85o01_state

从这个实体ID看起来，该实体并不是由本插件生成，应该是另一个miot插件生成的实体。

**Comment by usefrancisco3210** [comment]
大佬，我刚刚手动替换了整个插件文件，重启了HA，重新添加了集成，重新添加了设备，但是不知道发生了什么，状况如故。
![20211201](https://user-images.githubusercontent.com/92283999/144228932-f32c1427-424e-4f16-a408-50b8b66487a2.png)

**Comment by al-one** [comment]
@usefrancisco3210 

请在更新插件代码后检查文件`custom_components/xiaomi_miot/core/device_customizes.py`中是否包含以下代码：
https://github.com/al-one/hass-xiaomi-miot/blob/b3012d67801c23a4fa59d2a9dd41612d89d9a359/custom_components/xiaomi_miot/core/device_customizes.py#L152-L154

> 另外，更新插件无需重新添加集成。

**Comment by leokklai** [comment]
> @usefrancisco3210
> 
> 請在更新插件代碼後檢查文件`custom_components/xiaomi_miot/core/device_customizes.py`中是否包含以下代碼：
> 
> https://github.com/al-one/hass-xiaomi-miot/blob/b3012d67801c23a4fa59d2a9dd41612d89d9a359/custom_components/xiaomi_miot/core/device_customizes.py#L152-L154
> 
> > 另外，更新插件無需重新添加集成。

已檢查了已包含以上代碼, 重啟了仍是反轉了... 

另外也試了用False, 但情況沒有改善, 感覺好像不是用model: isa.magnet.dw2hl?

```
    'isa.magnet.dw2hl': {
        'reverse_state': False,
    },
```

**Comment by al-one** [comment]
@leokklai 

> Device: binary_sensor.dw2hl_cloud_g85o01_state

你说的如果是这个实体，那肯定没有效果，因为这个实体不是由本插件生成的。

**Comment by leokklai** [comment]
> binary_sensor.dw2hl_cloud_g85o01_stat

但很奇怪在整合那裡看到是在用Xiaomi MIoT:
```
裝置: 客廳門窗感應器
廠牌: Isa
型號: isa.magnet.dw2hl
整合: Xiaomi MIoT
```

**Comment by al-one** [comment]
> 但很奇怪在整合那裡看到是在用Xiaomi MIoT:

@leokklai 本项目插件显示名称为`Xiaomi Miot Auto`，插件域为`xiaomi_miot`

**Comment by leokklai** [comment]
> > 但很奇怪在整合那裡看到是在用Xiaomi MIoT:
> 
> @leokklai 本項目插件顯示名稱爲`Xiaomi Miot Auto`，插件域爲`xiaomi_miot`

明白了, 原來我看錯了插件.. 謝謝你熱心的回答及抱歉打擾了你~ m(=_=)m

**Comment by usefrancisco3210** [comment]
> > @usefrancisco3210
> > 請在更新插件代碼後檢查文件`custom_components/xiaomi_miot/core/device_customizes.py`中是否包含以下代碼：
> > https://github.com/al-one/hass-xiaomi-miot/blob/b3012d67801c23a4fa59d2a9dd41612d89d9a359/custom_components/xiaomi_miot/core/device_customizes.py#L152-L154
> > 
> > > 另外，更新插件無需重新添加集成。
> 
> 已檢查了已包含以上代碼, 重啟了仍是反轉了...
> 
> 另外也試了用False, 但情況沒有改善, 感覺好像不是用model: isa.magnet.dw2hl?
> 
> ```
>     'isa.magnet.dw2hl': {
>         'reverse_state': False,
>     },
> ```

感谢大佬的耐心指引，该问题已经成功解决！出现问题的原因是在于custom_components文件夹内除了本插件以外，还有有另外一个在HA集成里名为“xiaomi miio”的插件所建立的系统文件夹(xiaomi_miot)。
由于两个插件的文件夹名相同(xiaomi_miot)，里面的文件名device_customizes.py也一样。因此造成了上述的错误。我把”xiaomi miio”插件的“xiaomi_miot“文件夹全部删除后，问题得到完美解决。

**Comment by usefrancisco3210** [comment]
> @usefrancisco3210
> 
> 请在更新插件代码后检查文件`custom_components/xiaomi_miot/core/device_customizes.py`中是否包含以下代码：
> 
> https://github.com/al-one/hass-xiaomi-miot/blob/b3012d67801c23a4fa59d2a9dd41612d89d9a359/custom_components/xiaomi_miot/core/device_customizes.py#L152-L154
> 
> > 另外，更新插件无需重新添加集成。

感谢大佬的耐心指引，该问题已经成功解决！出现问题的原因是在于custom_components文件夹内除了本插件以外，还有有另外一个在HA集成里名为“xiaomi miio”的插件所建立的系统文件夹(xiaomi_miot)。
由于两个插件的文件夹名相同(xiaomi_miot)，里面的文件名device_customizes.py也一样。因此造成了上述的错误。我把”xiaomi miio”插件的“xiaomi_miot“文件夹全部删除后，问题得到完美解决。

**Comment by al-one** [comment]
@usefrancisco3210 `xiaomi miio`集成的目录不在`custom_components`目录中，`xiaomi_miot`目录就是本插件的目录。

**Comment by usefrancisco3210** [comment]
> @usefrancisco3210 `xiaomi miio`集成的目录不在`custom_components`目录中，`xiaomi_miot`目录就是本插件的目录。

感谢大佬的耐心指引，我想我知道原因了！

**Comment by icceey** [comment]
[lumi.sensor_magnet.aq2](https://home.miot-spec.com/spec/lumi.sensor_magnet.aq2) 这个门窗传感器显示的状态也是反的

**Comment by jifengmm** [comment]
我也遇到了，但是我的device_customizes.py 没有上述代码

**Comment by al-one** [comment]
此次提交的代码 (https://github.com/al-one/hass-xiaomi-miot/commit/8cd3c0d19ff3342df431e90d0ae5ca41e55c7fd4) 反转了门窗传感器的状态，根据[`contact-state`](https://miot-spec.org/miot-spec-v2/spec/property?type=urn:miot-spec-v2:property:contact-state:0000007C)属性的描述，该属性应该表示为磁铁的连接状态（磁铁连接时值为`true`表示关闭），可能小米最近意识到之前的状态与该描述相反，才反转了状态。此次提交及后续版本，通过本插件集成的门磁在HA中的状态都将正确显示。
