### ISSUE TITLE
大佬请教：米兔儿童手表5X（型号xiaoxun.watch.sw766），接入后实体直接显示地理位置而不是状态信息？

### ISSUE THREAD

**Issue by Potato501** [al-one/hass-xiaomi-miot#271]
1. 大神您好，通过您的插件将儿童手表接入HA，生成的device_tracker.xxxx实体默认显示的是地理位置信息，不是和HA常规的device_tracker实体显示的‘home’，‘not_home’这种，请教一下支持修改吗？

2. 还反馈一个问题就是：目前显示的地理位置信息确实是家庭实际位置，但是在HA的地图中，应该是调用了device_tracker.xxx实体属性中的**经纬度**，这个经纬度有一定程度的**偏移**，不知道这个和插件本身有没有关系，手表的地图和HA中都是高德地图，谢谢。

PS：补充了一下第二点疑问的描述。

**Comment by al-one** [comment]
> 1. 通过您的插件将儿童手表接入HA，生成的device_tracker.xxxx实体默认显示的是地理位置信息，不是和HA常规的device_tracker实体显示的‘home’，‘not_home’这种，请教一下支持修改吗？

刚才的提交 https://github.com/al-one/hass-xiaomi-miot/commit/41dd266dcc18ca811fdd7dc38368c80a0cc143aa 中为`device_tracker`实体新增了`disable_location_name`自定义属性，你可以[添加此自定义属性](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)以禁止显示状态为地址：
```yaml
# customize.yaml
device_tracker.your_entity_id:
  disable_location_name: true
```

----

> 2. 还反馈一个问题就是：目前显示的地理位置信息是家庭实际位置，但是在地图Map应用中，应该是调用了实体的经纬度的关系，会有一定程度的偏移，不知道这个和插件本身有没有关系，谢谢。

位置偏移可能是因为插件获取到的坐标与HA中地图使用的是不同的坐标系，需要确定手表使用的是哪种坐标系，参考：
- https://lbsyun.baidu.com/index.php?title=coordinate
- https://lbs.amap.com/api/webservice/guide/api/convert

**Comment by Potato501** [comment]
感谢这么快回复，第一个按照您给的办法搞定了；
第二个问题我只能补充一些信息，米兔的APP里面地图有两套可以切换，高德和百度都有，我选择的高德地图，插件接入后，经纬度坐标数据小数点后只有4位，感觉会不会是因为精确度不够的问题？地理位置和APP显示一致的。

**Comment by al-one** [comment]
偏移的具体原因我也不清楚了，坐标和位置信息都是小米接口返回的，插件没做任何处理。

**Comment by Potato501** [comment]
收到，我试了下经纬度坐标反查位置，四位小数确实不够精确，看来是做了限制，非常感谢。

**Comment by big111boy** [comment]
大佬，请问下，米兔6X手表，型号是xiaoxun.watch.sw771
在customize.yaml文件中配置了disable_location_name: true，但是device_tracker.xxxx实体默认显示的还是是地理位置信息，插件版本是0.6.11
