### ISSUE TITLE
建议：大神可否考虑将非联网设备（比如蓝牙设备）的lan_ip属性默认设置为false模式？

### ISSUE THREAD

**Issue by Potato501** [al-one/hass-xiaomi-miot#272]
今天提了一个Issues，大神回复非常及时，插件利用米家iot平台对接接入的设备非常广泛，我也在混合着用，不过发现了一个问题：
我接了两个米家的蓝牙夜灯，看到**lan_ip**显示的是外网的**IP（wan_ip）**，不像插座类本身有wifi模块，具备真正意义上的局域网IP，通过Customize去关闭/开启属性我觉得挺好的，不知道我理解的对不对，就提个建议，希望可以提供默认关闭的选项，提这个问题也没有刻意去搜索有没有人说这个。。。

就这样，感谢大神开发米家设备插件。

**Comment by al-one** [comment]
`lan_ip`是本插件生成的所有父实体都有的一个基础属性，属性值是由米家设备列表接口`/app/home/device_list`返回的，包括公网IP也是从接口返回的数据中拿到了，目前插件未对该属性做任何处理，也没有去判断设备类型来隐藏。该属性目前主要的用途是在`本地模式`使用该IP连接设备，或者在`自动模式`下连接[支持本地的设备](https://github.com/al-one/hass-xiaomi-miot/blob/master/custom_components/xiaomi_miot/core/miot_local_devices.py)，另一个用途可能就是为了让用户使用IP区分设备。目前也没有移除该属性的计划。

**Comment by Potato501** [comment]
谢谢，我以为可以通过插件屏蔽掉，我想多了。
