### ISSUE TITLE
deerma.humidifier.jsq5

### ISSUE THREAD

**Issue by alexandersgn** [al-one/hass-xiaomi-miot#275]
Hello, world, 

Today I'm installed integration Xiaomi Miot Auto and see an error in this plugin. I can't add my humidifier deerma.humidifier.jsq5, becouse has error. See below.

===============================
Logger: custom_components.xiaomi_miot.humidifier
Source: custom_components/xiaomi_miot/__init__.py:1093 
Integration: Xiaomi Miot Auto (documentation, issues) 
First occurred: 17:11:00 (3 occurrences) 
Last logged: 17:13:06

Humidifier (Fog) Humidifier: Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'humidifier.on': {'siid': 2, 'piid': 1}, 'humidifier.fault': {'siid': 2, 'piid': 2}, 'humidifier.fan_level': {'siid': 2, 'piid': 5}, 'humidifier.target_humidity': {'siid': 2, 'piid': 6}, 'custom.water_shortage_fault': {'siid': 7, 'piid': 1}, 'custom.the_tank_filed': {'siid': 7, 'piid': 2}, 'indicator_light.on': {'siid': 6, 'piid': 1}, 'alarm': {'siid': 5, 'piid': 1}, 'environment.relative_humidity': {'siid': 3, 'piid': 1}, 'environment.temperature': {'siid': 3, 'piid': 7}}, max_properties: 10/10

**Comment by al-one** [comment]
The device of this model [`deerma.humidifier.jsq5`](https://home.miot-spec.com/s/deerma.humidifier.jsq5) supports local mode, but it may return error `-9999` due to querying too many properties. Please try to [add this custom attribute](https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui) and observe again:
```yaml
# customize.yaml
humidifier.deerma_jsq5_entity_id:
  exclude_miot_services: alarm,custom
```

**Comment by alexandersgn** [comment]
Was added in custom attribute in /config/customize.yaml. But it's didn't help. Any ideas? 

=============
Logger: custom_components.xiaomi_miot.humidifier
Source: custom_components/xiaomi_miot/__init__.py:1093 
Integration: Xiaomi Miot Auto (documentation, issues) 
First occurred: 19:06:13 (2 occurrences) 
Last logged: 19:07:24

Humidifier (Fog) Humidifier: Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'humidifier.on': {'siid': 2, 'piid': 1}, 'humidifier.fault': {'siid': 2, 'piid': 2}, 'humidifier.fan_level': {'siid': 2, 'piid': 5}, 'humidifier.target_humidity': {'siid': 2, 'piid': 6}, 'custom.water_shortage_fault': {'siid': 7, 'piid': 1}, 'custom.the_tank_filed': {'siid': 7, 'piid': 2}, 'indicator_light.on': {'siid': 6, 'piid': 1}, 'alarm': {'siid': 5, 'piid': 1}, 'environment.relative_humidity': {'siid': 3, 'piid': 1}, 'environment.temperature': {'siid': 3, 'piid': 7}}, max_properties: 10/10

**Comment by al-one** [comment]
This custom attribute does not take effect because the excluded attributes are still in the log. [Customization using the UI](https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui) is recommended.

**Comment by alexandersgn** [comment]
In UI two parameters was excluded

<img width="580" alt="Screenshot 2021-12-02 at 19 19 35" src="https://user-images.githubusercontent.com/43504745/144461153-4ea93a5e-0003-4adf-a3dd-385767c8bead.png">
.

**Comment by al-one** [comment]
Reload integration config and show me logs again.

**Comment by alexandersgn** [comment]
No problem.
The same mistake. 

<img width="579" alt="Screenshot 2021-12-02 at 19 35 31" src="https://user-images.githubusercontent.com/43504745/144464426-5fd6d6f9-5756-4f1b-99fa-4464865b815a.png">
<img width="1309" alt="Screenshot 2021-12-02 at 19 38 34" src="https://user-images.githubusercontent.com/43504745/144464445-a8f2009c-4038-4a06-88d2-dafafee94ccb.png">

**Comment by alexandersgn** [comment]
Hmmm.... Today I added again humidifier in my Mi account. And all work =) I don't known what was it, but now my humidifier is worked. In HomeAssistant i'm did nothing.  

Theme can be closed.
