### ISSUE TITLE
yeelink.bhf_light.v1浴霸

### ISSUE THREAD

**Issue by xztxy** [al-one/hass-xiaomi-miot#28]
![image](https://user-images.githubusercontent.com/31698398/109913491-149d2800-7ce9-11eb-93d8-82398b643a33.png)
浴霸，无法使用，开启云端都显示但是还是无法使用。用您的另一个插件Miio for Yeelink是可以的。
日志：
![image](https://user-images.githubusercontent.com/31698398/109913568-35657d80-7ce9-11eb-9c30-a05c0c5b20e5.png)
![image](https://user-images.githubusercontent.com/31698398/109913704-680f7600-7ce9-11eb-8b7f-7123178d6e8a.png)

**Comment by al-one** [comment]
-9999的日志是在云端模式生效之前产生的，开启云端后或者刚启动HA会有一两分钟云端模式未生效。
`Unable to find referenced entities`日志是在操作后产生的吗？
看您的截图看起来获取状态是没问题的，切换模式不生效吗？

**Comment by xztxy** [comment]
还是不生效。刚午休起来看了下
![image](https://user-images.githubusercontent.com/31698398/109917973-35697b80-7cf1-11eb-86b0-c5f6a22f3ccf.png)


> -9999的日志是在云端模式生效之前产生的，开启云端后或者刚启动HA会有一两分钟云端模式未生效。
> `Unable to find referenced entities`日志是在操作后产生的吗？
> 看您的截图看起来获取状态是没问题的，切换模式不生效吗？

**Comment by xztxy** [comment]
> -9999的日志是在云端模式生效之前产生的，开启云端后或者刚启动HA会有一两分钟云端模式未生效。
> `Unable to find referenced entities`日志是在操作后产生的吗？
> 看您的截图看起来获取状态是没问题的，切换模式不生效吗？

![image](https://user-images.githubusercontent.com/31698398/109918176-7e213480-7cf1-11eb-848a-434faa8515c2.png)

**Comment by xztxy** [comment]
> -9999的日志是在云端模式生效之前产生的，开启云端后或者刚启动HA会有一两分钟云端模式未生效。
> `Unable to find referenced entities`日志是在操作后产生的吗？
> 看您的截图看起来获取状态是没问题的，切换模式不生效吗？

灯也是一样无法操作的，但是状态可以反馈到~

**Comment by al-one** [comment]
你的HA版本是多少？
另外请检查你的HA文件：`lib/python3.x/site-packages/homeassistant/components/climate/translations/zh-Hans.json`中是否包含以下代码：
```json
{
    "state": {
        "_": {
            "auto": "\u81ea\u52a8",
            "cool": "\u5236\u51b7",
            "dry": "\u9664\u6e7f",
            "fan_only": "\u4ec5\u9001\u98ce",
            "heat": "\u5236\u70ed",
            "heat_cool": "\u5236\u70ed/\u5236\u51b7",
            "off": "\u5173"
        }
    }
}
```
建议你清除一下浏览器缓存。

**Comment by al-one** [comment]
请进入 `配置 > 状态` 筛选实体`climate.yu_ptc_bath_heater`，并将其状态反馈给我

**Comment by xztxy** [comment]
> 请进入 `配置 > 状态` 筛选实体`climate.yu_ptc_bath_heater`，并将其状态反馈给我

hvac_modes:
  - 'off'
  - heat
  - dry
  - fan_only
min_temp: 16
max_temp: 31
target_temp_step: 1
fan_modes:
  - Low
  - Medium
  - High
preset_modes:
  - Ventilate
  - 'off'
swing_modes:
  - 'Off'
  - Horizontal
current_temperature: 23
current_humidity: 76
fan_mode: Medium
preset_mode: 'off'
swing_mode: 'Off'
model: yeelink.bhf_light.v1
lan_ip: 192.168.15.134
mac_address: '04:CF:8C:12:CD:AB'
firmware_version: 2.1.8
hardware_version: esp32
entity_class: MiotClimateEntity
brightness_delta.error: -704030013
light_extension.ct_delta.error: -704030013
environment.temperature: 23
environment.relative_humidity: 76
fan_control.fan_level: 2
fan_control.horizontal_swing: false
fan_control.horizontal_angle.error: -704220043
ptc_bath_heater.mode: 1
ptc_bath_heater.temperature: 23
light.on: false
light.brightness: 100
light.color_temperature: 6500
state_updater: cloud
sub_entities:
  - Ventilate
friendly_name: 浴 PTC Bath Heater
supported_features: 56

**Comment by al-one** [comment]
建议你升级HA版本后尝试。

**Comment by xztxy** [comment]
> 建议你升级HA版本后尝试。

一直用的最新的2.3版本，中午升级到最新的3.0
![image](https://user-images.githubusercontent.com/31698398/109919574-d0635500-7cf3-11eb-8716-547b27433553.png)

**Comment by xztxy** [comment]
> 你的HA版本是多少？
> 另外请检查你的HA文件：`lib/python3.x/site-packages/homeassistant/components/climate/translations/zh-Hans.json`中是否包含以下代码：
> 
> ```json
> {
>     "state": {
>         "_": {
>             "auto": "\u81ea\u52a8",
>             "cool": "\u5236\u51b7",
>             "dry": "\u9664\u6e7f",
>             "fan_only": "\u4ec5\u9001\u98ce",
>             "heat": "\u5236\u70ed",
>             "heat_cool": "\u5236\u70ed/\u5236\u51b7",
>             "off": "\u5173"
>         }
>     }
> }
> ```
> 
> 建议你清除一下浏览器缓存。

请问下，这个路径是在ha哪个路径还是，debian系统路径,我用debian安装的

**Comment by xztxy** [comment]
> 建议你升级HA版本后尝试。

感谢大佬的耐心解答，目前发现可以控制了。原因是我老早hacs之前安装的一个卡片主题导致的。
