### ISSUE TITLE
绿米温控器S2打开成功后马上自动关闭

### ISSUE THREAD

**Issue by uleatest** [al-one/hass-xiaomi-miot#280]
问题：[绿米温控器S2](https://home.miot-spec.com/s/lumi.airrtc.tcpecn01)在卡片上点击制冷或制热模式后顺利打开（面板有显示打开，能听到继电器工作的声音），但是大概1秒后马上自动关闭了。如果听继电器声音的话，是打开后紧接着马上断开。试用把教程里提到的把cloud_delay_update改到60秒， 但是没有效果。麻烦确认了！
Miot Auto版本:v0.4.4
HA版本:core-2021.11.5
网关：小米多功能网关
设备：绿米温控器S2
实体:climate.lumi_tcpecn01_XXXX_air_conditioner
插件版本：1.0.28

**Comment by al-one** [comment]
请将该设备通过米家共享给账号：`143050915`，另外建议升级插件到最新版本。

**Comment by uleatest** [comment]
非常感谢您的重视和深入确认！说一声辛苦了！米家APP竟然无法共享绿米的温控器，好神奇， 将通过别的方式共享给您（26开头中间是6）！

**Comment by al-one** [comment]
共享家庭我是没法调试该设备的，如果它的网关子设备，需要先共享网关才能共享子设备。（米家首页长按设备共享）
另外请加入QQ群`198841186`并联系我，以便我在调试该设备前通知你。

**Comment by al-one** [comment]
我需要操作设备开关来调试该问题，请问什么时间段操作比较合适。
