### ISSUE TITLE
Bump python-miio >= 0.5.9

### ISSUE THREAD

**Issue by Wh1terat** [al-one/hass-xiaomi-miot#284]
python-miio now at 0.5.9.1, selfishly >= 0.5.9 would be great as adds '[mmgg.pet_waterer.s1](https://home.miot-spec.com/s/mmgg.pet_waterer.s1)' 😸

**Comment by al-one** [comment]
Does this component currently support this device?

In order to be compatible with more different versions of HA, the version dependency of `python-miio` will not be easily changed. A higher version will make the old version of HA unable to use this component.

**Comment by Wh1terat** [comment]
True. The joy of dependencies.

It is supported by this component but requires quite a bit of customisation that is just easier in python than in hass.

I'll have a look and perhaps submit a PR.
