### ISSUE TITLE
all devices disconnect after some hours 

### ISSUE THREAD

**Issue by licheng5625** [al-one/hass-xiaomi-miot#286]
Hi,
I always have this that all devices are disconnected after sometime :
2021-12-03 02:40:40 WARNING (MainThread) [homeassistant.components.sensor] Updating xiaomi_miot sensor took longer than the scheduled update interval 0:00:30
2021-12-03 02:41:10 WARNING (MainThread) [homeassistant.components.vacuum] Updating xiaomi_miot vacuum took longer than the scheduled update interval 0:01:00
2021-12-03 02:41:10 WARNING (MainThread) [homeassistant.components.sensor] Updating xiaomi_miot sensor took longer than the scheduled update interval 0:00:30

All devices fails at same at time point .
There is no detail in the log which I can use for anlysing.

There is a max number of APIs' retrieving time ? 

regards
Cheng

**Comment by ads901119** [comment]
Encountered the same issue here.
I re-configured xiaomi-miot integration at about 11:38.
The sensor starts to update. 
However after a while (after 12:27), it no longer updates. It's 18:32 now and still no update.

![image](https://user-images.githubusercontent.com/756198/144830662-90def374-34c2-46bf-87b7-99f3155e9a98.png)

logs
`Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:712
Integration: 感測器 (documentation, issues)
First occurred: 13:17:32 (630 occurrences)
Last logged: 18:32:03

Updating xiaomi_miot sensor took longer than the scheduled update interval 0:00:30`

**Comment by licheng5625** [comment]
Hi @ads901119 , only two of us have this issue ?
I thought it might be a commen problem. 

I found out from time to time  miot returens 401
2021-12-12 06:08:15 DEBUG (SyncWorker_10) [custom_components.xiaomi_miot.core.xiaomi_cloud] response: is 401
2021-12-12 06:08:15 DEBUG (SyncWorker_10) [custom_components.xiaomi_miot.core.xiaomi_cloud] response: is {"code":2,"message":"auth err"}

**Comment by licheng5625** [comment]
@ads901119 
I might find a solution, add following code to your ***xiaomi_cloud.py*** to overwrite the original function of `class MiotCloud(micloud.MiCloud)`
```
def request(self, url, params):
        if not self.service_token or not self.user_id:
            raise MiCloudException("Cannot execute request. service token or userId missing. Make sure to login.")

        self.session = requests.Session()
        self.session.headers.update({'User-Agent': self.useragent})

        _LOGGER.debug("Send request: %s to %s", params['data'], url)
        self.session.headers.update({
            'x-xiaomi-protocal-flag-cli': 'PROTOCAL-HTTP2',
            'content-type': 'application/x-www-form-urlencoded'
        })
        self.session.cookies.update({
            'userId': str(self.user_id),
            'yetAnotherServiceToken': self.service_token,
            'serviceToken': self.service_token,
            'locale': str(self.locale),
            'timezone': str(self.timezone),
            'is_daylight': str(time.daylight),
            'dst_offset': str(time.localtime().tm_isdst * 60 * 60 * 1000),
            'channel': 'MI_APP_STORE'
        })
        for c in self.session.cookies:
            _LOGGER.debug('Cookie: %s', c)

        try:
            nonce = miutils.gen_nonce()
            signed_nonce = miutils.signed_nonce(self.ssecurity, nonce)
            signature = miutils.gen_signature(url.replace("/app", ""), signed_nonce, nonce, params)

            post_data = {
                'signature': signature,
                '_nonce': nonce,
                'data': params['data']
            }
            response = self.session.post(url, data=post_data,timeout=30 )
            if response.status_code == 403:
                self.service_token = None
            return response.text
        except requests.exceptions.HTTPError as e:
            self.service_token = None
            _LOGGER.error("Error while executing request to %s :%s", url, str(e))
        except MiCloudException as e:
            _LOGGER.error("Error while decrypting response of request to %s :%s", url, str(e))
        except Exception as e:
            _LOGGER.error("Error while executing request to %s :%s", url, str(e))

```

The difference is  adding a timeout.
```
  response = self.session.post(url, data=post_data,timeout=30 )
```

Tested with 12 hours, it is still working.
Hope it can be the solution.

**Comment by al-one** [comment]
> response = self.session.post(url, data=post_data, timeout=30)

@licheng5625 Is it still working ?

**Comment by licheng5625** [comment]
@al-one  still working. Quite stable comparing with previous version. 
This timeout supports to be smaller as the interval of update of status. 
And I am not sure if this disconnection is individual problem or not. No one else is reporting a similar issue.

**Comment by al-one** [comment]
Has the problem been solved ?

**Comment by licheng5625** [comment]
> Has the problem been solved ?

Yes
