### ISSUE TITLE
Supported Router Xiaomi AX6000 connected, but does not receive attributes

### ISSUE THREAD

**Issue by VikeDragon** [al-one/hass-xiaomi-miot#288]
Greetings !

Supported Router Xiaomi AX6000 connected, but does not receive attributes :

model: xiaomi.router.ra72
miot_type: urn:miot-spec-v2:device:router:0000A036:xiaomi-ra72:1
state_property: router.status
router.download_speed.error: '-706010002 Service does not exist'
router.upload_speed.error: '-706010002 Service does not exist'
router.connected_device_number.error: '-706010002 Service does not exist'
router.network_connection_type.error: '-706010002 Service does not exist'
router.ip_address.error: '-706010002 Service does not exist'
router.status.error: '-706010002 Service does not exist'
router.fault.error: '-706010002 Service does not exist'
router.ppp_username.error: '-706010002 Service does not exist'
router.ppp_encrypted_password.error: '-706010002 Service does not exist'
router.static_ip_address.error: '-706010002 Service does not exist'
router.subnet_mask.error: '-706010002 Service does not exist'
router.gateway_ip_address.error: '-706010002 Service does not exist'
router.dns_ip_address.error: '-706010002 Service does not exist'
router.dns_auto_mode.error: '-706010002 Service does not exist'
router.access_mode.error: '-706010002 Service does not exist'
router.rssi.error: '-706010002 Service does not exist'
router.wifi_band_combine.error: '-706010002 Service does not exist'
router.online_time.error: '-706010002 Service does not exist'
indicator_light.on.error: '-706010002 Service does not exist'
indicator_light.mode.error: '-706010002 Service does not exist'
indicator_light.brightness.error: '-706010002 Service does not exist'
indicator_light.color.error: '-706010002 Service does not exist'
color_temperature-5-5.error: '-706010002 Service does not exist'
indicator_light.flow.error: '-706010002 Service does not exist'
indicator_light.saturability.error: '-706010002 Service does not exist'
guest_wifi.on.error: '-706010002 Service does not exist'
guest_wifi.wifi_ssid.error: '-706010002 Service does not exist'
wifi_encrypted_password-4-3.error: '-706010002 Service does not exist'
guest_wifi.encrypted_strength.error: '-706010002 Service does not exist'
guest_wifi.signal_strength.error: '-706010002 Service does not exist'
guest_wifi.wifi_channel.error: '-706010002 Service does not exist'
guest_wifi.wifi_bandwidth.error: '-706010002 Service does not exist'
guest_wifi.speed_control.error: '-706010002 Service does not exist'
guest_wifi.max_upload_speed.error: '-706010002 Service does not exist'
guest_wifi.max_download_speed.error: '-706010002 Service does not exist'
wifi.wifi_ssid.error: '-706010002 Service does not exist'
wifi.wifi_encrypted_password.error: '-706010002 Service does not exist'
wifi.on.error: '-706010002 Service does not exist'
wifi.wifi_ssid_hidden.error: '-706010002 Service does not exist'
wifi.encrypted_strength.error: '-706010002 Service does not exist'
wifi.signal_strength.error: '-706010002 Service does not exist'
wifi.wifi_channel.error: '-706010002 Service does not exist'
wifi.wifi_bandwidth.error: '-706010002 Service does not exist'
state_updater: cloud
friendly_name: Xioami AX6000 Router Status
supported_features: 0

it is also not possible to connect the device via a token, since the token is non-standard.
Connected via MiHome account.
I ask for help in connecting the device.

**Comment by al-one** [comment]
These errors come from xiaomi cloud for unknown reasons.

**Comment by VikeDragon** [comment]
Greetings!
Is there any way to solve these problems? Maybe it's a non-standard token?

**Comment by al-one** [comment]
There's nothing I can do about it.
