### ISSUE TITLE
chuangmi.plug.v3 USB

### ISSUE THREAD

**Issue by xztxy** [al-one/hass-xiaomi-miot#29]
![image](https://user-images.githubusercontent.com/31698398/109983113-7c7d5e00-7d3d-11eb-882c-41544a48e436.png)
USB控制问题

**Comment by al-one** [comment]
请更新[master](https://github.com/al-one/hass-xiaomi-miot/tree/master)分支最新提交的版本再试下

**Comment by xztxy** [comment]
> 请更新[master](https://github.com/al-one/hass-xiaomi-miot/tree/master)分支最新提交的版本再试下

大佬很速度，确认已经OK~~
