### ISSUE TITLE
窗帘电机状态与实际相反

### ISSUE THREAD

**Issue by eavanhhh** [al-one/hass-xiaomi-miot#290]
Hi，
我的两个[杜亚m2窗帘电机](https://home.miot-spec.com/s/dooya.curtain.m2)在米家中设置了电机反转，在HA中实体属性识别的是Curtain.motor reverse  true，但与实际状态还是相反。
如果窗帘是打开状态，点击HA中的关闭，窗帘会关闭，但历史中会显示“已打开”，并且关闭后打开按钮变成灰色不可用；拖动滑块可以触发电机动作，但是状态也是反的。
Miot Auto版本:v0.4.12
![image](https://user-images.githubusercontent.com/81670366/145171363-bce6a85d-f0ec-457d-8419-5b88308b9306.png)

**Comment by al-one** [comment]
能否将此设备通过米家共享给我(ID: `143050915`)，并加入QQ群[`198841186`](https://jq.qq.com/?_wv=1027&k=lZAMn5Uo)联系我，以便我在操作设备前通知你。

**Comment by w4mxl** [comment]
@al-one 我遇到类似问题，已经将设备（dooya.curtain.m1）共享给你了

**Comment by al-one** [comment]
该问题已在 https://github.com/al-one/hass-xiaomi-miot/commit/8494e9d7fed4cdfbf0f2b46957cf5cb25cfcf1b9 中修复，请升级到master分支或等待下个版本。
