### ISSUE TITLE
设备导入时的区域问题

### ISSUE THREAD

**Issue by 020794** [al-one/hass-xiaomi-miot#293]
我的米家里面有多个房屋，每个房屋又有不同房间（都是重名的，都叫客厅、卧室、厨房、卫生间等等）。

目前倒入后设备很难区分，比如父母家客厅的净化器和自己家客厅的净化器，倒入后的区域都是客厅。

是否能在导入时，区域里面加上房屋名称，比如父母家的客厅、自己家的客厅，谢谢。

**Comment by al-one** [comment]
首先，HA中的区域是可以添加和更改的，设备所属的区域也可以更改。另外，一个HA通常情况下只对应一个家庭（方便局域网控制），多个家庭用在一个HA的情况好像不多。如果插件在区域名称前加了家庭名称，会导致其他用户的HA中生成重复的区域。因此，暂时没法达到你的需求，建议你手动更改设备的区域。实体的[状态属性](https://my.home-assistant.io/redirect/developer_states)中有个`home_room`属性，可以帮助你区分不同家庭的设备。
