### ISSUE TITLE
关于小米空调

### ISSUE THREAD

**Issue by yyxp1989** [al-one/hass-xiaomi-miot#294]
您好， 原来使用的是homeassistant和 miot auto 6个月前的版本， 今天升级后Home Assistant 2022.1.0.dev20211208， 通过HACS重新安装了hass-xiaomi-miot， 其中 小米空调 有一条警告日志  日志如下：

-------------------------------------------

Logger: custom_components.xiaomi_miot.climate
Source: custom_components/xiaomi_miot/__init__.py:1464
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 22:22:58 (2 occurrences)
Last logged: 22:23:05

小米空调 Air Conditioner: Set miot property {'did': '405921266', 'siid': 2, 'piid': 10, 'value': True} failed, result: {'did': '405921266', 'siid': 2, 'piid': 10, 'code': -5000}
小米空调 Air Conditioner: Set miot property {'did': '405921266', 'siid': 2, 'piid': 10, 'value': False} failed, result: {'did': '405921266', 'siid': 2, 'piid': 10, 'code': -5000}

**Comment by al-one** [comment]
请问操作该属性时空调是开机状态吗？空调的部分属性需要在设备开启状态下操作。另外请问该设备的型号是多少？

**Comment by yyxp1989** [comment]
> 请问操作该属性时空调是开机状态吗？空调的部分属性需要在设备开启状态下操作。另外请问该设备的型号是多少？

你好，感谢你的提示，原因已找到， 我在nodered中配置自动化， 空调在制热模式下， 自动关闭辅热 和 干燥 并打开eco ，其中干燥 只有在制冷模式下可用，所以报错了。
