### ISSUE TITLE
Request to add support for kxf321.mop.mo001

### ISSUE THREAD

**Issue by pbannykh** [al-one/hass-xiaomi-miot#295]
Please add ability to manually set device class.

Previously, mopping-machine were referred to as "vacuum".
After updating api, mopping-machine were moved to another class "mopping-machine".
Now mopping-machine don't work.

Problem device: SWDK ZDG300 mop robot [kxf321.mop.mo001](https://home.miot-spec.com/s/kxf321.mop.mo001) (cloud)

**Comment by al-one** [comment]
Added in https://github.com/al-one/hass-xiaomi-miot/commit/9430cb4e4b2b4b74c8b304ccf7b7c69a11e976c5 . Please upgrade to master branch and try.

**Comment by pbannykh** [comment]
It works, thanks!
