### ISSUE TITLE
model: lumi.airer.acn02 ui上升下降图标状态和功能反了

### ISSUE THREAD

**Issue by panpawang** [al-one/hass-xiaomi-miot#296]
------实体属性-------
current_position: 0
model: [lumi.airer.acn02](https://home.miot-spec.com/s/lumi.airer.acn02)
lan_ip: 192.168.31.32
mac_address: B4:60:ED:30:0F:B3
firmware_version: 2.0.8_0005
hardware_version: 
entity_class: MiotCoverEntity
miot_type: [urn:miot-spec-v2:device:airer:0000A00D:lumi-acn02:1](https://home.miot-spec.com/spec/lumi.airer.acn02)
airer.fault.error: -704042011
airer.motor_control.error: -704030013
airer.status: 0
airer.current_position: 0
airer.target_position: 0
light_control.error: -704030013
remote_button.f_one_wireless: 0
remote_button.f_two_wireless: 0
remote_button.f_three_wireless: 0
remote_button.f_four_wireless: 0
remote_button.f_one_position: 20
remote_button.f_two_position: 40
remote_button.f_three_position: 60
remote_button.f_four_position: 80
airer_user.pos_limit_cfg.error: -704030013
airer_user.pos_limit: 1
airer_user.mute_mode: 0
airer_user.tracer_mode: 0
airer_user.tracer_mode_cfg: 
airer_user.run_time: 15
light.on: false
state_updater: cloud
friendly_name: 晾衣架 Airer
supported_features: 15

-------ui按钮-----------
![image](https://user-images.githubusercontent.com/35269975/145323550-18860885-cc67-4443-b929-2073b7a7042c.png)

**Comment by al-one** [comment]
请更新到master分支后再试下。

**Comment by al-one** [comment]
该问题在最新版本中还存在吗？
