### ISSUE TITLE
v0.4.11升级到v0.4.12后fawad温控器不能工作

### ISSUE THREAD

**Issue by cuihaijun** [al-one/hass-xiaomi-miot#297]
[fawad.airrtc.30012](https://home.miot-spec.com/s/fawad.airrtc.30012)，[fawad.airrtc.30011](https://home.miot-spec.com/s/fawad.airrtc.30011)升级后不能用，显示灰色。

**Comment by al-one** [comment]
https://github.com/al-one/hass-xiaomi-miot/blob/c6edb39f0b9653d3b51e5edb67684375d2192ee8/custom_components/xiaomi_miot/core/miot_local_devices.py#L63-L64

这两款设备在v0.4.12版本中被加入[本地miot设备列表](https://github.com/al-one/hass-xiaomi-miot/blob/master/custom_components/xiaomi_miot/core/miot_local_devices.py)，请检查下有无相关报错[日志](https://my.home-assistant.io/redirect/logs)。

**Comment by cuihaijun** [comment]
我用本地接入，还是不能用，显示灰色
`此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.climate
Source: custom_components/xiaomi_miot/__init__.py:1094
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 11:59:52 (8 occurrences)
Last logged: 12:02:53

主卧空调 Thermostat: Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'thermostat.on': {'siid': 2, 'piid': 1}, 'thermostat.status': {'siid': 2, 'piid': 2}, 'thermostat.fault': {'siid': 2, 'piid': 3}, 'thermostat.mode': {'siid': 2, 'piid': 4}, 'thermostat.target_temperature': {'siid': 2, 'piid': 5}, 'thermostat.fan_level': {'siid': 2, 'piid': 6}, 'thermostat.temperature': {'siid': 2, 'piid': 7}, 'thermostat_vrf.device_info': {'siid': 4, 'piid': 1}, 'screen_lock_enable-4-2': {'siid': 4, 'piid': 2}, 'thermostat_vrf.wind_derection_v': {'siid': 4, 'piid': 3}, 'thermostat_vrf.wind_derection_h': {'siid': 4, 'piid': 4}, 'thermostat_vrf.dehumidity_level': {'siid': 4, 'piid': 5}, 'thermostat_vrf.timer_info': {'siid': 4, 'piid': 6}, 'founc_enable_flags-4-7': {'siid': 4, 'piid': 7}, 'thermostat_vrf.workauto_submode': {'siid': 4, 'piid': 8}, 'wind_direction_mode-4-9': {'siid': 4, 'piid': 9}, 'beep_opration_enable-4-10': {'siid': 4, 'piid': 10}, 'dark_night_display-4-11': {'siid': 4, 'piid': 11}, 'thermostat_vrf.ontime_dark': {'siid': 4, 'piid': 12}, 'thermostat_vrf.offtime_dark': {'siid': 4, 'piid': 13}, 'thermostat_vrf.powerlight_dark': {'siid': 4, 'piid': 14}, 'thermostat_vrf.monday_timer': {'siid': 4, 'piid': 15}, 'thermostat_vrf.tuesday_timer': {'siid': 4, 'piid': 16}, 'thermostat_vrf.wednesday_timer': {'siid': 4, 'piid': 17}, 'thermostat_vrf.thursday_timer': {'siid': 4, 'piid': 18}, 'thermostat_vrf.friday_timer': {'siid': 4, 'piid': 19}, 'thermostat_vrf.saturday_timer': {'siid': 4, 'piid': 20}, 'thermostat_vrf.sunday_timer': {'siid': 4, 'piid': 21}, 'thermostat_vrf.schedule_enable': {'siid': 4, 'piid': 22}}, max_properties: 10/29
书房空调 Thermostat: Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'thermostat.on': {'siid': 2, 'piid': 1}, 'thermostat.status': {'siid': 2, 'piid': 2}, 'thermostat.fault': {'siid': 2, 'piid': 3}, 'thermostat.mode': {'siid': 2, 'piid': 4}, 'thermostat.target_temperature': {'siid': 2, 'piid': 5}, 'thermostat.fan_level': {'siid': 2, 'piid': 6}, 'thermostat.temperature': {'siid': 2, 'piid': 7}, 'thermostat_vrf.device_info': {'siid': 4, 'piid': 1}, 'screen_lock_enable-4-2': {'siid': 4, 'piid': 2}, 'thermostat_vrf.wind_derection_v': {'siid': 4, 'piid': 3}, 'thermostat_vrf.wind_derection_h': {'siid': 4, 'piid': 4}, 'thermostat_vrf.dehumidity_level': {'siid': 4, 'piid': 5}, 'thermostat_vrf.timer_info': {'siid': 4, 'piid': 6}, 'founc_enable_flags-4-7': {'siid': 4, 'piid': 7}, 'thermostat_vrf.workauto_submode': {'siid': 4, 'piid': 8}, 'wind_direction_mode-4-9': {'siid': 4, 'piid': 9}, 'beep_opration_enable-4-10': {'siid': 4, 'piid': 10}, 'dark_night_display-4-11': {'siid': 4, 'piid': 11}, 'thermostat_vrf.ontime_dark': {'siid': 4, 'piid': 12}, 'thermostat_vrf.offtime_dark': {'siid': 4, 'piid': 13}, 'thermostat_vrf.powerlight_dark': {'siid': 4, 'piid': 14}, 'thermostat_vrf.monday_timer': {'siid': 4, 'piid': 15}, 'thermostat_vrf.tuesday_timer': {'siid': 4, 'piid': 16}, 'thermostat_vrf.wednesday_timer': {'siid': 4, 'piid': 17}, 'thermostat_vrf.thursday_timer': {'siid': 4, 'piid': 18}, 'thermostat_vrf.friday_timer': {'siid': 4, 'piid': 19}, 'thermostat_vrf.saturday_timer': {'siid': 4, 'piid': 20}, 'thermostat_vrf.sunday_timer': {'siid': 4, 'piid': 21}, 'thermostat_vrf.schedule_enable': {'siid': 4, 'piid': 22}}, max_properties: 10/29`

**Comment by al-one** [comment]
这两款设备应该是支持本地模式的，但是可能由于一次性查询的属性过多导致报错，请[添加自定义属性](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)后再观察下：
```yaml
# customize.yaml
climate.fawad_30011_entity_id:
  chunk_properties: 7 # 减少每次查询属性的个数
climate.fawad_30012_entity_id:
  exclude_miot_services: thermostat_vrf # 排除一些服务以减少设备负担
```

**Comment by cuihaijun** [comment]
我加了自定义属性后，重启homeassistant还是空调状态还是灰色不可用，报错的日志代码也是一样的，奇怪的是只有主卧空调fawad.airrtc.30011报错的日志，没有书房空调fawad.airrtc.30012报错的日志

**Comment by cuihaijun** [comment]
![climate](https://user-images.githubusercontent.com/10826652/145335468-72a6ab4a-9c3b-48eb-97c3-f86c41f24a7e.png)

**Comment by cuihaijun** [comment]
![climate](https://user-images.githubusercontent.com/10826652/145335607-5ceb7f03-a50d-4c13-899c-fb2ea47109d0.png)

**Comment by al-one** [comment]
书房空调`fawad.airrtc.30012`现在可用吗？

**Comment by cuihaijun** [comment]
书房空调没报错，也不能用



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月9日(周四) 中午12:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [al-one/hass-xiaomi-miot] v0.4.11升级到v0.4.12后fawad温控器不能工作 (Issue #297)




 
书房空调fawad.airrtc.30012现在可用吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by al-one** [comment]
请把最新的日志复制给我。

**Comment by cuihaijun** [comment]
[log.txt](https://github.com/al-one/hass-xiaomi-miot/files/7682335/log.txt)

**Comment by cuihaijun** [comment]
> 请把最新的日志复制给我。
[log.txt](https://github.com/al-one/hass-xiaomi-miot/files/7682338/log.txt)

还有需要我做什么的你跟我讲，谢谢！

**Comment by al-one** [comment]
请更新到master分支后，重启HA再试，自定义属性保持不变。

**Comment by cuihaijun** [comment]
> 请更新到master分支后，重启HA再试，自定义属性保持不变。

是不是重新下载，因为我发现hacs就是master
![xiaomi](https://user-images.githubusercontent.com/10826652/145341074-fae840b3-f1ea-48d9-8140-e0bf24da7b03.png)

**Comment by cuihaijun** [comment]
> 请更新到master分支后，重启HA再试，自定义属性保持不变。
![test](https://user-images.githubusercontent.com/10826652/145341449-f680754c-889b-4993-92ba-4ef91591070e.png)

[log1.txt](https://github.com/al-one/hass-xiaomi-miot/files/7682524/log1.txt)

**Comment by al-one** [comment]
重新下载 > 选择`master`(显示测试版) > 下载/安装 > 重启HA

不需要添加自定义存储库。

**Comment by cuihaijun** [comment]
> 重新下载 > 选择`master`(显示测试版) > 下载/安装 > 重启HA
> 
> 不需要添加自定义存储库。
![test1](https://user-images.githubusercontent.com/10826652/145341782-559085a2-d064-4529-9b8e-aec714bc11cb.png)
上面是空白的有一行，选择后下载是灰色的

**Comment by al-one** [comment]
![image](https://user-images.githubusercontent.com/4549099/145342142-9cb5db88-4f65-4e74-8460-77e94361eb60.png)

**Comment by cuihaijun** [comment]
> ![image](https://user-images.githubusercontent.com/4549099/145342142-9cb5db88-4f65-4e74-8460-77e94361eb60.png)

very good，可以正常工作了，非常感谢！
我还想问一下，我还有一个zigebee接入小米多模网关的中央空调温控器，云端选择后没有显示实体，是不是不支持？

**Comment by al-one** [comment]
https://github.com/al-one/hass-xiaomi-miot/issues/122#issuecomment-874713279

如果是这款的话，很抱歉不支持。

**Comment by cuihaijun** [comment]
> [#122 (comment)](https://github.com/al-one/hass-xiaomi-miot/issues/122#issuecomment-874713279)
> 
> 如果是这款的话，很抱歉不支持。

再次感谢，lumi.airrtc.vrfegl01不支持的话也没办法，你真是技术大牛，这么厉害。

**Comment by al-one** [comment]
自定义属性`exclude_miot_services: thermostat_vrf`已被提交到插件代码中(https://github.com/al-one/hass-xiaomi-miot/commit/0724b60ad204f7469131a03929da85b2b69d46dc) ，将在下个版本中发布，后续版本无需添加上述自定义属性即可正常使用。
