### ISSUE TITLE
小米手环配置问题

### ISSUE THREAD

**Issue by Tao173** [al-one/hass-xiaomi-miot#298]
RT 最新版添加了小米手环支持，请问如何操作的？？我的小米手环5 NFC版本该如何接入呢，目前连接的app是小米运动。

**Comment by al-one** [comment]
暂不支持小米[手环](https://home.miot-spec.com/s/%E6%89%8B%E7%8E%AF)5及以上版本，因为找不到他对应的型号(model)和规格(urn)。还有个方法可以验证是否支持，如果在米家APP的附近设备中可以看到手环，应该就是支持的。
![image](https://user-images.githubusercontent.com/4549099/145346262-810d584a-634f-4498-98c0-ac080688f2e5.png)

**Comment by Tao173** [comment]
OK，我已经测试了一番，设备型号：小米手环5NFC版本
一、米家没有这个附近的设备选项
二、小米运动app可以绑定，小米穿戴app也可以绑定，前者绑定在米家总设备数没有显示，后者绑定的话米家总设备数会增加一个，但是依旧没有小米手环（设备莫名多一个）
三、小米穿戴里面可以设置手环控制指定门锁。
四、小米穿戴绑定之后在集成里面更新设备之后可以看见miband5nfc，但是配置不生效，重启HA依旧没有。
<img width="185" alt="MI band" src="https://user-images.githubusercontent.com/64321391/145354539-f3a961e1-1d49-4cbd-aa91-67a0be9b846e.png">

**Comment by al-one** [comment]
https://miot-spec.org/miot-spec-v2/instances?status=all

没有实体是因为该型号`hmpace.bracelet.v5h`没有对应的[miot-spec urn](https://home.miot-spec.com/spec/hmpace.bracelet.v5h).
