### ISSUE TITLE
Magnet sensor: Cuando la puerta está cerrada muestra abierta y cuando está abierta aparece como cerrada.

### ISSUE THREAD

**Issue by benjaminmupe** [al-one/hass-xiaomi-miot#299]
cuando la puerta está cerrada muestra abierta y cuando está abierta aparece como cerrada.
magnet_sensor when state is  on = door open and when is off =close.

**Comment by al-one** [comment]
What is your component version ? Maybe you should upgrade to the [latest version](https://github.com/al-one/hass-xiaomi-miot/releases/latest).

**Comment by benjaminmupe** [comment]
v04.12 aparece cambiado, he vuelto a instalar la v04.11 y me aparece bien.
A local magnet with zigbee2mqtt:
contact true = off  - door closed
contact false = on  - door open

**Comment by benjaminmupe** [comment]
Lo cerré sin querer

**Comment by benjaminmupe** [comment]
> What is your component version ? Maybe you should upgrade to the [latest version](https://github.com/al-one/hass-xiaomi-miot/releases/latest).

 Creo que es porque recibo el estado del sensor cambiado 
magnet_sensor.contact_state: false when it´s closed 

V04.12
**Door: Open**

entity: binary_sensor.lumi_v2_13cd_magnet_sensor
state: off

model: lumi.sensor_magnet.v2
lan_ip: ''
mac_address: lumi.158d00034313cd
entity_class: LumiBinarySensorEntity
home_room: Casa Benjamín Entrada
miot_type: urn:miot-spec-v2:device:magnet-sensor:0000A016:lumi-v2:1
state_property: magnet_sensor.contact_state
magnet_sensor.contact_state: true
state_updater: cloud
trigger_type: event.open
trigger_time: 1639044699
trigger_at: '2021-12-09 11:11:39'
friendly_name: Puerta Piso Gateway
supported_features: 0
device_class: door

**Door Closed**

state: on

model: lumi.sensor_magnet.v2
lan_ip: ''
mac_address: lumi.158d00034313cd
entity_class: LumiBinarySensorEntity
home_room: Casa Benjamín Entrada
miot_type: urn:miot-spec-v2:device:magnet-sensor:0000A016:lumi-v2:1
state_property: magnet_sensor.contact_state
magnet_sensor.contact_state: false
state_updater: cloud
trigger_type: event.close
trigger_time: 1639045927
trigger_at: '2021-12-09 11:32:07'
friendly_name: Puerta Piso Gateway
supported_features: 0
device_class: door

**Comment by le8266** [comment]
Hi, I have currently the same problem. I use the newest version of the integration (0.4.12) and also the newest version of home assistant supervisor. I think the issue starts after the last integration update. Here you can see an entity state of the sensor:
![image](https://user-images.githubusercontent.com/4182767/145393305-7fc51f56-1dee-4541-bdab-753e69d365a5.png)

**Comment by al-one** [comment]
Fixed in https://github.com/al-one/hass-xiaomi-miot/commit/5cdb6fb10eb1c58ef6de9482258f59e1f80a129d , please upgrade to master branch and try again.

**Comment by le8266** [comment]
I updated to master and now it works again. Thanks. 👍

**Comment by benjaminmupe** [comment]
> Fixed in [5cdb6fb](https://github.com/al-one/hass-xiaomi-miot/commit/5cdb6fb10eb1c58ef6de9482258f59e1f80a129d) , please upgrade to master branch and try again.

Thank you!! 
working again!
