### ISSUE TITLE
Window and Door sensor shows status "Open" when closed, and status "Closed" when opened.

### ISSUE THREAD

**Issue by donald-ong** [al-one/hass-xiaomi-miot#300]
Trigger type show "event.close", but the binary sensor status of show as "Open". The door is closed. Totally confused the logic I guess.

model: lumi.sensor_magnet.aq2
lan_ip: ''
mac_address: *
entity_class: LumiBinarySensorEntity
home_room: 美牛妞帅新男 Kitchen
miot_type: urn:miot-spec-v2:device:magnet-sensor:0000A016:lumi-aq2:1
state_property: magnet_sensor.contact_state
magnet_sensor.contact_state: false
state_updater: cloud
trigger_type: event.close
trigger_time: 1638811715
trigger_at: '2021-12-07 01:28:35'
friendly_name: K - Freezer Door
supported_features: 0
device_class: door

**Comment by cihantok** [comment]
Same problem with lumi.sensor_magnet.v2

**Comment by al-one** [comment]
Fixed in https://github.com/al-one/hass-xiaomi-miot/commit/5cdb6fb10eb1c58ef6de9482258f59e1f80a129d , please upgrade to master branch and try again.

**Comment by cihantok** [comment]
My problem is solved.Thank you.

**Comment by donald-ong** [comment]
Thank you.

**Comment by athlon614** [comment]
0.4.14 似乎又出現這狀況?

**Comment by cihantok** [comment]
Hi im using 0.4.14 , no problem on this version
