### ISSUE TITLE
Is there anyways to add "candle flicker" effect to yeelink.light.strip6 model?

### ISSUE THREAD

**Issue by donald-ong** [al-one/hass-xiaomi-miot#306]
Is there anyways to add "candle flicker" effect to [yeelink.light.strip6](https://home.miot-spec.com/s/yeelink.light.strip6) model?

I be happy to help and test the options if there are any that I can do within my means.

**Comment by al-one** [comment]
There are no relevant properties in the device [miot-spec](https://home.miot-spec.com/spec/yeelink.light.strip6). Maybe you can try this way to get miio commands: https://github.com/al-one/hass-xiaomi-miot/issues/242#issuecomment-989453399

**Comment by donald-ong** [comment]
Got it working. Thank you!

**Comment by al-one** [comment]
@donald-ong It would be great if you could share your configuration.

**Comment by donald-ong** [comment]
@al-one here it is.

service: xiaomi_miot.send_command
data:
  method: set_scene
  params:
    - cf
    - 0
    - 0
    - >-
      800,2,2700,50,800,2,2700,30,1200,2,2700,80,800,2,2700,60,1200,2,2700,90,2400,2,2700,50,1200,2,2700,80,800,2,2700,60,400,2,2700,70
  entity_id: *
