### ISSUE TITLE
Xiaomi Philips Downlight problem

### ISSUE THREAD

**Issue by thecoopers** [al-one/hass-xiaomi-miot#307]
When I try to adjust brightness or colour temp, the sliders move but nothing happens at the light. The sliders then revert back to original position on their own.  Latest HA with master installed, setup using cloud account with local control. I hope that makes sense. Thanks in advance for any help

**Comment by al-one** [comment]
What's its [model](https://home.miot-spec.com/s/philips.light) ? 
Are there any [logs](https://my.home-assistant.io/redirect/logs) after operating the device?

**Comment by thecoopers** [comment]
Philips ZhiRui downlight
There are no errors In the log

**Comment by al-one** [comment]
Maybe you need to collect [debug](https://github.com/al-one/hass-xiaomi-miot#debug) logs for me.

**Comment by thecoopers** [comment]
[home-assistant.log](https://github.com/al-one/hass-xiaomi-miot/files/7727879/home-assistant.log)

**Comment by thecoopers** [comment]
I've just had a thought. My home assistant is connected on lan and wan. The state updater is set to lan! Would that affect the operation?

**Comment by thecoopers** [comment]
[Uploading home-assistant.log…]()

**Comment by thecoopers** [comment]
[home-assistant.log](https://github.com/al-one/hass-xiaomi-miot/files/7728768/home-assistant.log)

**Comment by al-one** [comment]
The brightness value returned by the device is always 0 or 1, and there is nothing I can do about it.

**Comment by thecoopers** [comment]
Thank you for looking for me, I appreciate your help. The brightness control works with the xiaomi_miio inergration. I will try and compare the light.py scripts and see if there is something I can change. I won't pretend to know what I am doing though :/

**Comment by thecoopers** [comment]
All working with latest update. Thank you
