### ISSUE TITLE
Aqara Wireless Switch found while addind integration but after never shows

### ISSUE THREAD

**Issue by Ky0sHiR00** [al-one/hass-xiaomi-miot#308]
Hi

While discovering I see all of my 5 Aqara Wireless Single Switches but when I'm adding they never shows as entities.
lumi.remote.b186acn01
+
lumi.sensor_switch.aq2

**Comment by al-one** [comment]
Since this component obtains the device state by polling, it cannot monitor the key events of wireless switch in real time, so it is not suitable for such devices.

**Comment by Ky0sHiR00** [comment]
Thank You for this information.
I would like to ask if polling in quicker intervals will increase battery usage of devices? 
I see that default for magnet is 15 sec.
Intervals are located in device_customizes.py - is it safe to modify them or just use customize.yaml?
What is lumi.sensor_wleak time_start_offset?
lumi.gateway.aqhm01 - light is working without any problems but motion is not working (I don't think it's feature of this device).  Anyway, main question about that hub - Is it possible to control Alarm & door bell function?
Sorry for many questions, appreciate this integration!
