### ISSUE TITLE
所有云端模式下的设备都不可用了

### ISSUE THREAD

**Issue by Joynaruto2nd** [al-one/hass-xiaomi-miot#310]
版本0412
用了好几天今天突然出问题
上午出现了个别设备离线，重启home assistant就好了
下午开始 所有设备的实体都显示 不可用（红色感叹号），我已尝试卸载重装插件，安装0411版本都没用
我选择的是自动的方法，输入账号密码，设备都能显示也能添加，但所有实例都是不可用（红色感叹号）
但奇怪的是，我点开实例，发现是数据都是有记录的（比如温度计能显示几秒前更新了温度，但实体里就是不可用）

**Comment by SUNDONG1996** [comment]
我也是，突然所有设备都下线

**Comment by Joynaruto2nd** [comment]
> 我也是，突然所有设备都下线

我还以为是我的问题，我尝试了各种重装（包括降级；卸载再重装到master分支），最后又整了个新的HA再次尝试，问题依旧

**Comment by al-one** [comment]
貌似是米家APP接口有点问题，请耐心再等待一会。

**Comment by Joynaruto2nd** [comment]
> 貌似是米家APP接口有点问题，请耐心再等待一会。

ok！谢谢大佬回复！

**Comment by al-one** [comment]
> {"code":0,"message":"throttle ignore"}

这是米家接口返回的，看这样子是小米对接口做了节流限制，太频繁的抓取状态会被限制访问。

**Comment by Joynaruto2nd** [comment]
> > {"code":0,"message":"throttle ignore"}
> 
> 这是米家接口返回的，看这样子是小米对接口做了节流限制，太频繁的抓取状态会被限制访问。

这= =、、怎么办啊  有什么方法限制访问频率嘛
我现在是是不是得把插件卸载了再等待 我看实体的显示还是灰色不可用，但数据还在更新（温度计大概是几分钟更新一下）

**Comment by PladyChan** [comment]
我也一样

**Comment by PladyChan** [comment]
是不是升级了米家7.0之后 开了那个全屋控制中心引起的

**Comment by al-one** [comment]
> 是不是升级了米家7.0之后 开了那个全屋控制中心引起的

不是，是今天下午突然开始的。米家7.0我很久前就升级了。

**Comment by donald-ong** [comment]
Same, I hit the same issues. All my xiaomi and aqara devices failed to query via miot.

**Comment by pnobear** [comment]
原来如此，我以为是我自己的问题。

**Comment by pnobear** [comment]
> 

我都卸载重装了一样。建议不必折腾。

**Comment by 020794** [comment]
希望作者优先开发本地协议，才是治本

**Comment by al-one** [comment]
> 希望作者优先开发本地协议，才是治本

设备不支持本地miot协议，我也无能为力。

**Comment by goxofy** [comment]
same problem

**Comment by donald-ong** [comment]
Seems like need to fallback to use miio protocol. Seems to be still working.

**Comment by troilus** [comment]
今天下午13:00后突然全部unavailabl。
Error while executing request to https://api.io.mi.com/app/miotspec/prop/get :HTTPSConnectionPool(host='api.io.mi.com', port=443): Max retries exceeded with url: /app/miotspec/prop/get (Caused by NewConnectionError('<

**Comment by al-one** [comment]
有部分朋友反应恢复了，我的云端设备也恢复正常了。

**Comment by altapo** [comment]
> 有部分朋友反应恢复了，我的云端设备也恢复正常了。

Confirm

**Comment by Joynaruto2nd** [comment]
恢复了！话说有啥办法能延长向米家服务器请求吗？怕再次被封（哭哭

**Comment by goxofy** [comment]
恢复+1

**Comment by goxofy** [comment]
恢复+1

**Comment by al-one** [comment]
> 恢复了！话说有啥办法能延长向米家服务器请求吗？

```yaml
xiaomi_miot:
  device_customizes:
    '*.light.*':
      interval_seconds: 120
    '*.plug.*':
      interval_seconds: 120
```

**Comment by Joynaruto2nd** [comment]
> > 恢复了！话说有啥办法能延长向米家服务器请求吗？
> 
> ```yaml
> # configuration.yaml
> xiaomi_miot:
>   device_customizes:
>     '*.light.*':
>       interval_seconds: 120
>     '*.plug.*':
>       interval_seconds: 120
> ```

谢大佬指点！

**Comment by donald-ong** [comment]
Finally. :)

**Comment by al-one** [comment]
[`v0.5.0b0`](https://github.com/al-one/hass-xiaomi-miot/releases)测试版发布！支持本地模式接入miio协议的设备！欢迎各位大佬体验。该版本实现一套机制将miio协议转换为miot协议，并且能通过本插件以本地模式接入。不过由于miio协议的不规范性，目前仅支持[部分设备](https://github.com/al-one/hass-xiaomi-miot/blob/master/custom_components/xiaomi_miot/core/miio2miot_specs.py)，更多设备需要日后慢慢适配。
理论上所有小米的WiFi设备(开放了本地协议)都能通过本地模式接入，从而减小对小米接口的依赖。

**Comment by donald-ong** [comment]
@al-one I have updated to the beta releases to test out.

**Comment by al-one** [comment]
[v0.5.0](https://github.com/al-one/hass-xiaomi-miot/releases/latest)正式版已经发布，此版本大大解决了WiFi设备对小米接口的调用。我觉得是时候关闭这个issue了。
