### ISSUE TITLE
能够通过customization.yaml自定义数据的解析和显示

### ISSUE THREAD

**Issue by itispip** [al-one/hass-xiaomi-miot#313]
以cuco.plug.cp2这个插座为例，注意到HA一启动，switch.cuco_cp2_switch这个parent entity就已经很快获得包括sub-entity需要引用的属性的全部value，但是几个sub-entity包括Power，Current, Voltage, Power_Cost_Today, Power_Cost_Month还要等待将近20~30秒以后才会更新。

我试过在customization中bind sensor, 也并不能加快sub-entity开机创建的过程。甚至如果sub-entity和parent-entity的interval_seconds不一样的话，它们的value更新都是不同步的，是否说明sub-entity是另外的cloud pull获得value的吗？

能够考虑sub entity的值从parent entity的property当中获得呢？这样是否会更快吗？除非sub-entity的value没有包含在parent的property当中。

**Comment by al-one** [comment]
目前子实体的状态就是从父实体中拿到的，更新状态是由父实体完成的，所以`interval_seconds`只能用于父实体。但是子实体是在父实体注册到Hass以后才创建的，所以导致HA启动后子实体需多等待一会才变为可用。
