### ISSUE TITLE
Gosund 彩光灯带 cuco.light.sl4 添加后日志报错无法使用

### ISSUE THREAD

**Issue by littlesky87** [al-one/hass-xiaomi-miot#315]
之前的老版本（0.4.10）中可以正常使用，升级后出现问题，帮忙看一下原因。

插件版本：0.4.14
HA版本：2021.12.3
设备：cuco.light.sl4

报错日志：

Logger: custom_components.xiaomi_miot.light
Source: custom_components/xiaomi_miot/__init__.py:1096
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 10:58:04 (39 occurrences)
Last logged: 11:17:04

洞洞板灯带 Light: Got MiioException while fetching the state: Unable to discover the device 192.168.1.158, mapping: {'light.on': {'siid': 2, 'piid': 1}, 'light.mode': {'siid': 2, 'piid': 2}, 'light.brightness': {'siid': 2, 'piid': 3}, 'light.color': {'siid': 2, 'piid': 4}, 'version_two.delay_open': {'siid': 6, 'piid': 1}, 'collection.list': {'siid': 5, 'piid': 1}, 'collection.add': {'siid': 5, 'piid': 2}, 'music.swich': {'siid': 4, 'piid': 1}, 'scene.mode': {'siid': 3, 'piid': 1}, 'scene.change_type': {'siid': 3, 'piid': 2}, 'scene.brightness': {'siid': 3, 'piid': 3}, 'scene.color': {'siid': 3, 'piid': 4}, 'scene.change_speed': {'siid': 3, 'piid': 5}, 'scene.default_color': {'siid': 3, 'piid': 6}}, max_properties: 7/14

**Comment by al-one** [comment]
请检查下设备IP是都有变动，如果是token集成需要手动更新IP，如果是账号集成需要通过集成选项更新设备列表并保存配置。
![image](https://user-images.githubusercontent.com/4549099/146707977-7d576c7b-c45d-4772-836f-e7fd13e4e051.png)

**Comment by littlesky87** [comment]
已解决，谢谢。
