### ISSUE TITLE
leshow.heater.bs1 shows heater internal temperature as current temperature

### ISSUE THREAD

**Issue by mouth4war** [al-one/hass-xiaomi-miot#316]
https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:heater:0000A01A:leshow-bs1:1

Room temp is showing 40C (heater fins temperature) instead of room environment temperature (which is showing as a sensor). These variables should be switched.

**Comment by mouth4war** [comment]
![image](https://user-images.githubusercontent.com/30283635/146714128-75de624e-5a44-44de-abad-4b7e861cab45.png)

Fix:
Replace Environment Temperature with Heater Temperature in sensor name.
Switch current temperature and heater temperature around

**Comment by al-one** [comment]
I don't think there's anything wrong with it.

**Comment by mouth4war** [comment]
My room is not currently at 36C, it is at 25C which is showing as a sensor instead of climate current temperature.

36C is the heater internal temperature and should instead be shown as a sensor called "Heater Internal Temperature".

25C is the room current temperature and should be shown as climate current temperature.

**Comment by zray3dvn** [comment]
> ![image](https://user-images.githubusercontent.com/30283635/146714128-75de624e-5a44-44de-abad-4b7e861cab45.png)
> 
> Fix: Replace Environment Temperature with Heater Temperature in sensor name. Switch current temperature and heater temperature around

could you share the way to add countdown timer card, my heater is "leshow.heater.bs1s", I cannot add the low mod and countdown card. Thanks
![image](https://user-images.githubusercontent.com/59231248/152691299-0e5ce633-2d57-4722-ad8f-0c4a815a6aef.png)

**Comment by mtbhomer** [comment]
Hello, I also encountered this problem with the wrong temperature (internal instead of environment temperature). I'm curious if there could be a fix for this? @al-one @mouth4war 

![Screenshot 2023-01-07 at 12 20 30](https://user-images.githubusercontent.com/182211/211130721-fbebb0ca-076e-47df-99e6-493ef7f8f1d9.png)

![Screenshot 2023-01-07 at 12 21 11](https://user-images.githubusercontent.com/182211/211130741-e9cca3dc-7032-44b4-98d1-124e2de057ae.png)

**Comment by al-one** [comment]
Show me the [entity attributes](https://my.home-assistant.io/redirect/developer_states).

**Comment by al-one** [comment]
Try master branch.

**Comment by mtbhomer** [comment]
> Show me the [entity attributes](https://my.home-assistant.io/redirect/developer_states).

Here you go:

hvac_modes:
  - auto
  - 'off'
min_temp: 18
max_temp: 28
target_temp_step: 1
preset_modes:
  - Sleep
  - 'off'
current_temperature: 24
temperature: 22
hvac_action: heating
preset_mode: null
model: leshow.heater.bs1
lan_ip: 192.168.31.165
mac_address: redacted
entity_class: MiotClimateEntity
home_room: redacted
miot_type: urn:miot-spec-v2:device:heater:0000A01A:leshow-bs1:1
heater.on: true
heater.mode: 0
heater.target_temperature: 22
heater.temperature: 41
alarm: false
physical_controls_locked: false
environment.temperature: 24
countdown.countdown_time: 0
state_updater: cloud
sub_entities:
  - heater-2.on-1
  - countdown-3.countdown_time-1
  - environment-4.temperature-7
  - physical_controls_locked-5.physical_controls_locked-1
icon: mdi:heat-wave
friendly_name: Baseboard Heater
supported_features: 17

**Comment by mtbhomer** [comment]
> Try master branch.

Awesome! Just tested the changes, and happy to report it's now showing the correct environment temperature attribute. Tks!
