### ISSUE TITLE
pwzn.plug.banana继电器接入HA后反应特别慢

### ISSUE THREAD

**Issue by cuihaijun** [al-one/hass-xiaomi-miot#321]
对不起，我不会讲英文，我有一个型号为[pwzn.plug.banana](https://home.miot-spec.com/s/pwzn.plug.banana)继电器，在HA中开与关时，米家APP中很快能显示开与关的状态，但是在米家APP中控制开与关时，HA显示延迟近30秒左右，能不能提高一下延时时间，谢谢！

**Comment by al-one** [comment]
请参考下这里：https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-909031222
