### ISSUE TITLE
显示可访问米家服务器unreachable

### ISSUE THREAD

**Issue by terryzsb** [al-one/hass-xiaomi-miot#322]
是我一个人的问题吗?为啥我新装的 Xiaomi Miot Auto 一直都无法访问到米家服务器？我需要什么额外的设置吗

**Comment by al-one** [comment]
参考下这里：https://github.com/al-one/hass-xiaomi-miot/issues/318#issuecomment-1000247112

**Comment by al-one** [comment]
该问题解决了吗？

**Comment by terryzsb** [comment]
解决了，感谢大佬！！！
