### ISSUE TITLE
Mi Smart Kettle Pro (yunmi.kettle.v12) has no urn

### ISSUE THREAD

**Issue by Japander** [al-one/hass-xiaomi-miot#327]
Heyho,

i tried to add my Smart Kettle into Homeassistant, and get the following error:

`2021-12-27 09:05:28 DEBUG (MainThread) [custom_components.xiaomi_miot] Setup xiaomi cloud for user: xxx, 1 devices
2021-12-27 09:05:28 INFO (MainThread) [custom_components.xiaomi_miot] Xiaomi device: ['Mi Wasserkocher', 'yunmi.kettle.v12'] has no urn`

Seems like this device isnt supported? Is there a way to help you to include it?

Best regards, Marko

**Comment by al-one** [comment]
Not currently supported without `urn`.

**Comment by Japander** [comment]
Featurewise, it seems to be identical with this one here:
[yunmi.kettle.v13](https://home.miot-spec.com/spec?type=urn%3Amiot-spec-v2%3Adevice%3Akettle%3A0000A009%3Ayunmi-v13%3A1)

**Comment by al-one** [comment]
Execute this shell command on the terminal of  your HA host:
```shell
miiocli -d device --ip 192.168.lan.ip --token xxxxxx raw_command get_properties '[{"did": "miot", "siid": 2, "piid": 1}]'
```

**Comment by Japander** [comment]
After a long search i found out, miiocli doesnt support bluetooth device like the kettle, but only wifi devices :-/

When using a BLE Scanner, i find these informations

![2021-12-29 13 54 25](https://user-images.githubusercontent.com/4379767/147664751-cca5faf3-6561-478c-8d86-a764ff54cdc1.jpg)
![2021-12-29 13 54 35](https://user-images.githubusercontent.com/4379767/147664753-35cb28f8-08a4-43c1-9678-cdfdac8ac22c.jpg)
![2021-12-29 13 55 39](https://user-images.githubusercontent.com/4379767/147664758-f7df2e74-3ba2-426d-8095-0a037c95f442.jpg)

**Comment by al-one** [comment]
Try this: https://github.com/custom-components/ble_monitor

**Comment by adriananeci** [comment]
> Try this: https://github.com/custom-components/ble_monitor

It doesn't work because kettle PRO requires an active connection and `ble_monitor` only supports passive listening to BLE advertisements. See https://github.com/custom-components/ble_monitor/issues/398 and https://github.com/custom-components/ble_monitor/issues/509 for more context.

**Comment by al-one** [comment]
This component is powerless, because it can only obtain the device state through LAN or Xiaomi cloud (urn is required).

**Comment by adriananeci** [comment]
@al-one any particular reasons why this issue was closed?

As @Japander mentioned, `yunmi.kettle.v12` seems to be almost identical with `yunmi.kettle.v13` which I suppose is already working.
