### ISSUE TITLE
isa.camera.hlc6 crashes on hw_ver

### ISSUE THREAD

**Issue by marines** [al-one/hass-xiaomi-miot#33]
I've just set up a fresh HA instance and I'm trying to integrate the isa.camera.hlc6 camera. I'm running HA in a docker container in host network mode. I've tried the latest stable, latest beta and master branch build of the integration. I'm using Europe Mi servers.

Providing host/token ends up with the following error on initialization:

```
homeassistant    | 2021-03-14 17:00:38 ERROR (MainThread) [homeassistant.components.camera] Error while setting up xiaomi_miot platform for camera
homeassistant    | Traceback (most recent call last):
homeassistant    |   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
homeassistant    |     await asyncio.shield(task)
homeassistant    |   File "/config/custom_components/xiaomi_miot/camera.py", line 44, in async_setup_entry
homeassistant    |     await async_setup_config_entry(hass, config_entry, async_setup_platform, async_add_entities, ENTITY_DOMAIN)
homeassistant    |   File "/config/custom_components/xiaomi_miot/__init__.py", line 349, in async_setup_config_entry
homeassistant    |     await async_setup_platform(hass, c, async_add_entities)
homeassistant    |   File "/config/custom_components/xiaomi_miot/camera.py", line 62, in async_setup_platform
homeassistant    |     entities.append(MiotCameraEntity(hass, cfg, srv))
homeassistant    |   File "/config/custom_components/xiaomi_miot/camera.py", line 71, in __init__
homeassistant    |     super().__init__(miot_service, config=config)
homeassistant    |   File "/config/custom_components/xiaomi_miot/__init__.py", line 903, in __init__
homeassistant    |     super().__init__(miot_service, device, **kwargs)
homeassistant    |   File "/config/custom_components/xiaomi_miot/__init__.py", line 538, in __init__
homeassistant    |     super().__init__(name, device, **kwargs)
homeassistant    |   File "/config/custom_components/xiaomi_miot/__init__.py", line 389, in __init__
homeassistant    |     'hardware_version': self._miio_info.hardware_version,
homeassistant    |   File "/usr/local/lib/python3.8/site-packages/miio/device.py", line 84, in hardware_version
homeassistant    |     if self.data["hw_ver"] is not None:
homeassistant    | KeyError: 'hw_ver'
```

Setting up an integration with Mi Account credentials successfuly adds devices but it shows either that camera is off or there was an error opening stream:

```
homeassistant    | 2021-03-14 17:09:56 ERROR (MainThread) [homeassistant.components.camera] Error requesting stream: Camera is off
```

```
homeassistant    | 2021-03-14 17:13:25 ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream https://de01.livestreaming.io.mi.com/hlstranscoder/.../playlist.m3u8
```

Let me know if I can help fixing this somehow as I cannot use the camera in HA. :(

**Comment by marines** [comment]
Just to add that with the above fix the camera can be added properly but it says that camera is off when trying to view the feed.

**Comment by al-one** [comment]
Get the `stream_address` from the entity state attributes (Developer tools > [State](https://my.home-assistant.io/redirect/developer_states)), and test whether it can play through VLC and other players.

**Comment by marines** [comment]
There is no `stream_address` attribute. :/

![image](https://user-images.githubusercontent.com/78715/111494162-88eeb700-873e-11eb-970c-2e8a312e7e42.png)

**Comment by al-one** [comment]
Before getting the stream address, click on the camera entity dialog, and the stream address is only valid for 5 minutes.

**Comment by marines** [comment]
I have also tried that before but `stream_address` didn't show up.

![image](https://user-images.githubusercontent.com/78715/111498777-8b531000-8742-11eb-8e51-125a117a9e74.png)

**Comment by al-one** [comment]
The `state_updater` is `lan`, do your enable [miot_cloud](https://github.com/al-one/hass-xiaomi-miot#configuration-xiaomi-cloud) ?

**Comment by marines** [comment]
Right. Forgot that the camera requires cloud connection. So with cloud connection enabled there is the issue I've described in the first post.

Here's the entity state:

![image](https://user-images.githubusercontent.com/78715/111503198-d2430480-8746-11eb-980a-5af2ec9ee029.png)

The playlist file is accessible by both my PC and HA container and has the following content (except X-es):

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=250000
chunklist_w2XXXXXXX1.m3u8
```

But VLC just spins trying to load the stream.

**Comment by lexin8** [comment]
Abnormal camera access seems not a case. At present, the plug-in is not well supported!

**Comment by marines** [comment]
@al-one Does that mean it can't be fixed?

**Comment by al-one** [comment]
If the stream address is not available, then I have no idea.
This component only generates camera entity proxy to stream address through HA ffmpeg.
