### ISSUE TITLE
智能马桶和马桶盖支持

### ISSUE THREAD

**Issue by kylinfedora** [al-one/hass-xiaomi-miot#334]
大神是否看下能不能支持智能马桶和马桶盖的支持，论坛中有对其的描述，https://bbs.hassbian.com/thread-12045-1-1.html
希望支持的主要是是否有人、加热、夜灯等功能的支持
miot spec：http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:toilet:0000A02E:xjx-relax:1

**Comment by al-one** [comment]
我在最新的提交 https://github.com/al-one/hass-xiaomi-miot/commit/b0de0790648e39ee45ec213a01d5403fec649440 中适配了本地模式，请更新到master分支后尝试。

**Comment by kylinfedora** [comment]
@al-one 谢谢大神的支持，是否能再添加 小鲸洗智能坐便盖Pro版的支持

miot spec：https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:toilet:0000A02E:xjx-pro:1

**Comment by al-one** [comment]
请升级至master分支后尝试。

**Comment by al-one** [comment]
请问有用吗？
