### ISSUE TITLE
Gosund CP5 power strip (cuco.plug.sp5) wifi reconnects when integrate in MioT Auto

### ISSUE THREAD

**Issue by chertvl** [al-one/hass-xiaomi-miot#335]
Hello.

I bought [Gosund CP5 power strip (cuco.plug.sp5)](https://home.miot-spec.com/s/cuco.plug.sp5) and tried to integrate it in MioT Auto as Local mode,
but I have a problem:
Just when I integrating my CP5, It start to reconnect to Wi-fi every 1 minute (or less), and turns off and on all them switches automatically.
In HA logs I have a Error about Unable to discover device <IP> (screenshot).
I have all 6 switches in device (4 channels, 1 usb channel, and 1 common switch) but it in unavailable states.

When I delete Miot Auto integration, powerstrip works well in mihome, router sessions without disconnects.

Miio protocol produces disconnects.

Please help me, what I can check/edit for getting it work?

One interesting thing - I found and write to another guy, who have same powerstip, and he told me it works perfectly, he used all same versions of this:

HA Core 2021.12.6
Miot Auto v0.4.15 in local mode
cuco.plug.sp5 - 2.1.3_0013 firmware

![image](https://user-images.githubusercontent.com/38353584/147639082-7739d334-2da2-4bcf-8c36-c4bba943593b.png)

**Comment by al-one** [comment]
I think it's because the device can't withstand too high concurrent requests. You can upgrade to branch [v0.4.x](https://github.com/al-one/hass-xiaomi-miot/tree/v0.4.x) and try again. I ignored some unimportant services for the device in my latest commit: https://github.com/al-one/hass-xiaomi-miot/commit/44f288f49ecea7d107158770486a0578e88b5bb4.

> This branch can only be installed manually or through this shell command:
> `wget -q -O - https://cdn.jsdelivr.net/gh/al-one/hass-xiaomi-miot/install.sh | ARCHIVE_TAG=v0.4.x bash -`

**Comment by chertvl** [comment]
> [4f36156](https://github.com/al-one/hass-xiaomi-miot/commit/4f36156c0e269360b0667159c5b853c0cc89984a).
Thank you for quick feedback.

Now the sutiation is better. 
When HA starts (or when I integrate device) still have errors in logs (1st screeshot) and my powerstrip turns off and on once (all channels), device again loses Wi-Fi.

Then I need to wait 5-10 minutes and finally I got all 6 working switches (2nd screenshot)  ;3  


![image](https://user-images.githubusercontent.com/38353584/147646544-72daad9c-d697-47fc-be12-da521bd95d2e.png)

![image](https://user-images.githubusercontent.com/38353584/147647068-a9d37049-b30a-4ae1-9a6c-abcdce43ef5f.png)

**Comment by chertvl** [comment]
Testing some more time and did HA restarts few times.
Yep, PowerStrip toggle all them channels and loses wifi all time, when HA restarts (and have same errors in logs).
Without HA restarts all works perfectly.

**Comment by chertvl** [comment]
Still have this errors with all branches, errors are shown while integration or HA starts, power strip toggles all switches at that moment. 
What branch I need to test? 
Thank you!

**Comment by al-one** [comment]
Please upgrade master branch and try again.
```shell
wget -q -O - https://cdn.jsdelivr.net/gh/al-one/hass-xiaomi-miot/install.sh | ARCHIVE_TAG=master bash -
```

**Comment by chertvl** [comment]
Many thanks for your work!
Now the situation is next:
Wifi reconnects gone; errors about indicator, custome, lock - gone; switch re-toggles at start gone too.
Switch works well, but:
1. at integration start I got 2-3 little errors (screenshot 1)
2. switches bot updates automatically (for example, if a turn off any switch with another way (manually with button on body, Mihome, etc), Got warning about it (screenshot 2)

![Screenshot_20220104-083227_Home Assistant](https://user-images.githubusercontent.com/38353584/148018724-f6d82e3f-50a0-4a04-b2a0-a6d1043d3652.jpg)


![Screenshot_20220104-082541_Home Assistant](https://user-images.githubusercontent.com/38353584/148018530-85f54ccd-5aa1-4043-8b5a-327486377d93.jpg)

**Comment by al-one** [comment]
This outlet has [six switch services](https://home.miot-spec.com/spec/cuco.plug.sp5) (including main switch and USB). During initialization, the component will send at least six query requests to the device at the same time. Maybe this is too frequent for the device. But there is no better way.
Maybe you can try to keep this device in only one integration.

**Comment by chertvl** [comment]
> This outlet has [six switch services](https://home.miot-spec.com/spec/cuco.plug.sp5) (including main switch and USB). During initialization, the component will send at least six query requests to the device at the same time. Maybe this is too frequent for the device. But there is no better way.
> Maybe you can try to keep this device in only one integration.

That interesting, outlet works well with MioT raw integration ( https://github.com/ha0y/xiaomi_miot_raw ), no any errors or timeouts.
Only one thing: service switch.toggle not works with switches, but switch.turn_on and switch.turn_off works as well.
State updates of all 7 objects without problems (6 switches and 7th "lock" domain object (for locking physical buttons)).
But anyway, I dont want use Raw integration, it looks like abadoned, last updated 3+ month ago.
