### ISSUE TITLE
大神你好，请问如何将ha中的摄像头接入homekit？

### ISSUE THREAD

**Issue by WillionFe** [al-one/hass-xiaomi-miot#337]
我已经将mijia.camera.v3型号的摄像头接入HA，能够正常的查看视频，但貌似没有自动的通过HASS bridge接入到home app中，请问有什么办法将其接入吗？

**Comment by al-one** [comment]
摄像头类型的实体无法通过桥接模式接入HomeKit，需要通过配件模式(accessory)。

**Comment by WillionFe** [comment]
原来如此，已成功接入home app，谢谢大神～
