### ISSUE TITLE
青萍空气检测仪 如何在HK里显示tvoc

### ISSUE THREAD

**Issue by googooog** [al-one/hass-xiaomi-miot#340]
请问青萍空气检测仪 如何在HK里显示tvoc

目前只能显示pm2.5。

customize中设置：

sensor.s1_cloud_152614_density_3:
  friendly_name: "tvoc"
  device_class: tvoc

HK里不显示tvoc数值

**Comment by al-one** [comment]
`tvoc`类型的传感器貌似目前还不支持直接接入homekit，具体请看：[Supported Components](https://www.home-assistant.io/integrations/homekit#supported-components)。
你可能需要要`device_class`改为`pm25`/`co`/`co2`。
![image](https://user-images.githubusercontent.com/4549099/148529065-203d56cc-428e-4210-adc2-1d84a3bc1bb0.png)
