### ISSUE TITLE
stoped working today with viomi.vacuum.v8 

### ISSUE THREAD

**Issue by radimsejk** [al-one/hass-xiaomi-miot#344]
I have installed this integration and it worked with my robot until today. Now is the device unavailable. When I tried thy python script for extracting cloud token, it says "unable to get devices". The vacuum is working normaly and I can see it or control it via the Mi Home app normaly.

**Comment by kennetjuh** [comment]
most likely the same issue as https://github.com/al-one/hass-xiaomi-miot/issues/345 (europe server has changed?)

**Comment by radimsejk** [comment]
> most likely the same issue as #345 (europe server has changed?)

It looks like it. And [this](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/issues/50#issuecomment-1003546251) one too.

**Comment by al-one** [comment]
https://github.com/al-one/hass-xiaomi-miot/issues/345#issuecomment-1003857714
