### ISSUE TITLE
chuangmi.gateway.ipc011 Will this camera ever start working?

### ISSUE THREAD

**Issue by Jo-Jo1987** [al-one/hass-xiaomi-miot#347]
chuangmi.gateway.ipc011 Will this camera ever start working?

I use the Xiaomi Gateway Cameras from Ali express. 

I am wondering if these would ever be supported with streams and so on.

**Comment by al-one** [comment]
The device is not supported because no service is defined in its [miot-spec](https://home.miot-spec.com/spec/chuangmi.gateway.ipc011).
