### ISSUE TITLE
组网的异地米家智能插座2蓝牙网关版是集成不了的吗？

### ISSUE THREAD

**Issue by mwdhk** [al-one/hass-xiaomi-miot#348]
智能插座新手

填局域网IP，HA服务器ping得通
Token用token_extractor.exe正常获取

添加集成提交后提示“连接设备失败”
本地的米家智能插座2蓝牙网关版可正常集成

**Comment by al-one** [comment]
异地组网的环境是不支持的，包括同网络环境下划分子网也不支持，这种情况只能用云端模式。
参考：https://github.com/rytilahti/python-miio/issues/422#issuecomment-455824152

**Comment by mwdhk** [comment]
好的，感谢指导
