### ISSUE TITLE
dreame.vacuum.p2028 problem

### ISSUE THREAD

**Issue by Techfreak96** [al-one/hass-xiaomi-miot#350]
[dreame.vacuum.p2028](https://home.miot-spec.com/s/dreame.vacuum.p2028) unfortunately does not work. 

"Robot Cleaner: Got MiioException while fetching the state: Unable to discover the device"

**Comment by Techfreak96** [comment]
Log:

Logger: custom_components.xiaomi_miot.vacuum
Source: custom_components/xiaomi_mRobot Cleaner: Got MiioException while fetching the state: Unable to discover the device 192.168.179.13, mapping: {'vacuum.status': {'siid': 2, 'piid': 1}, 'vacuum.fault': {'siid': 2, 'piid': 2}, 'vacuum.mode': {'siid': 2, 'piid': 3}, 'collect_dust.auto_collect': {'siid': 15, 'piid': 1}, 'collect_dust.clean_times': {'siid': 15, 'piid': 2}, 'collect_dust.dust_enable': {'siid': 15, 'piid': 3}, 'clean_logs.first_clean_time': {'siid': 12, 'piid': 1}, 'clean_logs.total_clean_time': {'siid': 12, 'piid': 2}, 'clean_logs.total_clean_times': {'siid': 12, 'piid': 3}, 'clean_logs.total_clean_area': {'siid': 12, 'piid': 4}, 'audio.volume': {'siid': 7, 'piid': 1}, 'audio.voice_packet_id': {'siid': 7, 'piid': 2}, 'audio.voice_change_state': {'siid': 7, 'piid': 3}, 'audio.set_voice': {'siid': 7, 'piid': 4}, 'map.frame_info': {'siid': 6, 'piid': 2}, 'map.map_extend_data': {'siid': 6, 'piid': 4}, 'map.mult_map_state': {'siid': 6, 'piid': 7}, 'map.mult_map_info': {'siid': 6, 'piid': 8}, 'do_not_disturb.enable': {'siid': 5, 'piid': 1}, 'do_not_disturb.start_time': {'siid': 5, 'piid': 2}, 'do_not_disturb.end_time': {'siid': 5, 'piid': 3}, 'vacuum_extend.work_mode': {'siid': 4, 'piid': 1}, 'vacuum_extend.cleaning_time': {'siid': 4, 'piid': 2}, 'vacuum_extend.cleaning_area': {'siid': 4, 'piid': 3}, 'vacuum_extend.cleaning_mode': {'siid': 4, 'piid': 4}, 'vacuum_extend.mop_mode': {'siid': 4, 'piid': 5}, 'vacuum_extend.waterbox_status': {'siid': 4, 'piid': 6}, 'vacuum_extend.task_status': {'siid': 4, 'piid': 7}, 'vacuum_extend.clean_extend_data': {'siid': 4, 'piid': 10}, 'break_point_restart-4-11': {'siid': 4, 'piid': 11}, 'vacuum_extend.carpet_press': {'siid': 4, 'piid': 12}, 'vacuum_extend.serial_number': {'siid': 4, 'piid': 14}, 'vacuum_extend.remote_state': {'siid': 4, 'piid': 15}, 'vacuum_extend.clean_rags_tip': {'siid': 4, 'piid': 16}, 'vacuum_extend.keep_sweeper_time': {'siid': 4, 'piid': 17}, 'vacuum_extend.faults': {'siid': 4, 'piid': 18}, 'vacuum_extend.nation_matched': {'siid': 4, 'piid': 19}, 'vacuum_extend.relocation_status': {'siid': 4, 'piid': 20}, 'filter.filter_life_level': {'siid': 11, 'piid': 1}, 'filter.filter_left_time': {'siid': 11, 'piid': 2}, 'brush_left_time-10-1': {'siid': 10, 'piid': 1}, 'brush_life_level-10-2': {'siid': 10, 'piid': 2}, 'brush_cleaner.brush_left_time': {'siid': 9, 'piid': 1}, 'brush_cleaner.brush_life_level': {'siid': 9, 'piid': 2}, 'battery.battery_level': {'siid': 3, 'piid': 1}, 'battery.charging_state': {'siid': 3, 'piid': 2}}, max_properties: 10/46

**Comment by Techfreak96** [comment]
Logger: custom_components.xiaomi_miot.vacuum
Source: custom_components/xiaomi_miot/__init__.py:1136
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 3. Januar 2022, 19:13:50 (742 occurrences)

Robot Cleaner: Got MiioException while fetching the state: Unable to discover the device 192.168.179.13, mapping: {'vacuum.status': {'siid': 2, 'piid': 1}, 'vacuum.fault': {'siid': 2, 'piid': 2}, 'vacuum.mode': {'siid': 2, 'piid': 3}, 'collect_dust.auto_collect': {'siid': 15, 'piid': 1}, 'collect_dust.clean_times': {'siid': 15, 'piid': 2}, 'collect_dust.dust_enable': {'siid': 15, 'piid': 3}, 'clean_logs.first_clean_time': {'siid': 12, 'piid': 1}, 'clean_logs.total_clean_time': {'siid': 12, 'piid': 2}, 'clean_logs.total_clean_times': {'siid': 12, 'piid': 3}, 'clean_logs.total_clean_area': {'siid': 12, 'piid': 4}, 'audio.volume': {'siid': 7, 'piid': 1}, 'audio.voice_packet_id': {'siid': 7, 'piid': 2}, 'audio.voice_change_state': {'siid': 7, 'piid': 3}, 'audio.set_voice': {'siid': 7, 'piid': 4}, 'map.frame_info': {'siid': 6, 'piid': 2}, 'map.map_extend_data': {'siid': 6, 'piid': 4}, 'map.mult_map_state': {'siid': 6, 'piid': 7}, 'map.mult_map_info': {'siid': 6, 'piid': 8}, 'do_not_disturb.enable': {'siid': 5, 'piid': 1}, 'do_not_disturb.start_time': {'siid': 5, 'piid': 2}, 'do_not_disturb.end_time': {'siid': 5, 'piid': 3}, 'vacuum_extend.work_mode': {'siid': 4, 'piid': 1}, 'vacuum_extend.cleaning_time': {'siid': 4, 'piid': 2}, 'vacuum_extend.cleaning_area': {'siid': 4, 'piid': 3}, 'vacuum_extend.cleaning_mode': {'siid': 4, 'piid': 4}, 'vacuum_extend.mop_mode': {'siid': 4, 'piid': 5}, 'vacuum_extend.waterbox_status': {'siid': 4, 'piid': 6}, 'vacuum_extend.task_status': {'siid': 4, 'piid': 7}, 'vacuum_extend.clean_extend_data': {'siid': 4, 'piid': 10}, 'break_point_restart-4-11': {'siid': 4, 'piid': 11}, 'vacuum_extend.carpet_press': {'siid': 4, 'piid': 12}, 'vacuum_extend.serial_number': {'siid': 4, 'piid': 14}, 'vacuum_extend.remote_state': {'siid': 4, 'piid': 15}, 'vacuum_extend.clean_rags_tip': {'siid': 4, 'piid': 16}, 'vacuum_extend.keep_sweeper_time': {'siid': 4, 'piid': 17}, 'vacuum_extend.faults': {'siid': 4, 'piid': 18}, 'vacuum_extend.nation_matched': {'siid': 4, 'piid': 19}, 'vacuum_extend.relocation_status': {'siid': 4, 'piid': 20}, 'filter.filter_life_level': {'siid': 11, 'piid': 1}, 'filter.filter_left_time': {'siid': 11, 'piid': 2}, 'brush_left_time-10-1': {'siid': 10, 'piid': 1}, 'brush_life_level-10-2': {'siid': 10, 'piid': 2}, 'brush_cleaner.brush_left_time': {'siid': 9, 'piid': 1}, 'brush_cleaner.brush_life_level': {'siid': 9, 'piid': 2}, 'battery.battery_level': {'siid': 3, 'piid': 1}, 'battery.charging_state': {'siid': 3, 'piid': 2}}, max_properties: 10/46

**Comment by al-one** [comment]
- Please confirm your device IP
- If the subnet divided: https://github.com/al-one/hass-xiaomi-miot/issues/349#issuecomment-1004179460
