### ISSUE TITLE
chuangmi_021a04 smooth video streaming

### ISSUE THREAD

**Issue by raptr55** [al-one/hass-xiaomi-miot#351]
Hello 

I have configured the camera but when i see the streaming video flow through home assistant It goes fast for about 5 seconds then It freeze and on and on. There Is a way to see the video flow smooth as in the mi app?

This Is my current customize.yaml:

camera.chuangmi_021a04_8fef_camera_control:
  keep_streaming: true
  video_attribute: 3
  miot_cloud: true
  motion_stream_slice : -2

**Comment by al-one** [comment]
There's nothing I can do about it. It's my best effort to see a screenshot or a few seconds of video.

**Comment by raptr55** [comment]
Ok i will close the issue in One week.

Thanks @al-one
