### ISSUE TITLE
chuangmi.gateway.ipc011

### ISSUE THREAD

**Issue by Jo-Jo1987** [al-one/hass-xiaomi-miot#358]
https://home.miot-spec.com/spec/chuangmi.gateway.ipc011

Will this camera ever be supported in home assistant? Just like the eufy doorbells.

**Comment by al-one** [comment]
https://github.com/al-one/hass-xiaomi-miot/issues/347#issuecomment-1006571536

No services are defined in this miot-spec.

**Comment by al-one** [comment]
Maybe you can share this device to account `143050915` (China server) through MiHome APP.

**Comment by tv4you2016** [comment]
@al-one 
I can share the device with account 143050915 (China server) through MiHome APP. if you so wish.
I can still do better I managed to dump all the partitions which I can share if I wish
