### ISSUE TITLE
chuangmi.plug.212a01 升级最新版本后不能用了

### ISSUE THREAD

**Issue by maybeloveu** [al-one/hass-xiaomi-miot#361]
升级0.5版本后一些传感器不可用了，只有switch显示可用，但是开关没反应
`Power Consumption
不可用
Power Consumption Electric
不可用
Power Consumption Electric Current
不可用
Power Consumption Surge power
不可用
Power Consumption Voltage
不可用
Switch Temperature
不可用
Switch power_cost_month
不可用
Switch power_cost_today
不可用`

**Comment by al-one** [comment]
我也有同型号的这个插座，没有你说的情况，实体都是正常的。请贴一下插座开关实体的属性（开发者工具 > 状态），以及是什么方式接入该设备的。

**Comment by maybeloveu** [comment]
升级最新版后本地添加了两个设备 小米路由器 和米兔儿童手表 净水器A1，发现都用不了。重启了一下这个插座也用不了了。
我还原了之前的备份（添加设备之前），在升级到新新版本，发现插座是能用的。应该不是新版本的问题。
问一下添加过的设备怎么删除？添加了的设备发现支持不是很好需要删了，使用其他插件接入。

**Comment by al-one** [comment]
v0.5支持miio设备本地接入，但也不是所有设备，需要适配过的型号才支持。推荐通过账号（自动模式）接入设备，插件会根据设备型号自动选择本地还是云端接入。

删除设备请看常见问题：#100
