### ISSUE TITLE
Zhimi.fan.fa1 work only 2 items

### ISSUE THREAD

**Issue by Aliskin-Papa** [al-one/hass-xiaomi-miot#362]
In the [zhimi.fan.fa1](https://home.miot-spec.com/s/zhimi.fan.fa1) i whatch only 2 items - Fan (on/off and speed) and Child block.
Other switch (vertical/horizontal, led, mode) - not present.

**Comment by al-one** [comment]
Show me the [state attributes](https://my.home-assistant.io/redirect/developer_states) of fan entity.

**Comment by Aliskin-Papa** [comment]
![IMG_20220108_182439](https://user-images.githubusercontent.com/76951399/148649841-c1e1091c-5f0b-45af-9d4a-a71732300741.jpg)

**Comment by Aliskin-Papa** [comment]
![Screenshot_2022-01-08-18-36-39-956_io homeassistant companion android](https://user-images.githubusercontent.com/76951399/148650241-cf0b6f97-d10d-4cb8-8a58-c3c09083f699.jpg)

**Comment by TheLordVader** [comment]
I have a similar problem after the latest update. Lost contact with my fan.

restored: true
speed_list:
  - 'off'
  - '1'
  - '2'
  - '3'
  - '4'
preset_modes:
  - Straight Wind
  - Natural Wind
friendly_name: Mi Standing Fan 2S 1 Fan
supported_features: 15

**Comment by al-one** [comment]
@Aliskin-Papa Please open the pop-up card of the fan entity to control the swing and preset mode.

**Comment by al-one** [comment]
@TheLordVader Any [logs](https://my.home-assistant.io/redirect/logs) about this device ?

**Comment by Aliskin-Papa** [comment]
> 

Yes, its work, but i cant set angle vertical/horisontal oscilate, cant set beep and light.

**Comment by TheLordVader** [comment]
> @TheLordVader Any [logs](https://my.home-assistant.io/redirect/logs) about this device ?

Yes:
Logger: homeassistant.helpers.service
Source: helpers/service.py:129
First occurred: 8 January 2022, 13:46:52 (3 occurrences)
Last logged: 8 January 2022, 21:35:31

Unable to find referenced entities fan.mi_standingfan2s_1

Entity says "This entity is currently unavailable and is an orphan to a removed, changed or dysfunctional integration or device. If the entity is no longer in use, you can clean it up by removing it."

**Comment by al-one** [comment]
@TheLordVader Not this log, please check whether you include this device in the integration option.

**Comment by al-one** [comment]
> Yes, its work, but i cant set angle vertical/horisontal oscilate, cant set beep and light.

@Aliskin-Papa You can [add this custom attributes](https://www.home-assistant.io/docs/configuration/customizing-devices/#customizing-entities):
```yaml
# customize.yaml
heater.zhimi_fa1_entity_id:
  switch_properties: vertical_swing,alarm,physical_controls_locked,h_swing_back,v_swing_back
  select_properties: brightness
  number_properties: vertical_angle,timing,stepless_fan_level
```

**Comment by Aliskin-Papa** [comment]
Thanks, i make new switch and ower, but horizon/vertikal angle not work. Allower work good!

**Comment by Aliskin-Papa** [comment]
![Screenshot_2022-01-10-10-22-44-084_io homeassistant companion android](https://user-images.githubusercontent.com/76951399/148730516-1bc48abe-ea60-4ebd-8943-65417aaac0fc.jpg)

**Comment by TheLordVader** [comment]
Hello again,

Yes, the fan is included in the integration. I have tried adding my account
again (duplicate) and then the fan is missing.
 All other 20 units are working fine.

Any suggestions? This happened after upgrading to 0.50.

**Comment by al-one** [comment]
@TheLordVader What is the model of your fan ? Maybe you can try the master branch.

**Comment by TheLordVader** [comment]
https://home.miot-spec.com/s/zhimi.fan.za4

I have never tried the master branch, I'm a little unfamiliar with Github and how to do. Strange that no one else seems to have the problem..?

**Comment by al-one** [comment]
@TheLordVader A friend in the discussion group reported a bug for `zhimi.fan.za4`, which has been fixed and commit. Just upgrade it to the master branch.
![xiaomi miot](https://user-images.githubusercontent.com/4549099/148519555-48cae2e4-a54b-4f76-b3a1-d6808748dea7.png)

**Comment by TheLordVader** [comment]
Great, thanks 👍! I really appreciate your work!

**Comment by al-one** [comment]
Does it work ?

**Comment by TheLordVader** [comment]
Nope. I tried Master branch and even downgrading to v0.4.17 without success. As of yesterday ALL my connected devices through the addon stopped working...

**Comment by al-one** [comment]
@TheLordVader  Update to master again and try.

**Comment by TheLordVader** [comment]
Just tried. Unfortunately it doesn't work with local devices (my fan and air purifier), just cloud connected to a hub/gateway working fine.

**Comment by TheLordVader** [comment]
Why closed? Issue still remains - no access to local devices.

**Comment by al-one** [comment]
@TheLordVader This issue is for `zhimi.fan.fa1`, you can open a new issue for your device.

**Comment by TheLordVader** [comment]
Thanks, missed that completely ;-)
