### ISSUE TITLE
cuco.plug.cp1小米插座无法使用

### ISSUE THREAD

**Issue by sxsjs123** [al-one/hass-xiaomi-miot#363]
固件：2.0.1_0011
以下是日志记录 ，谢谢

![image](https://user-images.githubusercontent.com/31535751/148648461-fa83241f-8405-446b-8682-89e550d6eaab.png)

**Comment by sxsjs123** [comment]
升级到0.5版本后解决了问题 谢谢

**Comment by sxsjs123** [comment]
升级到0.5版本后重启后又一次出现这个问题

![image](https://user-images.githubusercontent.com/31535751/148649332-56292333-4325-4889-bc8e-21e03aacfdc6.png)

**Comment by al-one** [comment]
有其他用户反馈v0.5版本此型号已没有问题。你是否有同感其他插件也集成了该设备？如没有的话，请尝试在米家重新绑定该设备。

**Comment by sxsjs123** [comment]
ok

**Comment by sxsjs123** [comment]
问题已经解决了  谢谢

**Comment by al-one** [comment]
可以分享下如何解决的吗？也许可以帮助其他人。

**Comment by sxsjs123** [comment]
好的好的  首先删除所有的集成  其次重新在米家绑定插座 。之后重新添加集成就行了 。 最后谢谢大大开发的软件非常好用哒
