### ISSUE TITLE
连接上米家 开关通断器wifi x版的问题

### ISSUE THREAD

**Issue by yyf2009** [al-one/hass-xiaomi-miot#366]
在连接上米家开关通断器wifi x版之后，这个通断器会隔一会就开关一次，不知如何解决

**Comment by al-one** [comment]
请尝试在配置文件中添加下面的配置：
```
​​​#​ configuration.yaml​​
​xiaomi_miot​:
  ​device_customizes​:
    leshi.switch.v002:
      exclude_miot_services: scenes,remote
```
然后重启HA（或在`服务控制`中重载）后重试。

**Comment by al-one** [comment]
请问上述方法有用吗？

**Comment by Aes64X** [comment]
> 请问上述方法有用吗？

emmmmmm。。。。 我来吧，相同的 leshi.switch.v002 
使用wifi网络，添加时明显比其他设备慢好多，添加完成开关为不可用状态并表现为间断性的自动开关，删除后恢复正常。

修改配置文件报错：Integration error: xiaomi_miot​ - Integration 'xiaomi_miot​' not found.
无法重启服务

我使用unraid docker运行 Home Ass

**Comment by Aes64X** [comment]
![微信截图_20220617121224](https://user-images.githubusercontent.com/47932152/174223377-fe35ab8b-aa8e-428b-b58a-c95b092ef060.png)

**Comment by Aes64X** [comment]
![微信截图_20220617121322](https://user-images.githubusercontent.com/47932152/174223466-fced0adc-6a23-469a-b19c-82503d5e1ad1.png)

**Comment by al-one** [comment]
> Integration error: xiaomi_miot​ - Integration 'xiaomi_miot​' not found.

@Aes64X 请确保你正确安装了本插件。

**Comment by Aes64X** [comment]
> 

仓库安装的呀，挂飞机安装的。。。。我也奇怪怎么提示这玩意 - -

**Comment by Aes64X** [comment]
> > Integration error: xiaomi_miot​ - Integration 'xiaomi_miot​' not found.
> 
> @Aes64X 请确保你正确安
![微信截图_20220617163326](https://user-images.githubusercontent.com/47932152/174260341-3a337521-26df-4d1c-b3b7-6cf91582777c.png)
装了本插件。

**Comment by al-one** [comment]
@Aes64X 请检查有无其他报错[日志](https://my.home-assistant.io/redirect/logs)，如果HA界面中没有，再检查下日志文件`home-assistant.log`。

**Comment by Aes64X** [comment]
> ```yaml
> scenes,remote
> ```
Integration error: xiaomi_miot​ - Integration 'xiaomi_miot​' not found.  仍然无法解决

改在 xiaomi_miot\core   device_customizes.py 文件中使用你的方法，验证成功，方法可行。
![微信截图_20220617173251](https://user-images.githubusercontent.com/47932152/174271314-98adce2b-681d-4945-b120-b46be7c09c24.png)

**Comment by Aes64X** [comment]
如有上述问题 按以下方式


    'leshi.switch.v002': {
        'exclude_miot_services': 'scenes,remote',
    },

添加在 xiaomi_miot/core/device_customizes.py  后重启HA

**Comment by al-one** [comment]
上面的[配置yaml](https://github.com/al-one/hass-xiaomi-miot/issues/366#issuecomment-1008214842)示例中的冒号后面存在不可见字符，导致你复制yaml到配置文件后报错，目前已移除不可见字符。
我会将该自定义选项默认添加至插件代码，后续升级无需在配置yaml和修改`device_customizes.py`文件。

**Comment by Aes64X** [comment]
> 上面的[配置yaml](https://github.com/al-one/hass-xiaomi-miot/issues/366#issuecomment-1008214842)示例中的冒号后面存在不可见字符，导致你复制yaml到配置文件后报错，目前已移除不可见字符。 我会将该自定义选项默认添加至插件代码，后续升级无需在配置yaml和修改`device_customizes.py`文件。

感谢！
