### ISSUE TITLE
cgllc.gateway.s1 integration works but no data

### ISSUE THREAD

**Issue by karolzamosc** [al-one/hass-xiaomi-miot#368]
Hi,

After integration Xiaomi BLE (cgllc.gateway.s1) gateway there is no data in HA from paired devices and no new entities too...

Regards,
Charles

**Comment by al-one** [comment]
If you want to integrate the sub devices of the gateway, you need to include the sub devices directly, not the gateway.

**Comment by karolzamosc** [comment]
> If you want to integrate the sub devices of the gateway, you need to include the sub devices directly, not the gateway.

Is there possibility to integrate the BLE temperature and humidity sensor (miaomiaoce.sensor_ht.t2) with HA and keep it working with Mi Home app too?

**Comment by al-one** [comment]
This component will get the state of the device from Xiaomi cloud.

**Comment by karolzamosc** [comment]
@al-one no way to get the states locally through cgllc.gateway.s1 gateway like it is done in the @AlexxIT Xiaomi Gateway 3 BLE integration?

**Comment by al-one** [comment]
- https://github.com/AlexxIT/XiaomiGateway3
- https://github.com/custom-components/ble_monitor
