### ISSUE TITLE
人体传感器一直处于触发状态

### ISSUE THREAD

**Issue by qiuyuxuan1999** [al-one/hass-xiaomi-miot#37]
看到新版本的插件支持门磁传感器和人体传感器了，也就相当于在HA里装了米家app了，控制了非WIFI设备。但是人体传感器一直显示触发状态，门磁传感器使用正常。或许跟米价服务器有关。

**Comment by al-one** [comment]
状态都是从米家服务器轮询获取的，每一分钟更新一次状态，因此不太适合人体传感器这类要求实时性比较高的设备。不过如果你的人体传感器有光照度`illumination`或无人移动时长`no_motion_duration`等环境字段，倒是可以通过本插件获取。

**Comment by qiuyuxuan1999** [comment]
> 状态都是从米家服务器轮询获取的，每一分钟更新一次状态，因此不太适合人体传感器这类实时性要求比较高的设备。不过如果你的人体传感器有光照度`illumination`或无人移动时长`no_motion_duration`等环境字段，倒是可以通过本插件获取。

我明白状态是轮询服务器获取的，但我想表达的问题是，这个状态一直显示触发，永远显示触发，而不是只在轮询间隔内没有变化。不知道是不是网关不向服务器上报无人状态，只在有人时上报。如果是这样，不知道大佬能不能从插件代码上解决。比如上次有人上报时间1分钟后自动变成无人。

**Comment by al-one** [comment]
这个没法实现的，因为如果每次读取到的状态都是有人移动，我也无法获取上次变化的时间是多少。

**Comment by qiuyuxuan1999** [comment]
> 这个没法实现的，因为如果每次读取到的状态都是有人移动，我也无法获取上次变化的时间是多少。

好的，如果米家服务器里没有上次有人时间，那这个估计无解了。

**Comment by al-one** [comment]
miot-spec协议中是没有最后移动时间的，顶多部分人体传感器会有`no_motion_duration`属性。

**Comment by al-one** [comment]
现已支持：https://github.com/al-one/hass-xiaomi-miot/issues/120#issuecomment-873782043
