### ISSUE TITLE
FIVE智能刀筷砧板杀菌架支持

### ISSUE THREAD

**Issue by Clevival2021** [al-one/hass-xiaomi-miot#370]
大神能否适配FIVE智能刀筷砧板杀菌架[uvfive.steriliser.tiger](https://home.miot-spec.com/s/uvfive.steriliser.tiger)，谢谢。

**Comment by al-one** [comment]
该设备已经是miot协议了，请问通过本插件接入有什么问题吗？

**Comment by Clevival2021** [comment]
> 该设备已经是miot协议了，请问通过本插件接入有什么问题吗？

通过集成配置，没有任何设备及实体出现。

**Comment by al-one** [comment]
请更新到master分支后尝试。

**Comment by Clevival2021** [comment]
感谢，已解决。
