### ISSUE TITLE
chuangmi.camera.v5

### ISSUE THREAD

**Issue by marcoahp** [al-one/hass-xiaomi-miot#371]
Stream is not working. How could I make it it work in home assistant?
![camera chuangmi v5](https://user-images.githubusercontent.com/49716815/148769678-c02ce575-7e4b-42a1-aaf9-43ea27512e59.jpg)
Those are the properties:

access_token: ---
brand: chuangmi
model: chuangmi.camera.v5
lan_ip: ---
mac_address: ---
entity_class: MiotCameraEntity
home_room: Casa de Marco Porche
miot_type: urn:miot-spec-v2:device:camera:0000A01C:chuangmi-v5:1
camera_control.on: true
camera_control.image_rollover: 0
camera_control.night_shot: 0
camera_control.time_watermark: true
camera_control.wdr_mode: true
camera_control.recording_mode: 2
state_updater: cloud
sub_entities: camera_control.on
entity_picture: /api/camera_proxy/camera.chuangmi_v5_490f_camera_control?token=---
friendly_name: Cámara Porche Camera Control
supported_features: 1

**Comment by marcoahp** [comment]
I think that the problem is my camera do not include  the service "camera-stream-for-google-home" in camera device miot-spec,
So, it's not goig to work. Somebody knows something about it?

**Comment by DarkoMir** [comment]
+1 for this
I have the same camera and confirm no "camera-stream-for-google-home"

**Comment by al-one** [comment]
There's nothing I can do about it. It's my best effort to see a screenshot or a few seconds of video after enable the `Home surveillance assistant` in the Mihome APP.
