### ISSUE TITLE
Xiaomi Mi Kettle Pro v12

### ISSUE THREAD

**Issue by RestOp** [al-one/hass-xiaomi-miot#374]
Hello,

i have Xiaomi Mi Kettle Pro v12. I have found it in the list of supported devices. 
![image](https://user-images.githubusercontent.com/46259141/149025807-637981bb-bd8a-4080-97f0-dcb55dbeba36.png)

Addon see it, but do not add to HA.
![image](https://user-images.githubusercontent.com/46259141/149025623-2e0ba6db-b879-449b-aa85-b94ec3c56041.png)
What can be the problem?

Thanks a lot!

**Comment by al-one** [comment]
Duplicate #327

**Comment by RestOp** [comment]
So why is it in ther list of compatible models? What can it means?

**Comment by al-one** [comment]
![](https://user-images.githubusercontent.com/46259141/149025623-2e0ba6db-b879-449b-aa85-b94ec3c56041.png)
This list does not filter unsupported devices.
