### ISSUE TITLE
请问下新增的支持米家设备消息传感器如何使用？

### ISSUE THREAD

**Issue by sephrioth** [al-one/hass-xiaomi-miot#377]
在米家App有发通知的前提下， 我好像没有找到相关的sensor？在对应的设备下也找不到相关信息， 请问下如何可以看到这个呢？
HA和插件均为最新版本。

**Comment by al-one** [comment]
设备消息传感器实体不存在与任何设备下面，是一个单独的实体，你可以通过开发者工具找到它。
![xiaomi miot](https://user-images.githubusercontent.com/4549099/149272845-be86eb9b-e296-4751-b154-546c7f39f499.png)

**Comment by sephrioth** [comment]
感谢您的快速回复， 我这里已经看过了， 但是并没有类似的 sensor

**Comment by al-one** [comment]
请确保你使用了账号模式集成。

**Comment by sephrioth** [comment]
谢谢， 通过账号模式添加后出现该 sensor 了，其余的我自己再测试下吧。
