### ISSUE TITLE
roidmi.vacuum.v60 vacuum-extend

### ISSUE THREAD

**Issue by ffesius** [al-one/hass-xiaomi-miot#379]
[roidmi.vacuum.v60](https://home.miot-spec.com/s/roidmi.vacuum.v60)
Does the vacuum cleaner support vacuum-extend? Didn't find vacuum-extend in documentation

**Comment by al-one** [comment]
`vacuum-extend` is not a standard miot service, maybe a custom service of a certain manufacturer. Your vacuum does not provide this service.

See https://home.miot-spec.com/spec/roidmi.vacuum.v60
