### ISSUE TITLE
Linptech WIFI Self-power-generating Wireless Doorbell (linp.doorbell.g03)

### ISSUE THREAD

**Issue by vampywiz17** [al-one/hass-xiaomi-miot#38]
It possible to add this device the support list?

https://www.banggood.com/Linptech-WIFI-Self-power-generating-Wireless-Doorbell-Work--p-1507639.html

**Comment by al-one** [comment]
Your device model is `linp.doorbell.g04` ?

**Comment by vampywiz17** [comment]
@al-one 

i take  pic. How to i check the device model?

![IMG_20210322_101309](https://user-images.githubusercontent.com/14281430/111966692-7e923b80-8af7-11eb-89bd-3d415d5c5e14.jpg)

**Comment by al-one** [comment]
You can try last commit: https://github.com/al-one/hass-xiaomi-miot/commit/8eac5c89597f4ad5bc7f8014f3969d2eb81993e3 of [master](https://github.com/al-one/hass-xiaomi-miot/tree/master).

**Comment by vampywiz17** [comment]
@al-one 

I try it, but get this:

`2021-03-22 11:18:10 ERROR (MainThread) [custom_components.xiaomi_miot] Got MiioException while fetching the state for Self-Powered Wirelss Doorbell Doorbell: {'code': -9999, 'message': 'user ack timeout'}`

it see this:

![image](https://user-images.githubusercontent.com/14281430/111975293-b8b40b00-8b00-11eb-8740-e6ac9bb5a541.png)

the device is: linp.doorbell.g03

the Entity say "not avaliable"

**Comment by al-one** [comment]
You need enable [miot_cloud](https://github.com/al-one/hass-xiaomi-miot#configuration-xiaomi-cloud).
Or `Add devices using Mi Account` (recommend).

**Comment by vampywiz17** [comment]
@al-one so it working only with internet?

**Comment by vampywiz17** [comment]
@al-one 

I try it, but not generate device. it is empty.

![image](https://user-images.githubusercontent.com/14281430/111978669-78568c00-8b04-11eb-9439-0fd5bab21004.png)

**Comment by al-one** [comment]
You need to include WiFi SSID/BSSID of device, or exclude empty list.

**Comment by vampywiz17** [comment]
> You need to include WiFi SSID/BSSID of device, or exclude empty list.

@al-one 

meantime i figure it, thanks :) So it only work with internet (cloud mode), right? Not possible to integrate it with Local mode?

**Comment by al-one** [comment]
Yes, this device don't support miot-spec in LAN.

**Comment by vampywiz17** [comment]
> Yes, this device don't support miot-spec in LAN.

@al-one 

I see. 

My other problem that i not see the button push trigger. Only just the ringtone volume.

![image](https://user-images.githubusercontent.com/14281430/111984167-4e549800-8b0b-11eb-9e9c-7efe7a6fc59b.png)

![image](https://user-images.githubusercontent.com/14281430/111984251-69bfa300-8b0b-11eb-9470-bb44fec2e520.png)

**Comment by al-one** [comment]
There is only one volume property in your device [miot-spec](http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:doorbell:0000A03B:linp-g03:1). It will support setting the volume later.
MIoT events are not supported.

**Comment by vampywiz17** [comment]
> There is only one volume property in your device [miot-spec](http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:doorbell:0000A03B:linp-g03:1). It will support setting the volume later.
> MIoT events are not supported.

hmm i see... so it not so usable in this form.

**Comment by al-one** [comment]
The last commit: https://github.com/al-one/hass-xiaomi-miot/commit/0b2e4b7f0ea025252c84ffa1095652ebd37a9202 of [master](https://github.com/al-one/hass-xiaomi-miot/tree/master) supports setting the volume for doorbell.
