### ISSUE TITLE
空气净化器开关不可用，模式类型有误；无设备报WARNING

### ISSUE THREAD

**Issue by lkaiy** [al-one/hass-xiaomi-miot#382]
小米空气净化器2代，zhimi.airpurifier.m1
1、开关不可用，当前运行模式为off和auto，且多了个预设模式sleep,favorite。查https://home.miot-spec.com/spec/zhimi.airpurifier.m1 可知，正常运行模式应为auto,sleep,favorite，使用switch开关控制开启关闭。
![image](https://user-images.githubusercontent.com/5352553/149527409-0cc3f10d-08df-4e75-a549-d192ad57c285.png)
![image](https://user-images.githubusercontent.com/5352553/149527429-f18aed18-fd10-4d37-851b-5ce5b8840104.png)

2、关闭空气净化器时，会报 WARNING (MainThread) [custom_components.xiaomi_miot.sensor] Get xiaomi message for XXXXXX failed: {'code': 0, 'message': 'ok', 'result': {'messages': None}} 的警告信息。不能完全确定是关闭导致，我偶尔会将空气净化器断开，此时该账号下无任何设备在线，也有可能是无任何在线设备的原因，该WARNING信息出现较为频繁。

**Comment by al-one** [comment]
由于本插件目前使用climate实体适配的空气净化器，关于其运行模式及预设模式的解释请参考https://github.com/al-one/hass-xiaomi-miot/issues/281#issuecomment-987581695 ，后期插件会考虑使用fan实体来适配空气净化器。

----

> Get xiaomi message for XXXXXX failed: {'code': 0, 'message': 'ok', 'result': {'messages': None}}

最新版本中添加了获取米家设备通知的传感器，出现这个warning日志，是因为你的米家账号没有收到过任何设备或系统通知。

**Comment by al-one** [comment]
最新的提交（https://github.com/al-one/hass-xiaomi-miot/commit/5b5fb895a5325a16b8428e6d6207f77cba85275f ）中已为该设备适配了本地模式，并通过fan实体实现，旧的climate实体仍会保留一段时间并标记弃用，会在后续版本中移除。

**Comment by CrushTide** [comment]
希望zhimi.airp.va2/zhimi.airpurifier.rma1也能通过fan实体实现

**Comment by al-one** [comment]
@CrushTide 请更新到master分支。

**Comment by CrushTide** [comment]
> @CrushTide 请更新到master分支。

搞定，看来以后不能用HACS了，选master竟然都不是最新

**Comment by lkaiy** [comment]
> 最新的提交（[5b5fb89](https://github.com/al-one/hass-xiaomi-miot/commit/5b5fb895a5325a16b8428e6d6207f77cba85275f) ）中已为该设备适配了本地模式，并通过fan实体实现，旧的climate实体仍会保留一段时间并标记弃用，会在后续版本中移除。

谢谢大神，响应真快速！！
