### ISSUE TITLE
deerma.humidifier.jsq5

### ISSUE THREAD

**Issue by kamilnuriev** [al-one/hass-xiaomi-miot#383]
[deerma.humidifier.jsq5](https://home.miot-spec.com/s/deerma.humidifier.jsq5)
In version v0.5.0, the attribute humidifier.fault (0 - No Faults; 1 - Insufficient Water; 2 - Water Separation) does not work correctly.

In version v0.4.17 everything works correctly.

**Comment by al-one** [comment]
Show me the [state attributes](https://my.home-assistant.io/redirect/developer_states).

**Comment by al-one** [comment]
Fixed in https://github.com/al-one/hass-xiaomi-miot/commit/431b6344f9a4c4fb3d99a942bd1eb743c2a35afe , upgrade to master branch and try.
