### ISSUE TITLE
Stream camera camera.chuangmi ipc013d not working, mi 360 camera

### ISSUE THREAD

**Issue by yevon** [al-one/hass-xiaomi-miot#385]
The stream for this camera is not working.

![image](https://user-images.githubusercontent.com/121157/149673788-d7dd3498-4d0b-48dc-a82d-e316544444fc.png)

Find attached camera properties:

access_token: XXXX
brand: chuangmi
model: [chuangmi.camera.ipc013d](https://home.miot-spec.com/s/chuangmi.camera.ipc013d)
lan_ip: XXXX
mac_address: XXXX
entity_class: MiotCameraEntity
home_room: Casa Comedor
miot_type: urn:miot-spec-v2:device:camera:0000A01C:chuangmi-ipc013d:1
camera_control.on: true
camera_control.image_rollover: 0
camera_control.night_shot: 0
camera_control.time_watermark: true
camera_control.wdr_mode: true
glimmer_full_color-2-6: true
camera_control.recording_mode: 3
camera_control.motion_tracking: false
state_updater: cloud
sub_entities: camera_control.on
entity_picture: /api/camera_proxy/camera.chuangmi_ipc013d_fe26_camera_control?token=XXXX
friendly_name: Cámara comedor Camera Control
supported_features: 1

**Comment by anti-spy** [comment]
I am having the same problem.

**Comment by yevon** [comment]
This is a very good camera It would be nice to have it working.

**Comment by al-one** [comment]
This camera is not supported.
