### ISSUE TITLE
大神能支持一下小寻手表吗

### ISSUE THREAD

**Issue by ilongjiang** [al-one/hass-xiaomi-miot#386]
[xiaoxun.watch.sw306](https://home.miot-spec.com/s/xiaoxun.watch.sw306)

**Comment by al-one** [comment]
https://home.miot-spec.com/spec/xiaoxun.watch.sw306
这款手表由于位定义任何[miot-spec](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:watch:0000A07C:xiaoxun-sw306:1)服务(`Device Information`除外)，因此无法支持。

**Comment by ilongjiang** [comment]
明白了。谢谢

**Comment by al-one** [comment]
请更新到master分支后观察此手表是否可用。
