### ISSUE TITLE
deerma.humidifier.jsq5   v0.5  no feedback

### ISSUE THREAD

**Issue by Blacksli** [al-one/hass-xiaomi-miot#387]
Good afternoon.
deerma.humidifier.jsq5
After updating to v0.5 when turning on the humidifier, turning it off, changing the mode through mihome or through the voice assistant, the change is not updated in the Home Assistant.
Management from HA is correct. And there is no return answer.

v0.4.17 - works correctly

**Comment by al-one** [comment]
Fixed in https://github.com/al-one/hass-xiaomi-miot/commit/431b6344f9a4c4fb3d99a942bd1eb743c2a35afe , upgrade to master branch and try.
