### ISSUE TITLE
最新版本更新后雷士灯无法本地接入，灰色了

### ISSUE THREAD

**Issue by xztxy** [al-one/hass-xiaomi-miot#39]
最新版本更新后雷士灯无法本地接入，灰色了
![864C415F-DD02-46BD-9011-911362744883](https://user-images.githubusercontent.com/31698398/111964910-17dd4400-8b30-11eb-990f-301f6944d5e9.png)

**Comment by al-one** [comment]
该设备在本插件之前的版本是否正常？
另外请查看[日志](https://my.home-assistant.io/redirect/logs)中是都有`Warming`和`Error`相关日志。

**Comment by xztxy** [comment]
> 该设备在本插件之前的版本是否正常？
> 另外请查看[日志](https://my.home-assistant.io/redirect/logs)中是都有`Warming`和`Error`相关日志。

之前都是正常的，今天看插件有更新就更新了，结果发现灰色。无法连接，后面改了云端发现可以了。是不支持云端了吗？。~
2021-03-22 17:17:39 INFO (MainThread) [custom_components.xiaomi_miot] Initializing with host 192.168.15.140 (客厅灯 light), miot mapping: {'default': {'siid': 4, 'piid': 1}, 'default.user_save': {'siid': 4, 'piid': 2}, 'scens.on_off': {'siid': 3, 'piid': 1}, 'scens.brightness_add': {'siid': 3, 'piid': 2}, 'scens.brightness_dec': {'siid': 3, 'piid': 3}, 'scens.brightness_switch': {'siid': 3, 'piid': 4}, 'scens.on_brightness_switch': {'siid': 3, 'piid': 5}, 'scens.color_temperatureadd': {'siid': 3, 'piid': 6}, 'scens.color_temperaturedec': {'siid': 3, 'piid': 7}, 'scens.color_temp_switch': {'siid': 3, 'piid': 8}, 'scens.on_or_colortemp': {'siid': 3, 'piid': 9}, 'light.on': {'siid': 2, 'piid': 1}, 'light.brightness': {'siid': 2, 'piid': 2}, 'light.color_temperature': {'siid': 2, 'piid': 3}}
2021-03-22 17:17:44 ERROR (MainThread) [custom_components.xiaomi_miot] Got MiioException while fetching the state for 客厅灯 light: Unable to discover the device 192.168.15.140
2021-03-22 17:17:45 WARNING (MainThread) [custom_components.xiaomi_miot_raw] New state (None) of 热水器 doesn't match expected values: True/False
2021-03-22 17:17:46 WARNING (MainThread) [homeassistant.components.light] Setup of light platform xiaomi_miot is taking over 10 seconds.
2021-03-22 17:17:46 ERROR (MainThread) [custom_components.xiaomi_miot] Got MiioException while fetching the state for 客厅灯 light: Unable to discover the device 192.168.15.140

**Comment by xztxy** [comment]
> > 该设备在本插件之前的版本是否正常？
> > 另外请查看[日志](https://my.home-assistant.io/redirect/logs)中是都有`Warming`和`Error`相关日志。
> 
> 之前都是正常的，今天看插件有更新就更新了，结果发现灰色。无法连接，后面改了云端发现可以了。是不支持云端了吗？。~
> 2021-03-22 17:17:39 INFO (MainThread) [custom_components.xiaomi_miot] Initializing with host 192.168.15.140 (客厅灯 light), miot mapping: {'default': {'siid': 4, 'piid': 1}, 'default.user_save': {'siid': 4, 'piid': 2}, 'scens.on_off': {'siid': 3, 'piid': 1}, 'scens.brightness_add': {'siid': 3, 'piid': 2}, 'scens.brightness_dec': {'siid': 3, 'piid': 3}, 'scens.brightness_switch': {'siid': 3, 'piid': 4}, 'scens.on_brightness_switch': {'siid': 3, 'piid': 5}, 'scens.color_temperatureadd': {'siid': 3, 'piid': 6}, 'scens.color_temperaturedec': {'siid': 3, 'piid': 7}, 'scens.color_temp_switch': {'siid': 3, 'piid': 8}, 'scens.on_or_colortemp': {'siid': 3, 'piid': 9}, 'light.on': {'siid': 2, 'piid': 1}, 'light.brightness': {'siid': 2, 'piid': 2}, 'light.color_temperature': {'siid': 2, 'piid': 3}}
> 2021-03-22 17:17:44 ERROR (MainThread) [custom_components.xiaomi_miot] Got MiioException while fetching the state for 客厅灯 light: Unable to discover the device 192.168.15.140
> 2021-03-22 17:17:45 WARNING (MainThread) [custom_components.xiaomi_miot_raw] New state (None) of 热水器 doesn't match expected values: True/False
> 2021-03-22 17:17:46 WARNING (MainThread) [homeassistant.components.light] Setup of light platform xiaomi_miot is taking over 10 seconds.
> 2021-03-22 17:17:46 ERROR (MainThread) [custom_components.xiaomi_miot] Got MiioException while fetching the state for 客厅灯 light: Unable to discover the device 192.168.15.140

另外一个作者的插件也试了，同样是不支持云端了。

**Comment by al-one** [comment]
`Unable to discover the device 192.168.15.140`
你的灯貌似局域网不通，建议检查下网络。

**Comment by xztxy** [comment]
> > 该设备在本插件之前的版本是否正常？
> > 另外请查看[日志](https://my.home-assistant.io/redirect/logs)中是都有`Warming`和`Error`相关日志。
> 
> 之前都是正常的，今天看插件有更新就更新了，结果发现灰色。无法连接，后面改了云端发现可以了。是不支持云端了吗？。~
> 2021-03-22 17:17:39 INFO (MainThread) [custom_components.xiaomi_miot] Initializing with host 192.168.15.140 (客厅灯 light), miot mapping: {'default': {'siid': 4, 'piid': 1}, 'default.user_save': {'siid': 4, 'piid': 2}, 'scens.on_off': {'siid': 3, 'piid': 1}, 'scens.brightness_add': {'siid': 3, 'piid': 2}, 'scens.brightness_dec': {'siid': 3, 'piid': 3}, 'scens.brightness_switch': {'siid': 3, 'piid': 4}, 'scens.on_brightness_switch': {'siid': 3, 'piid': 5}, 'scens.color_temperatureadd': {'siid': 3, 'piid': 6}, 'scens.color_temperaturedec': {'siid': 3, 'piid': 7}, 'scens.color_temp_switch': {'siid': 3, 'piid': 8}, 'scens.on_or_colortemp': {'siid': 3, 'piid': 9}, 'light.on': {'siid': 2, 'piid': 1}, 'light.brightness': {'siid': 2, 'piid': 2}, 'light.color_temperature': {'siid': 2, 'piid': 3}}
> 2021-03-22 17:17:44 ERROR (MainThread) [custom_components.xiaomi_miot] Got MiioException while fetching the state for 客厅灯 light: Unable to discover the device 192.168.15.140
> 2021-03-22 17:17:45 WARNING (MainThread) [custom_components.xiaomi_miot_raw] New state (None) of 热水器 doesn't match expected values: True/False
> 2021-03-22 17:17:46 WARNING (MainThread) [homeassistant.components.light] Setup of light platform xiaomi_miot is taking over 10 seconds.
> 2021-03-22 17:17:46 ERROR (MainThread) [custom_components.xiaomi_miot] Got MiioException while fetching the state for 客厅灯 light: Unable to discover the device 192.168.15.140



> `Unable to discover the device 192.168.15.140`
> 你的灯貌似局域网不通，建议检查下网络。

![image](https://user-images.githubusercontent.com/31698398/111969601-63462100-8b35-11eb-813e-14f894aabb48.png)
刚刚通过我之前备份的还原试了下。发现是正常的，可以证明应该不是局域网的问题。

**Comment by al-one** [comment]
开发者工具 > [状态](https://my.home-assistant.io/redirect/developer_states)
获取该设备的状态属性看看。

**Comment by xztxy** [comment]
> 开发者工具 > [状态](https://my.home-assistant.io/redirect/developer_states)
> 获取该设备的状态属性看看。

![BECFEBBB-4A79-4FD1-BA25-095EB7E43006](https://user-images.githubusercontent.com/31698398/111972463-75758e80-8b38-11eb-8fc3-19511ddcea89.png)

**Comment by al-one** [comment]
我觉得你可以手动安装下最新版本试试。
