### ISSUE TITLE
米家的地暖和空调二合一温控器以后能支持本地接入吗？

### ISSUE THREAD

**Issue by cuihaijun** [al-one/hass-xiaomi-miot#398]
我有一款米家的地暖和空调二合一温控器，型号[fawad.airrtc.fwd20011](https://home.miot-spec.com/s/fawad.airrtc.fwd20011)，这个能本地接入吗，有需要我做什么吗？

**Comment by al-one** [comment]
https://github.com/al-one/hass-xiaomi-miot/blob/3daaaeb67d45bbf95a99c22772922b6426f85ca8/custom_components/xiaomi_miot/core/miot_local_devices.py#L85

该设备支持本地模式接入，并已经在[支持本地miot的设备列表](https://github.com/al-one/hass-xiaomi-miot/blob/master/custom_components/xiaomi_miot/core/miot_local_devices.py)中，如果接入后不可用或有什么问题，请提供相关[日志](https://my.home-assistant.io/redirect/logs)。

**Comment by cuihaijun** [comment]
> https://github.com/al-one/hass-xiaomi-miot/blob/3daaaeb67d45bbf95a99c22772922b6426f85ca8/custom_components/xiaomi_miot/core/miot_local_devices.py#L85
> 
> 该设备支持本地模式接入，并已经在[支持本地miot的设备列表](https://github.com/al-one/hass-xiaomi-miot/blob/master/custom_components/xiaomi_miot/core/miot_local_devices.py)中，如果接入后不可用或有什么问题，请提供相关[日志](https://my.home-assistant.io/redirect/logs)。

非常抱歉，我搞错了，地暖和空调二合一温控器型号fawad.airrtc.20011

**Comment by cuihaijun** [comment]
![Uploading Screenshot_20220121_150950_com.vmos.pro.jpg…]()

**Comment by cuihaijun** [comment]
![Screenshot_20220121_150950_com vmos pro](https://user-images.githubusercontent.com/10826652/150482514-35eed191-7117-44fb-bf1a-020bd18a8e23.jpg)

**Comment by al-one** [comment]
[fawad.airrtc.fwd20011](https://home.miot-spec.com/s/fawad.airrtc.fwd20011) 这款吗？

**Comment by cuihaijun** [comment]
是的是的，要我提供什么帮助吗，我有一个这样的温控制

**Comment by cuihaijun** [comment]
> [fawad.airrtc.fwd20011](https://home.miot-spec.com/s/fawad.airrtc.fwd20011) 这款吗？

是的是的，要我提供什么帮助吗，我有一个这样的温控制

**Comment by al-one** [comment]
请更新到master分支后尝试。

**Comment by cuihaijun** [comment]
此错误来自自定义集成。


Logger: custom_components.xiaomi_miot.climate
Source: custom_components/xiaomi_miot/__init__.py:1199
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 19:25:50 (11 occurrences)
Last logged: 19:30:54


空调地暖 Air Conditioner: Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'air_conditioner.on': {'siid': 2, 'piid': 1}, 'air_conditioner.mode': {'siid': 2, 'piid': 2}, 'target_temperature-2-3': {'siid': 2, 'piid': 3}}, max_properties: 7/3
空调地暖 Air Conditioner: Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'air_conditioner.on': {'siid': 2, 'piid': 1}, 'air_conditioner.mode': {'siid': 2, 'piid': 2}, 'target_temperature-2-3': {'siid': 2, 'piid': 3}, 'environment.temperature': {'siid': 4, 'piid': 1}, 'fan_control.fan_level': {'siid': 3, 'piid': 1}}, max_properties: 8/5

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月21日(周五) 下午4:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [al-one/hass-xiaomi-miot] 米家的地暖和空调二合一温控器以后能支持本地接入吗？ (Issue #398)




 
请更新到master分支后尝试。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by al-one** [comment]
请再次更新master分支并尝试。

**Comment by cuihaijun** [comment]
1.能开机，通风，制冷，制热切换，但这些功能之间切换速度很慢。
2.关不了机，会出现不可用状态。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月23日(周日) 凌晨0:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [al-one/hass-xiaomi-miot] 米家的地暖和空调二合一温控器以后能支持本地接入吗？ (Issue #398)




 
请再次更新master分支并尝试。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by al-one** [comment]
切换速度很慢什么意思？通过插件切换模式后要等几秒设备才有反应？
执行关机操作后查看有没有新产生的报错日志。

**Comment by cuihaijun** [comment]
就是云端对接在HA按功能键时机器马上有反应，本地对接在HA按键时没有立刻变化，要等1~2秒才能在HA显示操作成功。本地接入在HA中不能关机，因为按关机功能键没有反应。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月23日(周日) 下午2:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [al-one/hass-xiaomi-miot] 米家的地暖和空调二合一温控器以后能支持本地接入吗？ (Issue #398)




 
切换速度很慢什么意思？通过插件切换模式后要等几秒设备才有反应？
 执行关机操作后查看有没有新产生的报错日志。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by al-one** [comment]
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: climate.fawad_fwd20011_entity_id
  method: set_work_mode
  params:
    - 3
  throw: true
```

在开发者工具中执行该服务，看看有没有延迟。

另外，请提供关闭设备后的报错日志。

**Comment by cuihaijun** [comment]
我测试在HA中不能关机，是在制热、制冷、送风这几个模式切换时会出现错误，导致HA中显示改设备的不可用。
至于延时问题，我一边在HA中操作制热、制冷、送风切换一边看温控制设备，在温控器设备中没延时问题，只是HA显示中要等2秒左右才变化不同的工作模式。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月24日(周一) 凌晨0:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [al-one/hass-xiaomi-miot] 米家的地暖和空调二合一温控器以后能支持本地接入吗？ (Issue #398)




 service: xiaomi_miot.send_command data:   entity_id: climate.fawad_fwd20011_entity_id   method: set_work_mode   params:     - 3   throw: true
 
在开发者工具中执行该服务，看看有没有延迟。
 
另外，请提供关闭设备后的报错日志。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by al-one** [comment]
日志？

**Comment by cuihaijun** [comment]
我附件中有日志文件，我再发一次



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月24日(周一) 凌晨1:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [al-one/hass-xiaomi-miot] 米家的地暖和空调二合一温控器以后能支持本地接入吗？ (Issue #398)




 
日志？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by al-one** [comment]
请问现在能用了吗？

**Comment by cuihaijun** [comment]
https://user-images.githubusercontent.com/10826652/154745434-1d5cf9fe-9b5e-4508-aa5f-14150a0c41d8.mp4

**Comment by al-one** [comment]
请将此设备通过米家共享给账号：`143050915`

**Comment by cuihaijun** [comment]
已共享了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月21日(周一) 中午12:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [al-one/hass-xiaomi-miot] 米家的地暖和空调二合一温控器以后能支持本地接入吗？ (Issue #398)




 
请将此设备通过米家共享给账号：143050915
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by al-one** [comment]
再次更新master试下。

**Comment by cuihaijun** [comment]
可以了，现在关机不会崩溃了，谢谢了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月21日(周一) 中午1:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [al-one/hass-xiaomi-miot] 米家的地暖和空调二合一温控器以后能支持本地接入吗？ (Issue #398)




 
再次更新master试下。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
