### ISSUE TITLE
mijia.vacuum.v2/ xiaomi mijia g1

### ISSUE THREAD

**Issue by bodi007pl** [al-one/hass-xiaomi-miot#40]
return to base does not work in Mi Robot Vacuum-Mop Essential G1 from other forum commands for Vacuum:
Start cleanup "method":"action","params":{"did":"X","siid":2,"aiid":1}
Pause cleanup "method":"action","params":{"did":"X","siid":2,"aiid":2}
Charge "method":"action","params":{"did":"X","siid":13,"aiid":1}

**Comment by al-one** [comment]
You can try last commit: https://github.com/al-one/hass-xiaomi-miot/commit/2aa3f43ddd1f221d0aa56b7c92f32f8ce76acee9 of [master](https://github.com/al-one/hass-xiaomi-miot/tree/master).

**Comment by bodi007pl** [comment]
now no return to base button

**Comment by bodi007pl** [comment]
the vacuum cleaner entity status is unknown but the additional vacuum.status attribute changes between from 1 to 6 1 = "Idle", 2= "Sweeping", 3= "Paused " 4="Error 5="Charging " 6="go charging"

**Comment by al-one** [comment]
Update and try again.
As for the `unknown` state, you need to provide the [entity state attributes](https://my.home-assistant.io/redirect/developer_states).

**Comment by bodi007pl** [comment]
thank you i'll check when i get home.

As for the `unknown`

entity: vacuum.vacuumname_robot_cleaner
State:  unknown 
Attributes:
fan_speed_list:
  - Auto-clean
  - Spot-clean
  - Wallflow-clean
battery_level: 100
battery_icon: 'mdi:battery'
fan_speed: Auto-clean
model: mijia.vacuum.v2
lan_ip: 192.168.XX.XX
mac_address: 'XX:YY:ZZ:XX:YY:ZZ'
firmware_version: 2.0.8
hardware_version: esp32
entity_class: MiotVacuumEntity
other_status.mop_status: 0
language: 8
language.not_disturb_switch: false
clean_record.clean_area: 0
clean_record.clean_time: 0
clean_record.total_clean_area: 0
clean_record.total_clean_time: 0
clean_record.total_clean_count: 0
remote_control.direction_key.error: -4003
brush_cleaner-15.brush_life_level: 94
brush_cleaner-15.brush_left_time: 8485
brush_cleaner.brush_life_level: 97
brush_cleaner.brush_left_time: 17506
filter.filter_life_level: 94
filter.filter_left_time: 8506
alarm: true
alarm.volume: 100
battery.battery_level: 100
battery.charging_state: 2
vacuum.status: 5
vacuum.fault: 0
vacuum.mode: 1
vacuum.target_water_level: 2
vacuum.fan_level: 1
state_updater: lan
sub_entities:
  - filter-11.filter_life_level-1
  - filter-11.filter_left_time-2
  - battery-3.battery_level-1
  - battery-3.charging_state-2
  - brush_cleaner-14.brush_life_level-1
  - brush_cleaner-14.brush_left_time-2
  - brush_cleaner-15.brush_life_level-1
  - brush_cleaner-15.brush_left_time-2
friendly_name: vaacuum Robot Cleaner
supported_features: 12536

**Comment by bodi007pl** [comment]
> Update and try again

now the button is there, unfortunately it doesn't work, 
Miot action result
 `did: '318979626'
siid: 3
aiid: 3
code: -4003 `
works when send from developer tools > services ... `siid: 13
aiid: 1`

**Comment by al-one** [comment]
Please try again.

**Comment by bodi007pl** [comment]
> Please try again.

Still not working :( 

```
Miot action result:

did: '318979626'
miid: 0
siid: 3
aiid: 1
code: -704040005
exe_time: 0
net_cost: 0
ot_cost: 0
otlocalts: 0
oa_cost: 0
_oa_rpc_cost: 0
```

**Comment by al-one** [comment]
Try again.

**Comment by bodi007pl** [comment]
Hooray! Now it works, thank you!
