### ISSUE TITLE
执行自动化的时候，报错

### ISSUE THREAD

**Issue by neil2017** [al-one/hass-xiaomi-miot#400]
执行自动化的时候，报下面错误，无法执行任务
Stopped because an error was encountered at 2022年1月22日 07:09:48 (runtime: 0.12 seconds)

HTTPSConnectionPool(host='api.io.mi.com', port=443): Max retries exceeded with url: /app/miotspec/prop/set (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x67fd7c40>: Failed to establish a new connection: [Errno 101] Network unreachable'))
![1642814135(1)](https://user-images.githubusercontent.com/23653387/150618873-8c020d89-a2b4-4be5-bab8-725c4bdaefeb.jpg)

**Comment by al-one** [comment]
> Failed to establish a new connection: [Errno 101] Network unreachable

出现该报错的原因是插件无法访问米家云端接口，请检查你的HA是否可以正常访问外网。
