### ISSUE TITLE
Adding service descriptions and translations in yaml?

### ISSUE THREAD

**Issue by blakadder** [al-one/hass-xiaomi-miot#405]
I'm trying to fully integrate the viomi.vacuum.v18 in local mode but I'm running into cosmetic issues:

1. Some services have no descriptions. 
Is there a way to populate those descriptions from the yaml or is it necessary to rename every entity manually?

2. Some services have descriptions of names and values in Chinese which aren't translated. 
For now I've been using `translations:` in configuration.yaml like this:

```yaml
  translations:
    # Global dictionary
    '是否重复': 'repeat cleaning'
    '扫地机 dust-collection': 'Empty Dust Bin'
    '1挡': 'Level 1'
    '2挡': 'Level 2'
    '3挡': 'Level 3'
    'Wide Dynamic Range Mode': 'Clean Mode'
    '扫地机 出水量大小': 'Mop Water Volume'
    '扫地机': 'Vacuum'
    'Y字形': 'Y-shaped Mode'
    '弓字形': 'S-shaped Mode'
    '边刷剩余寿命百分比': 'Side Brush Life'
    '主刷剩余寿命百分比': 'Main Brush Life'
 ```

Is there perhaps a more universal way?

**Comment by al-one** [comment]
If you want, you can submit a PR to redefine it's miot-spec (via `extend_miot_specs`).
https://github.com/al-one/hass-xiaomi-miot/commit/a4a991cf1ca9769bebba5bc72bc700b0f293b245#commitcomment-62930948
