### ISSUE TITLE
小米门窗传感器经常无法接收到数据

### ISSUE THREAD

**Issue by socekin** [al-one/hass-xiaomi-miot#408]
通过自动模式+小米账号，将小米传感器2接入到HA，但是经常会出现无法接收到数据，米家APP上的数据正常
isa.magnet.dw2hl
制造商：isa
固件：1.1.1_0045

**Comment by al-one** [comment]
请参考：https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-909031222
