### ISSUE TITLE
cgllc.airm.cgdn1 not getting all measurements

### ISSUE THREAD

**Issue by hsantens** [al-one/hass-xiaomi-miot#409]
Hi

I have added my [cgllc.airm.cgdn1 (Qingping air monitor lite)](https://home.miot-spec.com/spec/cgllc.airm.cgdn1) to HA. First I had to try all connection options:
- host token does not work (same subnet)
- xiaomi cloud acount
  - automatic: only brings up "relative humidity" entity, which has a status "unavailable"
  - local: same result as automatic
  - cloud: 6 entities are added (charging state, battery level, voltage, humidity, temperature)

So in my case, I assume I should use cloud. 
However, CO2, PM2.5 and PM10 measurements are missing.

Any idea on how I could fix this?

Thanks

regards,
Hans

**Comment by al-one** [comment]
Please upgrade to master branch and try again.

**Comment by hsantens** [comment]
Great, it all works fine now! Thank you very much!
