### ISSUE TITLE
米家门锁接入问题

### ISSUE THREAD

**Issue by qiuyuxuan1999** [al-one/hass-xiaomi-miot#41]
先感谢大佬，看到插件0.3.0版本写的增加了对门锁的支持，试了一下接入米家智能门锁，能接入，但一直显示未知。相关截图如下：
![Screenshot_20210323_210415_com android chrome](https://user-images.githubusercontent.com/64347554/112150763-6e737c80-8c1b-11eb-8ef9-ceda02b96da8.jpg)

**Comment by al-one** [comment]
由于此设备协议中的lock服务下没有可以表示状态的属性，且该服务下所有字段均无read读取权限，因此显示未知。
此设备应该只支持剩余电量。

**Comment by qiuyuxuan1999** [comment]
> 由于此设备协议中的lock服务下没有可以表示状态的属性，且该服务下所有字段均无read读取权限，因此显示未知。
> 此设备应该只支持剩余电量。

明白了，感谢大佬，应该是米家服务器不允许读取门锁的信息。
