### ISSUE TITLE
Vacuum device state is unavailable but can send commands

### ISSUE THREAD

**Issue by fokcuk** [al-one/hass-xiaomi-miot#410]
Dont know exactly when it broke, but now my vacuum device no longer reports its state and battery and I can no longer initiate start/stop commands via GUI. But via scripts I can still send commands to start/stop/vacuum room.
Logger does not seem to show any errors. In HA device is just grayed out

**Comment by fhold** [comment]
I had a similar problem, reintegrating it with the option "renew device" fixed my problem.

**Comment by fhold** [comment]
> I had a similar problem, reintegrating it with the option "renew device" fixed my problem.

sorry I must contradict myself. It went unavailable after 2 minutes again. It seems to be linked to the recent update

**Comment by fokcuk** [comment]
I had to create a new integration for the same device. Working ok so far

**Comment by fhold** [comment]
yeah that seems to work, strange

**Comment by al-one** [comment]
What is the model of your vacuum ?

**Comment by fokcuk** [comment]
viomi s9

**Comment by al-one** [comment]
Does this issue still exist in the latest version ?
