### ISSUE TITLE
Pan/PTZ Support?

### ISSUE THREAD

**Issue by Golab** [al-one/hass-xiaomi-miot#412]
Hello I own a [chuangmi.camera.021a04](https://home.miot-spec.com/s/chuangmi.camera.021a04) it works great with your integration, I have one question can you make so your integration supports Pan/PTZ? So I can move my camera up and down and sideways

**Comment by Golab** [comment]
?

**Comment by al-one** [comment]
None of the related services are defined in [miot-spec](https://home.miot-spec.com/spec/chuangmi.camera.021a04), if you can capture the relevant miio commands or cloud api, I'd be happy to support it.

**Comment by maxdobmax** [comment]
> Hello I own a [chuangmi.camera.021a04](https://home.miot-spec.com/s/chuangmi.camera.021a04) it works great with your integration, I have one question can you make so your integration supports Pan/PTZ? So I can move my camera up and down and sideways

I have same chuangmi.camera.021a04 and it works really bad, triggers (such as motion detection) don't work , streaming don't work too. How have you set up this? Thanks
