### ISSUE TITLE
Detected blocking call to sleep inside the event loop

### ISSUE THREAD

**Issue by yyxp1989** [al-one/hass-xiaomi-miot#422]
Logger: homeassistant.util.async_
Source: util/async_.py:144
First occurred: 22:48:31 (4 occurrences)
Last logged: 22:50:01

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom component author for xiaomi_miot doing blocking calls at custom_components/xiaomi_miot/select.py, line 141: time.sleep(0.2)

版本：
Home Assistant 2022.3.0.dev20220205

过年时候升级了HASS，就开始报这个错误了，一天能报上千次，麻烦看看是什么问题，谢谢。

**Comment by al-one** [comment]
请更新到master分支后再观察下。
