### ISSUE TITLE
viomi.waterheater.e1 mistake in logs

### ISSUE THREAD

**Issue by soulthiefer** [al-one/hass-xiaomi-miot#424]
good evening 

[viomi.waterheater.e1](https://home.miot-spec.com/s/viomi.waterheater.e1)
errors started appearing in the server logs again (
Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.xiaomi_miot.water_heater
Source: custom_components/xiaomi_miot/__init__.py:1200
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 07:31:39 (9 occurrences)
Last logged: 22:41:33

Xiaomi_Waterheat Water Heater: Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'water_heater.target_temperature': {'siid': 2, 'piid': 1}, 'water_heater.temperature': {'siid': 2, 'piid': 2}, 'water_heater.status': {'siid': 2, 'piid': 3}, 'water_heater.on': {'siid': 2, 'piid': 4}, 'water_heater.water_level': {'siid': 2, 'piid': 5}, 'water_heater.mode': {'siid': 2, 'piid': 6}}, max_properties: 10/6
Xiaomi_Waterheat Water Heater: Got MiioException while fetching the state: No response from the device, mapping: {'water_heater.target_temperature': {'siid': 2, 'piid': 1}, 'water_heater.temperature': {'siid': 2, 'piid': 2}, 'water_heater.status': {'siid': 2, 'piid': 3}, 'water_heater.on': {'siid': 2, 'piid': 4}, 'water_heater.water_level': {'siid': 2, 'piid': 5}, 'water_heater.mode': {'siid': 2, 'piid': 6}}, max_properties: 10/6
Xiaomi_Waterheat Water Heater: Got MiioException while fetching the state: Unable to discover the device 192.168.31.24, mapping: {'water_heater.target_temperature': {'siid': 2, 'piid': 1}, 'water_heater.temperature': {'siid': 2, 'piid': 2}, 'water_heater.status': {'siid': 2, 'piid': 3}, 'water_heater.on': {'siid': 2, 'piid': 4}, 'water_heater.water_level': {'siid': 2, 'piid': 5}, 'water_heater.mode': {'siid': 2, 'piid': 6}}, max_properties: 10/6

but the server receives data from the device

![image](https://user-images.githubusercontent.com/78509632/152861339-e088f82d-aca2-4c00-b124-b0e576b282c0.png)

there were no mistakes a week ago. I did not change the server configuration and integration settings. how to fix the error so that it does not appear

**Comment by twlodar** [comment]
Hi 
I've got similar errors in my log, device deerma.humidifier.jsq5 and HA also receives data from device 

Logger: custom_components.xiaomi_miot.humidifier
Source: custom_components/xiaomi_miot/__init__.py:1200
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 05:57:07 (2 occurrences)
Last logged: 15:45:39
Humidifier sypialnia Humidifier: Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'humidifier.on': {'siid': 2, 'piid': 1}, 'humidifier.fault': {'siid': 2, 'piid': 2}, 'humidifier.fan_level': {'siid': 2, 'piid': 5}, 'humidifier.target_humidity': {'siid': 2, 'piid': 6}, 'indicator_light.on': {'siid': 6, 'piid': 1}, 'alarm': {'siid': 5, 'piid': 1}, 'environment.relative_humidity': {'siid': 3, 'piid': 1}, 'environment.temperature': {'siid': 3, 'piid': 7}}, max_properties: 4/8

**Comment by profx5015** [comment]
Got the same thing with mr.bond airer:

`Got exception while fetching the state for cover.mr_bond (['dry', 'led', 'motor', 'drytime', 'airer_location']): {'code': -10000, 'message': 'error'} Unable to discover the device 192.168.1.111`

**Comment by al-one** [comment]
@soulthiefer Please try to rebind the device in the Mihome APP.

**Comment by al-one** [comment]
@twlodar @profx5015 Please create a new issue.

**Comment by soulthiefer** [comment]
thank you , the error is gone
