### ISSUE TITLE
hhcc.plantmonitor.v1 don't work

### ISSUE THREAD

**Issue by Nemesis24** [al-one/hass-xiaomi-miot#427]
![Sans titre](https://user-images.githubusercontent.com/25956796/153394099-e843be23-7f43-449f-8406-6ee56d3d16c6.png)
[hhcc.plantmonitor.v1](https://home.miot-spec.com/s/hhcc.plantmonitor.v1)

We don't have Soil Fertility, Illumination, Température and  Battery, Relative humidy is still unknown.

Thanks for this goos job.

**Comment by al-one** [comment]
Show me the [state attributes](https://my.home-assistant.io/redirect/developer_states) of this entity.

**Comment by Nemesis24** [comment]
![Sans titre](https://user-images.githubusercontent.com/25956796/153396354-f54b4a14-976b-48e3-a08b-452f34390921.png)

**Comment by al-one** [comment]
`-704010000 Unknown` This error comes from Xiaomi Cloud and I can't do anything about it.
