### ISSUE TITLE
yeelink.light.lamp4 Got MiioException

### ISSUE THREAD

**Issue by rirofal** [al-one/hass-xiaomi-miot#430]
And again I can't control my desktop light...

```
Mi LED Desk Lamp 1S Light: Got MiioException while fetching the state: Unable to discover the device 192.168.100.173, mapping: {'light.on': {'siid': 2, 'piid': 1}, 'light.brightness': {'siid': 2, 'piid': 2}, 'light.color_temperature': {'siid': 2, 'piid': 3}, 'light.mode': {'siid': 2, 'piid': 4}}, max_properties: 10/4
```

(Using v0.5.2 via HACS)

**Comment by al-one** [comment]
- Please confirm your device IP
- If the subnet divided: https://github.com/al-one/hass-xiaomi-miot/issues/349#issuecomment-1004179460

**Comment by rirofal** [comment]
Single subnet and the IP is correct (static lease in dhcp).

**Comment by rirofal** [comment]
Ehrm... this is strange. Now it works as it should. (and I haven't touch a single thing in the installation)
