### ISSUE TITLE
Get xiaomi message for xxxx failed

### ISSUE THREAD

**Issue by andiukas** [al-one/hass-xiaomi-miot#431]
All time I have this error:

This error originated from a custom integration.

Logger: custom_components.xiaomi_miot.sensor
Source: custom_components/xiaomi_miot/sensor.py:569
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 09:35:06 (193 occurrences)
Last logged: 12:52:38

Get xiaomi message for 1749420506 failed: {'code': 0, 'message': 'ok', 'result': {'messages': None}}

**Comment by al-one** [comment]
Your Mihome APP account has not received any device or system notifications.

**Comment by ALERTua** [comment]
@al-one can you please explain the reason for this message? my log got spammed with this message 24/7
![image](https://user-images.githubusercontent.com/8375129/200652787-add5fb87-cda3-4b0e-91a8-37dd506400b3.png)

**Comment by SergeyPomelov** [comment]
@al-one +1, Why the issue is closed?

**Comment by al-one** [comment]
Try master branch.

**Comment by ALERTua** [comment]
it seems that the error disappeared on the master branch. thank you, @al-one <3

**Comment by SergeyPomelov** [comment]
@al-one In master the particular problem is gone. However, there also yet another warnings spam from miot logs. There's a ton of issues and I don't know Chinese at all. Not sure was it reported or not. According to debug the resource unreachable from different region IPs, so, shouldn't be a rare case, just left it here.

```
Logger: custom_components.xiaomi_miot.core.xiaomi_cloud
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:204
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 13:48:05 (68 occurrences)
Last logged: 16:03:58

Request xiaomi api: v2/message/v2/typelist {} failed, response: None
```

**Comment by al-one** [comment]
You can now disable the Mihome notification entity from the integration options if it doesn't work for you.

![xiaomi miot option](https://user-images.githubusercontent.com/4549099/201006022-4a5aa21a-ae04-4c2c-9e36-668f028f3514.png)
