### ISSUE TITLE
deerma.humidifier.jsq missing features

### ISSUE THREAD

**Issue by njot0** [al-one/hass-xiaomi-miot#434]
I ma trying to use my [humidifier ](https://home.miot-spec.com/spec/deerma.humidifier.jsq) in local mode, but I cannot get it to work. In cloud mode it works fine, but in local mode I am getting error 4004.
This is what I get for state in cloud mode:
```
min_humidity: null
max_humidity: null
model: deerma.humidifier.jsq
lan_ip: 192.168.0.214
mac_address: **:**:**:**:**:**
entity_class: MiotHumidifierEntity
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq:1
humidifier.on: true
state_updater: cloud
exclude_miot_services:
  - custom
alarm: true
indicator_light.on: true
environment.relative_humidity: 41
environment.temperature: 20
sub_entities:
  - environment-3.relative_humidity-1
  - environment-3.temperature-2
  - indicator_light-4
device_class: humidifier
friendly_name: Mi Smart Antibacterial Humidifier Humidifier
supported_features: 0
```
This is what I get for state in local mode:
```
min_humidity: null
max_humidity: null
model: deerma.humidifier.jsq
lan_ip: 192.168.0.214
mac_address: **:**:**:**:**:**
entity_class: MiotHumidifierEntity
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq:1
humidifier.on.error: '-4004 Other internal errors'
state_updater: lan
exclude_miot_services:
  - custom
alarm.error: '-4004 Other internal errors'
indicator_light.on.error: '-4004 Other internal errors'
environment.relative_humidity.error: '-4004 Other internal errors'
environment.temperature.error: '-4004 Other internal errors'
device_class: humidifier
friendly_name: HumidifierMiotAuto Humidifier
supported_features: 0
```
Can you help to make this work?
Thanks # #

**Comment by njot0** [comment]
I can see that there was an [update ](https://github.com/al-one/hass-xiaomi-miot/commit/3a409368131801dfea0c343997bcb384c05ae09e) just today, done at the same time as I opened this.
So i changed to master - and voila, it works in local mode. Thanks a lot.
This is how it looks now (state in local mode):
```
min_humidity: null
max_humidity: null
model: deerma.humidifier.jsq
lan_ip: 192.168.0.214
mac_address: 5C:E5:0C:18:21:DC
entity_class: MiotHumidifierEntity
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq:1
humidifier.on: true
state_updater: lan
exclude_miot_services:
  - custom
alarm: true
indicator_light.on: true
environment.relative_humidity: 59
environment.temperature: 22
sub_entities:
  - environment-3.relative_humidity-1
  - environment-3.temperature-2
  - indicator_light-4
device_class: humidifier
friendly_name: Vlazitelj Humidifier
supported_features: 0
```
However, I can see that humidifier with this integration in local mode does not have all functions that are available in HA using [Xiaomi Miio](https://www.home-assistant.io/integrations/xiaomi_miio) integration. Namely, device in Xiaomi Miio is showing modes (I can select the humidifier mode in HA), there is buzzer switch and there are binary sensors for Water tank (connected or not) and for Water Tank empty.
Is there any change this could be added?

Thanx.

**Comment by njot0** [comment]
Thanks for looking into this.
I just tried new master branch, this is the state:
```
min_humidity: 0
max_humidity: 100
humidity: 0
model: deerma.humidifier.jsq
lan_ip: 192.168.0.214
mac_address: *
entity_class: MiotHumidifierEntity
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq:1
humidifier.on: true
humidifier.target_humidity: 0
state_updater: lan
exclude_miot_services:
  - custom
alarm: true
indicator_light.on: true
environment.relative_humidity: 53
environment.temperature: 20
sub_entities:
  - environment-3.relative_humidity-1
  - environment-3.temperature-2
  - indicator_light-4
device_class: humidifier
friendly_name: Vlazitelj Humidifier
supported_features: 0
```
I can see new attributes in state, and light entity now follows actual situation (whether it is on or not). But I still cannot see or change operation mode (low/medium/high/target humidity), switch buzzer or LED, or have an alarm for tank full or disconnected.
What changes should I see?
Anything you could recommend to try?

**Comment by njot0** [comment]
I just tried, here is the state now:
```
min_humidity: 1
max_humidity: 99
humidity: 0
model: deerma.humidifier.jsq
lan_ip: 192.168.0.214
mac_address: **
entity_class: MiotHumidifierEntity
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq:1
humidifier.on: false
humidifier.target_humidity: 0
humidifier.water_status: true
humidifier.tank_status: true
state_updater: lan
exclude_miot_services:
  - custom
alarm: true
indicator_light.on: true
environment.relative_humidity: 57
environment.temperature: 20
sub_entities:
  - environment-3.relative_humidity-1
  - environment-3.temperature-2
  - indicator_light-4
device_class: humidifier
friendly_name: Vlazitelj Humidifier
supported_features: 0
```
Now the light entity actually controls the LED.
And there are new attributes for water and tank (humidifier.water_status and humidifier.tank_status) and these change (I tried by removing the tank). But I don't have new sensor entities for these, should I create them somehow?
And there is still no operation mode (low/medium/high/target humidity) - should it be here per your latest changes?

Thanks again for looking into this.

**Comment by al-one** [comment]
> But I don't have new sensor entities for these, should I create them somehow ?

```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    deerma.humidifier.jsq:
      binary_sensor_properties: water_status,tank_status
```

**Comment by al-one** [comment]
This device has no mode options, only the target humidity can be set.
Are there any error/warning logs after you set the target humidity ?

**Comment by njot0** [comment]
> This device has no mode options, only the target humidity can be set.
> Are there any error/warning logs after you set the target humidity ?

How should I test that?
I tried running service xiaomi_miot.set_property for my humidifier's entity (humidifier.deerma_jsq_21dc_humidifier) , field "humidity", set value to few values. Then I get this in Logs:
```
This error originated from a custom integration.

Logger: custom_components.xiaomi_miot.humidifier
Source: custom_components/xiaomi_miot/__init__.py:1577 
Integration: Xiaomi Miot Auto (documentation, issues) 
First occurred: 23:48:55 (6 occurrences) 
Last logged: 23:50:15

Vlazitelj(deerma.humidifier.jsq): Set miot property humidity(40) failed: property not found
Vlazitelj(deerma.humidifier.jsq): Set miot property humidity(30) failed: property not found
Vlazitelj(deerma.humidifier.jsq): Set miot property humidity(35) failed: property not found
```
Then I tried running service xiaomi_miot.set_property for my humidifier's entity (humidifier.deerma_jsq_21dc_humidifier) , field" humidifier.target_humidity", set value to 20. I can hear a beep from the device, there is no warning in the Logs, and this is the state:
```
min_humidity: 1
max_humidity: 99
humidity: 20
model: deerma.humidifier.jsq
lan_ip: 192.168.0.214
mac_address: **
entity_class: MiotHumidifierEntity
miot_type: urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq:1
humidifier.on: true
humidifier.target_humidity: 20
humidifier.water_status: true
humidifier.tank_status: true
state_updater: lan
exclude_miot_services:
  - custom
alarm: true
indicator_light.on: true
environment.relative_humidity: 65
environment.temperature: 21
sub_entities:
  - humidifier-2.water_status-102
  - humidifier-2.tank_status-103
  - environment-3.relative_humidity-1
  - environment-3.temperature-2
  - indicator_light-4
humidifier-2.target_humidity: 20
device_class: humidifier
friendly_name: Vlazitelj Humidifier
supported_features: 0
binary_sensor_properties: water_status,tank_status
```
Attributes humidity and humidifier.target_humidity now are set to this value of 20, and there is new attribute humidifier-2.target_humidity: 20. And if I set the operation mode using button on the device to "humidity" then device will work or stop, based on current humidity. So control would work like this (control the speed of operation by changing target humidity), but the device has to be in humidity mode, not low/medium/high. So it would be still best if somehow this could be made available (control of operation mode.

**Comment by njot0** [comment]
> > But I don't have new sensor entities for these, should I create them somehow ?
> 
> ```yaml
> # configuration.yaml
> xiaomi_miot:
>   device_customizes:
>     deerma.humidifier.jsq:
>       binary_sensor_properties: water_status,tank_status
> ```

Unfortunately this does not have any effect.
But I added this into customize.yaml:
```
humidifier.deerma_jsq_21dc_humidifier:
  binary_sensor_properties: water_status,tank_status
```
And then I got new entities binary_sensor.deerma_jsq_21dc_water_status and binary_sensor.deerma_jsq_21dc_tank_status. And they work, follow attributes. But both these entities had the same name and no same icon. Is there any way to customize these from the YAML?

**Comment by njot0** [comment]
> Unfortunately this does not have any effect. But I added this into customize.yaml:
> 
> ```
> humidifier.deerma_jsq_21dc_humidifier:
>   binary_sensor_properties: water_status,tank_status
> ```
> 
> And then I got new entities binary_sensor.deerma_jsq_21dc_water_status and binary_sensor.deerma_jsq_21dc_tank_status. And they work, follow attributes. But both these entities had the same name and no same icon. Is there any way to customize these from the YAML?

Got this to work by modifying customize.yaml, please disregard the comment above.

**Comment by al-one** [comment]
Are there any other issues with the device ?

**Comment by njot0** [comment]
There is the issue with changing the operation mode of the device. I can set target humidity which then effects device's operation when it is in Humidity mode. But can anything be done to implement ability to change operation mode? If someone physically presses the button on the device , thus changing the mode, then I cannot change it back by using HA.
Maybe to try something like [this](https://github.com/al-one/hass-xiaomi-miot/issues/242#issuecomment-989453399)?

**Comment by al-one** [comment]
Try master branch again.

**Comment by njot0** [comment]
Tested and it is functioning properly - great work! :-)
There is one more small thing: integration allows for target humidity to be set in range from 1 to 99. But if you set anything lower than 40, it does not have any effect. E.g. if current relative humidity is 45 and you set 35 as target humidity in ConstHumidity mode, device will not stop working. But if you set it to 40, it will stop the fan.
Thus the solution is to set min_humidity to 40.
I tried by changing row 79 in custom_components/xiaomi_miot/core/miot_specs_extend.json , change values from [1, 99, 1] to [40,  99, 1] - and it works. Therefor, can you please integrate this into next release?

**Comment by al-one** [comment]
It's ok.

**Comment by njot0** [comment]
Tested latest release - it works fine.
Thank you for the great work!
