### ISSUE TITLE
PTX智能开关mesh添加失败

### ISSUE THREAD

**Issue by WalterDSU** [al-one/hass-xiaomi-miot#438]
这两个设备无法添加成功.
![1645064784](https://user-images.githubusercontent.com/91654066/154392835-0177a578-9c65-4571-b436-7ff2fbfb3599.jpg)
![1645064861(1)](https://user-images.githubusercontent.com/91654066/154392893-30359326-a85e-412c-8269-1ec657b8af90.jpg)

**Comment by al-one** [comment]
请检查你的dns服务器，建议将`8.8.8.8`等海外dns换成国内公共dns如阿里：`223.5.5.5`

**Comment by WalterDSU** [comment]
我应该用的是114和电信自动推荐.

**Comment by al-one** [comment]
如果是群晖，请检查下群晖设置中的dns配置。

**Comment by al-one** [comment]
该问题解决了吗？
