### ISSUE TITLE
Is there a way propagate Dehumidifier entity type to Google Assistant through HASS? Or to set nwt_wdh318efw1_2aa8_dehumidifier humidifier.ATTR_MIN_HUMIDITY to 40.0

### ISSUE THREAD

**Issue by hermanmak** [al-one/hass-xiaomi-miot#444]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/helpers.py", line 593, in sync_serialize
    device["attributes"].update(trt.sync_attributes())
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/trait.py", line 1143, in sync_attributes
    float(self.state.attributes[humidifier.ATTR_MIN_HUMIDITY])
TypeError: float() argument must be a string or a number, not 'NoneType'

**Comment by al-one** [comment]
What is the model of your dehumidifier ?

**Comment by hermanmak** [comment]
nwt_wdh318efw1_2aa8_dehumidifier

Thanks!

**Comment by hermanmak** [comment]
assert cap.parameters() == {
        'instance': 'humidity',
        'random_access': True,
        'range': {
            'max': 60,
            'min': 40,
            'precision': 10
        },
        'unit': 'unit.percent',
    }
