### ISSUE TITLE
Audio support for camera - isa.camera.hlc6

### ISSUE THREAD

**Issue by NikDevx** [al-one/hass-xiaomi-miot#45]
Is it possible to add 2 way audio or just audio support for this camera isa.camera.hlc6?

**Comment by al-one** [comment]
What is your HA core version?

**Comment by NikDevx** [comment]
> What is your HA core version?

core-2021.3.4

**Comment by al-one** [comment]
Get the `stream_address` from state attributes of this entity, and then use VLC to play whether there is audio.

**Comment by NikDevx** [comment]
No audio

**Comment by al-one** [comment]
So, there is also no audio in HA.

**Comment by NikDevx** [comment]
Is there a way to get audio from a stream?

**Comment by al-one** [comment]
I don't know.
