### ISSUE TITLE
ffmpeg错误

### ISSUE THREAD

**Issue by lyl12321** [al-one/hass-xiaomi-miot#450]
第一次入坑hass，还不太懂，手动安装插件后报 Unable to set up dependencies of xiaomi_miot. Setup failed for dependencies: ffmpeg，但是已经安装了ffmpeg，
root@OpenWrt:~# whereis ffmpeg
ffmpeg: /usr/bin/ffmpeg

系统是openwrt，是我还缺点什么依赖，还是哪里没有配置好？官方文档中的ffmpeg参考配置了，配置上去就没法启动hass，求给个解决思路

报错完整log
Logger: homeassistant.setup
Source: setup.py:135
First occurred: 02:07:17 (1 occurrences)
Last logged: 02:07:17

Unable to set up dependencies of xiaomi_miot. Setup failed for dependencies: ffmpeg

**Comment by xcstatus** [comment]
你好，在使用时也遇到了这个问题。 请问compent具体时指什么呢？
