### ISSUE TITLE
YeeLight Ceiling10 Ambilight

### ISSUE THREAD

**Issue by crgnclsn** [al-one/hass-xiaomi-miot#451]
Hi,

I've been enjoying this integration however I had a question. I have a Ceiling Yeelight that has both a main light and an ambient light (https://home.miot-spec.com/s/yeelink.light.ceiling10). 

Model: yeelink.light.ceiling10
Entity class: MiotLightEntity
Miot type: urn:miot-spec-v2:device:light:0000A001:yeelink-ceiling10:1

In home assistant I can only see and control the single main light and not the ambient light. Is there anyway to add access to the ambient light? Even if it is via [xiaomi_miot.send_command] or custom yamls.

Many thanks!

**Comment by shift-del1** [comment]
Did you try the official Yeelight integration? I have 2 yeelink.light.ceiling20, and they work perfectly:

![Screenshot_2022-02-26-21-49-47-769_io homeassistant companion android](https://user-images.githubusercontent.com/63366470/155858678-77cc16b4-e815-42a3-ac70-1ea6892c3010.jpg)

**Comment by al-one** [comment]
Supported in v0.6.11.
