### ISSUE TITLE
FOWAD 温控器不能关机

### ISSUE THREAD

**Issue by ABUAIJUTIE** [al-one/hass-xiaomi-miot#452]
关机日志如下

> 新风机(fawad.airrtc.fwd20011): Set miot property {'did': '4110xxxxx', 'siid': 2, 'piid': 1, 'value': False} failed: {'code': -9999, 'message': 'user ack timeout'}

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/398#issuecomment-1045018037

请更新到master分支。
