### ISSUE TITLE
app_segment_clean([13]) command not recive response

### ISSUE THREAD

**Issue by GrayFarkas** [al-one/hass-xiaomi-miot#453]
Hi All!

I try to made a vacuume integration in my HA. My robot device is viomi.vacuume.v8 so I use this integration because I have some other device which is supported only by this.

I try to use the developer console to send a command to my robot. My command is send.command.app_segment_clean([13]).

When I send this command or with some other room ID I always got this error to my log and the robot never do the cleaning:
`Ez a hiba egy egyéni integrációból lett származtatva.

Logger: custom_components.xiaomi_miot.vacuum
Source: custom_components/xiaomi_miot/__init__.py:813
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 21:34:07 (3 occurrences)
Last logged: 21:50:41

Negró(viomi.vacuum.v8): Send miio command: app_segment_clean([13]) failed: No response from the device
Negró(viomi.vacuum.v8): Send miio command: app_segment_clean([13])(None) failed: No response from the device`

What I do a wrong way?

**Comment by al-one** [comment]
`app_segment_clean` only supports Roborock vacuum, not viomi.
