### ISSUE TITLE
Room cleaning on Mi Robot Vacuum-Mop 2 Pro+

### ISSUE THREAD

**Issue by BernieV1977** [al-one/hass-xiaomi-miot#455]
Hello,
I can't figure out how to make cleaing a single room by using xiaomi_miot.call_action with params.
Without params it works like simple cleaning of all square. With the Mi Home app I can clean a single room.

What is correct way to call xiaomi_miot.call_action with params? On the miot-spec page there is only a start-sweep listed without params.

miot_type: urn:miot-spec-v2:device:vacuum:0000A006:dreame-p2041o:1

Thx in advance

**Comment by al-one** [comment]
Sorry I ignored this issue . . .

You can refer to them:
- https://github.com/al-one/hass-xiaomi-miot/issues/425
- https://github.com/al-one/hass-xiaomi-miot/issues/289#issuecomment-988438475

If you want to know the specific parameters, you can refer to here:
- https://github.com/al-one/hass-xiaomi-miot/issues/114#issuecomment-868721912
