### ISSUE TITLE
Unable to get image and more another error - isa.camera.hlc6

### ISSUE THREAD

**Issue by NikDevx** [al-one/hass-xiaomi-miot#46]
Sometimes getting this error.

```
Logger: homeassistant
Source: components/camera/__init__.py:148
First occurred: 23:28:14 (1 occurrences)
Last logged: 23:28:14

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_cameras.py", line 472, in async_get_snapshot
    await self.hass.components.camera.async_get_image(self.entity_id),
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 148, in async_get_image
    raise HomeAssistantError("Unable to get image")
homeassistant.exceptions.HomeAssistantError: Unable to get image
```

```
Error opening stream https://de08.livestreaming.io.mi.com/hlstranscoder/GCAwYjk4YWRkNWRjMjI0M2U5YmY3ZDBjMDY0NDExZmY4MhgKX191bnVzZWRfXwA_H265transH264/playlist.m3u8
Error opening stream https://de07.livestreaming.io.mi.com/hlstranscoder/GCBlN2M3ZjczZjJmNmU0OWMwODEzZTc5YzA3OGU1MzdlYxgKX191bnVzZWRfXwA_H265transH264/playlist.m3u8
```

**And after 5 minutes it will stop showing the stream. I need to reboot the camera or HA server.**

**Comment by NikDevx** [comment]
I think the camera does not receive a new token after 5 minutes

**Comment by SIM0N-F** [comment]
Hello, i have the same camera and i have another error, in my log I see this error.
`2021-04-06 18:46:01 ERROR (MainThread) [homeassistant.components.camera] Error requesting stream: Camera is off
2021-04-06 18:46:03 ERROR (MainThread) [homeassistant.components.camera] Error requesting stream: Camera is off`

In mihome my camera is ok, so could you help me please?

**Comment by NikDevx** [comment]
> Hello, i have the same camera and i have another error, in my log I see this error.
> `2021-04-06 18:46:01 ERROR (MainThread) [homeassistant.components.camera] Error requesting stream: Camera is off 2021-04-06 18:46:03 ERROR (MainThread) [homeassistant.components.camera] Error requesting stream: Camera is off`
> 
> In mihome my camera is ok, so could you help me please?

Hi
Did you read this one https://github.com/al-one/hass-xiaomi-miot/issues/11#issuecomment-773054167 ?

**Comment by al-one** [comment]
> @al-one
> Camera updates access_token success
> Only after rebooting the integrations or the HA server camera will you receive a new token

The `access_token` was generated by HA. This component only get the stream address from Xiaomi cloud and proxy it to HA. And HA will only trigger to get the stream address when viewing the camera entity.

**Comment by NikDevx** [comment]
> > Camera updates access_token success
> > Only after rebooting the integrations or the HA server camera will you receive a new token
> 
> The `access_token` was generated by HA. This component only get the stream address from Xiaomi cloud and proxy it to HA. And HA will only trigger to get the stream address when viewing the camera entity.

When I got stream address and open camera for the fist time - it is work perfect. But I can't never open more the one time.I need to reload integration or sometimes HA server.
Maybe I can add some custom field and use it to set up a reload trigger? For example count of opened stream or when stream not response? Could you help me?

**HA gets the stream address in real time?** Because I have a delay of 15-20 seconds.

**Comment by NikDevx** [comment]
Another update.
From vlc the video stream opens successfully all the time, but not from HA

And I got this in my logs
```
Logger: libav.tcp
Source: components/stream/worker.py:244
First occurred: 18:10:47 (2 occurrences)
Last logged: 18:10:47

Connection to tcp://de25.livestreaming.io.mi.com:443 failed: Connection refused
```

```
Logger: homeassistant.components.stream.worker
Source: components/stream/worker.py:255
Integration: Stream (documentation, issues)
First occurred: 18:10:47 (1 occurrences)
Last logged: 18:10:47

Error demuxing stream:
```

```
Logger: homeassistant.components.stream.worker
Source: components/stream/worker.py:130
Integration: Stream (documentation, issues)
First occurred: 18:14:41 (16 occurrences)
Last logged: 18:56:34

Error opening stream https://de25.livestreaming.io.mi.com/hlstranscoder/GCBjMjQ1MmIxZmNjMTk0Yjc4YTM3MTc2NmY0ZmI2NWYyZBgKX191bnVzZWRfXwA_H265transH264/playlist.m3u8
```

**Comment by al-one** [comment]
Check whether your HA host can connect to the Xiaomi streaming server:
```shell
curl -I https://de25.livestreaming.io.mi.com/hlstranscoder/GCBjMjQ1MmIxZmNjMTk0Yjc4YTM3MTc2NmY0ZmI2NWYyZBgKX191bnVzZWRfXwA_H265transH264/playlist.m3u8
```

**Comment by NikDevx** [comment]
It's fine

```
curl -I https://de11.livestreaming.io.mi.com/hlstranscoder/GCAzMGI5MTFmOWY2ZTk0MDIxODViYTQ3NTllOTg2ZTVjNhgKX191bnVzZWRfXwA_H265transH264/playlist.m3u8
HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Expose-Headers: Date, Server, Content-Type, Content-Length
Server: WowzaStreamingEngine/4.7.7
Cache-Control: no-cache
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: OPTIONS, GET, POST, HEAD
Access-Control-Allow-Headers: Content-Type, User-Agent, If-Modified-Since, Cache-Control, Range
Date: Thu, 08 Apr 2021 06:45:26 GMT
Content-Type: application/vnd.apple.mpegurl
Content-Length: 126
```

**Comment by NikDevx** [comment]
I got it!
I have this stream address now:
`stream_address: https://de21.livestreaming.io.mi.com/hlstranscoder/GCBkYTU0Zjc2Nzc3YTk0Yzk3OGEyMzYzZTQyMTFkMzM3NxgKX191bnVzZWRfXwA_H265transH264/playlist.m3u8`

But HA tries to open an older stream:
Logger: homeassistant.components.stream.worker
Source: components/stream/worker.py:130
Integration: Stream (documentation, issues)
First occurred: 7 апреля 2021 г., 21:38:07 (18 occurrences)
Last logged: 9:48:40

```
Error opening stream https://de13.livestreaming.io.mi.com/hlstranscoder/GCA3NDI0M2I5N2I4ZmM0YzIwOGUxZDQ1ZGRjZTIzMDU3NxgKX191bnVzZWRfXwA_H265transH264/playlist.m3u8
Error opening stream https://de29.livestreaming.io.mi.com/hlstranscoder/GCA1OTU3NmY5YWEzYWU0NTU1YTYyNjlkZDI3MzY2ZmRmORgKX191bnVzZWRfXwA_H265transH264/playlist.m3u8
```

**Comment by NikDevx** [comment]
I added with a token, not through the cloud
This helped https://github.com/al-one/hass-xiaomi-miot/issues/52#issuecomment-817077690
Thanks!

**Comment by al-one** [comment]
Try commit: https://github.com/al-one/hass-xiaomi-miot/commit/356ccbdd7af22b3c720e589860c72143d93f6dad

**Comment by NikDevx** [comment]
> Try commit: [356ccbd](https://github.com/al-one/hass-xiaomi-miot/commit/356ccbdd7af22b3c720e589860c72143d93f6dad)

Did not help

**Comment by al-one** [comment]
See https://github.com/al-one/hass-xiaomi-miot/issues/56#issuecomment-819379658
