### ISSUE TITLE
已经支持miio2miot本地接入的设备如果在外网即使使用云端接入也不行吗？

### ISSUE THREAD

**Issue by qiuyuxuan1999** [al-one/hass-xiaomi-miot#460]
如题，设备应该是miio协议的，由于作者做了miio2miot，可以本地接入了，所以应该在插件本地接入库里，默认本地接入。但这个设备不在HA主机所在地，在另外一个家。所以想让他云端接入，即使我将他自定义属性云端接入也还是不可用。而本身就不支持本地接入默认云端接入的异地设备就很顺利接入了。
目前有这个问题的我这有两个设备，一个是gosund插座cuco.plug.cp1，另一个是空调伴侣网关lumi.acpartner.v3。以插座为例，报错信息如下
鱼缸灯(cuco.plug.cp1): Got MiioException while fetching the state: Unable to discover the device 192.168.2.100, mapping: {'switch.on': {'siid': 2, 'piid': 1}}, max_properties: 1/1
我已经自定义他云端接入如下，还是不行
switch.cuco_cp1_26b0_switch:
  miot_cloud: true

另一个作者的miot插件就可以顺利地云端接入此设备

**Comment by al-one** [comment]
本插件支持一个小米账号多次添加集成，你可以把同一局域网下的设备用自动模式接入，再添加一个集成用自动模式接入另一个家庭的设备。

**Comment by al-one** [comment]
本插件支持一个小米账号多次添加集成，你可以把同一局域网下的设备用自动模式接入，再添加一个集成用云端模式接入另一个家庭的设备。

**Comment by qiuyuxuan1999** [comment]
再追问大佬一下，为什么我最开始添加的集成筛选设备是根据设备筛选的，而后添加的集成筛选设备是根据设备型号和WIFI筛选的？
![Screenshot_20220304_081431_io homeassistant companion android](https://user-images.githubusercontent.com/64347554/156674981-a2ede16a-6a8e-4a5a-9322-14270698abf9.jpg)
![Screenshot_20220304_081513_io homeassistant companion android](https://user-images.githubusercontent.com/64347554/156674993-053c8422-22da-46de-a4c4-91868de313be.jpg)

**Comment by al-one** [comment]
添加集成时不勾选“通过型号/WiFi筛选设备”即可。

**Comment by qiuyuxuan1999** [comment]
> 

明白了，非常感谢！
