### ISSUE TITLE
关于小米空气净化器1代，climate.zhimi_v1_befe_air_purifier

### ISSUE THREAD

**Issue by yyxp1989** [al-one/hass-xiaomi-miot#462]
你好
我的Xiaomi Miot Auto 为当前版本
Home Assistant 2022.3.1

小米空气净化器1代， 选择AUTO模式后，设备会相应开启，无法显示开机状态，一直显示是OFF， 反复操作过后，显示不可用状态报错如下，其余PM2.5 和滤芯寿命 显示正常。

Logger: custom_components.xiaomi_miot.climate
Source: custom_components/xiaomi_miot/__init__.py:1223
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 2022年3月4日 23:52:47 (7 occurrences)
Last logged: 24:23:47

[空气净化器(zhimi.airpurifier.v1)](https://home.miot-spec.com/s/zhimi.airpurifier.v1): Got MiioException while fetching the state: {'code': -9999, 'message': 'UART timeout'}, mapping: {'air_purifier.on': {'siid': 2, 'piid': 1}, 'air_purifier.fan_level': {'siid': 2, 'piid': 2}, 'air_purifier.mode': {'siid': 2, 'piid': 3}, 'filter.filter_life_level': {'siid': 4, 'piid': 1}, 'environment.pm2_5_density': {'siid': 3, 'piid': 1}}, max_properties: 10/5

**Comment by al-one** [comment]
请尝试在米家APP重新绑定改设备后再观察。

**Comment by al-one** [comment]
请问上述方法有用吗？

**Comment by yyxp1989** [comment]
> 请问上面的方法有用吗？

你好，miot已更新到现最新版本0.6.7，重新绑定后， 模式切换正常有响应，PM2.5和滤芯寿命 正常显示，  只有 空气净化器 Air Purifier Switch Status 这个实体，（是用来体现机器运行on/off的吗？）在机器运行时显示为false，无法触发为true.

**Comment by al-one** [comment]
请通过开发者工具执行下面的[服务](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.send_command)，并检查HA左侧边栏的通知：
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: climate.zhimi_v1_befe_air_purifier
  method: get_prop
  params: [power, mode]
  throw: true
```
