### ISSUE TITLE
能否给 德业除湿机DYD-Z12A3 添加水满状态监测？

### ISSUE THREAD

**Issue by zj1123581321** [al-one/hass-xiaomi-miot#463]
核心诉求是水满了给手机发个通知换水，避免人以为除湿机还在正常工作但是实际上它因为水满已经停机。

目前米家的自动化设置里还不支持水满作为自动化的触发条件，只能求助 HA 这边了。。

在当前的自定义属性中没有找到这款机型的设置：)还望添加

德业除湿机DYD-Z12A3 - 产品规格 - Xiaomi Miot Spec: https://home.miot-spec.com/spec?type=urn%3Amiot-spec-v2%3Adevice%3Adehumidifier%3A0000A02D%3Adeye-z12a3%3A1

![image](https://user-images.githubusercontent.com/33171229/156930067-9d24563a-2e94-4123-b0f4-fc9cb4c092af.png)

**Comment by al-one** [comment]
请提供开发者工具中的实体状态属性。

**Comment by zj1123581321** [comment]
```
min_humidity: 25
max_humidity: 80
available_modes:
  - Auto
  - Clothes Drying
humidity: 60
mode: Auto
model: deye.derh.z12a3
firmware_version: 2.0.2_0011
hardware_version: N/A for Cloud Mode
dehumidifi_switch_status: false
dehumidifi_fault: No Faults
dehumidifi_mode: 0
dehumidifi_target_humidity: 60
dehumidifi_speed: 3
environmen_relative_humidity: 79
environmen_temperature: 23
physical_c_physical_controls_locked: false
state_value: false
device_class: humidifier
friendly_name: 除湿机
supported_features: 1
```
目前是没有这个属性的？可以告知我去哪里找吗？
![image](https://user-images.githubusercontent.com/33171229/157062427-f29b8f4f-8948-4b8a-8e77-0c26a90b1228.png)
