### ISSUE TITLE
deerma.humidifier.jsq3: Unable to discover the device

### ISSUE THREAD

**Issue by hanley520** [al-one/hass-xiaomi-miot#464]
MI Smart humidifer Humidifier: Got MiioException while fetching the state: Unable to discover the device 192.168.10.216, mapping: {'humidifier.on': {'siid': 2, 'piid': 1}, 'humidifier.fault': {'siid': 2, 'piid': 2}, 'humidifier.fan_level': {'siid': 2, 'piid': 5}, 'humidifier.target_humidity': {'siid': 2, 'piid': 6}, 'humidifier.target_temperature': {'siid': 2, 'piid': 7}}, max_properties: 6/5
MI Smart humidifer Humidifier: Got MiioException while fetching the state: Unable to discover the device 192.168.10.216, mapping: {'humidifier.on': {'siid': 2, 'piid': 1}, 'humidifier.fault': {'siid': 2, 'piid': 2}, 'humidifier.fan_level': {'siid': 2, 'piid': 5}, 'humidifier.target_humidity': {'siid': 2, 'piid': 6}, 'humidifier.target_temperature': {'siid': 2, 'piid': 7}, 'indicator_light.on': {'siid': 6, 'piid': 1}, 'alarm': {'siid': 5, 'piid': 1}, 'environment.relative_humidity': {'siid': 3, 'piid': 1}, 'environment.temperature': {'siid': 3, 'piid': 7}}, max_properties: 6/9

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/350#issuecomment-1004561038
