### ISSUE TITLE
Not loaded issue

### ISSUE THREAD

**Issue by DeDuplicate** [al-one/hass-xiaomi-miot#468]
Xiaomi Miot Auto
Not loaded
can't see data anymore

**Comment by al-one** [comment]
Any error/warning [logs](https://my.home-assistant.io/redirect/logs) ?

**Comment by al-one** [comment]
https://github.com/al-one/hass-xiaomi-miot#installing

**Comment by DeDuplicate** [comment]
Error
Config flow could not be loaded: undefined
when trying to install from integration

**Comment by DeDuplicate** [comment]
It's working great work!

**Comment by DeDuplicate** [comment]
how can i add Mi 360 Webcam Camera Control video support?

**Comment by al-one** [comment]
> how can i add Mi 360 Webcam Camera Control video support?

Unsupported.

**Comment by al-one** [comment]
@MiAutomations Upgrade to latest release version.

**Comment by MiAutomations** [comment]
> a

@al-one I'm currently using the last one available over the hacs v1.4.1

What is the last one mentioned by you? 

Thank you

**Comment by al-one** [comment]
@MiAutomations 
![image](https://user-images.githubusercontent.com/4549099/157465107-1264a6b9-fcd1-43b0-949b-b20b83b7eee7.png)
