### ISSUE TITLE
云米热水器获取状态时出现 MiioException：设备无响应

### ISSUE THREAD

**Issue by hanley520** [al-one/hass-xiaomi-miot#471]
[热水器(viomi.waterheater.u24)](https://home.miot-spec.com/s/viomi.waterheater.u24): Got MiioException while fetching the state: No response from the device, mapping: {'water_heater.fault': {'siid': 2, 'piid': 1}, 'water_heater.target_temperature': {'siid': 2, 'piid': 2}, 'water_heater.temperature': {'siid': 2, 'piid': 3}, 'water_heater.mode': {'siid': 2, 'piid': 4}, 'water_heater.status': {'siid': 2, 'piid': 5}, 'water_heater.on': {'siid': 2, 'piid': 6}, 'function.water_velocity': {'siid': 4, 'piid': 1}}, max_properties: 9/7

**Comment by al-one** [comment]
请问该设备是一只不可用，还是偶尔出现比错误？

**Comment by al-one** [comment]
为了更有效及时的沟通，请加入QQ群`198841186`联系我。
