### ISSUE TITLE
如何恢复被删除的设备

### ISSUE THREAD

**Issue by malash** [al-one/hass-xiaomi-miot#473]
你好，我根据[这里的教程](https://github.com/al-one/hass-xiaomi-miot/issues/165#issuecomment-899988208)删除了设备之后，希望能再次恢复被删除的设备。

但是我尝试了在集成选项中重新勾选设备，该设备并没有恢复成功。

想问一下正确的恢复设备的操作是怎样的？

**Comment by al-one** [comment]
正常情况下重新勾选（包含模式）并保存后即可恢复，如果是排除模式需要取消勾选。如果筛选设备没有问题，请检查有无报错日志。

**Comment by malash** [comment]
看了下日志，有一个 `None device in xiaomi cloud: [邮箱]@qq.com` 的 warning，推测是这个造成了无法添加设备。

后续使用备份回滚了所有数据，没有再复现问题。
