### ISSUE TITLE
Xiaomi Mi Mop robot vacuum cleaner (mc1808) - unable to discover the device (MiioException while fetching the state)

### ISSUE THREAD

**Issue by schippie** [al-one/hass-xiaomi-miot#474]
**Problem I'm running into:**

I'm running into the following issue with my Xiaomi Mi Mop robot vacuum cleaner (mc1808) that is is unable to fetch the current state of it through the API or locally. Resulting in the below exception. I'm unsure where to ask this question or if it's even an issue with the integration itself. Any help or pointers where I could find help would be greatly appreciated.

**Device information:**

Firmware version: 4.1.8_1118

**Logs:**

```
This error originated from a custom integration.

Logger: custom_components.xiaomi_miot.vacuum
Source: custom_components/xiaomi_miot/__init__.py:1225
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 8:54:55 PM (3 occurrences)
Last logged: 8:56:07 PM

Robot vacuum(dreame.vacuum.mc1808): Got MiioException while fetching the state: 
Unable to discover the device 192.168.10.3, 
mapping: 

{
'vacuum.fault':{
'siid':3,
'piid':1
},
'vacuum.status':{
'siid':3,
'piid':2
},
'audio.volume':{
'siid':24,
'piid':1
},
'audio.voice_packets':{
'siid':24,
'piid':3
},
'map.map_view':{
'siid':23,
'piid':1
},
'map.frame_info':{
'siid':23,
'piid':2
},
'clean.work_mode':{
'siid':18,
'piid':1
},
'clean.area':{
'siid':18,
'piid':4
},
'clean.timer':{
'siid':18,
'piid':5
},
'clean.mode':{
'siid':18,
'piid':6
},
'clean.delete_timer':{
'siid':18,
'piid':8
},
'clean.water_box':{
'siid':18,
'piid':9
},
'clean.total_clean_time':{
'siid':18,
'piid':13
},
'clean.total_clean_times':{
'siid':18,
'piid':14
},
'clean.total_clean_area':{
'siid':18,
'piid':15
},
'clean.clean_log_start_time':{
'siid':18,
'piid':16
},
'clean.button_led':{
'siid':18,
'piid':17
},
'clean.task_done':{
'siid':18,
'piid':18
},
'brush_left_time-28-1':{
'siid':28,
'piid':1
},
'brush_life_level-28-2':{
'siid':28,
'piid':2
},
'filter.filter_life_level':{
'siid':27,
'piid':1
},
'filter.filter_left_time':{
'siid':27,
'piid':2
},
'brush_cleaner.brush_left_time':{
'siid':26,
'piid':1
},
'brush_cleaner.brush_life_level':{
'siid':26,
'piid':2
},
'battery.battery_level':{
'siid':2,
'piid':1
},
'battery.charging_state':{
'siid':2,
'piid':2
}
}
max_properties: 9/26
```

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/350#issuecomment-1004561038

**Comment by schippie** [comment]
It's probably due to the different subnets indeed, I have 1 LAN and 3 VLAN groups split out over 0,10,20 and 30. The home assistant is running within the admin subnet (192.168.0)  while the vacuum cleaner is within the home network 10 (but will get moved eventually to 30, but since this requires a full reset I haven't bother with changing this yet).

I do have an AVAHI mdns repeater setup (on the same Proxmox box, as the virtual machine for home assistant, but in a different virtual machine for Chromecast compatibility) and had hoped that the mdns repeater would suffice for this purpose as well. 

I'll follow the steps you provided here: https://python-miio.readthedocs.io/en/latest/troubleshooting.html#discover-devices-across-subnets provided in the hope this will rectify the issue. 

Thank you :+1:
