### ISSUE TITLE
shuii.humidifier.jsq002 信息获取不正常

### ISSUE THREAD

**Issue by ChanningHe** [al-one/hass-xiaomi-miot#477]
[shuii.humidifier.jsq002 零雾加湿器](https://home.miot-spec.com/s/shuii.humidifier.jsq002)
无法正常显示湿度温度以及加湿器状态

**Comment by al-one** [comment]
该设备的规格中相关属性没有读取权限。
https://home.miot-spec.com/spec/shuii.humidifier.jsq002
![image](https://user-images.githubusercontent.com/4549099/158510771-10fb39cc-b271-4d8b-9264-f6db7b9a544d.png)

**Comment by ChanningHe** [comment]
好的谢谢

**Comment by al-one** [comment]
该设备已适配本地模式，请更新到master分支体验。

**Comment by ChanningHe** [comment]
在本地模式下是可以读取数据了嘛

**Comment by al-one** [comment]
可用吗？

**Comment by ChanningHe** [comment]
读取数据任然不可。其他正常

**Comment by al-one** [comment]
更新到master分支了吗？

**Comment by ChanningHe** [comment]
恩，更新到master分支了。

**Comment by al-one** [comment]
请提供开发者工具中的[实体属性](https://my.home-assistant.io/redirect/developer_states)。

**Comment by al-one** [comment]
检查有无error/warning[日志](https://my.home-assistant.io/redirect/logs)。
