### ISSUE TITLE
chuangmi.camera.039a01 摄像头可以控制，但是无法预览摄像头画面

### ISSUE THREAD

**Issue by StimeKe** [al-one/hass-xiaomi-miot#478]
Logger: homeassistant.components.stream.stream.camera.chuangmi_039a01_187e_camera_control
Source: components/stream/__init__.py:340
Integration: Stream ([documentation](https://www.home-assistant.io/integrations/stream), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+stream%22))
First occurred: 10:12:37 (12 occurrences)
Last logged: 10:23:51

Error from stream worker: Error demuxing stream: [Errno 1094995529] Invalid data found when processing input: 'https://business.smartcamera.api.io.mi.com/common/app/m3u8?xxxxxxxxxxxxxxxxxxxxxxxx'; last error log: [mov,mp4,m4a,3gp,3g2,mj2] stream 0, offset 0x937: partial file

**Comment by al-one** [comment]
这也正是目前插件无法播放视频的原因，貌似是视频文件格式有问题。

**Comment by StimeKe** [comment]
> 这也正是目前插件无法播放视频的原因，貌似是视频文件格式有问题。

需要提供更多的信息吗

**Comment by al-one** [comment]
不用，暂时无法解决
