### ISSUE TITLE
米家窗帘不可用 Unable to discover the device

### ISSUE THREAD

**Issue by jihongboo** [al-one/hass-xiaomi-miot#483]
设备是米家窗帘Wi-Fi版
刚配置好的时候是可以用的，几个小时之后就一直处于“不可用”状态，hass和homekit一样，但是小米自己的app可以控制。尝试过删除设备重新添加，还是不行。

**Comment by al-one** [comment]
请检查有无error/warning日志。

**Comment by jihongboo** [comment]
Logger: custom_components.xiaomi_miot.cover
Source: custom_components/xiaomi_miot/__init__.py:1225 
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues)) 
First occurred: 13:30:46 (72 occurrences) 
Last logged: 13:48:36

窗帘(lumi.curtain.hmcn01): Got MiioException while fetching the state: Unable to discover the device 192.168.1.10, mapping: {'curtain.fault': {'siid': 2, 'piid': 1}, 'curtain.motor_control': {'siid': 2, 'piid': 2}, 'curtain.current_position': {'siid': 2, 'piid': 3}, 'curtain.status': {'siid': 2, 'piid': 6}, 'curtain.target_position': {'siid': 2, 'piid': 7}, 'remote_cfg.remote_identify': {'siid': 7, 'piid': 1}, 'remote_cfg.remote_list': {'siid': 7, 'piid': 2}, 'remote_cfg.remote_pair': {'siid': 7, 'piid': 3}, 'remote_cfg.remote_pair_status': {'siid': 7, 'piid': 4}, 'remote_cfg.remote_delete': {'siid': 7, 'piid': 5}, 'motor_controller.adjust_value': {'siid': 5, 'piid': 1}, 'curtain_cfg.manual_enabled': {'siid': 4, 'piid': 1}, 'curtain_cfg.polarity': {'siid': 4, 'piid': 2}, 'curtain_cfg.pos_limit': {'siid': 4, 'piid': 3}, 'curtain_cfg.en_night_tip_light': {'siid': 4, 'piid': 4}, 'curtain_cfg.run_time': {'siid': 4, 'piid': 5}}, max_properties: 8/16

**Comment by jihongboo** [comment]
> 

Logger: custom_components.xiaomi_miot.cover
Source: custom_components/xiaomi_miot/__init__.py:1225 
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues)) 
First occurred: 13:30:46 (72 occurrences) 
Last logged: 13:48:36

窗帘(lumi.curtain.hmcn01): Got MiioException while fetching the state: Unable to discover the device 192.168.1.10, mapping: {'curtain.fault': {'siid': 2, 'piid': 1}, 'curtain.motor_control': {'siid': 2, 'piid': 2}, 'curtain.current_position': {'siid': 2, 'piid': 3}, 'curtain.status': {'siid': 2, 'piid': 6}, 'curtain.target_position': {'siid': 2, 'piid': 7}, 'remote_cfg.remote_identify': {'siid': 7, 'piid': 1}, 'remote_cfg.remote_list': {'siid': 7, 'piid': 2}, 'remote_cfg.remote_pair': {'siid': 7, 'piid': 3}, 'remote_cfg.remote_pair_status': {'siid': 7, 'piid': 4}, 'remote_cfg.remote_delete': {'siid': 7, 'piid': 5}, 'motor_controller.adjust_value': {'siid': 5, 'piid': 1}, 'curtain_cfg.manual_enabled': {'siid': 4, 'piid': 1}, 'curtain_cfg.polarity': {'siid': 4, 'piid': 2}, 'curtain_cfg.pos_limit': {'siid': 4, 'piid': 3}, 'curtain_cfg.en_night_tip_light': {'siid': 4, 'piid': 4}, 'curtain_cfg.run_time': {'siid': 4, 'piid': 5}}, max_properties: 8/16

**Comment by al-one** [comment]
检查日志中的IP是否与米家APP中该设备的IP一致，建议通过路由器为该设备设置静态IP。

- https://github.com/al-one/hass-xiaomi-miot/issues/350#issuecomment-1004561038

**Comment by jihongboo** [comment]
确实是窗帘设备的网络问题，没有在路由器中找到窗帘，但是米家app中竟然可以操控？？重启窗帘后恢复正常。谢谢
