### ISSUE TITLE
能不能添加智能浴霸开关

### ISSUE THREAD

**Issue by mikeinblue** [al-one/hass-xiaomi-miot#487]
型号：[zinguo-b5m:1]
产品能认出来，不过只有2个entity,light,switch.
具体型号：https://home.miot-spec.com/spec?type=urn%3Amiot-spec-v2%3Adevice%3Aswitch%3A0000A003%3Azinguo-b5m%3A1

万分感谢

**Comment by al-one** [comment]
已添加对模式按键的支持，请更新到master分支后尝试。

**Comment by mikeinblue** [comment]
已经测试，完美局域网控制，谢谢龙大
