### ISSUE TITLE
Support zhimi.airfresh.va2 ?

### ISSUE THREAD

**Issue by bimodinochka** [al-one/hass-xiaomi-miot#489]
Will there be support ([zhimi.airfresh.va2](https://home.miot-spec.com/s/zhimi.airfresh.va2)) ?
The device is being added now, but it is not available for use.

**Comment by al-one** [comment]
Any error/warning [logs](https://my.home-assistant.io/redirect/logs) ?

**Comment by bimodinochka** [comment]
Here's what I see in the server log:


Logger: custom_components.xiaomi_miot.fan
Source: custom_components/xiaomi_miot/__init__.py:1225 
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues)) 
First occurred: 05:11:09 (38 occurrences) 
Last logged: 05:29:39

Air Fresh(zhimi.airfresh.va2): Got MiioException while fetching the state: {'code': -32601, 'message': 'Method not found.'}, mapping: {'air_fresh.on': {'siid': 2, 'piid': 1}, 'air_fresh.fan_level': {'siid': 2, 'piid': 2}, 'indicator_light.brightness': {'siid': 7, 'piid': 1}, 'alarm': {'siid': 6, 'piid': 1}, 'physical_controls_locked': {'siid': 5, 'piid': 1}, 'filter.filter_used_time': {'siid': 4, 'piid': 1}, 'environment.relative_humidity': {'siid': 3, 'piid': 1}, 'environment.pm2_5_density': {'siid': 3, 'piid': 2}, 'environment.temperature': {'siid': 3, 'piid': 3}, 'environment.co2_density': {'siid': 3, 'piid': 4}}, max_properties: 10/10

**Comment by al-one** [comment]
The device currently does not support local mode, please integrate it through automatic mode (account).

**Comment by bimodinochka** [comment]
Oh, will it be possible to add it locally?
Other integrations support local management.

**Comment by al-one** [comment]
Maybe soon ...

**Comment by al-one** [comment]
Upgrade to master branch and try.

**Comment by al-one** [comment]
Does it work ?

**Comment by altapo** [comment]
After update can't change fan mode in HA GUI (can set only Interval and Sleep mode)
I think problem with variable type

<img width="993" alt="Снимок экрана 2022-04-01 в 09 12 16" src="https://user-images.githubusercontent.com/837355/161193778-e909070d-b320-4cc5-855b-8ba7be3e8385.png">

**Comment by al-one** [comment]
@altapo Fixed in https://github.com/al-one/hass-xiaomi-miot/commit/22076b997d2918e3d254a9a1de23d26b071a2f03 for [zhimi.airfresh.va4](https://home.miot-spec.com/s/zhimi.airfresh.va4), upgrade to master branch.

**Comment by altapo** [comment]
After last fixes can't change fan mode to "Medium" (all other mode switch success)

try
```yaml
service: xiaomi_miot.set_miot_property
data:
  entity_id: fan.zhimi_va4_b22f_air_fresh
  siid: 2
  piid: 3
  value: 3
```

log
```
WARNING (SyncWorker_0) [custom_components.xiaomi_miot.fan] Приточный воздухоочиститель(zhimi.airfresh.va4): Set miot property {'did': '314765748', 'siid': 2, 'piid': 3, 'value': 3} failed: {'code': -5001, 'message': 'invaild_arg'}
```
