### ISSUE TITLE
关于开关的状态更新的问题。

### ISSUE THREAD

**Issue by purplebamboo** [al-one/hass-xiaomi-miot#490]
遇到开光物理按键设定后，hass里面状态同步很慢。

参考FAQ里面去设置了自定义属性发现没有用：https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774

**Comment by purplebamboo** [comment]
去翻了一下代码：https://github.com/al-one/hass-xiaomi-miot/blob/master/custom_components/xiaomi_miot/switch.py 好像开关不支持 interval_seconds: 10的设定，只支持传感器的吗？传感器里面有相应的获取参数代码。

**Comment by al-one** [comment]
通过其他终端改变设备状态同步到HA的延迟，我想FAQ中已经说的很明白了。如果你通过自定义属性控制更新频率没有生效，请检查配置是否正确，或通过debug日志观察更新间隔时长。

**Comment by lab37** [comment]
也可以通过一些开了局域网通信协议的设备来实现实时性要求，比如一个绿米网关，它会实时的在本地组播一些report，在局域网中监听这些组播数据，出现对应的数据时给hass发mqtt消息来触发自动化。
