### ISSUE TITLE
Video camera chuangmi.camera.ipc016 not displaying in lovelace

### ISSUE THREAD

**Issue by callacomp** [al-one/hass-xiaomi-miot#492]
Added camera to lovelace and comes up with :
Preview of the Video camera Camera Control camera.

This error originated from a custom integration.

Logger: custom_components.xiaomi_miot.camera
Source: custom_components/xiaomi_miot/camera.py:304
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 11:17:23 (378 occurrences)
Last logged: 17:38:53

Video camera(chuangmi.camera.ipc016): camera events is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'thirdPartPlayUnits': [], 'nextTime': 1647880493000, 'isContinue': True}, 'description': '成功', 'ts': 1648485293343}
Video camera(chuangmi.camera.ipc016): camera events is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'thirdPartPlayUnits': [], 'nextTime': 1647880553000, 'isContinue': True}, 'description': '成功', 'ts': 1648485353330}
Video camera(chuangmi.camera.ipc016): camera events is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'thirdPartPlayUnits': [], 'nextTime': 1647880613000, 'isContinue': True}, 'description': '成功', 'ts': 1648485413315}
Video camera(chuangmi.camera.ipc016): camera events is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'thirdPartPlayUnits': [], 'nextTime': 1647880673000, 'isContinue': True}, 'description': '成功', 'ts': 1648485473332}
Video camera(chuangmi.camera.ipc016): camera events is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'thirdPartPlayUnits': [], 'nextTime': 1647880733000, 'isContinue': True}, 'description': '成功', 'ts': 1648485533756}

**Comment by marian790** [comment]
i also have model: chuangmi.camera.ipc016. do you have any picture or stream? how to obtain?

**Comment by callacomp** [comment]
No picture yet, al-one has seen the request and labelled it camera. We wait for an update.😀

**Comment by al-one** [comment]
Only some newer cameras can see motion screenshots or playback for a few seconds after enable the `Home surveillance assistant` in the Mihome APP, and cannot play live streams.
