### ISSUE TITLE
空调插座功率显示错误

### ISSUE THREAD

**Issue by jibberchao** [al-one/hass-xiaomi-miot#496]
设备是这款 https://home.miot-spec.com/s/lumi.acpartner.mcn02
功率差了一千倍的样子，米家app上显示四百多瓦，HA上显示0.4W多点

**Comment by al-one** [comment]
https://github.com/al-one/hass-xiaomi-miot/commit/7a16c16f0736681deeb8d110baf64888be4d563f 已修复，请更新到master分支。
