### ISSUE TITLE
isa.camera.hlc7 No video stream after adding a camera to homeassistant

### ISSUE THREAD

**Issue by Alien-hide** [al-one/hass-xiaomi-miot#501]
No video stream after adding a camera(**isa.camera.hlc7**) to homeassistant 

![image](https://user-images.githubusercontent.com/31319054/161741927-bd060a5b-4666-41b7-97c5-a9006d7b2b06.png)

`2022-04-05 07:13:31 ERROR (MainThread) [homeassistant.components.camera] Error requesting stream: camera.isa_hlc7_e361_camera_control does not support play stream service`

**Comment by marian790** [comment]
same here...model: chuangmi.camera.ipc016

how to get stream or picture?

**Comment by Nemesis24** [comment]
I don't find anything too with isa.camera.isc5c1

**Comment by Alien-hide** [comment]
can you reveal more details ?
these cameras don't support sending video?
