### ISSUE TITLE
Error with Home Assistant 2022.4.0 - Unable to prepare setup for platform xiaomi_miot_raw.fan

### ISSUE THREAD

**Issue by Nag94** [al-one/hass-xiaomi-miot#503]
Hiello !

Since the update of Home Assistant to the version 2022.4.0, none of my Xiaomi Air Purifier is working (4 Pro and 3C versions). I have tried to uninstall and re-install, tried to redownload from HACS and of course, tried to restart HA, nothing to do, still not working. Here is the message received in the HA Logs  : 

_Unable to prepare setup for platform xiaomi_miot_raw.fan: Platform not found (cannot import name 'ATTR_SPEED' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py))._

Best.

**Comment by al-one** [comment]
Domain `xiaomi_miot_raw` is not this component.
This component is named `Xiaomi Miot Auto` and the domain is `xiaomi_miot`.

- https://github.com/ha0y/xiaomi_miot_raw/issues/380

**Comment by Nag94** [comment]
Sorry for the mistake, i have an error on both module. I will close this Issue and open a new one.

**Comment by Krzysztonek** [comment]
Hi,
Same issues here:

![image](https://user-images.githubusercontent.com/87784133/162421334-896f1e93-1348-4906-9d19-1dea67a73dbb.png)

 Logger: homeassistant.setup
Source: setup.py:298
First occurred: 11:46:58 (6 occurrences)
Last logged: 11:46:58

`    Unable to prepare setup for platform xiaomi_miot.fan: Platform not found (cannot import name 'SPEED_OFF' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)).
    Unable to prepare setup for platform xiaomi_miot.climate: Platform not found (cannot import name 'SPEED_OFF' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)).
    Unable to prepare setup for platform xiaomi_miot.cover: Platform not found (cannot import name 'SPEED_OFF' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)).
    Unable to prepare setup for platform xiaomi_miot.humidifier: Platform not found (cannot import name 'SPEED_OFF' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)).
    Unable to prepare setup for platform xiaomi_miot.device_tracker: Platform not found (cannot import name 'SPEED_OFF' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)).`

**Comment by al-one** [comment]
@Krzysztonek  Upgrade to master branch.
