### ISSUE TITLE
Air purifier error in logs

### ISSUE THREAD

**Issue by Merril-r** [al-one/hass-xiaomi-miot#509]
Getting this error from my air purifier . 

how do i fix this?

This error originated from a custom integration.

Logger: custom_components.xiaomi_miot.climate
Source: custom_components/xiaomi_miot/climate.py:178 
Integration: Xiaomi Miot Auto (documentation, issues) 
First occurred: 6:59:40 PM (1 occurrences) 
Last logged: 6:59:40 PM

climate.zhimi_mc1_7df7_air_purifier has been deprecated and will be removed in a future version. Please use fan.zhimi_mc1_7df7_air_purifier.

**Comment by al-one** [comment]
Use entity `fan.zhimi_mc1_7df7_air_purifier`.

**Comment by Merril-r** [comment]
How do I change that?

**Comment by Merril-r** [comment]
Blonde moment. I can see the entity you refer to. I was thinking i needed to change the climate to fan in the entity itself.

**Comment by Merril-r** [comment]
Thanks for the reply
