### ISSUE TITLE
ConnectionResetError when setting up integration

### ISSUE THREAD

**Issue by ads901119** [al-one/hass-xiaomi-miot#510]
It takes a lot of time to set up Xiaomi Miot Auto integration. After waiting for about 5-10 minute, it says `Unable to access Xiaomi API`

<img width="564" alt="image" src="https://user-images.githubusercontent.com/756198/162547248-94663868-0eb5-47d3-ae0a-2ac4ea79fda8.png">

Error message in logs:
`2022-04-09 06:44:18 ERROR (MainThread) [custom_components.xiaomi_miot.config_flow] Setup xiaomi cloud for user: MYACCOUNT@gmail.com failed: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

**Comment by al-one** [comment]
- Check the network of your HA host.
- ​[⚙️ Configuration](https://my.home-assistant.io/redirect/config) > Settings > [ℹ️ Info](https://my.home-assistant.io/redirect/info) > 🔍 Look for `Xiaomi Miot Auto`

**Comment by ads901119** [comment]
Hi @al-one 
There's no `Xiaomi Miot Auto` in the Info page. 
I guess I didn't successfully set up it, so it doesn't show. I installed it via HACS, but when setting up integration, it shows the error posted above.

**Comment by al-one** [comment]
Turn off VPN or proxy if you have them turned on.

**Comment by ads901119** [comment]
Hi @al-one 
I didn't use any VPN or proxy. What reason could be possible?
I remember this integration worked fine before about 2022.02
However for some unknown reason all related entities failed to update. I removed the integration and tried to add it back, but failed until now.

**Comment by al-one** [comment]
Try shell:
```shell
curl -v https://api.io.mi.com
curl -v https://account.xiaomi.com
curl -v https://miot-spec.org
```

**Comment by ads901119** [comment]
For https://api.io.mi.com it works fine.
<img width="608" alt="image" src="https://user-images.githubusercontent.com/756198/162679244-25c966c4-4523-4b65-876a-c231cc242144.png">

But no response from this two servers
https://account.xiaomi.com
https://miot-spec.org
<img width="525" alt="image" src="https://user-images.githubusercontent.com/756198/162679081-a0bb08e8-a575-4071-8d7f-a82d15dc6709.png">
<img width="760" alt="image" src="https://user-images.githubusercontent.com/756198/162679391-8673cfcc-e063-47fe-9fe9-e3c1088193bc.png">

**Comment by al-one** [comment]
```shell
nslookup miot-spec.org
```

**Comment by ads901119** [comment]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/756198/162680495-190e5c12-0c30-4b92-a91a-cf1748249d6e.png">

**Comment by al-one** [comment]
I don't know why, but you need to make sure you can access `https://miot-spec.org`.
