### ISSUE TITLE
可以加入yeelink.light.color5的支持嗎?

### ISSUE THREAD

**Issue by cooper2000** [al-one/hass-xiaomi-miot#511]
升級到Home Assistant 2022.4.1 Xiaomi Miio For Yeelink不能用了,目前"[米家 LED 智慧燈泡 Lite 彩光版(yeelink.light.color5)](https://home.miot-spec.com/s/yeelink.light.color5)"可以加入但顯示不可用,可以增加此裝置的支持嗎?謝謝!

**Comment by al-one** [comment]
请更新到最新版(v0.5.6)尝试。

**Comment by cooper2000** [comment]
可以用了,謝謝你!
