### ISSUE TITLE
Humidifier zhimi.humidifier.ca4 after update to  v0.5.5 - missed "physical-controls-locked"

### ISSUE THREAD

**Issue by prokudin07** [al-one/hass-xiaomi-miot#512]
Hello, 
after update to version v0.5.5 
missed "[physical-controls-locked](https://miot-spec.org/miot-spec-v2/spec/service?type=urn:miot-spec-v2:service:physical-controls-locked:00007807)"

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/81035252/162572775-dc1957b0-2c25-49d2-bfa9-f4e833f40951.png">

Thank you.

**Comment by al-one** [comment]
Upgrade to master branch.

**Comment by prokudin07** [comment]
Thanks a lot. All work.
