### ISSUE TITLE
麻烦增加yeelink.light.color8的本地支持

### ISSUE THREAD

**Issue by sirarikako** [al-one/hass-xiaomi-miot#513]
从miio for yeelink转来，各种吸顶灯OK，不过LAN模式下下面这个灯泡显示无法操作。
看更新记录里有miio2miot的记录，想问问下面这个是不是也可以？

https://home.miot-spec.com/s/yeelink.light.color8

谢谢

**Comment by al-one** [comment]
请更新到master分支尝试。

**Comment by sirarikako** [comment]
更新到master分支后已经可以正常操作了，谢谢。
