### ISSUE TITLE
相機看不到 camera events is empty

### ISSUE THREAD

**Issue by mountain0320** [al-one/hass-xiaomi-miot#515]
自行安裝整合產生錯誤。

Logger: custom_components.xiaomi_miot.camera
Source: custom_components/xiaomi_miot/camera.py:304
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 17:04:55 (80 occurrences)
Last logged: 17:23:56

攝影機3(chuangmi.camera.029a02): camera events is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'thirdPartPlayUnits': [], 'nextTime': 1648977805000, 'isContinue': True}, 'description': '成功', 'ts': 1649582606378}
攝影機4(chuangmi.camera.ipc009): camera events is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'thirdPartPlayUnits': [], 'nextTime': 1648977835000, 'isContinue': True}, 'description': '成功', 'ts': 1649582635746}
攝影機3(chuangmi.camera.029a02): camera events is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'thirdPartPlayUnits': [], 'nextTime': 1648977835000, 'isContinue': True}, 'description': '成功', 'ts': 1649582636135}
攝影機2(chuangmi.camera.029a02): camera events is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'thirdPartPlayUnits': [], 'nextTime': 1648977835000, 'isContinue': True}, 'description': '成功', 'ts': 1649582636479}
攝影機1(chuangmi.camera.029a02): camera events is empty. {'result': 'ok', 'retriable': False, 'code': 0, 'data': {'thirdPartPlayUnits': [], 'nextTime': 1648977836000, 'isContinue': True}, 'description': '成功', 'ts': 1649582636520}

**Comment by al-one** [comment]
请在米家APP中为该摄像头开启`看家助手`。

**Comment by mountain0320** [comment]
謝謝您

**Comment by mountain0320** [comment]
請問攝像頭是不是無法直播!?只有發生事件才會記錄

**Comment by al-one** [comment]
无法观看直播。
