### ISSUE TITLE
空调插座功率单位可能有误

### ISSUE THREAD

**Issue by findix** [al-one/hass-xiaomi-miot#519]
首先感谢作者！

`lumi.acpartner.mcn02` 设备的 `sensor.lumi_mcn02_f281_electric_power` 传感器单位是W，但是感觉其实应该是KW，不知道是只有`mcn02`是这样，还是`lumi.aircondition.*`都是，所以不敢提PR。

![image](https://user-images.githubusercontent.com/3446387/162922728-8f2cbb5b-110c-48c2-9dda-5eefb73b3f56.png)
![image](https://user-images.githubusercontent.com/3446387/162925644-c5eb991e-ffc5-436f-a904-0b62e00654c7.png)

https://github.com/al-one/hass-xiaomi-miot/blob/2ef57cd8fe3560c412223d0e622b4688d78febd4/custom_components/xiaomi_miot/core/device_customizes.py#L145-L149

**Comment by al-one** [comment]
https://github.com/al-one/hass-xiaomi-miot/commit/7a16c16f0736681deeb8d110baf64888be4d563f 已修复，请更新到master分支。

**Comment by findix** [comment]
感谢！！
