### ISSUE TITLE
设备突然全部掉线，麻烦帮忙看下什么问题

### ISSUE THREAD

**Issue by terryzsb** [al-one/hass-xiaomi-miot#520]
Logger: homeassistant.components.yeelight.config_flow
Source: components/yeelight/config_flow.py:267 
Integration: Yeelight (documentation, issues) 
First occurred: 22:52:53 (3 occurrences) 
Last logged: 22:52:56

Failed to get properties from 192.168.31.123: Failed to read from the socket at 192.168.31.123:55443: [Errno 111] Connect call failed ('192.168.31.123', 55443).
Failed to get properties from 192.168.31.69: Failed to read from the socket at 192.168.31.69:55443: [Errno 111] Connect call failed ('192.168.31.69', 55443).

**Comment by al-one** [comment]
日志来自[`yeelight`](https://home-assistant.io/integrations/yeelight)集成，并非本项目集成。

**Comment by terryzsb** [comment]
Logger: homeassistant.components.light
Source: custom_components/xiaomi_miot/fan.py:5 
Integration: 灯光 (documentation, issues) 
First occurred: 08:10:15 (2 occurrences) 
Last logged: 08:10:15

xiaomi_miot: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 735, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1154, in async_update
    self._update_sub_entities(pls, '*', domain=d)
  File "/config/custom_components/xiaomi_miot/__init__.py", line 1594, in _update_sub_entities
    from .binary_sensor import MiotBinarySensorSubEntity
  File "/config/custom_components/xiaomi_miot/binary_sensor.py", line 33, in <module>
    from .fan import MiotModesSubEntity
  File "/config/custom_components/xiaomi_miot/fan.py", line 5, in <module>
    from homeassistant.components.fan import (
ImportError: cannot import name 'SPEED_OFF' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)

**Comment by al-one** [comment]
请升级插件到最新版本：
- #495
- #505

**Comment by al-one** [comment]
请升级插件到最新版本：
- #495
- #505

**Comment by befantasy** [comment]
很奇怪，我的日志里也一直在报这个错误。
查了一下IP这两个设备分别是：yeelink.wifispeaker.v1和yeelink.light.lamp22，虽然是yeelight的设备，但都是兼容米家，绑定在米家账号上，通过本集成接入的。目前没看出有什么影响，但一直报错很别扭。

`Logger: homeassistant.components.yeelight.config_flow
Source: components/yeelight/config_flow.py:267
Integration: Yeelight ([documentation](https://www.home-assistant.io/integrations/yeelight), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+yeelight%22))
First occurred: 00:56:06 (3 occurrences)
Last logged: 01:11:11

Failed to get properties from 192.168.0.17: Failed to read from the socket at 192.168.0.17:55443: [Errno 111] Connect call failed ('192.168.0.17', 55443).
Failed to get properties from 192.168.0.111: Failed to read from the socket at 192.168.0.111:55443: [Errno 111] Connect call failed ('192.168.0.111', 55443).`

**Comment by al-one** [comment]
@befantasy `homeassistant.components.yeelight`
该报错与本插件无关。
