### ISSUE TITLE
跨网段设备无法本地控制

### ISSUE THREAD

**Issue by GavinCXY** [al-one/hass-xiaomi-miot#522]
有一支持本地模式的设备，型号为julun.switch.jlsw01，与HA属于不同网段，但网络可以互通。此设备通过本项目插件接入后，实体是离线状态，无法控制。

请问：
1. 能否支持跨网段本地模式？
2. 对于支持本地模式的设备，能否提供选项改为云端模式？

目前我的临时方案是把这个型号的本地模式给注释掉，让插件走云端模式。

非常感谢大神开发的插件~

**Comment by baiuu** [comment]
> 有一支持本地模式的设备，型号为julun.switch.jlsw01，与HA属于不同网段，但网络可以互通。此设备通过本项目插件接入后，实体是离线状态，无法控制。
> 
> 请问：
> 
> 1. 能否支持跨网段本地模式？
> 2. 对于支持本地模式的设备，能否提供选项改为云端模式？
> 
> 目前我的临时方案是把这个型号的本地模式给注释掉，让插件走云端模式。
> 
> 非常感谢大神开发的插件~

不能跨网段不是因为插件的原因是米家的设定不接受自来跨网段的局域网控制数据包，是想实现部分设备本地部分设备云端？

**Comment by al-one** [comment]
部分设备不支持跨网段连接，参考：
- https://github.com/al-one/hass-xiaomi-miot/issues/349#issuecomment-1004179460

如果想通过云端模式解决，可以再新建一次集成（登陆同一账号），使用云端模式接入这些设备。

**Comment by GavinCXY** [comment]
> > 有一支持本地模式的设备，型号为julun.switch.jlsw01，与HA属于不同网段，但网络可以互通。此设备通过本项目插件接入后，实体是离线状态，无法控制。
> > 请问：
> > 
> > 1. 能否支持跨网段本地模式？
> > 2. 对于支持本地模式的设备，能否提供选项改为云端模式？
> > 
> > 目前我的临时方案是把这个型号的本地模式给注释掉，让插件走云端模式。
> > 非常感谢大神开发的插件~
> 
> 不能跨网段不是因为插件的原因是米家的设定不接受自来跨网段的局域网控制数据包，是想实现部分设备本地部分设备云端？

主要是家里的网络根据布局进行了划分，但是其它子网的这个设备无法接入，所以来问一下。 如果确实无法跨子网集成，就想问一下怎么让这个设备走云端，因为用账号集成的时候插件自动识别设备型号之后走本地模式了。

**Comment by GavinCXY** [comment]
> 部分设备不支持跨网段连接，参考：
> 
> * [viomi.vacuum.v18 Unable to discover device #349 (comment)](https://github.com/al-one/hass-xiaomi-miot/issues/349#issuecomment-1004179460)
> 
> 如果想通过云端模式解决，可以再新建一次集成（登陆同一账号），使用云端模式接入这些设备。

好的，感谢

**Comment by GavinCXY** [comment]
最终用iptables nat方式解决跨网段的问题，再次表示感谢~
