### ISSUE TITLE
Dreame L10 Pro unavailable in local mode

### ISSUE THREAD

**Issue by Sim0cYz** [al-one/hass-xiaomi-miot#526]
Hello, I noticed my [Dreame L10 Pro vacuum](https://home.miot-spec.com/s/dreame.vacuum.p2029) is always unavailable in local mode.
In cloud mode is available but I can't use custom scripts ([like this one I'm trying to build](https://github.com/al-one/hass-xiaomi-miot/issues/491)) to clean specific rooms as they simply won't work, throws this notify:
```
{'did': '447506991', 'miid': 0, 'siid': 4, 'aiid': 1, 'code': -704220025, 'exe_time': 0, 'withLatency': 0}
```
How can I help troubleshooting? Thank you

**Comment by Sim0cYz** [comment]
I just tried to remove it from MiHome app, reset Wi-Fi settings and reconfigure it.
Now it's set up as Automatic, and I have this error in logs:
```
Logger: custom_components.xiaomi_miot.vacuum
Source: custom_components/xiaomi_miot/__init__.py:1242 
Integration: Xiaomi Miot Auto (documentation, issues) 
First occurred: 22:29:04 (6 occurrences) 
Last logged: 22:52:13

Dreame Bot L10 Pro(dreame.vacuum.p2029): Got MiioException while fetching the state: Unable to discover the device 192.168.69.2, mapping: {'vacuum.status': {'siid': 2, 'piid': 1}, 'vacuum.fault': {'siid': 2, 'piid': 2}, 'vacuum.mode': {'siid': 2, 'piid': 3}, 'clean_logs.first_clean_time': {'siid': 12, 'piid': 1}, 'clean_logs.total_clean_time': {'siid': 12, 'piid': 2}, 'clean_logs.total_clean_times': {'siid': 12, 'piid': 3}, 'clean_logs.total_clean_area': {'siid': 12, 'piid': 4}, 'audio.volume': {'siid': 7, 'piid': 1}, 'audio.voice_packet_id': {'siid': 7, 'piid': 2}, 'audio.voice_change_state': {'siid': 7, 'piid': 3}, 'audio.set_voice': {'siid': 7, 'piid': 4}, 'map.frame_info': {'siid': 6, 'piid': 2}, 'map.map_extend_data': {'siid': 6, 'piid': 4}, 'map.mult_map_state': {'siid': 6, 'piid': 7}, 'map.mult_map_info': {'siid': 6, 'piid': 8}, 'do_not_disturb.enable': {'siid': 5, 'piid': 1}, 'do_not_disturb.start_time': {'siid': 5, 'piid': 2}, 'do_not_disturb.end_time': {'siid': 5, 'piid': 3}, 'vacuum_extend.work_mode': {'siid': 4, 'piid': 1}, 'vacuum_extend.cleaning_time': {'siid': 4, 'piid': 2}, 'vacuum_extend.cleaning_area': {'siid': 4, 'piid': 3}, 'vacuum_extend.cleaning_mode': {'siid': 4, 'piid': 4}, 'vacuum_extend.mop_mode': {'siid': 4, 'piid': 5}, 'vacuum_extend.waterbox_status': {'siid': 4, 'piid': 6}, 'vacuum_extend.task_status': {'siid': 4, 'piid': 7}, 'vacuum_extend.clean_extend_data': {'siid': 4, 'piid': 10}, 'break_point_restart-4-11': {'siid': 4, 'piid': 11}, 'vacuum_extend.carpet_press': {'siid': 4, 'piid': 12}, 'vacuum_extend.serial_number': {'siid': 4, 'piid': 14}, 'vacuum_extend.remote_state': {'siid': 4, 'piid': 15}, 'vacuum_extend.clean_rags_tip': {'siid': 4, 'piid': 16}, 'vacuum_extend.keep_sweeper_time': {'siid': 4, 'piid': 17}, 'vacuum_extend.faults': {'siid': 4, 'piid': 18}, 'vacuum_extend.nation_matched': {'siid': 4, 'piid': 19}, 'vacuum_extend.relocation_status': {'siid': 4, 'piid': 20}, 'vacuum_extend.laser_switch': {'siid': 4, 'piid': 21}, 'filter.filter_life_level': {'siid': 11, 'piid': 1}, 'filter.filter_left_time': {'siid': 11, 'piid': 2}, 'brush_left_time-10-1': {'siid': 10, 'piid': 1}, 'brush_life_level-10-2': {'siid': 10, 'piid': 2}, 'brush_cleaner.brush_left_time': {'siid': 9, 'piid': 1}, 'brush_cleaner.brush_life_level': {'siid': 9, 'piid': 2}, 'battery.battery_level': {'siid': 3, 'piid': 1}, 'battery.charging_state': {'siid': 3, 'piid': 2}}, max_properties: 9/44
```

**Comment by al-one** [comment]
Try this configuration:
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    dreame.vacuum.p2029:
      exclude_miot_services: consumable,annoy,remote,time,clean_logs,map
```

**Comment by Sim0cYz** [comment]
Same, I get this log:

>Logger: custom_components.xiaomi_miot.vacuum
Source: custom_components/xiaomi_miot/__init__.py:1242 
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues)) 
First occurred: 11:18:01 (3 occurrences) 
Last logged: 11:19:42
Dreame Bot L10 Pro(dreame.vacuum.p2029): Got MiioException while fetching the state: Unable to discover the device 192.168.69.2, mapping: {'vacuum.status': {'siid': 2, 'piid': 1}, 'vacuum.fault': {'siid': 2, 'piid': 2}, 'vacuum.mode': {'siid': 2, 'piid': 3}, 'audio.volume': {'siid': 7, 'piid': 1}, 'audio.voice_packet_id': {'siid': 7, 'piid': 2}, 'audio.voice_change_state': {'siid': 7, 'piid': 3}, 'audio.set_voice': {'siid': 7, 'piid': 4}, 'do_not_disturb.enable': {'siid': 5, 'piid': 1}, 'do_not_disturb.start_time': {'siid': 5, 'piid': 2}, 'do_not_disturb.end_time': {'siid': 5, 'piid': 3}, 'vacuum_extend.work_mode': {'siid': 4, 'piid': 1}, 'vacuum_extend.cleaning_time': {'siid': 4, 'piid': 2}, 'vacuum_extend.cleaning_area': {'siid': 4, 'piid': 3}, 'vacuum_extend.cleaning_mode': {'siid': 4, 'piid': 4}, 'vacuum_extend.mop_mode': {'siid': 4, 'piid': 5}, 'vacuum_extend.waterbox_status': {'siid': 4, 'piid': 6}, 'vacuum_extend.task_status': {'siid': 4, 'piid': 7}, 'vacuum_extend.clean_extend_data': {'siid': 4, 'piid': 10}, 'break_point_restart-4-11': {'siid': 4, 'piid': 11}, 'vacuum_extend.carpet_press': {'siid': 4, 'piid': 12}, 'vacuum_extend.serial_number': {'siid': 4, 'piid': 14}, 'vacuum_extend.remote_state': {'siid': 4, 'piid': 15}, 'vacuum_extend.clean_rags_tip': {'siid': 4, 'piid': 16}, 'vacuum_extend.keep_sweeper_time': {'siid': 4, 'piid': 17}, 'vacuum_extend.faults': {'siid': 4, 'piid': 18}, 'vacuum_extend.nation_matched': {'siid': 4, 'piid': 19}, 'vacuum_extend.relocation_status': {'siid': 4, 'piid': 20}, 'vacuum_extend.laser_switch': {'siid': 4, 'piid': 21}, 'filter.filter_life_level': {'siid': 11, 'piid': 1}, 'filter.filter_left_time': {'siid': 11, 'piid': 2}, 'brush_left_time-10-1': {'siid': 10, 'piid': 1}, 'brush_life_level-10-2': {'siid': 10, 'piid': 2}, 'brush_cleaner.brush_left_time': {'siid': 9, 'piid': 1}, 'brush_cleaner.brush_life_level': {'siid': 9, 'piid': 2}, 'battery.battery_level': {'siid': 3, 'piid': 1}, 'battery.charging_state': {'siid': 3, 'piid': 2}}, max_properties: 9/36

Fyi, the robot is integrated choosing "Local" mode at wizard (and I tried to delete and re-add it now, no luck)

**Comment by al-one** [comment]
Try this configuration:
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    dreame.vacuum.p2029:
      exclude_miot_services: consumable,annoy,remote,time,clean_logs,map,vacuum_extend
```

**Comment by Sim0cYz** [comment]
Again, no success. 
Some more infos, I'm adding the device choosing:

- Add devices using Mi Account;
- Connection mode Local.

This is the log I get with the latest config you suggested:
>Logger: custom_components.xiaomi_miot.vacuum
Source: custom_components/xiaomi_miot/__init__.py:1242 
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues)) 
First occurred: 11:30:42 (4 occurrences) 
Last logged: 11:34:35
Dreame Bot L10 Pro(dreame.vacuum.p2029): Got MiioException while fetching the state: Unable to discover the device 192.168.69.2, mapping: {'vacuum.status': {'siid': 2, 'piid': 1}, 'vacuum.fault': {'siid': 2, 'piid': 2}, 'vacuum.mode': {'siid': 2, 'piid': 3}, 'audio.volume': {'siid': 7, 'piid': 1}, 'audio.voice_packet_id': {'siid': 7, 'piid': 2}, 'audio.voice_change_state': {'siid': 7, 'piid': 3}, 'audio.set_voice': {'siid': 7, 'piid': 4}, 'do_not_disturb.enable': {'siid': 5, 'piid': 1}, 'do_not_disturb.start_time': {'siid': 5, 'piid': 2}, 'do_not_disturb.end_time': {'siid': 5, 'piid': 3}, 'filter.filter_life_level': {'siid': 11, 'piid': 1}, 'filter.filter_left_time': {'siid': 11, 'piid': 2}, 'brush_left_time-10-1': {'siid': 10, 'piid': 1}, 'brush_life_level-10-2': {'siid': 10, 'piid': 2}, 'brush_cleaner.brush_left_time': {'siid': 9, 'piid': 1}, 'brush_cleaner.brush_life_level': {'siid': 9, 'piid': 2}, 'battery.battery_level': {'siid': 3, 'piid': 1}, 'battery.charging_state': {'siid': 3, 'piid': 2}}, max_properties: 9/18

**Comment by al-one** [comment]
There is no problem with the way of integration, make sure your device IP `192.168.69.2` is correct. Some devices reboot when querying a large number of properties.

**Comment by Sim0cYz** [comment]
I just double checked, device IP is correct, it's reachable as I can ping it. (and it's confirmed by attributes below)

if I set it up as Connection mode Cloud, it's online/available and has these attributes:

>Model
dreame.vacuum.p2029
Lan IP
192.168.69.2
MAC address
24:18:C6:16:21:33
Entity class
MiotVacuumEntity
Home room
Casa
Exclude miot services
consumable, annoy, remote, time, clean_logs, map, vacuum_extend
Miot type
urn:miot-spec-v2:device:vacuum:0000A006:dreame-p2029:3
Vacuum.status
6
Vacuum.fault
68
Vacuum.mode
2
Audio.volume
75
Audio.voice packet ID
IT
Audio.voice change state
{"id":"IT","state":"success","progress":100}
Audio.set voice.error
-704030013 Property is not readable
Do not disturb.enable
true
Do not disturb.start time
22:00
Do not disturb.end time
08:00
Filter.filter life level
95
Filter.filter left time
142
Brush left time-10-1
192
Brush life level-10-2
96
Brush cleaner.brush left time
292
Brush cleaner.brush life level
97
Battery.battery level
90
Battery.charging state
1
State updater
cloud

I also can start, stop, etc.. while cloud connected (but no custom scripts).

**Comment by al-one** [comment]
Are the IP of the HA core and the IP of the device on the same network segment ?

**Comment by Sim0cYz** [comment]
they aren't, but firewall rules let them access each other between different VLANs

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/349#issuecomment-1004179460

**Comment by Sim0cYz** [comment]
Okay you're right, moving it in the same subnet of Home Assistant Core fixed it.
Thank you for the great support and keep up the awesome work you are doing! :)
