### ISSUE TITLE
dooya-curtain-m1_miap7667 接入ha 电机自动反向，且无法修改

### ISSUE THREAD

**Issue by kkgtx** [al-one/hass-xiaomi-miot#528]
dooya-curtain-m1_miap7667 接入ha后电机自动反向，在米家中修改后立刻又变反向。导致所有操作都是反的。miot是最新的。电机断电后，ha和米家都无法操作电机。需要米家重新添加电机才正常。

**Comment by al-one** [comment]
请提供开发者工具中的实体状态属性，并详细描述具体状态，比如设备在米家中反向开和关状态下的实体属性。

**Comment by kkgtx** [comment]
实体属性 是相反 同时又2的位置偏差，最主要的是电机反转 没法改。改成自定义的实体，现在没从mito auto 里面挂载了，现在没问题，应该是程序bug
----- 原始邮件 -----
发件人：Alone ***@***.***>
收件人：al-one/hass-xiaomi-miot ***@***.***>
抄送人：kkgtx ***@***.***>,  Author ***@***.***>
主题：Re:_[al-one/hass-xiaomi-miot]_dooya-curtain-m1_miap7667_接入ha_电机自动反向，且无法修改_(Issue_#528)
日期：2022年04月20日 12点58分



请提供开发者工具中的实体状态属性，并详细描述具体状态，比如设备在米家中反向开和关状态下的实体属性。



&mdash;

**Comment by zhf883680** [comment]
我现在也遇到这个问题 请问是如何处理的

**Comment by TomatoFryEggs** [comment]
同样问题，已经删除了设备

**Comment by al-one** [comment]
请提供开发者工具中的实体状态属性，并详细描述具体状态，比如设备在米家中反向开和关状态下的实体属性。
