### ISSUE TITLE
我想在我的hass 的 homekit安装新的插件

### ISSUE THREAD

**Issue by MagicStarTrace** [al-one/hass-xiaomi-miot#529]
![image](https://user-images.githubusercontent.com/15685376/163762960-0cdda6f8-bc3a-4598-bdda-b807d1238f67.png)

我想在我的homekit安装新的插件，比如wol插件

这个似乎是自动被发现的，我没自己安装过

但是我不知道在哪里可新增插件，可以帮帮我吗？

谢谢~

**Comment by al-one** [comment]
我不太明白你的意思，且该问题貌似与本插件无关。

**Comment by MagicStarTrace** [comment]
好像是hass 集成的
