### ISSUE TITLE
升级后浴霸好像不支持了yeelink.bhf_light.v1

### ISSUE THREAD

**Issue by xztxy** [al-one/hass-xiaomi-miot#53]
yeelink.bhf_light.v1

日志都是这个，，ERROR (MainThread) [custom_components.xiaomi_miot] Got MiioException while fetching the state for 浴霸 Light: {'code': -9999, 'message': 'user ack timeout'}

**Comment by al-one** [comment]
v0.3.1在使用token集成设备并开启云端的情况下有bug。请升级到master最新版本。

**Comment by xztxy** [comment]
> v0.3.1在使用token集成设备并开启云端的情况下有bug。请升级到master最新版本。

好的，感谢~
