### ISSUE TITLE
Vacuum-Mop 2 Pro wrong fan speeds

### ISSUE THREAD

**Issue by Dejv311** [al-one/hass-xiaomi-miot#531]
On this model the selectable "fan speeds" are Sweep, Sweep and Mop, Mop. These are obviously not fan speeds, but cleaning profiles. Haven't found a way to work around this so far. Thank you for any feedback.

**Comment by al-one** [comment]
Is [`ijai.vacuum.v3`](https://home.miot-spec.com/spec/ijai.vacuum.v3) ?

The device manufacturer does not define any fan speed related miot properties for it.

**Comment by Dejv311** [comment]
Hi, yes... It is ijai.vacuum.v3. I find it strange not to have fan speed variables, since the official xiaomi app offers the option to change the fan speed...

**Comment by kaibs** [comment]
Do you mean the suction power of the vacuum with "fan speed"?
If so `suction-state` (siid 7, piid 5) should work for you.
I have a `ijai.vacuum.v19` (Vacuum-Mop 2S) which seems to have very similar miot-specs to your robot and this is how I'm able to do it (setting it with `xiaomi_miot.set_property`).

**Comment by al-one** [comment]
Please upgrade to master branch and try.
