### ISSUE TITLE
MiTV(xiaomi.tv.z2oh1): Set miot property return code: -4007

### ISSUE THREAD

**Issue by mumuxiyu** [al-one/hass-xiaomi-miot#532]
此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.media_player
Source: custom_components/xiaomi_miot/__init__.py:1660
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 08:47:51 (2 occurrences)
Last logged: 08:53:21

MiTV(xiaomi.tv.z2oh1): Set miot property {'did': 'prop.2.1', 'siid': 2, 'piid': 1, 'value': 5} failed, result: {'did': 'prop.2.1', 'siid': 2, 'piid': 1, 'code': -4007}

我是docker的HA，遥控功能都可用，但电视实体无法关机、更改信号源

**Comment by al-one** [comment]
`-4007`错误为设备`did`错误，小米/Redmi电视都必须要正确的`did`才能在本地调用miot协议，然而使用token接入的方式无法获取设备`did`，推荐你使用账号接入(自动模式)。
如果你坚持使用token接入，请自行获取`did`并通过[自定义属性](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)为电视实体绑定`did`：
```yaml
# customize.yaml
media_player.xiaomi_z2oh1_xxxx_entity_id:
  miot_did: mitv.abcdef...
```

> 小米设备的`did`可添加集成账号接入后在文件`.storage/xiaomi_miot/devices-xxxx-xx.json`中找到。
