### ISSUE TITLE
aqara 墙壁插座无功率显示

### ISSUE THREAD

**Issue by zhxiaoping** [al-one/hass-xiaomi-miot#536]
![image](https://user-images.githubusercontent.com/47968604/164679381-f19cd39f-0fca-43fe-971a-25e52705b80f.png)
如图所示，小米app是可以显示功率计，
通过插件接入就没有了，不知大佬们能否解决下

**Comment by al-one** [comment]
https://home.miot-spec.com/spec/lumi.ctrl_86plug.aq1

设备尝试未定义相关属性。

**Comment by zhxiaoping** [comment]
那如果通过多模网关本地接入，我们这个插件有没有可能就有这个属性呢？

> https://home.miot-spec.com/spec/lumi.ctrl_86plug.aq1
> 
> 设备厂商未定义相关属性。

**Comment by al-one** [comment]
miot属性与网关无关，是由设备厂商在米家开发者中心定义的一套设备规格，因此无论用什么网关接入，可获取的miot属性都是这些。如果你有多模网关，可以试试多模插件接入。
