### ISSUE TITLE
mijia.vacuum.v2 missing setting for Water Level 1,2,3

### ISSUE THREAD

**Issue by radek-kafka** [al-one/hass-xiaomi-miot#539]
Hello,
please would it be possible to allow in front-end setting for [mijia.vacuum.v2  (G1Vacuum class)](https://home.miot-spec.com/s/mijia.vacuum.v2) for Water level 1, 2, 3 ? I have tested with miiocli and working properly: 

Read overall status: 
 miiocli g1vacuum --ip=192.168.88.24 --token XXXXX
WARNING:miio.device:Found an unsupported model 'mijia.vacuum.v2' for class 'G1Vacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
State: G1State.Charging
Error: No error
Battery: 100%
Mode: G1VacuumMode.GlobalClean
Mop State: G1MopState.On
Charge Status: G1ChargeState.FullyCharged
Fan speed: G1FanSpeed.Standard
Water level: G1WaterLevel.Level3
Main Brush Life Level: 100%
Main Brush Life Time: 12 days, 12:00:00
Side Brush Life Level: 100%
Side Brush Life Time: 6 days, 6:00:00
Filter Life Level: 100%
Filter Life Time: 6 days, 6:00:00
Clean Area: 0
Clean Time: 0:00:00

------------------------

Read property for the water level : 
miiocli g1vacuum --ip=192.168.88.24 --token  XXXX get_property_by 2 5

[{'did': '2-5', 'siid': 2, 'piid': 5, 'code': 0, 'value': 3}]

------------------------------

Set the property:

miiocli g1vacuum --ip=192.168.88.24 --token XXXX set_property_by 2 5 3 int

[{'did': 'set-2-5', 'siid': 2, 'piid': 5, 'code': 0}]

-----

Also there are other properties and actions that could be interpreted but that is not the manin case now (like reseting of consumable etc.. ). 

Many thanks

BR,
Radek

---
{"iid":5,"type":"urn:miot-spec-v2:property:target-water-level:00000069:mijia-v1:1","description":"Target Water Level","format":"uint8","access":["read","write","notify"],"unit":"none","value-list":[{"value":1,"description":"Level1"},{"value":2,"description":"Level2"},{"value":3,"description":"Level3"}]}
---

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/507#issuecomment-1107697839

**Comment by radek-kafka** [comment]
Many thanks.. it helps me to add the setting .. Nice and perfect .. (need to learn a lot) ..
