### ISSUE TITLE
zhimi.humidifier.ca1: Unable to discover the device

### ISSUE THREAD

**Issue by soulthiefer** [al-one/hass-xiaomi-miot#541]
stopped working after last update(

Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.xiaomi_miot.humidifier
Source: custom_components/xiaomi_miot/__init__.py:1659
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 21:34:24 (3 occurrences)
Last logged: 21:34:32

Xiaomi_Humidifier(zhimi.humidifier.ca1): Set miot property {'did': 'prop.2.1', 'siid': 2, 'piid': 1, 'value': True} failed: Unable to discover the device 192.168.31.69
Xiaomi_Humidifier(zhimi.humidifier.ca1): Set miot property {'did': 'prop.2.2', 'siid': 2, 'piid': 2, 'value': 0} failed: Unable to discover the device 192.168.31.69

**Comment by al-one** [comment]
Check device IP and network segment.
