### ISSUE TITLE
zhimi.airpurifier.v6: Unable to discover the device

### ISSUE THREAD

**Issue by soulthiefer** [al-one/hass-xiaomi-miot#542]
stopped working after last update(((

Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.xiaomi_miot.core.miio2miot
Source: custom_components/xiaomi_miot/core/miio2miot.py:66
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 21:09:51 (201 occurrences)
Last logged: 21:34:35

zhimi.airpurifier.v6: Got MiioException: Unable to discover the device 192.168.31.29 while get_properties(['power', 'mode', 'humidity', 'filter1_life', 'led', 'buzzer', 'f1_hour_used', 'child_lock', 'aqi', 'temp_dec', 'led_b', 'favorite_level', 'motor1_speed', 'motor2_speed', 'purify_volume'])
zhimi.humidifier.ca1: Got MiioException: Unable to discover the device 192.168.31.69 while get_properties(['power', 'mode', 'humidity', 'temp_dec', 'buzzer', 'child_lock', 'depth'])
chuangmi.plug.m1: Got MiioException: Unable to discover the device 192.168.31.13 while get_properties(['power', 'temperature', 'wifi_led'])

**Comment by al-one** [comment]
> Unable to discover the device 192.168.31.29

Please check it's IP and make sure it in the same subnet as the HA.
