### ISSUE TITLE
Unable to change temperature unit to Fahrenheit

### ISSUE THREAD

**Issue by neebski** [al-one/hass-xiaomi-miot#549]
I have two [cgllc.airm.cgdn1](https://home.miot-spec.com/s/cgllc.airm.cgdn1) and after a recent update they are only reporting in Celsius. I am unable to change the reporting to Fahrenheit. In the mihome app they are reporting in F, only via HA are they reporting C. In the device settings I see there is a unit selection between F, C, K but selecting anything other then C produces no change. 

Any suggestions?

**Comment by msm8811** [comment]
I have the same issue.

**Comment by neebski** [comment]
@msm8811 

I ended up using unit converter in NodeRed and just made a new entity for fahrenheit. Work around for the time being.

**Comment by al-one** [comment]
Fixed in https://github.com/al-one/hass-xiaomi-miot/commit/d5f9dd0b3321bb7ba2a7e50dfc6ce2356b55e59b, please upgrade to master branch.
