### ISSUE TITLE
camera chuangmi.camera.ipc009 motion tracking not enabled

### ISSUE THREAD

**Issue by iamquirarte** [al-one/hass-xiaomi-miot#55]
Hello. A little help needed, how can I enable the motion tracing sensor for this camera? (chuangmi.camera.ipc009) this property camera_control.motion_tracking: false always show false and of course no subentity for motion is created, si tehre any way? Thanks.

**Comment by al-one** [comment]
Motion tracking usually lasts for a short time, but this component queries the state attributes of the device by polling every minute, so it is not suitable to be used as a motion sensor.
