### ISSUE TITLE
yeelink.light.bslamp2 is unavailable on v0.6.0b5

### ISSUE THREAD

**Issue by dronix27** [al-one/hass-xiaomi-miot#550]
yeelink.light.bslamp2 didn't work on v0.6.0b5. Last working version is v0.6.0b3

**Comment by al-one** [comment]
Fixed in [v0.6.0b6](https://github.com/al-one/hass-xiaomi-miot/releases).

**Comment by dronix27** [comment]
> Fixed in [v0.6.0b6](https://github.com/al-one/hass-xiaomi-miot/releases).
Unfortunately, the light object is still unavailable.
