### ISSUE TITLE
viomi.airer.ich108 能否适配支持local模式

### ISSUE THREAD

**Issue by hanley520** [al-one/hass-xiaomi-miot#551]
https://home.miot-spec.com/s/viomi.airer.ich108
云米互联网电动晾衣架Lite 1C属性信息：
current_position: 100
model: viomi.airer.ich108
lan_ip: 192.168.10.224
mac_address: 54:48:E6:xx:xx:xx
entity_class: MiotCoverEntity
miot_type: urn:miot-spec-v2:device:airer:0000A00D:viomi-ich108:1
airer.fault: 0
airer.motor_control.error: '-704030013 Property is not readable'
airer.status: 0
airer.current_position: 1
light.on: false
state_updater: cloud
supported_features: 11

**Comment by al-one** [comment]
请直接尝试使用token集成该设备，如果不可用提供下[日志](https://my.home-assistant.io/redirect/logs)。

**Comment by hanley520** [comment]
通过token集成无报错，使用正常，建议自动模式配置为local模式。
