### ISSUE TITLE
Cleargrass Air and Robot Cleaner do not work via Token

### ISSUE THREAD

**Issue by Sysoev86** [al-one/hass-xiaomi-miot#552]
Today I installed Xiaomi Miot Auto from HACS. Tried version v0.6.0b7 and v0.5.8
 I have four devices from Xiaomi
All devices work with the cloud, but I don't want to work through the cloud.

Through the token, all sensors appeared on only two devices out of four.

Working: Mi Air Purifier 2 and Mi Smart Power Strip
Not working: Cleargrass Air and Robot Cleaner (S51)

What am I doing wrong?

<img width="1073" alt="Снимок экрана 2022-05-01 в 00 17 09" src="https://user-images.githubusercontent.com/57587845/166115659-e41b2e4c-c949-4d23-a430-7c85d38e127e.png">
<img width="1097" alt="Снимок экрана 2022-05-01 в 00 17 16" src="https://user-images.githubusercontent.com/57587845/166115663-513d63bf-018d-49c9-a47a-1c2669b47932.png">
<img width="1108" alt="Снимок экрана 2022-05-01 в 00 17 23" src="https://user-images.githubusercontent.com/57587845/166115665-7abfb44a-ccfd-4a77-832f-a55312178821.png">
<img width="1081" alt="Снимок экрана 2022-05-01 в 00 17 32" src="https://user-images.githubusercontent.com/57587845/166115667-0cfaf34d-87fd-41a5-8aec-1b05099bf377.png">
<img width="285" alt="Снимок экрана 2022-05-01 в 00 17 40" src="https://user-images.githubusercontent.com/57587845/166115669-5bfbf3ea-09eb-413d-a71a-beafb3ec5d75.png">

**Comment by Sysoev86** [comment]
<img width="1472" alt="Снимок экрана 2022-05-01 в 00 38 34" src="https://user-images.githubusercontent.com/57587845/166116355-84a12505-56da-4e23-ae0b-187b076c7ae8.png">
<img width="1473" alt="Снимок экрана 2022-05-01 в 00 38 40" src="https://user-images.githubusercontent.com/57587845/166116358-8c968c4c-e166-4492-b7cc-afc03256fdda.png">

**Comment by al-one** [comment]
Try master branch for [roborock.vacuum.s5](https://home.miot-spec.com/s/roborock.vacuum.s5).

**Comment by Sysoev86** [comment]
> Try master branch for [roborock.vacuum.s5](https://home.miot-spec.com/s/roborock.vacuum.s5).

Thanks, I'll give it a try. But I don't care as much about the vacuum cleaner as I do about Cleargrass Air, which controls all the ventilation in the house
What can you advise to make Cleargrass Air work?

**Comment by Sysoev86** [comment]
> Try master branch for [roborock.vacuum.s5](https://home.miot-spec.com/s/roborock.vacuum.s5).

same error

**Comment by Sysoev86** [comment]
It's work! Thank you
I think there's a percentage unit missing from the humidity?!
<img width="1077" alt="Снимок экрана 2022-05-05 в 17 52 52" src="https://user-images.githubusercontent.com/57587845/166909250-104e62ec-eb15-4d59-bda5-513273538556.png">

**Comment by al-one** [comment]
> I think there's a percentage unit missing from the humidity?!

Fixed in https://github.com/al-one/hass-xiaomi-miot/commit/b91664846af6cfcaf00f98b6296fdefa30c10d1c
