### ISSUE TITLE
After the last update (0.6.1), the dayang.mosq.dyt16s mosquito repellent lamp stopped working.

### ISSUE THREAD

**Issue by VikeDragon** [al-one/hass-xiaomi-miot#557]
Greetings!
After the last update (0.6.1), the dayang.mosq.dyt16s mosquito repellent lamp 
(https://home.miot-spec.com/s/dayang.mosq.dyt16s) 
stopped working. Previously there were such messages, but it turned on and off.
From Mi Home works correctly (dayang.mosq.dyt16s update version 2.2.1).
I see messages in the log:
2022-05-02 11:27:50 ERROR (MainThread) [custom_components.xiaomi_miot.switch] dayang.mosq.dyt16s(dayang.mosq.dyt16s): Got MiioException while fetching the state: Unable to parse message payload, mapping: {'mosquito_dispeller.on': {'siid': 2, 'piid': 1}, 'mosquito_dispeller.mode': {'siid': 2, 'piid': 3}, 'custom.timer': {'siid': 3, 'piid': 1}, 'custom.count_down': {'siid': 3, 'piid': 2}}, max_properties: 7/4

**Comment by al-one** [comment]
Please try to rebind it in MiHome APP.

**Comment by VikeDragon** [comment]
Greetings!
Reconnected and tested.
When Wifi disappears for more than 2 minutes, such a violation occurs with all devices that are connected through integration. There is also a message in the notification about the violation of communication with devices. I have a router reboot set up at 00:00, and after the reboot, which ends at 00:03, such notifications come and there is a breakdown in communication with the devices, after a while the connection with the devices returns to normal.  Previously, this behavior was not observed and the devices did not fall off even while the router was rebooting.
Is there any way to disable notifications, or set, or can increase the interval of unavailability of devices?

**Comment by al-one** [comment]
Improved in https://github.com/al-one/hass-xiaomi-miot/commit/05c07b4575309a99c32b30ba141d35dc54c582f5, notification will be removed after all offline devices are restored.

**Comment by VikeDragon** [comment]
Thank you for your help in solving the problem!
I am waiting for the release of a new version of the integration.

**Comment by VikeDragon** [comment]
Thank you!
