### ISSUE TITLE
Viomi V5 Pro error (in error log)

### ISSUE THREAD

**Issue by galamarco** [al-one/hass-xiaomi-miot#560]
Hello,
I want report this error in error log:

```
Logger: custom_components.xiaomi_miot.vacuum
Source: custom_components/xiaomi_miot/__init__.py:1458
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 08:30:18 (115 occurrences)
Last logged: 10:24:26

Viomi V5 Pro(viomi.vacuum.v38): Got miio properties ['run_state', 'mode', 'err_state', 'battary_life', 'box_type', 'mop_type', 's_time', 's_area', 'suction_grade', 'water_grade', 'remember_map', 'has_map', 'is_mop', 'has_newmap'] failed: {'code': -9999, 'message': 'user ack timeout'}
```

The card don't show some information about filter, brush, sensor:
![image](https://www.webg.it/images/articoli/2022-05/Screenshot_41.png)

System information:
Home Assistant 2022.4.7
Version: core-2022.4.7
Xiaomi Miot Auto 47.87

Best regards
Marco

**Comment by al-one** [comment]
Fixed in https://github.com/al-one/hass-xiaomi-miot/commit/2ffa2efac974cb56c4622ad8b5e06b4f0a8e222f, please upgrade to master branch.
