### ISSUE TITLE
请问新版怎样获取扫地机器人的滤芯使用时间？

### ISSUE THREAD

**Issue by Leeeooooo** [al-one/hass-xiaomi-miot#561]
之前版本中我使用`state_attr('vacuum.roborock_a11_xxx_robot_cleaner', 'consumables').xxx_work_time`来获取时间的，新版本中vacuunm实体下不再包含consumables这个属性了，请问如何获取使用时间？

**Comment by al-one** [comment]
已适配[`roborock.vacuum.a11`](https://home.miot-spec.com/s/roborock.vacuum.a11)本地接入，请更新至master体验。另外耗材属性有变动，请通过开发者工具观察。
