### ISSUE TITLE
配置小米账户时 提示 无法访问小米API接口

### ISSUE THREAD

**Issue by whoseyy** [al-one/hass-xiaomi-miot#562]
配置小米账户
⚠️ HTTPSConnectionPool(host='miot-spec.org', port=443): Max retries exceeded with url: /miot-spec-v2/instances?status=all (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fced076a2e0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

无法访问小米API接口

求助，谢谢Thanks♪(･ω･)ﾉ

**Comment by al-one** [comment]
宿主机或路由器DNS问题：
- #500

**Comment by whoseyy** [comment]
> 

非常感谢！Thanks♪(･ω･)ﾉ
