### ISSUE TITLE
Two zhimi.airp.rmb1 , But only 1 Device get ALl Sesnors, Another one loss many , how to solve this problem

### ISSUE THREAD

**Issue by blackmeat1225** [al-one/hass-xiaomi-miot#566]
Two zhimi.airp.rmb1 , But only 1 Device get ALl Sesnors, Another one loss many , how to solve this problem, Thanks
![xiaomi Smart Air Purifier 4 Lite_ALL](https://user-images.githubusercontent.com/56983945/166622008-d0733abb-cb51-48f5-bc99-81ba4ab68a55.JPG)
![xiaomi Smart Air Purifier 4 Lite](https://user-images.githubusercontent.com/56983945/166622023-57df1822-2583-4e99-923d-9de540ae3d28.JPG)
![xiaomi Smart Air Purifier 4 Lite2](https://user-images.githubusercontent.com/56983945/166622031-43a734f7-936e-4b89-81ea-d80daeeabc28.JPG)

**Comment by al-one** [comment]
Any error/warning [logs](https://my.home-assistant.io/redirect/logs) ?

**Comment by blackmeat1225** [comment]
The Same Device & Net：only 1 Devicce OK？
Error Log：
自行安裝整合產生錯誤。

Logger: custom_components.xiaomi_miot.fan
Source: custom_components/xiaomi_miot/__init__.py:1242
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 08:44:04 (476 occurrences)
Last logged: 18:39:13

Xiaomi Smart Air Purifier 4 Lite(zhimi.airp.rmb1): Got MiioException while fetching the state: No response from the device, mapping: {'air_purifier.on': {'siid': 2, 'piid': 1}, 'air_purifier.fault': {'siid': 2, 'piid': 2}, 'air_purifier.mode': {'siid': 2, 'piid': 4}, 'aqi.aqi_updata_heartbeat': {'siid': 11, 'piid': 4}, 'custom_service.moto_speed_rpm': {'siid': 9, 'piid': 1}, 'custom_service.country_code': {'siid': 9, 'piid': 10}, 'custom_service.favorite_level': {'siid': 9, 'piid': 11}, 'temperature_display_unit-14-1': {'siid': 14, 'piid': 1}, 'screen.brightness': {'siid': 13, 'piid': 2}, 'physical_controls_locked': {'siid': 8, 'piid': 1}, 'alarm': {'siid': 6, 'piid': 1}, 'filter.filter_life_level': {'siid': 4, 'piid': 1}, 'filter.filter_used_time': {'siid': 4, 'piid': 3}, 'filter.filter_left_time': {'siid': 4, 'piid': 4}, 'environment.relative_humidity': {'siid': 3, 'piid': 1}, 'environment.pm2_5_density': {'siid': 3, 'piid': 4}, 'environment.temperature': {'siid': 3, 'piid': 7}}, max_properties: 9/17
Xiaomi Smart Air Purifier 4 Pro(zhimi.airp.vb4): Got MiioException while fetching the state: Unable to discover the device 192.168.31.109, mapping: {'air_purifier.on': {'siid': 2, 'piid': 1}, 'air_purifier.fault': {'siid': 2, 'piid': 2}, 'air_purifier.mode': {'siid': 2, 'piid': 4}, 'air_purifier.fan_level': {'siid': 2, 'piid': 5}, 'air_purifier.anion': {'siid': 2, 'piid': 6}, 'rfid.rfid_tag': {'siid': 12, 'piid': 1}, 'rfid.rfid_factory_id': {'siid': 12, 'piid': 2}, 'rfid.rfid_product_id': {'siid': 12, 'piid': 3}, 'rfid.rfid_time': {'siid': 12, 'piid': 4}, 'rfid.rfid_serial_num': {'siid': 12, 'piid': 5}, 'aqi.purify_volume': {'siid': 11, 'piid': 1}, 'aqi.average_aqi': {'siid': 11, 'piid': 2}, 'aqi.aqi_state': {'siid': 11, 'piid': 3}, 'aqi.aqi_updata_heartbeat': {'siid': 11, 'piid': 4}, 'filter_time.filter_used_debug': {'siid': 10, 'piid': 1}, 'custom_service.moto_speed_rpm': {'siid': 9, 'piid': 1}, 'custom_service.favorite_speed': {'siid': 9, 'piid': 2}, 'custom_service.motor_set_speed': {'siid': 9, 'piid': 4}, 'custom_service.favorite_level': {'siid': 9, 'piid': 5}, 'custom_service.buttom_door': {'siid': 9, 'piid': 6}, 'custom_service.reboot_cause': {'siid': 9, 'piid': 8}, 'custom_service.manual_level': {'siid': 9, 'piid': 9}, 'custom_service.country_code': {'siid': 9, 'piid': 10}, 'temperature_display_unit-14-1': {'siid': 14, 'piid': 1}, 'screen.brightness': {'siid': 13, 'piid': 2}, 'physical_controls_locked': {'siid': 8, 'piid': 1}, 'alarm': {'siid': 6, 'piid': 1}, 'filter.filter_life_level': {'siid': 4, 'piid': 1}, 'filter.filter_used_time': {'siid': 4, 'piid': 3}, 'filter.filter_left_time': {'siid': 4, 'piid': 4}, 'environment.relative_humidity': {'siid': 3, 'piid': 1}, 'environment.pm2_5_density': {'siid': 3, 'piid': 4}, 'environment.temperature': {'siid': 3, 'piid': 7}, 'environment.pm10_density': {'siid': 3, 'piid': 8}}, max_properties: 7/34
Xiaomi Smart Air Purifier 4 Lite2(zhimi.airp.rmb1): Got MiioException while fetching the state: Unable to discover the device 192.168.31.252, mapping: {'air_purifier.on': {'siid': 2, 'piid': 1}, 'air_purifier.fault': {'siid': 2, 'piid': 2}, 'air_purifier.mode': {'siid': 2, 'piid': 4}, 'aqi.aqi_updata_heartbeat': {'siid': 11, 'piid': 4}, 'custom_service.moto_speed_rpm': {'siid': 9, 'piid': 1}, 'custom_service.country_code': {'siid': 9, 'piid': 10}, 'custom_service.favorite_level': {'siid': 9, 'piid': 11}, 'temperature_display_unit-14-1': {'siid': 14, 'piid': 1}, 'screen.brightness': {'siid': 13, 'piid': 2}, 'physical_controls_locked': {'siid': 8, 'piid': 1}, 'alarm': {'siid': 6, 'piid': 1}, 'filter.filter_life_level': {'siid': 4, 'piid': 1}, 'filter.filter_used_time': {'siid': 4, 'piid': 3}, 'filter.filter_left_time': {'siid': 4, 'piid': 4}, 'environment.relative_humidity': {'siid': 3, 'piid': 1}, 'environment.pm2_5_density': {'siid': 3, 'piid': 4}, 'environment.temperature': {'siid': 3, 'piid': 7}}, max_properties: 9/17
Xiaomi Smart Air Purifier 4 Lite(zhimi.airp.rmb1): Got MiioException while fetching the state: Unable to discover the device 192.168.31.135, mapping: {'air_purifier.on': {'siid': 2, 'piid': 1}, 'air_purifier.fault': {'siid': 2, 'piid': 2}, 'air_purifier.mode': {'siid': 2, 'piid': 4}, 'aqi.aqi_updata_heartbeat': {'siid': 11, 'piid': 4}, 'custom_service.moto_speed_rpm': {'siid': 9, 'piid': 1}, 'custom_service.country_code': {'siid': 9, 'piid': 10}, 'custom_service.favorite_level': {'siid': 9, 'piid': 11}, 'temperature_display_unit-14-1': {'siid': 14, 'piid': 1}, 'screen.brightness': {'siid': 13, 'piid': 2}, 'physical_controls_locked': {'siid': 8, 'piid': 1}, 'alarm': {'siid': 6, 'piid': 1}, 'filter.filter_life_level': {'siid': 4, 'piid': 1}, 'filter.filter_used_time': {'siid': 4, 'piid': 3}, 'filter.filter_left_time': {'siid': 4, 'piid': 4}, 'environment.relative_humidity': {'siid': 3, 'piid': 1}, 'environment.pm2_5_density': {'siid': 3, 'piid': 4}, 'environment.temperature': {'siid': 3, 'piid': 7}}, max_properties: 9/17
Xiaomi Smart Air Purifier 4 Lite2(zhimi.airp.rmb1): Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'air_purifier.on': {'siid': 2, 'piid': 1}, 'air_purifier.fault': {'siid': 2, 'piid': 2}, 'air_purifier.mode': {'siid': 2, 'piid': 4}, 'aqi.aqi_updata_heartbeat': {'siid': 11, 'piid': 4}, 'custom_service.moto_speed_rpm': {'siid': 9, 'piid': 1}, 'custom_service.country_code': {'siid': 9, 'piid': 10}, 'custom_service.favorite_level': {'siid': 9, 'piid': 11}, 'temperature_display_unit-14-1': {'siid': 14, 'piid': 1}, 'screen.brightness': {'siid': 13, 'piid': 2}, 'physical_controls_locked': {'siid': 8, 'piid': 1}, 'alarm': {'siid': 6, 'piid': 1}, 'filter.filter_life_level': {'siid': 4, 'piid': 1}, 'filter.filter_used_time': {'siid': 4, 'piid': 3}, 'filter.filter_left_time': {'siid': 4, 'piid': 4}, 'environment.relative_humidity': {'siid': 3, 'piid': 1}, 'environment.pm2_5_density': {'siid': 3, 'piid': 4}, 'environment.temperature': {'siid': 3, 'piid': 7}}, max_properties: 9/17

**Comment by blackmeat1225** [comment]
I restart HA. and get the log  as below, 3 Devcie on MIJA App is normal
Waring 1:
自行安裝整合產生錯誤。
Logger: custom_components.xiaomi_miot.climate
Source: custom_components/xiaomi_miot/climate.py:178
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 18:46:44 (2 occurrences)
Last logged: 18:46:45

climate.zhimi_rmb1_5d34_air_purifier has been deprecated and will be removed in a future version. Please use fan.zhimi_rmb1_5d34_air_purifier.
climate.zhimi_vb4_a26a_air_purifier has been deprecated and will be removed in a future version. Please use fan.zhimi_vb4_a26a_air_purifier.
Warning 2
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:745
First occurred: 18:48:29 (1 occurrences)
Last logged: 18:48:29

Update of fan.zhimi_rmb1_5d34_air_purifier is taking over 10 seconds

Error1
自行安裝整合產生錯誤。

Logger: custom_components.xiaomi_miot.fan
Source: custom_components/xiaomi_miot/__init__.py:1242
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 18:49:29 (1 occurrences)
Last logged: 18:49:29

Xiaomi Smart Air Purifier 4 Lite2(zhimi.airp.rmb1): Got MiioException while fetching the state: Unable to discover the device 192.168.31.252, mapping: {'air_purifier.on': {'siid': 2, 'piid': 1}, 'air_purifier.fault': {'siid': 2, 'piid': 2}, 'air_purifier.mode': {'siid': 2, 'piid': 4}, 'aqi.aqi_updata_heartbeat': {'siid': 11, 'piid': 4}, 'custom_service.moto_speed_rpm': {'siid': 9, 'piid': 1}, 'custom_service.country_code': {'siid': 9, 'piid': 10}, 'custom_service.favorite_level': {'siid': 9, 'piid': 11}, 'temperature_display_unit-14-1': {'siid': 14, 'piid': 1}, 'screen.brightness': {'siid': 13, 'piid': 2}, 'physical_controls_locked': {'siid': 8, 'piid': 1}, 'alarm': {'siid': 6, 'piid': 1}, 'filter.filter_life_level': {'siid': 4, 'piid': 1}, 'filter.filter_used_time': {'siid': 4, 'piid': 3}, 'filter.filter_left_time': {'siid': 4, 'piid': 4}, 'environment.relative_humidity': {'siid': 3, 'piid': 1}, 'environment.pm2_5_density': {'siid': 3, 'piid': 4}, 'environment.temperature': {'siid': 3, 'piid': 7}}, max_properties: 9/17

**Comment by blackmeat1225** [comment]
i update to latest version, this issue be solved,
