### ISSUE TITLE
藍牙溫溼度計的溫度實體缺乏計量單位

### ISSUE THREAD

**Issue by delphicchen** [al-one/hass-xiaomi-miot#567]
近期更新後，小米藍牙溫濕度計的實體中濕度顯示正常，帶有單位。
但是溫度部分則不帶單位，僅能顯示數值
是否為缺少設置unit_of_measurement所致?

**Comment by delphicchen** [comment]
我這邊的溫濕度計型號是
cleargrass.sensor_ht.dk1
miaomiaoce.sensor_ht.t2

有關溫度的實體 (sensor.cleargrass_dk1_67f0_temperature_humidity_sensor)屬性為
model: cleargrass.sensor_ht.dk1
lan_ip: 
mac_address: ****************
entity_class: MiotSensorEntity
home_room: *************的家 客廳
miot_type: urn:miot-spec-v2:device:temperature-humidity-sensor:0000A00A:cleargrass-dk1:1
state_property: temperature-2-1
temperature-2-1: 26.4
relative_humidity-2-2: 72.5
battery.battery_level: 58
state_updater: cloud
sub_entities: battery-3.battery_level-1, temperature_humidity_sensor-2.relative_humidity-2
device_class: temperature
friendly_name: 客廳藍牙溫濕度計 Temperature Humidity Sensor
supported_features: 0

有關濕度的實體(sensor.cleargrass_dk1_67f0_relative_humidity)屬性為
entity_class: MiotSensorSubEntity
parent_entity_id: sensor.cleargrass_dk1_67f0_temperature_humidity_sensor
service_description: Temperature Humidity Sensor
property_description: Relative Humidity
relative_humidity-2-2: 72.6
battery.battery_level: 58
unit_of_measurement: %
device_class: humidity
friendly_name: 客廳藍牙溫濕度計 Temperature Humidity Sensor Relative
supported_features: 0


非常感謝大神的幫忙！

**Comment by al-one** [comment]
已修复，请更新到master分支。
