### ISSUE TITLE
lumi.weather.v1 小米温湿度传感器，温度缺少单位。

### ISSUE THREAD

**Issue by befantasy** [al-one/hass-xiaomi-miot#569]
![image](https://user-images.githubusercontent.com/31535803/166854950-259255e6-b698-4f08-8d40-dcc0cd2fb3a3.png)

如图，湿度和气压的sensor属性里都有unit_of_measurement，但是温度的没有，之前好像也没什么问题。
但是今天更新了2022.5，别的实体在调用这个sensor的时候报错了，提示没有单位。

**Comment by al-one** [comment]
已修复，请更新到master分支。

**Comment by befantasy** [comment]
谢谢，真是效率。
更新了一下试了试，有个新问题，现在温度是F，不知道怎么切换C。

**Comment by befantasy** [comment]
单位是F，但是实际上数值是C的数值。
