### ISSUE TITLE
Support additional server countries - Australia

### ISSUE THREAD

**Issue by barnabyjones** [al-one/hass-xiaomi-miot#57]
Thank you for your amazing work on this! 

Would it be possible to support Xiaomi Mi server countries beyond cn(default), de, i2, ru, sg, us? 

Most of my devices are on the cn server, however my Roborock vacuum is on the Australia server. It would be great to be able to add it to HA using this integration.

**Comment by al-one** [comment]
Do you know the Australian country code for xiaomi server, is `au` ?

**Comment by barnabyjones** [comment]
I guessed it would be :) The front end for the integration didn't have it as an option, so wasn't sure if it would be supported. 

Will the integration support devices from multiple servers (in my case au and cn) concurrently? i.e. If I set my server to au in config.yaml will the integration still support all of my devices from the cn server?

**Comment by al-one** [comment]
Multiple servers are not supported in one integrated config entry.
Configure the `server_country` in yaml only for `Add device using host/token`, which you can do and check the file: `.storage/xiaomi_miot/devices-xxxx.json`.

**Comment by al-one** [comment]
Xiaomi cloud may not have a server in Australia, because [`au.api.io.mi.com`](http://au.api.io.mi.com) cannot be accessed.

**Comment by Supreme-Bob** [comment]
australian server actually uses the 'sg' singapore server

**Comment by al-one** [comment]
See https://www.openhab.org/addons/bindings/miio/#country-servers
