### ISSUE TITLE
在以“账号集成”方式添加集成后，无法通过选项更改配置的密码

### ISSUE THREAD

**Issue by keniji** [al-one/hass-xiaomi-miot#571]
我会隔一段时间就改一次小米帐号的密码，我刚发现之前以“帐号集成”添加的小米账号，在集成的“选项”中，填入新的密码后按“提交”，实际提交的还是之前旧的密码，因而会出现登陆失败的报错。现在的workaround是删掉集成重新添加，但是我重命名的实例在重新添加集成后又变成了初始化后的名称，请问这个有解决办法吗？感谢！
![image](https://user-images.githubusercontent.com/42759206/167092508-ee9116aa-2d93-44f3-875b-ca9cdbff0e64.png)

**Comment by al-one** [comment]
已在 https://github.com/al-one/hass-xiaomi-miot/commit/258e268d9e7181267fc8fee051d0da285439bef2 修复，请更新至master分支

**Comment by keniji** [comment]
> 已在 [258e268](https://github.com/al-one/hass-xiaomi-miot/commit/258e268d9e7181267fc8fee051d0da285439bef2) 修复，请更新至master分支

感谢感谢, 大佬棒棒哒~
