### ISSUE TITLE
qushui.bed.001 working only Bed Motor Control, that turns both sides at the same time only

### ISSUE THREAD

**Issue by fixss** [al-one/hass-xiaomi-miot#572]
[qushui.bed.001](https://home.miot-spec.com/s/qushui.bed.001) have some problems, because only one function works, that turns both sides at the same time only. All others tells that they are Unavailable.

Logger: custom_components.xiaomi_miot.sensor
Source: custom_components/xiaomi_miot/__init__.py:1269
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 12:59:47 AM (1 occurrences)
Last logged: 12:59:47 AM

Bed(qushui.bed.001): Got MiioException while fetching the state: Unable to discover the device 192.168.31.208, mapping:
```python
{'bed.fault': {'siid': 2, 'piid': 1},
'bed.mode': {'siid': 2, 'piid': 4},
'bed.motor_control': {'siid': 2, 'piid': 5},
'physical_controls_locked': {'siid': 5, 'piid': 1},
'leg_rest_control.leg_rest_angle': {'siid': 4, 'piid': 1},
'backrest_control.backrest_angle': {'siid': 3, 'piid': 1}
}, max_properties: 8/6
```

**Comment by fixss** [comment]
Yes of course  the device IP is correct and in the same subnet as HA.

**Comment by fixss** [comment]
`cover.qushui_001_3a7f_backrest_angle
Bed Backrest Control Angle

unavailable	

friendly_name: Bed Backrest Control Angle
supported_features: 7


cover.qushui_001_3a7f_leg_rest_angle
Bed Leg Rest Control Angle

unavailable	

friendly_name: Bed Leg Rest Control Angle
supported_features: 7


cover.qushui_001_3a7f_motor_control
Bed Bed Motor Control

unknown	

entity_class: MiotCoverSubEntity
parent_entity_id: sensor.qushui_001_3a7f_bed
service_description: Bed
property_description: Motor Control
bed.motor_control: 2
friendly_name: Bed Bed Motor Control
supported_features: 11


fan.qushui_001_3a7f_mode
Bed Bed Mode

unavailable	

preset_modes: None, Reading, Zero Gravity, Anti-snoring, Tv, Lie Flat
icon: mdi:menu
friendly_name: Bed Bed Mode
supported_features: 8

sensor.qushui_001_3a7f_bed
Bed Bed Device Fault

no faults	

model: qushui.bed.001
lan_ip: 192.168.31.208
mac_address: 54:48:E6:6E:3A:7F
entity_class: MiotSensorEntity
miot_type: urn:miot-spec-v2:device:bed:0000A06A:qushui-001:1
state_property: bed.fault
bed.fault: 0
bed.mode.error: -4004 Other internal errors
bed.motor_control.error: -4004 Other internal errors
physical_controls_locked.error: -4004 Other internal errors
leg_rest_control.leg_rest_angle.error: -4004 Other internal errors
backrest_control.backrest_angle.error: -4004 Other internal errors
state_updater: lan
sub_entities: physical_controls_locked-5.physical_controls_locked-1, bed-2.mode-4, bed-2.motor_control-5, backrest_control-3.backrest_angle-1, leg_rest_control-4.leg_rest_angle-1
bed.fault_desc: No Faults
bed.motor_control: 2
friendly_name: Bed Bed Device Fault
supported_features: 0

switch.qushui_001_3a7f_physical_control_locked
Bed Physical Control Locked

unavailable	

friendly_name: Bed Physical Control Locked
supported_features: 0`

**Comment by al-one** [comment]
`-4004 Other internal errors` is from the device, try adding custom option `chunk_properties: 1`.
- #600
![xiaomi miot chunk_properties](https://user-images.githubusercontent.com/4549099/172757218-21085124-1dc2-4293-9a66-b7a082da8bde.png)

**Comment by fixss** [comment]
Yes, that fixed problem. Thanks
