### ISSUE TITLE
艾美特的电扇实体不会更新数据，只会更新开关状态，但能控制

### ISSUE THREAD

**Issue by xiaoluozhou** [al-one/hass-xiaomi-miot#575]
[air.fan.ca23ad9](https://home.miot-spec.com/s/air.fan.ca23ad9) 相关属性是：
preset_modes: Basic, Baby Care
oscillating: null
percentage: null
percentage_step: 3
preset_mode: null
model: air.fan.ca23ad9
lan_ip: 
mac_address: 
entity_class: MiotFanEntity
home_room: 客厅
miot_type: urn:miot-spec-v2:device:fan:0000A005:air-ca23ad9:1
fan.on.error: -704030013 Property is not readable
fan.fan_level.error: -704030013 Property is not readable
fan.horizontal_swing.error: -704030013 Property is not readable
fan.vertical_swing.error: -704030013 Property is not readable
fan.mode.error: -704030013 Property is not readable
state_updater: cloud
fan.on: true
friendly_name: 客厅风扇 Fan
supported_features: 11

对应的状态都不能更新，手动更新也不会，但调用对应服务是有效果的。很奇怪，日志也没有任何报错

**Comment by al-one** [comment]
请更新到master分支后尝试。
