### ISSUE TITLE
"The device model is not known, not able to setup the device using config flow."

### ISSUE THREAD

**Issue by 833M0L3** [al-one/hass-xiaomi-miot#576]
So I added the xiaomi_miot to custom_components, inside my Home Assistant config folder. I got the Xiaomi Miot option on the Add Integration page of Home Assistant. I entered the correct credentials and after that, it shows **"The device model is not known, not able to set up the device using config flow."** dialogue box. I checked the options but my **Mi Home Security Camera 360 i.e chuangmi.camera.ipc019**  , https://home.miot-spec.com/spec?type=urn%3Amiot-spec-v2%3Adevice%3Acamera%3A0000A01C%3Achuangmi-ipc019%3A1 is not there.

![image](https://user-images.githubusercontent.com/59522309/167290011-290c1e73-cfe2-4980-9d02-becdb9ff40e7.png)

How to integrate this device?

**Comment by al-one** [comment]
This screenshot is not this component, please click: [![Xiaomi Miot Auto](https://my.home-assistant.io/badges/config_flow_start.svg)](https://my.home-assistant.io/redirect/config_flow_start/?domain=xiaomi_miot)

**Comment by mfuhrmann** [comment]
I get exactly the same error with the [Yeelight RGB bulbs](https://home.mi.com/webapp/content/baike/product/index.html?model=yeelink.light.color1).
![image](https://user-images.githubusercontent.com/4995222/218254898-7129016c-ac96-4fae-a552-66d929b18f08.png)


The [vacuum cleaner](https://home.mi.com/webapp/content/baike/product/index.html?model=roborock.vacuum.m1s#/), [night light](https://home.mi.com/webapp/content/baike/product/index.html?model=yeelink.light.bslamp3#/) and the [fan](https://home.mi.com/webapp/content/baike/product/index.html?model=zhimi.fan.za5#/) worked perfectly.

Interestingly, I have to choose the `de` servers to see both lights in this view:
![Screenshot from 2023-02-11 12-07-11](https://user-images.githubusercontent.com/4995222/218254812-904580bd-b826-4cd2-92eb-e8dd00f5ab22.png)
All other Xiaomi devices are located in `cn`. I didn't know that a mix is possible. The Xiaomi home app tells me I am in `cn` with `de` language.

**Comment by al-one** [comment]
@mfuhrmann  Not this component !
