### ISSUE TITLE
air.fan.ca23ad9: -704030013 Property is not readable

### ISSUE THREAD

**Issue by Nugu-web** [al-one/hass-xiaomi-miot#578]
[air.fan.ca23ad9](https://home.miot-spec.com/s/air.fan.ca23ad9)
```
preset_modes:
  - Basic
  - Baby Care
oscillating: null
percentage: null
percentage_step: 3
preset_mode: null
model: air.fan.ca23ad9
lan_ip: ***.***.***.***
mac_address: **:**:**:**:**:**
entity_class: MiotFanEntity
miot_type: urn:miot-spec-v2:device:fan:0000A005:air-ca23ad9:1
fan.on.error: '-704030013 Property is not readable'
fan.fan_level.error: '-704030013 Property is not readable'
fan.horizontal_swing.error: '-704030013 Property is not readable'
fan.vertical_swing.error: '-704030013 Property is not readable'
fan.mode.error: '-704030013 Property is not readable'
state_updater: cloud
friendly_name: Air Fan
supported_features: 11
```

**Comment by al-one** [comment]
Upgrade to master branch and try.

**Comment by Nugu-web** [comment]
It connects normally.
However, no matter what operation is performed, the Off signal is transmitted and 'air.fan.ca23ad9' is turned off.

preset_modes:
  - Basic
  - Baby Care
oscillating: false
percentage: null
percentage_step: 3
preset_mode: Basic
model: air.fan.ca23ad9
lan_ip: ***.***.***.***
mac_address: **:**:**:**:**:**
entity_class: MiotFanEntity
miot_type: urn:miot-spec-v2:device:fan:0000A005:air-ca23ad9:1
fan.on: false
fan.fan_level: 10
fan.horizontal_swing: false
fan.vertical_swing: true
fan.mode: 1
state_updater: lan
friendly_name: Air Fan
supported_features: 11

**Comment by al-one** [comment]
Try master branch again.
