### ISSUE TITLE
小米空气净化器3频繁掉线

### ISSUE THREAD

**Issue by Leeeooooo** [al-one/hass-xiaomi-miot#579]
平均一天出现300次左右的报错，但是大部分时候设备是正常的，在米家或者HA或者HK里都能正常操作。
下面是错误日志，请查看。

[`zhimi.airpurifier.ma4`](https://home.miot-spec.com/s/zhimi.airpurifier.ma4)

此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.fan
Source: custom_components/xiaomi_miot/__init__.py:1269 
Integration: Xiaomi Miot Auto (documentation, issues) 
First occurred: 2022年5月8日 01:39:02 (601 occurrences) 
Last logged: 19:18:40

空气净化器(zhimi.airpurifier.ma4): Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'air_purifier.fault': {'siid': 2, 'piid': 1}, 'air_purifier.on': {'siid': 2, 'piid': 2}, 'air_purifier.fan_level': {'siid': 2, 'piid': 4}, 'air_purifier.mode': {'siid': 2, 'piid': 5}, 'aqi.purify_volume': {'siid': 13, 'piid': 1}, 'aqi.average_aqi': {'siid': 13, 'piid': 2}, 'aqi.average_aqi_cnt': {'siid': 13, 'piid': 3}, 'aqi.aqi_zone': {'siid': 13, 'piid': 4}, 'aqi.sensor_state': {'siid': 13, 'piid': 5}, 'aqi.aqi_goodh': {'siid': 13, 'piid': 6}, 'aqi.aqi_runstate': {'siid': 13, 'piid': 7}, 'aqi.aqi_state': {'siid': 13, 'piid': 8}, 'aqi.aqi_updata_heartbeat': {'siid': 13, 'piid': 9}, 'filter_time.filter_max_time': {'siid': 9, 'piid': 1}, 'filter_hour_used_debug-9-2': {'siid': 9, 'piid': 2}, 'physical_controls_locked': {'siid': 7, 'piid': 1}, 'indicator_light.brightness': {'siid': 6, 'piid': 1}, 'indicator_light.on': {'siid': 6, 'piid': 6}, 'alarm': {'siid': 5, 'piid': 1}, 'filter.filter_life_level': {'siid': 4, 'piid': 3}, 'filter.filter_used_time': {'siid': 4, 'piid': 5}, 'environment.pm2_5_density': {'siid': 3, 'piid': 6}, 'environment.relative_humidity': {'siid': 3, 'piid': 7}, 'environment.temperature': {'siid': 3, 'piid': 8}}, max_properties: 8/24
空气净化器(zhimi.airpurifier.ma4): Got MiioException while fetching the state: Unable to discover the device 192.168.123.238, mapping: {'air_purifier.fault': {'siid': 2, 'piid': 1}, 'air_purifier.on': {'siid': 2, 'piid': 2}, 'air_purifier.fan_level': {'siid': 2, 'piid': 4}, 'air_purifier.mode': {'siid': 2, 'piid': 5}, 'aqi.purify_volume': {'siid': 13, 'piid': 1}, 'aqi.average_aqi': {'siid': 13, 'piid': 2}, 'aqi.average_aqi_cnt': {'siid': 13, 'piid': 3}, 'aqi.aqi_zone': {'siid': 13, 'piid': 4}, 'aqi.sensor_state': {'siid': 13, 'piid': 5}, 'aqi.aqi_goodh': {'siid': 13, 'piid': 6}, 'aqi.aqi_runstate': {'siid': 13, 'piid': 7}, 'aqi.aqi_state': {'siid': 13, 'piid': 8}, 'aqi.aqi_updata_heartbeat': {'siid': 13, 'piid': 9}, 'filter_time.filter_max_time': {'siid': 9, 'piid': 1}, 'filter_hour_used_debug-9-2': {'siid': 9, 'piid': 2}, 'physical_controls_locked': {'siid': 7, 'piid': 1}, 'indicator_light.brightness': {'siid': 6, 'piid': 1}, 'indicator_light.on': {'siid': 6, 'piid': 6}, 'alarm': {'siid': 5, 'piid': 1}, 'filter.filter_life_level': {'siid': 4, 'piid': 3}, 'filter.filter_used_time': {'siid': 4, 'piid': 5}, 'environment.pm2_5_density': {'siid': 3, 'piid': 6}, 'environment.relative_humidity': {'siid': 3, 'piid': 7}, 'environment.temperature': {'siid': 3, 'piid': 8}}, max_properties: 8/24
空气净化器(zhimi.airpurifier.ma4): Got MiioException while fetching the state: No response from the device, mapping: {'air_purifier.fault': {'siid': 2, 'piid': 1}, 'air_purifier.on': {'siid': 2, 'piid': 2}, 'air_purifier.fan_level': {'siid': 2, 'piid': 4}, 'air_purifier.mode': {'siid': 2, 'piid': 5}, 'aqi.purify_volume': {'siid': 13, 'piid': 1}, 'aqi.average_aqi': {'siid': 13, 'piid': 2}, 'aqi.average_aqi_cnt': {'siid': 13, 'piid': 3}, 'aqi.aqi_zone': {'siid': 13, 'piid': 4}, 'aqi.sensor_state': {'siid': 13, 'piid': 5}, 'aqi.aqi_goodh': {'siid': 13, 'piid': 6}, 'aqi.aqi_runstate': {'siid': 13, 'piid': 7}, 'aqi.aqi_state': {'siid': 13, 'piid': 8}, 'aqi.aqi_updata_heartbeat': {'siid': 13, 'piid': 9}, 'filter_time.filter_max_time': {'siid': 9, 'piid': 1}, 'filter_hour_used_debug-9-2': {'siid': 9, 'piid': 2}, 'physical_controls_locked': {'siid': 7, 'piid': 1}, 'indicator_light.brightness': {'siid': 6, 'piid': 1}, 'indicator_light.on': {'siid': 6, 'piid': 6}, 'alarm': {'siid': 5, 'piid': 1}, 'filter.filter_life_level': {'siid': 4, 'piid': 3}, 'filter.filter_used_time': {'siid': 4, 'piid': 5}, 'environment.pm2_5_density': {'siid': 3, 'piid': 6}, 'environment.relative_humidity': {'siid': 3, 'piid': 7}, 'environment.temperature': {'siid': 3, 'piid': 8}}, max_properties: 8/24

**Comment by al-one** [comment]
Try master branch.

**Comment by Leeeooooo** [comment]
> 请升级到master分支后再观察。

v0.6.4 - 2022-05-10  这个版本仍然会有错误，只是也许不那么频繁了。
我之后更新到最新commit再重新添加设备试一下

**Comment by al-one** [comment]
请问该问题还存在吗？

**Comment by Leeeooooo** [comment]
最近没有出现了，谢谢
