### ISSUE TITLE
viomi.vacuum.v8: Unable to discover the device

### ISSUE THREAD

**Issue by Mick51** [al-one/hass-xiaomi-miot#582]
`Cette erreur provient d'une intégration personnalisée

Logger: custom_components.xiaomi_miot.vacuum
Source: custom_components/xiaomi_miot/__init__.py:1298
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 17:03:57 (1 occurrences)
Last logged: 17:03:57

Mi Robot Vacuum-Mop P(viomi.vacuum.v8): Got MiioException while fetching the state: Unable to discover the device 192.168.1.12, mapping: {'vacuum.status': {'siid': 2, 'piid': 1}, 'vacuum.mode': {'siid': 2, 'piid': 2}, 'viomi_vacuum.main_brush_life': {'siid': 200, 'piid': 201}, 'viomi_vacuum.side_brush_life': {'siid': 200, 'piid': 202}, 'viomi_vacuum.hypa_life': {'siid': 200, 'piid': 203}, 'viomi_vacuum.mop_life': {'siid': 200, 'piid': 204}, 'battery_level': {'siid': 3, 'piid': 1}}, max_properties: 10/7`

**Comment by al-one** [comment]
> Unable to discover the device 192.168.1.12

Please check it's IP and make sure it in the same subnet as the HA.

**Comment by drunkly** [comment]
I have a similar issue, my device (ijai.vacuum.v19)  was working until recently it stop to show entities information and display this message.
I have homeassistnat and vaccum device on different subnets (and different vlans) like I have other devices (whith their firewall rules and redirects) but this is the only one which giving me this problem.
I won't change the lan rules (It is done like this for security reasons) so I would like to ask if there is any chance to make it work on different subnets or it will be impossible (maybe due api arquitechture reasons)?.

I was thinking than maybe I can redirect one Lan port on HA subnet to other port on Vacuum subnet kind of:
10.0.0.1:443 => 10.0.3.8:443
but I don't know which port redirect or if I can use a different one from plugin.

Has someone get workaround this issue keeping devices on differnet subnets?

**Comment by al-one** [comment]
- https://python-miio.readthedocs.io/en/latest/troubleshooting.html#discover-devices-across-subnets
- https://github.com/rytilahti/python-miio/issues/422#issuecomment-455824152

**Comment by drunkly** [comment]
Thank you very much!!!!

Now it is working so I share my config just in case it is useful for someone:
![image](https://user-images.githubusercontent.com/9574437/179491469-2c81b7b2-fee0-426c-a60a-6dd6e2d842c4.png)

Details:
VLANHOME => where HA server lays with IP (192.168.3.5)
VLANUNKOWN => where vacuum and unsecure devices lays with IP (192.168.8.107)
