### ISSUE TITLE
zhimi.airpurifier.v7 missing parameters.

### ISSUE THREAD

**Issue by bimodinochka** [al-one/hass-xiaomi-miot#586]
Good day, I found the missing parameters.

1. There is no slider of the selected speed.

2. There is no speed sensor (I do not know if it is possible to get it).

3. There is no LUX sensor (I do not know if it is possible to get it).

4. There is no switch to mute the device (I do not know if it is possible to get it).

5. Switch auto-detection of air pollution (I don't know if this function is needed and if it is possible to get it).
When this function is turned on, it does not purify the engine speed in case of air pollution.

If you need tests or some data, I am ready to help.

**Comment by al-one** [comment]
Try master branch.

**Comment by bimodinochka** [comment]
> Try master branch.

I have upgraded to a branch (Master) but it didn't change anything, I also deleted and added the device again.
