### ISSUE TITLE
Mi Fresh Air Ventilator C1-80 zhimi.airfresh.ua1 - There is no way to control the function "Electric Auxiliary Heating"

### ISSUE THREAD

**Issue by theodorx7** [al-one/hass-xiaomi-miot#590]
_Home Assistant Core 2022.5.4
Xiaomi Miot Auto v 0.6.4_

The device has an air heating function, however, there is no switch for this function.
I would be grateful for your help in solving this problem.

![IMG_1305](https://user-images.githubusercontent.com/99128059/168588086-1ed7d4e7-e007-4296-8f8a-82304145fd2f.PNG)

![Air fresh heater](https://user-images.githubusercontent.com/99128059/168588112-714ba23b-2ccc-4150-9499-cf350a58cb4d.png)

![heater](https://user-images.githubusercontent.com/99128059/168588126-3ce1799c-7a01-494a-8dba-6d3e60eea130.png)

**Comment by al-one** [comment]
Upgrade to master branch and try.

**Comment by theodorx7** [comment]
Thank you very much!  The switch works! 
😃👍🏼
