### ISSUE TITLE
小米风扇1X无法控制风速

### ISSUE THREAD

**Issue by 18018639970** [al-one/hass-xiaomi-miot#594]
无论怎么调节风速永远是一档，同时无法自动更新状态，比如手动开启后电扇后状态不会自动更新。其他功能正常

**Comment by 18018639970** [comment]
> 已修复，请更新至master分支。
已经更新到master版了问题没有解决，试过重新删除并添加设备了

**Comment by al-one** [comment]
请再次更新master分支。

**Comment by zhheo** [comment]
> 在本地运行时和原来一样无法控制档位，在云端运行时可以控制档位
> 已经试过删除集成，删除设备

在本地运行时和原来一样无法控制档位，在云端运行时可以控制档位
已经试过删除集成，删除设备

**Comment by zhheo** [comment]
> 请再次更新master分支。

在本地运行时和原来一样无法控制档位，在云端运行时可以控制档位
已经试过删除集成，删除设备

**Comment by ABUAIJUTIE** [comment]
同上，本地无法运行。看日志好像有小爱对话？

**Comment by al-one** [comment]
- 确认插件版本为`v0.6.7`及以上
- 确认风扇型号为[`dmaker.fan.p5`](https://home.miot-spec.com/s/dmaker.fan.p5)
- 确认是在自动模式/本地模式下集成该风扇
- 请提供开发者工具中的[实体属性](https://my.home-assistant.io/redirect/developer_states)

**Comment by sctale** [comment]
@al-one 
大佬，我昨天也增加了一个小米落地扇1X，也是相同问题。
版本：v0.6.7
型号：dmaker.fan.p5
模式：自动
实体属性：如下

preset_modes: Natural Wind, Straight Wind
direction: null
oscillating: true
percentage: null
percentage_step: 25
preset_mode: Straight Wind
model: dmaker.fan.p5
lan_ip: 192.168.20.178
mac_address: 58:B6:23:..:..:..
entity_class: MiotFanEntity
home_room: 浩浩的家 次卧
miot_type: urn:miot-spec-v2:device:fan:0000A005:dmaker-p5:1
fan.on: false
fan.horizontal_swing: true
fan.mode: 1
fan.fan_level: 35
fan.horizontal_angle: 60
off_delay_time: 0
alarm: true
indicator_light.on: true
physical_controls_locked: false
state_updater: lan
sub_entities: off_delay_time-200.off_delay_time-201, fan-2.horizontal_angle-101, physical_controls_locked-3.physical_controls_locked-1, indicator_light-4
friendly_name: 小米落地扇1X Fan
supported_features: 15

**Comment by al-one** [comment]
控制风速后有无任何报错[日志](https://my.home-assistant.io/redirect/logs)？

**Comment by al-one** [comment]
请再次更新至master分支。
