### ISSUE TITLE
通过米家控制器接入的设备会显示吗？

### ISSUE THREAD

**Issue by googooog** [al-one/hass-xiaomi-miot#595]
是不是只要设备可以接入米家app，就可以在HA中找到相应的设备？

例如我想通过米家控制器连接低压灯带，实现接入米家app的功能。这样HA中就可以显示我这个灯带从而可以使用home kit控制？

**Comment by al-one** [comment]
能够在米家APP控制的设备，几乎都可以通过本插件接入HA，并通过HA的HomeKit集成接入iOS家庭。
