### ISSUE TITLE
Humidifier zhimi.ca1 unsupported Water Level

### ISSUE THREAD

**Issue by zzaal** [al-one/hass-xiaomi-miot#598]
Hello!
After updating from 0.6.4 to 0.6.5 Humidifier_zhimi_ca1 does not show the water level.
Status: unsupported
rollback to 0.6.4 - works again!

developer-tools/state:

**Version 0.6.4:**
min: 0
max: 127
step: 1
mode: auto
friendly_name: Humidifier Water Level
supported_features: 0
entity_class: MiotNumberSubEntity
parent_entity_id: humidifier.zhimi_ca1_84d9_humidifier
service_description: Humidifier
property_description: Water Level
humidifier.water_level: 99

**Version 0.6.5**
restored: true
min: 0
max: 127
step: 1
mode: auto
friendly_name: Humidifier Water Level
supported_features: 0

as seen above in 0.6.5, there are not enough parameters:

_entity_class: MiotNumberSubEntity
parent_entity_id: humidifier.zhimi_ca1_84d9_humidifier
service_description: Humidifier
property_description: Water Level
humidifier.water_level: 99_

**Comment by zzaal** [comment]
0.6.6. not work too.
can you fix?

**Comment by al-one** [comment]
Upgrade to master branch.

**Comment by zzaal** [comment]
hello!

A new sensor has appeared: **sensor.zhimi_ca1_84d9_water_level**

entity_class: MiotSensorSubEntity
parent_entity_id: humidifier.zhimi_ca1_84d9_humidifier
service_description: Humidifier
property_description: Water Level
humidifier.water_level: 67
friendly_name: Humidifier Bedroom Humidifier Water Level
supported_features: 0

Many thanks for the work done! 
The water level is working again!
