### ISSUE TITLE
米家app的状态与HA中状态的同步

### ISSUE THREAD

**Issue by a451435623** [al-one/hass-xiaomi-miot#599]
你好，开发者
        感谢做出如此好用的插件！
        我在家中有一款蓝牙MESH的灯 https://home.miot-spec.com/s/lemesh.switch.sw0a01
        当我在在HA和米家app中对它进行开关都没有问题，但是我在HA中对它进行关闭时关灯的状态无法同步到米家APP中，在米家APP对它关闭时也无法同步到HA中，请问我需要做什么或者提供什么材料。

**Comment by al-one** [comment]
请提供开发者工具中的[实体属性](https://my.home-assistant.io/redirect/developer_states)。

在HA控制设备后，设备实际有无变化？并在米家控制设备一分钟以后，观察HA中状态是否同步。

**Comment by a451435623** [comment]
设备实际有变化，但是同步时间很奇怪（是云端的原因么？），有时候在操作后十几秒才能同步，有时几秒以后就同步成功了
model: lemesh.switch.sw0a01
lan_ip: 
mac_address: 5C:E5:0C:EE:B3:B0
entity_class: MiotSwitchEntity
home_room: XXX的家庭 客厅
miot_type: urn:miot-spec-v2:device:switch:0000A003:lemesh-sw0a01:2:0000C808
switch.on: false
iv: 43992320
scenes.on_off.error: -704030013 Property is not readable
scenes.default: 3
state_updater: cloud
device_class: switch
friendly_name: 射灯 switch
supported_features: 0

**Comment by al-one** [comment]
正常。请参考：

- https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-909031222

**Comment by a451435623** [comment]
谢谢，了解了，我将会关闭问题
