### ISSUE TITLE
空调 IR Aircondition Control数据无法与米家同步

### ISSUE THREAD

**Issue by unknown-o** [al-one/hass-xiaomi-miot#601]
此空调红外遥控是使用小爱同学Play万能遥控版创建的
使用HA接入后可以在设备列表中显示，也可以正常控制空调
但是不可以同步米家的设置和状态
![image](https://user-images.githubusercontent.com/51825113/169631594-1aaa1aa8-4daa-4fd1-9d18-d7a6df2b32ea.png)
![image](https://user-images.githubusercontent.com/51825113/169631600-080f7f3f-11b8-4443-b8da-1d55dd8761ac.png)

**Comment by al-one** [comment]
红外虚拟设备是没有状态的。。。

**Comment by unknown-o** [comment]
所以无法和米家同步红外空调遥控器的状态么？

**Comment by al-one** [comment]
无法同步。米家也没有红外空调的状态吧。

**Comment by unknown-o** [comment]
确实，看了一下，米家APP的空调温度确实不能多设备同步。
麻烦了

**Comment by al-one** [comment]
不过你可以通过添加自定义选项`bind_sensor`来给HA中的红外空调实体绑定一个温度传感器实体。

**Comment by unknown-o** [comment]
OK，感谢

**Comment by PhDLuffy** [comment]
@al-one 您好，我在Node-red里面想设置红外空调的风速，服务选择的是select_option，但是Data里面不知道该填什么。

例子，比如设置温度，我用的服务是set_temperature，Data是{"temperature":22}，
与之对应的调节空调风速的Data是什么呀？

https://fastly.jsdelivr.net/gh/PhDLuffy/PicGo@master/img/202306031020116.png
