### ISSUE TITLE
米家小夜灯做为关照感应使用

### ISSUE THREAD

**Issue by yyk8754** [al-one/hass-xiaomi-miot#602]
Motion Sensor no_motion_seconds这个感应器是运行多久没人移动的功能吗还是测试流明度的，Illumination Sensor这个参数在测试流明度的时候只有1和100，没有其他的，这个咱么解决，想把小夜灯2做为移动传感器和光照使用，但是必须满足一定亮度之后才启动，现在调用的光照数值只有1和100，没有其他无法满足使用需求

**Comment by al-one** [comment]
实体`Motion Sensor no_motion_seconds`是多久没人移动的传感器。

米家夜灯2只有明暗监测，无具体流明数值。
