### ISSUE TITLE
正确小米账号密码依旧无法登录

### ISSUE THREAD

**Issue by Donleo-feng** [al-one/hass-xiaomi-miot#603]
![image](https://user-images.githubusercontent.com/31247360/169647739-5fee5b03-6664-464e-9e3c-b6752f67bbe5.png)
登录验证是显示ok，也重启过，依旧不行
![image](https://user-images.githubusercontent.com/31247360/169648038-c78ec534-ef28-4081-a71b-db2841d0fa9d.png)
报错代码如下：
```2022-05-21 18:37:13 ERROR (MainThread) [custom_components.xiaomi_miot.config_flow] Setup xiaomi cloud for user: 13554548709 failed: Login to xiaomi error: &&&START&&&{"notificationUrl":"https://account.xiaomi.com/identity/authStart?sid=passport&context=zk148yDipjfqJZ1StcrptKUbzpo6zKM722Quep0t_9WrAr3axWdcqAfuT0M7BRgP0M7W7HEG9YXvbRhN9NzgGR0rZeFlfOEm9lvlKw9GRNYS9Tzy3JAMbl-IwfxISha2lbVzkuy5i96_dvl_DfJ67F6IQjhTaqxRjhoPSCwUCMuAf3FdVmDRh0izNE_8hYXaDb7rux6ycOjOgX6MfWPnRzkTrk92enSFMB5liXFki_cUDjXF8iHB2nrpGcBALhgNmfmWaKcRt2McJihhsQAu4OMNsb8YpBXW4BBuyEkN0Yh6_9Rst7RAWhwhPT74YHuAqJdpz70zI9DEuuaVQvM7OX_sXDH-Gm25wL4qGvi-qWqGpOejTtn1aTtMKWzK7Ll09dz6_Tat1qK7FhcYYEEHprnbtoEKf-IaOjHWYlzcrCbAy-GDaUAHzXcQQEvGPXy_VGrDKY_lLxO5VDAaBdKDE55iHtpTsalb7mShtg8vNsY4SZalfTIBsXv7-sJdoNSvvVHhuOefxfvo4UaC2VsaDT2Kocua1wqfoaOc4yVLepIY3CYQVBzJmE2BAp3Nx5YuP_BmDwIH9alcZEay7MTsFaPCzFXAsS7Y3hkbxowjQmwj9QfaHtnErFA4RmsxFjYJixSiD6dasLut0uarWAciGDZTAbt4g5TZq35svb86S7cCk8L3U_SJ_zWTKiafdMtF2nm6QEWrhZIoJaSq7caPcOTOC7qUoNvtSc0PLAnmgT1JyzcgUCt-c7Kk0wmycIX8Bf9Y_Wvm3zbvq_7LFehcp4RVpVxS3b4ngZnNhfYVdsc&_locale=zh_CN","result":"ok","code":0,"captchaUrl":null,"description":"成功","location":"","securityStatus":16,"pwd":0,"desc":"成功"}```

**Comment by al-one** [comment]
请确保HA所属网络环境和打开链接验证时是同一网络环境。

**Comment by al-one** [comment]
请问现在可以登录了吗？

**Comment by shsxxx** [comment]
> 请确保HA所属网络环境和打开链接验证时是同一网络环境。

什么意思 ，怎么确保在同一网络！我也遇到同样的问题。我是在centos7中docker安装的ha，登录xiaomi时也是登录失败，安全验证成功了，也没有反应

**Comment by al-one** [comment]
HA所在的主机需要和你登陆验证的电脑在同一个局域网。

**Comment by Donleo-feng** [comment]
现在可以登陆了，是在同一个网才能登陆成功

**Comment by Zhanglk-stack** [comment]
我也遇到了相同的问题，主机和电脑都是同一个局域网，点击链接验证ok后点提交，显示没有设备，请问如何解决
