### ISSUE TITLE
米家早期的空调有错误，请看一下问题

### ISSUE THREAD

**Issue by iwangzhuo** [al-one/hass-xiaomi-miot#605]
型号：https://home.miot-spec.com/spec/zhimi.aircondition.ma4

此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.climate
Source: custom_components/xiaomi_miot/__init__.py:1336
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 10:31:49 (37 occurrences)
Last logged: 10:34:53

客厅的米家空调(zhimi.aircondition.ma4): Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'air_conditioner.on': {'siid': 2, 'piid': 1}, 'air_conditioner.mode': {'siid': 2, 'piid': 2}, 'target_temperature-2-3': {'siid': 2, 'piid': 3}, 'air_conditioner.heater': {'siid': 2, 'piid': 4}, 'air_conditioner.sleep_mode': {'siid': 2, 'piid': 5}, 'indicator_light.on': {'siid': 6, 'piid': 1}, 'indicator_light.brightness': {'siid': 6, 'piid': 2}, 'alarm': {'siid': 5, 'piid': 1}, 'environment.temperature': {'siid': 4, 'piid': 1}, 'fan_control.fan_level': {'siid': 3, 'piid': 1}, 'fan_control.vertical_swing': {'siid': 3, 'piid': 2}, 'fan_control.vertical_angle': {'siid': 3, 'piid': 3}}, max_properties: 6/12

**Comment by al-one** [comment]
已适配该型号的本地模式接入，请更新至master分支后尝试。
