### ISSUE TITLE
是否可以增加设备离线提醒的开关？

### ISSUE THREAD

**Issue by wdmywm3** [al-one/hass-xiaomi-miot#606]
有些设备联网不是很稳定，偶尔会wifi掉线，实际是一直好用的，但每天点进ha就会提示xx设备已掉线，强迫症表示非常难受，是否可以考虑在以后的更新里增加一项设置，开关这个自动提醒的功能？

**Comment by al-one** [comment]
你可以通过[自定义选项](https://github.com/al-one/hass-xiaomi-miot/issues/600)`ignore_offline`来为指定设备禁用离线通知：
- https://github.com/al-one/hass-xiaomi-miot/issues/574#issuecomment-1121955107

对于不稳定的设备，还可以使用`auto_cloud`选项来自动切换云端模式。
