### ISSUE TITLE
感谢作者的一直付出更新插件请问有捐赠方式吗？并且我的babai.switch.bb103s三键开关有问题，能否帮助我处理。

### ISSUE THREAD

**Issue by Jerrys-j** [al-one/hass-xiaomi-miot#61]
Got MiioException while fetching the state for Light Left Switch Service: Unable to parse message payload
Got MiioException while fetching the state for Light Middle Switch Service: Unable to parse message payload
Got MiioException while fetching the state for Light Right Switch Service: Unable to parse message payload
2021-04-15 16:20:06 INFO (MainThread) [custom_components.xiaomi_miot] Initializing miot device: Light Left Switch Service, mapping: {'switch-4.on': {'siid': 4, 'piid': 1}, 'switch-4.off_delay': {'siid': 4, 'piid': 2}, 'switch-3.on': {'siid': 3, 'piid': 1}, 'switch-3.off_delay': {'siid': 3, 'piid': 2}, 'switch.on': {'siid': 2, 'piid': 1}, 'switch.eco': {'siid': 2, 'piid': 2}, 'switch.off_delay': {'siid': 2, 'piid': 3}, 'switch.mode': {'siid': 2, 'piid': 4}}
2021-04-15 16:20:06 INFO (MainThread) [custom_components.xiaomi_miot] Initializing miot device: Light Middle Switch Service, mapping: {'switch-4.on': {'siid': 4, 'piid': 1}, 'switch-4.off_delay': {'siid': 4, 'piid': 2}, 'switch-3.on': {'siid': 3, 'piid': 1}, 'switch-3.off_delay': {'siid': 3, 'piid': 2}, 'switch.on': {'siid': 2, 'piid': 1}, 'switch.eco': {'siid': 2, 'piid': 2}, 'switch.off_delay': {'siid': 2, 'piid': 3}, 'switch.mode': {'siid': 2, 'piid': 4}}
2021-04-15 16:20:06 INFO (MainThread) [custom_components.xiaomi_miot] Initializing miot device: Light Right Switch Service, mapping: {'switch-4.on': {'siid': 4, 'piid': 1}, 'switch-4.off_delay': {'siid': 4, 'piid': 2}, 'switch-3.on': {'siid': 3, 'piid': 1}, 'switch-3.off_delay': {'siid': 3, 'piid': 2}, 'switch.on': {'siid': 2, 'piid': 1}, 'switch.eco': {'siid': 2, 'piid': 2}, 'switch.off_delay': {'siid': 2, 'piid': 3}, 'switch.mode': {'siid': 2, 'piid': 4}}

**Comment by Jerrys-j** [comment]
插件的0.28版本接入正常，但0.28以后的版本就不能使用，由于更新了homeassistant2021.4.4版本，退回2.2版本已经没办法正常使用，1开、2开都可以正常接入，3开的话显示实体不可用

**Comment by al-one** [comment]
感谢您对本插件的肯定与支持，暂时不开放捐赠，如果对您有帮助的话，点个⭐就好。
至于您的开关，是否之前的版本也一直是本地模式，未开启云端模式？

**Comment by Jerrys-j** [comment]
是的，目前三开开关云端状态是正常的，但本地模式就会显示不可用。

> 感谢您对本插件的肯定与支持，暂时不开放捐赠，如果对您有帮助的话，点个⭐就好。
> 至于您的开关，是否之前的版本也一直是本地模式，未开启云端模式？

**Comment by Jerrys-j** [comment]
您好，经过昨天测试发现了一个问题。如果本地模式中三开开关随意打开一路，那么所有开关都会变成可用状态并且能实时控制，如果三路全关的话，开关所有三路会直接不可用。

**Comment by al-one** [comment]
建议你通过miiocli工具测试下设备是否也会出现这种情况。
```shell
miiocli -d miotdevice --ip ... --token ... set_property_by 2 1 'False' 'bool'
miiocli -d miotdevice --ip ... --token ... set_property_by 3 1 'False' 'bool'
miiocli -d miotdevice --ip ... --token ... set_property_by 4 1 'False' 'bool'
```

**Comment by Jerrys-j** [comment]
您好，更新0.34，如下情况第一路可以控制，其他两路仍然不可用，按照以上测试日志如下

INFO:miio.cli:Debug mode active                                                                                                                                                                                                                                                             
Running command set_property_by                                                                                                                                                                                                                                                             
DEBUG:miio.miioprotocol:Got a response: Container:                                                                                                                                                                                                                                          
    data = Container:                                                                                                                                                                                                                                                                       
        data = b'' (total 0)                                                                                                                                                                                                                                                                
        value = b'' (total 0)                                                                                                                                                                                                                                                               
        offset1 = 32                                                                                                                                                                                                                                                                        
        offset2 = 32                                                                                                                                                                                                                                                                        
        length = 0                                                                                                                                                                                                                                                                          
    header = Container:                                                                                                                                                                                                                                                                     
        data = b'!1\x00 \x00\x00\x00\x00\x169&\\\x00?I\x1b' (total 16)                                                                                                                                                                                                                      
        value = Container:                                                                                                                                                                                                                                                                  
            length = 32                                                                                                                                                                                                                                                                     
            unknown = 0                                                                                                                                                                                                                                                                     
            device_id = unhexlify('1639265c')                                                                                                                                                                                                                                               
            ts = 1970-02-18 00:04:43                                                                                                                                                                                                                                                        
        offset1 = 0                                                                                                                                                                                                                                                                         
        offset2 = 16                                                                                                                                                                                                                                                                        
        length = 16                                                                                                                                                                                                                                                                         
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)                                                                                                                                                                                               
DEBUG:miio.miioprotocol:Discovered 1639265c with ts: 1970-02-18 00:04:43, token: b'ffffffffffffffffffffffffffffffff'                                                                                                                                                                        
DEBUG:miio.miioprotocol:192.168.1.16:54321 >>: {'id': 1, 'method': 'set_properties', 'params': [{'did': 'set-2-1', 'siid': 2, 'piid': 1, 'value': False}]}                                                                                                                                  
DEBUG:miio.miioprotocol:192.168.1.16:54321 (ts: 1970-02-18 00:04:43, id: 1) << {'id': 1, 'result': [{'did': 'set-2-1', 'siid': 2, 'piid': 1, 'code': 0}], 'exe_time': 200}                                                                                                                  
[{'did': 'set-2-1', 'siid': 2, 'piid': 1, 'code': 0}]

INFO:miio.cli:Debug mode active                                                                                                                                                                                                                                                             
Running command set_property_by                                                                                                                                                                                                                                                             
DEBUG:miio.miioprotocol:Got a response: Container:                                                                                                                                                                                                                                          
    data = Container:                                                                                                                                                                                                                                                                       
        data = b'' (total 0)                                                                                                                                                                                                                                                                
        value = b'' (total 0)                                                                                                                                                                                                                                                               
        offset1 = 32                                                                                                                                                                                                                                                                        
        offset2 = 32                                                                                                                                                                                                                                                                        
        length = 0                                                                                                                                                                                                                                                                          
    header = Container:                                                                                                                                                                                                                                                                     
        data = b'!1\x00 \x00\x00\x00\x00\x169&\\\x00?I\x1c' (total 16)                                                                                                                                                                                                                      
        value = Container:                                                                                                                                                                                                                                                                  
            length = 32                                                                                                                                                                                                                                                                     
            unknown = 0                                                                                                                                                                                                                                                                     
            device_id = unhexlify('1639265c')                                                                                                                                                                                                                                               
            ts = 1970-02-18 00:04:44                                                                                                                                                                                                                                                        
        offset1 = 0                                                                                                                                                                                                                                                                         
        offset2 = 16                                                                                                                                                                                                                                                                        
        length = 16                                                                                                                                                                                                                                                                         
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)                                                                                                                                                                                               
DEBUG:miio.miioprotocol:Discovered 1639265c with ts: 1970-02-18 00:04:44, token: b'ffffffffffffffffffffffffffffffff'                                                                                                                                                                        
DEBUG:miio.miioprotocol:192.168.1.16:54321 >>: {'id': 1, 'method': 'set_properties', 'params': [{'did': 'set-3-1', 'siid': 3, 'piid': 1, 'value': False}]}                                                                                                                                  
DEBUG:miio.miioprotocol:192.168.1.16:54321 (ts: 1970-02-18 00:04:44, id: 1) << {'id': 1, 'result': [{'did': 'set-3-1', 'siid': 3, 'piid': 1, 'code': 0}], 'exe_time': 80}                                                                                                                   
[{'did': 'set-3-1', 'siid': 3, 'piid': 1, 'code': 0}]

INFO:miio.cli:Debug mode active                                                                                                                                                                                                                                                             
Running command set_property_by                                                                                                                                                                                                                                                             
DEBUG:miio.miioprotocol:Got a response: Container:                                                                                                                                                                                                                                          
    data = Container:                                                                                                                                                                                                                                                                       
        data = b'' (total 0)                                                                                                                                                                                                                                                                
        value = b'' (total 0)                                                                                                                                                                                                                                                               
        offset1 = 32                                                                                                                                                                                                                                                                        
        offset2 = 32                                                                                                                                                                                                                                                                        
        length = 0                                                                                                                                                                                                                                                                          
    header = Container:                                                                                                                                                                                                                                                                     
        data = b'!1\x00 \x00\x00\x00\x00\x169&\\\x00?I!' (total 16)                                                                                                                                                                                                                         
        value = Container:                                                                                                                                                                                                                                                                  
            length = 32                                                                                                                                                                                                                                                                     
            unknown = 0                                                                                                                                                                                                                                                                     
            device_id = unhexlify('1639265c')                                                                                                                                                                                                                                               
            ts = 1970-02-18 00:04:49                                                                                                                                                                                                                                                        
        offset1 = 0                                                                                                                                                                                                                                                                         
        offset2 = 16                                                                                                                                                                                                                                                                        
        length = 16                                                                                                                                                                                                                                                                         
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)                                                                                                                                                                                               
DEBUG:miio.miioprotocol:Discovered 1639265c with ts: 1970-02-18 00:04:49, token: b'ffffffffffffffffffffffffffffffff'                                                                                                                                                                        
DEBUG:miio.miioprotocol:192.168.1.16:54321 >>: {'id': 1, 'method': 'set_properties', 'params': [{'did': 'set-4-1', 'siid': 4, 'piid': 1, 'value': False}]}                                                                                                                                  
DEBUG:miio.miioprotocol:192.168.1.16:54321 (ts: 1970-02-18 00:04:49, id: 1) << {'id': 1, 'result': [{'did': 'set-4-1', 'siid': 4, 'piid': 1, 'code': 0}], 'exe_time': 50}                                                                                                                   
[{'did': 'set-4-1', 'siid': 4, 'piid': 1, 'code': 0}]

**Comment by al-one** [comment]
从日志看好像三次都是成功的。另外建议你开启云端模式后尝试下是否也是这种情况。

**Comment by Jerrys-j** [comment]
日志除了数值变化基本一样，配置云端账号后勾选云端模式状态更新还是本地模式，以下是开关一直可用那一路状态和暂时可用的一路信息

![微信截图_20210524115655](https://user-images.githubusercontent.com/49357718/119294631-7e452680-bc87-11eb-822b-dedb221fe40c.png)
![微信截图_20210524115731](https://user-images.githubusercontent.com/49357718/119294657-8c934280-bc87-11eb-9ef5-170e26a5af4c.png)

> INFO:miio.cli:Debug mode active                                                                                                                                                                                                                                                             
Running command set_property_by                                                                                                                                                                                                                                                             
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''                                                                                                                                                                                                                             
DEBUG:miio.miioprotocol:Got a response: Container:                                                                                                                                                                                                                                          
    data = Container:                                                                                                                                                                                                                                                                       
        data = b'' (total 0)                                                                                                                                                                                                                                                                
        value = b'' (total 0)                                                                                                                                                                                                                                                               
        offset1 = 32                                                                                                                                                                                                                                                                        
        offset2 = 32                                                                                                                                                                                                                                                                        
        length = 0                                                                                                                                                                                                                                                                          
    header = Container:                                                                                                                                                                                                                                                                     
        data = b'!1\x00 \x00\x00\x00\x00\x169&\\\x00?\xf4\xf7' (total 16)                                                                                                                                                                                                                   
        value = Container:                                                                                                                                                                                                                                                                  
            length = 32                                                                                                                                                                                                                                                                     
            unknown = 0                                                                                                                                                                                                                                                                     
            device_id = unhexlify('1639265c')                                                                                                                                                                                                                                               
            ts = 1970-02-18 12:17:59                                                                                                                                                                                                                                                        
        offset1 = 0                                                                                                                                                                                                                                                                         
        offset2 = 16                                                                                                                                                                                                                                                                        
        length = 16                                                                                                                                                                                                                                                                         
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)                                                                                                                                                                                               
DEBUG:miio.miioprotocol:Discovered 1639265c with ts: 1970-02-18 12:17:59, token: b'ffffffffffffffffffffffffffffffff'                                                                                                                                                                        
DEBUG:miio.miioprotocol:192.168.1.16:54321 >>: {'id': 1, 'method': 'set_properties', 'params': [{'did': 'set-3-1', 'siid': 3, 'piid': 1, 'value': False}]}                                                                                                                                  
DEBUG:miio.miioprotocol:192.168.1.16:54321 (ts: 1970-02-18 12:17:59, id: 1) << {'id': 1, 'result': [{'did': 'set-3-1', 'siid': 3, 'piid': 1, 'code': 0}], 'exe_time': 60}                                                                                                                   
[{'did': 'set-3-1', 'siid': 3, 'piid': 1, 'code': 0}]

>INFO:miio.cli:Debug mode active                                                                                                                                                                                                                                                             
Running command set_property_by                                                                                                                                                                                                                                                             
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''                                                                                                                                                                                                                             
DEBUG:miio.miioprotocol:Got a response: Container:                                                                                                                                                                                                                                          
    data = Container:                                                                                                                                                                                                                                                                       
        data = b'' (total 0)                                                                                                                                                                                                                                                                
        value = b'' (total 0)                                                                                                                                                                                                                                                               
        offset1 = 32                                                                                                                                                                                                                                                                        
        offset2 = 32                                                                                                                                                                                                                                                                        
        length = 0                                                                                                                                                                                                                                                                          
    header = Container:                                                                                                                                                                                                                                                                     
        data = b'!1\x00 \x00\x00\x00\x00\x169&\\\x00?\xf4\xf7' (total 16)                                                                                                                                                                                                                   
        value = Container:                                                                                                                                                                                                                                                                  
            length = 32                                                                                                                                                                                                                                                                     
            unknown = 0                                                                                                                                                                                                                                                                     
            device_id = unhexlify('1639265c')                                                                                                                                                                                                                                               
            ts = 1970-02-18 12:17:59                                                                                                                                                                                                                                                        
        offset1 = 0                                                                                                                                                                                                                                                                         
        offset2 = 16                                                                                                                                                                                                                                                                        
        length = 16                                                                                                                                                                                                                                                                         
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)                                                                                                                                                                                               
DEBUG:miio.miioprotocol:Discovered 1639265c with ts: 1970-02-18 12:17:59, token: b'ffffffffffffffffffffffffffffffff'                                                                                                                                                                        
DEBUG:miio.miioprotocol:192.168.1.16:54321 >>: {'id': 1, 'method': 'set_properties', 'params': [{'did': 'set-3-1', 'siid': 3, 'piid': 1, 'value': False}]}                                                                                                                                  
DEBUG:miio.miioprotocol:192.168.1.16:54321 (ts: 1970-02-18 12:17:59, id: 1) << {'id': 1, 'result': [{'did': 'set-3-1', 'siid': 3, 'piid': 1, 'code': 0}], 'exe_time': 60}                                                                                                                   
[{'did': 'set-3-1', 'siid': 3, 'piid': 1, 'code': 0}]

>INFO:miio.cli:Debug mode active                                                                                                                                                                                                                                                             
Running command set_property_by                                                                                                                                                                                                                                                             
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''                                                                                                                                                                                                                             
DEBUG:miio.miioprotocol:Got a response: Container:                                                                                                                                                                                                                                          
    data = Container:                                                                                                                                                                                                                                                                       
        data = b'' (total 0)                                                                                                                                                                                                                                                                
        value = b'' (total 0)                                                                                                                                                                                                                                                               
        offset1 = 32                                                                                                                                                                                                                                                                        
        offset2 = 32                                                                                                                                                                                                                                                                        
        length = 0                                                                                                                                                                                                                                                                          
    header = Container:                                                                                                                                                                                                                                                                     
        data = b'!1\x00 \x00\x00\x00\x00\x169&\\\x00?\xf5%' (total 16)                                                                                                                                                                                                                      
        value = Container:                                                                                                                                                                                                                                                                  
            length = 32                                                                                                                                                                                                                                                                     
            unknown = 0                                                                                                                                                                                                                                                                     
            device_id = unhexlify('1639265c')                                                                                                                                                                                                                                               
            ts = 1970-02-18 12:18:45                                                                                                                                                                                                                                                        
        offset1 = 0                                                                                                                                                                                                                                                                         
        offset2 = 16                                                                                                                                                                                                                                                                        
        length = 16                                                                                                                                                                                                                                                                         
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)                                                                                                                                                                                               
DEBUG:miio.miioprotocol:Discovered 1639265c with ts: 1970-02-18 12:18:45, token: b'ffffffffffffffffffffffffffffffff'                                                                                                                                                                        
DEBUG:miio.miioprotocol:192.168.1.16:54321 >>: {'id': 1, 'method': 'set_properties', 'params': [{'did': 'set-4-1', 'siid': 4, 'piid': 1, 'value': False}]}                                                                                                                                  
DEBUG:miio.miioprotocol:192.168.1.16:54321 (ts: 1970-02-18 12:18:45, id: 1) << {'id': 1, 'result': [{'did': 'set-4-1', 'siid': 4, 'piid': 1, 'code': 0}], 'exe_time': 300}                                                                                                                  
[{'did': 'set-4-1', 'siid': 4, 'piid': 1, 'code': 0}]

**Comment by al-one** [comment]
推荐通过账号方式集成该设备，此方式会默认使用云端模式，且无需在yaml配置账号密码。

**Comment by Jerrys-j** [comment]
> 推荐通过账号方式集成该设备，此方式会默认使用云端模式，且无需在yaml配置账号密码。

谢谢辛苦了，云端虽然配置简单，但是延迟也是会偏大

**Comment by al-one** [comment]
其实延迟也没有那么大，只是依赖外网。我是想让你测试一下在云端模式下是否会出现你之前提到的问题：
> 如果本地模式中三开开关随意打开一路，那么所有开关都会变成可用状态并且能实时控制，如果三路全关的话，开关所有三路会直接不可用。

**Comment by Jerrys-j** [comment]
云端三路都能正常开关，没有以上问题，就是本地模式才会出现的问题，更新到0.34后，除了有一路能正常操控，其他两路感觉有时候会随机变成可用

**Comment by al-one** [comment]
可能还是设备本身的问题吧。
