### ISSUE TITLE
All camera entities got "serviceToken expired" after v0.6.6 upgradation. (Workaround included)

### ISSUE THREAD

**Issue by kodbuzz** [al-one/hass-xiaomi-miot#610]
### Log:

> Front(madv.cateye.miowl3): camera events is empty. {'code': 3, 'message': 'serviceToken expired'}
> Yard(madv.cateye.miowl3): camera events is empty. {'code': 3, 'message': 'serviceToken expired'}
> Driveway F(chuangmi.camera.055a02): camera events is empty. {'code': 3, 'message': 'serviceToken expired'}
> Driveway N(chuangmi.camera.055a02): camera events is empty. {'code': 3, 'message': 'serviceToken expired'}

### Workaround:

Settings - Devices & Services - Xiaomi Miot Auto - Target mi account - CONFIGURE - submit without changing anything.

**Comment by al-one** [comment]
Try [reload integration](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.reload):
```yaml
service: xiaomi_miot.reload
```

**Comment by kodbuzz** [comment]
> Try [reload integration](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.reload):
> 
> ```yaml
> service: xiaomi_miot.reload
> ```

Yes, this is indeed a much more elegant solution.

Personally, I think that would be great if it could be done automatically when necessary. ;)

**Comment by kodbuzz** [comment]
> Try [reload integration](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.reload):
> 
> ```yaml
> service: xiaomi_miot.reload
> ```

Yes, this is indeed a much more elegant solution.

Personally, I think that would be great if it could be done automatically when necessary. ;)

**Comment by kodbuzz** [comment]
> Try [reload integration](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.reload):
> 
> ```yaml
> service: xiaomi_miot.reload
> ```

UPDATE:

I have encountered the same issue again today(June 14th, 2022), I tried to get it fixed the elegant way but unfortunately, it was not working, not sure if it needs to restart to take effect but tapping on CONFIGURE button under integrations immediately did the trick without a restart.
