### ISSUE TITLE
米家云端登录接口问题

### ISSUE THREAD

**Issue by FragranceHUST** [al-one/hass-xiaomi-miot#613]
登陆时的数据采用了RC4加密，该加密算法和相关参数是如何获取到的呢？

**Comment by al-one** [comment]
- 登陆账号相关接口没有用到RC4加密
- https://github.com/squachen/micloud
- https://github.com/al-one/hass-xiaomi-miot/blob/master/custom_components/xiaomi_miot/core/xiaomi_cloud.py
