### ISSUE TITLE
米家智能门锁加入homekit的问题

### ISSUE THREAD

**Issue by googooog** [al-one/hass-xiaomi-miot#615]
大佬你好，目前通过插件可以看到HA里面锁的状态，在homekit里可以看到门锁（人体传感器），但是开关门homekit里面的传感器没有任何反应

请问需要特别设置吗？

**Comment by al-one** [comment]
本插件因为采用轮询的方式更新设备状态，因此无法实时获取门锁触发的各种事件，请参考：
- https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-909031222
