### ISSUE TITLE
米家集成的一个新风机偶尔会出现不受控，麻烦看看

### ISSUE THREAD

**Issue by xiaoluozhou** [al-one/hass-xiaomi-miot#616]
相关错误是：
此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.fan
Source: custom_components/xiaomi_miot/__init__.py:1797
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 11:08:25 (2 occurrences)
Last logged: 11:10:04

书房新风(1245.airfresh.mini2): Set miot property {'did': '242122877', 'siid': 2, 'piid': 1, 'value': False} failed, result: {'did': '242122877', 'siid': 2, 'piid': 1, 'code': -704220043, 'exe_time': 0}
书房新风(1245.airfresh.mini2): Set miot property {'did': '242122877', 'siid': 2, 'piid': 5, 'value': 0} failed, result: {'did': '242122877', 'siid': 2, 'piid': 5, 'code': -704220043, 'exe_time': 0}

实体相关信息是：
preset_modes: 
percentage: 20
percentage_step: 20
preset_mode: null
model: [1245.airfresh.mini2](https://home.miot-spec.com/s/1245.airfresh.mini2)
lan_ip: 
mac_address: 
entity_class: MiotFanEntity
home_room: 
miot_type: urn:miot-spec-v2:device:air-fresh:0000A012:1245-mini2:1
air_fresh.on: true
air_fresh.fault.error: -704220043 Property value error
air_fresh.fan_level: 0
air_fresh.heat_level: 0
panel_led.led.error: -704220043 Property value error
filter-12.filter_life_level: 33
alarm: true
physical_controls_locked: false
filter.filter_life_level: 56
state_updater: cloud
sub_entities: filter-4.filter_life_level-1, filter-12.filter_life_level-1, physical_controls_locked-10.physical_controls_locked-1
friendly_name: 书房新风 Air Fresh
supported_features: 1

**Comment by al-one** [comment]
请尝试为该设备添加[自定义选项](https://github.com/al-one/hass-xiaomi-miot/issues/600)：`miot_local: true`
<img width="396" alt="xiaomi miot customizing" src="https://user-images.githubusercontent.com/4549099/170473563-7563241b-3f42-44b0-bb9e-c292a58493f6.png">

**Comment by xiaoluozhou** [comment]
不行，添加miot_local后就直接离线了，应该是不能走本地吧

**Comment by al-one** [comment]
本地不可用，且云端报错`-704220043`(属性值错误)。那插件也无能为力了。

**Comment by xiaoluozhou** [comment]
那估计是设备的稳定性导致的，辛苦你的付出，谢谢
