### ISSUE TITLE
关于米家直流变频落地扇2在homekit上显示开关已开启的问题

### ISSUE THREAD

**Issue by DFOUD** [al-one/hass-xiaomi-miot#617]
我设置完成添加到homekit后显示开关已开启（无论风扇已经关闭）
查看后是直流风和自然风模式开关
目的是为了解决不在homekit上显示一个开关已开启的问题
因为我不是计算机专业，看不太懂代码。
所以我想提问：如何把模式设置成一个开关，开代表直流风，而关闭代表自然风，这样就能使用一个开关控制模式切换，homekit上也不会一直显示一个开关已开启
![IMG_6194](https://user-images.githubusercontent.com/44726767/170807493-27d7c6f4-2e29-4dd9-9889-fa65c0b327e7.PNG)
![IMG_6193](https://user-images.githubusercontent.com/44726767/170807498-dd46853a-09d4-4dce-b7aa-da0b73ba9780.PNG)

**Comment by al-one** [comment]
风扇型号是[`dmaker.fan.p10`](https://home.miot-spec.com/s/dmaker.fan.p10)吗？请提供下[开发者工具](https://my.home-assistant.io/redirect/developer_states)中该设备所有实体的属性。

**Comment by DFOUD** [comment]
> 风扇型号是[`dmaker.fan.p10`](https://home.miot-spec.com/s/dmaker.fan.p10)吗？请提供下[开发者工具](https://my.home-assistant.io/redirect/developer_states)中该设备所有实体的属性。

![image](https://user-images.githubusercontent.com/44726767/170882358-5c89030a-970c-43b8-8b1e-e7de3281361d.png)

**Comment by al-one** [comment]
homekit中显示的控件是由HA的[homekit集成](https://www.home-assistant.io/integrations/homekit)适配的，插件无能为力。

**Comment by weiyideai520** [comment]
我的也是，有办法屏蔽这个属性吗？

**Comment by DFOUD** [comment]
> 我的也是，有办法屏蔽这个属性吗？

可以‘‘曲线救国’’将模式切换开关分离，然后不显示状态即可

**Comment by al-one** [comment]
请尝试更新到master分支，并为你的风扇添加自定义选项：`disable_preset_modes: true`。
![xiaomi miot fan](https://user-images.githubusercontent.com/4549099/172308638-c8af1ffb-9677-4973-917b-7718db208bd1.png)
