### ISSUE TITLE
The main device of Mi Home Security Camera 360° 1080P(192.168.1.52) is still not ready after 30 seconds!

### ISSUE THREAD

**Issue by tbarbette** [al-one/hass-xiaomi-miot#619]
Hi all!

I've got this error repeating and I can't get the picture from the camera:

`2022-05-28 09:43:59 ERROR (MainThread) [custom_components.xiaomi_miot_raw] The main device of Mi Home Security Camera 360° 1080P(192.168.1.52) is still not ready after 30 seconds!`

Any idea what should I look for? I used the UI based configuration. I can view the camera in the Xiaomi app without any problem.

**Comment by al-one** [comment]
`custom_components.xiaomi_miot_raw` is not this component.
