### ISSUE TITLE
当前时间版本不支持chuangmi.camera.036a02

### ISSUE THREAD

**Issue by nmweizi** [al-one/hass-xiaomi-miot#62]
当前时间版本不支持chuangmi.camera.036a02
设置后没有识别到设备
本地控制模式

**Comment by al-one** [comment]
在[miot-spec](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:camera:0000A01C:chuangmi-036a02:1)中未发现名为`start-hls-stream`及`start-rtsp-stream`的action，因此不支持您的设备。

https://github.com/al-one/hass-xiaomi-miot/issues/11#issuecomment-770642627
https://github.com/al-one/hass-xiaomi-miot/issues/11#issuecomment-774625999
https://github.com/al-one/hass-xiaomi-miot/issues/60#issuecomment-819435571

**Comment by nmweizi** [comment]
看到有这个，Start P2P Stream能用吗?

**Comment by al-one** [comment]
用不了
