### ISSUE TITLE
小爱音箱无法静默执行

### ISSUE THREAD

**Issue by chikehe** [al-one/hass-xiaomi-miot#621]
已经参考了 #180 中提到的解决办法，但音箱仍然会回复

**Comment by chikehe** [comment]
发现我还在用0.5.4 先升级一下看看

**Comment by chikehe** [comment]
发现虽然开发者模式中、脚本测试时都能静默执行，但实际使用触发脚本时会随机出现无法静默的情况

**Comment by al-one** [comment]
请提供小爱音箱型号、脚本yaml，以及执行后的音箱[实体属性](https://my.home-assistant.io/redirect/developer_states)。
