### ISSUE TITLE
可以增加小米人脸解锁X门锁的支持么？

### ISSUE THREAD

**Issue by lypiaoling** [al-one/hass-xiaomi-miot#623]
型号是[lumi.lock.bmcn05](https://home.miot-spec.com/s/lumi.lock.bmcn05)   谢谢

**Comment by al-one** [comment]
已支持，不过由于插件的轮询机制，门锁事件无法实时触发。
另外最新的提交中修复了该门锁的门铃截图，可以更新至master分支体验。
