### ISSUE TITLE
🥶 lumi.acpartner.mcn04 空调伴侣 本月耗电量、今日耗电量数据为0

### ISSUE THREAD

**Issue by dofine** [al-one/hass-xiaomi-miot#625]
![CleanShot 2022-05-31 at 13 39 28@2x](https://user-images.githubusercontent.com/440101/171187320-76090d0d-1404-4291-a1f8-9f96870d3ca4.png)

如图，另一个插排的本月耗电量数据与米家 app 显示一致。

另外，插件汇报的空调伴侣总耗电量与米家app历史月份加和的数据是一致的。

![CleanShot 2022-05-31 at 13 39 51@2x](https://user-images.githubusercontent.com/440101/171187400-250e44a1-bdec-4831-9018-6ae7ddc081ab.png)

**Comment by x1983** [comment]
确认此问题确实存在，米家空调伴侣Pro【lumi.acpartner.mcn04】生成的传感器，其中的本月与当日耗电量都为0，而sensor.lumi_mcn04_ad46_power_consumption以及sensor.lumi_mcn04_ad46_power_consumption_2的单位为Wh，实际为kWh，我知道可以自定义，可否官方帮忙修正一下。此空调伴侣Pro以及酷金空调一并已经共享了。

**Comment by al-one** [comment]
与修复，请更新至master分支

**Comment by x1983** [comment]
![image](https://user-images.githubusercontent.com/43801781/192453591-27247801-e8dc-445c-a8ef-fb5604bb3a33.png)
power_consumption 单位仍然是Wh，应该是kWh才对啊

**Comment by al-one** [comment]
`power_consumption`属性来自[miot-spec](https://home.miot-spec.com/spec/lumi.acpartner.mcn04)，该设备的规格中未定义其用电量属性的单位，因此无法确认它的单位。

**Comment by x1983** [comment]
> `power_consumption`属性来自[miot-spec](https://home.miot-spec.com/spec/lumi.acpartner.mcn04)，该设备的规格中未定义其用电量属性的单位，因此无法确认它的单位。

其值就是历月的用电量的总和，在米家里面是度，这里改为kWh是正确的。

**Comment by al-one** [comment]
`power_consumption`属性单位已修正。
