### ISSUE TITLE
小米智慧攝影機雲台版2K Pro無法使用

### ISSUE THREAD

**Issue by a000a498** [al-one/hass-xiaomi-miot#626]
我將攝影機透過Miot Auto 整合進去HA
但是都沒辦法顯示畫面
![image](https://user-images.githubusercontent.com/33992911/171222330-ceeb2d43-a008-4afb-8ac9-d5db0e9d1d02.png)
提取到http地址,也顯示拒絕存取
![image](https://user-images.githubusercontent.com/33992911/171222244-f0017f7c-3095-49a9-9a25-77120e6d6811.png)

![image](https://user-images.githubusercontent.com/33992911/171223038-50626131-712b-452b-8627-6c45bf27c9c8.png)

**Comment by al-one** [comment]
> stream_http_status: 403
> stream_http_reason: Forbidden

流地址拒绝访问，插件无能为力。

**Comment by a000a498** [comment]
> > stream_http_status: 403
> 
> > stream_http_reason: Forbidden
> 
> 
> 
> 流地址拒绝访问，插件无能为力。

只有最新的產品才會限制嗎

**Comment by al-one** [comment]
接入米家的很多摄像头都有这个问题，原因未知。
目前只能做到在米家开启“看家助手”后，通过`motion_event`实体看到移动侦测截图，或者少数型号的摄像头能看到几秒的回放。
