### ISSUE TITLE
cover.py里有个bug

### ISSUE THREAD

**Issue by kiethrios** [al-one/hass-xiaomi-miot#628]
在配aqara晾衣杆的升降的时候发现的。return这里要改成

```python
    @property
    def is_closed(self):
        """ Most of Xiaomi covers does not report position as 0 when they are fully closed.
            It can be 0, 1, 2... So we consider it closed when it is <= 3. The _current_position
            has been converted so it is always percentage. (#227) """
        return int(self.current_cover_position) <= 3`
```
int()强转成int，不然会报type error

然后dryer属性好像用不了，或者要通过什么方式？再加一个实例heat吗？感觉好像不是这么搞的。望指教

**Comment by al-one** [comment]
这不是本项目的代码。。。
本项目代码如下：
https://github.com/al-one/hass-xiaomi-miot/blob/430bcd8c5ea6c92b2af762b15a032a95a143d3b5/custom_components/xiaomi_miot/cover.py#L211-L222
