### ISSUE TITLE
小爱音箱实体不可用

### ISSUE THREAD

**Issue by nmweizi** [al-one/hass-xiaomi-miot#629]
- 型号：xiaomi.wifispeaker.s12
- media_player.xiaomi_s12_cadb_play_control 实体状态是不可用。
- 本地模式
- 添加后可以获取小爱设备版本
```
固件：1.54.1@Linux
```

**Comment by nmweizi** [comment]
云

**Comment by love768952693** [comment]
我是状态不能同步，物理按钮或者小米APP播放后，hass播放按钮的状态是不同步更新的。
