### ISSUE TITLE
xiaomi camera 360 Unable to discover the device

### ISSUE THREAD

**Issue by peppenamir** [al-one/hass-xiaomi-miot#63]
this is my log
Logger: custom_components.xiaomi_miot
Source: custom_components/xiaomi_miot/__init__.py:733
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 15:53:02 (1 occurrences)
Last logged: 15:53:02

and this is my yaml configuration

xiaomi_miot:
  username: xxxxxxx@xxxxxxl.com
  password: xxxxxxxxxxxx

camera.xiaomi_miot_camera_control:
  video_attribute: 1
  keep_streaming: true
  check_lan: true

Got MiioException while fetching the state for Xiaomi Miot Camera Control: {'code': -9999, 'message': 'user ack timeout'}
where am I wrong?

**Comment by al-one** [comment]
`Add devices using Mi Account`

**Comment by peppenamir** [comment]
I did, but it doesn't detect anything, can you send me a link with a tutorial on how to integrate it? maybe I'm wrong something, thanks

**Comment by al-one** [comment]
![](https://pic1.zhimg.com/v2-9519f4545d2a91ad9f35d308738d25ec_r.jpg)
**Include** the model of your camera and **exclude** empty Wifi SSID/BSSID.

**Comment by peppenamir** [comment]
thank you so much !! for all
