### ISSUE TITLE
Xiaomi mop 2 pro

### ISSUE THREAD

**Issue by antoweb** [al-one/hass-xiaomi-miot#631]
Hello can i ask another help?
Now works all good but i have a question:
The first time i have configured a room cleaning script on HA in the Xiaomi app I saw just before the cleaning started, the area that will be cleaned was highlighted. Now this doesn't happen anymore. Is it possible to highlight in the xiaomi app the area that is going to be cleaned when the vacuum cleaner starts?

**Comment by al-one** [comment]
This component cannot control the map display of MiHome.
