### ISSUE TITLE
使用HomeKit控制空调伴侣无法调节风速

### ISSUE THREAD

**Issue by MartialBE** [al-one/hass-xiaomi-miot#637]
使用HomeKit控制空调伴侣无法调节风速

HomeKit有发送指令，但是 miot没有执行。

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/42402987/172507957-00127e31-e636-4002-af48-040cbf20588c.png">

**Comment by al-one** [comment]
请更新到master分支后重试，如果仍然无法控制风速，请提供操作后的debug日志。
