### ISSUE TITLE
ned help white domain.your_entity_id

### ISSUE THREAD

**Issue by Golab** [al-one/hass-xiaomi-miot#64]
Hello I'm using HACS I'm trying to get your integration to work my question is where can I find
domain.your_entity_id on my HA
I get this error
expected a dictionary for dictionary value @ data['customize']['domain.your_entity_id']

this is how my customize.yaml is setup

![cus](https://user-images.githubusercontent.com/1252745/115709530-9fa5b080-a371-11eb-8002-aa2c09e33c55.jpg)

**Comment by al-one** [comment]
**Recommended** [Customization Using The UI](https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui):

> [⚙️ Configuration](https://my.home-assistant.io/redirect/config) > 🖌 Customize > 🔍 Select Entity > Add Other Attribute

**Comment by al-one** [comment]
```yaml
domain.your_entity_id:
  miot_cloud: true
```

**Comment by Golab** [comment]
Can you please take a picture of customize.yaml white camera setup and what it needs to change in customize.yaml

**Comment by al-one** [comment]
If you `Add devices using Mi Account`, Maybe you don't need to modify customize.yaml.
https://github.com/al-one/hass-xiaomi-miot/issues/63#issuecomment-824681702
