### ISSUE TITLE
米家智能插座2蓝牙网关版 当前功率显示问题

### ISSUE THREAD

**Issue by 520xcy** [al-one/hass-xiaomi-miot#640]
![image](https://user-images.githubusercontent.com/18565637/172755070-14b7419d-4592-4fe7-942f-2911b9aa5998.png)
实际应该是2W，读取到的数据是0.02

**Comment by al-one** [comment]
- #534

该设备在云端模式下获取功率数值会比真实数据小100倍，建议通过自动模式或本地模式集成，如果它与HA不在一个局域网环境，请参考 https://github.com/al-one/hass-xiaomi-miot/issues/534#issuecomment-1105475576 自定义实体。

**Comment by 520xcy** [comment]
多谢，完美解决
