### ISSUE TITLE
Fan Speed - Mi Robot Vacuum 1C (dreame.vacuum.mc1808)

### ISSUE THREAD

**Issue by rogodra** [al-one/hass-xiaomi-miot#645]
Hello, would there be the option to select the fan speed in the Mi Robot Vacuum 1C ([dreame.vacuum.mc1808](https://home.miot-spec.com/spec/dreame.vacuum.mc1808))?

**Comment by al-one** [comment]
Upgrade to master branch and try.

**Comment by rogodra** [comment]
Hi, thanks, it works fine. Although the names come out in Chinese.

安静  ->  Silent
标准  ->  Standard
中档  ->  Strong
强力  ->  Turbo

**Comment by al-one** [comment]
Upgrade to master again.

**Comment by rogodra** [comment]
> Upgrade to master again.

Hello, it continues to come out in Chinese.

**Comment by al-one** [comment]
```yaml
#​ configuration.yaml​
​xiaomi_miot​:
  ​language​: ​en
```

**Comment by al-one** [comment]
@pdx0  Please copy again, there is an invisible character before `:`.
