### ISSUE TITLE
ptx mash 智能开关控制过于缓慢

### ISSUE THREAD

**Issue by rufengsuixing** [al-one/hass-xiaomi-miot#646]
智能开关接入方式为小爱音箱mash
使用本插件控制大概有两秒延迟或更久，而且有时候状态更新不对
使用隔壁的插件可以做到无延迟感知控制
我想知道这中间有什么区别，希望作者改进一下
隔壁已经很少更新了，还是希望支持一下活跃的作者的

**Comment by al-one** [comment]
请讲此设备通过米家APP共享给我`143050915`，并加群联系我。
