### ISSUE TITLE
无法登陆，通过网页登陆mi.com是正常的

### ISSUE THREAD

**Issue by weiyideai520** [al-one/hass-xiaomi-miot#649]
'utf-8' codec can't decode byte 0xea in position 885237: invalid continuation byte

**Comment by al-one** [comment]
该报错日志看起来与插件和网络无关，请提供更详细的日志。

**Comment by weiyideai520** [comment]
此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.config_flow
Source: custom_components/xiaomi_miot/config_flow.py:141
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 14:07:25 (1 occurrences)
Last logged: 14:07:25

Setup xiaomi cloud for user: 13135214040 failed: 'utf-8' codec can't decode byte 0xea in position 885237: invalid continuation byte

**Comment by xfc913** [comment]
我也是相同的提示，等过很多天，一直是登录不进去，网页访问登录正常。

**Comment by AddIcechan** [comment]
同样的问题

**Comment by xfc913** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by al-one** [comment]
请提供具体报错日志。

**Comment by AddIcechan** [comment]
> 

env: 威联通 docker，ha
version：v0.6.7

error:

此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.config_flow
Source: custom_components/xiaomi_miot/config_flow.py:141
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 01:47:10 (1 occurrences)
Last logged: 01:47:10

Setup xiaomi cloud for user: xxxxxx@xxx.com failed: Login to xiaomi error: &&&START&&&{"result":"error","qs":"%3Fsid%3Dxiaomiio%26_json%3Dtrue","code":70016,"captchaUrl":null,"callback":"https://sts.api.io.mi.com/sts","description":"登录验证失败","location":"","securityStatus":0,"pwd":0,"_sign":"0psXfr43eNI0IX6q9Suk3qWbRqU=","sid":"xiaomiio","desc":"登录验证失败"}

**Comment by AddIcechan** [comment]
@al-one 
env: 威联通 docker，ha
version：v0.6.7

error:

此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.config_flow
Source: custom_components/xiaomi_miot/config_flow.py:141
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 01:47:10 (1 occurrences)
Last logged: 01:47:10

Setup xiaomi cloud for user: [xxxxxx@xxx.com](mailto:xxxxxx@xxx.com) failed: Login to xiaomi error: &&&START&&&{"result":"error","qs":"%3Fsid%3Dxiaomiio%26_json%3Dtrue","code":70016,"captchaUrl":null,"callback":"[https://sts.api.io.mi.com/sts","description":"登录验证失败","location":"","securityStatus":0,"pwd":0,"_sign":"0psXfr43eNI0IX6q9Suk3qWbRqU=","sid":"xiaomiio","desc":"登录验证失败"}](https://sts.api.io.mi.com/sts%22,%22description%22:%22%E7%99%BB%E5%BD%95%E9%AA%8C%E8%AF%81%E5%A4%B1%E8%B4%A5%22,%22location%22:%22%22,%22securityStatus%22:0,%22pwd%22:0,%22_sign%22:%220psXfr43eNI0IX6q9Suk3qWbRqU=%22,%22sid%22:%22xiaomiio%22,%22desc%22:%22%E7%99%BB%E5%BD%95%E9%AA%8C%E8%AF%81%E5%A4%B1%E8%B4%A5%22%7D)

**Comment by al-one** [comment]
之前也有用户反馈过，修改密码后即可正常登录，具体原因未知。

**Comment by tenderop** [comment]
配置小米账户
⚠️ The login of Xiaomi account needs security verification. Click here to continue!
本次登陆小米账号需要安全验证，点击这里继续！
改了密码也不行，这个怎么破
Setup xiaomi cloud for user: 252xxxx failed: Login to xiaomi error: &&&START&&&{"notificationUrl":"https://account.xiaomi.com/identity/authStart?sid=passport&context=M_rS-LyBzqyRUaWk---------------------------------------省略----------------------Vd8z_A&_locale=zh_CN","result":"ok","code":0,"captchaUrl":null,"description":"成功","location":"","securityStatus":16,"pwd":0,"child":0,"desc":"成功"}

**Comment by xfc913** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by xfc913** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
