### ISSUE TITLE
climate.zhimi_heater_za1 all sensors reports '0' and cant be toggled

### ISSUE THREAD

**Issue by minskmail** [al-one/hass-xiaomi-miot#65]
Hi, climate.zhimi_heater_za1 all sensors reports '0' and cant be toggled

![image](https://user-images.githubusercontent.com/25284132/115772052-57a97c80-a3b7-11eb-85f8-d3dbfec698c9.png)

**Comment by al-one** [comment]
You need enable miot_cloud or `Add devices using Mi Account`.

**Comment by minskmail** [comment]
> You need enable miot_cloud or `Add devices using Mi Account`.

Yuup. My fault. Via mi account it works. Thanks
