### ISSUE TITLE
米家人体传感器2一段时间后失效

### ISSUE THREAD

**Issue by gwj0323** [al-one/hass-xiaomi-miot#653]
刚绑定时正常，可以识别人物移动，大约十分钟后就不行了，motion sensor 永远是未触发，但motion Sensor trigger正常，需要重载集成后才可恢复，然后10分钟左右又不行了

**Comment by gwj0323** [comment]
model: lumi.motion.bmgl01
lan_ip: 36.5.121.161
mac_address: 54:EF:44:C3:D7:3C
entity_class: BleBinarySensorEntity
home_room: 我的家 卧室
miot_type: urn:miot-spec-v2:device:motion-sensor:0000A014:lumi-bmgl01:1
motion_sensor.illumination: 2
battery_level: 100
state_updater: cloud
trigger_time: 1655363679
trigger_at: '2022-06-16T15:14:39+08:00'
illumination: 256
no_motion_seconds: 0
light_strong: true
illumination_level: strong
state_property: no_motion_duration-2-2
sub_entities:
  - trigger_at
  - light_strong
  - battery-3.battery_level-1
  - motion_sensor-2.illumination-1
no_motion_duration-2-2: 2
device_class: motion
friendly_name: Mi Motion Sensor 2 Motion Sensor
supported_features: 0
no_motion_duration-2-2.error: '-704220043 Property value error'

**Comment by 5869251** [comment]
我也发现了这个问题

**Comment by kingwap99** [comment]
往前回推幾個版本, 問題似乎還是存在.
看來是米家 app 方, 有變更了些什麼地方的樣子

**Comment by home110120** [comment]
同样问题 传感器灯亮的时候 HA里面sensor state没有变化

**Comment by naiver79** [comment]
是小米服务器更新导致的吗？ 只有小米人体2有这个问题，始终没有触发，aqare和青萍都没有问题。

**Comment by jacky86669003** [comment]
有没有解决的办法呢？

**Comment by kingwap99** [comment]
> 有没有解决的办法呢？

就 alexxit 的套件, 兼著用呀, 那邊可行用那邊呀.
然後 alexxit 本家的套件目前不支持 中樞網關, 但有位大大, 接手摩改了一個版本.
https://github.com/zvldz/XiaomiGateway3
目前用起來, 還算正常

**Comment by 13860605362** [comment]
> > 有没有解决的办法呢？
> 
> 就 alexxit 的套件, 兼著用呀, 那邊可行用那邊呀. 然後 alexxit 本家的套件目前不支持 中樞網關, 但有位大大, 接手摩改了一個版本. https://github.com/zvldz/XiaomiGateway3 目前用起來, 還算正常

这个套件可以支持中枢网关（ZSWG01CM）吗？

**Comment by wolnlow** [comment]
根据no_motion_seconds属性判断吧！

**Comment by kingwap99** [comment]
> 根据no_motion_seconds属性判断吧！

感謝
