### ISSUE TITLE
请问小白智慧门blade star可以接入miot auto吗？（希望功能更全）

### ISSUE THREAD

**Issue by arthurfsy** [al-one/hass-xiaomi-miot#654]
hassbian链接;https://bbs.hassbian.com/thread-13033-1-1.html
最近入手了创米的小白智慧门blade star，听大门安装师傅说是深圳第三家安装
目前已通过miot auto 成功连接小白智慧门，但是能触发的动作好像比较少
麻烦大佬能够提供支持，增加新的属性Properties，以便于自动化触发。感激不尽！
对应[miot-spec.com](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:door:0000A041:chuangmi-515a01:3)介绍如下：
[小白智慧门Blade Star系列 - 产品规格 - Xiaomi Miot Spec (miot-spec.com)](https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:door:0000A041:chuangmi-515a01:3)

**Comment by arthurfsy** [comment]
发现开门后，lock_key_id状态发生变化，且通知比较稳定，已经设置lock_key_id作为自动化的触发条件。

**Comment by al-one** [comment]
插件默认的轮询时间比较长，如果你想延迟小点，可以为其[添加自定义选项](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774)`interval_seconds: 10`
