### ISSUE TITLE
小米无线开关能识别但是不能添加使用吗？

### ISSUE THREAD

**Issue by SamuelReeves** [al-one/hass-xiaomi-miot#659]
最近入手了小米的无线开关双键版本，XMWXKG01YL，协议是蓝牙的，在蓝牙网关和蓝牙mesh网关里都能正常接入。
添加插件添加的时候能正常显示有这个设备，但是点击提交后ha里并没有这个设备。
我看支持列表里是有小米开关的，是这个开关还没有适配吗？

**Comment by al-one** [comment]
本插件无法很好的支持无线开关等要求实时触发的设备。
