### ISSUE TITLE
Different number of devices initially found and finally added!

### ISSUE THREAD

**Issue by agagelis** [al-one/hass-xiaomi-miot#66]
Great Integration! I have a problem though. while I installed it and it finds 12 devices initially only nine appear in my configiration.
I am adding here a link of the initially found devices and finally.
https://photos.app.goo.gl/7z3ZrSysPuvWqP288
https://photos.app.goo.gl/UKDAm9NYTWJf8Z9y6
Thanks in advance.

**Comment by al-one** [comment]
[lumi.sensor_switch.v2](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:remote-control:0000A021:lumi-v2:1) and [xiaomi.repeater.v2](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:repeater:0000A037:xiaomi-v2:1) have no any properties in miot-spec.
