### ISSUE TITLE
小米智能插线板2的功耗信息无法在HA自带的“能源”仪表盘中识别添加

### ISSUE THREAD

**Issue by wdmywm3** [al-one/hass-xiaomi-miot#660]
设备信息在此：https://home.miot-spec.com/s/qmi.plug.psv3
设备在auto中添加正常，信息显示正常，可以看到设备的功耗信息
但通过ha自带的“能源”添加用电实体时，发现该设备的功耗实体无法被“能源”识别
而如米家智能插座2蓝牙网关版 https://home.miot-spec.com/s/chuangmi.plug.212a01
或米家空调伴侣2 https://home.miot-spec.com/s/lumi.acpartner.mcn02
这两个设备下的功耗实体，则可以正常被识别并添加到HA自带的“能源”仪表盘中
新增：仔细看了一下，发现实际上识别也有一定错误
正确识别的只有当前功率一项，其他的如月度用电的单位有误（应为KWh），今日用电一项没有显示，电压等识别显示也有些问题
可能无法在能源仪表盘添加的原因也是来源于此

**Comment by wdmywm3** [comment]
新增：仔细看了一下，发现实际上识别也有一定错误
正确识别的只有当前功率一项，其他的如月度用电的单位有误（应为KWh），今日用电一项没有显示，电压等识别显示也有些问题
可能无法在能源仪表盘添加的原因也是来源于此

**Comment by ilazycat** [comment]
米家智能插座2蓝牙网关版 https://home.miot-spec.com/s/chuangmi.plug.212a01 的功耗显示好像也有些问题，不知道是最近更新了固件导致的还是一直存在。

Electric power-5-6  136

功率应该是136w，但是页面显示和历史中均显示 1.36w

**Comment by al-one** [comment]
@wdmywm3 请提供开发者工具中相关实体的[属性](https://my.home-assistant.io/redirect/developer_states)。

**Comment by al-one** [comment]
@ilazycat
- #534
- #640

该设备([chuangmi.plug.212a01](https://home.miot-spec.com/s/chuangmi.plug.212a01))在云端模式下获取功率数值会比真实数据小100倍，建议通过自动模式或本地模式集成，如果它与HA不在一个局域网环境，请参考 https://github.com/al-one/hass-xiaomi-miot/issues/534#issuecomment-1105475576 自定义实体。

**Comment by ilazycat** [comment]
@al-one 发现这个问题了，不过我有多个插座所以自定义实体比较麻烦。我后来是通过增加 device_customizes 来实现的，还没来得及回复 comment。

```
xiaomi_miot:
  device_customizes:
    chuangmi.plug.212a01:electric_power:
      value_ratio: 1
```

**Comment by kklod** [comment]
> @wdmywm3 请提供开发者工具中相关实体的[属性](https://my.home-assistant.io/redirect/developer_states)。

![Uploading image.png…]()
遇到一样的问题……

**Comment by kklod** [comment]
`    # 智能插座用电
sensor.qmi_psv3_2f71_power_consumption: 
  unit_of_measurement: kWh
  device_class: energy
  state_class: total_increasing
  icon: mdi:counter
  last_reset: sensor.qmi_psv3_2f71_power_consumption`

customize.yaml 添加以上参数，问题解决！
