### ISSUE TITLE
No Fan Speed option Dreame F9

### ISSUE THREAD

**Issue by Smartzeug** [al-one/hass-xiaomi-miot#663]
Hello guys,
I can't see a fan speed option for my dreame f9. 
Is this normal or did I miss something?

![Unbenannt](https://user-images.githubusercontent.com/88797584/174595335-ddf3e781-c06e-4da4-a93c-1f7ed0d2b228.png)

cheers

**Comment by al-one** [comment]
Is [dreame.vacuum.p2008](https://home.miot-spec.com/s/dreame.vacuum.p2008) ?
Show me the [state attributes](https://my.home-assistant.io/redirect/developer_states) of this vacuum.

**Comment by al-one** [comment]
Show me the [state attributes](https://my.home-assistant.io/redirect/developer_states) in [developer tools](https://my.home-assistant.io/redirect/developer_states).

**Comment by Smartzeug** [comment]
> Show me the [state attributes](https://my.home-assistant.io/redirect/developer_states) in [developer tools](https://my.home-assistant.io/redirect/developer_states).

Man sorry for the brain lag. 

Here you go 

battery_level: 100
battery_icon: mdi:battery
model: dreame.vacuum.p2008
lan_ip: 123
mac_address: 123
entity_class: MiotVacuumEntity
exclude_miot_services:
  - consumable
  - annoy
  - remote
  - time
exclude_miot_properties:
  - delete_timer
  - clean_info
  - map_view
  - frame_info
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:dreame-p2008:1
vacuum.status: 2
vacuum.fault: 0
vslam_extend.save_map_status: 1
clean_logs.first_clean_time: 1611658445
clean_logs.total_clean_time: 7499
clean_logs.total_clean_times: 207
clean_logs.total_clean_area: 6647
audio.volume: 75
audio.voice_packet_id: DE
audio.voice_change_state: '{\"id\":\"\",\"state\":\"idle\",\"progress\":0}'
audio.set_voice.error: '-1'
map.map_extend_data.error: '-1'
do_not_disturb.enable: true
do_not_disturb.start_time: '22:00'
do_not_disturb.end_time: '08:00'
vacuum_extend.work_mode: 14
vacuum_extend.cleaning_time: 0
vacuum_extend.cleaning_area: 0
vacuum_extend.cleaning_mode: 0
vacuum_extend.mop_mode: 3
vacuum_extend.waterbox_status: 0
vacuum_extend.task_status: 0
vacuum_extend.clean_extend_data.error: '-1'
break_point_restart-4-11: 1
vacuum_extend.carpet_press: 0
vacuum_extend.serial_number: P20080B21EU04241KF
vacuum_extend.remote_state.error: '-1'
filter.filter_life_level: 16
filter.filter_left_time: 25
brush_left_time-10-1: 75
brush_life_level-10-2: 37
brush_cleaner.brush_left_time: 175
brush_cleaner.brush_life_level: 58
battery.charging_state: 1
state_updater: lan
vacuum.status_desc: Idle
sub_entities:
  - vacuum-2.status-1
  - filter-11.filter_life_level-1
  - filter-11.filter_left_time-2
  - battery-3.battery_level-1
  - battery-3.charging_state-2
  - brush_cleaner-9.brush_left_time-1
  - brush_cleaner-9.brush_life_level-2
  - brush_cleaner-10.brush_left_time-1
  - brush_cleaner-10.brush_life_level-2
miot_action_result:
  did: action-3-1
  siid: 3
  aiid: 1
  out: []
  code: 0
friendly_name: Xiaomi Miot Token Robot Cleaner
supported_features: 13016

**Comment by al-one** [comment]
Please upgrade to master branch and try.

**Comment by Smartzeug** [comment]
Hi, 
it worked, thank you very much. 
But now HACS is asking me to update. 

I will just ignore it then

**Comment by al-one** [comment]
Don't worry, wait for the next release to upgrade.

**Comment by Smartzeug** [comment]
Alright. Closing this issue

**Comment by Smartzeug** [comment]
Fixed
