### ISSUE TITLE
skyrc.pet_waterer.fre1 - didn't get status

### ISSUE THREAD

**Issue by NikDevx** [al-one/hass-xiaomi-miot#67]
Hello
Power switch from `skyrc.pet_waterer.fre1`   doesn't getting status when switch on/off
Always off

**Comment by al-one** [comment]
The property: `on` of the device have no `read` access in [miot-spec](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:pet-drinking-fountain:0000A067:skyrc-fre1:1).

**Comment by NikDevx** [comment]
Switch Status has access":["write","notify"]
Can it write this status somewhere and then use it for get status?

**Comment by al-one** [comment]
Can't.
Maybe you can use [helper entities](https://my.home-assistant.io/redirect/helpers).

**Comment by NikDevx** [comment]
> Can't.
> Maybe you can use [helper entities](https://my.home-assistant.io/redirect/helpers).

Thanks
I will try
