### ISSUE TITLE
米家智能直流变频循环扇 落地式  dmaker.fan.p28 多个数据无法读取到

### ISSUE THREAD

**Issue by gx19970920** [al-one/hass-xiaomi-miot#670]
![image](https://user-images.githubusercontent.com/33535925/175240273-80bf1935-f7df-4e92-a7d6-4db00f360315.png)
如图所示，以下列出的几种属性无法读取到

Dm service.swing updown manual.error
-704030013 Property is not readable
Dm service.swing lr manual.error
-704030013 Property is not readable
Dm service.start left.error
-704030013 Property is not readable
Dm service.start right.error
-704030013 Property is not readable
Dm service.start up.error
-704030013 Property is not readable
Dm service.start down.error
-704030013 Property is not readable
Dm service.back to center.error
-704030013 Property is not readable

**Comment by al-one** [comment]
这些属性在miot-spec.org被厂商标记为不可读，该设备支持本地接入，请尝试通过token接入。

**Comment by gx19970920** [comment]
谢谢大佬
