### ISSUE TITLE
090615.curtain.sidt82 problem after update

### ISSUE THREAD

**Issue by luisarn** [al-one/hass-xiaomi-miot#672]
Hi! I get these errors on both sidt82.
Thanks!
Luis

This error originated from a custom integration.

Logger: custom_components.xiaomi_miot.cover
Source: custom_components/xiaomi_miot/__init__.py:1793
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 4:31:06 PM (84 occurrences)
Last logged: 11:42:27 PM

Curtain 1(090615.curtain.sidt82): Set miot property {'did': '129326765', 'siid': 2, 'piid': 1, 'value': 0} failed: {'code': -9999, 'message': 'user ack timeout'}
Curtain 1(090615.curtain.sidt82): Set miot property {'did': '129326765', 'siid': 2, 'piid': 1, 'value': 2} failed: {'code': -9999, 'message': 'user ack timeout'}
Curtain 1(090615.curtain.sidt82): Set miot property {'did': '129326765', 'siid': 2, 'piid': 1, 'value': 1} failed: {'code': -9999, 'message': 'user ack timeout'}
Curtain 1(090615.curtain.sidt82): Set miot property {'did': '129326765', 'siid': 2, 'piid': 1, 'value': 2} failed: {'code': -30012, 'message': 'busy.'}
Curtain 1(090615.curtain.sidt82): Set miot property {'did': '129326765', 'siid': 2, 'piid': 2, 'value': 100} failed: {'code': -9999, 'message': 'user ack timeout'}

**Comment by al-one** [comment]
> {'code': -9999, 'message': 'user ack timeout'}

The error is returned from the device, there is nothing this component can do.

**Comment by luisarn** [comment]
I'm not sure, just trying to help, using https://github.com/ha0y/xiaomi_miot_raw the curtain works

**Comment by al-one** [comment]
Does this issue still exist in the last release (v0.6.10) ?

**Comment by luisarn** [comment]
Unfortunatelly no:

This error originated from a custom integration.

Logger: custom_components.xiaomi_miot.cover
Source: custom_components/xiaomi_miot/__init__.py:1342
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 10:14:46 AM (1 occurrences)
Last logged: 10:14:46 AM

Curtain 1(090615.curtain.sidt82): Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'curtain.target_position': {'siid': 2, 'piid': 2}}, max_properties: 6/1

**Comment by caoxiaojun521** [comment]
miiocli device --ip xxxxx --token xxxxx raw_command setOperation "[0]"

miiocli device --ip xxxxx --token xxxxx raw_command setOperation "[1]"

miiocli device --ip xxxxx --token xxxxx raw_command setOperation "[2]"

miiocli device --ip xxxxx --token xxxxx raw_command setOperation "[50]"

miiocli device --ip xxxxx --token xxxxx raw_command setOperation "[0, 1, 2]"

The above code has been tested to be able to control 090615.curtain.sidt82, should we merge and update the program?
