### ISSUE TITLE
达阔电蚊香可开启，无法关闭

### ISSUE THREAD

**Issue by wdmywm3** [al-one/hass-xiaomi-miot#673]
产品页面在此：
https://home.miot-spec.com/s/ateai.mosq.dakuo
可以正常开启，开启后电蚊香也会打开，但是无论是直接在设备页面关闭，或者直接调用switch.turn_off服务，都无法关闭电蚊香，电蚊香会一直运行

**Comment by al-one** [comment]
请检查操作关闭后有无该设备相关报错[日志](https://my.home-assistant.io/redirect/logs)。

**Comment by al-one** [comment]
已修复，请更新至master分支后再试。
