### ISSUE TITLE
Roborock S5 Max unavailable sensors and missing attributes

### ISSUE THREAD

**Issue by Axydas** [al-one/hass-xiaomi-miot#675]
Hello,

I am using this integration for my Roborock S5 Max vacuum and I am facing two issues after my last update:
1.  Props clean_area and Props clean_time are unavailble
2.  Under the vacuum vacuum.roborock_s5e_ef8d_robot_cleaner I missed many attributes like props section, filter info, side brush time, main brush time and sensors time

Any clue what is wrong?

Thanks in advance

**Comment by Axydas** [comment]
> Show me the [entity attributes](https://my.home-assistant.io/redirect/developer_states).

Attached

![image](https://user-images.githubusercontent.com/79807389/176130707-0e08c10c-bf02-4fb7-88a2-9d3b9565a9df.png)

**Comment by Axydas** [comment]
> Show me the [entity attributes](https://my.home-assistant.io/redirect/developer_states).

Attributed in Development

![image](https://user-images.githubusercontent.com/79807389/176130934-87f8d39e-bfe2-475e-b3de-a3ce935b5a6b.png)

**Comment by al-one** [comment]
This device has been adapted for local integration, please integrate it in automatic mode.
![xiaomi miot config flow](https://user-images.githubusercontent.com/4549099/176159394-ee2f1c27-76e6-41ec-823c-f9127f61433d.png)

**Comment by Axydas** [comment]
of course this what i done.


i done it again and i have same result

**Comment by al-one** [comment]
Make sure your component are up to date with the latest release.
