### ISSUE TITLE
小米晾衣架接入后出现频繁不再可用问题

### ISSUE THREAD

**Issue by pcj1997** [al-one/hass-xiaomi-miot#677]
插件版本是：V0.6.7
![image](https://user-images.githubusercontent.com/35689683/176357245-787e8e12-3feb-49de-9080-36ecd3fc2e29.png)
频繁出现不可用；

日志：
此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.cover
Source: custom_components/xiaomi_miot/__init__.py:1336
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 13:16:18 (3 occurrences)
Last logged: 13:17:33

Mijia Smart Clothes Drying Rack(hyd.airer.znlyj4): Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'airer.fault': {'siid': 2, 'piid': 1}, 'airer.motor_control': {'siid': 2, 'piid': 2}, 'airer.current_position': {'siid': 2, 'piid': 3}, 'airer.status': {'siid': 2, 'piid': 4}, 'light.on': {'siid': 3, 'piid': 1}}, max_properties: 8/5

此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.light
Source: custom_components/xiaomi_miot/__init__.py:1336
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 13:12:58 (4 occurrences)
Last logged: 13:17:28

Mijia Smart Clothes Drying Rack(hyd.airer.znlyj4): Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'light.on': {'siid': 3, 'piid': 1}, 'airer.fault': {'siid': 2, 'piid': 1}, 'airer.motor_control': {'siid': 2, 'piid': 2}, 'airer.current_position': {'siid': 2, 'piid': 3}, 'airer.status': {'siid': 2, 'piid': 4}}, max_properties: 8/5

**Comment by pcj1997** [comment]
问题补充：
![image](https://user-images.githubusercontent.com/35689683/176357659-ed786a07-4a19-4671-b87d-e9c70fe175c0.png)
 接入的其他小米设备目前没遇到这个问题；

![image](https://user-images.githubusercontent.com/35689683/176357725-03f8550c-17a3-4067-9cd9-5f289019520b.png)
 为了接入HK后晾衣架状态更合理，在UI上自定义了实体反转了电机状态

**Comment by al-one** [comment]
请更新至master分支后再观察。

**Comment by pcj1997** [comment]
依然会出现这个问题，日志打印如下：
此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.light
Source: custom_components/xiaomi_miot/__init__.py:1342
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 15:57:59 (2 occurrences)
Last logged: 16:00:30

Mijia Smart Clothes Drying Rack(hyd.airer.znlyj4): Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'light.on': {'siid': 3, 'piid': 1}}, max_properties: 6/1

此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.cover
Source: custom_components/xiaomi_miot/__init__.py:1342
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 15:57:05 (3 occurrences)
Last logged: 16:06:05

Mijia Smart Clothes Drying Rack(hyd.airer.znlyj4): Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'airer.fault': {'siid': 2, 'piid': 1}, 'airer.motor_control': {'siid': 2, 'piid': 2}, 'airer.current_position': {'siid': 2, 'piid': 3}, 'airer.status': {'siid': 2, 'piid': 4}, 'light.on': {'siid': 3, 'piid': 1}}, max_properties: 8/5

![image](https://user-images.githubusercontent.com/35689683/176385174-11c59863-f442-4a97-9905-bf27967b9a56.png)

PS：我更新master分支的方式是：在xiaomi_miot集成正常运行的情况下，下载github最新code，然后将新的xiaomi_miot文件夹整个复制替换掉hass上custom_components文件夹里面的的老的xiaomi_miot文件夹，重启hass系统。
请问这种更新方式是否有误？

**Comment by al-one** [comment]
更新方式没有问题，从日志也看得出更新成功了。请尝试在米家APP重新绑定该设备。

**Comment by pcj1997** [comment]
米家APP重新绑定晾衣架之后问题还是没有解决。
而且我发现晾衣架的灯，HA只能控制开启，不能控制关闭了。

![image](https://user-images.githubusercontent.com/35689683/176421806-c5f25617-8167-4022-941a-35fe09211143.png)

日志：
此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.cover
Source: custom_components/xiaomi_miot/__init__.py:1342
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 19:01:51 (4 occurrences)
Last logged: 19:03:51

Mijia Smart Clothes Drying Rack(hyd.airer.znlyj4): Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'airer.fault': {'siid': 2, 'piid': 1}, 'airer.motor_control': {'siid': 2, 'piid': 2}, 'airer.current_position': {'siid': 2, 'piid': 3}, 'airer.status': {'siid': 2, 'piid': 4}, 'light.on': {'siid': 3, 'piid': 1}}, max_properties: 8/5


此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.light
Source: custom_components/xiaomi_miot/__init__.py:1342
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 18:59:30 (7 occurrences)
Last logged: 19:03:36

Mijia Smart Clothes Drying Rack(hyd.airer.znlyj4): Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'light.on': {'siid': 3, 'piid': 1}}, max_properties: 6/1


此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.cover
Source: custom_components/xiaomi_miot/__init__.py:1814
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 19:00:17 (2 occurrences)
Last logged: 19:00:20

Mijia Smart Clothes Drying Rack(hyd.airer.znlyj4): Set miot property {'did': '532696866', 'siid': 2, 'piid': 2, 'value': 2} failed: {'code': -9999, 'message': 'user ack timeout'}
Mijia Smart Clothes Drying Rack(hyd.airer.znlyj4): Set miot property {'did': '532696866', 'siid': 2, 'piid': 2, 'value': 1} failed: {'code': -9999, 'message': 'user ack timeout'}

![image](https://user-images.githubusercontent.com/35689683/176421940-96daf186-e76b-44c6-a7ed-2fdd7efd3e35.png)

**Comment by pcj1997** [comment]
现在master分支的代码有很多bug，基本所有小米设备都是只能打开，无法关闭。目前已经回退到V0.6.7版本。

**Comment by pcj1997** [comment]
V0.6.9版本，目前除小米晾衣架外其他设备均正常。

小米晾衣架依然会频繁出现不可用的问题，日志如下：
此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.cover
Source: custom_components/xiaomi_miot/__init__.py:1342
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 11:16:48 (4 occurrences)
Last logged: 11:19:48

Mijia Smart Clothes Drying Rack(hyd.airer.znlyj4): Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'airer.fault': {'siid': 2, 'piid': 1}, 'airer.current_position': {'siid': 2, 'piid': 3}, 'airer.status': {'siid': 2, 'piid': 4}, 'light.on': {'siid': 3, 'piid': 1}}, max_properties: 7/4


此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.light
Source: custom_components/xiaomi_miot/__init__.py:1342
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 11:02:14 (1 occurrences)
Last logged: 11:02:14

Mijia Smart Clothes Drying Rack(hyd.airer.znlyj4): Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'light.on': {'siid': 3, 'piid': 1}}, max_properties: 6/1

**Comment by pcj1997** [comment]
大佬，麻烦再关注下这个问题

**Comment by pcj1997** [comment]
@al-one

**Comment by al-one** [comment]
> {'code': -9999, 'message': 'user ack timeout'}

报错信息来自设备，插件无能为力。建议尝试[自定义实体](https://github.com/al-one/hass-xiaomi-miot/issues/600)`auto_cloud: true`

**Comment by pcj1997** [comment]
刚才更新到了master分支，发现问题应该解决了，待我观察一晚之后看看。但也有可能是我对openwrt路由器做了一些改动让这个问题不在复现了。
