### ISSUE TITLE
青萍動作和環境光傳感器 反應延遲

### ISSUE THREAD

**Issue by kingwap99** [al-one/hass-xiaomi-miot#678]
青萍動作和環境光傳感器 反應延遲
可以用, 但.....時間落差太到數分鐘.
反觀米家倒是反應快速, 直逼 zigbee.
不確定是否因為小米中樞網關介入的關係
![螢幕擷取畫面 2022-06-29 142127](https://user-images.githubusercontent.com/33337987/176365862-a1857a6c-672d-427a-bf05-e70ae9be5f4f.jpg)
![Screenshot_2022-06-29-14-21-04-357_com xiaomi smarthome](https://user-images.githubusercontent.com/33337987/176365928-686d669e-40ea-46e7-8c4d-73ba22090c27.jpg)

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-909031222
