### ISSUE TITLE
Is there a goto target available for vacuums?

### ISSUE THREAD

**Issue by NicoLeOca** [al-one/hass-xiaomi-miot#679]
Hi,
I use this integration with a [Dreame D9 vaccum](https://home.miot-spec.com/s/dreame.vacuum.p2009).
Using the Miio integration with a Roborock, I can call action to send the robot to specific coordinates.
How is this possible with this integration please?

**Comment by al-one** [comment]
- Use [vacuum.send_command](https://my.home-assistant.io/redirect/developer_call_service/?service=vacuum.send_command) like [xiaomi_miio](https://www.home-assistant.io/integrations/xiaomi_miio#example-on-how-to-clean-a-specific-room) (Only for Roborock).
- https://github.com/al-one/hass-xiaomi-miot/issues/491#issuecomment-1100708607
- https://github.com/al-one/hass-xiaomi-miot/issues/425#issuecomment-1035986355
- https://github.com/al-one/hass-xiaomi-miot/issues/289#issuecomment-988438475

**Comment by NicoLeOca** [comment]
Hi @al-one 
Thanks for trying to help me 

I successfully used call_action to clean rooms and zones.
Home et I am looking for an option to send the vaccum to a specific place, and stay there without having it to clean nor go back to dock.
With roborock, we can do that by giving it the coordinates of the point.

**Comment by al-one** [comment]
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: vacuum.roborock_entity_id
  method: app_goto_target
  params: [x, y]
```

**Comment by NicoLeOca** [comment]
still no effet on the Dreame D9

**Comment by NicoLeOca** [comment]
actually, the zone cleaning (using "areas") does not work with this either
Room cleaning works properly though (using "selects")

**Comment by al-one** [comment]
If you can go to the target point in MiHome, you can use [MiHome mod via vevs](https://github.com/al-one/hass-xiaomi-miot/issues/114#issuecomment-868721912) to get miio logs.
