### ISSUE TITLE
小米空調fan_mode問題

### ISSUE THREAD

**Issue by paul159321** [al-one/hass-xiaomi-miot#682]
你好
今天更新了0.6.9 發現小米空調的fan_mode全部都變成小寫(low,medium,high)
造成無法控制冷氣fan_mode
我重新裝回0.6.7後正常就可正常控制fan_mode!!!
fan_mode的話 需要使用Low,Medium,High

**Comment by al-one** [comment]
由于通过HA的接入空调至HomeKit时，风速模式必须为小写才会在HomeKit中显示风速控件。因此在(https://github.com/al-one/hass-xiaomi-miot/commit/230f1ec01a3548fa99a9da0ead1d86dfc5a410f1) 中将风速模式值改为小写。目前暂不支持改回首字母大写。

**Comment by Theergold** [comment]
所以现在的情况是能在Homekit显示控件,但是没办法控制风速了,那这个风速控件也用不了啊

**Comment by paul159321** [comment]
> 所以现在的情况是能在Homekit显示控件,但是没办法控制风速了,那这个风速控件也用不了啊

我的解決方法是
利用samba或者fileEditor進去 custom_components > xiaomi_miot 然後編輯climate.py
找到set_fan_mode(在559行)
並在560行加入 "fan_mode = fan_mode.capitalize()"

目前對我來說是都正常了

**Comment by al-one** [comment]
我有两个空调伴侣`lumi.acpartner.v2/mcn04`，均需要在`fan_modes`为小写的时候才能在HomeKit显示风速控件，并能正常控制。如果你的不能控制，请告诉我具体型号以及在HA中能否正常控制风速，且观察有无报错[日志](https://my.home-assistant.io/redirect/logs)。

**Comment by Theergold** [comment]
> 我有两个空调伴侣`lumi.acpartner.v2/mcn04`，均需要在`fan_modes`为小写的时候才能在HomeKit显示风速控件，并能正常控制。如果你的不能控制，请告诉我具体型号以及在HA中能否正常控制风速，且观察有无报错[日志](https://my.home-assistant.io/redirect/logs)。

型号的`lumi.acpartner.mcn02`,在HA中无法控制风速,能显示出风速控件,是用选项的时候日志显示
```
2022-07-01 14:25:50 WARNING (SyncWorker_6) [custom_components.xiaomi_miot.climate] Mi Smart Air Conditioner Controller 2(lumi.acpartner.mcn02): Set miot property {'did': '***', 'siid': 3, 'piid': 1, 'value': None} failed: {'code': -32602, 'message': 'Invalid param.'}
```

**Comment by al-one** [comment]
已在最新的提交(https://github.com/al-one/hass-xiaomi-miot/commit/76c78d829710996d4dfdc26c8dea9b294d0c78b4) 中修复，可以更新至master分支，也可以通过下面的方式配置`translations`修复此问题：
```yaml
# configuration.yaml
xiaomi_miot:
  fan_control.fan_level:
    low: low
    medium: medium
    middle: middle
    high: high
```

**Comment by Aes64X** [comment]
已测试，修复。
