### ISSUE TITLE
无法获取空调伴侣设定的当前空调的工作温度

### ISSUE THREAD

**Issue by xtream7** [al-one/hass-xiaomi-miot#686]
![image](https://user-images.githubusercontent.com/97107612/177023341-c6191f50-e6f0-4dff-861c-f84cf13f2e13.png)
如图，无法获取空调伴侣设定的当前空调的工作温度属性current_temperature

**Comment by al-one** [comment]
空调伴侣无温度传感器，无法获取当前温度值，你可以通过[自定义选项](https://github.com/al-one/hass-xiaomi-miot/issues/600)配置`bind_sensor`来绑定温度实体。
![xiaomi miot bind_sensor](https://user-images.githubusercontent.com/4549099/177076285-b445ce9a-fea9-47bb-a350-fec21a898336.png)

**Comment by eunrui** [comment]
> 

wow，非常感谢，配置上了舒服

**Comment by Decwind** [comment]
> bind_sensor

请问这个自定义的菜单在哪里，新版本是不是没有自定义设备这个功能了

**Comment by al-one** [comment]
> 请问这个自定义的菜单在哪里，新版本是不是没有自定义设备这个功能了

https://user-images.githubusercontent.com/4549099/211185592-79daa90d-c5cb-4c9e-829c-12a52fa3eaf0.mp4

**Comment by Decwind** [comment]
> @Decwind 
> 
> > 请问这个自定义的菜单在哪里，新版本是不是没有自定义设备这个功能了
> 
> 
> 
> https://user-images.githubusercontent.com/4549099/211185592-79daa90d-c5cb-4c9e-829c-12a52fa3eaf0.mp4

感谢大佬回复，最新版本还是没找到。已经通过配置customize.yaml解决

climate.lumi_air_v1_2e2c:
  bind_sensor: sensor.xxxxxx

**Comment by SEUZTh** [comment]
> > [@Decwind](https://github.com/Decwind)
> > > 请问这个自定义的菜单在哪里，新版本是不是没有自定义设备这个功能了
> > 
> > 
> > 
> >   
> >     
> >     
> > 
> >     xiaomi-mito-customize.mp4
> 
> 感谢大佬回复，最新版本还是没找到。已经通过配置customize.yaml解决
> 
> climate.lumi_air_v1_2e2c: bind_sensor: sensor.xxxxxx

请问customize.yaml这个文件在哪

**Comment by eunrui** [comment]
> > > [@Decwind](https://github.com/Decwind)
> > > > 请问这个自定义的菜单在哪里，新版本是不是没有自定义设备这个功能了
> > > 
> > > 
> > > ```
> > > xiaomi-mito-customize.mp4
> > > ```
> > 
> > 
> > 感谢大佬回复，最新版本还是没找到。已经通过配置customize.yaml解决
> > climate.lumi_air_v1_2e2c: bind_sensor: sensor.xxxxxx
> 
> 请问customize.yaml这个文件在哪

没有的话，和configuration.yaml同级创建一个
