### ISSUE TITLE
米家新风机，空气净化器实体缺失

### ISSUE THREAD

**Issue by 18018639970** [al-one/hass-xiaomi-miot#688]
米家新风机和空气净化器之前可以控制模式，如自动模式，睡眠模式，在更新插件后消失，只有开关或者调节风速

> 以下是新风机实体

Model
dmaker.airfresh.a1
Lan IP
192.168.123.52
MAC address

Entity class
MiotFanEntity
Home room
卧室
Miot type
urn:miot-spec-v2:device:air-fresh:0000A012:dmaker-a1:1
Air fresh.on
true
Air fresh.mode
0
Air fresh.heater
false
Alarm
true
Physical controls locked
false
Filter.filter life level
50
Filter.filter left time
90
Environment.pm2 5 density
94
Environment.co2 density
780
State updater
cloud
Sub entities
environment-3.pm2_5_density-1, environment-3.co2_density-2, filter-4.filter_life_level-1, filter-4.filter_left_time-2, physical_controls_locked-
5.physical_controls_locked-1

**Comment by al-one** [comment]
点开fan实体弹出卡片即可控制模式
