### ISSUE TITLE
Aqara墙壁开关（单火线双键版）无法获取状态

### ISSUE THREAD

**Issue by Turingmachine01** [al-one/hass-xiaomi-miot#690]
通过物理按键和米家app操作时hass上无法获取状态更新。单键版本可以正常获取更新。
查看状态时有三个error：
switch-3.on.error: '-704002000 Unknown'
switch-3.name.error: '-704002000 Unknown'
switch-3.mode.error: '-704002000 Unknown'

**Comment by al-one** [comment]
已修复，请更新至master分支。

**Comment by Turingmachine01** [comment]
谢谢
