### ISSUE TITLE
无法访问小米API接口

### ISSUE THREAD

**Issue by darknesscho** [al-one/hass-xiaomi-miot#691]
昨晚开始就部分设备掉线,可能是只能云端模式的那些.然后我尝试更新设备列表,结果显示“无法访问小米API接口”

配置小米账户
⚠️ HTTPSConnectionPool(host='account.xiaomi.com', port=443): Max retries exceeded with url: /pass/serviceLogin?sid=xiaomiio&_json=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe59d8f69e0>: Failed to establish a new connection: [Errno -3] Try again'))

插件版本为最新,HASSOS版本为2022.07.0

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/500

建议重启宿主机(`reboot`)。

**Comment by darknesscho** [comment]
重启过了问题依然存在.

**Comment by PhDLuffy** [comment]
Docker版本的HA，在建立容器的时候网络模式选择host而不是桥接，host端口映射本地8123:容器8123
我用桥接模式也出现了这样的问题，改成host模式就可以了。

**Comment by PhDLuffy** [comment]
@al-one 
我发现，网络设置使用bridge，可以正常登陆小米云服务获取设备。
               网络设备使用host，无法访问小米API接口。
但是网络使用bridge，HA自带的homekit，发现不了设备，ios扫码之后，什么设备也没有。

**Comment by al-one** [comment]
网络环境问题，请自行解决。
