### ISSUE TITLE
Pet Feeder (mmgg.feeder.petfeeder)新固件只显示喂食次数

### ISSUE THREAD

**Issue by ocerot** [al-one/hass-xiaomi-miot#692]
小米分别于6月22日和7月4日升级了喂食器固件。之后接入HA后就只能显示喂食次数，手动喂食功能正常。LED状态灯，童锁，粮仓盖检测都获取不到信息了。

![image](https://user-images.githubusercontent.com/49577317/178099696-ab8da8ae-8d06-4b64-a109-16fa83b819bd.png)
![image](https://user-images.githubusercontent.com/49577317/178099724-69ebb0e7-a4f4-4d2f-bf0e-b5fcf007adad.png)

属性
Model
mmgg.feeder.petfeeder
Lan IP
192.168.0.96
MAC address
54:48:E6:0E:XX:XX
Entity class
MiotSensorEntity
Home room
我的家 门厅
Miot type
urn:miot-spec-v2:device:pet-feeder:0000A06C:mmgg-petfeeder:1
State property
pet_feeder.pet_food_left_level
State updater
lan
Event.feedStats
fed_today: 9
fed_week: 109
fed_month: 126
Sub entities
pet_feeder-2.feeding_measure-1, pet_feeder-2.feedstatus-102, pet_feeder-2.reset_desiccant_life-101, physical_controls_locked-300.physical_controls_locked-301, event.feedStats:fed_today, event.feedStats:fed_week, event.feedStats:fed_month
Sensor attributes
clean_days,dryer_days,event.feedStats:fed_today,event.feedStats:fed_week,event.feedStats:fed_month
Binary sensor attributes
wifiledon,keylock,feed_plan,wifi_led,key_lock,outlet_status,door_result
Miio cloud records
event.feedStats:500
Miio event feedStats template
{%- set dat = namespace(today=0,week=0,month=0) %} {%- set tim = now() %} {%- set hour = tim.replace(minute=0, second=0) %} {%- set today = hour.replace(hour=0) %} {%- set week = (today - timedelta(days=7)) | as_timestamp | int(0) %} {%- set month = (today - timedelta(days=tim.day-1)) | as_timestamp | int(0) %} {%- set today = today | as_timestamp | int(0) %} {%- for d in (result or []) %} {%- set t = d.time | default(0) | int(0) %} {%- if t >= month %} {%- set v = (d.value | default('[]') | string | from_json) or [] %} {%- set n = v[0] | default(0) %} {%- if t >= week %} {%- set dat.week = dat.week + n %} {%- if t >= today %} {%- set dat.today = dat.today + n %} {%- endif %} {%- endif %} {%- set dat.month = dat.month + n %} {%- endif %} {%- endfor %} {{ { 'fed_today': dat.today | int(0), 'fed_week': dat.week | int(0), 'fed_month': dat.month | int(0), } }}

小米固件更新内容：
2.1.3.0049
手动更新    2022-06-22
更新内容   
1、新增OTA静默升级；
2、新增夜间提醒免打扰；
3、优化开关上盖检测；
4、新增搅粮叶片使用90天更换提醒；
5、新增解绑定或者删除设备时清除本地数据。

2.1.3.0047
手动更新   2021-07-04
更新内容
1. 优化设备时间校准逻辑
![image](https://user-images.githubusercontent.com/49577317/178099761-50a7d27c-1992-40af-9d97-91a6534c0cc9.png)

**Comment by al-one** [comment]
请升级插件到最新版本，并提供开发者工具中的[实体属性](https://my.home-assistant.io/redirect/developer_states)。

**Comment by ahaghshenas** [comment]
![pet1](https://user-images.githubusercontent.com/39365580/183082324-9f0d3ae1-32af-47b0-a8b6-777aa565ca86.jpg)
![pet2](https://user-images.githubusercontent.com/39365580/183082330-ce449a0c-c8d9-4f92-970b-e89664e1aede.jpg)

I am getting fewer sensors available than there should be.

I am using the latest release of hass-Xiaomi-miot

**Comment by al-one** [comment]
Call this service and find results in HA notifications.
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: sensor.miaomiaoce_t1_5c97_temperature
  method: getprops
  params: []
  throw: true
```

**Comment by ahaghshenas** [comment]
> Call this service and find results in HA notifications.
> 
> ```yaml
> service: xiaomi_miot.send_command
> data:
>   entity_id: sensor.mmgg_petfeeder_xxxx
>   method: getprops
>   params: []
>   throw: true
> ```

Miio command result
[0, 1, 0, 0, 1, 0, 24, 3, 1, 0]

**Comment by licheng5625** [comment]
怪我手贱，升级了固件。。。完蛋了。。。

**Comment by licheng5625** [comment]
[0, 0, 0, 0, 10, 0, 0, 1, 0, 1, 255, 88]

 `service: xiaomi_miot.send_command
data:
  entity_id: sensor.mmgg_petfeeder_xxxx
  method: getprops
  params: []
  throw: true`

**Comment by al-one** [comment]
请更新至master分支。
