### ISSUE TITLE
MiotNumberEntity is overriding deprecated methods on an instance of NumberEntity

### ISSUE THREAD

**Issue by dwd1** [al-one/hass-xiaomi-miot#695]
custom_components.xiaomi_miot.number::MiotNumberEntity is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.
custom_components.xiaomi_miot.number::MiotNumberSubEntity is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.
custom_components.xiaomi_miot.number::MiotNumberActionSubEntity is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.

**Comment by al-one** [comment]
- https://github.com/home-assistant/core/pull/73233
