### ISSUE TITLE
conversation无法输出小爱应答信息

### ISSUE THREAD

**Issue by 65698888** [al-one/hass-xiaomi-miot#698]
小爱音响PRO，conversation无法输出应答信息。
各位有遇到的么？

**Comment by al-one** [comment]
请提供具体的设备型号，并检查在米家中有无对话记录。

**Comment by caoyaochong** [comment]
遇到同样的问题，大概率偶发性出现的问题，设备是 小爱音箱play增强版 。 米家或小爱音箱App中可以查到对话记录，但HASS 的conversion service无法获取当前对话记录，entity的state状态 还是之前的对话内容。

**Comment by caoyaochong** [comment]
> 请提供具体的设备型号，并检查在米家中有无对话记录。

遇到同样的问题，大概率偶发性出现的问题，设备是 小爱音箱play增强版 。 米家或小爱音箱App中可以查到对话记录，但HASS 的conversion service无法获取当前对话记录，entity的state状态 还是之前的对话内容。

**Comment by al-one** [comment]
检查HA[日志](https://my.home-assistant.io/redirect/logs)。
