### ISSUE TITLE
zhimi.fan.za5 rotation not working properly

### ISSUE THREAD

**Issue by steuerzentrale** [al-one/hass-xiaomi-miot#699]
Hi there

first of all many thanks for this neat integration, really love it ! I recently bought 2x  [zhimi.fan.za5](https://home.miot-spec.com/s/zhimi.fan.za5) and integrated them via this add-on which worked easy and reliable.

I noticed that the rotation-function is not working properly, the right-arrow (see screenshot) is greyed out and cannot be clicked. If I click on the left-arrow the fan turns all the way to the end and activates the oscillation-function.
<img width="373" alt="Bildschirmfoto 2022-07-12 um 09 48 09" src="https://user-images.githubusercontent.com/75168550/178438215-bf9a71de-2e0c-4d25-8fa8-b93a31593b65.png">
<img width="276" alt="Bildschirmfoto 2022-07-12 um 09 48 25" src="https://user-images.githubusercontent.com/75168550/178438229-940aa13f-7223-402d-a7d9-841a7ec418bc.png">

Would be happy if you can have a look at it, I would expect that the fan turns a bit in either direction if you click on one of the arrows.

all the best

Andrew

**Comment by al-one** [comment]
Please try master branch.

**Comment by steuerzentrale** [comment]
first of all many thanks for having a look at it! sorry to ask but I dont understand what you mean by trying the master branch. I installed xiaomi-miot via HACS on my Home Assistant OS.

**Comment by al-one** [comment]
Try latest branch.
