### ISSUE TITLE
小米窗帘关闭状态相反

### ISSUE THREAD

**Issue by bobo522487** [al-one/hass-xiaomi-miot#7]
添加多个窗帘，有几个的开合状态是反的。

Model：lumi.curtain.hmcn01
Entity class：LumiCurtainEntity
Adjust value：-
Position：0
Closed：true

**Comment by al-one** [comment]
是否在米家配置过开合方向？

**Comment by bobo522487** [comment]
米家里看不见是否配置过，不过当初印象里好像确实有一两个配置过开合方向。但现在米家里面是可以读取到窗帘开合状态的

**Comment by al-one** [comment]
HA的卷帘只有上下操作，上为开（100%）、下未关(0%)
如果你的窗帘状态和上述一样，则说明没有问题。

**Comment by bobo522487** [comment]
APP上再重置一下开合方向，解决问题了。
