### ISSUE TITLE
No update on sensors when motion is detected or window/door is opened

### ISSUE THREAD

**Issue by macreeve** [al-one/hass-xiaomi-miot#70]
The following devices can be connected:
lumi.gateway.mieu01
lumi.sensor_motion.v2
lumi.sensor_magnet.v2

The issue is the following devices do not update and do not give triggers when either motion is detected or window/door is opened (They only initialize and stop updating):
lumi.sensor_motion.v2
lumi.sensor_magnet.v2

**Comment by al-one** [comment]
https://github.com/al-one/hass-xiaomi-miot/issues/55#issuecomment-817442144

**Comment by al-one** [comment]
Add support for lumi motion sensor in commit: https://github.com/al-one/hass-xiaomi-miot/commit/06388138d0c3c12770dbe6c4fe48b02c867caa72 https://github.com/al-one/hass-xiaomi-miot/issues/120#issuecomment-873782043
