### ISSUE TITLE
Exception whilst fetching state

### ISSUE THREAD

**Issue by buhito81** [al-one/hass-xiaomi-miot#700]
This error below occurs several times a day.

> This error originated from a custom integration.
> 
> Logger: custom_components.xiaomi_miot.fan
> Source: custom_components/xiaomi_miot/__init__.py:1342
> Integration: Xiaomi Miot Auto (documentation, issues)
> First occurred: 13:37:48 (1 occurrences)
> Last logged: 13:37:48
> 
> Smartmi Air Purifier(zhimi.airpurifier.za1): Got MiioException while fetching the state: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'air_purifier.on': {'siid': 2, 'piid': 1}, 'air_purifier.fault': {'siid': 2, 'piid': 2}, 'air_purifier.mode': {'siid': 2, 'piid': 5}, 'aqi.purify_volume': {'siid': 13, 'piid': 1}, 'aqi.average_aqi': {'siid': 13, 'piid': 2}, 'use_time': {'siid': 12, 'piid': 1}, 'temperature_display_unit-16-1': {'siid': 16, 'piid': 1}, 'physical_controls_locked': {'siid': 7, 'piid': 1}, 'indicator_light.brightness': {'siid': 6, 'piid': 1}, 'alarm': {'siid': 5, 'piid': 1}, 'filter.filter_life_level': {'siid': 4, 'piid': 3}, 'filter.filter_used_time': {'siid': 4, 'piid': 5}, 'environment.air_quality': {'siid': 3, 'piid': 1}, 'environment.pm2_5_density': {'siid': 3, 'piid': 6}, 'environment.relative_humidity': {'siid': 3, 'piid': 7}, 'environment.temperature': {'siid': 3, 'piid': 8}}, max_properties: 8/16

**Comment by al-one** [comment]
The error was returned by the device, perhaps because the device was too busy. Please try adding the custom option `interval_seconds: 60` to reduce the frequency of status requests to the device.
- #600
