### ISSUE TITLE
空调伴侣风速无法调节

### ISSUE THREAD

**Issue by FlyRenxing** [al-one/hass-xiaomi-miot#703]
通过ha或HomeKit控制空调伴侣风速均无反应。
日志如下
Logger: custom_components.xiaomi_miot.climate
Source: custom_components/xiaomi_miot/__init__.py:1818
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 16:15:27 (17 occurrences)
Last logged: 16:27:20

主卧空调(lumi.acpartner.v3): Set miot property {'did': '93867406', 'siid': 3, 'piid': 1, 'value': None} failed, result: {'did': '93867406', 'siid': 3, 'piid': 1, 'code': -704220043, 'exe_time': 0}
次卧空调(lumi.acpartner.v3): Set miot property {'did': '93674712', 'siid': 3, 'piid': 1, 'value': None} failed, result: {'did': '93674712', 'siid': 3, 'piid': 1, 'code': -704220043, 'exe_time': 0}

**Comment by ChristianSwift** [comment]
+1

**Comment by al-one** [comment]
v0.6.10已修复
