### ISSUE TITLE
无法连接/添加扫地机器人，报错“连接设备失败”

### ISSUE THREAD

**Issue by keniji** [al-one/hass-xiaomi-miot#704]
扫地机器人型号是：ijai.vacuum.v14 / [米家免洗扫拖机器人](https://home.miot-spec.com/s/ijai.vacuum.v14)

印象是几天前开始扫地机器人就连不上了，状态显示“unavailable”，然后我尝试移除掉原来的，通过局域网方式添加提示”连接设备失败“，通过云方式添加的话状态也是显示“unavailable”，今天把扫地机器人重置了（要重建地图那种……），问题依旧（但是token好像没变）。通过局域网方式时添加的报错是：
`2022-07-15 21:00:31 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: timed out`
然后我用了:
`miiocli -d device --ip xxx.xxx.xxx.xxx --token xxxxxxxxxx info`
最后也是提示:
```
miio.exceptions.DeviceException: No response from the device
Error: No response from the device
```
但是直接米家APP或者小爱是可以控制的，也可以ping通扫地机器人的IP，请问还有什么排错是可以做的吗？

**Comment by al-one** [comment]
请确保设备ID和HA宿主机IP在同一网段，如果在同一网段，请尝试在米家APP重新绑定设备。

**Comment by keniji** [comment]
> 请确保设备ID和HA宿主机IP在同一网段，如果在同一网段，请尝试在米家APP重新绑定设备。



> 请确保设备ID和HA宿主机IP在同一网段，如果在同一网段，请尝试在米家APP重新绑定设备。

设备IP和HA宿主机IP一直在同一网段，我在HA宿主机上通过traceroute看到宿主机是可以不通过任何跃点访问到扫地机器人的。然后昨天扫地机器人被重置后也在米家中重新绑定过了。

**Comment by keniji** [comment]
过了好久再去看, 云端模式添加又可以获取到状态了, 但是局域网还是显示无法连接, 怀疑是不是小米把局域网方式的接口关闭了(虽然扫地机器人并没有更新过).. 反正云端模式先用着吧, 看了issue list也似乎没有其他人遇到这个问题.

**Comment by kinosang** [comment]
本周出现同样情况, 删除设备并重新更新设备列表后只有一个开关了

**Comment by al-one** [comment]
@kinosang 请收集相关报错[日志](https://my.home-assistant.io/redirect/logs)并重新提交一个issue。
