### ISSUE TITLE
小米新风空调频繁掉线，每二十几分钟就会出现“不可用”的状态，大约一分钟后自动恢复“可用”状态

### ISSUE THREAD

**Issue by skasoka** [al-one/hass-xiaomi-miot#706]

**Comment by al-one** [comment]
目前猜测原因是由于[小米新风空调](https://home.miot-spec.com/spec/xiaomi.aircondition.mt6)的miot属性过多，请尝试通过自定义选项`exclude_miot_services`/`exclude_miot_properties`排除不需要的服务和属性，也可以通过自定义选项`auto_cloud: true`在设备不可用时使用云端连接。
![image](https://user-images.githubusercontent.com/4549099/179436926-204393a6-c604-488f-8c1c-d53ccdbcc33f.png)

**Comment by skasoka** [comment]
感谢大神的回复，我已经把hass-xiaomi-miot恢复到V0.67版本，非常稳定
