### ISSUE TITLE
小米智能插座(chuangmi.plug.v1)添加后无法单独操控USB开关和220插座开关

### ISSUE THREAD

**Issue by Networkzt** [al-one/hass-xiaomi-miot#707]
model: chuangmi.plug.v1
lan_ip: XXXX
mac_address: XXXX
entity_class: MiotSwitchEntity
home_room: XXXX的家
miot_type: urn:miot-spec-v2:device:outlet:0000A002:chuangmi-v1:2
switch.on: true
indicator_light.on: true
state_updater: lan
sub_entities: indicator_light-3
device_class: outlet
friendly_name: USB电源插座 Power Switch Status
supported_features: 0

希望可以将USB口单独建一个开关控制,驱动device:outlet:0000A002:chuangmi-v1:1,大大看看能不能后续的更新里可以加上

**Comment by Networkzt** [comment]
米家里面是有单独USB控制的,用隔壁家的插件竟然是有单独控制,希望这边也能实现,省的我就一个设备挂在那个下面,大大研究研究
mapping:
{"switch":{"switch_status":{"siid":2,"piid":1}},"switch_usb":{"switch_status":{"siid":3,"piid":1}}}
配置参数:
{"switch":{"switch_status":{"power_on":true,"power_off":false},"main":true},"switch_usb":{"switch_status":{"power_on":true,"power_off":false}}}
![f8d9a8c4a1192574b51df62c006abb1](https://user-images.githubusercontent.com/61804157/179782767-e05b56cd-1326-439d-ba4f-b10f4b154bea.jpg)
![446fd517cd712d84b56c40d24031ab7](https://user-images.githubusercontent.com/61804157/179782797-e997ed5c-f55a-4ffa-98ef-379d3df04e56.jpg)
![Snipaste_2022-07-19_22-58-49](https://user-images.githubusercontent.com/61804157/179782813-9b6bcfa9-4cc6-4e5c-bc4f-12cd17687fbf.png)

**Comment by al-one** [comment]
已添加该设备的USB开关实体，请更新到master分支

**Comment by chenjiezb** [comment]
已经更新到最新版本0.6.11，也核对了保存在本地的代码已经更新了，但发现chuangmi.plug.v1的usb开关没有能出来。
![2022-08-30_210254](https://user-images.githubusercontent.com/69343470/187443714-c0bf0a49-c935-4ad6-bcf5-bac1f0727c64.gif)

**Comment by Networkzt** [comment]
我也测试了和你一样,但我用隔壁的就能出USB的开关,扎心了
![image](https://user-images.githubusercontent.com/61804157/187687741-7bc8d443-6363-44e7-a857-62144cc48198.png)
他的Mapping 和参数如下:
{"switch":{"switch_status":{"siid":2,"piid":1}},"switch_usb":{"switch_status":{"siid":3,"piid":1}}}
{"switch":{"switch_status":{"power_on":true,"power_off":false},"main":true},"switch_usb":{"switch_status":{"power_on":true,"power_off":false}}}

**Comment by Networkzt** [comment]
> 已经更新到最新版本0.6.11，也核对了保存在本地的代码已经更新了，但发现chuangmi.plug.v1的usb开关没有能出来。 ![2022-08-30_210254](https://user-images.githubusercontent.com/69343470/187443714-c0bf0a49-c935-4ad6-bcf5-bac1f0727c64.gif) [ ![2022-08-30_210254](https://user-images.githubusercontent.com/69343470/187443714-c0bf0a49-c935-4ad6-bcf5-bac1f0727c64.gif) ](https://user-images.githubusercontent.com/69343470/187443714-c0bf0a49-c935-4ad6-bcf5-bac1f0727c64.gif) [ ](https://user-images.githubusercontent.com/69343470/187443714-c0bf0a49-c935-4ad6-bcf5-bac1f0727c64.gif)

![image](https://user-images.githubusercontent.com/61804157/187688290-bb16b20a-d167-467e-bfc5-32a67fe1e70a.png)
只能用右边的先顶顶吧

**Comment by Networkzt** [comment]
@chenjiezb 用右边的顶顶哈哈
![image](https://user-images.githubusercontent.com/61804157/187688560-e2d5898d-ff62-4cc9-be1b-883c642333d3.png)

**Comment by al-one** [comment]
执行下面的服务并从HA通知中获取结果。
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: switch.chuangmi_v1_xxxx
  method: get_prop
  params: ['on', usb_on, temperature, wifi_led]
  throw: true
```

**Comment by al-one** [comment]
更新master分支再试

**Comment by chenjiezb** [comment]
目前220v和usb两个开关功能均恢复正常了，但原来正常的指示灯开关功能现在不能使用，出现了两个指示灯开关，无温度传感器数据。
![2022-09-01_195657](https://user-images.githubusercontent.com/69343470/187908389-d52fad12-48cf-4ef1-8f75-dedf951ba1ed.gif)

**Comment by al-one** [comment]
不可用的指示灯实体直接删除即可。

**Comment by chenjiezb** [comment]
此设备在ha中的功能完美展现，感谢大侠即时修复！哪里有教程，俺也想学一学:)
![2022-09-01_210255](https://user-images.githubusercontent.com/69343470/187920328-0d29c741-4c1a-4dc6-9f1f-eebcac3221ae.gif)

**Comment by Networkzt** [comment]
我更新到master怎么出不来,你后来是怎么操作的 @chenjiezb
