### ISSUE TITLE
Zemismart 智能窗帘电机多项属性读取失败

### ISSUE THREAD

**Issue by ChristianSwift** [al-one/hass-xiaomi-miot#708]
<img width="359" alt="image" src="https://user-images.githubusercontent.com/20925565/179361258-c7c7741e-82f9-4cc4-9984-ea020018f2df.png">  
可以看一下是什么情况吗

**Comment by al-one** [comment]
请尝试添加自定义选项`chunk_properties: 1`
- https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-864678774
- #500

**Comment by ChristianSwift** [comment]
> * Customizing entities and devices | 通过UI管理自定义选项 #600

添加了没有效果，另外测试了一下通过账号云接入是可以看到current position和target position的，只有这个局域网接入是显示error

**Comment by al-one** [comment]
该设备也许仅支持云端模式接入。
