### ISSUE TITLE
可否增加小白门铃的按钮触发功能？

### ISSUE THREAD

**Issue by guokai10000** [al-one/hass-xiaomi-miot#709]
设备是：chuangmi.cateye.i023a01
现在仅有视频传输功能，而且使用起来也有点卡卡的。
想请教一下能否将有人按门铃的功能接入到homeassistant中，继而触发homekit的通知功能？

**Comment by al-one** [comment]
无法支持实时事件监听，参考：
- https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-909031222
