### ISSUE TITLE
若删除不是通过 miot auto指定的方式 （修改设备名词为”删除“）， 则设备下面的实体 就是不能删除的状态

### ISSUE THREAD

**Issue by geekli** [al-one/hass-xiaomi-miot#712]
**如题 我通过下面这种方式删除设备后**
![1](https://user-images.githubusercontent.com/830238/179947705-d642daa5-e3ea-41ed-80fa-f0cd19fad914.png)

**它下面的实体并没有删除，同时是不可点选状态**
![2](https://user-images.githubusercontent.com/830238/179947748-0351f1fd-4a6b-4cec-81dc-12b65284e767.png)

**也手动删除不了**
![3](https://user-images.githubusercontent.com/830238/179947768-0e2c9fdd-f3da-480e-81d1-cec38a65a7b6.png)

这种情况该如何处理啊？

**Comment by al-one** [comment]
重启HA后，这些实体便会消失。
