### ISSUE TITLE
最近一周来无法获得设备。注销了小米账号重新开一个新的都不行

### ISSUE THREAD

**Issue by YaoFei509** [al-one/hass-xiaomi-miot#719]
Logger: custom_components.xiaomi_miot.core.xiaomi_cloud
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:198
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 14:51:30 (2 occurrences)
Last logged: 14:52:30

Request xiaomi api: v2/message/v2/check_new_msg {'begin_at': 1658731819} failed, response: None
Request xiaomi api: home/device_list {'getVirtualModel': True, 'getHuamiDevices': 1, 'get_split_device': False, 'support_smart_home': True} failed, response: None

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/500

请通过上面的文章排查下是不是网络问题导致的。

**Comment by YaoFei509** [comment]
发现从电信宽带接入的任何DNS都返回api.io.mi.com的地址里有一个2401:1d40:ff::b的IPv6地址，在宿主机（armbian）上能正常ping通，但是curl访问不到。在路由器的DNS里强制只给IPv4地址，成功获取设备列表。在路由器(RouterOS 7.4) 的IPv6防火墙里添加 

/ipv6 firewall mangleadd action=change-mss chain=forward new-mss=clamp-to-pmtu passthrough=yes protocol=tcp tcp-flags=syn

之后就正常了。看来是IPv6路由的问题。
