### ISSUE TITLE
I have a issue is from xiaomi miot,it is MiotNumberInput is overriding a deprecated method on NumberEntity instances, which is invalid and will not be supported in Home Assistant 2022.10.  and how to i do?

### ISSUE THREAD

**Issue by j1104c** [al-one/hass-xiaomi-miot#720]
記錄器：homeassistant.components.number
來源：components/number/__init__.py:220 集成：數字 （[文檔](https://www.home-assistant.io/integrations/number)， [問題](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+number%22)） 首次出現： 01:37: 31 （5次出現） 最後記錄： 02:02: 48
custom_components.xiaomi_miot.number::MiotNumberInput 正在覆蓋 NumberEntity 實例上不推薦使用的方法，這是無效的，並且在 Home Assistant 2022.10 中將不受支持。

**Comment by al-one** [comment]
https://github.com/al-one/hass-xiaomi-miot/issues/695#issuecomment-1185681889
