### ISSUE TITLE
yeelight 皓石吊灯氛围灯无法控制

### ISSUE THREAD

**Issue by rickycm** [al-one/hass-xiaomi-miot#721]
yeelight 皓石吊灯 有主灯和氛围灯，添加后在HA里只有显示和控制主灯，无法控制氛围灯。
可以通过添加自定义实体解决吗？

**Comment by al-one** [comment]
请更新至master分支后再试。

**Comment by rickycm** [comment]
我是直接从HACS市场下载的，可以切换分支吗？

**Comment by rickycm** [comment]
<img width="1028" alt="2022-07-29 11-14-08" src="https://user-images.githubusercontent.com/5108179/181675401-ae19d457-87c6-43fc-ac05-21f7e330edc9.png">
切换到masterwvfc分支也还是没有氛围灯的控制选项。

**Comment by al-one** [comment]
https://github.com/al-one/hass-xiaomi-miot/blob/373a8f11a969dd1e295f29e9847a97b3e792dc9e/custom_components/xiaomi_miot/core/miio2miot_specs.py#L1522-L1530

请检查你的本地文件以确保更新成功。

**Comment by rickycm** [comment]
重新下载了master分支，也检查了[miio2miot_specs.py](https://github.com/al-one/hass-xiaomi-miot/blob/373a8f11a969dd1e295f29e9847a97b3e792dc9e/custom_components/xiaomi_miot/core/miio2miot_specs.py#L1522-L1530)这段代码，手动添加上这段，都还是不行。

**Comment by al-one** [comment]
请下载完整的插件代码。

**Comment by rickycm** [comment]
<img width="963" alt="image" src="https://user-images.githubusercontent.com/5108179/186063915-183aecd3-e5b3-4bf7-869b-31f006db3409.png">
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/5108179/186064028-66bcd31d-c0a8-4f85-882e-24689334f3ee.png">
更新到了Master，也重新添加了设备，还是没有氛围灯属性，是少做了什么吗？

**Comment by al-one** [comment]
![image](https://user-images.githubusercontent.com/4549099/186669105-ed991168-0afb-407a-8c26-eb7298dc694e.png)

**Comment by al-one** [comment]
尝试最新版本

**Comment by crgnclsn** [comment]
Hi, I have just tried the latest version. The ambient light is still not showing up for me. Just the main light and off_delay_time like @rickycm. Is there anything I can run or do to help you figure out why it is not working?

**Comment by al-one** [comment]
@crgnclsn  Show me the [entity attributes](https://my.home-assistant.io/redirect/developer_states).

**Comment by crgnclsn** [comment]
<img width="269" alt="image" src="https://user-images.githubusercontent.com/23727785/187396745-4bfbd5d9-f77c-468d-b191-29af5cae1ea7.png">
 Here you are!

**Comment by crgnclsn** [comment]
It is integrated via account. I have tried both manual and account.

**Comment by al-one** [comment]
Error `-704030013 Property is not readable` comes from the cloud.
 Ambient light of the device is only available in local mode.

**Comment by crgnclsn** [comment]
Forced refresh in local mode.

Still only showing a single light entity with one setting.

```
min_mireds: 154
max_mireds: 370
effect_list: Day, Night
supported_color_modes: brightness, color_temp, onoff
color_mode: color_temp
brightness: 51
color_temp: 357
hs_color: 28.185, 62.588
rgb_color: 255, 170, 95
xy_color: 0.516, 0.386
effect: Day
model: yeelink.light.ceiling10
lan_ip: 192.168.0.206
mac_address: 50:EC:50:89:77:20
entity_class: MiotLightEntity
miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-ceiling10:1
light.on: true
light.brightness: 20
light.color_temperature: 2801
light.mode: 1
light.off_delay_time: 0
state_updater: lan
sub_entities: light-2.off_delay_time-102
friendly_name: Ceiling Bar Light
supported_features: 39
```

**Comment by crgnclsn** [comment]
> Try master branch.

Working! You are a hero. Many thanks.
