### ISSUE TITLE
小米无线开关无法添加到设备/实体

### ISSUE THREAD

**Issue by rickycm** [al-one/hass-xiaomi-miot#722]
添加或刷新Xiaomi Miot Auto集成时，在筛选设备列表里有小米无线开关（lumi.sensor_switch.v2），无论选中或不选中，刷新后在设备/实体列表里都找不到小米无线开关。

**Comment by al-one** [comment]
不支持无线开关。

**Comment by rickycm** [comment]
能否添加这个支持，家里好几个无线开关，想用来触发自动化脚本

**Comment by al-one** [comment]
无法支持，建议尝试`XiaomiGateway3`

**Comment by rickycm** [comment]
aqura E1无线双键开关也不能支持吗？设备标识是：lumi.remote.acn004

**Comment by al-one** [comment]
> aqura E1无线双键开关也不能支持吗？设备标识是：lumi.remote.acn004

支持不了
