### ISSUE TITLE
Mi Smart Mosquito Repeller 2(zimi.mosq.v2): Got MiCloudException while fetching the state

### ISSUE THREAD

**Issue by Axydas** [al-one/hass-xiaomi-miot#723]
Hi

get the below error:
Logger: custom_components.xiaomi_miot.switch
Source: custom_components/xiaomi_miot/__init__.py:1363
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 10:03:04 (304 occurrences)
Last logged: 12:34:47

Mi Smart Mosquito Repeller 2(zimi.mosq.v2): Got MiCloudException while fetching the state: Cannot execute request. service token or userId missing. Make sure to login., mapping: {'mosquito_dispeller.on': {'siid': 2, 'piid': 1}, 'mosquito_dispeller.mode': {'siid': 2, 'piid': 2}, 'light_indicator.on': {'siid': 9, 'piid': 1}, 'light_indicator.start_time': {'siid': 9, 'piid': 2}, 'light_indicator.end_time': {'siid': 9, 'piid': 3}, 'enter_app': {'siid': 8, 'piid': 1}, 'user_timer.set_timer': {'siid': 5, 'piid': 1}, 'user_timer.timestamp': {'siid': 5, 'piid': 2}, 'user_timer.del_mult_timer': {'siid': 5, 'piid': 3}, 'battery_level': {'siid': 3, 'piid': 1}, 'repellent.repellent_left_level': {'siid': 4, 'piid': 1}}

Can somebody help me?

Thanks in advance

**Comment by al-one** [comment]
![xiaomi miot re-configure](https://user-images.githubusercontent.com/4549099/181695285-4373f041-420c-419c-80eb-2313fbf3f59a.png)
Re-configure and save.

**Comment by al-one** [comment]
Bluetooth devices only support integration through the cloud (Automatic mode for account integration).
