### ISSUE TITLE
Mi Desk Lamp 1s 5001 errors

### ISSUE THREAD

**Issue by mouth4war** [al-one/hass-xiaomi-miot#727]
> Mi LED Desk Lamp 1S(yeelink.light.lamp4): Send miio command: set_ct_abx([2597, 'smooth', 3000.0]) failed: {'code': -5001, 'message': 'invalid params'}
Mi LED Desk Lamp 1S(yeelink.light.lamp4): Send miio command: set_ct_abx([2597, 'smooth', 10000.0]) failed: {'code': -5001, 'message': 'invalid params'}

**Comment by mouth4war** [comment]
> Logger: custom_components.xiaomi_miot.light Source: custom_components/xiaomi_miot/__init__.py:1266

>Xiaomi Miot(yeelink.light.lamp4): Send miio command: set_bright([0, 'smooth', 3000]) failed: {'code': -5001, 'message': 'invalid params'}
>Xiaomi Miot(yeelink.light.lamp4): Send miio command: set_ct_abx([2597, 'smooth', 1000.0]) failed: {'code': -5001, 'message': 'invalid params'}
>Xiaomi Miot(yeelink.light.lamp4): Send miio command: set_ct_abx([2597, 'smooth', 10000.0]) failed: {'code': -5001, 'message': 'invalid params'}
>Xiaomi Miot(yeelink.light.lamp4): Send miio command: set_bright([0, 'smooth', 3000.0]) failed: {'code': -5001, 'message': 'invalid params'}

**Comment by al-one** [comment]
Try latest release version.

**Comment by mouth4war** [comment]
Xiaomi Miot(yeelink.light.lamp4): Send miio command: set_ct_abx([2597, 'smooth', 5000.0]) failed: {'code': -5001, 'message': 'invalid params'}
Xiaomi Miot(yeelink.light.lamp4): Send miio command: set_bright([0, 'smooth', 3000.0]) failed: {'code': -5001, 'message': 'invalid params'}
Xiaomi Miot(yeelink.light.lamp4): Send miio command: set_bright([0, 'smooth', 3000]) failed: {'code': -5001, 'message': 'invalid params'}
Xiaomi Miot(yeelink.light.lamp4): Send miio command: set_ct_abx([2597, 'smooth', 5000]) failed: {'code': -5001, 'message': 'invalid params'}

**Comment by mouth4war** [comment]
Errors still exist

**Comment by al-one** [comment]
- https://home.miot-spec.com/spec/yeelink.light.lamp4

```javascript
[
    {
        "iid":2,
        "type":"urn:miot-spec-v2:property:brightness:0000000D:yeelink-lamp4:1",
        "description":"Brightness",
        "format":"uint8",
        "access":["read", "write", "notify"],
        "unit":"percentage",
        "value-range":[1, 100, 1] // min: 1, max: 100, step: 1
    },
    {
        "iid":3,
        "type":"urn:miot-spec-v2:property:color-temperature:0000000F:yeelink-lamp4:1",
        "description":"Color Temperature",
        "format":"uint32",
        "access":["read", "write", "notify"],
        "unit":"kelvin",
        "value-range":[2600, 5000, 1] // min: 2600, max: 5000, step: 1
    }
]
```
