### ISSUE TITLE
小米智能插座2蓝牙网关版对功率的单位可能有错  已更新到最新的master分支

### ISSUE THREAD

**Issue by sxsjs123** [al-one/hass-xiaomi-miot#728]
首先感谢作者 ！这是我看到的一点小bug
设备型号：chuangmi.plug.212a01
名称：米家智能插座2
问题截图
![8DFD5)7%GW GPMYFT{` M$H](https://user-images.githubusercontent.com/31535751/181721033-1d6cf2f3-0e8a-40de-93e5-b55870aed877.png)
![IMG_4803](https://user-images.githubusercontent.com/31535751/181721062-2a7b5a04-c6e0-47eb-9984-6e32c613eaff.PNG)
：

问题如图 app里显示50w  home里限时0.5w  单位有误。

**Comment by sxsjs123** [comment]
https://github.com/al-one/hass-xiaomi-miot/issues/534

已经通过此解决方法尝试 没有效果  
请问
![image](https://user-images.githubusercontent.com/31535751/181725321-c2c9950a-743d-44d2-abfe-cfd21ecbfdc0.png)
是否需要改动

**Comment by sxsjs123** [comment]
![image](https://user-images.githubusercontent.com/31535751/181725933-989f0d4e-723f-4fcc-a9e6-9ca1246be4f3.png)

**Comment by sxsjs123** [comment]
![image](https://user-images.githubusercontent.com/31535751/181726974-47399dfe-3e80-4012-bcde-74ad20527d62.png)

**Comment by sxsjs123** [comment]
![image](https://user-images.githubusercontent.com/31535751/181728850-1194c8b3-d978-4a35-a67d-f7dd5c0a7e30.png)
只有这些资料

**Comment by sxsjs123** [comment]
和我看到的教程不太一样

**Comment by al-one** [comment]
@sxsjs123 你截图中的实体不是由本插件生成的。。。

**Comment by sxsjs123** [comment]
啊  抱歉 弄了半天发现弄错插件了

**Comment by sxsjs123** [comment]
我刚发现太抱歉了  我一直以为我用的是本插件

**Comment by sxsjs123** [comment]
我弄好了谢谢啊
谢谢
