### ISSUE TITLE
无法控制浴霸的灯关闭, 型号 yeelink.bhf_light.v6

### ISSUE THREAD

**Issue by chenrongyu** [al-one/hass-xiaomi-miot#729]
其他的控制都正常，但是灯开起来之后，亮度可调，就是无法关闭，日志内容如下，感谢

Logger: homeassistant.components.websocket_api.messages
Source: components/websocket_api/messages.py:199
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 13:39:40 (12 occurrences)
Last logged: 16:22:49

Unable to serialize to JSON. Bad data found at $.event(Event: state_changed).data.old_state(State: light.yeelink_v6_ef0d_light).attributes<key: <custom_components.xiaomi_miot.core.miot_spec.MiotProperty object at 0x7fbf6c2b3880>>=<custom_components.xiaomi_miot.core.miot_spec.MiotProperty object at 0x7fbf6c2b3880>(<class 'custom_components.xiaomi_miot.core.miot_spec.MiotProperty'>
Unable to serialize to JSON. Bad data found at $.event(Event: state_changed).data.new_state(State: light.yeelink_v6_ef0d_light).attributes<key: <custom_components.xiaomi_miot.core.miot_spec.MiotProperty object at 0x7fbf723779a0>>=<custom_components.xiaomi_miot.core.miot_spec.MiotProperty object at 0x7fbf723779a0>(<class 'custom_components.xiaomi_miot.core.miot_spec.MiotProperty'>
Unable to serialize to JSON. Bad data found at $.event.c.light.yeelink_v6_ef0d_light.+.a<key: <custom_components.xiaomi_miot.core.miot_spec.MiotProperty object at 0x7fbf723779a0>>=<custom_components.xiaomi_miot.core.miot_spec.MiotProperty object at 0x7fbf723779a0>(<class 'custom_components.xiaomi_miot.core.miot_spec.MiotProperty'>
Unable to serialize to JSON. Bad data found at $.event.c.light.yeelink_v6_ef0d_light.-.a={<custom_components.xiaomi_miot.core.miot_spec.MiotProperty object at 0x7fbf723779a0>}(<class 'set'>
Unable to serialize to JSON. Bad data found at $.event(Event: state_changed).data.old_state(State: light.yeelink_v6_ef0d_light).attributes<key: <custom_components.xiaomi_miot.core.miot_spec.MiotProperty object at 0x7fbf723779a0>>=<custom_components.xiaomi_miot.core.miot_spec.MiotProperty object at 0x7fbf723779a0>(<class 'custom_components.xiaomi_miot.core.miot_spec.MiotProperty'>

Logger: homeassistant.components.recorder.core
Source: components/recorder/core.py:794
Integration: Recorder (documentation, issues)
First occurred: 13:39:40 (3 occurrences)
Last logged: 16:22:49

State is not JSON serializable: <state light.yeelink_v6_ef0d_light=on; effect_list=['Day', 'Night'], supported_color_modes=['brightness', 'onoff'], color_mode=brightness, brightness=92, effect=Night, light.on=True, light.mode=1, light.brightness=36, <custom_components.xiaomi_miot.core.miot_spec.MiotProperty object at 0x7fbf6c2b3880>=True, friendly_name=Yeelight 智能浴霸 S20 测试 Light, supported_features=37 @ 2022-07-29T13:38:03.171852+08:00>: Dict key must a type serializable with OPT_NON_STR_KEYS
State is not JSON serializable: <state light.yeelink_v6_ef0d_light=on; effect_list=['Day', 'Night'], supported_color_modes=['brightness', 'onoff'], color_mode=brightness, brightness=105, effect=Night, light.on=True, light.mode=1, light.brightness=41, <custom_components.xiaomi_miot.core.miot_spec.MiotProperty object at 0x7fbf723779a0>=True, friendly_name=Yeelight 智能浴霸 S20 测试 Light, supported_features=37 @ 2022-07-29T16:22:40.193079+08:00>: Dict key must a type serializable with OPT_NON_STR_KEYS

**Comment by keniji** [comment]
同型号的路过, 刚试了可以调亮度也可以关闭和打开没问题. 要是原来通过云端方式接入的话要不用xiaomi_miot.get_token服务获取token之后试一下局域网方式接入.

**Comment by chenrongyu** [comment]
> 同型号的路过, 刚试了可以调亮度也可以关闭和打开没问题. 要是原来通过云端方式接入的话要不用xiaomi_miot.get_token服务获取token之后试一下局域网方式接入.

仿佛有毒， 尝试使用局域网的token模式，一样无法关闭 T。T

**Comment by keniji** [comment]
> > 同型号的路过, 刚试了可以调亮度也可以关闭和打开没问题. 要是原来通过云端方式接入的话要不用xiaomi_miot.get_token服务获取token之后试一下局域网方式接入.
> 
> 仿佛有毒， 尝试使用局域网的token模式，一样无法关闭 T。T

那我只能建议你等作者来看了, 或者先按显示屏旁边那个白色按钮重置了浴霸试试 =￣ω￣=

**Comment by al-one** [comment]
请尝试升级HA。

**Comment by chenrongyu** [comment]
> 

升级到最新版之后可以了！感谢！
