### ISSUE TITLE
小米扫地机在HomeKit里只有一个开关

### ISSUE THREAD

**Issue by wqhqq1** [al-one/hass-xiaomi-miot#730]
小米扫地机在homekit里只有一个开关，无法控制具体功能
如图：
![image](https://user-images.githubusercontent.com/53130008/181907178-c4dc2265-9f62-4f90-9304-fe98d50a95ca.png)

**Comment by wqhqq1** [comment]
有没有办法给他加上HA里面的控制功能
![image](https://user-images.githubusercontent.com/53130008/181907635-54480a30-c05d-48f4-aaa0-178ecd914aed.png)

**Comment by wqhqq1** [comment]
@al-one

**Comment by al-one** [comment]
与插件无关。
