### ISSUE TITLE
Gosund CP5Pro 插线板电流单位错误

### ISSUE THREAD

**Issue by L1cardo** [al-one/hass-xiaomi-miot#731]
这里应该是A，而不是mA
<img width="889" alt="image" src="https://user-images.githubusercontent.com/33802186/181908127-6fc3ae3e-e899-42fc-9bee-404c8ba8642a.png">
![IMG_0502](https://user-images.githubusercontent.com/33802186/181908140-e285a2d4-cf57-4fbb-908e-1d373f84bb5e.jpg)

**Comment by L1cardo** [comment]
问题好像出在这里？你这里写了通配符，我不知道该称A会不会影响其他设备
https://github.com/al-one/hass-xiaomi-miot/blob/59d23b5a065495e8507b11a4dd1e05ff312834e1/custom_components/xiaomi_miot/core/device_customizes.py#L173
<img width="342" alt="image" src="https://user-images.githubusercontent.com/33802186/181908305-14a028ba-fa8d-4f99-b003-4cc76f940a16.png">

**Comment by x1983** [comment]
> 问题好像出在这里？你这里写了通配符，我不知道该称A会不会影响其他设备
> 
> https://github.com/al-one/hass-xiaomi-miot/blob/59d23b5a065495e8507b11a4dd1e05ff312834e1/custom_components/xiaomi_miot/core/device_customizes.py#L173
> 
> 
> <img alt="image" width="342" src="https://user-images.githubusercontent.com/33802186/181908305-14a028ba-fa8d-4f99-b003-4cc76f940a16.png">

通过自定义设备将此传感器单位修正为A以后，在日志中会出现以下的错误提示：

2022-07-31 22:10:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.cuco_cp5pro_b85b_electric_current (A) does not match the unit of already compiled statistics (mA). Generation of long term statistics will be suppressed unless the unit changes back to mA. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this

所以，看起来如果不能拿到所有的型号电流单位的数据话，只能通过官方再加一条额外的自定义来为CP5 Pro修正了。
