### ISSUE TITLE
红外空调如何绑定额外温度传感器的值？

### ISSUE THREAD

**Issue by shenwrt** [al-one/hass-xiaomi-miot#732]
同上，空调伴侣的可以通过  选项-为空调绑定外部温度传感器，成功绑定，但是红外空调按照这种方法绑定无效，请问应该如果绑定，谢谢大佬

**Comment by al-one** [comment]
经测试，可正常绑定：
![xiaomi miot climate bind sensor](https://user-images.githubusercontent.com/4549099/183050867-e7797065-775b-460f-9e46-a5737a7c9ba3.png)
