### ISSUE TITLE
小米人体传感器2motion sensor无法使用

### ISSUE THREAD

**Issue by AkaJLock** [al-one/hass-xiaomi-miot#736]
如题...希望作者大大帮帮忙
<img width="325" alt="截屏2022-08-07 02 30 18" src="https://user-images.githubusercontent.com/102549331/183262079-13a9e33b-1629-4bcc-9c91-6ed8fc7a96f1.png">

**Comment by AkaJLock** [comment]
更新至master分支后解决，自关...

**Comment by AkaJLock** [comment]
使用最新版本的集成，添加小米人体传感器2后无法显示电量，重载/删除后再次添加都无法获得该实体，但动作传感器的使用一直是没有问题的。昨天开了这个issue后自行把集成更新为master分支后，成功多了一个电量实体，但发现动作传感器无法获取到数据.....重载/删除后再次添加均无法使用该传感器
![image](https://user-images.githubusercontent.com/102549331/183291990-70965fe9-d3f1-487b-ba1d-7c353a25ada8.png)

**Comment by al-one** [comment]
建议使用多模网关+XiaomiGateway3

**Comment by AkaJLock** [comment]
> 我的motion sensor 不会输出又没有检测到，最后发现不是第一个选项，而是trigger_at实体更新时间就表示有人了。

两码事，trigger_at是最后变化记录时间的，这个字段在ha里不太好设置自动化，而motion sensor确实是无效的，也只有这个实体可以接入hk和ha的原生自动化。不过没关系我用nr取实体的属性值变化实现自动化了，po主大佬的插件真的太棒了，支持的设备非常多，后面有机会修复到这里就行😬我关题了
