### ISSUE TITLE
viomi.vacuum.v8: Expose attributes as separate sensors?

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [al-one/hass-xiaomi-miot#737]
When integrated via local connection, created entities are:
![obraz](https://user-images.githubusercontent.com/24268470/183307974-fae2491b-1867-4f8f-b9d6-372b2bddadc3.png)

vacuum entity has this attributes:
![obraz](https://user-images.githubusercontent.com/24268470/183308041-55e1b76f-f2bf-47c4-bb37-8274b593297a.png)

Can this integration create more sensor entities? Installed box type, mop type, available suction speed, available water amount, etc.

**Comment by al-one** [comment]
- #600 `sensor_attributes`
- https://www.home-assistant.io/integrations/template
