### ISSUE TITLE
ows.towel_w.mj1x0 not work

### ISSUE THREAD

**Issue by pafftis** [al-one/hass-xiaomi-miot#739]
hi all
ha version 2022.08.03

not work device.

I extracted the token and specified the ip addres.
the device is added but does not function not as.

https://home.miot-spec.com/s/ows.towel_w.mj1x0

**Comment by pafftis** [comment]
device unavailable

**Comment by al-one** [comment]
Please integrate it via account (automatic mode).

**Comment by pafftis** [comment]
I also tried to integrate it through my account. I also have a Towel Rack device and it is not active.

**Comment by pafftis** [comment]
Through automatic I have added. But it works like a switch. there are no entities like temperatures and it is not defined as a thermostat.

**Comment by al-one** [comment]
Show me the [entity attributes](https://my.home-assistant.io/redirect/developer_states).

**Comment by loginblogin** [comment]
> Show me the [entity attributes](https://my.home-assistant.io/redirect/developer_states).

model: ows.towel_w.mj1x0
lan_ip: ***
mac_address: ***
entity_class: MiotSwitchEntity

miot_type: urn:miot-spec-v2:device:towel-rack:0000A09A:ows-mj1x0:1
towel_rack.on: false
towel_rack.mode: 0
towel_rack.target_temperature: 44
towel_rack.temperature: 53
state_updater: cloud
device_class: switch
friendly_name: Adult Electric towel Towel Rack
supported_features: 0

**Comment by loginblogin** [comment]
i removed it and integrate again (via token and automatic mode)... but now device is unavailable

**Comment by al-one** [comment]
Now, it supports local mode. Try master branch.

**Comment by loginblogin** [comment]
> Now, it supports local mode. Try master branch.

yep. it's work! thnx
can you change "mode" description?
0: 'dry', 1: 'warn', 2: 'antifreeze', 3: 'programming';

**Comment by loginblogin** [comment]
... and can you add property "dry_time"?

**Comment by al-one** [comment]
Try master again.

**Comment by loginblogin** [comment]
> Try master again.

**drytime** added. thanx.

but **mode** still only numbers.

 _0: 'dry', 1: 'warn', 2: 'antifreeze', 3: 'programming';_

**Comment by loginblogin** [comment]
Entity **number.ows_mj1x0_03ad_target_temperature** (<class 'custom_components.xiaomi_miot.number.MiotNumberSubEntity'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom integration author.

also
number.ows_mj1x0_03ad_dry_time
number.ows_mj1x0_b9ce_target_temperature
number.ows_mj1x0_b9ce_dry_time
