### ISSUE TITLE
青萍空气检测仪 升级固件后无法读取任何参数

### ISSUE THREAD

**Issue by googooog** [al-one/hass-xiaomi-miot#740]
[cgllc.airmonitor.s1](https://home.miot-spec.com/s/cgllc.airmonitor.s1)
如图显示，小米app可以正常使用

<img width="981" alt="截屏2022-08-12 19 22 33" src="https://user-images.githubusercontent.com/26278416/184344362-f5183bac-dabd-4651-9923-f737e48600b6.png">

**Comment by HiMuzi** [comment]
I had the same problem as you

**Comment by al-one** [comment]
或许设备新估计关闭了局域网通信端口，插件无能为力。

**Comment by littlesky87** [comment]
4.1.8_9999 版本的固件，同样问题。
改为云端模式也不行。

**Comment by akarpych** [comment]
https://github.com/Cheaterdev/clear_grass-ha

**Comment by al-one** [comment]
Try master branch.

**Comment by googooog** [comment]
> Try master branch.

Thanks.

**Comment by al-one** [comment]
@googooog  Does it work ?

**Comment by akarpych** [comment]
> @googooog  Does it work ?

Yes, it work!

**Comment by HiMuzi** [comment]
great!
