### ISSUE TITLE
邦先生晾衣架通过 ha 接入到 HomeKit 后升降状态是反的

### ISSUE THREAD

**Issue by twoer** [al-one/hass-xiaomi-miot#742]
![IMG_5156](https://user-images.githubusercontent.com/1292330/184502054-bca5b4bb-bbc9-4b23-bf5a-cfda0b850eaf.PNG)
![7921660406633_ pic](https://user-images.githubusercontent.com/1292330/184502066-acd1f4c1-f919-4003-b58f-61955a0f3e02.jpg)

其实有两个问题：

1、HA 经常报 晾衣架不在可用；

2、Homekit 中 晾衣架升降是反的；
> 晾衣架在 HomeKit中显示为窗帘，当晾衣架升到最上面时，HomeKit 的状态为开，这里是否应该反过来？

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/138#issuecomment-884878551
