### ISSUE TITLE
dooya.curtain.m2 窗帘 homekit中控制开关位置异常

### ISSUE THREAD

**Issue by Dark-Existed** [al-one/hass-xiaomi-miot#744]
homekit 中直接将位置拉到0 全关上 homeassistant中 target_positon 会从 0跳到其他位置
导致homekit中显示没关上 实际上已经关上了 
包括打开窗帘的时候也有类似的问题 

***homekit 中只操作了一次 没有多次操作***

## 关闭时候
https://user-images.githubusercontent.com/24956657/184586641-d61c786a-8b9c-4409-9081-88a4eaf9c07d.mov

## 打开时候

https://user-images.githubusercontent.com/24956657/184586791-ab2ed28d-6671-430a-95fd-36ae61c710a8.mov

**Comment by al-one** [comment]
当通过homekit关闭窗帘时，hk会通过插件向设备发送目标位置0%，指定发送成功后状态属性更新为目标位置0%，随后插件请求最新的设备状态，设备返回当前位置16%。
造成此问题的主要原因是homekit是调用HA的`cover.set_cover_position`服务来控制窗帘，而非`cover.close_cover`。另外你的窗帘在完全关闭的状态下实际位置为16%，应该是需要重置下窗帘行程。或者通过[自定义选项](https://github.com/al-one/hass-xiaomi-miot/issues/100#custom)`closed_position: 16`来指定关闭状态的位置。

**Comment by wolnlow** [comment]
自定义选项中能否增加一个配置，在某个区间值为关闭状态，某个区间值为打开状态，因为现在很多窗帘带百叶。

**Comment by wolnlow** [comment]
> 当通过homekit关闭窗帘时，hk会通过插件向设备发送目标位置0%，指定发送成功后状态属性更新为目标位置0%，随后插件请求最新的设备状态，设备返回当前位置16%。 造成此问题的主要原因是homekit是调用HA的`cover.set_cover_position`服务来控制窗帘，而非`cover.close_cover`。另外你的窗帘在完全关闭的状态下实际位置为16%，应该是需要重置下窗帘行程。或者通过[自定义选项](https://github.com/al-one/hass-xiaomi-miot/issues/100#custom)`closed_position: 16`来指定关闭状态的位置。

自定义选项中能否增加一个配置，在某个区间值为关闭状态，某个区间值为打开状态，因为现在很多窗帘带百叶。

**Comment by al-one** [comment]
HA的cover实体只有开/关/打开中/关闭中四种状态。
- https://developers.home-assistant.io/docs/core/entity/cover#states
