### ISSUE TITLE
请问有遇到过这样的情况吗，设备都可以正常的接入，而且可以正常使用，但是一旦重启ha之后，就会有几个设备失去连接，甚至可能是一个开关的某一个键，失去连接之后就再也连不回来了。但是只要安装之后不重启，我测试了几天，都正常。

### ISSUE THREAD

**Issue by jhchenchong** [al-one/hass-xiaomi-miot#746]
RT

**Comment by al-one** [comment]
请提供具体的[实体属性](https://my.home-assistant.io/redirect/developer_states)或[日志](https://my.home-assistant.io/redirect/logs)。

**Comment by jhchenchong** [comment]
> 请提供具体的[实体属性](https://my.home-assistant.io/redirect/developer_states)或[日志](https://my.home-assistant.io/redirect/logs)。

不好意思，这个issues先关了，我今天重新安装了最新版本的ha之后，重启没有复现之前的问题。如果下次出现了我再提供日志。谢谢！
