### ISSUE TITLE
怎么样调整Yeelight灯的更新同步时间啊

### ISSUE THREAD

**Issue by MagicStarTrace** [al-one/hass-xiaomi-miot#747]
我使用了mushroom的UI，用的Yeelight灯（wifi）

然后在米家APP打开灯以后，为什么3-4分钟才更新灯的状态？(我一直刷页面都没切换)

**Comment by al-one** [comment]
请通过[开发者工具](https://my.home-assistant.io/redirect/developer_states)观察实体状态及属性的变化。可以通过[自定义实体/设备](https://github.com/al-one/hass-xiaomi-miot/issues/600)的`interval_seconds`选项改变更新频率。

**Comment by big111boy** [comment]
麻烦看下，我也是这个问题，APP上操作了以后一直不会更新

min_mireds: 154
max_mireds: 370
effect_list: Day, Night
supported_color_modes: brightness, color_temp, onoff
color_mode: color_temp
brightness: 138
color_temp: 323
hs_color: 27.676, 54.374
rgb_color: 255, 180, 116
xy_color: 0.487, 0.381
effect: Day
model: yeelink.light.ceiling14
entity_class: MiotLightEntity
miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-ceiling14:2
light.on: true
light.brightness: 54
light.color_temperature: 3100
light.mode: 1
light.off_delay_time: 0
state_updater: lan
sub_entities: light-2.off_delay_time-102
friendly_name: 书房吸顶灯 Light
supported_features: 39

**Comment by al-one** [comment]
APP操作后需要等待30~60秒才能同步状态到HA。
