### ISSUE TITLE
viomi.vacuum.v7: Got MiioException: No response from the device while get_properties间歇性报错，起初我怀疑是家里wifi网络问题。但是。。。。

### ISSUE THREAD

**Issue by superwangmeng** [al-one/hass-xiaomi-miot#749]
首先，非常感谢作者这么牛x的插件并且在持续更新维护中，我的很多mijia设备慢慢都都转到这个集成了，本地模式支持的非常良好。

        我用该自定义集成目前接入7个wifi设备，通过账号集成方式，除了小爱音箱全部选择的是本地模式（之前用自动模式接入，在状态查看都是lan模式）。
插件使用良好，但是最近遇到偶尔设备没反应，在HA里体现为实体不可用，起初发现这个现象是我的扫拖机器人间歇性的变为实体不可用，日志内容有两种：

1. viomi.vacuum.v7: Got MiioException: No response from the device while get_properties(['suction_grade', ........
2. 扫地机器人(viomi.vacuum.v7): Got MiioException while fetching the state: Unable to discover the device 192.168.1.98, mapping: {'vacuum.mode': {'siid': ........

        我原本怀疑是wifi网络不稳，机器人有时候走远了可能信号不好，然后后来我发现间歇性的也会在充电状态时发生（充电庄离路由器很近），实体变为不可用的时长不定 有时候几分钟 有时候1分钟以内，实体的这种状态切换给我自动化带来了很大困扰，所以最近自动化我都改了。

之后根据观看日志发现该集成接入的貌似所有设备都会有这个报错，例如：

次卧智能插座(chuangmi.plug.212a01): Got MiioException while fetching the state: Unable to discover the device 192.168.1.217, mapping: {'switch.on........

小爱音箱(xiaomi.wifispeaker.l05c): Got MiioException while fetching the state: Unable to discover the device 192.168.1.73, mapping: {'play_contr........

空气净化器(zhimi.airpurifier.v6): Got MiioException while fetching the state: Unable to discover the device 192.168.1.216, mapping: {'air_purifier.on': {'siid': 2, 'piid': 1}, 'air.......

以上这些设备能看到日志里有报错，但是基本上使用正常，只有扫地机器人出现较频繁。
PS：我的网络很简单，所有设备在一个C段内，路由器linksys的mesh，有三个节点有线组的mesh网；
以上出现的频率不高，由于我老重启HA，有些log找不到了，所以想问问作者，这个究竟是网络问题？还是插件问题？

**Comment by al-one** [comment]
如果是间歇性报错，可能是查询设备状态过于频繁导致设备繁忙，以致于设备无响应。
可以尝试[自定义设备](https://github.com/al-one/hass-xiaomi-miot/issues/600)`interval_seconds: 120`以降低轮询频率，或者通过`auto_cloud: true`在本地不可用时请求云端状态。
