### ISSUE TITLE
xiaomi.aircondition.mt8小米巨省电空调不可用

### ISSUE THREAD

**Issue by OliverYN** [al-one/hass-xiaomi-miot#755]
此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.climate
Source: custom_components/xiaomi_miot/__init__.py:1342 
Integration: Xiaomi Miot Auto (documentation, issues) 
First occurred: 20:56:32 (9 occurrences) 
Last logged: 21:03:42

小米巨省电空调(xiaomi.aircondition.mt8): Got MiioException while fetching the state: Unable to parse message payload, mapping: {'air_conditioner.on': {'siid': 2, 'piid': 1}, 'air_conditioner.mode': {'siid': 2, 'piid': 2}, 'air_conditioner.fault': {'siid': 2, 'piid': 3}, 'target_temperature-2-4': {'siid': 2, 'piid': 4}, 'air_conditioner.eco': {'siid': 2, 'piid': 7}, 'air_conditioner.heater': {'siid': 2, 'piid': 9}, 'air_conditioner.dryer': {'siid': 2, 'piid': 10}, 'air_conditioner.sleep_mode': {'siid': 2, 'piid': 11}, 'air_conditioner.target_humidity': {'siid': 2, 'piid': 14}, 'unstraight_blowing-2-15': {'siid': 2, 'piid': 15}, 'machine_state.indoor_pipe_temp': {'siid': 12, 'piid': 1}, 'machine_state.indoor_fan_speed': {'siid': 12, 'piid': 3}, 'real_heater_switch-12-4': {'siid': 12, 'piid': 4}, 'realindoor_fan_lever-12-5': {'siid': 12, 'piid': 5}, 'machine_state.outdoor_temp': {'siid': 12, 'piid': 7}, 'machine_state.outdoor_pipe_temp': {'siid': 12, 'piid': 8}, 'outdoor_exhaust_temp-12-9': {'siid': 12, 'piid': 9}, 'machine_state.outdoor_fan_lever': {'siid': 12, 'piid': 10}, 'compressor_frequency-12-11': {'siid': 12, 'piid': 11}, 'fourway_valve_switch-12-12': {'siid': 12, 'piid': 12}, 'machine_state.outdoor_current': {'siid': 12, 'piid': 13}, 'machine_state.outdoor_m_voltage': {'siid': 12, 'piid': 14}, 'machine_state.expansion_valve': {'siid': 12, 'piid': 15}, 'longitude_latitude-12-16': {'siid': 12, 'piid': 16}, 'iot_linkage.iot_temp': {'siid': 11, 'piid': 1}, 'iot_linkage.temp_ctrl': {'siid': 11, 'piid': 5}, 'iot_linkage.smart_sleep_ctrl': {'siid': 11, 'piid': 6}, 'enhance.fan_percent': {'siid': 10, 'piid': 1}, 'enhance.timer': {'siid': 10, 'piid': 3}, 'enhance.humidity_range': {'siid': 10, 'piid': 6}, 'maintenance.clean': {'siid': 9, 'piid': 1}, 'maintenance.examine': {'siid': 9, 'piid': 2}, 'maintenance.running_duration': {'siid': 9, 'piid': 5}, 'electricity': {'siid': 8, 'piid': 1}, 'electricity.elec_count': {'siid': 8, 'piid': 3}, 'indicator_light.on': {'siid': 6, 'piid': 1}, 'alarm': {'siid': 5, 'piid': 1}, 'environment.temperature': {'siid': 4, 'piid': 7}, 'environment.relative_humidity': {'siid': 4, 'piid': 9}, 'fan_control.fan_level': {'siid': 3, 'piid': 2}, 'fan_control.vertical_swing': {'siid': 3, 'piid': 4}}, max_properties: 9/41

**Comment by al-one** [comment]
请检查设备固件是否可以升级。
