### ISSUE TITLE
gosund cp2 插座耗电量读取有误

### ISSUE THREAD

**Issue by ichenyf** [al-one/hass-xiaomi-miot#756]
cuco.plug.cp2
制造商：cuco
固件：2.0.4_0011

读取的月耗电量，如：sensor.cuco_cp2_b9b5_power_cost_month、sensor.cuco_cp2_b9b5_power_cost_tody，都是实际值的十分之一，比如耗电量是 215kWh，会读成 21.5kWh。

**Comment by ichenyf** [comment]
https://github.com/al-one/hass-xiaomi-miot/blob/59d23b5a065495e8507b11a4dd1e05ff312834e1/custom_components/xiaomi_miot/core/device_customizes.py#L181

修改这里的值 从 0.001 修改成 0.01 可以了

**Comment by al-one** [comment]
已修复，请更新至最新版本。

**Comment by ichenyf** [comment]
grateful
