### ISSUE TITLE
yunmi.ysj.v1 (MJMY23YM) Please add new device Water Dispenser Xiaomi Mijia 

### ISSUE THREAD

**Issue by VikeDragon** [al-one/hass-xiaomi-miot#757]
Please add new device https://home.miot-spec.com/spec/yunmi.ysj.v1

The device is connected to the Home Assistant as a thermostat, some of the properties are visible, but it cannot be controlled. For example, it is not possible to turn it on or off. it would be convenient to have switches similar to those given in the link. Please see how to include this device in the supported ones.

climate.yunmi_v1_eb27_water_dispenser    (state 'off') setting 'on' does not affect the device.

properties :
hvac_modes: off
min_temp: 0
max_temp: 100
target_temp_step: 1
current_temperature: 29
temperature: 95
hvac_action: off
model: yunmi.ysj.v1
lan_ip: 192.168.31.70
mac_address: CC:B5:D1:2D:EB:27
entity_class: MiotClimateEntity
miot_type: urn:miot-spec-v2:device:water-dispenser:0000A0A1:yunmi-v1:1
water_dispenser.fault: 0
water_dispenser.status: 1
water_dispenser.temperature: 29
target_temperature-2-4: 95
local_timing.scene_sequence: 0,0,0,0,0
local_timing.scene_one: 0000,0000,0.5,0
local_timing.scene_two: 0000,0000,0.5,0
local_timing.scene_three: 0000,0000,0.5,0
local_timing.scene_four: 0000,0000,0.5,0
local_timing.scene_five: 0000,0000,0.5,0
debug.water_lv: 1
debug.water_out_pump: 1660
debug.output_water_temp: 297
debug.cool_temp: 273
water_statistic.use_time: 0
water_statistic.flow_out: 0
water_statistic.temperature: 0
custom.icing: false
custom.current_mode_flow: 500,200,200,100
custom.current_mode_temp: 12,29,55,95
custom.mode: 4
custom.rinse_status: 0
custom.rinse_progress: 0
custom.child_lock: false
custom.drink_remind: false
custom.switch_button: true
custom.store_timeout: 0
custom.whether_have_water: 1
custom.buzzer_enable: true
state_updater: lan
friendly_name: Диспенсер Water Dispenser
supported_features: 1

**Comment by al-one** [comment]
Try latest release version.

**Comment by VikeDragon** [comment]
Greetings! 
Thank you for the high-speed change. Everything is done in the best possible way! 
Thank you so much, the support is at the highest level!
There is a small wish :
The main object is correctly placed in the newer water_heater domain, but as climate it could be used with thermostat maps. Is it possible to duplicate an entity and as a climate domain?

**Comment by al-one** [comment]
> The main object is correctly placed in the newer water_heater domain, but as climate it could be used with thermostat cards. Is it possible to duplicate an entity and as a climate domain?

Try [generic thermostat](https://www.home-assistant.io/integrations/generic_thermostat).

**Comment by VikeDragon** [comment]
I will follow the advice. Thank you for the excellent implementation!
