### ISSUE TITLE
米家智能插座2的传感器实体ID好像有错误

### ISSUE THREAD

**Issue by bonnyandsky** [al-one/hass-xiaomi-miot#758]
米家智能插座2
[chuangmi.plug.212a01](https://home.miot-spec.com/s/chuangmi.plug.212a01)
制造商：chuangmi
固件：2.1.8_0032

sensor.chuangmi_212a01_f693_power_consumption这个实体id的实际数据是昨日用电量。但是从名字上看不出来是昨日。不知道是插件的问题还是小米那边预设的名称导致的？
sensor.chuangmi_212a01_f693_electric_current这个实体的数据一直是5，不管插座是开还是关都是5，从名称看是电流。但是看起来并不是，大佬能告诉我这个实体是什么的数据么？

**Comment by bonnyandsky** [comment]
今天又观察了下，sensor.chuangmi_212a01_f693_power_consumption这个实体好像又不是昨日用电量。因为今天这个显示还是0.1kwh。但是昨日我特地测试了昨天的时候当日用电量是0.6kwh的。

**Comment by al-one** [comment]
https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:outlet:0000A002:chuangmi-212a01:2
该属性来着miot-spec规格，规格描述中没有明确的统计区间，因此我也不知道它具体是什么时间范围的用电量。
![xiaomi miot chuangmi.plug.212a01](https://user-images.githubusercontent.com/4549099/187111822-bbf97124-6f7c-47db-8dd1-e172958bf7e1.png)

**Comment by bonnyandsky** [comment]
> https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:outlet:0000A002:chuangmi-212a01:2 该属性来着miot-spec规格，规格描述中没有明确的统计区间，因此我也不知道它具体是什么时间范围的用电量。 ![xiaomi miot chuangmi.plug.212a01](https://user-images.githubusercontent.com/4549099/187111822-bbf97124-6f7c-47db-8dd1-e172958bf7e1.png)

electric_current这个也不是电流对吧？

**Comment by al-one** [comment]
> electric_current这个也不是电流对吧？

不太清楚，数据来自设备。
