### ISSUE TITLE
zhimi.airpurifier.mb4 do not show AQI on lovelace card

### ISSUE THREAD

**Issue by zibous** [al-one/hass-xiaomi-miot#76]
Please check zhimi.airpurifier.mb4

![Bildschirmfoto 2021-05-06 um 19 59 00](https://user-images.githubusercontent.com/30198737/117344361-98b88b00-aea5-11eb-9cf0-9fa10c492dfc.png)

![Bildschirmfoto 2021-05-06 um 20 01 09](https://user-images.githubusercontent.com/30198737/117344629-e0d7ad80-aea5-11eb-9619-964a8dc03777.png)

**Testcase miiocli, version 0.5.6** 
Test with `miiocli airpurifiermb4 --ip ******* --token ************** status` is working !

```json
Power: on
AQI: 92 μg/m³
Mode: OperationMode.Auto
LED brightness level: 8
Buzzer: True
Child lock: False
Filter life remaining: 97 %
Filter hours used: 106
Motor speed: 1256 rpm
Favorite RPM: 2000 rpm
```

**Comment by al-one** [comment]
No `aqi` related properties were found in [miot-spec](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-mb4:2). Only find `pm2.5-density` (siid: 3, piid: 4).
The `aqi` via `miiocli` is taken from the value of `pm2.5-density`.

https://github.com/rytilahti/python-miio/blob/8fa59e7113cef145050cbae4cba1c4e3607ed9b4/miio/airpurifier_miot.py#L278
