### ISSUE TITLE
Changing refresh/update interval on Air Purifier sensor

### ISSUE THREAD

**Issue by GergelyMagyar** [al-one/hass-xiaomi-miot#760]
Is it possible to change the update interval on Xiaomi Air Purifier devices?
The Pm2.5 sensor is getting updated roughly every 15 minutes which is a really long time and I feel like I am not getting a realistic number in home assistant because of this. I would like a much lower interval, maybe ~1 minute.

Thank you

**Comment by Tinteex** [comment]
Did you manage to fix it? Im Struggling with the same. sadly i dont understand the above advice to customize the device (im new)
