### ISSUE TITLE
米家屏幕挂灯1S

### ISSUE THREAD

**Issue by DeathAndLife** [al-one/hass-xiaomi-miot#768]
能不能实现对1s控制器（遥控器）的长按-双击的功能控制？
![image](https://user-images.githubusercontent.com/51323917/187907053-e803e111-c461-435d-9cf8-413de4efdd42.png)

**Comment by al-one** [comment]
自定义按键后的具体功能是什么？

**Comment by DeathAndLife** [comment]
> 自定义按键后的具体功能是什么？

双击的是：开启专注模式和开启延时关灯
长按的是：切换情景模式（灯光的模式）
我想提的是能不能将这两种触发方式弄出来，然后配合hass执行自定义的功能

**Comment by al-one** [comment]
无法支持。
