### ISSUE TITLE
大佬请教：米兔儿童手表6X（型号xiaoxun.watch.sw771），接入后实体直接显示地理位置而不是状态信息？

### ISSUE THREAD

**Issue by big111boy** [al-one/hass-xiaomi-miot#772]
大佬，请问下，米兔6X手表，型号是[xiaoxun.watch.sw771](https://home.miot-spec.com/s/xiaoxun.watch.sw771)，UI配置界面中找不到`disable_location_name`这个属性，在customize.yaml文件中配置了`disable_location_name: true`，但是device_tracker.xxxx实体默认显示的还是是地理位置信息，插件版本是0.6.11。

**Comment by al-one** [comment]
- `disable_location_name`已添加至UI配置，请更新至master后重试
- `customize.yaml`文件中的配置没有生效可能是格式不对，或者没有被include至`configuration.yaml`

**Comment by big111boy** [comment]
感谢大佬，已经可以配置disable_location_name并且生效了
