### ISSUE TITLE
希望能够禁用全局或者某个设备的离线通知

### ISSUE THREAD

**Issue by ichenyf** [al-one/hass-xiaomi-miot#774]
日常使用过程中，总会有部分设备是允许离线的，比如经常会有自动关闭某些设备的电源，例如晚上时间或家里没人时关闭洗衣机电源，关闭某些智能设备的电源，比如灯带、净化器、电视等，以减少待机时间的电能消耗，但总是定期出现这些设备离线的通知，比较影响使用，所以建议增加关闭某设备离线通知的选项，或者干脆全局禁用离线通知的选项。

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/606#issuecomment-1133811911
