### ISSUE TITLE
小米空调场景的一个怪异的问题

### ISSUE THREAD

**Issue by shenzhen1970** [al-one/hass-xiaomi-miot#775]
我用xiaomi Miot auto接入了一台小米巨省力立式空调和小米空调伴侣控，小米空调伴侣控制一台格力挂机。用空调控制卡片控制空调完全没有任何问题，但我建立了一个场景，比如说离开家时关闭空调，在场景中加入空调设备，无论如何设置，都有一个奇怪的现象，就是打开场景后，空调关闭，但过了一会，空调又会自动打开，设置为纯风模式，做了各种测试，一直没有搞明白，大家又没有遇到同样的问题。

**Comment by al-one** [comment]
你文中说的“场景”是HA中的[场景](https://my.home-assistant.io/redirect/scenes/)吗？

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/908#issuecomment-1342711068
