### ISSUE TITLE
米家空调伴侣1代不可用

### ISSUE THREAD

**Issue by babutree** [al-one/hass-xiaomi-miot#778]
![空调伴侣11](https://user-images.githubusercontent.com/21240045/188767019-9f31e0f0-2f01-417c-bbc9-89767f175594.png)
米家空调伴侣1代添加后不可用
另请教1代是否支持功率显示？谢谢！

**Comment by al-one** [comment]
请提供[日志](https://my.home-assistant.io/redirect/logs)。

**Comment by babutree** [comment]
`Logger: custom_components.xiaomi_miot.climate
Source: custom_components/xiaomi_miot/__init__.py:1342
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 09:10:15 (710 occurrences)
Last logged: 20:59:19

Mi Smart Air Conditioner Controller(lumi.acpartner.v2): Got MiioException while fetching the state: Unable to discover the device 192.168.88.111, mapping: {'air_conditioner.on': {'siid': 2, 'piid': 1}, 'air_conditioner.mode': {'siid': 2, 'piid': 2}, 'target_temperature-2-3': {'siid': 2, 'piid': 3}, 'fan_control.fan_level': {'siid': 3, 'piid': 1}, 'fan_control.vertical_swing': {'siid': 3, 'piid': 2}}, max_properties: 10/5`

**Comment by al-one** [comment]
https://github.com/al-one/hass-xiaomi-miot/issues/500#offline

**Comment by babutree** [comment]
空调伴侣一直是固定IP 使用xiaomi_miot_raw是正常的 切换成hass-xiaomi-miot就失联 可能哪里有bug吧 如果需要设备权限 我共享给您

**Comment by al-one** [comment]
`xiaomi_miot_raw`使用的是云端接入该设备。
而本插件已适配该设备本地接入，请检查HA和设备是否在同一个IP段。

**Comment by babutree** [comment]
> `xiaomi_miot_raw`使用的是云端接入该设备。 而本插件已适配该设备本地接入，请检查HA和设备是否在同一个IP段。

谢谢 如您所说确实不在一个网段 修改成云端模式正常了 再次感谢！
