### ISSUE TITLE
viomi.airer.ich108 Unable to discover the device, but can be controlled by ha

### ISSUE THREAD

**Issue by dyf991645** [al-one/hass-xiaomi-miot#779]
It's ip is in the same subnet as the HA, and I can control it by HA.

But HA notice the error every 15 s.

`
ERROR (MainThread) [custom_components.xiaomi_miot.cover] Viomi electric drying rack Lite 1C(viomi.airer.ich108): Got MiioException while fetching the state: Unable to discover the device 192.168.31.169, mapping: {'airer.fault': {'siid': 2, 'piid': 1}, 'airer.motor_control': {'siid': 2, 'piid': 2}, 'airer.status': {'siid': 2, 'piid': 4}, 'airer.current_position': {'siid': 2, 'piid': 7}, 'light.on': {'siid': 3, 'piid': 1}}, max_properties: 8/5
`

https://home.miot-spec.com/s/viomi.airer.ich108

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/search?type=issues&q=%22Unable+to+discover+the+device%22
