### ISSUE TITLE
请问倒入的小米设备可以在 homekit 中出现吗？

### ISSUE THREAD

**Issue by willemswang** [al-one/hass-xiaomi-miot#78]

**Comment by al-one** [comment]
可以通过HA内置的集成`HomeKit`桥接。

**Comment by willemswang** [comment]
> 可以通过HA内置的集成`HomeKit`桥接。

非常感谢🙏

https://bbs.hassbian.com/thread-3907-1-1.html

已解决。
我是因为之前添加了一个homekit的integration，之后把这个integration删掉之后。在configuration.yaml里面添加了一行homekit: 就解决了
