### ISSUE TITLE
Add missing entities for zhimi.airpurifier.mb4

### ISSUE THREAD

**Issue by mihsu81** [al-one/hass-xiaomi-miot#780]
Hi @al-one, 

Would it be possible to add additional entities for zhimi.airpurifier.mb4 in the template like in the official Xiaomi integration?
Missing: Enable/Disable Buzzer, Enable/Disable Child Lock, Set Favorite motor speed, Set, LED Brightness, Read current Motor speed.

The specifications are available here: https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-mb4:1 or https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-mb4:2

Thank you in advance.

![image](https://user-images.githubusercontent.com/40715497/189062414-321a67e6-9932-42e6-8e40-45d2ce0ba4f8.png)
![image](https://user-images.githubusercontent.com/40715497/189062436-a76c6d4d-941b-4e96-97ad-1f13a2a47774.png)

**Comment by al-one** [comment]
Try master branch.

**Comment by mihsu81** [comment]
Awesome @al-one. There are a couple of things to adjust though.

1. The entity for the current motor speed ([moto-speed-rpm](https://miot-spec.org/miot-spec-v2/spec/property?type=urn:zhimi-spec:property:moto-speed-rpm:00000001)) doesn't get created. Should be _moto_speed_rpm_ instead of _motor_speed_rpm_
2.  _moto_speed_rpm_ should actually be a slider like _brightness_. As a number input is difficult to djust.
3. Can the name of the _custom-service_ entities be changed: _aqi-updata-heartbeat_, _favorite_speed_ and _moto-speed-rpm_?
4. _Alarm_ should actually be Buzzer.

![image](https://user-images.githubusercontent.com/40715497/189080382-43b486f6-87cf-42cc-a9b5-31853b209243.png)

**Comment by mihsu81** [comment]
@al-one Would it be possible to also implement _Reset filter_? SIID 4 - AIID 1

I've tried adding ```        'select_properties': 'reset-filter-life',``` and ```        'button_actions': 'reset-filter-life',``` but the entity didn't get created.

P.S. Would be great if you could implement a way to modify the names of the entities which get created instead of the ones from _miot-spec.org_

**Comment by al-one** [comment]
```yaml
# customize.yaml
fan.zhimi_mb4_xxxx:
  button_actions: reset_filter_life
```

**Comment by mihsu81** [comment]
@al-one Thanks a lot. Using underscores instead of dashes made the button appear.

Pressing the button throws a warning in HA and the filter is not reset.
Looks like the device expects: ```3 - filter-used-time``` but I don't know how to specify it.
![image](https://user-images.githubusercontent.com/40715497/190117426-4674b960-8fce-44f7-b4d1-3de577047990.png)

```
This error originated from a custom integration.

Logger: custom_components.xiaomi_miot.fan
Source: custom_components/xiaomi_miot/__init__.py:2382
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 11:50:06 (1 occurrences)
Last logged: 11:50:06

Master Bedroom Air Purifier(zhimi.airpurifier.mb4): Call miot action {'did': '360529481', 'siid': 4, 'aiid': 1, 'in': []} failed: {'code': -9998, 'message': 'user ack invalid'}
```

**Comment by al-one** [comment]
Then you can only reset it through the service:
```yaml
service: xiaomi_miot.call_action
data:
  entity_id: fan.zhimi_mb4_xxxx
  siid: 4
  aiid: 1
  params: [1]
```

**Comment by mihsu81** [comment]
Nice. Looks like this action is telling the purifier how many hours have passed since the filter was last changed.
Anything between 0 and 166666 can be set, where 0 means 100% new, while 65000 means fully used (0%).
If a value can't be specified for "button_actions", I'll just create a script since it's easier to use.

**Comment by mihsu81** [comment]
I think it would provide for a better integration on some devices if a value could be specified for a service in dvice_customize.py.
Would it be worth opening a feature request in your repository for this, or you just want to leave it at this stage where a service call should be used?
Thanks again for your help and this integration. 😊
