### ISSUE TITLE
Unable to get properties for vacuum via the cloud

### ISSUE THREAD

**Issue by fokcuk** [al-one/hass-xiaomi-miot#784]
I cannot get the property of room numbers via miiocli as its only available via the cloud. But even though integration is suppose to be using the cloud, it still not returning room details

**Comment by al-one** [comment]
- Vacuum model ?
- Entity attributes ?

**Comment by fokcuk** [comment]
Thought it could be for any model. The one I have is Viomi S9 (v18)

**Comment by al-one** [comment]
Resubmit issue using the [template](https://github.com/al-one/hass-xiaomi-miot/issues/new?template=device-issue.yml).
