### ISSUE TITLE
Add missing entities for ijai.vacuum.v19

### ISSUE THREAD

**Issue by gvssr** [al-one/hass-xiaomi-miot#786]
Hi @al-one,

Would it be possible to add missing entities for Xiaomi Robot vacuum-mop 2S ([ijai.vacuum.v19](https://home.miot-spec.com/s/ijai.vacuum.v19))? I recently upgraded from Mi Robot vacuum-mop (dreame.vacuum.mc1808), but it's missing a lot of entities like consumables state, water level, battery charging state and more (also services/buttons like locate).

For comparison:

**Mi robot vacuum-mop**
![image](https://user-images.githubusercontent.com/61377476/189490206-5827c5f5-2968-46fb-bc5c-2ac7ce111fd8.png)

**While for Xiaomi Robot vacuum-mop 2S:**
![image](https://user-images.githubusercontent.com/61377476/189490220-35ed3371-14ed-4389-977a-3eaf31b5b33e.png)

It might be missing other entities as well. For instance, while you can set the mode (sweep, mop), you cannot set the actual fan speed (silent, standard, strong, turbo) like you can with the older Mi robot vacuum-mop. Haven't gotten to testing cleaning specific rooms yet, so not sure if that's implemented.

You can find the spec here I believe: https://home.miot-spec.com/spec/ijai.vacuum.v19

Thanks in advance! I can answer more device info questions if required.

**Comment by al-one** [comment]
Try master branch.

**Comment by gvssr** [comment]
@al-one Thanks for getting back to me so fast and it's much improved already. There's still a couple of things I've noticed:

**Fan Speed**
The new mode entity works well, but vacuum entity fan speed only displays mode, where fan speed would be expected. I think having mode as a separate entity as it currently is and actual fan speed in the entity card would be better
![image](https://user-images.githubusercontent.com/61377476/189823117-73363b82-c574-49eb-a221-bde5f61a74eb.png)
![image](https://user-images.githubusercontent.com/61377476/189823204-4f8ee84b-fe72-414f-8391-6e76f99b4325.png)

There's currently no entity or option to set the actual fan speed, but looking at the entity state it does look like it's being reported. The sweep.suction_state attribute changes when setting the fan speed in the Mi app, as follows:

sweep.suction_state: 0 = Silent
sweep.suction_state: 1 = Standard
sweep.suction_state: 2 = Strong
sweep.suction_state: 3 = Turbo

**Comment by gvssr** [comment]
**Sensors**
There are now subentities for the consumable % life, but not yet hours remaining:
![image](https://user-images.githubusercontent.com/61377476/189824355-733ad650-b2cf-4dfb-8cc5-1e9e2f24bb77.png)

Look like those are reported in:

sweep.side_brush_hours
sweep.main_brush_hours
sweep.hypa_hours
sweep.mop_hours

**Comment by gvssr** [comment]
**Sweep Type**
Main branch contains a new select entity but I'm not sure what it does:
![image](https://user-images.githubusercontent.com/61377476/189825290-0c49d45c-3625-43d3-96b4-e8a0ed5acfb4.png)

I've noticed at least one setting corresponds to "Clean up along the edges" in the Mi app. I could do more research if required

**Comment by al-one** [comment]
> There are now subentities for the consumable % life, but not yet hours remaining

Maybe you need to get them via customizing:
```yaml
# customize.yaml
vacuum.ijai_v19_xxxx:
  sensor_properties: vacuum.status,main_brush_life,side_brush_life,hypa_life,mop_life,main_brush_hours,side_brush_hours,hypa_hours,mop_hours
```

**Comment by gvssr** [comment]
@al-one Thank you, the latest commit in main fixes the fan speed:
![image](https://user-images.githubusercontent.com/61377476/189914456-43e9a861-8fcb-42dd-83ed-e72348db66bf.png)

And using your comment as a template I added a bunch more controls and sensors, thank you! You can close this one, I might add the most important ones (like water level) as a PR
![image](https://user-images.githubusercontent.com/61377476/189914895-f783a534-d932-499b-82e4-ef41d444ef3e.png)

**Comment by gvssr** [comment]
@al-one One last thing I noticed, a typo in the fan_speed. Should be "Silent, not "Slient". Couldn't find where to fix it in the code myself
![image](https://user-images.githubusercontent.com/61377476/189923072-044eab89-a6f6-4ba8-9448-4915972afd44.png)

**Comment by al-one** [comment]
![image](https://user-images.githubusercontent.com/4549099/190046884-2b90d87b-9dd3-4af5-a079-645d2bf0d079.png)

`Slient` is from [miot-spec.org](https://home.miot-spec.com/spec/ijai.vacuum.v19), we can fix it via [translation](https://github.com/al-one/hass-xiaomi-miot/blob/master/custom_components/xiaomi_miot/core/translation_languages.py).

**Comment by gvssr** [comment]
@al-one I updated to the latest master but the translation isn't coming through:

![image](https://user-images.githubusercontent.com/61377476/190081952-18d2b2dd-bf17-4fd2-9d78-536875f6547d.png)
![image](https://user-images.githubusercontent.com/61377476/190081999-d4c64fb3-4934-4ba1-9c06-54824d63dadd.png)

version c4f19eb

**Comment by al-one** [comment]
Configuration is required:
```yaml
# configuration.yaml
xiaomi_miot:
  language: en
```

**Comment by gvssr** [comment]
@al-one Looks good, you can close this one

![image](https://user-images.githubusercontent.com/61377476/190581420-d3121a29-32e4-418d-8ace-b4cfc8232fa6.png)
