### ISSUE TITLE
Error adding ijai.vacuum.v1

### ISSUE THREAD

**Issue by gvssr** [al-one/hass-xiaomi-miot#787]
I'm getting an error when adding [ijai.vacuum.v1](https://home.miot-spec.com/s/ijai.vacuum.v1):

`Mi Robot(ijai.vacuum.v19): Got MiioException while fetching the state: Unable to recover failed command, mapping: {'vacuum.status': {'siid': 2, 'piid': 1}, 'vacuum.fault': {'siid': 2, 'piid': 2}, 'vacuum.mode': {'siid': 2, 'piid': 4}, 'vacuum.sweep_type': {'siid': 2, 'piid': 8}, 'vacuum.on': {'siid': 2, 'piid': 9}, 'disturb.dnd_enable': {'siid': 12, 'piid': 1}, 'disturb.dnd_start_hour': {'siid': 12, 'piid': 2}, 'disturb.dnd_start_minute': {'siid': 12, 'piid': 3}, 'disturb.dnd_end_hour': {'siid': 12, 'piid': 4}, 'disturb.dnd_end_minute': {'siid': 12, 'piid': 5}, 'disturb.multi_prop_dnd': {'siid': 12, 'piid': 7}, 'map.remember_state': {'siid': 10, 'piid': 1}, 'map.cur_map_id': {'siid': 10, 'piid': 2}, 'map.map_num': {'siid': 10, 'piid': 3}, 'map.cur_cleaning_path': {'siid': 10, 'piid': 5}, 'map.build_map': {'siid': 10, 'piid': 14}, 'map.has_new_map': {'siid': 10, 'piid': 19}, 'sweep.repeat_state': {'siid': 7, 'piid': 1}, 'sweep.door_state': {'siid': 7, 'piid': 3}, 'sweep.cloth_state': {'siid': 7, 'piid': 4}, 'sweep.suction_state': {'siid': 7, 'piid': 5}, 'sweep.water_state': {'siid': 7, 'piid': 6}, 'sweep.mop_route': {'siid': 7, 'piid': 7}, 'sweep.side_brush_life': {'siid': 7, 'piid': 8}, 'sweep.side_brush_hours': {'siid': 7, 'piid': 9}, 'sweep.main_brush_life': {'siid': 7, 'piid': 10}, 'sweep.main_brush_hours': {'siid': 7, 'piid': 11}, 'sweep.hypa_life': {'siid': 7, 'piid': 12}, 'sweep.hypa_hours': {'siid': 7, 'piid': 13}, 'sweep.mop_life': {'siid': 7, 'piid': 14}, 'sweep.mop_hours': {'siid': 7, 'piid': 15}, 'sweep.direction': {'siid': 7, 'piid': 16}, 'sweep.time_zone': {'siid': 7, 'piid': 20}, 'sweep.cur_lang': {'siid': 7, 'piid': 21}, 'sweep.cleaning_time': {'siid': 7, 'piid': 22}, 'sweep.cleaning_area': {'siid': 7, 'piid': 23}, 'sweep.dirt_recognize': {'siid': 7, 'piid': 35}, 'sweep.pet_recognize': {'siid': 7, 'piid': 36}, 'sweep.ai_recognize': {'siid': 7, 'piid': 42}, 'sweep.carpet_booster': {'siid': 7, 'piid': 44}, 'sweep.multi_prop_vacuum': {'siid': 7, 'piid': 45}, 'sweep.carpet_avoid': {'siid': 7, 'piid': 47}, 'sweep.tank_shake': {'siid': 7, 'piid': 48}, 'sweep.shake_shift': {'siid': 7, 'piid': 50}, 'sweep.map_encrypt': {'siid': 7, 'piid': 55}, 'alarm': {'siid': 4, 'piid': 1}, 'alarm.volume': {'siid': 4, 'piid': 2}, 'battery_level': {'siid': 3, 'piid': 1}}, max_properties: 10/48`

**Comment by al-one** [comment]
keep reporting this error or occasionally ?

**Comment by gvssr** [comment]
Looks like only occasionally, haven't had it since and the device is now added. You can close this one
