### ISSUE TITLE
请问一下我的摄像机没有画面是正常的吗？

### ISSUE THREAD

**Issue by willemswang** [al-one/hass-xiaomi-miot#79]
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/27256966/117563320-a6555700-b0d7-11eb-88f8-3553842c12d8.png">

**Comment by al-one** [comment]
请提供实体状态属性：
> [🔨 开发者工具](https://my.home-assistant.io/redirect/developer_states) > [ℹ️ 状态](https://my.home-assistant.io/redirect/developer_states) > 🔍 筛选实体

**Comment by al-one** [comment]
https://github.com/al-one/hass-xiaomi-miot/issues/56#issuecomment-846336169
