### ISSUE TITLE
米家互联网空调的风速设置不太对

### ISSUE THREAD

**Issue by Young1223** [al-one/hass-xiaomi-miot#792]
设备型号：[zhimi.aircondition.ma4](https://home.miot-spec.com/s/zhimi.aircondition.ma4)
homeassistant版本：N1的docker里2022.9.14最新开发版
问题：通过本插件将空调接入，但是将风速设置为level1时，实际风速为2级，之后每一级设置风速都比实际风速小1，直到设置风速为5时空调实际风速变为自动

**Comment by al-one** [comment]
已修复，请更新至master分支

**Comment by Young1223** [comment]
> 已修复，请更新至master分支

感谢
