### ISSUE TITLE
Add seat heater functionnality to zhimi.toilet.va1

### ISSUE THREAD

**Issue by Sim7b** [al-one/hass-xiaomi-miot#799]
Hello,

Thanks for your work  !
Please,  can you  add this functionnality for this device : [zhimi.toilet.va1](https://home.miot-spec.com/s/zhimi.toilet.va1)
![image](https://user-images.githubusercontent.com/6420502/191013362-849fd695-44e1-49ea-8675-13cde7f8192a.png)

Thanks !

**Comment by al-one** [comment]
Show me the [entity attributes](https://my.home-assistant.io/redirect/developer_states).

**Comment by Sim7b** [comment]
Actually I have only this :
![image](https://user-images.githubusercontent.com/6420502/191019433-a076c64d-8f9e-4a3e-8a00-bb5747bb3f46.png)

**Comment by al-one** [comment]
Not this project.

**Comment by Sim7b** [comment]
Sorry, I tried with your project and it works !
Thanks
