### ISSUE TITLE
chuangmi.camera.ipc019 not working

### ISSUE THREAD

**Issue by niaosuan** [al-one/hass-xiaomi-miot#801]
New to HA. I successfully setup chuangmi.camera.ipc019 with Xiaomi Miot Auto however entity shown unavailable.

![image](https://user-images.githubusercontent.com/79821406/191209726-44a8cd72-f5d9-4a29-b2bd-37a0249f168a.png)

![image](https://user-images.githubusercontent.com/79821406/191209906-affdd9f5-254f-45bb-a202-523fc7db4ee4.png)

Any idea?

**Comment by nc1120917035** [comment]
cloud mode

**Comment by niaosuan** [comment]
> cloud mode

I see. Seems there is no local option, thanks I will test.

**Comment by h3ld3rkid** [comment]
> > cloud mode
> 
> I see. Seems there is no local option, thanks I will test.

Did you can get stream working?

**Comment by niaosuan** [comment]
> Did you can get stream working?

Sorry, I'm in my work peak period. I will let you know again.

**Comment by niaosuan** [comment]
> Did you can get stream working?

Tested working, but not very stable (CN server) need app to be active If unable to stream video. Once it's able to stream need to turn "camera stream" (Warning This is device intensive.) 

I will explore into Frigate. My current stable working CCTV TPLink Tapo.

**Comment by h3ld3rkid** [comment]
> > Did you can get stream working?
> 
> Tested working, but not very stable (CN server) need app to be active If unable to stream video. Once it's able to stream need to turn on "camera stream" (Warning This is device intensive.)
> 
> I will explore into Frigate. My current stable working CCTV TPLink Tapo.

How do you do this?
App active how? I have to open the app first?
How turn on camera stream?

thnkx

**Comment by niaosuan** [comment]
> How do you do this? App active how? I have to open the app first? How turn on camera stream?
> 
> thnkx

1. add Miot with cloud account signed in, at first wasn't able to view.
2. open mihome ap and stream the camera, then Miot start to able to view.
3. after first successful attempted, no more after that.

Redo the step again everytime It stop working. I had since stop using xiaomi in HA, maybe can look into flash the cam to RTSP.

**Comment by h3ld3rkid** [comment]
> > How do you do this? App active how? I have to open the app first? How turn on camera stream?
> > thnkx
> 
> 1. add Miot with cloud account signed in, at first wasn't able to view.
> 2. open mihome ap and stream the camera, then Miot start to able to view.
> 3. after first successful attempted, not able to stream again.
> 
> Redo the step again everytime It stop working. I had since stop using It in HA, maybe can look into flash the cam to RTSP.

No luck for me…. Cant get it work

thnkx

**Comment by niaosuan** [comment]
> No luck for me…. Cant get it work
> 
> thnkx

Ya, It took me few attempts to get It work. 

Just skip this and try RTSP I recommend.

**Comment by h3ld3rkid** [comment]
But for RTSP i have to “hack” the camera… and i have 4.x firm.. so i cant do this… or you have a magic trick for this?

thnkx

**Comment by niaosuan** [comment]
> But for RTSP i have to “hack” the camera… and i have 4.x firm.. so i cant do this… or you have a magic trick for this?
> 
> thnkx

Nawp I have not tried It but here is the [link ](https://github.com/telmomarques/xiaomi-360-1080p-hacks) to the firmware hack.

**Comment by h3ld3rkid** [comment]
> > But for RTSP i have to “hack” the camera… and i have 4.x firm.. so i cant do this… or you have a magic trick for this?
> > thnkx
> 
> Nawp I have not tried It but here is the [link ](https://github.com/telmomarques/xiaomi-360-1080p-hacks) to the firmware hack.
> 
> DO IT AT YOUR OWN RISK**

This just work below 4.x firm… theres no solution
