### ISSUE TITLE
Please add device support for era.airp.cwb03

### ISSUE THREAD

**Issue by VikeDragon** [al-one/hass-xiaomi-miot#802]
Please add device support for era.airp.cwb03
https://home.miot-spec.com/s/era.airp.cwb03

**Comment by al-one** [comment]
Supporting this device is difficult because it doesn't define any [specs](https://home.miot-spec.com/spec/era.airp.cwb03).

**Comment by VikeDragon** [comment]
Can I help with something? Maybe screenshots of the interface will help? Maybe I can collect some data? Tell me please...

**Comment by Psytoshgen** [comment]
https://home.miot-spec.com/spec/era.airp.cwb03
here some specs
