### ISSUE TITLE
无法访问小米API接口

### ISSUE THREAD

**Issue by pangpu** [al-one/hass-xiaomi-miot#805]
在使用账号集成方式登录的时候提示：

配置小米账户
HTTPSConnectionPool(host='account.xiaomi.com', port=443): Max retries exceeded with url: /pass/serviceLogin?sid=xiaomiio&_json=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f707de00bb0>: Failed to establish a new connection: [Errno -3] Try again'))
无法访问小米API接口

尝试切换小米服务器也无解。。
xiaomi miot auto插件是通过hacs下载的

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/500#unreach

检测网络或DNS。

**Comment by pangpu** [comment]
> * [登录失败/没有实体等常见问题解决办法 #500 (comment)](https://github.com/al-one/hass-xiaomi-miot/issues/500#unreach)
> 
> 检测网络或DNS。

感谢大佬回复。我的HA的网络应该是没啥问题的？我可以在HA管理界面顺利更新HA，HACS里也能顺利下载xiaomi miot auto。。

**Comment by al-one** [comment]
`Failed to establish a new connection: [Errno -3] Try again`

报这个错误，只能是网络问题。

**Comment by PhDLuffy** [comment]
#### 无法登陆小米账号的问题困扰我很久了，今天终于解决了。

#### 核心原因是如果你的网络无法解析到ipv6的DNS，就会出现无法登陆或无法访问接口的问题。

我用tcpdump测试了下，

#### 在Host模式下

当访问api.xiaomi.com的时候，路由DNS返回正确的ipv4地址，同时返回空的ipv6地址(或错误无法解析)，

此时，HA直接就丢掉正确的ipv4的ip，显示bad address，无法进一步访问接口。

#### 在bridge或者macvlan模式下

如果路由DNS返回正确的ipv4地址，同时ipv6错误，会接着用ipv4来访问接口，正常登陆

#### 路由的ipv6 DNS解析正常

无论是host还是bridge还是macvlan，正常登陆。

**Comment by nanshihui** [comment]
想问问网络设置是在哪里设置的

**Comment by al-one** [comment]
@nanshihui 如果你有类似问题，请重新提交issue，并提供相关报错日志。我将关闭此issue。

**Comment by qfwc258** [comment]
> 
你好，请问是怎么解决的？

**Comment by yangjinhui2936** [comment]
有解决的吗

**Comment by jameszhang023** [comment]
是ipv6的问题，以我的群晖docker为例，进入群晖网络设置种关闭ipv6就可以了。
