### ISSUE TITLE
小米电视盒子homekit遥控器控制问题

### ISSUE THREAD

**Issue by XHFO** [al-one/hass-xiaomi-miot#806]
家庭app内可以关闭电视盒子（自定义实体中开启了电视机熄屏） homekit遥控器可以调整音量大小  但方向键返回确认菜单都没有用

**Comment by al-one** [comment]
请提供开发者工具中的[实体属性](https://my.home-assistant.io/redirect/developer_states)。
并检测有没有一个`select.xiaomi_xxxx_keycodes`实体。

**Comment by XHFO** [comment]
有的
![image](https://user-images.githubusercontent.com/52497157/191953816-e3258054-dc45-48b9-a2ff-2059da4f59c3.png)

**Comment by XHFO** [comment]
好像在之前老版本是可以用的 我昨天更新了一下插件

**Comment by al-one** [comment]
`restored: true`表示实体未接入HA
