### ISSUE TITLE
Xiaomi Miot Auto: intelligent_speaker 发送语音指令 小爱音箱死机

### ISSUE THREAD

**Issue by 86580425** [al-one/hass-xiaomi-miot#807]
Xiaomi Miot Auto: intelligent_speaker 执行一个语音指令，这个语音指令是配置在小爱音箱-训练里面的
大概有十来个指令，包括小爱音箱自定义指令
然后执行1-2遍后小爱音箱就死机了，必须重启才能用
米家app提示部分执行成功，失败的是在米家app里定义的小米音箱自定义指令
使用的Xiaomi Miot Auto 0.6.12的插件
音箱是小米play增强版

**Comment by 86580425** [comment]
图片：
![捕获1](https://user-images.githubusercontent.com/114288075/192092849-10973e59-ce74-41da-ac43-2789d69bb1c8.PNG)
![捕获](https://user-images.githubusercontent.com/114288075/192092859-24002db4-5511-4570-8d67-036e8c2d22f3.PNG)

**Comment by al-one** [comment]
貌似与插件无关。
