### ISSUE TITLE
关于小米空气净化器2接入hass后，空气质量历史曲线不能显示为曲线的样式

### ISSUE THREAD

**Issue by gaupay** [al-one/hass-xiaomi-miot#81]
1.安装最新0.3.3（2021.5.12）版本，接入小米空气净化器可以正确识别，所有功能均正常，唯独空气质量的历史曲线不能正常显示。
2.经查询HASS卡片功能说明：只有显示的数值具有单位（unit of measurement）时，才可以显示为曲线，无单位时显示为色卡样式。
3.在HASS中查询到sensor.xiaomi_miot_air_purifier_pm2_5_density，的确没有单位
希望作者能够设置一下代码，给这个数据加一个单位，随便一个单位就行（ppm or ug/cm3 ... anything is OK）,以便能够正常显示出曲线。

**Comment by gaupay** [comment]
![概览页面](https://user-images.githubusercontent.com/75199635/118095787-11b66600-b403-11eb-8b14-df013cfbf5da.jpg)
![配置设备页面](https://user-images.githubusercontent.com/75199635/118095821-2135af00-b403-11eb-81b6-0d6e4996b66d.jpg)
![开发者工具页面](https://user-images.githubusercontent.com/75199635/118095829-24309f80-b403-11eb-932f-c79b0ee40809.jpg)

**Comment by al-one** [comment]
请尝试通过[自定义](https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui)设置单位：
> [⚙️ 配置](https://my.home-assistant.io/redirect/config) > 🖌 [自定义](https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui) > 🔍 选择实体 > 选择要覆盖的属性 > `unit_of_measurement`

**Comment by gaupay** [comment]
没有安装hass.io,我直接在configure.yaml中修改的自定义属性，完美解决此问题，感谢。

![Uploading CODE.jpg…]()
