### ISSUE TITLE
米家空调伴侣Pro lumi.acpartner.mcn04 不可用

### ISSUE THREAD

**Issue by MondoGao** [al-one/hass-xiaomi-miot#810]
![image](https://user-images.githubusercontent.com/3753893/192140631-1ece39c4-34ae-44c2-9417-70ab904b385f.png)

尝试过强制 cloud 模式，也不生效，当前配置如下：
![image](https://user-images.githubusercontent.com/3753893/192140710-c19d4cb0-237b-41ae-b61d-bb5d9c69b435.png)

固件版本：2.2.1.0022

**Comment by al-one** [comment]
- 提供相关报错[日志](https://my.home-assistant.io/redirect/logs)
- https://github.com/al-one/hass-xiaomi-miot/issues/500#offline

**Comment by MondoGao** [comment]
> * 提供相关报错[日志](https://my.home-assistant.io/redirect/logs)
> * [登录失败/没有实体等常见问题解决办法 #500 (comment)](https://github.com/al-one/hass-xiaomi-miot/issues/500#offline)

日志中没有任何有用的信息。插件也未报错。两个关联实体的日志如下：
![Screen Shot 2022-09-26 at 23 02 46](https://user-images.githubusercontent.com/3753893/192312373-fba0807c-8d4a-4079-8d97-df455c2076f4.png)


![Screen Shot 2022-09-26 at 23 02 50](https://user-images.githubusercontent.com/3753893/192313671-93cd2bf8-0d03-45a7-8355-e7d12005701f.png)

**Comment by MondoGao** [comment]
其它本地设备和云端设备都是正常的，64 个设备里就这个有问题，不知道该从哪排查了

**Comment by MondoGao** [comment]
更换了 IP，重新同步了设备，设备 IP 也是对的，但就是不可用，状态也不对
![CleanShot 2022-09-26 at 23 24 14](https://user-images.githubusercontent.com/3753893/192316838-4779af6c-15f7-487c-a786-10bd4d4ca2c9.png)

**Comment by al-one** [comment]
HA也在192.168.50网段吗？

**Comment by MondoGao** [comment]
> 

在，ha 部署在 nas 上（192.168.50.10），network=host

**Comment by MondoGao** [comment]
> HA也在192.168.50网段吗？


在，ha 部署在 nas 上（192.168.50.10），container 模式部署，network=host

**Comment by al-one** [comment]
提供下climate实体的[属性](https://my.home-assistant.io/redirect/developer_states)。

**Comment by al-one** [comment]
日志位置：配置 > 系统 > 日志

**Comment by MondoGao** [comment]
> 日志位置：配置 > 系统 > 日志

哦抱歉，这里是有错误的。
<img width="1491" alt="CleanShot 2022-09-27 at 11 55 30@2x" src="https://user-images.githubusercontent.com/3753893/192428329-4031ead3-9eab-499a-849d-95f429a1d8d2.png">

```
Logger: custom_components.xiaomi_miot.climate
Source: custom_components/xiaomi_miot/__init__.py:1343
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues))
First occurred: 2022年9月25日 20:18:07 (2377 occurrences)
Last logged: 11:54:21

空调(lumi.acpartner.mcn04): Got MiioException while fetching the state: Unable to recover failed command, mapping: {'air_conditioner.on': {'siid': 3, 'piid': 1}, 'air_conditioner.mode': {'siid': 3, 'piid': 2}, 'air_conditioner.fault': {'siid': 3, 'piid': 3}, 'target_temperature-3-4': {'siid': 3, 'piid': 4}, 'indicator_light': {'siid': 9, 'piid': 1}, 'indicator_light.effective_time': {'siid': 9, 'piid': 2}, 'ac_function.set_ele_info': {'siid': 8, 'piid': 1}, 'ac_function.brand_id': {'siid': 8, 'piid': 2}, 'ac_function.remote_id': {'siid': 8, 'piid': 3}, 'ac_function.ac_mode': {'siid': 8, 'piid': 4}, 'ac_function.ac_type': {'siid': 8, 'piid': 5}, 'ac_function.ac_ctrl_range': {'siid': 8, 'piid': 6}, 'ac_function.ac_state': {'siid': 8, 'piid': 7}, 'ac_function.quick_cool_enable': {'siid': 8, 'piid': 8}, 'ac_function.quick_cool_time': {'siid': 8, 'piid': 9}, 'ac_function.quick_cool_status': {'siid': 8, 'piid': 10}, 'ac_function.sleep_cfg': {'siid': 8, 'piid': 11}, 'ac_function.sleep_status': {'siid': 8, 'piid': 12}, 'power_consumption': {'siid': 7, 'piid': 1}, 'electric_power-7-2': {'siid': 7, 'piid': 2}, 'power_consumption-7-3': {'siid': 7, 'piid': 3}, 'electric_power-7-4': {'siid': 7, 'piid': 4}, 'fan_control.fan_level': {'siid': 4, 'piid': 2}, 'fan_control.vertical_swing': {'siid': 4, 'piid': 4}}, max_properties: 7/24
空调(lumi.acpartner.mcn04): Got MiioException while fetching the state: Unable to discover the device 192.168.50.16, mapping: {'air_conditioner.on': {'siid': 3, 'piid': 1}, 'air_conditioner.mode': {'siid': 3, 'piid': 2}, 'air_conditioner.fault': {'siid': 3, 'piid': 3}, 'target_temperature-3-4': {'siid': 3, 'piid': 4}, 'indicator_light': {'siid': 9, 'piid': 1}, 'indicator_light.effective_time': {'siid': 9, 'piid': 2}, 'ac_function.set_ele_info': {'siid': 8, 'piid': 1}, 'ac_function.brand_id': {'siid': 8, 'piid': 2}, 'ac_function.remote_id': {'siid': 8, 'piid': 3}, 'ac_function.ac_mode': {'siid': 8, 'piid': 4}, 'ac_function.ac_type': {'siid': 8, 'piid': 5}, 'ac_function.ac_ctrl_range': {'siid': 8, 'piid': 6}, 'ac_function.ac_state': {'siid': 8, 'piid': 7}, 'ac_function.quick_cool_enable': {'siid': 8, 'piid': 8}, 'ac_function.quick_cool_time': {'siid': 8, 'piid': 9}, 'ac_function.quick_cool_status': {'siid': 8, 'piid': 10}, 'ac_function.sleep_cfg': {'siid': 8, 'piid': 11}, 'ac_function.sleep_status': {'siid': 8, 'piid': 12}, 'power_consumption': {'siid': 7, 'piid': 1}, 'electric_power-7-2': {'siid': 7, 'piid': 2}, 'power_consumption-7-3': {'siid': 7, 'piid': 3}, 'electric_power-7-4': {'siid': 7, 'piid': 4}, 'fan_control.fan_level': {'siid': 4, 'piid': 2}, 'fan_control.vertical_swing': {'siid': 4, 'piid': 4}}, max_properties: 7/24
```

**Comment by MondoGao** [comment]
> 提供下climate实体的[属性](https://my.home-assistant.io/redirect/developer_states)。

这个 404 了
![CleanShot 2022-09-27 at 11 56 37@2x](https://user-images.githubusercontent.com/3753893/192428512-19c4f2eb-b346-4d51-b32e-2ffe774e0994.png)

**Comment by al-one** [comment]
设备是否最新固件？建议给设备断电重启后再试

**Comment by MondoGao** [comment]
> 设备是否最新固件？建议给设备断电重启后再试

Home Assistant 2022.9.6
固件版本：2.2.1.0022，昨天已尝试过断电（我换 dhcp ip 到静态了，要断电刷一下的 0 - 0）

**Comment by al-one** [comment]
开发者工具 > 状态

**Comment by MondoGao** [comment]
> 开发者工具 > 状态
![image](https://user-images.githubusercontent.com/3753893/192513840-abdf9956-00f3-495a-be5f-5564487f5a20.png)

**Comment by kuroyukihime0** [comment]
遇到了同样的问题， 两台米家空调伴侣Pro，一台连接正常，一台无论怎么都是不可用

**Comment by yetone** [comment]
遇到了同样的问题，好难过

**Comment by yetone** [comment]
找到解决方案了：https://github.com/al-one/hass-xiaomi-miot/issues/486#issuecomment-1120690037

**Comment by al-one** [comment]
已默认为该设备开启自动云端(`auto_cloud`)，将在本地不可用时使用云端读取状态和控制设备。
