### ISSUE TITLE
Dreame L10s Ultra (dreame.vacuum.r2228o) support

### ISSUE THREAD

**Issue by Dopamin2485** [al-one/hass-xiaomi-miot#811]
Please support the new Dreame L10s Ultra (dreame.vacuum.r2228o)
When i tried to add the device i get following error in the log:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.xiaomi_miot.vacuum
Source: custom_components/xiaomi_miot/__init__.py:1343
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 21:27:45 (7 occurrences)
Last logged: 21:33:50

DreameBot L10s Ultra(dreame.vacuum.r2228o): Got MiioException while fetching the state: Unable to discover the device 192.168.10.147, mapping: {'vacuum.status': {'siid': 2, 'piid': 1}, 'vacuum.fault': {'siid': 2, 'piid': 2}, 'vacuum.mode': {'siid': 2, 'piid': 3}, 'silver_ion.silverion_life_time': {'siid': 19, 'piid': 1}, 'silver_ion.silverion_life_level': {'siid': 19, 'piid': 2}, 'mop.mop_life_level': {'siid': 18, 'piid': 1}, 'mop.mop_left_time': {'siid': 18, 'piid': 2}, 'collect_dust.auto_collect': {'siid': 15, 'piid': 1}, 'collect_dust.clean_times': {'siid': 15, 'piid': 2}, 'collect_dust.dust_enable': {'siid': 15, 'piid': 3}, 'collect_dust.dust_status': {'siid': 15, 'piid': 5}, 'clean_logs.first_clean_time': {'siid': 12, 'piid': 1}, 'clean_logs.total_clean_time': {'siid': 12, 'piid': 2}, 'clean_logs.total_clean_times': {'siid': 12, 'piid': 3}, 'clean_logs.total_clean_area': {'siid': 12, 'piid': 4}, 'audio.volume': {'siid': 7, 'piid': 1}, 'audio.voice_packet_id': {'siid': 7, 'piid': 2}, 'audio.voice_change_state': {'siid': 7, 'piid': 3}, 'audio.set_voice': {'siid': 7, 'piid': 4}, 'map.map_extend_data': {'siid': 6, 'piid': 4}, 'map.mult_map_state': {'siid': 6, 'piid': 7}, 'map.mult_map_info': {'siid': 6, 'piid': 8}, 'do_not_disturb.enable': {'siid': 5, 'piid': 1}, 'do_not_disturb.start_time': {'siid': 5, 'piid': 2}, 'do_not_disturb.end_time': {'siid': 5, 'piid': 3}, 'vacuum_extend.work_mode': {'siid': 4, 'piid': 1}, 'vacuum_extend.cleaning_time': {'siid': 4, 'piid': 2}, 'vacuum_extend.cleaning_area': {'siid': 4, 'piid': 3}, 'vacuum_extend.cleaning_mode': {'siid': 4, 'piid': 4}, 'vacuum_extend.mop_mode': {'siid': 4, 'piid': 5}, 'vacuum_extend.waterbox_status': {'siid': 4, 'piid': 6}, 'vacuum_extend.task_status': {'siid': 4, 'piid': 7}, 'vacuum_extend.clean_extend_data': {'siid': 4, 'piid': 10}, 'break_point_restart-4-11': {'siid': 4, 'piid': 11}, 'vacuum_extend.carpet_press': {'siid': 4, 'piid': 12}, 'vacuum_extend.serial_number': {'siid': 4, 'piid': 14}, 'vacuum_extend.remote_state': {'siid': 4, 'piid': 15}, 'vacuum_extend.clean_rags_tip': {'siid': 4, 'piid': 16}, 'vacuum_extend.keep_sweeper_time': {'siid': 4, 'piid': 17}, 'vacuum_extend.faults': {'siid': 4, 'piid': 18}, 'vacuum_extend.nation_matched': {'siid': 4, 'piid': 19}, 'vacuum_extend.relocation_status': {'siid': 4, 'piid': 20}, 'vacuum_extend.laser_switch': {'siid': 4, 'piid': 21}, 'vacuum_extend.ai_switch': {'siid': 4, 'piid': 22}, 'vacuum_extend.clean_setting': {'siid': 4, 'piid': 23}, 'vacuum_extend.mop_status': {'siid': 4, 'piid': 25}, 'vacuum_extend.custom_enable': {'siid': 4, 'piid': 26}, 'vacuum_extend.child_lock': {'siid': 4, 'piid': 27}, 'vacuum_extend.sensitivity': {'siid': 4, 'piid': 28}, 'vacuum_extend.mop_way': {'siid': 4, 'piid': 29}, 'vacuum_extend.clean_cancel': {'siid': 4, 'piid': 30}, 'carpet_distinguish-4-33': {'siid': 4, 'piid': 33}, 'vacuum_extend.autowash_switch': {'siid': 4, 'piid': 34}, 'vacuum_extend.warn_status': {'siid': 4, 'piid': 35}, 'vacuum_extend.carpet_clean': {'siid': 4, 'piid': 36}, 'auto_add_detergent-4-37': {'siid': 4, 'piid': 37}, 'vacuum_extend.dry_time': {'siid': 4, 'piid': 40}, 'vacuum_extend.nowater_tips': {'siid': 4, 'piid': 41}, 'filter.filter_life_level': {'siid': 11, 'piid': 1}, 'filter.filter_left_time': {'siid': 11, 'piid': 2}, 'brush_left_time-10-1': {'siid': 10, 'piid': 1}, 'brush_life_level-10-2': {'siid': 10, 'piid': 2}, 'brush_cleaner.brush_left_time': {'siid': 9, 'piid': 1}, 'brush_cleaner.brush_life_level': {'siid': 9, 'piid': 2}, 'battery_level': {'siid': 3, 'piid': 1}, 'battery.charging_state': {'siid': 3, 'piid': 2}}, max_properties: 10/66

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/search?type=issues&q=%22Unable+to+discover+the+device%22
