### ISSUE TITLE
Air purifier 3C (zhimi.airp.mb4a) - favorite level fan speed

### ISSUE THREAD

**Issue by Szeryff** [al-one/hass-xiaomi-miot#812]
Can you add support to change favorite level fan speed on Air purifier 3C (zhimi.airp.mb4a)?

I have 3 other models of purifiers added with MIoT and each one have entity to set fan.speed.
I'm using latest version installed via HACS.

![obraz](https://user-images.githubusercontent.com/5165008/192830359-eb6d7d99-cb23-49e4-b4dd-c480030b2fbf.png)

**Comment by Szeryff** [comment]
I've checked MIIO integration for this purifier and it is characterized not as **fan.speed** but as **_favorite_motor_speed** and value is set in RPM:
![obraz](https://user-images.githubusercontent.com/5165008/193466740-a7131f43-a93c-4b08-9ff7-03143e019e2c.png)

**Comment by al-one** [comment]
Try master branch.

**Comment by Szeryff** [comment]
I've applied this part of code on my server and everything works as expected. Thank you.
