### ISSUE TITLE
custom_components.xiaomi_miot.number::MiotNumberSubEntity is overriding deprecated methods

### ISSUE THREAD

**Issue by bluehj777** [al-one/hass-xiaomi-miot#814]
Logger: homeassistant.components.number
Source: components/number/__init__.py:119
Integration: 数值输入器 (documentation, issues)
First occurred: 01:33:20 (1 occurrences)
Last logged: 01:33:20

custom_components.xiaomi_miot.number::MiotNumberSubEntity is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.

**Comment by RadioLed2000** [comment]
Logger: homeassistant.components.number
Source: components/number/__init__.py:119
Integration: Number (documentation, issues)
First occurred: September 27, 2022 at 23:59:43 (2 occurrences)
Last logged: September 27, 2022 at 23:59:43

custom_components.xiaomi_miot.number::MiotNumberSubEntity is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
custom_components.xiaomi_miot.number::MiotNumberActionSubEntity is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.

**Comment by tamamma** [comment]
> Logger: homeassistant.components.number Source: components/number/**init**.py:119 Integration: Number (documentation, issues) First occurred: September 27, 2022 at 23:59:43 (2 occurrences) Last logged: September 27, 2022 at 23:59:43
> 
> custom_components.xiaomi_miot.number::MiotNumberSubEntity is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author. custom_components.xiaomi_miot.number::MiotNumberActionSubEntity is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.

Same here...

**Comment by bluehj777** [comment]
For This 

> custom_components.xiaomi_miot.number::MiotNumberActionSubEntity is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.

I edit /homeassistant/custom_components/xiaomi_miot/number.py
#def set_value(self, value: float):
and add
def set_native_value(self, value: float):
this error can be fixed

**Comment by auanasgheps** [comment]
Please address this issue, 2022.10 will be released very soon!

**Comment by auanasgheps** [comment]
Seems it's being worked on
#73233

**Comment by gudvinr** [comment]
@auanasgheps there is beta version in releases
