### ISSUE TITLE
云米晾衣架 不能執行風干

### ISSUE THREAD

**Issue by kei81131** [al-one/hass-xiaomi-miot#817]
你好, [云米的晾衣架](https://home.miot-spec.com/s/viomi.airer.vch110)在miot auto 中無法執行風干
下圖的Airer Dryer (switch), 按後會打開一下, 然後馬上關閉

在米家app 是可以執行正常
而且執行後, miot auto 中的switch沒有反應

![image](https://user-images.githubusercontent.com/111072203/192676852-f39145fc-b5a5-49b2-9a69-040b3b2fda95.png)

**Comment by al-one** [comment]
![image](https://user-images.githubusercontent.com/4549099/194798489-ba003806-cbb7-4870-aec2-d29334858979.png)
点开此实体切换风速

**Comment by kei81131** [comment]
你好
點開後並沒有找到切換風速的選項
裡面的switch 也是沒法操作

![airer dryer](https://user-images.githubusercontent.com/111072203/195228862-49bed861-fc8d-41e7-959c-fc4ac73ee98f.jpg)

**Comment by al-one** [comment]
尝试master分支。

**Comment by kei81131** [comment]
你好, 修改device_customizes.py 後
操作頁多了些選項

但, dryer 的部份還是沒反應

![image](https://user-images.githubusercontent.com/111072203/195483561-9d3374c7-374e-4512-9ac5-ed0d3b4718f4.png)

**Comment by kei81131** [comment]
不知道是不是因為Dryer 原來已指派為"switch"
所以沒法修改
![image](https://user-images.githubusercontent.com/111072203/195494289-da3e5a54-8927-4813-909e-933dabbf2985.png)

**Comment by al-one** [comment]
再次更新后尝试。

**Comment by kei81131** [comment]
可以了, 謝謝大佬 ^_^
