### ISSUE TITLE
小米智能插座3 cuco.plug.v3 接入后不显示每日和每月电量

### ISSUE THREAD

**Issue by Loyido** [al-one/hass-xiaomi-miot#820]
![8C80A3ADCA2073055D9746E79F4D5B53](https://user-images.githubusercontent.com/80599145/193050764-b2f8a0c0-ac23-44ec-9da3-62ff5c4192b2.png)
如图。
设备接入后仅Power Consumption Electric正常显示，Power Consumption无法正常工作

**Comment by al-one** [comment]
尝试master分支。

**Comment by xiaolan66** [comment]
使用远端模式连接可以解决

**Comment by qq289531426** [comment]
我也是，添加的时候选择自动都不行，开关都点不了，只有选择了远端模式链接才能正常运行。那意思是如果断网情况下是不是就不能使用这个插座了

**Comment by doradoradoradoradoradora** [comment]
请问下您使用小米智能插座有用到小米miio协议吗？用的是miio里面的哪个协议？我下载的python-miio  0.5.12版本没有看到cuco的协议,请问你是怎么使用cuco.plug.v3的？
