### ISSUE TITLE
添加空气净化器的异常

### ISSUE THREAD

**Issue by GINmvp** [al-one/hass-xiaomi-miot#821]
![1](https://user-images.githubusercontent.com/40859392/193409972-9de914a6-bd82-442e-a2de-4228cfb52d3c.png)
![image](https://user-images.githubusercontent.com/40859392/193410081-8404ab49-62f3-49be-8b58-90660ceddd70.png)

通过Miot添加小米空气净化器2s,极少数可以添加成功可以控制开关看到温湿度度数，绝大多数情况下是什么也不显示

**Comment by al-one** [comment]
图中设备不是由本项目接入的。
