### ISSUE TITLE
Unable to detect Smart Clothes Dryer (hyd.airer.znlyj1) when it is powered on

### ISSUE THREAD

**Issue by donald-ong** [al-one/hass-xiaomi-miot#824]
Hi,

I would like to share that Smart Clothes Dryer is not detectable when the power is on. I tried reloading but it is not working.

hyd.airer.znlyj1
by hyd
Firmware: 2.2.4

Home Assistant 2022.9.7
Supervisor 2022.09.1
Operating System 9.0
Frontend 20220907.2 - latest

Please advise if you can help.

Thank you.

**Comment by al-one** [comment]
Any [logs](https://my.home-assistant.io/redirect/logs) ?

**Comment by donald-ong** [comment]
After the new update to [v0.7.0b1], it is working now. Thank you.
