### ISSUE TITLE
您好，该插件支持多用户嘛

### ISSUE THREAD

**Issue by greenhat616** [al-one/hass-xiaomi-miot#827]
RT，使用环境是宿舍、公寓：多个房客拥有各自的小米智能家居，经过协商后想一起接入 HA。

尝试再添加过插件后再次添加 MIOT 继承，发现只有 IP/TOKEN 和自动发现设备的添加选项。

如果不行的，能通过客制化支持嘛？亦或者以后有可能在官方版本得到支持嘛？

**Comment by al-one** [comment]
本插件支持添加多个账号，请确保你使用的是`Xiaomi Miot Auto`。

**Comment by greenhat616** [comment]
感谢，我才发现我反馈错了仓库。我目前使用的是 `Xiaomi Miot Raw`。我现在尝试下 Auto，感谢作者的耐心回复！
