### ISSUE TITLE
跨网段的局域网设备无法添加

### ISSUE THREAD

**Issue by yanguoqing123** [al-one/hass-xiaomi-miot#828]
跨网段的设备无法添加，不同的网段设备可以ping通。但是添加不了。我其它博联的设备跨网段可以正常添加控制。现在只能通过云端添加。

**Comment by al-one** [comment]
跨网段无法本地接入，是由于miio协议限制，建议移到和HA同一网段。

- https://python-miio.readthedocs.io/en/latest/troubleshooting.html#discover-devices-across-subnets
- https://github.com/rytilahti/python-miio/issues/422#issuecomment-455824152
