### ISSUE TITLE
Smart Air Purifier 4 (zhimi.airp.mb5) missing controls

### ISSUE THREAD

**Issue by leroyloren** [al-one/hass-xiaomi-miot#829]
In The integration missing e.g. control of ionizers, lights, etc.

A lot of things can be controlled according to the specification, viz. https://home.miot-spec.com/spec/zhimi.airp.mb5

Only
![obrazek](https://user-images.githubusercontent.com/57643470/194059573-a0bc1398-604b-4c14-b8f7-cfe57563b9d1.png)

vv0.7.0b0

**Comment by al-one** [comment]
Try master branch.

**Comment by leroyloren** [comment]
![obrazek](https://user-images.githubusercontent.com/57643470/195335266-4d6a0339-1976-4747-93a4-fcf073e46a1b.png)

Perfect, thx 👍

**Comment by MrHakisak** [comment]
sorry for silly question, but how do I use master branch?

**Comment by leroyloren** [comment]
Greeen button "Code" > Download ZIP > Extract ZIP

![obrazek](https://user-images.githubusercontent.com/57643470/220059364-547e2875-a57e-48b8-8221-c463d3ba1b28.png)

**Comment by MrHakisak** [comment]
> Greeen button "Code" > Download ZIP > Extract ZIP
> 
> ![obrazek](https://user-images.githubusercontent.com/57643470/220059364-547e2875-a57e-48b8-8221-c463d3ba1b28.png)

Thank you!

Unfortunately I am getting problems where the controls are not right, I think toggle mode is meant to switch between Auto, Silent, Favorite, Fan..
I have tried many Xiaomi integrations with no luck :( 
![Screenshot 2023-02-20 200413](https://user-images.githubusercontent.com/39749769/220060721-74c9e662-e93b-472d-90c1-b8782a0336cd.png)

**Comment by leroyloren** [comment]
Click on it. mode is set via the fan entity.

![image](https://user-images.githubusercontent.com/20426629/220061341-83a1b720-1bbf-4dd0-b396-7ea2b78b5c48.png)

**Comment by MrHakisak** [comment]
> Click on it. mode is set via the fan entity.
> 
> ![image](https://user-images.githubusercontent.com/20426629/220061341-83a1b720-1bbf-4dd0-b396-7ea2b78b5c48.png)

Ahhhhh! thank you!!! it works now. hahaha, thank you very much. ❤️
