### ISSUE TITLE
camera is "streaming" but i receive "Error opening stream" Xiaomi Miot For HomeAssistant v0.3.3

### ISSUE THREAD

**Issue by TheBisk** [al-one/hass-xiaomi-miot#83]
with the latest component update the camera switch is back to "on" and the status of the camera is "streaming" but unfortunately i cannot see the live stream:
**ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream https://de01.livestreaming.io.mi.com/hlstranscoder/...._H265transH264/playlist.m3u8**

model: isa.camera.hlc6
firmware_version: 4.0.5_0105
stream_status: 1
camera_control.on: true
camera_control.image_rollover: 0
camera_control.night_shot: 0
camera_control.time_watermark: true
camera_control.recording_mode: 2
state_updater: cloud
sub_entities:
  - camera_control.on

**Comment by al-one** [comment]
Please make sure that your HA host can access the stream address. Each stream address has a validity period of only 5 minutes. Please test it as soon as possible after obtaining a new stream address.
```shell
curl -I https://de01.livestreaming.io.mi.com/hlstranscoder/...._H265transH264/playlist.m3u8
```

**Comment by al-one** [comment]
https://github.com/al-one/hass-xiaomi-miot/issues/56#issuecomment-846336169
