### ISSUE TITLE
MiotNumberSubEntity

### ISSUE THREAD

**Issue by razzietheman** [al-one/hass-xiaomi-miot#830]
Logger: homeassistant.components.number
Source: components/number/__init__.py:117
Integration: Nummer (documentation, issues)
First occurred: 08:12:19 (2 occurrences)
Last logged: 08:12:19

custom_components.xiaomi_miot.number::MiotNumberSubEntity is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
custom_components.xiaomi_miot.number::MiotNumberActionSubEntity is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.

**Comment by gudvinr** [comment]
#814

**Comment by al-one** [comment]
Try beta version in releases.

**Comment by oopiicaa** [comment]
Fixes the error for me. Thanks
