### ISSUE TITLE
Unable to access Xiaomi API

### ISSUE THREAD

**Issue by wengip** [al-one/hass-xiaomi-miot#832]
Config xiaomi cloud account.
⚠️ HTTPSConnectionPool(host='account.xiaomi.com', port=443): Max retries exceeded with url: /pass/serviceLogin?sid=xiaomiio&_json=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8d564f40>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

試過重啟
試過從/etc/resolv.conf 和HASSio裡改DNS 依然出現相同錯誤

[core-ssh ~]$ nslookup api.io.mi.com
Server:         172.0.0.11
Address:        172.0.0.11#53

Non-authoritative answer:
Name:   api.io.mi.com
Address: 110.43.87.16
Name:   api.io.mi.com
Address: 2401:1d40:ff::b

[core-ssh ~]$ nslookup account.xiaomi.com
Server:         172.0.0.11
Address:        172.0.0.11#53

Non-authoritative answer:
Name:   account.xiaomi.com
Address: 220.181.106.104

曾經有一次成功登入,之後都顯示Unable to access Xiaomi API

**Comment by al-one** [comment]
有办法ssh登录宿主机然后通过`docker exec -it homeassistant`进入容器内部再测试上面的命令吗？
