### ISSUE TITLE
Could you please fix (linp.magnet.m1 领普门窗传感器) issue?

### ISSUE THREAD

**Issue by ericgtx5791** [al-one/hass-xiaomi-miot#833]
https://home.miot-spec.com/s/linp.magnet.m1
![xiaomi miot linp.magnet.m1](https://user-images.githubusercontent.com/87137120/194579193-2f709147-b53b-452f-986d-b5f2f42f0be8.jpeg)
Entity: Binary sensor will not change(always on)
But attribute:magnet_sensor.status will change.

**Comment by al-one** [comment]
请更新至master分支后再观察。
