### ISSUE TITLE
API calls every second

### ISSUE THREAD

**Issue by pduchnovsky** [al-one/hass-xiaomi-miot#835]
Is there any reason for this component to call API every second ?
![image](https://user-images.githubusercontent.com/54581833/194562582-1c818aa1-4715-4e9e-97d8-2256061c2349.png)

**Comment by al-one** [comment]
Usually a device will update it‘s state every 30~60 seconds. If you have many devices integrated through the cloud, it is possible to request Xiaomi API every second.

**Comment by pduchnovsky** [comment]
> Usually a device will update it‘s state every 30~60 seconds. If you have many devices integrated through the cloud, it is possible to request Xiaomi API every second.

Isn't it possible to do batch updates of multiple devices at once ? Or preferably request all devices via API at once and then parse them ? Or is there some limitation of the API ?
I can't imagine this is good, considering if people have tens of devices such as multiple vacuums, temperature sensors, water detection, and other smart home stuff, they would send hundreds of thousands requests towards API, I can imagine there being a limit to API calls in the future due to this ?

**Comment by al-one** [comment]
it is difficult to achieve.

**Comment by pduchnovsky** [comment]
> it is difficult to achieve.

understood, just wanted to bring this to your attention, might be that they will put limits to API calls per hour/day/month and then you'll have to do this anyway :)
