### ISSUE TITLE
cuco.plug.cp1m/cuco.plug.cp5d一直在不再可用和可用之间切换

### ISSUE THREAD

**Issue by sctale** [al-one/hass-xiaomi-miot#836]
忘记什么时候开始的了，状态一直是这样的。之前没问题的。
HASSOS10.1，8.1的时候已经这样了。
![Snipaste_2022-10-07_21-15-31](https://user-images.githubusercontent.com/18475722/194563071-e0bb88cf-0350-4d3a-804d-05e0239c5bbf.png)
实体状态如下：
state_class: measurement
entity_class: MiotSensorSubEntity
parent_entity_id: switch.cuco_cp1m_2fee_switch
service_description: Switch
property_description: Electric Current
updated_time: 2022-10-07T14:26:01.688578+08:00
switch.electric_current: 0
unit_of_measurement: mA
device_class: current
friendly_name: 洗衣机插座 Switch Electric Current
supported_features: 0

**Comment by sctale** [comment]
今天把另一个这个型号的智能插座启用了，也是这个情况。
然后看了下同品牌的那个插排，居然也是一样的。cuco.plug.cp5d
![Snipaste_2022-10-08_07-36-40](https://user-images.githubusercontent.com/18475722/194675560-a2677cdc-6079-4bf3-9b53-eb375eaa19e6.png)
实体属性如下：
effect_list: 
supported_color_modes: onoff
friendly_name: 电小酷 CP5 indicator-light
supported_features: 4
color_mode: onoff
indicator_light.on: true
indicator_light.mode: false
indicator_light.start_time: 1380
indicator_light.end_time: 420

**Comment by al-one** [comment]
请尝试通过[自定义选项](https://github.com/al-one/hass-xiaomi-miot/issues/600)排除`indicator_light`服务。

**Comment by sctale** [comment]
测试结果如下：
18:00左右进行了自定义，23:00查看状态。
cuco.plug.cp1m 无效；
cuco.plug.cp5d 暂时有效。

**Comment by al-one** [comment]
尝试master分支。

**Comment by sctale** [comment]
升级到了v0.7.0b1，更新日志有这两个的优化。
不过cuco.plug.cp1m还是一样的问题，而且现在电压和电流不显示了。
我把整个插座的实体都截图了。
![Snipaste_2022-10-10_19-08-36](https://user-images.githubusercontent.com/18475722/194852930-6d24ce43-b816-40c8-9e54-6db109c17060.png)
![开发者工具 – Home Assistant](https://user-images.githubusercontent.com/18475722/194853799-7138fbf0-be5c-4795-8b81-3f781817d351.png)

**Comment by al-one** [comment]
请尝试为cp1m添加以下[自定义选项](https://github.com/al-one/hass-xiaomi-miot/issues/600)：
```yaml
exclude_miot_services: setting,cyc,use_time,power,physical_controls_locked
exclude_miot_properties: power_consumption,voltage,electric_current
```

**Comment by sctale** [comment]
大佬，排除power项这个插座就没有意义了，主要就是靠功率判断来做一些自动化的

**Comment by al-one** [comment]
我明白，可以逐个排除尝试。

**Comment by sctale** [comment]
有可能还真是power的问题，图表居然有两个，以前我记得是一个的。
![Snipaste_2022-10-10_22-53-08](https://user-images.githubusercontent.com/18475722/194894891-2526c42e-3e7c-4266-ac27-a92795dacb91.png)

**Comment by sctale** [comment]
10/11 07:14更新：
cuco.plug.cp1m 无效；
cuco.plug.cp5d 有效。

**Comment by sctale** [comment]
10/30 13:48更新：
版本：最新版 v0.7.0
cuco.plug.cp1m 有效；
cuco.plug.cp5d 有效。
