### ISSUE TITLE
Xiaomi Smart Standing Fan Pro (dmaker.fan.p11/p15/p33) percentage level support

### ISSUE THREAD

**Issue by iquix** [al-one/hass-xiaomi-miot#838]
Xiaomi Smart Standing Fan Pro has 3 variations (dmaker.fan.p11/p15/p33)
https://www.mi.com/global/product/mi-smart-standing-fan-pro/
and they share same structures of packet.

In the miot-spec, 'property:status' is the percentage level.

https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:fan:0000A005:dmaker-p11:1
https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:fan:0000A005:dmaker-p15:1
https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:fan:0000A005:dmaker-p33:1

In these model, {"siid": 2, "piid": 6} is 'property:status', and it's applied in the rytilahti/python-miio library.
https://github.com/rytilahti/python-miio/blob/aa2718853455c40b5b8c2a1883019d8cb7a683b4/miio/integrations/fan/dmaker/fan_miot.py#L55

I hope you to modify the fan.py as below

https://github.com/al-one/hass-xiaomi-miot/blob/7efcd0d463ee6da46b6329d3a05fc2cf926af56a/custom_components/xiaomi_miot/fan.py#L113

(-) for p in s.get_properties('speed_level', 'wind_speed', 'fan_level'):
(+) for p in s.get_properties('speed_level', 'wind_speed', 'status', 'fan_level'):

Thank you so much.

**Comment by al-one** [comment]
Try master.

**Comment by iquix** [comment]
It works well with my p11 fan. Thank you so much!
