### ISSUE TITLE
Xiaomi Smart Plug (chuangmi.plug.212a01) need siid

### ISSUE THREAD

**Issue by a1ekseev** [al-one/hass-xiaomi-miot#84]
After plugging the socket into HASS, errors are logged:

`[custom_components.xiaomi_miot] Got MiioException while fetching the state for Power Plug Switch: {'code': -32602, 'message': 'need siid'}`

It works through the cloud, I wanted it to work locally...

siid's can be found here - https://github.com/rytilahti/python-miio/issues/844

**Comment by al-one** [comment]
Maybe you can try to add [custom attributes](https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui):
```yaml
# customize.yaml
switch.your_entity_id:
  chunk_properties: 7
```
> [⚙️ Configuration](https://my.home-assistant.io/redirect/config) > 🖌 Customize > 🔍 Select Entity > Add Other Attribute

**Comment by al-one** [comment]
The device can query 10 attributes at a time in LAN. This component defaults to 12, and the device has 14 properties. Therefore, you need to add a custom attribute `chunk_properties` to be used normally.
