### ISSUE TITLE
dreame.vacuum.p2114a set_miot_property "only vacuum" or "mop and vacuum" -704040003: “property not found”

### ISSUE THREAD

**Issue by DediCATeD88** [al-one/hass-xiaomi-miot#841]
Trying to set the mopping settings "only vacuum" or "mop and vacuum" via ha script.

Used MiHome Mod by vevsvevs to extract 

{"id":4584,"method":"set_properties","params":[{"did":"10340xxx2","siid":4,"piid":23,"value":136194}]}
{"id":4585,"method":"set_properties","params":[{"did":"103xxx902","siid":4,"piid":23,"value":136192}]}

Script:
```yaml
service: xiaomi_miot.set_miot_property
data:
  entity_id: vacuum.robi
  siid: 4
  piid: 23
  value: 136192
```
Result
(dreame.vacuum.p2114a): Set miot property {'did': '103xxxx2', 'siid': 4, 'piid': 23, 'value': 136192} failed, result: {'did': '103xxxxx02', 'siid': 4, 'piid': 23, 'code': -704040003, 'exe_time': 0}

-> -704040003: “property not found”

https://home.miot-spec.com/spec?type=urn%3Amiot-spec-v2%3Adevice%3Avacuum%3A0000A006%3Adreame-p2114a%3A2

So the result states property not found but the MiHome sets this property and the miot-spec lists this property.

Tried

  miot_cloud: true        # Enable miot cloud for entity (read, write, action)
  miot_cloud_write: true  # Enable miot cloud (only write)
  miot_cloud_action: true # Enable miot cloud (only action)

with no change.

I'am missing something here?

**Comment by al-one** [comment]
![dreame.vacuum.p2114a](https://user-images.githubusercontent.com/4549099/195030746-592d087d-3ce2-468c-b396-8371269fb0d8.png)
`urn:miot-spec-v2:device:vacuum:0000A006:dreame-p2114a:2` is debug, must be released to operate in the cloud.
Tip: Integrate it via token.

**Comment by DediCATeD88** [comment]
Thank you. Local integration via Token did the trick. Good to know that the cloud version status needs to be released to operate.
