### ISSUE TITLE
Xiaomi Leshow Fan Auto Turn off By Itself

### ISSUE THREAD

**Issue by swiftydroid** [al-one/hass-xiaomi-miot#843]
Hi,

I have a Xiaomi leshow fan that is integrated with Home Assistant and is set up to be controlled by Miot. However, it seems to turned off by itself each time I turn it on (please see the video).

Fan Model: Xiaomi Leshow
Home Assistant Version: 2022.10.3
Miot Version: 0.6.13

https://user-images.githubusercontent.com/54492695/195378156-6e3cf0b9-5cba-4fed-9f4c-7cfd303507c2.mov

**Comment by al-one** [comment]
Debug logs required.
