### ISSUE TITLE
isa.magnet.dw2hl sensor is missing in the device list

### ISSUE THREAD

**Issue by bithajcsar** [al-one/hass-xiaomi-miot#847]
Door/Window sensor isa.magnet.dw2hl does not show up in the device list.
Firmware of the device is the latest.

**Comment by al-one** [comment]
![xiaomi miot options](https://user-images.githubusercontent.com/4549099/196135522-4f905e1e-a6c2-4c53-92d6-1679c56df826.png)

**Comment by bithajcsar** [comment]
I tried it already...
How long it could take to recognize the device after such configuration?

**Comment by bithajcsar** [comment]
Configured as you advised. Device is still not seen in HA.

**Comment by al-one** [comment]
Show me your filters.

**Comment by bithajcsar** [comment]
Sorry...
I gave up suffering with that integration. The device is now handled by the "Xiaomi Gateway 3" integration.
