### ISSUE TITLE
Constantly unavailable szkj.vacuum.mjfc01

### ISSUE THREAD

**Issue by lasry1** [al-one/hass-xiaomi-miot#852]
Hi there,

I have issues recently with my [szkj.vacuum.mjfc01](https://home.miot-spec.com/s/szkj.vacuum.mjfc01) and the MIOT integration. The vacuum is unavailable every few seconds being unable to control it with automations.

This has became an issue since 8th October before it was working well. I'm not sure if an update of the integration has caused this. 

This vacuum doesn't seem to work through local connection.

<img width="1154" alt="Screenshot 2022-10-24 at 14 46 25" src="https://user-images.githubusercontent.com/44910611/197541552-444f5e25-d7cc-4428-bef2-6554aef05223.png">

Any ideas??
Thanks

**Comment by al-one** [comment]
These configurations can be added and it will try to get the device state from the cloud if it is not available in local.
```yaml
xiaomi_miot:
  device_customizes:
    szkj.vacuum.mjfc01:
      auto_cloud: true
```
