### ISSUE TITLE
Gosund cp1m (cp1md?)电流电压显示

### ISSUE THREAD

**Issue by Jianhong-Han** [al-one/hass-xiaomi-miot#853]
大佬你好，我在 https://home.miot-spec.com/s/plug 页面查询到Gosund 的CP1AM有如下两个：
![image](https://user-images.githubusercontent.com/51055116/197542759-7d7beef9-deb2-493d-92f1-e4ac327c89ea.png)
我在Home Assistant里看见的是cp1md，这个cp1md型号不在miot_local_devices.py，也就是目前无法用本地模式？请问后续有无可能适配为本地模式？
而且目前无法显示cp1md的电流电压（云端模式），还请大佬支持一下。
感谢大佬开发出这么好用的插件。

**Comment by al-one** [comment]
https://home.miot-spec.com/spec/cuco.plug.cp1md
尝试master分支。

**Comment by SeanChengN** [comment]
@Jianhong-Han 你的可以显示电流电压功耗了吗？我用master分支也不行

**Comment by SeanChengN** [comment]
![chrome_l7HdWG2k16](https://user-images.githubusercontent.com/20624068/200315695-529a0f1d-994a-4f44-b223-31c2a0a95ddd.jpg)
