### ISSUE TITLE
Minij.washer.v8 unavailable help

### ISSUE THREAD

**Issue by aotuyet82** [al-one/hass-xiaomi-miot#855]
[minij.washer.v8](https://home.miot-spec.com/s/minij.washer.v8) unavailable
the washer always get "Became unavailable" error many times in a day. But it reconnect very soon. Help

**Comment by al-one** [comment]
[Logs](https://my.home-assistant.io/redirect/logs)

**Comment by aotuyet82** [comment]
This error originated from a custom integration.

Logger: custom_components.xiaomi_miot.core.xiaomi_cloud
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:63
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 11:53:13 AM (1 occurrences)
Last logged: 11:53:13 AM

Request xiaomi api: miotspec/prop/get {'params': [{'did': '106290809', 'siid': 2, 'piid': 1}, {'did': '106290809', 'siid': 2, 'piid': 2}, {'did': '106290809', 'siid': 2, 'piid': 3}, {'did': '106290809', 'siid': 2, 'piid': 4}, {'did': '106290809', 'siid': 2, 'piid': 5}, {'did': '106290809', 'siid': 2, 'piid': 6}, {'did': '106290809', 'siid': 2, 'piid': 7}, {'did': '106290809', 'siid': 2, 'piid': 8}, {'did': '106290809', 'siid': 2, 'piid': 9}, {'did': '106290809', 'siid': 4, 'piid': 1}, {'did': '106290809', 'siid': 3, 'piid': 1}]} failed, response: None

**Comment by aotuyet82** [comment]
This error originated from a custom integration.

Logger: custom_components.xiaomi_miot.core.xiaomi_cloud
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:63
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 12:06:15 PM (1 occurrences)
Last logged: 12:06:15 PM

Request xiaomi api: miotspec/prop/get {'params': [{'did': '106290809', 'siid': 2, 'piid': 1}, {'did': '106290809', 'siid': 2, 'piid': 2}, {'did': '106290809', 'siid': 2, 'piid': 3}, {'did': '106290809', 'siid': 2, 'piid': 4}, {'did': '106290809', 'siid': 2, 'piid': 5}, {'did': '106290809', 'siid': 2, 'piid': 6}, {'did': '106290809', 'siid': 2, 'piid': 7}, {'did': '106290809', 'siid': 2, 'piid': 8}, {'did': '106290809', 'siid': 2, 'piid': 9}, {'did': '106290809', 'siid': 4, 'piid': 1}, {'did': '106290809', 'siid': 3, 'piid': 1}]} failed, response: None

This error originated from a custom integration.

Logger: custom_components.xiaomi_miot.core.xiaomi_cloud
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:204
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 12:06:10 PM (2 occurrences)
Last logged: 12:07:38 PM

Request xiaomi api: v2/message/v2/typelist {} failed, response: None

**Comment by aotuyet82** [comment]
This error originated from a custom integration.

Logger: custom_components.xiaomi_miot.core.xiaomi_cloud
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:63
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: October 26, 2022 at 12:20:12 PM (144 occurrences)
Last logged: 11:21:02 AM

Request xiaomi api: miotspec/prop/get {'params': [{'did': '106290809', 'siid': 2, 'piid': 1}, {'did': '106290809', 'siid': 2, 'piid': 2}, {'did': '106290809', 'siid': 2, 'piid': 3}, {'did': '106290809', 'siid': 2, 'piid': 4}, {'did': '106290809', 'siid': 2, 'piid': 5}, {'did': '106290809', 'siid': 2, 'piid': 6}, {'did': '106290809', 'siid': 2, 'piid': 7}, {'did': '106290809', 'siid': 2, 'piid': 8}, {'did': '106290809', 'siid': 2, 'piid': 9}, {'did': '106290809', 'siid': 4, 'piid': 1}, {'did': '106290809', 'siid': 3, 'piid': 1}]} failed, response: None
