### ISSUE TITLE
不知道怎么回事，经常导致CPU占用100%

### ISSUE THREAD

**Issue by gujiangjiang** [al-one/hass-xiaomi-miot#858]
<img width="360" alt="image" src="https://user-images.githubusercontent.com/13273955/198860779-bce25e97-4dec-4e34-adfb-53cc8d5c7d0b.png">

J3455ITX 16G内存 实体群晖

单独开启HASS+HACS没问题，装上hass-xiaomi-miot也没问题，但是登陆账号同步设备之后短期内没问题，一般过一段时间后就会出现群晖CPU占用100%卡死的情况，整个群晖卡死，我已经反复重装HASS好多次，也反复重装hass-xiaomi-miot好多次，均出现这个情况，难道是我设备太多？我右83个设备也不算多吧，总是100%的CPU导致群晖卡死真的完全没法使用，还导致群晖上的其他服务全部瘫痪。

整个HASS只用了hass-xiaomi-miot并没有其余任何插件。

[DOCKER日志.zip](https://github.com/al-one/hass-xiaomi-miot/files/9894998/DOCKER.zip)

**Comment by gujiangjiang** [comment]
会不会是内存分配太小导致的？我限制hass的内存为256M？麻烦大佬看一下log，谢谢

**Comment by gujiangjiang** [comment]
我先测试一下，我把内存和CPU限制关闭，再测试几天，有问题再open

**Comment by al-one** [comment]
`[2022-10-30 01:27:46.569 WARNING (Recorder) [homeassistant.components.recorder.util]  The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
[15:35:01] INFO: [Home Assistant Core finish process received signal 9
[15:35:01] INFO: [Home Assistant Core finish process exit code 256
`

你的HA似乎一直在自动重启，请尝试删除HA数据库文件`/config/home-assistant_v2.db`

**Comment by gujiangjiang** [comment]
@al-one 
我看了一下，我的设备全都是DHCP自动分配IP的，重启进去看了一下有几个吸顶灯离线了，IP变了，但是hass没有自动更新这个变化，我又重新登陆了一下auto，但是依然显示离线，搞不清，不知道是不是这个原因导致的反复重启，还有，目前的auto不支持自动更新设备的IP嘛

**Comment by al-one** [comment]
暂不支持自动更新设备IP，需要你在集成选项勾线`更新设备列表`并报错。
