### ISSUE TITLE
无法添加子擎人在传感器

### ISSUE THREAD

**Issue by keniji** [al-one/hass-xiaomi-miot#859]
微信群没看到有人讨论这个，所以来问问…

尝试通过插件添加子擎人体传感器，添加完成之后插件只获取到一个传感器实体（Sensor），看样子似乎是米家的消息中心：
![image](https://user-images.githubusercontent.com/42759206/198910424-62ea5d38-7ce6-4d36-8645-1c6daba85118.png)
我在实际使用环境和测试环境中试过了是一样的情况（截图是测试环境）：
![image](https://user-images.githubusercontent.com/42759206/198911138-d60c0cf2-a103-4b3e-8233-925b2502180c.png)
![image](https://user-images.githubusercontent.com/42759206/198910741-68428f40-0f6d-4484-a042-f78072dd376b.png)
另如上图因为没有生成设备，这个实体也无法被删除，通过实体注册表也不行（已在插件中移除设备，也尝试过重启HA）：
![image](https://user-images.githubusercontent.com/42759206/198911754-0dda1bfc-dd23-4f2e-9bfe-42263311767e.png)
我尝试仿照 #165 把实体重命名为“删除”或者“delete”，均无法删除实体（我想也应该是），请问还有其他方法可以删除吗？感谢！

**Comment by al-one** [comment]
请更新至master分支。

**Comment by keniji** [comment]
> 请更新至master分支。

一针见血 💯 
删实体的我就再想想吧, 不行的话全删了重新加 🤣

**Comment by JimmyRespawn** [comment]
的确加了不显示，也没显示到HK下。应该是还没适配吧

**Comment by JimmyRespawn** [comment]
> @JimmyRespawn 请确认你已经成功升级插件至最新版本v0.7.1。

@al-one 谢谢回复，更新后的确出现6个实体了。HK好像还没集成显示，期待之后集成
