### ISSUE TITLE
I have a Couple of questions

### ISSUE THREAD

**Issue by Golab** [al-one/hass-xiaomi-miot#86]
Hello I have some question

1: I have a
Mi 360° Home Security Camera 2K Pro
MODEL:    chuangmi.camera.021a04
EU model

When I have it setup to EU server everything thing works ok but when I have it setup to China mainland server it doesn’t work I can sometimes get a status update like it’s recording but I can’t get stream to work but when I use xiaomi own iOS  app Mi Home then everything in the app works like streaming and uploade recordings to xiaomi own cloud, so what can be the problem?

And Can you explain to me what
 
2: What is Filter WiFi SSID
3: What is WiFi SSID List
4: And what does Empty do?
5: And way dos Empty show a number?

you should update your readme file so it explains this

**Comment by al-one** [comment]
> 1:  Mi 360° Home Security Camera 2K Pro

This component connects Mi Home devices such as cameras to HA through miot-spec. It does not directly access Mi Cloud like Mi Home APP, so not all data can be obtained. In addition, the streaming service of some camera models supported by miot-spec often cannot access the streaming address.

> 2: What is Filter WiFi SSID
> 3: What is WiFi SSID List

If you have many devices in multiple places (homes) under the same Mi account, filtering Wifi SSID/BSSID can only integrate part of the devices into HA. You need to choose whether to include or exclude the list you checked.

> 4: And what does Empty do?
> 5: And way dos Empty show a number?

include all = exclude empty (integrate all devices)
exclude all = include empty (don't integrate any devices)
