### ISSUE TITLE
Gsound CP5 PRO新型号添加每日以及每月电量统计

### ISSUE THREAD

**Issue by Loyido** [al-one/hass-xiaomi-miot#860]
Gsound CP5 PRO似乎有了新的型号

cuco.plug.cp5prd - 此为新型号，接入HA后，未显示每日及每月电量统计
![image](https://user-images.githubusercontent.com/80599145/199000064-8146e157-81ae-41f1-ae6c-99e968f512ca.png)

cuco.plug.cp5pro - 此为旧型号，接入HA后有每日及每月电量统计
![image](https://user-images.githubusercontent.com/80599145/199000327-91eb501d-15ed-4c01-b5bb-8c594553766b.png)

**Comment by al-one** [comment]
尝试master分支。
