### ISSUE TITLE
希望增加通过家庭名筛选设备的功能

### ISSUE THREAD

**Issue by JimmyKmi** [al-one/hass-xiaomi-miot#862]
在家庭和设备都非常多的情况下，不同房子会有相同的房间名字，如卫生间。
如果能在添加设备时通过房间筛选能够更方便选择设备，蓝牙设备无法通过wifi筛选

**Comment by al-one** [comment]
最新的提交已支持根据家庭筛选设备，请更新至master分支后尝试。
由于某些限制，目前仅支持家庭所有者账号筛选，共享家庭的子账号不支持筛选共享家庭。

> 另外，蓝牙设备可以通过排除wifi/bssid的方式筛选。
