### ISSUE TITLE
MILAB EC2

### ISSUE THREAD

**Issue by tv4you2016** [al-one/hass-xiaomi-miot#866]
hello I put the latest version of Xiaomi Mi Auto.
I add my device (IMILAB EC2 Wireless Camera Gateway) that appears to me but then I don't have an entity, How can I get the Video??

![image](https://user-images.githubusercontent.com/83761813/199788676-f7ab1459-40ee-4c19-a773-2687cf803786.png)

![image](https://user-images.githubusercontent.com/83761813/199788579-553395c8-0d4d-43e0-b594-b2f5d63f763d.png)

![image](https://user-images.githubusercontent.com/83761813/199788876-8fcb954d-c0a5-4455-9882-dfa2897efaac.png)

**Comment by al-one** [comment]
https://home.miot-spec.com/spec/chuangmi.gateway.ipc011

Cannot be supported because it does not define any specifications.

**Comment by dimadusk** [comment]
Would be nice to have support for these cameras
