### ISSUE TITLE
linp.remote.k9b01(Linptech BLE Switch Sensor K11) is not yet supported

### ISSUE THREAD

**Issue by diametrical** [al-one/hass-xiaomi-miot#871]
Linptech BLE Switch Sensor K11 is not yet supported by miot but it is supported by xiaomi gateway3 now.

Please refer to here https://github.com/AlexxIT/XiaomiGateway3/issues/826
& 
https://github.com/AlexxIT/XiaomiGateway3/pull/844/commits/6978fd9a74fc20793472b1c509b3a4a093e4b912#diff-835ac6f8ac13bc923627410597ac01dd1dfbce8d7a9d9db066bbed538e0a218f

**Comment by al-one** [comment]
This component cannot support wireless switch sensors because it obtains the device status by polling and cannot listen key events in real time.
