### ISSUE TITLE
通过账号集成的青萍空气检测仪（cgllc.airmonitor.s1）最近频繁不可用

### ISSUE THREAD

**Issue by wingkuen** [al-one/hass-xiaomi-miot#874]
大神好，通过账号集成的青萍空气检测仪（cgllc.airmonitor.s1）最近频繁不可用，日志如下：

此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.sensor
Source: custom_components/xiaomi_miot/__init__.py:1358 
Integration: Xiaomi Miot Auto (documentation, issues) 
First occurred: 09:53:16 (17 occurrences) 
Last logged: 10:02:11

空气检测仪(cgllc.airmonitor.s1): Got MiioException while fetching the state: Unable to discover the device 192.168.31.60, mapping: {'environment.relative_humidity': {'siid': 2, 'piid': 1}, 'environment.pm2_5_density': {'siid': 2, 'piid': 2}, 'environment.temperature': {'siid': 2, 'piid': 3}, 'environment.co2_density': {'siid': 2, 'piid': 4}, 'environment.tvoc_density': {'siid': 2, 'piid': 5}, 'battery_level': {'siid': 3, 'piid': 1}, 'battery.charging_state': {'siid': 3, 'piid': 2}}, max_properties: 10/7

**Comment by wingkuen** [comment]
以及连接xiaomi api的问题，如下：

此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.core.xiaomi_cloud
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:204
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 2022年11月17日 15:53:47 (2 occurrences)
Last logged: 15:53:55

Request xiaomi api: https://userprofile.mina.mi.com/device_profile/v2/conversation {'hardware': 'LX06', 'timestamp': 1668671627001, 'limit': 3} failed, response: <!doctype html><html lang="en"><head><title>HTTP Status 401 – Unauthorized</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 401 – Unauthorized</h1></body></html>
Request xiaomi api: https://userprofile.mina.mi.com/device_profile/v2/conversation {'hardware': 'LX06', 'timestamp': 1668758035002, 'limit': 3} failed, response: <!doctype html><html lang="en"><head><title>HTTP Status 401 – Unauthorized</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 401 – Unauthorized</h1></body></html>

**Comment by al-one** [comment]
> 空气检测仪(cgllc.airmonitor.s1): Got MiioException while fetching the state: Unable to discover the device 192.168.31.60

如果设备IP没有问题，请确认插件是最新版本。


> HTTP Status 401 – Unauthorized

尝试在集成选项中重新登录你的小米账号。
