### ISSUE TITLE
升级0.71后，云米衣架ich110升到顶部时，状态反了

### ISSUE THREAD

**Issue by zhongyongming1** [al-one/hass-xiaomi-miot#876]
升级0.71后，中间位置的问题解决了，但是云米衣架ich110状态反了，本来衣架到顶后，应该是闭锁上升键，现在成了闭锁下降键[捂脸]
![13CE9930-99F0-43A4-AC8D-D356837D02D1](https://user-images.githubusercontent.com/103315468/201507497-3947bba4-927c-4ed8-9180-693f5acbfb73.jpeg)

**Comment by al-one** [comment]
请更新master分支后尝试。
