### ISSUE TITLE
Xiaomi Mesh AX3000 (xiaomi.router.ra82 ) added, but no stats

### ISSUE THREAD

**Issue by joddye2** [al-one/hass-xiaomi-miot#878]
Hi!

I have a Xiaomi Mesh AX3000 (xiaomi.router.ra82).
Added via auto discovery.

Token generating not works so I think it only supports cloud.

The obtainable parameters fewer than the specs (https://home.miot-spec.com/spec/xiaomi.router.ra82).
All cached parameters are "not available".

Anyone using this router?
Anyone successfully use it?

HA: 2022.11.2
Miio integration: latest

**Comment by al-one** [comment]
As far as I know, most of the Xiaomi routers cannot be integrated locally, and in the cloud mode, the correct attribute value cannot be obtained.

**Comment by joddye2** [comment]
Yes, correct.
Changed the connection mode to automatic, and still the same.

**Comment by joddye2** [comment]
> As far as I know, most of the Xiaomi routers cannot be integrated locally, and in the cloud mode, the correct attribute value cannot be obtained.

Yes, correct.
Changed the connection mode to automatic, and still the same.

**Comment by al-one** [comment]
Can't fix because can't get correct state from cloud and device.
