### ISSUE TITLE
WX08ZM mosquito repellent

### ISSUE THREAD

**Issue by alexreddy78** [al-one/hass-xiaomi-miot#88]
Got following error in Home assistant after trying to switch on/off Mosquito repellent:
Logger: custom_components.xiaomi_miot_raw
Source: custom_components/xiaomi_miot_raw/__init__.py:502
Integration: Xiaomi MIoT (documentation, issues)
First occurred: 19:48:55 (8 occurrences)
Last logged: 20:09:39

Control Отпугиватель насекомых by cloud failed: [{'did': 'blt.3.16mdrp93sec00', 'siid': 4, 'piid': 1, 'code': -704030023}]

Integration of repellent was successful but controlling via cloud failed...
Any solutions to control it via MI Home account on cloud basis only Or device will work only with Xiaomi Gateway?

THX in advance

**Comment by al-one** [comment]
Not this component !

Goto https://github.com/ha0y/xiaomi_miot_raw
