### ISSUE TITLE
小米三键零火开关，转无线后无法识别单击

### ISSUE THREAD

**Issue by frishcat** [al-one/hass-xiaomi-miot#881]
1. 接入方式：小米三键零火开关 -> 米家中枢网关 -> hass-xiaomi-miot - > hass

2. 开关在米家中转成了无线开关

3. hass 里面，只能拿到三个键分别的 on / off 状态（继电器），没有单击的状态

求大神支持，可以让 home assistant 拿到转无线开关后到点击状态🙏

**Comment by jay1943000** [comment]
弄个继电器在米家里面关联一下开关, 然后在HA里面监控继电器的开关

**Comment by andyboyce** [comment]
全屋都想转无线，不然小爱有时候乱动开关。

**Comment by frishcat** [comment]
> 全屋都想转无线，不然小爱有时候乱动开关。

已经通过 Zigbee2MQTT 解决这个问题了
