### ISSUE TITLE
Can not discover MC1808

### ISSUE THREAD

**Issue by Zwaubel** [al-one/hass-xiaomi-miot#882]
Hey,
I'm trying to discover my Xiaomi Mijia 1C vacuum mop (MC1808). 
Unfortunately, after the initial setup, the robot is not discovered. In fact I only get a list containing my Mi Bedsidelamp 2. 
Also, there are no exceptions or warnings in the log. 
My Robot is on firmware 4.3.3 and is in the same subnet as my HA. 
I am new to the project and might be missing something. 
Can anybody give me a hint as to how to proceed?

Thanks!

**Comment by al-one** [comment]
Show me your integration options, how to filter these devices ?

**Comment by Zwaubel** [comment]
Here are Dome Screenshots:
![image](https://user-images.githubusercontent.com/25179994/202137323-6e6ad1ef-242a-4639-81f7-a0a80d3aad2f.png)
![image](https://user-images.githubusercontent.com/25179994/202137351-0c7550f1-db17-4b4b-96b7-dd4422e9cfb1.jpeg)

**Comment by al-one** [comment]
Please try selecting a different server location.

**Comment by Zwaubel** [comment]
Tried all options with no success. Only the European server provides a device as shown above. All others contain nothing.

**Comment by al-one** [comment]
Are you sure you only have this Xiaomi account ?

**Comment by Zwaubel** [comment]
Yes, I use the same credentials from within Xiaomi Home to control the vacuum.

**Comment by al-one** [comment]
Try to delete the folder `.storage/xiaomi_miot` under the HA configuration directory.
