### ISSUE TITLE
yeelink.light.ceiling4 no rgb ambilight support

### ISSUE THREAD

**Issue by orsgah** [al-one/hass-xiaomi-miot#884]
[yeelink.light.ceiling4](https://home.miot-spec.com/s/yeelink.light.ceiling4) no rgb ambilight support, only CCT and brightness

model: YLXD02YL 
Yeelight Ceiling Light (Jiaoyue 650)

**Comment by orsgah** [comment]
Update to v0.7.2, still no rgb settings

**Comment by al-one** [comment]
Show the [entity attributes](https://my.home-assistant.io/redirect/developer_states).

**Comment by al-one** [comment]
This entity looks like intergraded via `hass-miio-yeelink`, not this component.

**Comment by orsgah** [comment]
![image](https://user-images.githubusercontent.com/9882503/205858572-d5d32777-9c52-4a92-990b-1a35523a3b43.png)
