### ISSUE TITLE
配置错误，提示参数错误

### ISSUE THREAD

**Issue by peecabooom** [al-one/hass-xiaomi-miot#885]
homeassistant.util.file.WriteError: [Errno 22] Invalid argument: '/config/.storage/xiaomi_miot/tmp9liw50wb' -> '/config/.storage/xiaomi_miot/urn:miot-spec-v2:device:outlet:0000A002:cuco-v3:1.json'

**Comment by al-one** [comment]
Windows系统安装的HA吗？

**Comment by echochenyueyang** [comment]
> Windows系统安装的HA吗？

我也遇到同样的问题了，不是win，是docker的HA

**Comment by al-one** [comment]
请提供详细的日志。并列出`ls -1 /config/.storage/xiaomi_miot/`文件加下的文件列表。
