### ISSUE TITLE
Integrate miot-local for yunmi.waterpuri.lx7

### ISSUE THREAD

**Issue by dinde** [al-one/hass-xiaomi-miot#890]
Hello,

Is it possible to integrate https://home.miot-spec.com/spec/yunmi.waterpuri.lx7 with miot-local ?
Here is the output when I add the device to Home Assistant with ip/token:
Model
yunmi.waterpuri.lx7
Lan IP
192.168.x.y
MAC address
[deleted]
Entity class
MiotSensorEntity
Miot type
urn:miot-spec-v2:device:water-purifier:0000A013:yunmi-lx7:1
State property
water_purifier.temperature
Water purifier.temperature.error
-4004 Other internal errors
Filter-5.filter used time.error
-4004 Other internal errors
Filter-5.filter used flow.error
-4004 Other internal errors
Filter.filter used time.error
-4004 Other internal errors
Filter.filter used flow.error
-4004 Other internal errors
Tds sensor.tds in.error
-4004 Other internal errors
Tds sensor.tds out.error
-4004 Other internal errors
State updater
lan

thanks !

**Comment by al-one** [comment]
It is not a miot device, I will adapt it to local integration through `miio2miot` in future versions.

**Comment by dinde** [comment]
Thank you !
If you need tests, do not hesitate to hit me.

**Comment by al-one** [comment]
Try master branch.

**Comment by dinde** [comment]
Hello,

Checked out latest branch and I've been able to add it without warning.
But it only pulls water temp and remains in state unknown
Attributes below:
Model
yunmi.waterpuri.lx7
Lan IP
[private]
MAC address
[private]
Entity class
MiotSensorEntity
Miot type
urn:miot-spec-v2:device:water-purifier:0000A013:yunmi-lx7:1
State property
water_purifier.temperature
Water purifier.temperature.error
-4004 Other internal errors
Filter-5.filter used time.error
-4004 Other internal errors
Filter-5.filter used flow.error
-4004 Other internal errors
Filter.filter used time.error
-4004 Other internal errors
Filter.filter used flow.error
-4004 Other internal errors
Tds sensor.tds in.error
-4004 Other internal errors
Tds sensor.tds out.error
-4004 Other internal errors
State updater
lan

**Comment by al-one** [comment]
You failed to update to the master branch.

**Comment by al-one** [comment]
> Is TDS IN missing or not available on the device ?

Show me the latest [entity attributes](https://my.home-assistant.io/redirect/developer_states).

**Comment by dinde** [comment]
sensor.yunmi_lx7_5a4b_filter_used_flow
Purificateur d'Eau Composite Filter Service Used Flow
170	state_class: total_increasing
entity_class: MiotSensorSubEntity
parent_entity_id: sensor.yunmi_lx7_5a4b_water_purifier
service_description: Composite Filter Service
property_description: Filter Used Flow
updated_time: 2022-12-08T04:05:28.975213+01:00
filter.filter_used_flow: 170
icon: mdi:water-percent
friendly_name: Purificateur d'Eau Composite Filter Service Used Flow
supported_features: 0
sensor.yunmi_lx7_5a4b_filter_used_flow_2
Purificateur d'Eau RO Filter Service Used Flow
170	state_class: total_increasing
entity_class: MiotSensorSubEntity
parent_entity_id: sensor.yunmi_lx7_5a4b_water_purifier
service_description: RO Filter Service
property_description: Filter Used Flow
updated_time: 2022-12-08T04:05:28.975614+01:00
filter-5.filter_used_flow: 170
icon: mdi:water-percent
friendly_name: Purificateur d'Eau RO Filter Service Used Flow
supported_features: 0
sensor.yunmi_lx7_5a4b_filter_used_time
Purificateur d'Eau Composite Filter Service Used Time
3156	entity_class: MiotSensorSubEntity
parent_entity_id: sensor.yunmi_lx7_5a4b_water_purifier
service_description: Composite Filter Service
property_description: Filter Used Time
updated_time: 2022-12-08T08:33:00.246242+01:00
filter.filter_used_time: 3156
unit_of_measurement: hours
icon: mdi:clock
friendly_name: Purificateur d'Eau Composite Filter Service Used Time
supported_features: 0
sensor.yunmi_lx7_5a4b_filter_used_time_2
Purificateur d'Eau RO Filter Service Used Time
3156	entity_class: MiotSensorSubEntity
parent_entity_id: sensor.yunmi_lx7_5a4b_water_purifier
service_description: RO Filter Service
property_description: Filter Used Time
updated_time: 2022-12-08T08:32:30.246777+01:00
filter-5.filter_used_time: 3156
unit_of_measurement: hours
icon: mdi:clock
friendly_name: Purificateur d'Eau RO Filter Service Used Time
supported_features: 0
sensor.yunmi_lx7_5a4b_total_dissolved_solids_for_output_water
Purificateur d'Eau Total Dissolved Solids Sensor for Output Water
193	state_class: measurement
entity_class: MiotSensorSubEntity
parent_entity_id: sensor.yunmi_lx7_5a4b_water_purifier
service_description: Total Dissolved Solids Sensor
property_description: Total Dissolved Solids for Output Water
updated_time: 2022-12-09T02:49:01.831978+01:00
tds_sensor.tds_out: 193
unit_of_measurement: ppm
icon: mdi:water-check
friendly_name: Purificateur d'Eau Total Dissolved Solids Sensor for Output Water
supported_features: 0
sensor.yunmi_lx7_5a4b_water_purifier
Purificateur d'Eau Water Purifier Temperature
19.0	model: yunmi.waterpuri.lx7
lan_ip: 192.168.y.z
mac_address: [removed]
entity_class: MiotSensorEntity
miot_type: urn:miot-spec-v2:device:water-purifier:0000A013:yunmi-lx7:1
state_property: water_purifier.temperature
run_status: 0
f1_totalflow: 7200
f2_totalflow: 7200
water_purifier.temperature: 19
water_purifier.rinse: 0
water_purifier.light_mode: false
water_purifier.tds_warn_thd: 100
filter-5.filter_used_time: 3156
filter-5.filter_used_flow: 170
filter.filter_used_time: 3156
filter.filter_used_flow: 170
tds_sensor.tds_out: 193
state_updater: lan
sub_entities: filter-4.filter_used_time-1, filter-4.filter_used_flow-2, filter-5.filter_used_time-1, filter-5.filter_used_flow-2, tds_sensor-3.tds_out-2
unit_of_measurement: °C
device_class: temperature
friendly_name: Purificateur d'Eau Water Purifier Temperature
supported_features: 0

**Comment by al-one** [comment]
Try master branch again.

**Comment by dinde** [comment]
Tested latest master and TDS IN populated immediately.
Thank you

**Comment by dinde** [comment]
It seems that TDS IN value stays on 80 in my end.
No variation at all since 24h.

**Comment by al-one** [comment]
Is there any change in MiHome APP ?

**Comment by dinde** [comment]
Mi Home only reports TDS OUT by design.

**Comment by al-one** [comment]
The `TDS IN` of some models of Yunmi water purifiers is hard-coded in the device firmware, not the real value. These values are all from the device, you can verify the data through the following [service command](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.send_command), if they have not changed, I can't do anything.
```yaml
service: xiaomi_miot.send_command
data:
  entity_id: sensor.yunmi_lx7_5a4b_water_purifier
  method: get_prop
  params: [tds_in,tds_out]
  throw: true
```

**Comment by dinde** [comment]
Miio command result
[100, 'error']

Now

**Comment by liuan1990** [comment]
> The `TDS IN` of some models of Yunmi water purifiers is hard-coded in the device firmware, not the real value. These values are all from the device, you can verify the data through the following [service command](https://my.home-assistant.io/redirect/developer_call_service/?service=xiaomi_miot.send_command), if they have not changed, I can't do anything.
> 
> ```yaml
> service: xiaomi_miot.send_command
> data:
>   entity_id: sensor.yunmi_lx7_5a4b_water_purifier
>   method: get_prop
>   params: [tds_in,tds_out]
>   throw: true
> ```

Miio command result
[80, 'error']

**Comment by dinde** [comment]
![image](https://user-images.githubusercontent.com/5851544/208268946-ca39c1d6-95f3-48b0-82a9-a57efa4ada1e.png)
Peak is due to a power outage.
For some reasons, value switched from 80 to 100 now for TDS IN.
