### ISSUE TITLE
fan.zhimi_mb3_a66f_air_purifier controls from lan

### ISSUE THREAD

**Issue by dinde** [al-one/hass-xiaomi-miot#893]
Hello,

I tried to control my [Mi Air Purifier 3H from HA](https://home.miot-spec.com/s/zhimi.airpurifier.mb3).
I can't turn it on or off neither change any settings from HA.
e.g: I try to switch the backlight of screen to off which is done by turning brightness to 0/1/2 but it does not change.

Also, my sensors are not updated often. I've set it to 30s ip/token which is the default setting.
My temperature is not updated since 15h.
Is there something I'm missing here ?

Thanks !

**Comment by al-one** [comment]
Show the [entity attributes](https://my.home-assistant.io/redirect/developer_states).

**Comment by dinde** [comment]
I tried to reset the Air Purifier and reboot HA, controls started to work as expected !

Temperature sensor seems to do not update for some reasons (last update was 30mn ago)
Attributs
Entity class MiotSensorSubEntity
Parent entity ID fan.zhimi_mb3_a66f_air_purifier
Service description Environment
Property description Temperature
Updated time 23 novembre 2022 à 04:32:07
Environment.temperature 19,8

Entities attributes below:
<html>
<body>


fan.zhimi_mb3_a66f_air_purifierXMAP3H Air Purifier | off | preset_modes: Auto, Sleep, Favorite, None percentage: null percentage_step: 33 preset_mode: Auto model: zhimi.airpurifier.mb3 lan_ip: [filtered] mac_address: [filtered] entity_class: MiotFanEntity exclude_miot_services: button, filter_time, rfid, others exclude_miot_properties: average_aqi_cnt, aqi_zone, sensor_state, aqi_goodh, aqi_runstate, aqi_state, motor_strong, motor_high, motor_med, motor_med_l, motor_low, motor_silent, motor_favorite, motor_set_speed miot_type: urn:miot-spec-v2:device:air-purifier:0000A007:zhimi-mb3:2 air_purifier.fault: 0 air_purifier.on: false air_purifier.fan_level: 1 air_purifier.mode: 0 aqi.purify_volume: 206227 aqi.average_aqi: 23 aqi.aqi_updata_heartbeat: 0 use_time: 7417200 motor_speed: 0 motor_speed.favorite_fan_level: 2 physical_controls_locked: false indicator_light.brightness: 1 indicator_light.on: true alarm: false filter.filter_life_level: 38 filter.filter_used_time: 2140 environment.pm2_5_density: 16 environment.relative_humidity: 47 environment.temperature: 19.799999 state_updater: lan sub_entities: motor_speed-10.motor_speed-8, air_purifier-2.on-2, motor_speed-10.favorite_fan_level-10, environment-3.pm2_5_density-6, environment-3.relative_humidity-7, environment-3.temperature-8, filter-4.filter_life_level-3, filter-4.filter_used_time-5, physical_controls_locked-7.physical_controls_locked-1, indicator_light-6 friendly_name: XMAP3H Air Purifier supported_features: 9
-- | -- | --
light.zhimi_mb3_a66f_indicator_lightXMAP3H Indicator Light | on | supported_color_modes: brightness, onoff color_mode: brightness brightness: 3 indicator_light.brightness: 1 indicator_light.on: true friendly_name: XMAP3H Indicator Light supported_features: 1
number.zhimi_mb3_a66f_favorite_fan_levelXMAP3H motor-speed favorite-fan-level | 2 | min: 0 max: 14 step: 1 mode: auto entity_class: MiotNumberSubEntity parent_entity_id: fan.zhimi_mb3_a66f_air_purifier service_description: motor-speed property_description: favorite-fan-level motor_speed.favorite_fan_level: 2 friendly_name: XMAP3H motor-speed favorite-fan-level supported_features: 0
sensor.zhimi_mb3_a66f_filter_life_levelXMAP3H Filter Life Level | 38 | entity_class: MiotSensorSubEntity parent_entity_id: fan.zhimi_mb3_a66f_air_purifier service_description: Filter property_description: Filter Life Level updated_time: 2022-11-23T04:32:07.963365+01:00 filter.filter_life_level: 38 unit_of_measurement: % icon: mdi:percent friendly_name: XMAP3H Filter Life Level supported_features: 0
sensor.zhimi_mb3_a66f_filter_used_timeXMAP3H Filter Used Time | 2140 | entity_class: MiotSensorSubEntity parent_entity_id: fan.zhimi_mb3_a66f_air_purifier service_description: Filter property_description: Filter Used Time updated_time: 2022-11-23T04:32:07.967504+01:00 filter.filter_used_time: 2140 unit_of_measurement: hours icon: mdi:clock friendly_name: XMAP3H Filter Used Time supported_features: 0
sensor.zhimi_mb3_a66f_motor_speedXMAP3H motor-speed | 0 | entity_class: MiotSensorSubEntity parent_entity_id: fan.zhimi_mb3_a66f_air_purifier service_description: motor-speed property_description: motor-speed updated_time: 2022-11-23T04:34:08.299548+01:00 motor_speed: 0 friendly_name: XMAP3H motor-speed supported_features: 0
sensor.zhimi_mb3_a66f_pm25XMAP3H Environment PM2.5 | 16 | entity_class: MiotSensorSubEntity parent_entity_id: fan.zhimi_mb3_a66f_air_purifier service_description: Environment property_description: PM2.5 updated_time: 2022-11-23T04:33:32.558595+01:00 environment.pm2_5_density: 16 unit_of_measurement: µg/m³ icon: mdi:air-filter friendly_name: XMAP3H Environment PM2.5 supported_features: 0
sensor.zhimi_mb3_a66f_relative_humidityXMAP3H Environment Relative Humidity | 47.0 | entity_class: MiotSensorSubEntity parent_entity_id: fan.zhimi_mb3_a66f_air_purifier service_description: Environment property_description: Relative Humidity updated_time: 2022-11-23T04:36:07.980035+01:00 environment.relative_humidity: 47 unit_of_measurement: % device_class: humidity friendly_name: XMAP3H Environment Relative Humidity supported_features: 0
sensor.zhimi_mb3_a66f_temperatureXMAP3H Environment Temperature | 19.8 | entity_class: MiotSensorSubEntity parent_entity_id: fan.zhimi_mb3_a66f_air_purifier service_description: Environment property_description: Temperature updated_time: 2022-11-23T04:32:07.959061+01:00 environment.temperature: 19.799999 unit_of_measurement: °C device_class: temperature friendly_name: XMAP3H Environment Temperature supported_features: 0
switch.zhimi_mb3_a66f_physical_control_lockedXMAP3H Physical Control Locked | off | entity_class: MiotSwitchSubEntity parent_entity_id: fan.zhimi_mb3_a66f_air_purifier service_description: Physical Control Locked property_description: Physical Control Locked physical_controls_locked: false friendly_name: XMAP3H Physical Control Locked supported_features: 0
switch.zhimi_mb3_a66f_switch_statusXMAP3H Air Purifier Switch Status | off | entity_class: MiotSwitchSubEntity parent_entity_id: fan.zhimi_mb3_a66f_air_purifier service_description: Air Purifier property_description: Switch Status air_purifier.on: false icon: mdi:power friendly_name: XMAP3H Air Purifier Switch Status supported_features: 0


</body>
</html>

**Comment by al-one** [comment]
Are there any [logs](https://my.home-assistant.io/redirect/logs) generated after you control it in HA ?

**Comment by dinde** [comment]
As I said, control is working since I reseted everything.
Temperature sensor fetching is not working correctly.
It updates at some random frequency which is usualy dozen of hours between 2 updates.
Thanks.

**Comment by al-one** [comment]
Temperature & humidity is from device. You can see if they are updated from the debug logs.

**Comment by dinde** [comment]
That's right. I got the updates every 30s (as specified on integration configuration) but the value of temperature remain the same.
I don't know why it does not update at all for hours and suddenly update then no more !
Is there a way to trigger a temperature update of the air purifier ?

Maybe there is a strange implementation from Xiaomi team.
Usualy when you get sensors (temperature/aqi/humidity) it's supposed to update live (or at least almost live).
![image](https://user-images.githubusercontent.com/5851544/203874468-bf54ffef-4b15-43fb-94f5-68e6555bd34c.png)

AQI seems to update way more often though.
![image](https://user-images.githubusercontent.com/5851544/203874440-3f4608b5-2cbd-4057-aa4f-8e550198c367.png)

If anybody got inputs, it would be appreciated. (I seen some issues on HA forums but nobody seems to know). :(

**Comment by dinde** [comment]
Hello,

There is still a missing entity to control the fan mode.
The following attribute is missing: Air purifier.mode 
* 0 = Automatic
* 1 = Night (Silent)
* 2 = Manual (which use motor-speed favorite-fan-level) or Manual used with air_purifier.fan_level: (1/2/3)

Thanks.

**Comment by al-one** [comment]
It is controlled by the preset mode of the fan entity (popup card).

**Comment by dinde** [comment]
Ok found it. It is a bit counter intuitive. Still thank you for pointing this.
