### ISSUE TITLE
Thermostat Heatcold cubee.airrtc.th123e  - Failed to call the service climate/set_hvac_mode

### ISSUE THREAD

**Issue by theodorx7** [al-one/hass-xiaomi-miot#894]
Home Assistant v2022.11.4
Xiaomi Miot Auto v0.7.1
[cubee.airrtc.th123e](https://home.miot-spec.com/s/cubee.airrtc.th123e) firmware v2.2.1.1006

**When switching the thermostat modes or presets, an error message is displayed:**

.
![Screenshot_20221122-100633](https://user-images.githubusercontent.com/99128059/203532179-3ca3db3d-bdea-45c4-a5bd-982f8185e172.png)

**Comment by theodorx7** [comment]
Home Assistant v2022.11.4
Xiaomi Miot Auto v0.7.1
cubee.airrtc.th123e firmware v2.2.1.1006

**Comment by theodorx7** [comment]
Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.xiaomi_miot.core.xiaomi_cloud
Source: custom_components/xiaomi_miot/core/xiaomi_cloud.py:63
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 21:05:49 (1 occurrences)
Last logged: 21:05:49

Request xiaomi api: miotspec/prop/get {'params': [{'did': '437002191', 'siid': 2, 'piid': 1}, {'did': '437002191', 'siid': 2, 'piid': 2}, {'did': '437002191', 'siid': 2, 'piid': 3}, {'did': '437002191', 'siid': 2, 'piid': 4}, {'did': '437002191', 'siid': 2, 'piid': 5}, {'did': '437002191', 'siid': 2, 'piid': 7}, {'did': '437002191', 'siid': 4, 'piid': 1}, {'did': '437002191', 'siid': 4, 'piid': 2}, {'did': '437002191', 'siid': 4, 'piid': 3}, {'did': '437002191', 'siid': 4, 'piid': 4}, {'did': '437002191', 'siid': 4, 'piid': 5}, {'did': '437002191', 'siid': 4, 'piid': 6}, {'did': '437002191', 'siid': 4, 'piid': 7}]} failed, response: None

**Comment by theodorx7** [comment]
2022-11-23 07:00:45.207 ERROR (MainThread) [custom_components.xiaomi_miot_raw.climate] Modes {'Manual': 0, 'Home': 1, 'Away': 2, 'Smart': 3, 'Sleep': 4} contains unsupported ones. Please report this message to the developer.

**Comment by theodorx7** [comment]
Perhaps the information from this topic will be useful: 
https://github.com/ha0y/xiaomi_miot_raw/issues/287

**Comment by scarycky** [comment]
Привет, подскажи пожалуйста, как ты сделал, чтобы отразить информацию с термостата?? я просмотрел 2 инструкции но так и не понял что необходимо сделать, спасибо

**Comment by al-one** [comment]
Try this configuration:
```yaml
# configuration.yaml
xiaomi_miot:
  device_customizes:
    cubee.airrtc.th123e:
      miot_local: true
      chunk_properties: 1
      exclude_miot_services: heatold
```

**Comment by scarycky** [comment]
> Try this configuration:
> ```yaml
> # configuration.yaml
> xiaomi_miot:
>   device_customizes:
>     cubee.airrtc.th123e:
>       miot_local: true
>       chunk_properties: 1
>       exclude_miot_services: heatold
> ```

Thank you very much, everything worked

**Comment by al-one** [comment]
Try master branch without configurations.

**Comment by al-one** [comment]
- #940
