### ISSUE TITLE
用户已经被封禁

### ISSUE THREAD

**Issue by EC11112** [al-one/hass-xiaomi-miot#895]
配置小米账户
⚠️ Login to xiaomi error: &&&START&&&{"qs":"%3Fsid%3Dxiaomiio%26_json%3Dtrue","code":350008,"description":"用户已经被封禁","securityStatus":0,"_sign":"0psXfr43eNI0IX6q9Suk3qWbRqU=","sid":"xiaomiio","result":"error","captchaUrl":null,"callback":"https://sts.api.io.mi.com/sts","location":"","pwd":0,"child":0,"desc":"用户已经被封禁"}

**Comment by al-one** [comment]
已在[v0.7.12](https://github.com/al-one/hass-xiaomi-miot/releases/latest)版本中修复！

**Comment by EC11112** [comment]
> 已在[v0.7.12](https://github.com/al-one/hass-xiaomi-miot/releases/latest)版本中修复！

令人敬佩的速度

**Comment by caoyaochong** [comment]
令人敬佩的速度 +1

**Comment by GU0FORY1** [comment]
令人敬佩的速度 +1
