### ISSUE TITLE
净水器缺少“温度”选项

### ISSUE THREAD

**Issue by arthurfsy** [al-one/hass-xiaomi-miot#898]
型号：yunmi.waterpuri.s20
该型号净水器已成功接入HA，在HA的water_purifier这个实体里也发现又属性temperature，但是没有单独的“temperature”实体，请问可以新增“温度”这个实体吗？

https://home.miot-spec.com/spec/yunmi.waterpuri.s20
![image](https://user-images.githubusercontent.com/68410058/203937554-e5b52be8-8909-4017-9c59-78417958f71b.png)

**Comment by al-one** [comment]
尝试master分支。

**Comment by arthurfsy** [comment]
已解决！感谢感谢
![image](https://user-images.githubusercontent.com/68410058/206141110-b781ce9b-0086-4112-bcae-07ef12d9f48b.png)
