### ISSUE TITLE
原来接入没问题的净水器，更新后无法接入获取不到实体了

### ISSUE THREAD

**Issue by aktifin** [al-one/hass-xiaomi-miot#9]
Logger: homeassistant.components.sensor
Source: custom_components/xiaomi_miot/sensor.py:101
Integration: 传感器 (documentation, issues)
First occurred: 下午11:20:25 (2 occurrences)
Last logged: 下午11:20:25

Error adding entities for domain sensor with platform xiaomi_miot
Error while setting up xiaomi_miot platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 424, in _async_add_entity
    device_class=entity.device_class,
  File "/config/custom_components/xiaomi_miot/sensor.py", line 101, in device_class
    if self._prop_state.name in ['temperature']:
AttributeError: 'NoneType' object has no attribute 'name'

设备号：yunmi.waterpuri.lx9

**Comment by al-one** [comment]
下载[master](https://github.com/al-one/hass-xiaomi-miot)分支最新代码试下

**Comment by aktifin** [comment]
更新后，能取得一个实体（之前是10个实体，包括tds、温度以及各个滤芯的流量和时间等），但是没有数据

Platform xiaomi_miot does not generate unique IDs. ID 04:cf:8c:xx already exists - ignoring sensor.jing_shui_qi_ro_filter_service


Model
yunmi.waterpuri.lx9
Lan ip
192.168.xx.xx
Mac address
04:CF:8C:xx
Firmware version
2.1.3
Hardware version
esp8266
Entity class
MiotSensorEntity
Water purifier.temperature
-
Tds sensor.tds in
-
Tds sensor.tds out
-
Filter.filter used time
-
Filter.filter used flow
-

**Comment by al-one** [comment]
下载[master](https://github.com/al-one/hass-xiaomi-miot)分支最新代码试下

**Comment by aktifin** [comment]
获取到5个实体，但是实体没有数据
切换回0.12版本，就恢复正常了
![image](https://user-images.githubusercontent.com/29476277/106245264-28b3bc80-6247-11eb-98ef-40ad65689534.png)

**Comment by aktifin** [comment]
这个是master的
![image](https://user-images.githubusercontent.com/29476277/106246108-8ac0f180-6248-11eb-8f36-884d2b9f6c6d.png)

**Comment by al-one** [comment]
事实上v0.1.2版本是基于旧版miio协议实现对云米净水器的支持，你的设备需要开启miot-cloud才可以使用miot协议读写数据。
不过现在我已经将型号`yunmi.waterpuri.lx9`添加到强制使用旧版miio协议的列表。更新master分支即可正常使用。

**Comment by aktifin** [comment]
> 事实上v0.1.2版本是基于旧版miio协议实现对云米净水器的支持，你的设备需要开启miot-cloud才可以使用miot协议读写数据。
> 不过现在我已经将型号`yunmi.waterpuri.lx9`添加到强制使用旧版miio协议的列表。更新master分支即可正常使用。

嗯嗯，我看到9999错误也觉得是得通过cloud接入了

**Comment by aktifin** [comment]
成功修复
![image](https://user-images.githubusercontent.com/29476277/106247668-d07eb980-624a-11eb-8b8f-d2369ab70ac1.png)

**Comment by yhwl8888** [comment]
> 成功修复
> ![图片](https://user-images.githubusercontent.com/29476277/106247668-d07eb980-624a-11eb-8b8f-d2369ab70ac1.png)

这个是云米那个型号净水器

**Comment by al-one** [comment]
> > 成功修复
> > ![图片](https://user-images.githubusercontent.com/29476277/106247668-d07eb980-624a-11eb-8b8f-d2369ab70ac1.png)
> 
> 这个是云米那个型号净水器

Model: yunmi.waterpuri.lx9
