### ISSUE TITLE
Is my rice cooker supported?

### ISSUE THREAD

**Issue by Golab** [al-one/hass-xiaomi-miot#90]
Hello I’m wondering if my rice cooker is supported?

chunmi.cooker.normal2
Firmware: 1.3.9

**Comment by al-one** [comment]
The model [chunmi.cooker.normal2](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:cooker:0000A00B:chunmi-normal2:1) is supported.
But it may only support the cloud mode, you can integrate it through xiaomi account.
