### ISSUE TITLE
小米电视 source_list 是否可以指定仅显示某些输入源，以及为其设置别名

### ISSUE THREAD

**Issue by axelburks** [al-one/hass-xiaomi-miot#904]
小米电视 source_list 是否可以指定仅显示某些输入源，比如不显示 ATV、DTV、AV，仅显示 HDMI123
以及为其设置别名，比如 HDMI1 设置为 AppleTV之类的

**Comment by al-one** [comment]
请问你的电视具体型号是多少？

不支持扩展指定的属于源，如果想设置别名，可以尝试通过配置[`translations`](https://github.com/al-one/hass-xiaomi-miot/issues/100#issuecomment-874613054)

**Comment by axelburks** [comment]
xiaomi.tv.rmh1，不是扩展增加新的输入源，是类似黑白名单的机制
比如，source_list 全集是 ATV, DTV, AV, HDMI 1, HDMI 2, HDMI 3，我想配置只显示 HDMI 1, HDMI 2, HDMI 3

translations 我看是针对设备类型进行翻译，我只想翻译这一台设备的可以吗，因为不同的设备的输入源的别名想设置不同的

**Comment by axelburks** [comment]
非常感谢，但是尝试后未生效，是需要删除重新添加设备吗

**Comment by al-one** [comment]
请确保`customize.yaml`被包含在`configuration.yaml`中的`homeassistant:`节点下（参考：https://github.com/al-one/hass-xiaomi-miot/issues/100#custom ）。
`customize.yaml`中的自定义生效后，会出现在属性中，正确配置后还需重载自定义及插件或重启HA。

**Comment by al-one** [comment]
抱歉，我想起来了。`extend_miot_specs`选项比较特殊，无法在`customize.yaml`中配置，目前仅支持在`configuration.yaml`中配置。

**Comment by axelburks** [comment]
好的，感谢，尝试了下是有效的，但直接改机型的配置的话不适合我，那我先不改了，但还是谢谢
