### ISSUE TITLE
关于小米电饭煲的设置

### ISSUE THREAD

**Issue by googooog** [al-one/hass-xiaomi-miot#91]
电饭煲 Cooker实体中开关一直是开启的状态。

实际电饭煲是没有插电源的状态。

**Comment by googooog** [comment]
还有飞利浦灯泡，在关电的情况下，也是一直显示开启的状态。

**Comment by al-one** [comment]
如果是开启了云端模式或者通过账号接入的设备，小米云端会缓存断电前的数据。
你可以通过自定义属性检查设备在局域网环境是否可用：
> [⚙️ 配置](https://my.home-assistant.io/redirect/config) > 🖌 自定义 > 🔍 选择实体 > 选择要覆盖的属性 > 添加Other属性
```yaml
# customize.yaml
sensor.cooker_entity_id:
  check_lan​: ​true
```
