### ISSUE TITLE
没挂代理登录不了小米账号

### ISSUE THREAD

**Issue by 0521jin** [al-one/hass-xiaomi-miot#917]
### Device model

登录不了小米账号

### Integrated mode

Automatic (自动模式)

### The problem

n5105 虚拟的  主路由ikuai dns已改223.5.5.5  homeassitant 网关指向ikuai dns已改223.5.5.5

Home Assistant URL:
http://homeassistant.local:8123
Observer URL:
http://homeassistant.local:4357
[core-ssh ~]s nslookup api.io.mi.com
127.0.0.11
Server:
Address:
127.0.0.11#53
Non-authoritative answer:
Name：
api.io.mi.com
Address:111.13.213.29
Names
api.io.mi.com
Address:39.156.44.8
Name：
api.io.mi.com
Address:39.156.81.118
[core-ssh ~]$ curl -v https://api.io.mi.com
Trying111.13.213.29:443..
connect to 111.13.213.29 port 443 failed:Operation timed out
Trying 39.156.44.8:443...
* After 85548ms connect time， move on!
connect to 39.156.44.8 port 443 failed: Operation timed out
Trying 39.156.81.118:443..
*After 42773ms connect time move onl
* connect to 39.156.81.118 port 443 failed: Operation timed out
* Failed to connect to api.io.mi.com port 443 after 257228 ms: Operation timed out
* Closirg connection 3
curl:（28） Failed to connect
257228
Operation
timed out

### Entity attributes

```yaml
11
```

### Home Assistant Logs

此错误来自自定义集成。

Logger: custom_components.xiaomi_miot.config_flow
Source: custom_components/xiaomi_miot/config_flow.py:303
Integration: xiaomi_miot (documentation, issues)
First occurred: 13:43:59 (2 occurrences)
Last logged: 22:24:43

Setup xiaomi cloud for user: 13804909908 failed: HTTPSConnectionPool(host='account.xiaomi.com', port=443): Max retries exceeded with url: /pass/serviceLogin?sid=xiaomiio&_json=true (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd296814820>, 'Connection to account.xiaomi.com timed out. (connect timeout=None)'))
Setup xiaomi cloud for user: 13804909908 failed: HTTPSConnectionPool(host='account.xiaomi.com', port=443): Max retries exceeded with url: /pass/serviceLogin?sid=xiaomiio&_json=true (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd2979051b0>, 'Connection to account.xiaomi.com timed out. (connect timeout=None)'))

**Comment by 0521jin** [comment]
ip冲突 ha里dhcp自动获取就好了

**Comment by lbhbrave** [comment]
能介绍下具体的解决思路吗，我也遇到了
