### ISSUE TITLE
能适配支持Gosund电小酷16A智能插座吗

### ISSUE THREAD

**Issue by ppttu** [al-one/hass-xiaomi-miot#919]
### Device model

[cuco.plug.cp2d](https://home.miot-spec.com/s/cuco.plug.cp2d)

### Component version

1.4.3

### HA core version

2022.11.2

### Integrated mode

Automatic (自动模式)

### The problem

Gosund电小酷智能插座wifi语音控制手机APP远程控制定时开关16A记电量热水器插座无线定时智能插座接入小爱
https://item.jd.com/100020583222.html

请问能对这个设备进行适配吗？  我看到已经在适配列表里，但hass中显示实体状态为不可用。
16a的智能插座是大功率电器必备  市面上兼容米家的16a插座也不多，而一些红外控制的设备是无法通过遥控判断开关机状态的：即开机与关机是同一个遥控按键。这个时候通过插座功率来判断设备运行状态将是一个很好的方式。

还请作者帮忙适配一下：可以控制插座开关、可以读取到功率数据，如有需要 我可以寄一个测试用的智能插座给你

### Entity attributes

```yaml
evice_class: outlet
friendly_name: 智能插座-次卫洗手台 Switch
supported_features: 0
```

### Home Assistant Logs

2022-12-05 11:02:33.131 ERROR (MainThread) [custom_components.xiaomi_miot.switch] 智能插座-厨房空调(cuco.plug.cp2d): Got MiioException while fetching the state: Unable to parse message payload, mapping: {'switch.on': {'siid': 2, 'piid': 1}, 'other_setting.overheat_alarm': {'siid': 6, 'piid': 1},

**Comment by al-one** [comment]
请在米家重新绑定该设备后再试。

**Comment by ppttu** [comment]
好的，   感谢回复    下午我回去试试

**Comment by ppttu** [comment]
仍旧一样，一共三个同款设备  都是一样的表现形式

Logger: custom_components.xiaomi_miot.switch
Source: custom_components/xiaomi_miot/__init__.py:1360 
Integration: Xiaomi Miot Auto ([documentation](https://github.com/al-one/hass-xiaomi-miot), [issues](https://github.com/al-one/hass-xiaomi-miot/issues)) 
First occurred: 11:02:33 (3642 occurrences) 
Last logged: 18:49:42

智能插座-公卫洗手台(cuco.plug.cp2d): Got MiioException while fetching the state: No response from the device, mapping: {'switch.on': {'siid': 2, 'piid': 1}, 'other_setting.overheat_alarm': {'siid': 6, 'piid': 1}, 'other_setting.temperature': {'siid': 6, 'piid': 2}, 'other_setting.overload_alarm': {'siid': 6, 'piid': 3}, 'physical_controls_locked': {'siid': 5, 'piid': 1}, 'indicator_light.on': {'siid': 4, 'piid': 1}, 'power_consumption': {'siid': 3, 'piid': 1}, 'electric_current-3-2': {'siid': 3, 'piid': 2}, 'power_consumption.voltage': {'siid': 3, 'piid': 3}, 'electric_power-3-4': {'siid': 3, 'piid': 4}}, max_properties: 10/10
智能插座-主卫洗手台(cuco.plug.cp2d): Got MiioException while fetching the state: Unable to parse message payload, mapping: {'switch.on': {'siid': 2, 'piid': 1}, 'other_setting.overheat_alarm': {'siid': 6, 'piid': 1}, 'other_setting.temperature': {'siid': 6, 'piid': 2}, 'other_setting.overload_alarm': {'siid': 6, 'piid': 3}, 'physical_controls_locked': {'siid': 5, 'piid': 1}, 'indicator_light.on': {'siid': 4, 'piid': 1}, 'power_consumption': {'siid': 3, 'piid': 1}, 'electric_current-3-2': {'siid': 3, 'piid': 2}, 'power_consumption.voltage': {'siid': 3, 'piid': 3}, 'electric_power-3-4': {'siid': 3, 'piid': 4}}, max_properties: 10/10
智能插座-厨房空调(cuco.plug.cp2d): Got MiioException while fetching the state: Unable to parse message payload, mapping: {'switch.on': {'siid': 2, 'piid': 1}, 'other_setting.overheat_alarm': {'siid': 6, 'piid': 1}, 'other_setting.temperature': {'siid': 6, 'piid': 2}, 'other_setting.overload_alarm': {'siid': 6, 'piid': 3}, 'physical_controls_locked': {'siid': 5, 'piid': 1}, 'indicator_light.on': {'siid': 4, 'piid': 1}, 'power_consumption': {'siid': 3, 'piid': 1}, 'electric_current-3-2': {'siid': 3, 'piid': 2}, 'power_consumption.voltage': {'siid': 3, 'piid': 3}, 'electric_power-3-4': {'siid': 3, 'piid': 4}}, max_properties: 10/10
智能插座-次卫洗手台(cuco.plug.cp2d): Got MiioException while fetching the state: Unable to parse message payload, mapping: {'switch.on': {'siid': 2, 'piid': 1}, 'other_setting.overheat_alarm': {'siid': 6, 'piid': 1}, 'other_setting.temperature': {'siid': 6, 'piid': 2}, 'other_setting.overload_alarm': {'siid': 6, 'piid': 3}, 'physical_controls_locked': {'siid': 5, 'piid': 1}, 'indicator_light.on': {'siid': 4, 'piid': 1}, 'power_consumption': {'siid': 3, 'piid': 1}, 'electric_current-3-2': {'siid': 3, 'piid': 2}, 'power_consumption.voltage': {'siid': 3, 'piid': 3}, 'electric_power-3-4': {'siid': 3, 'piid': 4}}, max_properties: 10/10
智能插座-公卫洗手台2(cuco.plug.cp2d): Got MiioException while fetching the state: Unable to parse message payload, mapping: {'switch.on': {'siid': 2, 'piid': 1}, 'other_setting.overheat_alarm': {'siid': 6, 'piid': 1}, 'other_setting.temperature': {'siid': 6, 'piid': 2}, 'other_setting.overload_alarm': {'siid': 6, 'piid': 3}, 'physical_controls_locked': {'siid': 5, 'piid': 1}, 'indicator_light.on': {'siid': 4, 'piid': 1}, 'power_consumption': {'siid': 3, 'piid': 1}, 'electric_current-3-2': {'siid': 3, 'piid': 2}, 'power_consumption.voltage': {'siid': 3, 'piid': 3}, 'electric_power-3-4': {'siid': 3, 'piid': 4}}, max_properties: 10/10

**Comment by home110120** [comment]
草民附议 这个设备只有一个switch实体 看不到功率等等 switch也不可使用

**Comment by a490077** [comment]
附议。

**Comment by al-one** [comment]
更新master分支后重试。

**Comment by a490077** [comment]
更新master后目前可以正常显示功率及开关状态,  但用电统计的单日电量和本月电量一直为0,  且功率实体在传感器列表不显示

**Comment by al-one** [comment]
提供[实体属性](https://my.home-assistant.io/redirect/developer_states)

**Comment by a490077** [comment]
### 月电量:
state_class: total_increasing
entity_class: BaseSensorSubEntity
parent_entity_id: switch.cuco_cp2d_19ba_switch
updated_time: '2022-12-08T08:51:02.151670+08:00'
power_cost_month: 0
unit_of_measurement: kWh
device_class: energy
friendly_name: 热水器 Switch power_cost_month
supported_features: 0

### 日电量:
state_class: total_increasing
entity_class: BaseSensorSubEntity
parent_entity_id: switch.cuco_cp2d_19ba_switch
updated_time: '2022-12-08T08:51:02.151126+08:00'
power_cost_today: 0
unit_of_measurement: kWh
device_class: energy
friendly_name: 热水器 Switch power_cost_today
supported_features: 0

### 功率:
entity_class: MiotSensorSubEntity
parent_entity_id: switch.cuco_cp2d_19ba_switch
service_description: Power Consumption
property_description: Electric Power
updated_time: '2022-12-08T12:52:32.114705+08:00'
electric_power-3-4: 0
unit_of_measurement: watt
device_class: power
friendly_name: 热水器 Power Consumption Electric
supported_features: 0

**Comment by al-one** [comment]
再试更新master分支。

**Comment by a490077** [comment]
感谢!   已可以正常显示,  但是数值比app少了一个0, 应该是换算错了
app显示10.44度电  ha才1.044度

**Comment by al-one** [comment]
已修复。

**Comment by al-one** [comment]
@ppttu 感谢支持，你们的Star就是我最大的动力了。
