### ISSUE TITLE
小米无线开关（蓝牙版）集成更新设备列表可见，但添加后无实体

### ISSUE THREAD

**Issue by nas835270** [al-one/hass-xiaomi-miot#920]
### Device model / 设备型号

小米无线开关（蓝牙版），产品型号：XMWXKG01LM

### Component version / 插件版本

 0.7.2

### HA core version / HA版本

2022.8.7

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

小米无线开关（蓝牙版）集成更新设备列表可见，但添加后无实体

### Entity attributes / 实体属性

无实体

**Comment by al-one** [comment]
不支持无线开关。
