### ISSUE TITLE
Xiaomi Smart Pet Fountain only show 3 entities. Not all are shown, for example no water sensor, and others

### ISSUE THREAD

**Issue by quinzico** [al-one/hass-xiaomi-miot#921]
### Device model / 设备型号

[mmgg.pet_waterer.wi11](https://home.miot-spec.com/s/mmgg.pet_waterer.wi11)

### Component version / 插件版本

0.7.2

### HA core version / HA版本

2022.11.5

### Integrated mode / 集成方式

Token

### The problem / 问题详情

I have a Xiaomi pet fountain, which was integrated with HA with Xiaomi Miio Auto. I've checked that i only have 3 entities associated:

![imagem](https://user-images.githubusercontent.com/57102800/205902521-da71f490-ea06-448a-900e-c93549eb850b.png)

But from:

https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:pet-drinking-fountain:0000A067:mmgg-wi11:1

There are a lot of entities that are not mapped. One of them is very important - "no-water-flag", which should tell us that we need to add more water.

Is it possible to add these entities?

### Entity attributes / 实体属性

Missing entities:

- no-water-flag
- Filter
- Filter-cotton
- remain-clean-time
- reset-device
- timezone

Information on https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:pet-drinking-fountain:0000A067:mmgg-wi11:1

**Comment by quinzico** [comment]
Thanks @al-one,

I just checked that it is mapped as attributes:

![image](https://user-images.githubusercontent.com/57102800/205929431-573353a6-105e-481c-97ec-1fc667a86e0f.png)

In this way i can create an automation to know when there is no water.

**Comment by al-one** [comment]
Try master branch.
