### ISSUE TITLE
nwt.derh.312en becomes unavailable when running

### ISSUE THREAD

**Issue by reindl** [al-one/hass-xiaomi-miot#922]
### Device model / 设备型号

[nwt.derh.312en](https://home.miot-spec.com/s/nwt.derh.312en)

### Component version / 插件版本

0.7.2

### HA core version / HA版本

2022.11.5

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

The dehumidifier becomes unavailable whenever it is running. There are no problems when it is off or full.

### Entity attributes / 实体属性

unavailable

### Home Assistant Logs / 系统日志

ERROR (MainThread) [custom_components.xiaomi_miot.humidifier] NEW WIDETECH Internet Dehumidifier 12L(nwt.derh.312en): Got MiioException while fetching the state: Unable to parse message payload, mapping: {'dehumidifier.on': {'siid': 2, 'piid': 1}, 'dehumidifier.fault': {'siid': 2, 'piid': 2}, 'dehumidifier.mode': {'siid': 2, 'piid': 3}, 'dehumidifier.target_humidity': {'siid': 2, 'piid': 5}, 'dehumidifier.fan_level': {'siid': 2, 'piid': 7}, 'timer_service.timer': {'siid': 8, 'piid': 1}, 'timer_service.timer_setting': {'siid': 8, 'piid': 2}, 'event_service.coil_temp': {'siid': 7, 'piid': 1}, 'event_service.compressor_status': {'siid': 7, 'piid': 2}, 'event_service.water_tank_status': {'siid': 7, 'piid': 3}, 'event_service.defrost_status': {'siid': 7, 'piid': 4}, 'physical_controls_locked': {'siid': 6, 'piid': 1}, 'indicator_light.on': {'siid': 5, 'piid': 1}, 'alarm': {'siid': 4, 'piid': 1}, 'environment.relative_humidity': {'siid': 3, 'piid': 1}, 'environment.temperature': {'siid': 3, 'piid': 7}}, max_properties: 8/16

**Comment by al-one** [comment]
Try re-bind it in MiHome APP.

**Comment by reindl** [comment]
> Try re-bind it in MiHome APP.

That helped al little:
When turning on the dehumidifier via HA it becomes unavailabe ~10 seconds later but sometimes becomes available for a short while. The error message stays the same.
