### ISSUE TITLE
请求添加Aqara无线开关D1、小米无线开关（小圆饼）、绿米魔方支持

### ISSUE THREAD

**Issue by PerryLayne** [al-one/hass-xiaomi-miot#931]
### Device model / 设备型号

lumi.remote.b286acn02  &  lumi.sensor_cube.aqgl01 &  lumi.sensor_switch.v2

### Component version / 插件版本

0.7.2

### HA core version / HA版本

2022.12.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

使用小米帐号添加设备时，在添加设备（筛选设备）中可以看到：Aqara无线开关D1、小米无线开关（小圆饼）、绿米魔方，但是无论通过什么方式都无法添加设备。个人感觉是未得到支持
以上三款均作为无线开关都是实现智能家居功能操作的第一步的设备，是不可或缺的一环。希望能给与支持，十分感谢

### Entity attributes / 实体属性

无法添加看不到

**Comment by al-one** [comment]
本插件通过轮询的方式从设备或者云端获取设备状态，因此无法实时监听无线开关的按键事件。
建议使用多模网关+`XiaomiGateway3`接入。

- https://github.com/al-one/hass-xiaomi-miot/issues/927#issuecomment-1342994999
