### ISSUE TITLE
色温调整支持 米家LED筒灯 蓝牙mesh版 yeelink.light.light3

### ISSUE THREAD

**Issue by home110120** [al-one/hass-xiaomi-miot#932]
### Device model / 设备型号

yeelink.light.light3

### Component version / 插件版本

0.7.2

### HA core version / HA版本

2022.12.1

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

设备在米家APP中可以调整开关和色温 但在HA中只能调整开关 请求支持色温调整

### Entity attributes / 实体属性

min_color_temp_kelvin: 2702
max_color_temp_kelvin: 6493
min_mireds: 154
max_mireds: 370
supported_color_modes: brightness, color_temp, onoff
model: yeelink.light.light3
lan_ip: 
mac_address: CC:B5:D1:99:83:18
entity_class: MiotLightEntity
home_room: XXX
miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-light3:1:0000C802
light.on: false
light.brightness: 65535
light.color_temperature: 4553
yeelight_scene.bright_scene.error: -704030013 Property is not readable
yeelight_scene.ct_scene.error: -704030013 Property is not readable
yeelight_scene.delay_off: 0
yeelight_scene.color_scene.error: -704030013 Property is not readable
yeelight_scene.smart_switch: 0
yeelight_scene.toggle.error: -704030013 Property is not readable
yeelight_scene.bright_adjust.error: -704030013 Property is not readable
yeelight_scene.ct_adjust.error: -704030013 Property is not readable
yeelight_scene.delay_scene.error: -704030013 Property is not readable
yeelight_scene.powerup_setting: 256
state_updater: cloud
friendly_name: 卧室筒灯右 light
supported_features: 35

**Comment by al-one** [comment]
色温、亮度需要点开灯实体弹出卡片并打开灯后才可以调节。
