### ISSUE TITLE
Wi-Fi doesn't work

### ISSUE THREAD

**Issue by ppechenegg** [al-one/hass-xiaomi-miot#934]
### Device model / 设备型号

mijia smart pet feeder

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

Bought an automatic feeder. Wi-Fi does not work when trying to reset. I disassembled the device, replaced the ESP-WROOM-02D module. It did not help. Is there a firmware for the ESP-WROOM-02D module? Thanks

### Entity attributes / 实体属性

.

**Comment by al-one** [comment]
I have no idea.
