### ISSUE TITLE
小厨宝显示设定温度和实体内不一致

### ISSUE THREAD

**Issue by LUOZEYUE** [al-one/hass-xiaomi-miot#935]
### Device model / 设备型号

[zimi.waterheater.h03](https://home.miot-spec.com/s/zimi.waterheater.h03)

### Component version / 插件版本

0.7.2

### HA core version / HA版本

 2022.12.0

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

1，小厨宝显示设定温度和实体内不一致，实体内显示设定温度为25，米家内为中档，看了是可以到60度
2，homebridge到homekit里，开关和温度调节是分开的，会导致温度那个显示一直开着的。
3，很多专业术语不会，希望大佬能看懂。

### Entity attributes / 实体属性

water_heater.zimi_h03_cc9f_water_heater
switch.zimi_h03_cc9f_switch_status

**Comment by al-one** [comment]
> 1，小厨宝显示设定温度和实体内不一致，实体内显示设定温度为25，米家内为中档，看了是可以到60度

请提供实体属性，而不是实体ID。

> 2，homebridge到homekit里，开关和温度调节是分开的，会导致温度那个显示一直开着的。

本插件只能保证设备正常接入HA，无法完全兼容Homekit。

**Comment by LUOZEYUE** [comment]
min_temp: 25
max_temp: 75
operation_list: Low, Medium, High
current_temperature: 25
temperature: 60
target_temp_high: 75
target_temp_low: 25
operation_mode: Medium
model: zimi.waterheater.h03
lan_ip: 192.168.31.83
mac_address: 68:AB:BC:B7:CC:9F
entity_class: MiotWaterHeaterEntity
home_room: 我爱我家 厨卫
miot_type: urn:miot-spec-v2:device:water-heater:0000A02A:zimi-h03:1
water_heater.fault: 0
water_heater.target_temperature: 60
water_heater.temperature: 25
water_heater.mode: 2
water_heater.on: false
factory_test.factory_water_temp: 00000000
custom_function.heat_timer: 
custom_function.push_degerming: -1
switch_degerming-3-8: true
custom_function.switch_freeze: true
custom_function.sterilization.error: -704220043 Property value error
custom_function.heater_status: 0
custom_function.in_cloud_timer: true
state_updater: cloud
sub_entities: water_heater-2.on-6
icon: mdi:fire
friendly_name: 小厨宝
supported_features: 3


entity_class: MiotSwitchSubEntity
parent_entity_id: water_heater.zimi_h03_cc9f_water_heater
service_description: Water Heater
property_description: Switch Status
water_heater.on: false
icon: mdi:power
friendly_name: 小厨宝开关
supported_features: 0

**Comment by LUOZEYUE** [comment]
temperature: 60，这个是我手动调到60的

**Comment by al-one** [comment]
```yaml
current_temperature: 25
temperature: 60
operation_mode: Medium
water_heater.target_temperature: 60
water_heater.temperature: 25
```

根据实体属性显示，当前温度为25，目标温度为60，中档，没看出有什么问题。
