### ISSUE TITLE
[Feature] Easy way to export and import customisations for devices?

### ISSUE THREAD

**Issue by blakadder** [al-one/hass-xiaomi-miot#937]
I have a few integrated devices that required custom entities which is done through the UI. Since I didn't use the yaml way there is no yaml to share the customization for other users.

It would be handy if there were a way to export/import entire device customization so other users can easier integrate theirs. 

Currently it seems it is required to document the UI process (most like screenshots or screencaps) then the user has to repeat it to replicate the integration.

**Comment by al-one** [comment]
If your customization is suitable for most users, we welcome you to [submit a PR](https://github.com/al-one/hass-xiaomi-miot/edit/master/custom_components/xiaomi_miot/core/device_customizes.py) to preset it into the component.

**Comment by blakadder** [comment]
Yes ofcourse but some devices can have different ways of integration depending on the user and/or uses and cannot be shared easily unless it was done in yaml
