### ISSUE TITLE
升级至0.7.3版本后地暖实例的某些属性被默认排除了(exclude_miot_services)

### ISSUE THREAD

**Issue by keniji** [al-one/hass-xiaomi-miot#940]
### Device model / 设备型号

cubee.airrtc.th123e

### Component version / 插件版本

0.7.3

### HA core version / HA版本

2022.12.6

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

我将插件升级从`0.7.2`至`0.7.3`后，插件生成的地暖实体默认加入了`exclude_miot_services: heatold`属性，同时以下属性被移除了：
```
heatold.childlock
heatold.sensortype
heatold.tempactivate
heatold.tempcomp
heatold.tempfloor
heatold.maxsettemp
heatold.minsettemp
```
因为其中的`heatold.tempfloor`属性还是挺重要的（埋在地下的外置温度感应），所以我参考 [通过UI管理自定义选项](https://github.com/al-one/hass-xiaomi-miot/issues/600#top) 尝试了将`exclude_miot_services: heatold`置空、改为`null`等操作，但均无法让插件将相关属性添加进来，请问这个有什么解决办法吗？谢谢！

### Entity attributes / 实体属性

null

### Home Assistant Logs / 系统日志

null

**Comment by keniji** [comment]
还有一个挺奇怪的情况，我一个生产环境和一个测试环境，都退回到`0.7.2`版本，同样是删除了原有设备和实体，同样在`设备连接模式`中选择了`Automatic (自动模式)`。在生产环境中重新添加实体后是`lan`模式；而在测试环境中重新添加实体后是`cloud`模式。

**Comment by al-one** [comment]
已在最近的提交 https://github.com/al-one/hass-xiaomi-miot/commit/e7a498b888fa3f3b1b6bf529b1c97ba60acc083a 中优化，请更新至master分支。

**Comment by keniji** [comment]
感谢, 修复的速度比提问的还快 🤣🤣🤣

**Comment by keniji** [comment]
Hello，今天更新了`0.7.4`后发现`exclude_miot_services`的问题变成了`exclude_miot_properties`的问题，然后其中一个重要的属性`tempfloor`还是被排除了，更新了`master`分支后情况还是一样：
![image](https://user-images.githubusercontent.com/42759206/209747253-0c54a8ea-34b4-4572-9091-dd74530302ab.png)
所以我又尝试通过 [通过UI管理自定义选项](https://github.com/al-one/hass-xiaomi-miot/issues/600#top) 覆盖设置：
![image](https://user-images.githubusercontent.com/42759206/209745938-2a7cf7b2-7dca-4a41-8486-794bfa3d36a4.png)
重启了HASS，但是设置似乎不生效…然后我删掉了前面的设置又手动在customize里加入了`exclude_miot_properties: fault`，再次重启HASS后在实体属性中确认到配置”似乎“apply上去了，但是实体中还是未发现`tempfloor`属性：
![image](https://user-images.githubusercontent.com/42759206/209746916-1220e9e2-71c1-48bd-823d-950eaca3f719.png)
请问这个`exclude_miot_xxx`的问题有其他办法解决吗？谢谢~

**Comment by al-one** [comment]
已恢复`tempfloor`属性。
