### ISSUE TITLE
米家智能驱蚊器2指示灯实体操作逻辑和实际表现相反

### ISSUE THREAD

**Issue by mentalfl0w** [al-one/hass-xiaomi-miot#942]
### Device model / 设备型号

[zimi.mosq.v2](https://home.miot-spec.com/s/zimi.mosq.v2)

### Component version / 插件版本

0.7.3

### HA core version / HA版本

2022.12.7

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

米家智能驱蚊器2指示灯实体在Home Assistant里显示打开，实际上指示灯是关闭的；在HA里关闭后，实际上指示灯是打开的。总而言之，指示灯实体的操作逻辑和实际表现是反的。

### Entity attributes / 实体属性

```
supported_color_modes: onoff
light_indicator.on: false
light_indicator.start_time: 60
light_indicator.end_time: 0
friendly_name: Mi Smart Mosquito Repeller 2 light-indicator
supported_features: 0
```
<img width="934" alt="image" src="https://user-images.githubusercontent.com/30333935/208437844-c6b8d31a-a138-4233-811e-5c816136c2be.png">

### Home Assistant Logs / 系统日志

无

**Comment by al-one** [comment]
尝试更新至master分支。

**Comment by mentalfl0w** [comment]
> 尝试更新至master分支。

切换后灯常亮，开关一直显示打开，无法关闭，HA里点击关闭后一会儿会自动打开，设备的灯一直是亮的

**Comment by al-one** [comment]
实体属性

**Comment by mentalfl0w** [comment]
> 实体属性

<img width="980" alt="image" src="https://user-images.githubusercontent.com/30333935/208823898-b512967d-bef2-4ef9-9715-4cc3f1c2d807.png">
```
supported_color_modes: onoff
light_indicator.on: true
light_indicator.start_time: 60
light_indicator.end_time: 0
friendly_name: Mi Smart Mosquito Repeller 2 light-indicator
supported_features: 0
color_mode: onoff
```

**Comment by al-one** [comment]
请将此设备通过米家共享给我：`143050915`

**Comment by mentalfl0w** [comment]
> 请将此设备通过米家共享给我：`143050915`

好的，已经共享啦

**Comment by al-one** [comment]
该设备的指示灯实体已有`light`切换为`switch`，请更新值master再试。

**Comment by mentalfl0w** [comment]
> 该设备的指示灯实体已有`light`切换为`switch`，请更新值master再试。

测试已正常，谢谢！😊
