### ISSUE TITLE
yuemee.airmonitor.mhfd1霍尼韦尔甲醛传感器(JQJCY01YM ）甲醛值能否接入homekit平台

### ISSUE THREAD

**Issue by QiuYueBaiJXW** [al-one/hass-xiaomi-miot#945]
[yuemee.airmonitor.mhfd1](https://home.miot-spec.com/s/yuemee.airmonitor.mhfd1)(cloud)  霍尼韦尔甲醛传感器(JQJCY01YM 小米商城卖的那款)
cloud状态是从开发者工具选择实体后看state_updater: cloud确认到的, 是这样操作的吗?
关于霍尼韦尔甲醛传感器, Miot Auto识别了电池, 温度, 环境(默认值是湿度), 但是甲醛值不是单独一个实体,在环境实体的属性中, 可以看到甲醛值(environment.hcho_density), 目前临时用template sensor来读取这个属性, 已反馈大佬.
_Originally posted by @uleatest in https://github.com/al-one/hass-xiaomi-miot/issues/12#issuecomment-992045128_

大佬们请问这款甲醛值在ha里面能看见，但是homekit里面没有，有没有什么办法可以接入到hk里去？

**Comment by al-one** [comment]
请提供完整的[实体属性](https://my.home-assistant.io/redirect/developer_states)。

**Comment by QiuYueBaiJXW** [comment]
Entity class
MiotSensorSubEntity
Parent entity ID
sensor.yuemee_mhfd1_a8b4_environment
Service description
Environment
Property description
HCHO Density
Updated time
2022年12月21日 14:28:21
Environment.hcho density
0.17
Battery level
26

**Comment by al-one** [comment]
截止目前，最新的HA版本(2022.12)仍不支持将甲醛传感器接入HomeKit。

Component | Type Name | Description
-- | -- | --
sensor | TemperatureSensor | All sensors that have °C or °F as their unit_of_measurement and temperature as their device_class.
sensor | HumiditySensor | All sensors that have % as their unit_of_measurement and humidity as their device_class.
sensor | AirQualitySensor | All sensors that have gas/pm10/pm25 as part of their entity_id or gas/pm10/pm25/nitrogen_dioxide/volatile_organic_compounds as their device_class
sensor | CarbonMonoxideSensor | All sensors that have co as their device_class
sensor | CarbonDioxideSensor | All sensors that have co2 as part of their entity_id or co2 as their device_class
sensor | LightSensor | All sensors that have lm or lx as their unit_of_measurement or illuminance as their device_class

- https://www.home-assistant.io/integrations/homekit#supported-components
- https://developers.home-assistant.io/docs/core/entity/sensor#available-device-classes
