### ISSUE TITLE
How to set up the feed supply on the Nutri Vision Mini skyrc.feeder.vdfeed?

### ISSUE THREAD

**Issue by DivanX10** [al-one/hass-xiaomi-miot#952]
Nutri Vision Mini was added to Xiaomi Mi Auto without any problems. The feed supply works, but the dose is very small. How can I set it up so that a large dose of feed is fed when turned on?

Home Assistant 2022.12.8
Supervisor 2022.11.2
Operating System 9.4
Frontend 20221213.1 - latest
Integration: Xiaomi Miot Auto v0.7.4 - 2022-12-22
NAME:     Nutri Vision Mini
MODEL:    skyrc.feeder.vdfeed
https://home.miot-spec.com/s/skyrc.feeder.vdfeed

![image](https://user-images.githubusercontent.com/64090632/209406816-9728b355-d25b-48e9-89e1-0eb3ad9e96a8.png)
![image](https://user-images.githubusercontent.com/64090632/209406885-efbb83af-64b0-4638-a40f-c15b47087696.png)
![image](https://user-images.githubusercontent.com/64090632/209406913-9aba75dc-beb5-42a2-962c-88f5f662b1bb.png)
![image](https://user-images.githubusercontent.com/64090632/209406970-40e5dedf-7fe0-4ef1-b7a1-7b92198f902d.png)

**Comment by DivanX10** [comment]
> Try configuration:
> 
> ```yaml
> # configuration.yaml
> xiaomi_miot:
>   device_customizes:
>     skyrc.feeder.vdfeed:
>       feeding_measure: 5
> ```

Thanks, it works. Tell me, do you know if it is possible to take out the camera? If so, how do I do it?

**Comment by al-one** [comment]
> do you know if it is possible to take out the camera? If so, how do I do it?

Sorry i don't know.

**Comment by DivanX10** [comment]
Thanks. One more time. Then I will close the topic, and if someone sees this topic and knows how to do it, he can always add his answer if desired.
