### ISSUE TITLE
不知道什么时候起yeelight的灯都不可用了

### ISSUE THREAD

**Issue by anschein** [al-one/hass-xiaomi-miot#953]
### Device model / 设备型号

yeelight

### Component version / 插件版本

0.7.4

### HA core version / HA版本

2022.12.8

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

所有yeelight的灯的实体都不可用了

### Entity attributes / 实体属性

min_color_temp_kelvin: 2702
max_color_temp_kelvin: 6493
min_mireds: 154
max_mireds: 370
effect_list:
  - Day
  - Night
supported_color_modes:
  - brightness
  - color_temp
  - onoff
friendly_name: 主卧顶灯 Light
supported_features: 39

### Home Assistant Logs / 系统日志

书房顶灯(yeelink.light.ceiling14): Got MiioException while fetching the state: Unable to discover the device 192.168.5.188, mapping: {'light.on': {'siid': 2, 'piid': 1}, 'light.brightness': {'siid': 2, 'piid': 2}, 'light.color_temperature': {'siid': 2, 'piid': 3}, 'light.mode': {'siid': 2, 'piid': 4}, 'light.off_delay_time': {'siid': 2, 'piid': 102}, 'adjust_brightness-3-1': {'siid': 3, 'piid': 1}, 'light_extension.ct_delta': {'siid': 3, 'piid': 2}}, max_properties: 10/7
客厅顶灯(yeelink.light.ceiling18): Got MiioException while fetching the state: Unable to discover the device 192.168.5.54, mapping: {'light.on': {'siid': 2, 'piid': 1}, 'light.brightness': {'siid': 2, 'piid': 2}, 'light.color_temperature': {'siid': 2, 'piid': 3}, 'light.mode': {'siid': 2, 'piid': 4}, 'light.off_delay_time': {'siid': 2, 'piid': 102}, 'adjust_brightness-3-1': {'siid': 3, 'piid': 1}, 'light_extension.ct_delta': {'siid': 3, 'piid': 2}}, max_properties: 10/7
台灯(yeelink.light.lamp7): Got MiioException while fetching the state: Unable to discover the device 192.168.5.69, mapping: {'light.on': {'siid': 2, 'piid': 1}, 'light.brightness': {'siid': 2, 'piid': 2}, 'light.color_temperature': {'siid': 2, 'piid': 3}, 'adjust_brightness-3-1': {'siid': 3, 'piid': 1}, 'light_extension.ct_delta': {'siid': 3, 'piid': 2}, 'light_extension.ct_adjust_alexa': {'siid': 3, 'piid': 3}, 'bright_with_zero-3-4': {'siid': 3, 'piid': 4}}, max_properties: 10/7
床头灯(yeelink.light.bslamp2): Got MiioException while fetching the state: No response from the device, mapping: {'light.on': {'siid': 2, 'piid': 1}, 'light.brightness': {'siid': 2, 'piid': 2}, 'light.color_temperature': {'siid': 2, 'piid': 3}, 'light.color': {'siid': 2, 'piid': 4}, 'light.mode': {'siid': 2, 'piid': 5}, 'light.saturability': {'siid': 2, 'piid': 6}, 'adjust_brightness-3-1': {'siid': 3, 'piid': 1}, 'light_extension.ct_delta': {'siid': 3, 'piid': 2}, 'light_extension.ct_adjust_alexa': {'siid': 3, 'piid': 3}}, max_properties: 10/9
主卧顶灯(yeelink.light.ceiling13): Got MiioException while fetching the state: No response from the device, mapping: {'light.on': {'siid': 2, 'piid': 1}, 'light.brightness': {'siid': 2, 'piid': 2}, 'light.color_temperature': {'siid': 2, 'piid': 3}, 'light.mode': {'siid': 2, 'piid': 4}, 'light.off_delay_time': {'siid': 2, 'piid': 102}, 'adjust_brightness-3-1': {'siid': 3, 'piid': 1}, 'light_extension.ct_delta': {'siid': 3, 'piid': 2}}, max_properties: 10/7

**Comment by al-one** [comment]
检查设备IP

**Comment by anschein** [comment]
> 检查设备IP

IP都是对的，检查过了，我所有的设备都是分配的静态IP

**Comment by anschein** [comment]
我测试下回退版本看看

**Comment by anschein** [comment]
> 我测试下回退版本看看

测试了下回退也不行，然后开成云端模式可以用，会不会是yeelight的灯现在不能走本地了？

**Comment by al-one** [comment]
如果IP没有问题留给灯强制断电。

- https://github.com/al-one/hass-xiaomi-miot/issues/500#offline

**Comment by anschein** [comment]
感谢，断电后就OK了
