### ISSUE TITLE
How to translate?

### ISSUE THREAD

**Issue by vlad36N** [al-one/hass-xiaomi-miot#954]
Hello, Thank you for integration.

Have:
Devices Mi Robot Vacuum-Mop 2 Lite
MODEL:  ijai.vacuum.v10
Home Assistant 2022.12.8 
Supervisor 2022.11.2 
Operating System 9.4 
Frontend 20221213.1 - latest 

How to translate following:

![vac1](https://user-images.githubusercontent.com/30022288/209437978-f63224bd-1eca-4e64-bd4a-e6f93d36aad2.png)

![vac2](https://user-images.githubusercontent.com/30022288/209437981-dc7b21f5-0a59-476a-aee4-4f9e27589f73.png)

![vac3](https://user-images.githubusercontent.com/30022288/209437982-7f5cbfc9-4905-425d-947b-4fe879a16461.png)

![vac4](https://user-images.githubusercontent.com/30022288/209438128-2c622174-37d9-47f6-a97d-a2885736b081.png)

**Comment by al-one** [comment]
- https://github.com/al-one/hass-xiaomi-miot/issues/842#issuecomment-1275964389
- #405

**Comment by vlad36N** [comment]
I did add following before opening issue:

# configuration.yaml
xiaomi_miot:
  language: ru

No changes. 
Will try to add **translations:**

Thank you.

**Comment by cfilo88** [comment]
> I did add following before opening issue:
> 
> '# configuration.yaml'
> 
> ```yaml
> xiaomi_miot:
>   language: ru
> ```
> 
> No changes. Will try to add **translations:**
> 
> Thank you.
> 
> `translations:` works.
> 
> Thank you. I'll close issue.

Hi! How did you solve it?

**Comment by vlad36N** [comment]
Add to configuration.yaml

xiaomi_miot: !include include/xiaomi.yaml

Add to xiaomi.yaml

  language: ru
  translations:
    # Global dictionary
    '强劲': 'Турбо'
    '标准': 'Стандартный'
    '节能': 'Средний'
    '关': 'Бесшумный'
    '低': 'Низкий'
    '中': 'Средний'
    '高': 'Высокий'
    'Sweep': 'Пылесос'
    'Sweep And Mop': 'Пылесос и влажная уборка'
    'Mop': 'Влажная уборка'
    'Global': 'Авто'
    'Edge': 'Очистка углов'
    'Point': 'Точечная'
    'Remote': 'Дистанционная'
    'Mi Robot Vacuum-Mop 2 Lite Robot Cleaner Режим': 'Режим уборки'
    'Mi Robot Vacuum-Mop 2 Lite Robot Cleaner Sweep Type': 'Вид уборки'
    'Mi Robot Vacuum-Mop 2 Lite sweep water_state': 'Уровень воды'
    'starting': 'Начало уборки'
    'charger disconnected': 'Зарядное устройство отключено'
    'idle': 'Ожидание'
    'remote control active': 'Включено управление через пульт'
    'cleaning': 'Уборка'
    'returning home': 'Возвращение на базу'
    'manual mode': 'Ручной режим'
    'charging': 'Зарядка'
    'charging problem': 'Проблема с зарядкой'
    'paused': 'Пауза'
    'spot cleaning': 'Уборка точки'
    'error': 'Ошибка'
    'shutting down': 'Выключение'
    'updating': 'Обновление'
    'docking': 'Остановка у базы'
    'going to target': 'Направление до точки'
    'zoned cleaning': 'Уборка зоны'
    'segment cleaning': 'Уборка'
    'emptying the bin': 'Очистка бака'
    'charging complete': 'Зарядка завершена'
    'device offline': 'Устройство не в сети'
    'Sweeping and Mopping': 'Пылесосит и моет полы'
