### ISSUE TITLE
Stream loops after about 4 minutes

### ISSUE THREAD

**Issue by thermosiphonas** [al-one/hass-xiaomi-miot#96]
Hi,

First of all, thank you for your awesome work.

I have a Xiaomi Mi Camera (chuangmi.camera.ipc019, device model: mjsxj05cm). I managed to get it integrated in home assistant, everything looks fine except that after 5 minutes the stream loops the last 9 seconds for ever.

The logs I get at the time the stream stops are:

> Logger: libav.tcp
Source: components/stream/worker.py:255
First occurred: 11:11:33 AM (2 occurrences)
Last logged: 11:11:33 AM
Connection to tcp://de06.livestreaming.io.mi.com:443 failed: Connection refused

> Logger: homeassistant.components.stream.worker
Source: components/stream/worker.py:266
Integration: Stream (documentation, issues)
First occurred: 11:11:33 AM (1 occurrences)
Last logged: 11:11:33 AM
Error demuxing stream:

And after a few more minutes I get:

> Logger: homeassistant.components.stream.worker
Source: components/stream/worker.py:131
Integration: Stream (documentation, issues)
First occurred: 11:11:45 AM (7 occurrences)
Last logged: 11:16:18 AM
Error opening stream https://de06.livestreaming.io.mi.com/hlstranscoder/*************1YmNlOTM1ZjdjOGRhY2RhNxgK**********RfXwA_H265transH264/playlist.m3u8

**Comment by thermosiphonas** [comment]
Anyone?

**Comment by barnabyjones** [comment]
I don't know how to fix it, but would love to know how you got it to work? I have the same model and can't even get the stream to start.

**Comment by al-one** [comment]
See https://github.com/al-one/hass-xiaomi-miot/issues/166
