### ISSUE TITLE
Please, add support to "XVV Smart Wifi PTZ Camera (XVV-6620S-Q8)"

### ISSUE THREAD

**Issue by wbrione** [al-one/hass-xiaomi-miot#97]
Device information:

    Name(s) of the device: XVV Smart Wifi PTZ Camera (XVV-6620S-Q8)
    Link: https://fccid.io/2AV39XVV-6620S-Q8

Use miiocli device --ip <ip address> --token <token>.

    Model: xiaovv.camera.xvsnowman
    Hardware version: Linux
    Firmware version: 4.0.9_2512

Additional context

https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:camera:0000A01C:xiaovv-xvsnowman:1

**Comment by al-one** [comment]
This component doesn't support your camera, because it doesn't have `start-hls-stream` or `start-rtsp-stream` in miot-speg.org.

https://github.com/al-one/hass-xiaomi-miot/issues/11#issuecomment-774625999
https://github.com/al-one/hass-xiaomi-miot/issues/11#issuecomment-770642627
https://github.com/al-one/hass-xiaomi-miot/issues/60#issuecomment-819435571
https://github.com/al-one/hass-xiaomi-miot/issues/62#issuecomment-823759494

**Comment by wbrione** [comment]
Ok, but it has the methods "Start P2P Stream" and "Stop P2P Stream", so the lack of support would be in relation to the component "python-miio" ??? I understand that the path would be something similar to what was done in the "videoP2Proxy" project (https://github.com/miguelangel-nubla/videoP2 projectProxy), but this one has been inactive for 3 years.

**Comment by wbrione** [comment]
python3 miottemplate.py print urn\:miot-spec-v2\:device\:camera\:0000A01C\:xiaovv-xvsnowman\:1.json
Device 'urn:miot-spec-v2:device:camera:0000A01C:xiaovv-xvsnowman:1': Camera with 3 services

* Service siid 1: (Device Information): 4 props, 0 actions

        ## Properties ##
                siid 1: piid: 1 (Device Manufacturer): (string, unit: None) (acc: ['read'])
                siid 1: piid: 2 (Device Model): (string, unit: None) (acc: ['read'])
                siid 1: piid: 3 (Serial Number): (string, unit: None) (acc: ['read'])
                siid 1: piid: 4 (Current Firmware Version): (string, unit: None) (acc: ['read'])

* Service siid 2: (Camera Control): 1 props, 0 actions

        ## Properties ##
                siid 2: piid: 1 (Switch Status): (bool, unit: None) (acc: ['read', 'write'])

* Service siid 3: (P2P Stream): 0 props, 2 actions

        ## Actions ##
                siid 3: aiid 1 Start P2P Stream: in: [] -> out: []
                siid 3: aiid 2 Stop Camera Stream: in: [] -> out: []
