### ISSUE TITLE
(zhimi.airp.mb5): Set miot property failed

### ISSUE THREAD

**Issue by buhito81** [al-one/hass-xiaomi-miot#972]
### Device model / 设备型号

[zhimi.airp.mb5](https://home.miot-spec.com/s/zhimi.airp.mb5)

### Component version / 插件版本

0.7.4

### HA core version / HA版本

2022.12.9

### Integrated mode / 集成方式

Cloud (云端模式)

### The problem / 问题详情

This error is thrown several times a day:

Xiaomi Smart Air Purifier 4(zhimi.airp.mb5): Set miot property {'did': '476041252', 'siid': 2, 'piid': 4, 'value': 0} failed, result: {'did': '476041252', 'iid': '0.2.4', 'siid': 2, 'piid': 4, 'code': -704220043, 'exe_time': 0}

### Entity attributes / 实体属性

N/A 

### Home Assistant Logs / 系统日志

See under 'Problem'

**Comment by al-one** [comment]
This device supports integrated in local, it is recommended to use `Automatic mode`.
This error code `-704220043` means `Property value error`, and it is returned by Xiaomi Cloud. I don't know why this error occurs.
