### ISSUE TITLE
camera.chuangmi_ipc009 no picture

### ISSUE THREAD

**Issue by pargit** [al-one/hass-xiaomi-miot#974]
hi,
i have the security 360 camera (detected as camera.chuangmi_ipc009).
i can coltrol the switch but i have no image.
when i try to open the entitie_picture from browser i get error 500 internal error..
from developer:
access_token: 8536b7xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxbf123a2dee61ea
model_name: chuangmi.camera.ipc009
brand: chuangmi
frontend_stream_type: hls
model: chuangmi.camera.ipc009
lan_ip: 192.168.11.89
mac_address: 04:CF:8C:06:72:28
entity_class: MiotCameraEntity
home_room: Pargit's home Balcony
miot_type: urn:miot-spec-v2:device:camera:0000A01C:chuangmi-ipc009:1
camera_control.on: true
camera_control.image_rollover: 0
camera_control.night_shot: 0
camera_control.time_watermark: true
camera_control.wdr_mode: false
glimmer_full_color-2-6: true
camera_control.recording_mode: 3
camera_control.motion_tracking: false
stream_status-3-1: 1
state_updater: cloud
sub_entities: camera_control-2.on-1, motion_event
entity_picture: /api/camera_proxy/camera.chuangmi_ipc009_7228_camera_control?token=8536b7xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxbf123a2dee61ea
friendly_name: Mi Home Security Camera 360° 1080P Camera Control
supported_features: 3

what am i missing?
thanks

**Comment by al-one** [comment]
Can not support.
