### ISSUE TITLE
Request to add support for leshi.light.wy0b01

### ISSUE THREAD

**Issue by limeh** [al-one/hass-xiaomi-miot#98]
Need to use this for LAN only, currently not able to detect.

Got MiioException while fetching the state for leshi light: Unable to discover the device 192.168.3.103, mapping: {'light.on': {'siid': 2, 'piid': 1}, 'light.brightness': {'siid': 2, 'piid': 2}, 'light.color_temperature': {'siid': 2, 'piid': 3}, 'light.mode': {'siid': 2, 'piid': 5}, 'remote.remote_switch': {'siid': 8, 'piid': 1}, 'remote.remote_add': {'siid': 8, 'piid': 2}, 'remote.remote_del': {'siid': 8, 'piid': 3}, 'remote.remote_ltype': {'siid': 8, 'piid': 4}, 'remote.remote_htype': {'siid': 8, 'piid': 5}, 'remote.remote_a': {'siid': 8, 'piid': 6}, 'remote.remote_b': {'siid': 8, 'piid': 7}, 'remote.remote_c': {'siid': 8, 'piid': 8}, 'remote.remote_d': {'siid': 8, 'piid': 9}, 'remote.remote_e': {'siid': 8, 'piid': 10}, 'remote.remote_f': {'siid': 8, 'piid': 11}, 'remote.remote_g': {'siid': 8, 'piid': 12}, 'remote.remote_h': {'siid': 8, 'piid': 13}, 'default': {'siid': 4, 'piid': 1}, 'default.user_save': {'siid': 4, 'piid': 2}, 'default.dimming': {'siid': 4, 'piid': 3}, 'default.inteligent_switch': {'siid': 4, 'piid': 4}, 'default.night_switch': {'siid': 4, 'piid': 5}, 'default.delay': {'siid': 4, 'piid': 6}, 'scene.on_off': {'siid': 3, 'piid': 1}, 'scene.brightness_add': {'siid': 3, 'piid': 2}, 'scene.brightness_dec': {'siid': 3, 'piid': 3}, 'scene.brightness_switch': {'siid': 3, 'piid': 4}, 'scene.on_or_brightness': {'siid': 3, 'piid': 5}, 'scene.colortemperature_add': {'siid': 3, 'piid': 6}, 'scene.colortemperature_dec': {'siid': 3, 'piid': 7}, 'scene.colortemperature_sw': {'siid': 3, 'piid': 8}, 'scene.on_or_colortemp': {'siid': 3, 'piid': 9}}

**Comment by al-one** [comment]
Please check the network between your device and HA.
