### ISSUE TITLE
梦幻帘电机接入ha后，无法正常操作

### ISSUE THREAD

**Issue by ttsgit** [al-one/hass-xiaomi-miot#982]
### Device model / 设备型号

[novo.curtain.n21](https://home.miot-spec.com/s/novo.curtain.n21)

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

窗帘电机无法正常工作，点击开或者关，会自动停止

## cover.novo_n21_4540_curtain
current_position: 27
model: novo.curtain.n21  
miot_type: urn:miot-spec-v2:device:curtain:0000A00C:novo-n21:1 
curtain.fault: 0 
curtain.motor_control.error: -4004 Other internal errors 
curtain.current_position: 27 
curtain.target_position.error: -4004 Other internal errors 
curtain.motor_reverse: false 
state_updater: lan device_class: curtain 
friendly_name: NOVO智能窗帘电机西 Curtain supported_features: 15 sub_entities: curtain-2.motor_control-2 curtain.target_position: 52

## select.novo_n21_4540_motor_control
options: Pause, Close, Open
entity_class: MiotSelectSubEntity
parent_entity_id: cover.novo_n21_4540_curtain
service_description: Curtain
property_description: Motor Control
friendly_name: NOVO智能窗帘电机西 Curtain Motor Control
supported_features: 0

### Home Assistant Logs / 系统日志

NOVO智能窗帘电机东(novo.curtain.n21): Got MiioException while fetching the state: Unable to parse message payload, mapping: {'curtain.fault': {'siid': 2, 'piid': 1}, 'curtain.motor_control': {'siid': 2, 'piid': 2}, 'curtain.current_position': {'siid': 2, 'piid': 6}, 'curtain.target_position': {'siid': 2, 'piid': 7}, 'curtain.motor_reverse': {'siid': 2, 'piid': 8}}, max_properties: 8/5

**Comment by al-one** [comment]
- 尝试给设备断电后重试
- 尝试在米家重新绑定该设备
- 给该设备[添加自定义选项](https://github.com/al-one/hass-xiaomi-miot/issues/600)`chunk_properties: 1`

**Comment by ttsgit** [comment]
> * 尝试给设备断电后重试
> * 尝试在米家重新绑定该设备
> * 给该设备[添加自定义选项](https://github.com/al-one/hass-xiaomi-miot/issues/600)`chunk_properties: 1`

感谢及时回复，已经解决。
另外想问下开合角度是否也能通过自定义属性里配置显示和调整

**Comment by al-one** [comment]
角度可以通过cover实体弹出卡片的滑竿来控制。

**Comment by Meo1991** [comment]
> 
请教一下是怎么解决的。。。我在HA里还是不能控制

**Comment by Larrycal** [comment]
> > * 尝试给设备断电后重试
> > * 尝试在米家重新绑定该设备
> > * 给该设备[添加自定义选项](https://github.com/al-one/hass-xiaomi-miot/issues/600)`chunk_properties: 1`
> 
> 我的问题是窗帘会在 ha 中显示不可用，同时红外遥控器工作也不正常：无法正常关闭，开合也不正确。 通过设置 `chunk_properties` 为 `1` 后解决。

请教一下梦幻帘电机有在 homekit 中使用吗？我在 ha 中一个实体可以控制开合和角度，但是在homekit 家庭中显示成了一个窗帘和 3 个插座.

**Comment by ttsgit** [comment]
> > > * 尝试给设备断电后重试
> > > * 尝试在米家重新绑定该设备
> > > * 给该设备[添加自定义选项](https://github.com/al-one/hass-xiaomi-miot/issues/600)`chunk_properties: 1`
> > 
> > 
> > 我的问题是窗帘会在 ha 中显示不可用，同时红外遥控器工作也不正常：无法正常关闭，开合也不正确。 通过设置 `chunk_properties` 为 `1` 后解决。
> 
> 请教一下梦幻帘电机有在 homekit 中使用吗？我在 ha 中一个实体可以控制开合和角度，但是在homekit 家庭中显示成了一个窗帘和 3 个插座.

homekit上我也是一样，显示的窗帘只能调节角度，三个插座分别是开、暂停、关。

**Comment by Larrycal** [comment]
> > > > * 尝试给设备断电后重试
> > > > * 尝试在米家重新绑定该设备
> > > > * 给该设备[添加自定义选项](https://github.com/al-one/hass-xiaomi-miot/issues/600)`chunk_properties: 1`
> > > 
> > > 
> > > 我的问题是窗帘会在 ha 中显示不可用，同时红外遥控器工作也不正常：无法正常关闭，开合也不正确。 通过设置 `chunk_properties` 为 `1` 后解决。
> > 
> > 
> > 请教一下梦幻帘电机有在 homekit 中使用吗？我在 ha 中一个实体可以控制开合和角度，但是在homekit 家庭中显示成了一个窗帘和 3 个插座.
> 
> homekit上我也是一样，显示的窗帘只能调节角度，三个插座分别是开、暂停、关。

是的，请问有啥比较好的使用方式吗？我用 Siri 控制梦幻窗帘，识别的都是控制角度，没办法开合

**Comment by blackwing8121** [comment]
> > > > > * 尝试给设备断电后重试
> > > > > * 尝试在米家重新绑定该设备
> > > > > * 给该设备[添加自定义选项](https://github.com/al-one/hass-xiaomi-miot/issues/600)`chunk_properties: 1`
> > > > 
> > > > 
> > > > 我的问题是窗帘会在 ha 中显示不可用，同时红外遥控器工作也不正常：无法正常关闭，开合也不正确。 通过设置 `chunk_properties` 为 `1` 后解决。
> > > 
> > > 
> > > 请教一下梦幻帘电机有在 homekit 中使用吗？我在 ha 中一个实体可以控制开合和角度，但是在homekit 家庭中显示成了一个窗帘和 3 个插座.
> > 
> > 
> > homekit上我也是一样，显示的窗帘只能调节角度，三个插座分别是开、暂停、关。
> 
> 是的，请问有啥比较好的使用方式吗？我用 Siri 控制梦幻窗帘，识别的都是控制角度，没办法开合

我遇到的也是同样的问题，在HASS里可以切换，但在homekit里就没有了，只能旋转，不能开合

**Comment by ttsgit** [comment]
> > > > > > * 尝试给设备断电后重试
> > > > > > * 尝试在米家重新绑定该设备
> > > > > > * 给该设备[添加自定义选项](https://github.com/al-one/hass-xiaomi-miot/issues/600)`chunk_properties: 1`
> > > > > 
> > > > > 
> > > > > 我的问题是窗帘会在 ha 中显示不可用，同时红外遥控器工作也不正常：无法正常关闭，开合也不正确。 通过设置 `chunk_properties` 为 `1` 后解决。
> > > > 
> > > > 
> > > > 请教一下梦幻帘电机有在 homekit 中使用吗？我在 ha 中一个实体可以控制开合和角度，但是在homekit 家庭中显示成了一个窗帘和 3 个插座.
> > > 
> > > 
> > > homekit上我也是一样，显示的窗帘只能调节角度，三个插座分别是开、暂停、关。
> > 
> > 
> > 是的，请问有啥比较好的使用方式吗？我用 Siri 控制梦幻窗帘，识别的都是控制角度，没办法开合
> 
> 我遇到的也是同样的问题，在HASS里可以切换，但在homekit里就没有了，只能旋转，不能开合

目前将就下就是在homekit中设置一个自动化，比如名字叫开窗帘，然后执行梦幻帘的打开，关闭如是，然后siri就能识别你的自动化名称执行相应动作
