### ISSUE TITLE
No information about connectivity issues when hub offline

### ISSUE THREAD

**Issue by Oliviakrkk** [al-one/hass-xiaomi-miot#984]
Hi, 

I have added Aqara E1 hub with entities using the cloud integration.  For a test I disconnected the HUB from power source. 
In MiHome app all devices are offline:

![Screenshot_20230108-183811](https://user-images.githubusercontent.com/43586519/211210687-5f9794ac-3651-4a44-8423-17d3ce3847a4.jpg)

Is there a way to detect that in Home assistant? I want to alert on such situations.

All entities in HA are shown normalny as if there were online:
<img width="516" alt="image" src="https://user-images.githubusercontent.com/43586519/211210749-ff975b0b-ed28-42db-8f50-9b35c159ffc7.png">

**Comment by al-one** [comment]
Xiaomi cloud server has cached device data. For Wi-Fi devices, you can customize `check_lan: true`. For ZigBee devices, there is nothing i can do.
