### ISSUE TITLE
define Humidity and temperature as long term sensors.

### ISSUE THREAD

**Issue by tsvikas** [al-one/hass-xiaomi-miot#989]
### Device model / 设备型号

Xiaomi Smart Humidifier 2 (humidifier.deerma_jsq2w_0673_humidifier)

### Component version / 插件版本

0.7.5

### HA core version / HA版本

2023.1.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

I can't add the temperature and humidity from my humidifier to a statistics graph card configuration this is useful to see trends over long time.

to recreate this: 
Edit Dashboard > Add Card > Statistics Graph, 
and try to input the humidity entity in in the Statistics field

According to HASS, Integrations need to configure their entities correctly so Home Assistant knows that we need to track statistics for it and how.

see https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics.
it seems like a simple configuration: the sensor should have `state_class` set to `measurement`

### Entity attributes / 实体属性

entity_class: MiotSensorSubEntity
parent_entity_id: humidifier.deerma_jsq2w_0673_humidifier
service_description: Environment
property_description: Relative Humidity
updated_time: 2023-01-12T13:11:40.597780+02:00
environment.relative_humidity: 55
unit_of_measurement: %
device_class: humidity
friendly_name: Xiaomi Smart Humidifier 2 Environment Relative Humidity
supported_features: 0

**Comment by al-one** [comment]
Try master branch.
