### ISSUE TITLE
zhimi.fan.za4

### ISSUE THREAD

**Issue by kyo66666** [al-one/hass-xiaomi-miot#99]
Logger: custom_components.xiaomi_miot
Source: custom_components/xiaomi_miot/__init__.py:787
Integration: Xiaomi Miot Auto (documentation, issues)
First occurred: 15:39:52 (47 occurrences)
Last logged: 16:02:52

Got MiioException while fetching the state for Stand Fan 2S Fan: {'code': -9999, 'message': 'user ack timeout'}, mapping: {'fan.on': {'siid': 2, 'piid': 1}, 'fan.fan_level': {'siid': 2, 'piid': 2}, 'fan.horizontal_swing': {'siid': 2, 'piid': 3}, 'fan.horizontal_angle': {'siid': 2, 'piid': 4}, 'fan.mode': {'siid': 2, 'piid': 5}, 'indicator_light.on': {'siid': 5, 'piid': 1}, 'alarm': {'siid': 4, 'piid': 1}, 'physical_controls_locked': {'siid': 3, 'piid': 1}}

**Comment by al-one** [comment]
You need enable miot_cloud or `Add devices using Mi Account`.

> [⚙️ Configuration](https://my.home-assistant.io/redirect/config) > [🧩 Integrations](https://my.home-assistant.io/redirect/integrations) > Xiaomi Miot Auto > Options > ☑️ Enable miot cloud
