### ISSUE TITLE
小愛音箱AI增強版 的ringtone Unavailable

### ISSUE THREAD

**Issue by kei81131** [al-one/hass-xiaomi-miot#994]
小愛音箱AI增強版 [miot-spec](https://home.miot-spec.com/spec/xiaomi.wifispeaker.l05c) 內clock - ringtone是支持的, 
但無法調用, 都是Unavailable (已試過 button/number/select properties 都不行)

請幫忙看看, 謝謝

------

### Device model / 设备型号

[xiaomi.wifispeaker.l05c](https://home.miot-spec.com/s/xiaomi.wifispeaker.l05c)

### Component version / 插件版本
v0.6.12

### HA core version / HA版本
2022.12.2

### Integrated mode / 集成方式
local

### Entity attributes / 实体属性
volume_level: 0.1
is_volume_muted: true
model: xiaomi.wifispeaker.l05c
lan_ip: 192.168.31.78
mac_address: 24:CF:24:2D:69:5D
entity_class: MiotMediaPlayerEntity
home_room: Lung的家 大門
miot_type: urn:miot-spec-v2:device:speaker:0000A015:xiaomi-l05c:1
attribution: Support TTS through service
play_control.playing_state: 0
play_control.play_loop_mode.error: -4003 Property/Action/Event does not exist
clock.on.error: -4003 Property/Action/Event does not exist
clock.status.error: -4003 Property/Action/Event does not exist
clock.fault.error: -4003 Property/Action/Event does not exist
clock.ringtone.error: -4003 Property/Action/Event does not exist
microphone.mute: false
speaker.volume: 10
speaker.mute: true
state_updater: lan
sub_entities: speaker-2.volume-1, clock-6.ringtone-4, intelligent_speaker-5.wake_up-1, intelligent_speaker-5.play_music-5, clock-6.stop_alarm-1
miot_action_result: 
code: 0
out: []

device_class: speaker
friendly_name: Mi AI Speaker Play Plus Play Control
supported_features: 21565

### Home Assistant Logs / 系统日志

[home-assistant_2023-01-14T06-43-41.136Z.log](https://github.com/al-one/hass-xiaomi-miot/files/10416807/home-assistant_2023-01-14T06-43-41.136Z.log)

**Comment by al-one** [comment]
请按上方格式重新编辑issue。

**Comment by kei81131** [comment]
已更新, 謝謝

**Comment by al-one** [comment]
小爱音箱不支持本地接入，请通过账号(自动模式)接入。

**Comment by kei81131** [comment]
已更改為cloud 接入
但 ringtone 依舊無法調用

另外，play_text, execute_text_directive
也是無法調用

請幫忙看看，謝謝🙏🏻

volume_level: 0.1
is_volume_muted: true
media_content_id: '1674542552160717800'
media_content_type: MUSIC
media_duration: 269
media_position: 216
media_title: 耿
media_artist: 汪苏泷
media_album_name: 耿
repeat: all
model: xiaomi.wifispeaker.l05c
lan_ip: 192.168.31.78
mac_address: 24:CF:24:2D:69:5D
entity_class: MiotMediaPlayerEntity
home_room: Lung的家 大門
miot_type: urn:miot-spec-v2:device:speaker:0000A015:xiaomi-l05c:1
attribution: Support TTS through service
play_control.playing_state.error: '-704220043 Property value error'
play_control.play_loop_mode.error: '-704220008 Invalid IID (PID, SID, AID, etc.)'
clock.on.error: '-704220008 Invalid IID (PID, SID, AID, etc.)'
clock.status.error: '-704220008 Invalid IID (PID, SID, AID, etc.)'
clock.fault.error: '-704220008 Invalid IID (PID, SID, AID, etc.)'
clock.ringtone.error: '-704220008 Invalid IID (PID, SID, AID, etc.)'
microphone.mute: false
speaker.volume: 10
speaker.mute: true
state_updater: cloud
sub_entities:
  - speaker-2.volume-1
  - clock-6.ringtone-4
  - intelligent_speaker-5.wake_up-1
  - intelligent_speaker-5.play_music-5
  - clock-6.stop_alarm-1
  - conversation
xiaoai_id: af006eab-897b-4351-bc5a-64f8d5d890f7
device_class: speaker
entity_picture: >-
  /api/media_player_proxy/media_player.xiaomi_l05c_695d_play_control?token=8f489acd09de16c932de5654c1c2fe912d8d39de84816f066a305f3f1d33f96d&cache=49345f983637e0ac
friendly_name: Mi AI Speaker Play Plus Play Control
supported_features: 21565

**Comment by kei81131** [comment]
剛更新版本v0.7.5
Play text 及 execute text directive 都能正常使用，先感謝一下大佬🙏🏻

但ringtone 依舊無法調用

**Comment by al-one** [comment]
```yaml
clock.ringtone.error: '-704220008 Invalid IID (PID, SID, AID, etc.)'
```
There is an error from Xiaomi cloud API.

**Comment by kei81131** [comment]
了解，謝謝🙏🏻
