### ISSUE TITLE
LOG gets flooded with entries from integration

### ISSUE THREAD

**Issue by sezlony** [al-one/hass-xiaomi-miot#995]
I'm using an IMILAB EC2 outdoor wifi camera through MIoT integration and since recent updates the LOG is full of entries like this:

`...indoor receiver camera control became unavailable`
`...EC2 camera control became unavailable`
`...indoor receiver camera control switch status became unavailable`
`...EC2 camera motion camera control switch status became unavailable`

and then 1-2 mins later:
`...EC2 camera motion detection turned to true`
`...EC2 camera control switch status turned on`
`...EC2 camera control changed to idle`
`...indoor receiver camera control switch status turned on`
`...indoor receiver camera control switch turned to idle`

this goes in and endless cycle all through the day

it's like the integration or something constantly turns off and on the outdoor camera
![kép](https://user-images.githubusercontent.com/101760883/212291022-e3e83ded-af82-43d3-b9c9-0f96c8a40b73.png)

what the heck is this? is it a FW bug or a bug in the MIoT integration?

**Comment by al-one** [comment]
Show me [logs](https://my.home-assistant.io/redirect/logs).

**Comment by sezlony** [comment]
part of the log, is that's enough?
[log.txt](https://github.com/al-one/hass-xiaomi-miot/files/10417062/log.txt)

**Comment by al-one** [comment]
`2023-01-13 02:03:55.311 WARNING (SyncWorker_8) [custom_components.xiaomi_miot.core.xiaomi_cloud] Request xiaomi api: miotspec/prop/get {'params': [{'did': '512855740', 'siid': 2, 'piid': 1}, {'did': '512855740', 'siid': 2, 'piid': 2}, {'did': '512855740', 'siid': 2, 'piid': 3}, {'did': '512855740', 'siid': 2, 'piid': 4}, {'did': '512855740', 'siid': 2, 'piid': 5}, {'did': '512855740', 'siid': 6, 'piid': 1}, {'did': '512855740', 'siid': 6, 'piid': 2}, {'did': '512855740', 'siid': 4, 'piid': 1}, {'did': '512855740', 'siid': 4, 'piid': 2}, {'did': '512855740', 'siid': 4, 'piid': 3}, {'did': '512855740', 'siid': 4, 'piid': 4}, {'did': '512855740', 'siid': 3, 'piid': 1}, {'did': '512855740', 'siid': 3, 'piid': 2}, {'did': '512855740', 'siid': 3, 'piid': 3}, {'did': '512855740', 'siid': 3, 'piid': 4}, {'did': '512855740', 'siid': 3, 'piid': 5}, {'did': '512855740', 'siid': 3, 'piid': 6}, {'did': '512855740', 'siid': 3, 'piid': 7}, {'did': '512855740', 'siid': 3, 'piid': 8}, {'did': '512855740', 'siid': 8, 'piid': 9}, {'did': '512855740', 'siid': 7, 'piid': 9}, {'did': '512855740', 'siid': 5, 'piid': 1}, {'did': '512855740', 'siid': 5, 'piid': 2}, {'did': '512855740', 'siid': 5, 'piid': 3}]} failed, response: None
2023-01-13 02:03:55.312 WARNING (SyncWorker_5) [custom_components.xiaomi_miot.core.xiaomi_cloud] Request xiaomi api: miotspec/prop/get {'params': [{'did': '1070178529', 'siid': 2, 'piid': 1}, {'did': '1070178529', 'siid': 6, 'piid': 1}, {'did': '1070178529', 'siid': 6, 'piid': 2}, {'did': '1070178529', 'siid': 5, 'piid': 1}, {'did': '1070178529', 'siid': 5, 'piid': 2}, {'did': '1070178529', 'siid': 5, 'piid': 3}, {'did': '1070178529', 'siid': 4, 'piid': 1}, {'did': '1070178529', 'siid': 4, 'piid': 2}, {'did': '1070178529', 'siid': 4, 'piid': 3}, {'did': '1070178529', 'siid': 4, 'piid': 4}, {'did': '1070178529', 'siid': 4, 'piid': 5}, {'did': '1070178529', 'siid': 3, 'piid': 1}, {'did': '1070178529', 'siid': 3, 'piid': 2}, {'did': '1070178529', 'siid': 3, 'piid': 3}, {'did': '1070178529', 'siid': 3, 'piid': 4}, {'did': '1070178529', 'siid': 3, 'piid': 5}]} failed, response: None`

When requesting Xiaomi cloud API, often respond `None`, please check your network. It may also be a problem with the Xiaomi server.

**Comment by sezlony** [comment]
is that a problem of indoor receiver being without internet connection or the portable camera being out of range of the receiver?
